### ISSUE TITLE
Upload a lib, and can be found under personal projects page, but can not searched under PyPi nor installed with pip

### ISSUE THREAD

**Issue by innerNULL** [pypa/warehouse#10000]
Hi I just upload a lib, 
[pyfeather](https://pypi.org/project/pyfeather/)
![image](https://user-images.githubusercontent.com/10429190/132037331-44c4f97b-4659-4d59-8f03-5d5729177f9c.png)
But I can not search it on PyPi, and also can not install it with `pip install pyfeather`.

I tried this:
```python
import requests


requests.post(
    "https://pypi.python.org/pypi",
    data={"action": "purge", "project": "pyfeather"}
)
```
and this
```curl -X PURGE https://pypi.python.org/simple/pyfeather```
But all not work, is there any possible solution?

Here is how I upload my wheels:
```bash
twine upload dist/*-manylinux*.whl
```
and here is my [setup.py](https://github.com/innerNULL/feather/blob/main/setup.py)

THANK U!

**Comment by innerNULL** [comment]
For now I can install with `pip install pyfeather`, but the library still can not be searched on https://pypi.org/

**Comment by di** [comment]
It takes a bit for brand new projects to show up in the search results. It's there now: https://pypi.org/search/?q=pyfeather
