### ISSUE TITLE
Dist upload failing for PyPI (403 error), but was fine for PyPI Test

### ISSUE THREAD

**Issue by mfarragher** [pypa/warehouse#10031]
**Describe the bug**
I am ready to launch a package on PyPI, having done so successfully on PyPI Test in the past few hours, but I cannot upload the package due to a 403 error:

```
twine upload dist/*

...

HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'mfarragher' isn't allowed to upload to project 'obsidian-tools'. See https://pypi.org/help/#project-name for more information.
```

From the link I wondered if the package name was being squatted but I couldn't find the page being in use, therefore I don't have a person to contact or much to say for a PEP 541 request.  As far as I can tell the package name is available, but perhaps there's a block on it being registered? 🤷‍♂️

I have tried different forms of the upload command with no success, different formats of `.pypirc`, entering login details sequentially in terminal, etc.

In search of alternative ways to upload, I did notice a recent unresolved issue on Python 3.9 where I also get the described blake2_256_digest error when I do `python3 setup.py sdist upload`: https://github.com/pypa/distutils/issues/25.  That's not the command I'd expect to do but could be related to my issue.

**Expected behavior**
Expect the wheel to upload successfully on PyPI (like it did for PyPI Test).

**To Reproduce**
As above and below - for system details, commands and package info.

See the upload on PyPI Test for my package with setup.py.  I installed it successfully from that server and the readme renders OK so the code seems fine.

**My Platform**
I have had these issues in fresh Miniconda environments (Python 3.9.6) for these operating systems - with wheels rebuilt on each system - via the command line for commands described above:
- Fedora 34 (GNOME 40)
- Windows 10

**Additional context**
N/A

**Comment by ewjoachim** [comment]
You can make a PEP 541 request (https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME)

The current owner of the package is https://pypi.org/user/sfermigier/ (but since then, they have deleted the project, thus the 404)
