### ISSUE TITLE
pkg-resources returning a 404

### ISSUE THREAD

**Issue by williamtwomey** [pypa/warehouse#10080]
https://pypi.org/simple/pkg-resources/ is currently returning a 404

**Comment by di** [comment]
The `pkg_resources` module is provided by the [`setuptools`](https://pypi.org/p/setuptools) project: https://setuptools.pypa.io/en/latest/pkg_resources.html, it is not installable on it's own.

**Comment by rjmill** [comment]
@di It shows up in the list of packages at https://pypi.org/simple/ .

```console
$ curl -s https://pypi.org/simple/ | grep '/pkg-resources'
    <a href="/simple/pkg-resources/">pkg-resources</a>
```

Is the dead link something clients should expect/handle?

**Comment by di** [comment]
> Is the dead link something clients should expect/handle?

Yes, it happens from time to time when a project is removed or deleted. The cache for th e`/simple` page is not updated as regularly as other pages, it may be several hours behind reality.

What is the "client" in question here?

**Comment by rjmill** [comment]
Thanks for the info!

> What is the "client" in question here?

An old version of virtualenv (15.1.0). Looks like the failure I'm seeing isn't related to the cache mismatch anyway. The cache seems to be caught up now, and I'm still seeing the same issue. 

I'm not seeing this on more recent versions of virtualenv. If anyone else is hitting this with older versions of virtualenv, using `--no-download` seems to be a fine workaround. (Of course, updating virtualenv is a better workaround, but that's not an option for everyone.)

@di Thanks for taking the time to explain. I've got a workaround, and the cache seems to be working as expected. So I'm satisfied. Thanks!

**Comment by di** [comment]
We got a similar report in https://github.com/pypa/warehouse/issues/10081 and it should be resolved now, FYI.
