### ISSUE TITLE
Missing pypi.org/simple/pkg-resources/

### ISSUE THREAD

**Issue by bill-within** [pypa/warehouse#10081]
**Describe the bug**
https://pypi.org/simple/pkg-resources/ is returning a 404 - this package is installed automatically on venv creation, so I'm guessing that a directory was accidentally nuked

virtualenv -p python3 --no-site-packages venv
...
Installing setuptools, pkg_resources, pip, wheel...
...  
Collecting pkg_resources
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/pkg-resources/

**Expected behavior**
200 OK

**To Reproduce**
virtualenv -p python3 --no-site-packages venv

**My Platform**
Debian 10, python 3.7

**Additional context**
My builds are broke :(
Also thank you all for this important python community service!

**Comment by di** [comment]
Can you try again now? Also, what version of `virtualenv` are you using?

**Comment by bill-within** [comment]
Thank you for the quick response @di - preliminary local test lookin' good, will try kicking off a build!

$ virtualenv --version
15.1.0
