### ISSUE TITLE
Threading cannot work properly when argument contain list

### ISSUE THREAD

**Issue by 2541989802** [pypa/warehouse#10086]
**Describe the bug**
Threading cannot work properly when argument contain list. It seems thread accept contents of list as its arguments. This problem show in numpy array too.

**Expected behavior**
I expect the thread will accept a reference point to each list beginner, so that I can use in the function

**To Reproduce**
```
import threading

def temp(l):
    for i in range(3):
        l[i]=l[i]+1

array = [[1,2,3],[4,5,6]]
threads = []
for i in range(2):
    t = array[i]
    threads.append(threading.Thread(target=temp,args=(t)))
for thread in threads:
    thread.start()
for thread in threads:
    thread.join()

print(array)
```

**My Platform**
Windows 10
Python 3.7.3

**Comment by 2541989802** [comment]
It  seem that this problem specifically occur when I put a list from 2D array as args in threading. However temp(array[0]) works for me.

**Comment by ewjoachim** [comment]
Hi, this issue tracker is for issues with the codebase behind [pypi.org](https://pypi.org) itself, not the projects hosted on PyPI, nor for Python itself.

You should report this issue to the tracker for the project in question instead. For Python, this will be on https://bugs.python.org I believe
