### ISSUE TITLE
Allow OS X Wheels

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1009]
We need to allow OS X wheels to be uploaded.

**Comment by njsmith** [comment]
This is somewhat complicated by the fact that there are a *lot* of different valid OS X platform tags.

**Comment by dstufft** [comment]
Here's a snippet that I *think* will generate all possible OS X platform tags:

```python
["_".join(["macosx", v, a]) for v, a in itertools.product(["10_{}".format(i) for i in range(12)], ["ppc", "ppc64", "i386", "x86_64", "fat", "fat32", "fat64", "intel", "universal"])]
```

A downside of this, is that it also generates some *invalid* OS X platform tags. For example, there was no such thing as a ``intel`` or ``i386`` or ``x86_64`` binary on 10.0 (and others). We could just ignore that as a mildly amusing edge case where someone could upload a wheel that doesn't actually make sense and couldn't actually exist in real life (and which pip won't actually use), or we could try to complicate this a lot more and only generate ``ppc`` on 10.0 through to 10.6, ``ppc64`` on 10.5 (and maybe 10.4, though it only partially worked there), ``i386`` on 10.4+, and ``x86_64`` on 10.5+ (maybe 10.4+, but it only partially worked on 10.4). Then we'd also have to allow the multi architecture tags based on what archiectures are contained within them. I'm not sure it's worth it to actually do that though versus just allowing all of the architectures for all of the versions through.

This would also of course bake a maximum OS X version into Warehouse which would need to be bumped whenever OS X releases a new version. This could be a bit annoying, though it might also be a good thing, if they drastically alter something in 10.12 so that we need to hold of on allowing them, that will be baked in right away, but I'm not sure that there is much of a chance of that actually happening. We could work around it by using ``range(99)`` or something, or by adding more runtime logic so that ``macosx`` wheels use something like:

```python
re.match("macosx_10_[0-9]+_(ppc|ppc64|...")
```

Dunno!

**Comment by njsmith** [comment]
The approach currently in #1011 makes the decisions to:
* don't bother trying to restrict to valid (version, architecture) tuples
* do restrict to valid architectures (might at least catch typos like "itnel")
* do use a regexp to allow 10.12, 10.13, etc.

Ideally I guess this code could be shared with pip but meh...

**Comment by xavfernandez** [comment]
> Ideally I guess this code could be shared with pip but meh...

Well, I think pep425 tags implementation will certainly end up in `packaging` package so this could be done :)
