### ISSUE TITLE
PyPI does not recognize README format as Markdown

### ISSUE THREAD

**Issue by skorokithakis** [pypa/warehouse#10114]
I'm trying to upload a package to the PyPI and am getting this error:

```
running upload
Submitting dist/django-loginas-0.3.10.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.
error: Upload failed (400): The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.
```

However, this is my `setup.py`:

```
#!/usr/bin/env python
import sys

from loginas import __version__

assert sys.version >= "3.4", "Requires Python v3.4 or above."

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

setup(
    name="django-loginas",
    version=__version__,
    author="Stochastic Technologies",
    author_email="info@stochastictechnologies.com",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/stochastic-technologies/django-loginas/",
    description="""An app to add a "Log in as user" button in the Django user admin page.""",
    license="BSD",
    keywords="django",
    zip_safe=False,
    include_package_data=True,
    packages=["loginas"],
    package_dir={"loginas": "loginas"},
    python_requires=">3.3",
)
```

The source package seems to include the README file fine:

[django-loginas-0.3.10.tar.gz](https://github.com/pypa/warehouse/files/7258378/django-loginas-0.3.10.tar.gz)

I can't figure out what's going on, am I doing something wrong or is this an ill-phrased error message?

**Comment by ewjoachim** [comment]
You can use `twine check` to run locally the same code as the one that runs on warehouse, which is https://pypi.org/project/readme-renderer/ . This is not a warehouse bug. You'll probably have more success by checking in https://github.com/pypa/readme_renderer/issues.

Now for your specific problem, I'm seeing you mix titles like `Hey\n---` and like `### hey`, but I highly doubt it's the issue. I'm not seeing anything funky from skimming through your readme.

**Comment by skorokithakis** [comment]
Oh hmm, I'll try Twine, thanks!

**Comment by di** [comment]
You didn't mention how you're uploading the distribution, but my guess is that you're using something that predates support for the metadata version that includes markdown READMEs. Using the latest version of [twine](https://pypi.org/project/twine/) should allow the upload to succeed.

**Comment by skorokithakis** [comment]
Ah, that was it, it succeeded, thanks! I was running `python3 setup.py sdist bdist_wheel upload`.
