### ISSUE TITLE
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/ The user 'kosyachniy' isn't allowed to upload to project 'libb'. See https://pypi.org/help/#project-name for more information.

### ISSUE THREAD

**Issue by kosyachniy** [pypa/warehouse#10139]
Describe the bug
Trying to upload via twine. New project. Not registered, but getting this:

HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'kosyachniy' isn't allowed to upload to project 'libb'. See https://pypi.org/help/#project-name for more information.

But there isn't any project with the same name (https://pypi.org/project/libb/)

Expected behavior
Uploads the package

To Reproduce
Try to upload to that project.

My Platform
using git bash

**Comment by yeraydiazdiaz** [comment]
Hello, there is a project with that name but it's got no releases. Please open a [PEP 541 request on pypi-support](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME) if you would like to claim the name.
