### ISSUE TITLE
Images served with Let's Encrypt are not rendering

### ISSUE THREAD

**Issue by mhils** [pypa/warehouse#10171]
Warehouse currently does not render README images if they are served with a Let's Encrypt certificate: https://pypi.org/project/pdoc/ should render https://pdoc.dev/logo.svg (hosted on GitHub pages), which it doesn't.

After looking into this, the root cause seems to be that pypa/warehouse-camo's Docker image is based off node:8.10, which is based off Ubuntu 14.04, which does not have the new Let's Encrypt roots. 🙃

I have bumped node to 16.10 locally, which then works fine. I'll follow up with a commit in the pypa/warehouse-camo repo that addresses this issue, but given that symptom and root cause are a bit distant I figured an issue here would be useful. 😃

**Comment by ewdurbin** [comment]
Thank you for diving deep and getting this all fixed! Should be good to go in production now!

**Comment by mhils** [comment]
Fantastic, thanks for the super fast fix! 🍰
