### ISSUE TITLE
Fix static dist

### ISSUE THREAD

**Issue by demianbrecht** [pypa/warehouse#1018]
I haven't looked into this at all yet so I'm not sure what the cause is, but seems like hashes are appended to static dist files on every static build, so you end up with something like this:

```
plugins.js.02f2416d.02f2416d.02f2416d.02f2416d.map
plugins.js.02f2416d.02f2416d.02f2416d.map
plugins.js.02f2416d.02f2416d.map
plugins.js.02f2416d.map
plugins.js.map
```

After enough runs, `COPY`ing the static dir to /app/ fails due to filename lengths.

**Comment by dstufft** [comment]
I think if you delete your static dist directory once, this problem should go away. It happens because the location of map files changed in one PR so if you had a checkout from before that PR, you had some map files that the system no longer knows to delete.

**Comment by di** [comment]
@dstufft This issue has actually happened multiple times for me, even after `rm`-ing `warehouse/static/dist`. I'm also unsure on the cause.

**Comment by dstufft** [comment]
Interesting, that suggests the clean task is missing some files still then.
