### ISSUE TITLE
Use natural sort order for file listings

### ISSUE THREAD

**Issue by pradyunsg** [pypa/warehouse#10262]
**What's the problem this feature will solve?**

Currently on https://pypi.org/project/lxml/4.6.3/#files, the files are listed as:

- lxml-4.6.3-cp27-cp27mu-manylinux1_x86_64.whl
- lxml-4.6.3-cp310-cp310-manylinux_2_12_i686.manylinux2010_i686.manylinux_2_24_i686.whl
- lxml-4.6.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl
- lxml-4.6.3-cp35-cp35m-manylinux1_i686.whl

This is because the strings are sorted as 27 < 310 < 35, for strings.

**Describe the solution you'd like**

Use natural sorting order for filenames, similar to what we did for https://github.com/pypa/trove-classifiers/issues/56.

This _may_ also make sense for the simple pages, where it would be a nice-to-have when a human looks at the page.

**Comment by jbylund** [comment]
re `pg_config` not found: you need to apt-install either postgresql-common, libpq-dev (making some assumptions about build env).

**Comment by ewjoachim** [comment]
If you're using mac os, what you may want to do is
```
brew install libpq
```
In the output, it will mentionned that libpq is not automatically put in the path, so you may want to either edit your path for the current shell or link libpq executables to your path with the `link --force` command that will be described in the output.

**Comment by pradyunsg** [comment]
Hurray! Thanks @miketheman! ^.^
