### ISSUE TITLE
Daily and weekly download traffic stats

### ISSUE THREAD

**Issue by abitrolly** [pypa/warehouse#10355]
**What's the problem this feature will solve?**

I need to calculate money savings from traffic savings in https://github.com/pypa/warehouse/pull/9972 to get understanding of the value of my efforts, to pitch it for better job offers.

**Describe the solution you'd like**

https://pypi.org/stats/ endpoint provided rendered number of the daily and weekly outgoing traffic served by infrastructure, split by traffic provider.

Ideally there should also be a link to API that allows to query more specific or detailed info.

**Additional context**

If there a list of all hosting infrastructure used by PyPI for the start?

**Comment by pradyunsg** [comment]
See https://warehouse.pypa.io/api-reference/bigquery-datasets.html#download-statistics-table

**Comment by abitrolly** [comment]
@pradyunsg have you checked that [the table](https://console.cloud.google.com/bigquery?pli=1&p=bigquery-public-data&d=pypi&t=file_downloads&page=table) includes the downloaded size before closing the issue? Because there is no traffic stats.

**Comment by pradyunsg** [comment]
I hadn't, and, no, that data is not directly accessible in a single spot.

Your best bet would be to also make a few hundred API requests to the JSON API to know the size of the distribution files which, combined with the total download counts, will give you your answer.

**Comment by abitrolly** [comment]
@pradyunsg or reopen the issue to make the data available without few thousands JSON API calls.

**Comment by abitrolly** [comment]
`piwheels` provides the monthly bandwidth stats - https://blog.piwheels.org/piwheels-stats-2021q3/ and I don't see the reason why $300000 project can't do the same. @pradyunsg reopen?

**Comment by di** [comment]
This is a duplicate of #787.
