### ISSUE TITLE
Should we remove the Copyright Footer?

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1035]
I've raised this with the PSF Board, but I'm recording it here just to keep a record of it. Currently on legacy PyPI we have a footer that states:

> Copyright © 1990-2015, Python Software Foundation

We've copied that over into Warehouse so that every page now says:

> © 2016 Python Software Foundation.

However it's not clear that we should actually have this statement or that it's accurate in any way. Most of the *content* on PyPI has it's copyright owned by the authors of those projects. For Warehouse itself the copyright is owned by the contributors to the Warehouse project, not to the PSF. Frankly, I'm not sure if any part of PyPI's copyright is owned by the PSF.

I've asked the PSF what, if anything, we should include in the footer and we'll go ahead and go with their recommendation.

Taken from #1030

**Comment by kennethreitz** [comment]
Of note, is that GitHub has a copyright line at the bottom of every page.

**Comment by dstufft** [comment]
Ok, after talking with the board, we're going to be keeping this.

**Comment by techtonik** [comment]
@dstufft is it possible to post the discussion?
