### ISSUE TITLE
ipympl 0.8.2 - ginput() does not work on Jupyter / returns an empty array

### ISSUE THREAD

**Issue by opens9999** [pypa/warehouse#10407]
**Describe the bug**
I should be able to select data points from a figure and then red crosses are supposed to appear after clicking with the mouse, but nothing happens, an empty array is returned and the figures only appear after the timeout of ginput(). 

**Expected behavior**
Figure pops up and I can click with the mouse on the figure to select data points. An array will be generated

**To Reproduce**
```
%matplotlib widget 

import matplotlib.pyplot as plt
import numpy as np
t = np.arange(10)
   
plt.plot(t, np.sin(t))
     
plt.title('matplotlib.pyplot.ginput()\
 function Example', fontweight ="bold")
   
print("After 3 clicks :")
x = plt.ginput(3)
print(x)
   
plt.show()
```

**My Platform**

    Firefox on Arch Linux, latest version after system update

**Comment by ewjoachim** [comment]
Hi, this issue tracker is for issues with the codebase behind [pypi.org](https://pypi.org) itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
