### ISSUE TITLE
Keyword "Apache Spark" shows up on Warehouse as two keywords "Apache", "Spark"

### ISSUE THREAD

**Issue by nchammas** [pypa/warehouse#1041]
Here's how I set my project's keywords ([ref](https://github.com/nchammas/flintrock/blob/413b7f408fe11b2da4b262d1499e829a63f08c4d/setup.py#L40)):

```python
keywords=['Apache Spark'],
```

So my intention was 1 keyword, "Apache Spark". However, here on Warehouse this [shows up as](https://warehouse.python.org/project/Flintrock/) two keywords, "Apache" and "Spark".

Is this intentional?

I know that `setup()` also accepts a single string for `keywords`, instead of a list of strings, as follows:

```python
keywords='Apache Spark',
```

In this case I would expect the keywords to be interpreted as whitespace-delimited -- that is, two keywords, "Apache" and "Spark", as they currently are on Warehouse.

**Comment by karan** [comment]
This seems to be the doing on `format_tags` filter.

https://github.com/pypa/warehouse/blob/master/warehouse/filters.py#L101

Specifically

L108: `split_tags = re.split(r'\s+', tags)`

I think the correct behavior is this:

- If passed argument `tags` is a list, then call `format_tags` recursively (or iteratively), to clean each individual one.
- If `tags` is a string, then execute the existing flow.

Legacy pypi doesn't seem to be doing any formatting - just dumps the keyword as a string on the UI.

@dstufft or @rjwebb can confirm.

**Comment by robhudson** [comment]
Does distutils (and setuptools) allow lists for `keywords`? I scanned the code quickly and could find no evidence that this is supported there. If not, I wouldn't imagine warehouse shouldn't either.

**Comment by nchammas** [comment]
@robhudson - setuptools accepts lists for `keywords`. See the first link in my original post, under "(ref)".

**Comment by berkerpeksag** [comment]
distutils allows lists. There is a test in `Lib/distutils/tests/test_dist.py`:

```py
self.assertEqual(dist.metadata.keywords, ['one', 'two'])
```

**Comment by dstufft** [comment]
In PyPI/Warehouse it will *always* be a string, distutils/setuptools coerces it.

**Comment by nchammas** [comment]
@dstufft - Does that mean it's not possible to have a single tag that has a space in it?

**Comment by dstufft** [comment]
@nchammas that means it's not possible to deterministically parse the output of this field, because it can be a fee form string, and it can also be a list that distutils/setuptools coerced into a string. So we have to use some sort of mechanism to determine where to split these (or we need to not try and split them and just render it as is).

Currently our hueristics are implemented such that a single tag with a space in it shows up as two tags, because in the wild people have done stuff like "tag1 tag2".

**Comment by nchammas** [comment]
Okie doke. Sounds like this issue should be closed as "Won't Fix" and if people want a multi-word tag like "Apache Spark" they should be instructed to capture that differently, perhaps as "apache-spark".

Does that make sense?

**Comment by dstufft** [comment]
I *think* that if you use ``keywords="Apache Spark,"`` you might get the behavior you want, but yea, closing this as WONTFIX. Thanks!
