### ISSUE TITLE
Legacy support for protocol_version keyword is... funky.

### ISSUE THREAD

**Issue by amilstead** [pypa/warehouse#1042]
Distuils has a bug/typo in the `distutils/command/upload.py` file (line 91), where they send the key `protcol_version` rather than `protocol_version`.

Warehouse's legacy support (https://github.com/pypa/warehouse/blob/master/warehouse/legacy/api/pypi.py#L562) uses `.get("protocol_version", "1")`, which will always return `"1"` because the key isn't actually there. Valid checking of the version distutils sends won't actually ever validate properly.

Effectively, it always assumes version 1 unless something other than distuils sent a proper `protocol_version` form parameter.

**Comment by dstufft** [comment]
Heh, this is kind of amusing, but at this point probably not worth fixing it. I doubt we'll ever see a version of the legacy upload protocol other than 1. Nice find though!

**Comment by sigmavirus24** [comment]
We're hoping to transition everyone to twine anyway. I am 90% certain it doesn't have that bug :)

**Comment by amilstead** [comment]
=)

I figured that might be the case but didn't see it already reported so decided to go ahead.

I'll have to check out twine!
