### ISSUE TITLE
I got this error "ERROR: XMLRPC request failed [code: -32500] RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information." upon using pip search selenium -i https://pypi.org, What do I do then?

### ISSUE THREAD

**Issue by Harsh22222** [pypa/warehouse#10428]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by Harsh22222** [comment]
Ok, mistakenly I put bug label to this issue ,sorry for that ,but please help me to find a solution .

**Comment by di** [comment]
Hi @Harsh22222, the endpoint is currently disabled due to https://status.python.org/incidents/grk0k7sz6zkp.

Can you describe what you're trying to do with the endpoint so we can suggest alternatives?

**Comment by Harsh22222** [comment]
hello , I was just trying to search about selenium, in depth all the files and stuff.

**Comment by di** [comment]
I'd recommend using https://pypi.org/search/ instead.
