### ISSUE TITLE
PyPi Stats Not Updated Since Nov 24

### ISSUE THREAD

**Issue by alexheat** [pypa/warehouse#10441]
The PyPi stats data on https://pypistats.org/ and BigQuery has not been updated in over a week. Is there an issue with that data pipeline?  Check the data of https://pypistats.org/packages/pandas.

I know that pypistats is not an official site, though I am reporting it here because I am not sure if the issues is in PyPI itself or not.

Thank you!

**Comment by di** [comment]
This is https://status.python.org/incidents/2jj696st6yn5, also captured at https://github.com/crflynn/pypistats.org/issues/44 and https://github.com/pypa/linehaul-cloud-function/issues/54. Unrelated to this codebase so closing in favor of those issues.
