### ISSUE TITLE
Unable to Install pyqt5 with pip - SSL error

### ISSUE THREAD

**Issue by Reggie86** [pypa/warehouse#10457]
Unable to install pyqt5 from windows console using pip

C:\Users\davcam\Documents\SVN\PycharmProjects>pip install pyqt5
Collecting pyqt5
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_
NUMBER] wrong version number (_ssl.c:2629)'))': /packages/be/f2/8e7b751d102ce3500cbeff97cb514eaf5c06d5e423676c37e9de28d0c06b/PyQt5-5.15.6-cp36-abi3-win_amd64.wh
l
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_
NUMBER] wrong version number (_ssl.c:2629)'))': /packages/be/f2/8e7b751d102ce3500cbeff97cb514eaf5c06d5e423676c37e9de28d0c06b/PyQt5-5.15.6-cp36-abi3-win_amd64.wh
l
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_
NUMBER] wrong version number (_ssl.c:2629)'))': /packages/be/f2/8e7b751d102ce3500cbeff97cb514eaf5c06d5e423676c37e9de28d0c06b/PyQt5-5.15.6-cp36-abi3-win_amd64.wh
l
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_
NUMBER] wrong version number (_ssl.c:2629)'))': /packages/be/f2/8e7b751d102ce3500cbeff97cb514eaf5c06d5e423676c37e9de28d0c06b/PyQt5-5.15.6-cp36-abi3-win_amd64.wh
l
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_
NUMBER] wrong version number (_ssl.c:2629)'))': /packages/be/f2/8e7b751d102ce3500cbeff97cb514eaf5c06d5e423676c37e9de28d0c06b/PyQt5-5.15.6-cp36-abi3-win_amd64.wh
l
**ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/be/f
2/8e7b751d102ce3500cbeff97cb514eaf5c06d5e423676c37e9de28d0c06b/PyQt5-5.15.6-cp36-abi3-win_amd64.whl (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER]
 wrong version number (_ssl.c:2629)')))**

My Environment
Operating System
	Windows 7 Professional 64-bit SP1
	Computer type: Mini Tower
	Installation Date: 4/3/2015 12:09:10 AM
		Windows Security Center
			User Account Control (UAC)	Enabled
			Notify level	2 - Default
		Windows Update
			AutoUpdate	Download Automatically and Notify Prior to Install
		Windows Defender
			Windows Defender	Disabled
		Firewall
			Firewall	Enabled
			Display Name	ZoneAlarm Free Firewall Firewall
		Antivirus
			Antivirus	Enabled
			Company Name	Microsoft
			Display Name	Microsoft Security Essentials
			Product Version	4.10.209.0
			Virus Signature Database	Up to date
		.NET Frameworks installed
			v4.8 Full
			v4.8 Client
			v3.5 SP1
			v3.0 SP2
			v2.0 SP2
		Internet Explorer
			Version	11.0.9600.19596
		PowerShell
			Version	2.0
		Java
				Java Runtime Environment
					Path	C:\Program Files (x86)\Java\jdk1.8.0_172\bin\java.exe
					Version	8.0
					Update	172
					Build	11
				Java Runtime Environment
					Path	C:\Program Files (x86)\Java\jre1.8.0_311\bin\java.exe
					Version	8.0
					Update	311
					Build	11
				Java Runtime Environment
					Path	C:\Program Files\Java\jdk1.8.0_51\bin\java.exe
					Version	8.0
					Update	51
					Build	16
				Java Runtime Environment
					Path	C:\Program Files\Java\jre1.8.0_311\bin\java.exe
					Version	8.0
					Update	311
					Build	11

**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, please file a [Network Access Issue](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=network&template=access-issues.yml) and be sure to provide responses to all fields.
