### ISSUE TITLE
Question/Request: Pointless rapidjson repo with deleted user

### ISSUE THREAD

**Issue by PhilipDeegan** [pypa/warehouse#10454]
Can you replace
https://pypi.org/project/rapidjson
with
https://pypi.org/project/python-rapidjson
?

I don't know what the policy on this is, but it seems a bit weird to have a somewhat serious project (rapidjson), not have the default project name for itself, and that some other project, which is not useful to anyone, has it.

**Comment by di** [comment]
Hi, if that project is interested in acquiring that project name, they can file a name retention request [here](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME).
