### ISSUE TITLE
GFM is not supported on PyPI

### ISSUE THREAD

**Issue by jiri-one** [pypa/warehouse#10462]
**Describe the bug**
The [Core Metadata specifications](https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-description-content-type) and the Packaging Python projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-readme-md) document say that you can use [Github-flavored Markdown](https://guides.github.com/features/mastering-markdown/)in descriptions. but (at least) the [Task Lists](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#task-lists) feature of GFM is not supported on PyPI. 

**To Reproduce**
See [easydict-gtk](https://pypi.org/project/easydict-gtk/#description) for an example:
![image](https://user-images.githubusercontent.com/302922/145218311-01999bdf-1ae9-44b2-89be-6f85d27bea73.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/302922/145218350-99783488-f7a0-4873-9bdc-af90b728d5a7.png)

**My Platform**
Firefox/Arch Linux

**Comment by di** [comment]
Thanks for the report! This is https://github.com/pypa/readme_renderer/issues/208.
