### ISSUE TITLE
"installing packages" links on pypi.org are broken

### ISSUE THREAD

**Issue by junyer** [pypa/warehouse#10470]
**Describe the bug**
At least two "installing packages" links on pypi.org are broken. The "Download files" panel says "Download the file for your platform. If you're not sure which to choose, learn more about installing packages." and links to https://packaging.python.org/installing/, which doesn't exist. The page footer has an "Installing packages" link with the same problem. Perhaps there are other such links elsewhere on the site that I haven't encountered?

**Expected behavior**
The "installing packages" links should probably be to https://packaging.python.org/tutorials/installing-packages/ instead?

**To Reproduce**
I noticed this on https://pypi.org/project/google-re2/#files right after I sent it to someone who probably needs that documentation. :(

**My Platform**
N/A

**Additional context**
N/A

**Comment by marienz** [comment]
Looks like this is caused by https://github.com/pypa/packaging.python.org/issues/1026, which mentions /installing/ should redirect to /tutorials/installing-packages, but it's masked by a redirect to /en/latest.

**Comment by di** [comment]
This should now be resolved per https://github.com/pypa/packaging.python.org/issues/1026#issuecomment-992538633.
