### ISSUE TITLE
Definitive list of what Browsers we support

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1052]
I was poking at things and one thing that stood out to me is that we don't really define what browsers we actually do support currently. In #979 and #881 we decided we're not going to support IE8, but then the question becomes what *do* we support?

We're currently using the following javascript libraries:

* **jQuery**: IE9+, Chrome, Edge, Firefox Current and Current -1, Safari 5.1+, Opera 12.1x, (Current - 1) or Current, iOS 6.1+, and Android 2.3, 4.0+.
* **L20n.js**: "Evergreen Browsers", which I believe are Chrome, Edge, Firefox, and Opera. They might be able to support IE11 and I'm unsure about Safari, iOS, and Android.

Looking at data for PyPI we have (in March 2016):

* 64% of sessions are using Chrome.
* 22% of sessions are using Firefox.
* 7.8% of sessions are using Safari.
* 3.4% of sessions are using Internet Explorer.
* 1% of sessions are using Edge.
* 0.9% of sessions are using Opera.
* Everything else is at < 0.25%.

Off the bat I think it's easy to say that we'll support the Current, and Current - 1 of the "Evergreen" browsers which are Chrome, Firefox, Edge, and Opera which will cover 88% of our traffic in march.

Breaking down what Safari looks like (as the largest non evergreen browser) we get:

* 71% using Safari 9.0.
* 18% using Safari 9.1.
* 11% using Safari < 9.

I think we can justify supporting Safari 9+ since Safari < 9 represents 0.85% of our total sessions.

Taking a look then at Internet Explorer, we get:

* 81% using IE11.
* 6.27% using IE8.
* 6.11% using IE9.
* 4.9% using IE10.

I think it's reasonable to say we're going to support IE11+. IE11 is by far the largest share of IE users and we've already decided not to support the next largest share which is IE8 and IE < 11 represents 0.64% of our traffic.

This would gives us a policy of:

| Browser | Supported Versions   |
| --------| -------------------- |
| Chrome  | Current, Current - 1 |
| Firefox | Current, Current - 1 |
| Edge    | Current, Current - 1 |
| Opera   | Current, Current - 1 |
| Safari  | 9.0+                 |
| IE      | 11+                  |

I'm not a front end person so I may be missing some important piece of the puzzle here, but this seems like a reasonable policy to me given our traffic numbers but I'd like @nlhkabu to sign off on this policy.

**Comment by nlhkabu** [comment]
I think we should *officially* support ie11+, but I don't see any harm in spending a short time pre launch to check that ie9 and 10 are not totally broken.  If it only takes an hour for checking this, then that is not going to be a problem.

The great thing is that this means *I think* we can now remove modernizr, which is causing some load time issues according to https://developers.google.com/speed/pagespeed/insights/?url=warehouse.python.org&tab=mobile

**Comment by dstufft** [comment]
Yea I'm primarily worried about what we officially support. If we want to unofficially make things ok-ish in other browsers that's fine with me. So then I'll go ahead and add a PR to make this policy documented and another PR to remove modernizer. Thanks!
