### ISSUE TITLE
Replace Warehouse-Camo with Ivatar / Add Libravatar Support

### ISSUE THREAD

**Issue by baseplate-admin** [pypa/warehouse#10522]
# **What's the problem this feature will solve?**

Gravatar is not an open source project. There are [some](https://meta.stackexchange.com/questions/44717/is-gravatar-a-privacy-risk) [talks](https://meta.stackexchange.com/questions/21117/is-using-gravatar-a-security-risk) about Gravatar having privacy issues. This will essentially replace Gravatar with a privacy focused alternative.

# **Describe the solution you'd like**
## **Proposal 1:**
 My proposition is to replace Gravatar with Libravatar. [Ivatar ](https://git.linux-kernel.at/oliver/ivatar/)( the software the powers Libravatar ) being a [open source project, ](https://git.linux-kernel.at/oliver/ivatar/) maintained by a [Red Hat Systems Engineer](https://www.redhat.com/sysadmin/users/oliver-falk) and is backed by the [Fedora](https://blog.libravatar.org/posts/Back_To_Fedora/) project seems a really good, [customizable](https://wiki.libravatar.org/api/), [feature rich](https://wiki.libravatar.org/features/), [actively developed](https://git.linux-kernel.at/oliver/ivatar/-/commits/master) candidate. Since  [Libravatar and Gravatar are API compatible](https://wiki.libravatar.org/api/) it will just be a URL change in this [line.](https://github.com/pypa/warehouse/blob/eb241f9061633752672a07851cd553ad4c5cd24a/warehouse/utils/gravatar.py#L25) Also we may not need to use [warehouse-camo](https://github.com/pypa/warehouse-camo/) proxy ( because [Ivatar does the proxying](https://git.linux-kernel.at/oliver/ivatar/-/blob/master/ivatar/views.py#L190)  ) and save proxy bandwidth.

## **Proposal 2:**
If we dont trust the Libravatar project or if we want more control over avatar management we can fork the [Ivatar project](https://git.linux-kernel.at/oliver/ivatar/) ( to not reinvent the wheel ) and self host [Ivatar](https://git.linux-kernel.at/oliver/ivatar/) as a avatar backend for PyPi. Which will also remove the need for warehouse-camo proxy. Also it would solve both  #782 #8211. The code is mostly Python ( Django ), But it will increase bandwidth on our server / Require us to host a instance of Ivatar.

# **Additional context**

1. [Gitlab already offers both Gravatar and Libravatar](https://docs.gitlab.com/ee/administration/libravatar.html)

**Comment by di** [comment]
Thanks for the issue!

Given that we wrap our Gravatar URL's in a Camo URL, I think the risks mentioned (MD5 reversal, user tracking) are mitigated. It also seems that Libravatar also does an MD5 hash of the user's email, so I'm not sure there's an advantage w.r.t. that risk.

Part of the reason we use Gravatar is that a) it's lightweight & maintenance-free for us, and b) many users have Gravatar avatars. Unless we have a solution that is comparable, that also allows us to fall back on Gravatar to maintain existing avatars, I think we're unlikely to migrate.

Given that, I'm going to close this issue for now, but I'm open to revisiting it in the future if things change.
