### ISSUE TITLE
Specify which fields to return for the JSON API

### ISSUE THREAD

**Issue by frostming** [pypa/warehouse#10595]
**What's the problem this feature will solve?**
Currently the json API returns package info together with ALL releases and links, while the latter can be retrieved from simple API and are not useful for most use cases.

By specifying fields, we can exclude releases to reduce the response size

**Describe the solution you'd like**
Follow the RESTful convention, add a query parameter `fields` to the JSON API endpoint:

`/pypi/{package}/{version}/json?fields={comma separated list of fields}`

**Additional context**

**Comment by ewjoachim** [comment]
The limiting factor on Warehouse's side is less the response size and more the cache rate. The more personalized the responses, the more likely it will hit the warehouse service and not just fastly, which would make it much more costly (more compute power). So I'm not sure it's really interesting on the warehouse side to pay a lot of compute power for fastly to gain some response size. Of course, I understand that it might be interesting on the client side, but I'm not sure it's really worth it.

Is there a specific reason why you want to limit response size on your side ?

**Comment by frostming** [comment]
I was trying to build a package resolver that is fed by the dependencies of all versions of a given package.
I didn't consider the server-side limitation and it makes sense to me.

Feel free to close the issue or if you want to leave it for others to chime in.
