### ISSUE TITLE
Build to Upgrade bleach to 3.3.0 is failing due to django-incident-response 0.5.1 depends on bleach 3.1.4

### ISSUE THREAD

**Issue by aquinoelite** [pypa/warehouse#10604]
**Describe the bug**
Build failed due to "django-incident-response 0.5.1 depends on bleach 3.1.4"
The latest version of bleach is 4.1.0
Snyk detects a vulnerability issue on bleach - Cross-site Scripting(XSS)

However, the heroku build/deploy is failing because django-incident-response 0.5.1  is not accepting the latest version of bleach (3.3.0 or 4.1.0)

**My Platform**
 Heroku deployment
Django 2.2.26

**Additional context**
https://pypi.org/project/django-incident-response/
https://pypi.org/search/?q=bleach

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
