### ISSUE TITLE
Library Validators - Error URL with "--" in subdomain

### ISSUE THREAD

**Issue by ricardosupo** [pypa/warehouse#10640]
In version 0.18.2 URL with '--' in subdomain have problem:

> import validators
> url = 'https://abc--eddd.repl.co/'
> print(validators.__version__)
> print (validators.url(url))
> 0.18.2
> ValidationFailure(func=url, args={'value': 'https://abc--eddd.repl.co/', 'public': False})

_

**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
