### ISSUE TITLE
PyPI search box could use autofocus=true

### ISSUE THREAD

**Issue by brsolomon-deloitte** [pypa/warehouse#10656]
The "Search projects" input box on https://pypi.org would benefit from using HTML [autofocus](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus). (The specific HTML DOM element is `input#search`.)

**Comment by sedders123** [comment]
It looks like the decision was made not to autofocus the search box in https://github.com/pypa/warehouse/issues/6088 and instead a keyboard shortcut was implemented (tracking issue https://github.com/pypa/warehouse/issues/6099). The shortcut is <kbd>/</kbd> and will focus the search box

**Comment by brsolomon-deloitte** [comment]
Thanks for providing the links and my fault for not searching in existing issues first.
