### ISSUE TITLE
Finish porting warehouse/static/js/main.js to ES6

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1068]
In #1059 we laid out the framework for using ES6 modules and webpack to handle our Javascript, but we still need to port everything in ``warehouse/static/js/main.js`` over to this as well, ideally without using jQuery if possible.

**Comment by karan** [comment]
Are there any UI tests that can be run to make sure the porting is correct?

**Comment by dstufft** [comment]
Nope :( We have the start of some UI tests, but the original JS was not written with tests.

**Comment by dstufft** [comment]
We probably don't need this to actually launch do we? The downside to not having this is basically that we have extra JS being downloaded that we don't really need (some duplication between the old and new) but other than that it should work yea?

**Comment by dstufft** [comment]
Also to mention is that ``warehouse/static/js/main.js`` doesn't need to be entirely ported in one go (in fact, it'd be easier both to implement and review if it were done feature by feature instead of all at once). 

These things aren't massive bits of JS, but porting each would ideally involve figuring out if there's a native alternative to whatever is being used (possibly will a polyfill if needed for our [Browser Support Policy](https://warehouse.readthedocs.io/development/frontend/#browser-support) or else wise pulling in small modern libraries where needed. Ideally each port will also include with it some front end tests to ensure that the JS continues to work in the future.

**Comment by brainwane** [comment]
@wismer is working on the rest of this issue.

**Comment by wismer** [comment]
@dstufft since all of `main.js` has been ported, I suppose this issue could be closed, then?
