### ISSUE TITLE
Automatic account recovery service

### ISSUE THREAD

**Issue by novitae** [pypa/warehouse#10698]
Hello,
I am of the 36 people that lost access to my pipit account (because I lost my recovery codes lol).

It could be nice if the recovery process was an automatic one ... for some people, getting back their pypi account can be something urgent, and it seems that nobody from the past 3 months got theirs back, and @ewdurbin was alone doing this manually for everyone that lost access ...

Thanks for your attention !

**Comment by di** [comment]
Hi @novitae, thanks for the issue. Ultimately we need to ensure that you are you and not an attacker trying to compromise your account. To do that for accounts that have 2FA enabled, we need to either a) a valid 2FA authentication b) valid recovery codes or c) manual verification via third parties like GitHub, depending on what information we have available about the account.

As a result, automating account recovery will essentially make 2FA no more secure than 1 factor authentication, so we have no plans to automate this process. Instead, resolving issues like https://github.com/pypa/warehouse/issues/8897 will make it more likely that users have recovery codes in their possession.

Closing this in favor of https://github.com/pypa/warehouse/issues/8897.
