### ISSUE TITLE
Automatically update Javascript dependencies

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1069]
We're currently using requires.io to handle automatically indicating when there is a new Python level dependency, however we don't have anything like that to handle our JS level dependencies. It would be great if we could wire up something like that now that we've started to add tests. Maybe we can use something like [Greenkeeper](https://greenkeeper.io/) to do this? If possible it would be great to also figure out how to add something like `--require-hashes` so that we're not dependent on the security of the npmjs.org repository.

**Comment by di** [comment]
We're now using Dependabot and I just turned on Javascript support there.

Also our `package-lock.json` now has SHA512 integrity hashes as well, so calling this issue resolved!
