### ISSUE TITLE
Could not find a version

### ISSUE THREAD

**Issue by beucismis** [pypa/warehouse#10705]
**Describe the bug**

I'm can't installed of `pythonfetch` package. Currently there are 2 versions in PyPI.
![ss_1644322727](https://user-images.githubusercontent.com/40023234/152985645-8fc66f70-c6ba-4350-8c76-44772e3d202d.png)

**Expected behavior**

Being able to install the package.

**To Reproduce**

**My Platform**

OS: `Debian Unstable`
PIP Version: `22.0.2`

**Additional context**

https://pypi.org/project/pythonfetch/

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by beucismis** [comment]
Sorry, I don't understand. What is problem?
