### ISSUE TITLE
Please increase max wheel size limit for intel-extionsion-for-pytorch projects(test and prod) to 250MB.

### ISSUE THREAD

**Issue by ashahba** [pypa/warehouse#10754]
Hi,
My team at Intel is planning to publish wheels for [IPEX](https://github.com/intel/intel-extension-for-pytorch) at the following location:

Test project: https://test.pypi.org/project/intel-extension-for-pytorch/
Prod project:  https://upload.pypi.org/legacy/intel-extension-for-pytorch/

Our first set of wheels are a little over 100 MB in size which is the current default max size limit for artifacts.

Would you please increase the individual artifact max size limit to 250MB?

By the way I haven't initiated the production project yet, due to failure of upload to even test project. If you require me to create that one as well before modifying size limit, please let me know.

Thanks!

**Comment by ashahba** [comment]
Hi @jamadden 
I'm not sure if you are still the right person to handle this ticket, if not please assign to the right owner.

Thanks.

**Comment by pradyunsg** [comment]
Please file a limit request issue, on https://github.com/pypa/pypi-support. The issue form will have the relevant questions that you'd need to answer.

This repository is not the correct location for making limit increase requests.
