### ISSUE TITLE
Cannot add a second email address to PyPI account

### ISSUE THREAD

**Issue by Anthchirp** [pypa/warehouse#10761]
**Describe the bug**
I have a single primary+verified mail address on my pypi account (`mgerstel`), and want to add a second address.
After clicking the 'Add email' button I get the following server response:

> 429 Too Many Requests
> The action could not be performed because there were too many requests by the client.
> 
> Too many emails have been added to this account without verifying them. Check your inbox and follow the verification links. (IP: _(redacted)_)

**Expected behavior**

Either a new email address should be added, or - if there are other unverified mail addresses on the account - those should be shown.

**To Reproduce**

https://pypi.org/manage/account/, no idea if other users are affected or not.

**My Platform**
Linux/Firefox ESR

**Comment by di** [comment]
Are you on a shared IP? I'm seeing lots of activity from the IP you logged in with today across many different accounts.

**Comment by Anthchirp** [comment]
Thank you Dustin for looking into this. Yes, that IP may have [1200 staff behind it](https://stfc.ukri.org/about-us/where-we-work/rutherford-appleton-laboratory/) - not all of them on pypi of course, but I did ask some colleagues today to set up accounts. I will try again tomorrow :+1:

**Comment by di** [comment]
Sorry about that! You might understand how we usually interpret similar behavior to be 'spammy'.

Just verifying one email from an account created today will have the effect of resetting the rate limiter for that IP.

**Comment by Anthchirp** [comment]
Tried again now, and it works. Thank you
