### ISSUE TITLE
`make initdb` slows to a crawl/fails when `docker-compose` is compose v2

### ISSUE THREAD

**Issue by woodruffw** [pypa/warehouse#10772]
Noticed this while trying to stand up a local instance of Warehouse with compose v2 enabled:

Observed behavior:

1. Running `make initdb` produces *much more* output on the terminal than it normally does
2. The console scrollback for the `db` service is filled with lots of SQL syntax errors, e.g.:

    ```
    warehouse-db-1             | 2022-02-17 17:02:49.596 UTC [35] ERROR:  syntax error at or near "0.0" at character 1
    ```

I let `make initdb` run for about ~5 minutes, which is several times longer than it takes to complete when using compose v1, without visible progress beyond the initial SQL load phase.

Reproduction steps:

These steps are for macOS.

1. Open up the Docker for Mac preferences pane (`Cmd + ,`)
1. Go to the "General" page
1. Click the checkbox for "Use Docker Compose V2" (screenshot below)
1. Restart the Docker daemon
1. `make serve`
1. `make initdb` (in a separate window)

![Screen Shot 2022-02-17 at 12 13 08 PM](https://user-images.githubusercontent.com/3059210/154534514-96fdc4ed-6c7d-4170-aafe-7ef70ecf3fea.png)

**Comment by di** [comment]
Parts of #9993 might be a potential solution for this.

**Comment by woodruffw** [comment]
Yep, it's that one. My guess is that compose V2 has broken/buggy pipe behavior, since that's been a consistent problem across `docker` and `docker-compose` over the years.

**Comment by woodruffw** [comment]
> Parts of #9993 might be a potential solution for this.

I can give that changeset a try in a moment!

**Comment by miketheman** [comment]
If the pipe behavior is the culprit, did this fix it? https://github.com/pypa/warehouse/pull/10978

**Comment by woodruffw** [comment]
> If the pipe behavior is the culprit, did this fix it? #10978

I'll re-try this afternoon and find out.

**Comment by di** [comment]
@woodruffw Have you been able to determine if this is resolved?

**Comment by woodruffw** [comment]
Sorry, this fell off my radar! Trying now (as soon as Docker Desktop finishes updating...)

**Comment by woodruffw** [comment]
It appears to be working now! I see this in my logs:

```
warehouse-db-1             | 2022-04-13 22:40:19.421 UTC [39] FATAL:  terminating connection due to administrator command
warehouse-db-1             | 2022-04-13 22:40:19.421 UTC [40] FATAL:  terminating connection due to administrator command
warehouse-db-1             | 2022-04-13 22:40:34.177 UTC [60] FATAL:  role "root" does not exist
```

...but Warehouse does appear to come up correctly and the commands all still exit successfully. Closing.

**Comment by miketheman** [comment]
For that last message, I've supplied https://github.com/pypa/warehouse/pull/11182 to fix it.

**Comment by woodruffw** [comment]
Awesome. I can test that PR tonight.
