### ISSUE TITLE
Clarification on name similarity restrictions

### ISSUE THREAD

**Issue by agkphysics** [pypa/warehouse#10810]
I tried uploading my project [`ertk`](https://github.com/Strong-AI-Lab/emotion) to PyPI and received the following error, which did not appear when uploading to Test PyPI:
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The name 'ertk' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

there is no project with the exact name `ertk` that I can see, but there is one called [`nertk`](https://pypi.org/project/nertk/) which I suspect is the cause of the issue.

Is having an extra 'n' at the beginning sufficient to cause this name issue? If so then I can change the project name slightly but I just want to confirm that this is the specific issue.

**Comment by di** [comment]
This project name was prohibited as it was previously published in a suspected dependency confusion attack.

If you file an issue [here](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME) we can transfer the project name to you.

**Comment by di** [comment]
To specifically answer your question:

> Is having an extra 'n' at the beginning sufficient to cause this name issue?

No, the difference of a single character would not prevent a new project name from being created.

**Comment by agkphysics** [comment]
> This project name was prohibited as it was previously published in a suspected dependency confusion attack.
> 
> If you file an issue [here](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME) we can transfer the project name to you.

Okay I will do that. Thanks for clarification.
