### ISSUE TITLE
Win10 installation & runtime problems

### ISSUE THREAD

**Issue by hbkoenig** [pypa/warehouse#10842]
**Describe the bug**
trying to install and run pythonpy (py) on Win10 I found 2 issues:

1) pip install does not work, it fails with 
                    `ValueError: path '/' cannot be absoute`

I've tried python versions 3.7, 3.8 and 3.9 with pip versions 19.* and 22.* and always got the same error.

looking for that error I found hints on stackoverflow that downloading the egg 
and removing the pythonpy.egg-info/ will help -- and it does!
without that pythonpy.egg-info/ directory, installation works. 
BUT:

2) runtime error "SIGPIPE"
running pythonpy-0.4.11 on Win10 I then get
                  `ImportError: cannot import name 'SIGPIPE' from 'signal'`

which I now avoid with this ugly hack which "works for me" [TM]

```
--- pythonpy/__main__.py~       2016-01-13 03:31:34.000000000 +0100
+++ pythonpy/__main__.py        2022-02-25 16:38:58.995840347 +0100
@@ -7,8 +7,9 @@
     reload(sys)
     sys.setdefaultencoding('utf-8')
 
-from signal import signal, SIGPIPE, SIG_DFL
-signal(SIGPIPE,SIG_DFL)
+if sys.platform != 'win32':
+    from signal import signal, SIGPIPE, SIG_DFL
+    signal(SIGPIPE,SIG_DFL)
 
 import argparse
 import json
```

**Expected behavior**
installation with pip in windows should work,
and the missing support for SIGPIPE in windows should be handled...

**To Reproduce**
pip install --user pythonpy
anaconda3 with python 3.7, 3.8 and 3.9

**My Platform**
Windows Server 2019 (version 1809)
anaconda 

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
