### ISSUE TITLE
Explore adding static typing

### ISSUE THREAD

**Issue by di** [pypa/warehouse#10865]
We should determine a way that we can gradually add static typing (and ensure that we're able to assert that it is correct in CI) without introducing a single massive PR.

**Comment by fizyk** [comment]
mypy has configuration options that would allow doing that gradually

https://mypy.readthedocs.io/en/stable/config_file.html

We could either include paths that got converted or exclude those that do not (this would require all new ones to already be typed)

**Comment by miketheman** [comment]
I'm interested in this kind of work.

A few questions/decisions arise at this juncture:

- Is mypy considered a lint tool, or a testing tool? (for requirements inclusion) I think lint - from the mypy docs:
  > As mypy is a static analyzer, or a lint-like tool, ...
- Is there a particular entry point or an area of focus? We can also follow the [recommended path](https://mypy.readthedocs.io/en/stable/existing_code.html)
- Where do we want to configure mypy? I'm partial to `pyproject.toml`, but that's not currently mounted to the developer container - should we mount that as well?

**Comment by di** [comment]
> Is mypy considered a lint tool, or a testing tool? (for requirements inclusion)

I think this belongs with our linters.

> Is there a particular entry point or an area of focus? We can also follow the recommended path

There are some existing types that @fizyk did that could be a good starting point. Other good starting points would be our more critical codepaths.

> Where do we want to configure mypy? I'm partial to pyproject.toml, but that's not currently mounted to the developer container - should we mount that as well?

Using `pyproject.toml` is preferable, and this should already be getting included in the dev container, as there's configuration for other linters and pytest in there as well

**Comment by miketheman** [comment]
I think this can be closed now, as we have a mechanism for adding more types as gradually as we want to now.
