### ISSUE TITLE
broken links to Google BigQuery

### ISSUE THREAD

**Issue by milahu** [pypa/warehouse#10900]
these pages have broken links to Google BigQuery

* https://pypistats.org/about
* https://pypistats.org/api/

working links

* https://console.cloud.google.com/search;q=bigquery-public-data:pypi
* https://console.cloud.google.com/marketplace/product/gcp-public-data-pypi/pypi

example SQL code

https://stackoverflow.com/a/71414912/10440128

**Comment by ewdurbin** [comment]
Hi @milahu, pypistats.org is not hosted by PyPI itself, please report this to the pypistats.org project: https://github.com/hugovk/pypistats

**Comment by Ark-kun** [comment]
The Warehouse documentation is very confusing about this.
It says "We use BigQuery to serve our public datasets. PyPI offers two tables ...", but never actually links to those "two tables".

https://warehouse.pypa.io/api-reference/bigquery-datasets.html?highlight=bigquery

**Comment by di** [comment]
You might find https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/ to be more helpful.
