### ISSUE TITLE
PyPi Download Counts and Warehouse Migration

### ISSUE THREAD

**Issue by tlee0818** [pypa/warehouse#10979]
I'm asking this question here because it seemed like the discussions tab was inactive. 

I did a download count analysis on PyPi's projects, and found something interesting.

https://imgur.com/a/ZUWf28B

There is a significant jump in the number of downloads of PyPi projects from July 2018 to August 2018.

I saw that that's around the time when PyPI migrated to a new backend, Warehouse, in late April. Might this have affected the number of download counts? If so, how?

If anyone has any answers, that would be great. Thanks!

**Comment by di** [comment]
Yep. See https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/#caveats for an explanation.
