### ISSUE TITLE
Remove "em". 

### ISSUE THREAD

**Issue by paulteleo** [pypa/warehouse#10999]
**What's the problem this feature will solve?**
[em](https://pypi.org/project/em/) has a name collision with [empy](https://pypi.org/project/empy/).

**Describe the solution you'd like**
Remove em from PyPI. Alternatively, rename the package (e.g. emphasize-em).

**Additional context**
[](https://github.com/ikalnytskyi/em/issues/9)

**Comment by di** [comment]
Hi, thanks for the issue. We don't consider this a collision, `em` and `empy` are two different project names. In addition, we don't remove projects from PyPI unless they are malicious, and there is no way to rename a project.

Given that, I'm going to close this, but let us know if anything is unclear.
