### ISSUE TITLE
Version missing from release history but showing up in simple index

### ISSUE THREAD

**Issue by ahirschfeld-nv** [pypa/warehouse#10990]
**Describe the bug**

nvidia-ml-py version 375.53 shows up in the [simple index](https://pypi.org/simple/nvidia-ml-py/) but is not showing up in the [release history](https://pypi.org/project/nvidia-ml-py/#history) for either the project from a user perspective, or a maintainer perspective making it impossible to delete the version and upload one with the correct versioning.

**Expected behavior**

All versions should be visible in the release history.

**To Reproduce**

Find version 375.53 in the [simple index](https://pypi.org/simple/nvidia-ml-py/)
Find version 375.53 in the [release history](https://pypi.org/project/nvidia-ml-py/#history)

**My Platform**

This is not browser, version, or OS specific, this is a version listing issue.

**Additional context**

If I am missing something basic, such as the ability to update a version number, or if there are docs relating to fixing this kind of issue already, please link me to them, and make them more searchable, that would be greatly appreciated.

**Comment by di** [comment]
I'm not sure what happened but it appears that something went wrong during the upload of that artifact: It's available as a file in the 2.0 release: https://pypi.org/project/nvidia-ml-py/2.0/#files. PyPI also thinks it's an `.egg` file when it clearly isn't.

Given the age of this release , it seems likely that the uploader provided the wrong metadata at upload time and PyPI lacked sufficient checks to prevent the confusion, so this was valid at the time of upload. If this is causing problems for you, I'd suggest re-uploading the file with a modern version of `twine` to ensure the metadata is set correctly.

**Comment by ahirschfeld-nv** [comment]
Thank you!
