### ISSUE TITLE
How do we recognize our OSS dependencies?

### ISSUE THREAD

**Issue by stevepiercy** [pypa/warehouse#1099]
It would be nice to publicly recognize and support the OSS dependencies used in Warehouse. What's a good way to present this to the general public?

## Some examples
- https://axis.apache.org/axis/java/jmx/dependencies.html # generated automatically by maven, technically inclined, too much information, not very marketing-friendly
- https://us.pycon.org/2016/sponsors/#sponsor-321 
- https://developers.google.com/open-source/projects

## OSS Dependencies (add to the list)
Do we list *all* dependencies? For example Pyramid depends on WebOb, etc.
- Pyramid
- Another dependency

**Comment by dstufft** [comment]
I suspect that @nlhkabu is best positioned to figure out a way to add this into the overall design.

**Comment by nlhkabu** [comment]
We are planning on putting together a development credits page.  The initial intention for this was to credit contributors, but I don't see why we can't also highlight OSS dependencies.

I'm going to close this issue and add this suggestion to the existing issue to avoid duplication.
