### ISSUE TITLE
HTTP Error 403: The user '' isn't allowed to upload to project ''

### ISSUE THREAD

**Issue by mirecl** [pypa/warehouse#11013]
HTTP Error 403: The user '' isn't allowed to upload to project '***'. See https://test.pypi.org/help/#project-name for more information.
In **https://test.pypi.org/project/***/** have very old package ``(Released: May 15, 2016)`` and I don't load my package:(

But in **https://pypi.org/project/***/** don't have package and I can load )))

How do I use the test environment, only change the package name (for https://test.pypi.org) and then change it back (for https://pypi.org)?

**Comment by di** [comment]
Hi, thanks for the issue. PyPI and TestPyPI are completely separate (see https://packaging.python.org/en/latest/guides/using-testpypi/). If you can share the name in question, we can probably release it to you on TestPyPI.

**Comment by mirecl** [comment]
Now, for test using https://test.pypi.org/project/pprof-dev/
Address my package in prod https://pypi.org/project/pprof/

**Comment by di** [comment]
I added you as owner of https://test.pypi.org/project/pprof
