### ISSUE TITLE
Error 403 - The user isn't allowed to upload to project

### ISSUE THREAD

**Issue by roqueds** [pypa/warehouse#11059]
**Describe the bug**

INFO     Response from https://upload.pypi.org/legacy/:
         403 The user 'roqueds11' isn't allowed to upload to project 'Basic-Calculator'. See
         https://pypi.org/help/#project-name for more information.

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, please see https://pypi.org/help/#project-name for more details.
