### ISSUE TITLE
Interceptor path is hardcoded!

### ISSUE THREAD

**Issue by hubertqtf** [pypa/warehouse#11058]
```
def interceptor(request):
    if request.url == 'https://server.com/some/path':
        request.create_response(
            status_code=200,
            headers={'Content-Type': 'text/html'},  # Optional headers dictionary
            body='<html>Hello World!</html>'  # Optional body
        )

driver.request_interceptor = interceptor
driver.get(...)

# Requests to https://server.com/some/path will have their responses mocked
```

This is documentation about mock response, line:
`if request.url == 'https://server.com/some/path'`
is hardcoded!

A lot of requests have dynamic values in them. In my case, the request has node_id coded into it, and my test gets that `node_id` value in runtime!
Your documentation, in my opinion, has knowingly hardcoded paths in every place!

I need to find a request with a dynamic value in it, and mock the response, to check if the browser properly displays data, that normally takes a month to get. Tried to use a lambda expression, but your validator refuses any other arguments in the interceptor method! For me, thats a wall I cannot pass now.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
