### ISSUE TITLE
Broken link to docker-compose.yml

### ISSUE THREAD

**Issue by zuma89** [pypa/warehouse#11097]
**Describe the bug**

When click on "An example composefile is [provided](https://pypi.org/project/pypiserver/docker-compose.yml)." Its throws error 404.

![Screenshot from 2022-04-04 00-07-18](https://user-images.githubusercontent.com/1813198/161437143-555ce4f7-0bc2-4cf2-a25b-35e44d3974d1.png)

**Expected behavior**

It should provide a RAW format of a sample docker-compose.yml 

**To Reproduce**

1. Go to the section [Using the Docker Image](https://pypi.org/project/pypiserver/#using-the-docker-image) 
2. Scroll toward the end of section (just before [Alternative Installation Methods](https://pypi.org/project/pypiserver/#alternative-installation-methods) there's a link written "An example composefile is [provided](https://pypi.org/project/pypiserver/docker-compose.yml)".
3. Click on it will throw page not found error.

**My Platform**

OS: Ubuntu 20.04.4 LTS
Browser: Google Chrome Version 100.0.4896.60 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
