### ISSUE TITLE
Cannot receive verification emails

### ISSUE THREAD

**Issue by rhatto** [pypa/warehouse#11128]
**Describe the bug**

I'm not receiving verification emails for [my account](https://pypi.org/user/rhatto/).

Verification emails are working properly with my [testing account at test.pypi.org](https://test.pypi.org/user/rhatto/), but the same setup in [my pypi.org account](https://pypi.org/user/rhatto/) is not working.

**Expected behavior**

Receiving a confirmation email for each address configured in my account.

**To Reproduce**

0. Create an account via https://pypi.org/account/register/
1. Go to https://pypi.org/manage/account/#account-emails and request a verification email.
2. The system shows a "Verification email for XXX@YYY resent" message, but no message arrives even after some hours.
3. Problem happens with both primary and non-primary email addresses.

**My Platform**

The problem does not seem to be related with my platform, but anyway I was using Firefox ES 91.7.0esr (64-bit) on Debian 11.3.

**Additional context**

This issue might be related to [a recent downtime in PyPI](https://status.python.org/incidents/mxgkk3xxr9v7).

**Comment by di** [comment]
I'm seeing all emails sent to both your email addresses marked as delivered by your mail providers:

Your primary address:
<img width="973" alt="2" src="https://user-images.githubusercontent.com/294415/161988361-c5016455-d355-4d89-bbfb-5a8a4e71e8bc.png">
Your secondary address:
<img width="976" alt="1" src="https://user-images.githubusercontent.com/294415/161988350-06821941-eea3-4449-8dea-7cb13fb4e67a.png">

I'd recommend checking spam/junk folders.

**Comment by rhatto** [comment]
Checked and confirm that those messages were tagged as spam (contrary to test.pypi.org messages). Then I was able to verify my email addresses. Thanks :)

**Comment by sumitkanoje** [comment]
Hi Team,

I'm facing same issue. Just opened a new account on PyPi.
Received verification mail form [test.pypi.org](https://test.pypi.org/user/rhatto/) server

But have not received verification mail from [pypi.org](https://pypi.org/) server
Checked my spam folder many time

**Comment by Dev-king-coder** [comment]
Hi there,
I'm facing same issue. Just opened a new account on PyPi.
Received verification mail form [test.pypi.org](https://test.pypi.org/user/rhatto/) server

But have not received verification mail from [pypi.org](https://pypi.org/) server
Checked my spam folder many time

**Comment by viralRupani** [comment]
I am also not receiving email verification at [test.pypi.org]("test.pypi.org")

**Comment by henrymcbean** [comment]
Not receiving email to rest password.
