### ISSUE TITLE
sometime this week, all our previous SDK releases became unavailable.

### ISSUE THREAD

**Issue by BrianMouncer** [pypa/warehouse#11169]
**Describe the bug**
We have many years of package versions available on PyPi.org.
Last week they were all available, e.g. you could PIP install older versions of our SDK like 1.15.0.
Sometime this week, all but the current/latest version of our SDK stopped working.
They still show up as valid package version on PyPi.org web search, but the PIP command started failing sometime this week.

**Expected behavior**
I expect PIP install to work for not only the current package release, but all older version too.
 
**To Reproduce**

C:\git\spx\spx>pip install azure-cognitiveservices-speech==1.14.0
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech==1.14.0 (from versions: 1.20.0)
ERROR: No matching distribution found for azure-cognitiveservices-speech==1.14.0

C:\git\spx\spx>pip install azure-cognitiveservices-speech==1.16.0
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech==1.16.0 (from versions: 1.20.0)
ERROR: No matching distribution found for azure-cognitiveservices-speech==1.16.0

C:\git\spx\spx>pip install azure-cognitiveservices-speech==1.19.0
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech==1.19.0 (from versions: 1.20.0)
ERROR: No matching distribution found for azure-cognitiveservices-speech==1.19.0

C:\git\spx\spx>pip install azure-cognitiveservices-speech==1.20.0
Collecting azure-cognitiveservices-speech==1.20.0
  Using cached azure_cognitiveservices_speech-1.20.0-cp310-cp310-win_amd64.whl (1.7 MB)
Installing collected packages: azure-cognitiveservices-speech
Successfully installed azure-cognitiveservices-speech-1.20.0

**My Platform**

I'm trying this on windows, but this also fails on our Ubuntu CiCd pipeline that produces docker images for the SDK...

**Additional context**

I was able to install 1.15.0 last week, and we have not uploaded any new package versions, or changed anything on PyPi.org since the last time I successfully installed an older version of the Speech SDK.

**Comment by di** [comment]
Is it possible you're trying to install with Python 3.10? I see that the latest release has built distributions for Python 3.7, 3.8, 3.9 and 3.10 but previous versions don't have built distributions for 3.10. None of the releases publish source distributions either, so pip can't fall back on building from source when there is no appropriate built distribution.

**Comment by BrianMouncer** [comment]
> Is it possible you're trying to install with Python 3.10? I see that the latest release has built distributions for Python 3.7, 3.8, 3.9 and 3.10 but previous versions don't have built distributions for 3.10. None of the releases publish source distributions either, so pip can't fall back on building from source when there is no appropriate built distribution.

You are correct.  Apparently all our machines auto installed an update and now have python 3.10 as the default python.
This makes the older packages disappear.  If I select python 3.9 or lower, they come back.

Thank you for the better set of eyes!
