### ISSUE TITLE
Refactor Warehouse's Auth{N,Z} to use Pyramid 2.0-style security policies

### ISSUE THREAD

**Issue by woodruffw** [pypa/warehouse#11211]
Pyramid 2.x introduces a [refactored AuthN/AuthZ system](https://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-2.0.html#upgrading-auth-20), built around "security policies." These changes combine authentication and authorization into a single policy, and produce an "identity" that's more flexible than the concept of an authenticated user.

Why does Warehouse need this? The most immediate reason is that it simplifies the planned approach for #10970, which involves minting API tokens that aren't tied to any particular user. Because they aren't associated with a user identity, these tokens don't fit into the Pyramid 1.0 authentication scheme.

Here are some open things that need to be considered as part of this refactor:

* How are we going to handle multiple authentication policies? The current codebase uses [`pyramid_multiauth`](https://github.com/mozilla-services/pyramid_multiauth) to dispatch to multiple underlying providers, but that library doesn't support Pyramid 2.0-style policies yet. Tracking: https://github.com/mozilla-services/pyramid_multiauth/issues/28
* How much/how invasive will the `request.user` refactor be? That attribute currently pervades the codebase, and is currently assumed to be a `User` model (AFAICT). Should we remove that entirely, or keep it around as an `Optional[User]`?

Pinging @ewdurbin and @di for thoughts.

**Comment by di** [comment]
> How are we going to handle multiple authentication policies? The current codebase uses [pyramid_multiauth](https://github.com/mozilla-services/pyramid_multiauth) to dispatch to multiple underlying providers, but that library doesn't support Pyramid 2.0-style policies yet.

Given that that dependency looks fairly unmaintained, we might want to think about internalizing something similar instead.

> How much/how invasive will the `request.user` refactor be? That attribute currently pervades the codebase, and is currently assumed to be a `User` model (AFAICT). Should we remove that entirely, or keep it around as an `Optional[User]`?

We could probably minimize the blast radius of the refactor by keeping `request.user` around as a wrapper around `request.identity` that ensures the identity is a `User`.

**Comment by woodruffw** [comment]
> Given that that dependency looks fairly unmaintained, we might want to think about internalizing something similar instead.

Yep, I'm currently working on a `MultiSecurityPolicy` that will do this.

**Comment by woodruffw** [comment]
Hmm, here's a hiccup: even 2.0-style security policies are dependent on `authenticated_userid`: https://docs.pylonsproject.org/projects/pyramid/en/latest/api/interfaces.html#pyramid.interfaces.ISecurityPolicy

Quote:

> [](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/interfaces.html#pyramid.interfaces.ISecurityPolicy.authenticated_userid)authenticated_[userid](https://docs.pylonsproject.org/projects/pyramid/en/latest/glossary.html#term-userid)(request)
>
> Return a userid string identifying the trusted and verified user, or None if unauthenticated.
>
> If the result is None, then [pyramid.request.Request.is_authenticated](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.is_authenticated) will return False.

**Comment by woodruffw** [comment]
> Hmm, here's a hiccup: even 2.0-style security policies are dependent on `authenticated_userid`: https://docs.pylonsproject.org/projects/pyramid/en/latest/api/interfaces.html#pyramid.interfaces.ISecurityPolicy
> 
> Quote:
> 
> > authenticated_[userid](https://docs.pylonsproject.org/projects/pyramid/en/latest/glossary.html#term-userid)(request)
> > Return a userid string identifying the trusted and verified user, or None if unauthenticated.
> > If the result is None, then [pyramid.request.Request.is_authenticated](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.is_authenticated) will return False.
> 
> Given that, we'll probably still need some kind of special "sentinel" `userid` value that indicates the absence of a real user, which defeats most of the point of the refactor.

I was wrong about this; I think it'll be okay.

**Comment by leplatrem** [comment]
> Given that that dependency looks fairly unmaintained, we might want to think about internalizing something similar instead.

Don't hesitate to reach out next time 😉 

We maintain it. Dependabot PRs are merged. It's stable and doesn't have issues 😅  
I just started recently to work on a Pyramid 2 security policy. But we could have joined efforts 😊
