### ISSUE TITLE
Refactor rollup: post #11218

### ISSUE THREAD

**Issue by woodruffw** [pypa/warehouse#11253]
Once #11218 is merged, we should perform a couple of low-hanging refactoring tasks:

* Save some indentation by failing early: https://github.com/pypa/warehouse/pull/11218#discussion_r856930497, https://github.com/pypa/warehouse/pull/11218#discussion_r858010327
* Deduplicate authentication code between POST handler for logins and HTTP basic auth: https://github.com/pypa/warehouse/pull/11218#discussion_r856935274

**Comment by woodruffw** [comment]
Some other refactor items: https://github.com/pypa/warehouse/pull/11333#issuecomment-1117633736

**Comment by di** [comment]
@woodruffw Is there more to do here or should this be closed?

**Comment by woodruffw** [comment]
Yep, this is done.
