### ISSUE TITLE
Not allowed to upload project

### ISSUE THREAD

**Issue by lbluque** [pypa/warehouse#11270]
**Describe the bug**

I am attempting to upload a project to PyPI using twine, but get the following error:
```
 403 The user 'lbluque' isn't allowed to upload to project 'smol'. See https://pypi.org/help/#project-name for more information.    
```
After looking at the link in the error message, I am unsure why the project name is not allowed. It is not used by any project I can find on PyPI. Perhaps too similar to some or prohibited? but I still don't think so.

Same error occurs when trying to upload to TestPyPI

**Expected behavior**

I would like to be able to use the project name `smol` since it does not seem to clash with current projects on PyPI, and I guess it is not prohibited.
**To Reproduce**

**Comment by di** [comment]
This project has been registered by another user, but has no releases. It likely would qualify as an abandoned project, please file a PEP 541 request here to start the process of acquiring it: https://github.com/pypa/pypi-support/issues/new/choose
