### ISSUE TITLE
aws-sam-translation installation issue.

### ISSUE THREAD

**Issue by SarveshRideCell** [pypa/warehouse#11344]
Hi, I am Sarvesh and was trying to install aws-sam-translation==1.4.5 on the machine, and I get this error.
(https://user-images.githubusercontent.com/98031249/167072354-d9448619-8fa5-4873-b030-912a2e4e3c2b.png)
but on release page it shows https://pypi.org/project/aws-sam-translator/1.45.0/#history. as latest, Can you see, what is the issue, please.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
