### ISSUE TITLE
Package incompatibility

### ISSUE THREAD

**Issue by zangzsien** [pypa/warehouse#11377]
Pycrypto and pycryptohome are different in the new function of AES. Their encrypt function requires different parameters. The former can also execute str normally, while the latter needs to encode str
![image](https://user-images.githubusercontent.com/39982331/167977509-8a163423-1ab2-4102-badf-fb98f22bfc5a.png)

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by zangzsien** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
