### ISSUE TITLE
Timestamps calculated at different times are the same for python3.6

### ISSUE THREAD

**Issue by AlphaJin95** [pypa/warehouse#11410]
I want to calculate the timestamps at different times. On the linux server, I call the package time that comes with python, but the timestamps of 2:00 a.m. on April 15, 1990 and 3:00 a.m. on April 15, 1990 are the same Yes, I want to ask if it is the problem of the python package itself, thank you

Python 3.6.9 (default, Jan 26 2021, 15:33:00)

[GCC 8.4.0] on linux

Type "help", "copyright", "credits" or "license" for more information.

$import time

$time.mktime(time.strptime(str('1990-04-15 02:00:00'), '%Y-%m-%d %H:%M:%S'))

$640116000.0

$time.mktime(time.strptime(str('1990-04-15 03:00:00'), '%Y-%m-%d %H:%M:%S'))

$640116000.0

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
