### ISSUE TITLE
Add support for cyrillic in projects' READMEs

### ISSUE THREAD

**Issue by ItsAleph** [pypa/warehouse#11474]
I've noticed that cyrillic not works here: https://pypi.org/project/cb-i18n

**Comment by di** [comment]
It looks like this is potentially an issue with the way you're providing the contents of your README? What PyPI is displaying is exactly what's present in the `PKG-INFO` for your package:

    root@7933bff455b9:/# wget https://files.pythonhosted.org/packages/e0/3a/c8cccc91c58526e4ba4fb6099ae3b2d143e72b5ab02974596ddda8fcc283/cb_i18n-1.0.4.tar.gz
    --2022-05-31 22:13:06--  https://files.pythonhosted.org/packages/e0/3a/c8cccc91c58526e4ba4fb6099ae3b2d143e72b5ab02974596ddda8fcc283/cb_i18n-1.0.4.tar.gz
    Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.1.63, 151.101.65.63, 151.101.129.63, ...
    Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.1.63|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 5201 (5.1K) [application/x-tar]
    Saving to: ‘cb_i18n-1.0.4.tar.gz’

    cb_i18n-1.0.4.tar.gz                                                           100%[===================================================================================================================================================================================================>]   5.08K  --.-KB/s    in 0s

    2022-05-31 22:13:06 (36.8 MB/s) - ‘cb_i18n-1.0.4.tar.gz’ saved [5201/5201]

    root@7933bff455b9:/# tar -xvvf cb_i18n-1.0.4.tar.gz
    drwxrwxrwx 0/0               0 2022-04-21 11:36 cb_i18n-1.0.4/
    -rw-rw-rw- 0/0            1084 2022-04-21 11:34 cb_i18n-1.0.4/LICENSE
    -rw-rw-rw- 0/0            4950 2022-04-21 11:36 cb_i18n-1.0.4/PKG-INFO
    -rw-rw-rw- 0/0            4139 2022-04-21 11:34 cb_i18n-1.0.4/README.md
    drwxrwxrwx 0/0               0 2022-04-21 11:36 cb_i18n-1.0.4/cb_i18n/
    -rw-rw-rw- 0/0              53 2022-04-21 11:34 cb_i18n-1.0.4/cb_i18n/__init__.py
    -rw-rw-rw- 0/0            4746 2022-04-21 11:34 cb_i18n-1.0.4/cb_i18n/translator.py
    drwxrwxrwx 0/0               0 2022-04-21 11:36 cb_i18n-1.0.4/cb_i18n.egg-info/
    -rw-rw-rw- 0/0            4950 2022-04-21 11:36 cb_i18n-1.0.4/cb_i18n.egg-info/PKG-INFO
    -rw-rw-rw- 0/0             192 2022-04-21 11:36 cb_i18n-1.0.4/cb_i18n.egg-info/SOURCES.txt
    -rw-rw-rw- 0/0               1 2022-04-21 11:36 cb_i18n-1.0.4/cb_i18n.egg-info/dependency_links.txt
    -rw-rw-rw- 0/0               8 2022-04-21 11:36 cb_i18n-1.0.4/cb_i18n.egg-info/top_level.txt
    -rw-rw-rw- 0/0              42 2022-04-21 11:36 cb_i18n-1.0.4/setup.cfg
    -rw-rw-rw- 0/0             998 2022-04-21 11:35 cb_i18n-1.0.4/setup.py

    root@7933bff455b9:/# cat cb_i18n-1.0.4/PKG-INFO
    Metadata-Version: 2.1
    Name: cb_i18n
    Version: 1.0.4
    Summary: Advanced internationalisation (i18n) support for Discord bots, originally developed for ClansBot
    Home-page: https://github.com/LiTechO/cb-i18n
    Author: weerdy15
    License: MIT
    Project-URL: Issue tracker, https://github.com/LiTech/cb-i18n/issues
    Platform: UNKNOWN
    Classifier: Development Status :: 5 - Production/Stable
    Classifier: Intended Audience :: Developers
    Classifier: Natural Language :: English
    Classifier: Programming Language :: Python :: 3.8
    Classifier: Programming Language :: Python :: 3.9
    Classifier: Programming Language :: Python :: 3.10
    Classifier: Topic :: Utilities
    Requires-Python: >=3.8.0
    Description-Content-Type: text/markdown
    License-File: LICENSE

    # cb-i18n

    Advanced internationalisation (i18n) support for Discord bots

    This module works with any well-known Discord API library for Python, including:

    - [discord.py](https://github.com/Rapptz/discord.py) (and any derived libraries such as [disnake](https://github.com/DisnakeDev/disnake), [nextcord](https://github.com/nextcord/nextcord) and [pycord](https://github.com/Pycord-Development/pycord))
    - [hikari.py](https://github.com/hikari-py/hikari)

    ### Installation

    Install with pip:

    ```sh
    # Linux / MacOS
    python3 -m pip install cb-i18n

    # Windows
    py -3 -m pip install cb-i18n
    ```

    Install from source:

    ```sh
    git clone https://github.com/LTT/cb-i18n
    cd cb-i18n
    python3 setup.py install

    # Windows
    git clone https://github.com/LTT/cb-i18n
    cd cb-i18n
    py -3 setup.py install
    ```

    ### Example usage of `cb-i18n`:

    *In fact, this library can work with just any application written in python. The first arg in `Translator.translate` can be **anything**, you can pass integer, string, custom object or even module, all will work as expected by you. Internally, lib does nothing with that "context", it just passing it to your `locale_getter` and all.*

    Directory structure:

    ```
    src/
      languages/
        en-US.json
        ru-RU.json
      main.py
    ```

    `src/languages/en-US.json`:
    ```json
    {
      "Hello {}": "Hello {}", // Positional placeholders
      "You're a Genius!": "You're a Genius!", // No placeholders
      "Locale is now {locale}": "Locale is now {locale}" // Keyword-only placeholders
    }
    ```

    `src/languages/ru-RU.json`:
    ```json
    {
      "Hello {}": "РџСЂРёРІРµС‚ {}",
      "You're a Genius!": "Р”Р° С‚С‹ РіРµРЅРёР№!",
      "Locale is now {locale}": "РЇР·С‹Рє С‚РµРїРµСЂСЊ {locale}"
    }
    ```

    `src/main.py`:
    ```py
    import sqlite3
    import disnake
    from disnake.ext import commands
    import cb_i18n as i18n

    bot = commands.Bot("!", intents=disnake.Intents.all())

    connection = sqlite3.connect('mydatabase.db')
    cursor = connection.cursor()

    translator = None
    _ = None

    def get_locale(ctx: commands.Context):
        return cursor.execute("SELECT locale FROM guilds WHERE id = ?;", ctx.guild.id).fetchone()[0]

    @bot.event
    async def on_ready():
        print("Bot loading")

        cursor.execute("CREATE TABLE IF NOT EXISTS guilds (id bigint, locale text);")
        connection.commit()

        print("  Loading guilds table...")
        for guild in bot.guilds:
            if not cursor.execute("SELECT * FROM guilds WHERE id = ?", guild.id).fetchone():
                print("    Guild {}: not exist".format(guild.id))

                cursor.execute("INSERT INTO guilds VALUES (?, ?);", guild.id, "en-US")
                connection.commit()
            else:
                print("    Guild {}: exists".format(guild.id))
        print("  Loaded guilds table.")

        print("  Loading i18n...")
        global translator, _

        translator = i18n.make_translator()
        translator.set_locale_dir("./languages/")
        translator.set_locale_getter(get_locale)
        translator.load_translations()
        _ = translator.translate
        print("  Loaded i18n.")

        print("Bot ready!\nAccount: {} (ID: {})\nGuild count: {}\nUser count: {}".format(str(bot.user), bot.user.id, len(bot.guilds), len(bot.users)))

    @bot.command(description="Set locale for a guild", aliases=["setlocale", "set-locale"])
    async def set_locale(ctx: commands.Context, locale: str):
        cursor.execute("UPDATE guilds SET locale = ? WHERE id = ?;", locale, ctx.guild.id)
        connection.commit()

        return await ctx.send(_(ctx, "Locale is now {locale}").format(locale=locale))

    @bot.command(description="Say hi!")
    async def hi(ctx: commands.Context, name: str):
        return await ctx.send(_(ctx, "Hello {}").format(name))

    @bot.command(description="You're Genius, right?")
    async def genius(ctx: commands.Context):
        return await ctx.send(_(ctx, "You're a Genius!"))

    try:
        bot.run(os.environ.get("BOT_TOKEN"))
    except Exception as exc:
        print(exc.__class__.__name__ + ": " + exc.__str__() + "".join(tb.format_exception(exc)))
    finally:
        cursor.close()
        connection.close()
    ```

**Comment by di** [comment]
Closing this, as I don't believe PyPI has any issue with displaying Cyrillic characters (see for example, https://pypi.org/project/g2p-kz/).

**Comment by wolkolak** [comment]
i got an issiue though. At least in hyperlink

**Comment by di** [comment]
There seems to be something wrong with how this wheel was built. The [source distribution](https://test-files.pythonhosted.org/packages/ed/a9/65471669db312625d5c06d5146099edf408692f5f850ba16185dac029e94/token_posfix_calculation-14.0.tar.gz) has a `README.md` that says:

```
Used algorithm from **[Алгоритм сортировочной станции](https://ru.wikipedia.org/wiki/Алгоритм_сортировочной_станции)** ,
also known as **[Shunting yard algorithm](https://en.wikipedia.org/wiki/Shunting_yard_algorithm)**. I used less detailed russian wiki and had no choice but improove it a little - degree('^') handler added. Unary minus was created too - better fix negatives in postfixing than in calculating.
```
but the [wheel](https://test-files.pythonhosted.org/packages/78/96/19f80bcbeb4a12cd5c27893d9f3ef146a871914a2bca03f19d380cfa52f1/token_posfix_calculation-14.0-py3-none-any.whl) has:

```
Used algorithm from **[РђР»РіРѕСЂРёС‚Рј СЃРѕСЂС‚РёСЂРѕРІРѕС‡РЅРѕР№ СЃС‚Р°РЅС†РёРё](https://ru.wikipedia.org/wiki/РђР»РіРѕСЂРёС‚Рј_СЃРѕСЂС‚РёСЂРѕРІРѕС‡РЅРѕР№_СЃС‚Р°РЅС†РёРё)** ,
also known as **[Shunting yard algorithm](https://en.wikipedia.org/wiki/Shunting_yard_algorithm)**. I used less detailed russian wiki and had no choice but improove it a little - degree('^') handler added. Unary minus was created too - better fix negatives in postfixing than in calculating.
```

and PyPI is just displaying what's in the wheel. It looks like you built this with `wheel==0.42.0`, can you try upgrading to https://pypi.org/project/wheel/0.43.0/ to see if that solves the problem? If not, I would recommend filing an issue at https://github.com/pypa/wheel/issues/new.
