### ISSUE TITLE
Newly-released package fails to install: 403 from CDN

### ISSUE THREAD

**Issue by antifuchs** [pypa/warehouse#11500]
**Describe the bug**

I just released `pulumi-honeycomb==0.0.11`, which is impossible to install due to an error that seems to originate on the pypi CDN:

```
Collecting pulumi-honeycomb==0.0.11
  ERROR: HTTP error 403 while getting https://files.pythonhosted.org/packages/9c/cd/a4923847851502a5ea8cee74338009da6aa07083482fc921cb3dc00f7702/pulumi_honeycomb-0.0.11.tar.gz#sha256=bfbed43b107842f9dde3fd30b0b1e47e110df7a6401ae9bea77f2dd58fca78a7 (from https://pypi.org/simple/pulumi-honeycomb/)
ERROR: Could not install requirement pulumi-honeycomb==0.0.11 from https://files.pythonhosted.org/packages/9c/cd/a4923847851502a5ea8cee74338009da6aa07083482fc921cb3dc00f7702/pulumi_honeycomb-0.0.11.tar.gz#sha256=bfbed43b107842f9dde3fd30b0b1e47e110df7a6401ae9bea77f2dd58fca78a7 (from -r requirements.txt (line 38)) because of HTTP error 403 Client Error: Forbidden for url: https://files.pythonhosted.org/packages/9c/cd/a4923847851502a5ea8cee74338009da6aa07083482fc921cb3dc00f7702/pulumi_honeycomb-0.0.11.tar.gz for URL https://files.pythonhosted.org/packages/9c/cd/a4923847851502a5ea8cee74338009da6aa07083482fc921cb3dc00f7702/pulumi_honeycomb-0.0.11.tar.gz#sha256=bfbed43b107842f9dde3fd30b0b1e47e110df7a6401ae9bea77f2dd58fca78a7 (from https://pypi.org/simple/pulumi-honeycomb/)
```

**Expected behavior**

Package gets downloaded & installation is attempted.

**To Reproduce**

`pip install pulumi-honeycomb==0.0.11`

Visiting these URLs above results in an error with `<Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message>`.

**My Platform**

OS: Linux (nixOS 21.11)

```
:;    python --version
Python 3.9.6
:;    pip --version
pip 21.1.3 from /nix/store/5isc0y4805gw20qf1wlsywvzfxs73h0x-python3.9-pip-21.1.3/lib/python3.9/site-packages/pip (python 3.9)
```

**Additional context**

**Comment by mullenkamp** [comment]
ditto:
https://files.pythonhosted.org/packages/6e/31/c34cfd091d71fa823217f47ca120e853e451f2a264f85b66c1b1fe3f0f87/nz-flow-naturalisation-0.1.4.tar.gz

**Comment by di** [comment]
Thanks for the report, we are looking into it, please follow along here for updates: https://status.python.org/incidents/bt0tzq7x2fk2?u=szv0ry9nhcbg

No need to add additional "me too"s at this time, please 👍 the OP instead.

**Comment by andrewleech** [comment]
FWIW it's not just new files - I just ran into this issue trying to install [v8-cffi](https://pypi.org/project/v8-cffi/) - this file in particular from 2016: https://files.pythonhosted.org/packages/0b/14/f24f90fa45f0ac2e990e483d9276bd049fd6ace4b6cbe7179e1fb9199d27/v8-cffi-0.2.1.tar.gz

**Comment by di** [comment]
This should now be resolved, please let us know if you are still able to reproduce.
