### ISSUE TITLE
Project-URL in format {name}{comma}{url} is rejected

### ISSUE THREAD

**Issue by stanislavlevin** [pypa/warehouse#11513]
**Describe the bug**

A project having `Project-URL: name,url` (without a space after comma) in metadata is rejected with:
```
Invalid value for project_urls. Error: Use both a label and an URL.
```
**Expected behavior**

According to https://packaging.python.org/en/latest/specifications/core-metadata/#project-url-multiple-use:
> Project-URL
> A string containing a browsable URL for the project and a label for it, separated by a comma.
>
> Example:
> Project-URL: Bug Tracker, http://bitbucket.org/tarek/distribute/issues/

But the validator wrongly expects comma+space `label, url = value.split(", ", 1)`:
https://github.com/pypa/warehouse/blob/630a5b574bc357c306b089cae690225d98285653/warehouse/forklift/legacy.py#L324-L326

**To Reproduce**

Try to publish a project with `Project-URL: name,url` (without a space after comma) in metadata.

**Comment by di** [comment]
I think the spec is a little ambiguous here, but since in practice we've been throwing away the whitespace, I don't see why we can't do:

```python
label, url = (x.strip() for x in value.split(",", 1))
```

Please feel free to send a PR.

**Comment by stanislavlevin** [comment]
@di, thank you for the provided solution.
