### ISSUE TITLE
Newly released package unavailable to pip install more than an hour after it was released

### ISSUE THREAD

**Issue by gibsondan** [pypa/warehouse#11512]
**Describe the bug**
This dagit 0.14.19 release went live an hour ago: https://pypi.org/project/dagit/0.14.19/

It's available over the pypi API: https://pypi.org/pypi/dagit/json

But running "pip install dagit==0.14.19" returns:
"ERROR: Could not find a version that satisfies the requirement dagit==0.14.19"

We've experienced some caching related delay with pypi releases before, but pip install failing more than an hour later is unusual, and usually once the version appears via the JSON API it is also available to install via pip install.

**Expected behavior**
pip install dagit==0.14.19 will work

**To Reproduce**
Run pip install dagit==0.14.19 in command line

**My Platform**
pip 22.1 on a Macbook

**Additional context**

**Comment by gibsondan** [comment]
I've verified that if I download the wheels for the new release from pypi, they install cleanly with the correct version - so this seems to be a case of pypi having old cached values for the set of versions that are currently available to install via pip.

**Comment by di** [comment]
Our CDN is having an outage which is preventing us from purging the cache: https://status.fastly.com/incidents/7pps2nn0r9q0

**Comment by billyc** [comment]
Good to know that it's being investigated. But note, the Python status page is still showing all green. Took me a long time trying to debug things because I thought the problem was on my end ;-) 

https://status.python.org/

**Comment by di** [comment]
@billyc Thanks, you should see it there now.

**Comment by gibsondan** [comment]
Fastly says that the issue has been resolved: https://status.fastly.com/incidents/7pps2nn0r9q0

But I'm still seeing the symptoms I reported here. Should I yank the release and re-publish?

**Comment by di** [comment]
Our cache is still stale, and will eventually come up to date over time, but I just manually purged the cache for `dagit` so installs for that project should work as expected.

**Comment by gibsondan** [comment]
Got it. There are actually a bunch of other packages that we released today that are still having the issue (basically everything that is prefixed with 'dagster-', maybe 30 packages or so?). I don't expect you to manually purge them all, but do you have a sense of roughly how long it will be for the cache to recover?

**Comment by di** [comment]
I've issued a purge for all simple index pages and all project detail pages on PyPI. I glanced at a couple `dagster-*` projects and they seem to be all up to date, but if there's any that haven't been purged, could you let me know here?

**Comment by di** [comment]
(if not, please feel free to close this issue!)

**Comment by gibsondan** [comment]
we're all set now, thanks!
