### ISSUE TITLE
Redirect error on pypi.python.org/.../json

### ISSUE THREAD

**Issue by ilyadrmx** [pypa/warehouse#11554]
**Describe the bug**

After a request for https://pypi.python.org/pypi/ANY_PACKAGE/json getting "Too many redirects"

**Expected behavior**

Expected to get package information 

**To Reproduce**

https://pypi.python.org/pypi/ANY_PACKAGE/json

**My Platform**

Google Chrome 101.0.4951.61
Android 12; M2102J20SG Build/SKQ1.211006.001

**Comment by ewdurbin** [comment]
See https://status.python.org/incidents/lgpr13fy71bk

**Comment by johnthagen** [comment]
This broke Poetry:

- https://github.com/python-poetry/poetry/issues/5826

**Comment by ilyadrmx** [comment]
Thank you
