### ISSUE TITLE
Redirect error on specific packages and accept-encoding request header

### ISSUE THREAD

**Issue by supermomonga** [pypa/warehouse#11567]
**Describe the bug**

When I request following endpoint with gzip accepted header for some package, it returns self-redirect location.

example:

- `curl 'https://pypi.org/pypi/numpy/1.22.4/json'` -> OK (200)
- `curl 'https://pypi.org/pypi/numpy/1.22.4/json' -H 'Accept-Encoding: gzip'` -> OK (200)
- `curl 'https://pypi.org/pypi/TA-Lib/0.4.24/json'` -> OK (200)
- `curl 'https://pypi.org/pypi/TA-Lib/0.4.24/json' -H 'Accept-Encoding: gzip'` -> NG (301 redirect loop)

`numpy` works as expected, but `TA-Lib` is not.

**Expected behavior**

The endpoint should not loop redirects.

**To Reproduce**

Using curl:

```sh
curl 'https://pypi.org/pypi/TA-Lib/0.4.24/json' -H 'Accept-Encoding: gzip'
# or
curl 'https://pypi.org/pypi/TA-Lib/0.4.24/json' --compressed
```

Using [requests](https://pypi.org/project/requests/) python package:

```py
import requests
requests.get('https://pypi.org/pypi/TA-Lib/0.4.24/json')
```

I think poetry using requests so `poetry add TA-Lib` will fail too. ref: https://github.com/python-poetry/poetry/issues/5826

**My Platform**

- Ubuntu 20.04
- Python 3.10.4
- [requests](https://pypi.org/project/requests/) 2.28.0

**Additional context**

- https://github.com/python-poetry/poetry/issues/5826
- https://github.com/pypa/warehouse/issues/11554
- https://status.python.org/incidents/lgpr13fy71bk

**Comment by ewdurbin** [comment]
This is likely a latent cache entry that failed to purge while mitigating the incident referenced.

I'm unable to reproduce this at this time, as the cache entry may have expired.

If you are still experiencing the issue, please re-open.
