### ISSUE TITLE
Wrong data reported from Pypi API

### ISSUE THREAD

**Issue by TG1999** [pypa/warehouse#11587]
**Describe the bug**
 The pypi API tells that `cryptography@37.0.2` has no dependency https://pypi.org/pypi/cryptography/37.0.2/json, (requires-dist is null) but in the METADATA file it is found that it has a dependency `Requires-Dist: cffi (>=1.12)`

**Expected behavior**
requires-dist in the API should report same dependency as in METADATA

**To Reproduce**
Download wheel for `cryptography@37.0.2` and check the METADATA file you can find this `Requires-Dist: cffi (>=1.12)`
https://pypi.org/pypi/cryptography/37.0.2/json the requires-dist is null

**Comment by miketheman** [comment]
Current behavior is a result of upload-time metadata, see: https://warehouse.pypa.io/api-reference/json.html#get--pypi--project_name--json:~:text=Metadata%20returned%20comes%20from%20the%20values%20provided%20at%20upload%20time%20and%20does%20not%20necessarily%20match%20the%20content%20of%20the%20uploaded%20files.

Related to #474 and #8090

**Comment by dstufft** [comment]
Closing as a duplicate to #474
