### ISSUE TITLE
python3.7 -m pip install paddlepaddle==2.0.0 -i https://mirror.baidu.com/pypi/simple  

### ISSUE THREAD

**Issue by KishoreElvicto** [pypa/warehouse#11611]
Looking in indexes: https://mirror.baidu.com/pypi/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=.HTTPSConnection object at 0x7f23b734a490>: Failed to establish a new connection:
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=.HTTPSConnection object at 0x7f23b73aaf50>: Failed to establish a new connection:
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=.HTTPSConnection object at 0x7f23b734a790>: Failed to establish a new connection:
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=.HTTPSConnection object at 0x7f23b734aa10>: Failed to establish a new connection:
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=.HTTPSConnection object at 0x7f23b734ad50>: Failed to establish a new connection:
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.0.
ERROR: No matching distribution found for paddlepaddle==2.0.0            

how to solve this

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not PyPI mirrors.

You should report this issue to the tracker for the project in question instead.
