### ISSUE TITLE
PyPI downloads page does not show all wheels available

### ISSUE THREAD

**Issue by colcrunch** [pypa/warehouse#11652]
**Describe the bug**
Earlier when trying to figure out why we could not get a specific package to install via pip I realized that not all wheels are shown under the "Built Distributions" section of a given package's download page.

**Expected behavior**
I would expect that the downloads page would show me all available wheels to download should I need to.

**To Reproduce**
A good example exists here:
https://pypi.org/project/mysqlclient/2.1.0/#files

Only `win_amd64.whl` files are shown, though `linux_x86_64.whl` versions do exist. 

**My Platform**
I am running Firefox 101.0.1 on Windows 11.

**Additional context**
I feel this is an important issue as it would be useful to be able to determine if an install issue lies with pip, pypi, or the package its self. From a lot of trial and error we were able to deduce that the mysqlclient package must just be missing linux distributions for 2.1.1, however, when we looked at 2.1.0 and also saw only windows distributions listed it added a lot of confusion as we know for a fact that they exist (as we were able to install 2.1.0).

**Comment by miketheman** [comment]
I can't confirm this issue yet - inspecting https://pypi.org/simple/mysqlclient/ and https://pypi.org/pypi/mysqlclient/json/ both confirm the same set of built distributions.

How are you confirming that `linux_x86_64.whl` versions exists?

**Comment by colcrunch** [comment]
I just realized that pip was grabbing source and building the wheel, so looks like it might be a different issue entirely.
