### ISSUE TITLE
Latest version not detected

### ISSUE THREAD

**Issue by mravanelli** [pypa/warehouse#11678]
Hi,
I just released the new version of speechbrain (0.5.12). Everything seems fine and the new version is available here:
https://pypi.org/project/speechbrain/0.5.12/
However, https://pypi.org/project/speechbrain/ still points to the previous version (and thus when I do "pip install speechbrain" it installs to the old version). This is the first time that this weird behavious happened. Any suggestion?

**Comment by mravanelli** [comment]
It took about 1 hour to update it. It was just slower than usual but everything is fine now!

**Comment by di** [comment]
FYI, this is likely a duplicate of https://github.com/pypa/warehouse/issues/10390
