### ISSUE TITLE
Users not receiving verification or reset password emails

### ISSUE THREAD

**Issue by simonpai** [pypa/warehouse#11682]
**Describe the bug**
Users not receiving verification email and reset password email. I tried to reset the password and register a new one, but I've receive no email from PyPI.

**Expected behavior**
* Users should receive email when reseting password.
* Users should receive verification email when registering a new account.

**To Reproduce**
From PyPI website, reset the password or register a new account.

**My Platform**
(irrelevant)

**Comment by iafisher** [comment]
I am also experiencing this issue.

**Comment by Darren-Chambers** [comment]
Me too

**Comment by TimeAshore** [comment]
Me too, I can't reset my password.

**Comment by andreonaymayer** [comment]
Me too, I have to verify my account

**Comment by di** [comment]
Sorry for the issues. We're investigating, please follow https://status.python.org/incidents/l16ylxktn4r9 for updates.

**Comment by miketheman** [comment]
I got my reset email about 25 minutes ago, after ~4 hours or so.

**Comment by simonpai** [comment]
I assume everything gets normal now? I am closing this issue. Thank PyPI teams for quick response!

**Comment by vidanovic** [comment]
I have this issue now
