### ISSUE TITLE
Most recent release not found on PyPi

### ISSUE THREAD

**Issue by danielward27** [pypa/warehouse#11696]
**Describe the bug**
Most recent version of package is not showing for the project. I.e. if I go here [https://pypi.org/project/flowjax/](https://pypi.org/project/flowjax/), the version shown is 0.9.0. Even on the release history it only shows up to version 0.9.0. However, a more recent release (1.0.0) is available on PyPi [https://pypi.org/project/flowjax/1.0.0/](https://pypi.org/project/flowjax/1.0.0/). 
Additionally if I try to install the most recent version, i.e.
```
pip install flowjax==1.0.0
```
I get:
```
ERROR: Could not find a version that satisfies the requirement flowjax==1.0.0
ERROR: No matching distribution found for flowjax==1.0.0
```
If I don't specify the version, version 0.9.0 is installed.

**Expected behavior**
I would expect [https://pypi.org/project/flowjax/](https://pypi.org/project/flowjax/) to show the most recent version, and pip to find and install the most recent version by default.

**Comment by zktuong** [comment]
same here with [sc-dandelion](https://pypi.org/project/sc-dandelion/)

**Comment by di** [comment]
Sorry for the issues. We're investigating, please follow https://status.python.org/incidents/l16ylxktn4r9 for updates.

**Comment by Areix** [comment]
same issue here https://pypi.org/project/areixio and it has been 8 hours

**Comment by di** [comment]
Please don't add 'same here' comments to this issue, we're aware that a large number of projects are affected, we've identified the issue, and it will be resolved shortly.

**Comment by di** [comment]
This has been resolved.
