### ISSUE TITLE
`wraps` name is not allowed

### ISSUE THREAD

**Issue by nekitdev** [pypa/warehouse#11714]
**Describe the bug**

I've tried to upload a package under `wraps` name, but for some reason it is not allowed:

```console
$ poetry publish

Publishing wraps (0.1.0) to PyPI
 - Uploading wraps-0.1.0-py3-none-any.whl FAILED

HTTP Error 400: The name 'wraps' isn't allowed. See https://pypi.org/help#project-name for more information.
```

**Expected behavior**

I expected the `wraps` name to be allowed.

**To Reproduce**

Attempt to upload a package under `wraps` name.

**My Platform**

Windows 11, `poetry` 1.2.0b2, though `twine` does not work either.

**Comment by di** [comment]
Hi, please see https://pypi.org/help/#project-name.

**Comment by nekitdev** [comment]
Is it explicitly prohibited? Because I don't think it collided with the standard library... perhaps `functools.wraps`?

**Comment by di** [comment]
It is explicitly prohibited but likely can be made available by following https://pypi.org/help/#project-name-claim.

**Comment by nekitdev** [comment]
I see. I'm going to file a request and see how it goes, then.
