### ISSUE TITLE
Permanent URL (Heroku "No such app" error)

### ISSUE THREAD

**Issue by di** [pypa/warehouse#1175]
I noticed that https://warehouse.python.org/ produces a `Heroku | No such app` error at the moment. Is this intentional? Are we permanently at https://pypi.io/ now?

If so, we should probably update the URL in a few places: https://github.com/pypa/warehouse/search?utf8=%E2%9C%93&q=%22warehouse.python.org%22

**Comment by dstufft** [comment]
#1176 should make ``warehouse.python.org`` redirect to ``https://pypi.io/`` but we are permanently at ``https://pypi.io/`` (and ``https://test.pypi.io/``) so we should still update those references.
