### ISSUE TITLE
PyPI does not always give a specific reason for why a name is not allowed

### ISSUE THREAD

**Issue by seanthegeek** [pypa/warehouse#11872]
**Describe the bug**
I received a client error `400` when I try to upload a package named `yaramail`

```text
(venv) sean@sean-desktop ~/d/yaramail (main)> hatch publish
Enter your username: Sean.Whalen
Enter your credentials:
dist/yaramail-1.0.0-py3-none-any.whl ... failed
Client error '400 The name 'yaramail' isn't allowed. See https://pypi.org/help/#project-name for more information.' for url 'https://upload.pypi.org/legacy/'
For more information check: https://httpstatuses.com/400
```
When I tried to upload `yara-mail` to Test PyPI after successfully uploading `yaramail` to Test PyPI, I got a much more specific error message that said the name was too similar to an existing project, until I deleted the `yaramail` project in Test PyPI.

```text
(venv) sean@sean-desktop ~/d/yaramail (main) [1]> hatch publish -r test
dist/yara_mail-1.0.0-py3-none-any.whl ... failed
Client error '400 The name 'yara-mail' is too similar to an existing project. See https://test.pypi.org/help/#project-name for more information.' for url 'https://test.pypi.org/legacy/'
For more information check: https://httpstatuses.com/400
```

**Expected behavior**

PyPI should always give a specific reason when a name is not allowed 

**To Reproduce**

Attempt to upload a project named `yaramail`.

**My Platform**
Ubuntu 20.04 LTS
Python 3.8.10
Hatch 1.3.1

**Comment by domdfcoding** [comment]
Related: https://github.com/pypi/warehouse/issues/11139

**Comment by di** [comment]
This error message is the result of the name being specifically prohibited. Would language like:

> The name 'yaramail' has been prohibited

make that more clear?

**Comment by seanthegeek** [comment]
Adding **why** it is prohibited would be helpful.

**Comment by di** [comment]
Just to push back on that a bit: why? The [process for acquiring the name](https://pypi.org/help/#project-name-claim) is the same regardless of the reason why the name is prohibited.

To give a bit more context: there are lots of reasons why a project name might be prohibited, and they might not all make sense to an end user, or make sense to share with the end user.
