### ISSUE TITLE
Make linting errors more specific

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1193]
I just had a HTML indentation linting error: https://travis-ci.org/pypa/warehouse/jobs/131053768

Error info:

```
home/travis/virtualenv/python3.5.1/bin/html_lint.py --disable=optional_tag `find ./warehouse/templates -path ./warehouse/templates/legacy -prune -o -name '*.html' -print`

61:1: Error: Indentation: Use two spaces and no tabs: Was expecting between 0 and 8 (in multiples of 2) spaces but got 9.
```

As far as I can tell the CI thread does not point me to the file or line number where the error is located - I had to find it manually.

Can we update our linter output to make these errors more specific?

**Comment by di** [comment]
@nlhkabu Agreed, this has bugged me before as well. I made a PR against `html-linter`: https://github.com/sk-/html-linter/pull/8 which should make these errors easier to interpret.

**Comment by nlhkabu** [comment]
Thanks @di :dancers:

**Comment by dstufft** [comment]
I love that Warehouse is extending out to improving other libs in the Python ecosystem :]
