### ISSUE TITLE
Temporarily Purge Legacy PyPI

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1194]
Uploading should temporarily purge legacy PyPI, currently if someone uploads to Warehouse they need to do something like:

```
$ curl -XPURGE https://pypi.python.org/simple/<name>/
$ curl -XPURGE https://pypi.python.org/pypi/<name>/json
```

To make sure that their upload shows up on PyPI without it having to fall out of the cache. Or they could go and hit save on PyPI legacy at least once to trigger the same thing. This is less than optimal and we should just temporarily do the purges for folks until legacy is retired.

**Comment by matthew-brett** [comment]
I've been doing some uploads to warehouse in the last few days - sure enough, the uploads don't show up for `pip` at once.  The XPURGE commands don't seem to have any effect, but doing an 'edit' of the project page, changing nothing, and clicking 'Add information' does seem to work.  I suppose this might just be coincidence, and the effective change is the short delay after upload before testing, but thought I'd report in any case.

On the other hand the twine uploads have been reliable so far, which is much better than pypi - so thanks much for that.
