### ISSUE TITLE
Move Conveyor back to using (test.)pypi.org

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1211]
Currently conveyor is configured to use `(test)pypi.python.org` to avoid a stale cache that occurs when someone uploads a file to legacy PyPI. Once we've switched to using Warehouse as our primary we should switch this back so that it uses `(test.)pypi.org` instead.

**Comment by dstufft** [comment]
We can do this now, prior to launch since uploads to legacy PyPI have been disabled.

**Comment by brainwane** [comment]
We talked about this in [today's Warehouse developers' meeting](https://wiki.python.org/psf/PackagingWG/2018-03-06-Warehouse); Ernest plans to deploy this to cabotage later this week.

**Comment by di** [comment]
This is done!
