### ISSUE TITLE
[Question] -- Beginner : Error in 'make build' from sources

### ISSUE THREAD

**Issue by mramanathan** [pypa/warehouse#1219]
Am following the detailed steps given in this page:

https://warehouse.readthedocs.io/development/getting-started/#detailed-installation-instructions

Am working on building warehouse from sources in AWS using Amazon Linux Image.

1. In the first run of 'make build' it failed with this error. In the 2nd run, however, it passed thru' this stage.

**ERROR: Service 'app' failed to build:** The command '/bin/sh -c set -x     && apt-get update     && apt-get install inotify-tools wget bzip2 gcc g++ make libpq-dev libjpeg-dev libffi-dev --no-install-recommends -y     && rm -rf node_modules     && wget https://saucelabs.com/downloads/sc-4.3.14-linux.tar.gz -O /tmp/sc.tar.gz     && tar zxvf /tmp/sc.tar.gz --strip 1 -C /usr/     && chmod 755 /usr/bin/sc     && npm install -g phantomjs-prebuilt gulp-cli     && npm install     && pip install -U pip setuptools     && pip install -r requirements/dev.txt                    -r requirements/tests.txt     && pip install -r requirements/deploy.txt                    -r requirements/main.txt     && find /usr/local -type f -name '*.pyc' -name '*.pyo' -delete     && rm -rf ~/.cache/     && apt-get purge bzip2 gcc g++ make libpq-dev libffi-dev -y     && apt-get autoremove -y     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1 make: *** [build] Error 1

2. Next step was to start 'make initdb' but this too failed with errors on multiple runs, while trying to update SQL table with SQL connection timeout errors (it was running to multiple lines). Are these known issues with possible resolutions ?

  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 200, in delete
    params=params)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 105, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3580214d68>: Failed to establish a new connection: [Errno 113] No route to host) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3580214d68>: Failed to establish a new connection: [Errno 113] No route to host)
make[1]: *** [reindex] Error 1
make[1]: Leaving directory `/home/ec2-user/github/warehouse'
make: *** [initdb] Error 2

TIA,
/Ram

**Comment by dstufft** [comment]
One thing that I'm not sure is obvious, when you're running ``make initdb`` it's assumed that you already have ``make serve`` running.

**Comment by mramanathan** [comment]
Do you mean run 'make server', then go over for 'initdb' ?

Just now tried running, 'make build' (3rd iteration), this time around, it's an reindex error:


docker-compose run web python -m warehouse search reindex
{"level": "INFO", "thread": 140579109558016, "logger": "raven.base.Client", "event": "Raven is not configured (logging is disabled). Please see the documentation for more information."}
{"level": "INFO", "thread": 140579109558016, "logger": "urllib3.connectionpool", "event": "Starting new HTTP connection (1): elasticsearch"}
. . . . . . 
. . . . . . 
{"level": "INFO", "thread": 140578851477248, "logger": "elasticsearch", "event": "POST http://elasticsearch:9200/_bulk [status:200 request:1.063s]"}
make[1]: *** [reindex] Error 137
make[1]: Leaving directory `/home/ec2-user/github/warehouse'
make: *** [initdb] Error 2

**Comment by dstufft** [comment]
You'll need two terminals open, one running ``make serve``, and one for you to do things like ``make initdb`` in.

**Comment by dstufft** [comment]
IOW, ``make serve`` is a persistent process that is running the web site, the DB server, etc.

**Comment by dstufft** [comment]
Huh, something is already bound to port ``80`` for you. I'm not sure what Amazon Linux has running in it though that might already be binding to that port.

**Comment by nlhkabu** [comment]
I'm going to close this issue - @mramanathan I hope this issue has been resolved for you.
If you need any further help, please speak to us on `pypa-dev` on freenode :)
