### ISSUE TITLE
Prevent rebuilding of all containers when changing package.json

### ISSUE THREAD

**Issue by karan** [pypa/warehouse#1221]
I added a dep in package.json and wanted to install the new package. Sadly, `make serve` causes the container(s) to install basically from scratch (from `apt-get update` on). Is there a better way to install additional packages or add new frontend js dependencies?

**Comment by dstufft** [comment]
There's not currently a better way no :/

**Comment by karan** [comment]
That sucks. I'll leave this open then until we can find a faster install process.

**Comment by karan** [comment]
@dstufft slightly off-topic: how would I include a new JS library? I can't find a place to put a js library in. Docs say use bower but I believe warehouse doesn't use that anymore.

To be more specific, I'm working on #818 and including clipboard.js file.

**Comment by dstufft** [comment]
``npm install --save -E clipboard``, then you should be able to import and use it inside of ``warehouse/static/js/warehouse/*``.

**Comment by karan** [comment]
@dstufft would i run that in the `app` container?  Can't run it in on the host OS because the `node_modules` folder isn't shared.

**Comment by dstufft** [comment]
@karan it'd install on the host because the main goal of that is to get the packages.json updated. You could also do it by hand if you wanted.

**Comment by karan** [comment]
@dstufft hmm so I'm pretty stuck - the frontend architecture is confusing me a lot.

So the simplest way to use clipboardjs is to just include the js file in the DOM. But there's no documentation on how to use it in ES6. Basically, all it should take is this:

```
// HTML
<script src="dist/clipboard.min.js"></script>

// JS
new Clipboard('.btn');
```

I installed the npm package, but can't import it.

`import "clipboard";`, or `import Clipboard from "clipboard";` don't work at all. I tried `require`ing too, but that too doesn't work.

Any ideas how I could import a js file from `node_modules` in the HTML?

**Comment by dstufft** [comment]
Once you add something to ``package.json`` you have to run ``make build`` again if you didn't do that. Then it should be just as simple as:

```javascript

import Clipboard from "clipboard";

docReady(() => {
    new Clipboard(".btn");
});
```

**Comment by karan** [comment]
Should've mentioned, that I did. After adding to `package.json`, I run `make serve` which rebuilt everything.

It still says `Uncaught TypeError: h.default is not a constructor` on `new Clipboard(".btn");`.

I'll rebuild the containers again although I doubt that'll change much.

**Comment by dstufft** [comment]
Ahh there's an error

**Comment by dstufft** [comment]
@karan Can you submit a PR with what you have so I can take a look?

**Comment by karan** [comment]
@dstufft #1223
