### ISSUE TITLE
Uploads to pypi.io don't trigger auto-hide old releases functionality in pypi.python.org

### ISSUE THREAD

**Issue by jaraco** [pypa/warehouse#1222]
It appears that [uploads to pypi.io are only syncing json metadata](https://github.com/pypa/setuptools/issues/589#issuecomment-223615124) and not updating the latest package [at the canonical location](https://pypi.python.org/pypi/setuptools).

I've tried [managing the project](https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=setuptools) to see what releases might be present, but that URL returns 500 after 30 seconds (probably a timeout), so I'm unable to assess exactly why pypi.python.org isn't showing the latest release.

**Comment by jaraco** [comment]
So the management interface did finally load, and as I suspected, the new releases are present in pypi.python.org; it's just that the older versions are not hidden:

![screen shot 2016-06-03 at 13 14 27](https://cloud.githubusercontent.com/assets/308610/15786937/32594e5a-298d-11e6-993c-9b7d0c11d40c.png)

**Comment by dstufft** [comment]
Ah yes, Warehouse doesn't use the hidden flag, so it didn't occur to me to update that.
