### ISSUE TITLE
Add disabled style to inputs

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1231]

**Comment by brainwane** [comment]
@nlhkabu Sorry, could you add a little more detail on what this task is? I'm not sure I understand. (I'm asking so we can check whether it's necessary for the launch or whether we can push it to the "feature parity" milestone.)

**Comment by nlhkabu** [comment]
We need to add a style for when inputs, textareas and selects are disabled, e.g. `<input type="text" name="name" disabled>`

We don't currently have any of these in the UI, so I have removed this from the launch milestone.

**Comment by nlhkabu** [comment]
I'm going to close this - it looks like we are not going to need it.
