### ISSUE TITLE
Copy button changes subpage navigation

### ISSUE THREAD

**Issue by alex** [pypa/warehouse#1232]
Instructions to reproduce:

- Browse to https://pypi.io/project/cryptography/
- Click "Download files"
- Press the "Copy" button next to "pip install cryptography"
- Notice that you are not on the download files page anymore

**Comment by dstufft** [comment]
Ahhh good catch. I wonder if this can be fixed by just dropped the href from the <a> tag. Maybe @karan can take a look?

**Comment by karan** [comment]
Ah yes I added `href="#"` which removes the current hash. I'll fix that!
