### ISSUE TITLE
IRC channel wrong

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1235]
On the help page, I accidently wrote `#pypa` rather than `#pypa-dev`:

![screenshot from 2016-06-04 22-38-03](https://cloud.githubusercontent.com/assets/3323703/15802289/1a2a7728-2aa5-11e6-977a-6784e163d51c.png)

**Comment by dstufft** [comment]
Actually, ``#pypa`` is one of our channels, and is the more user facing one.
