### ISSUE TITLE
Missing sponsor information

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1238]
Logos for footer:
- [x] HPE
- [x] StatusPage.io
- [x] Pingdom
- [x] Dyn
- [x] Amazon (AWS)
- [x] Mozilla

Content for sponsors page:
- [x] HPE
- [x] StatusPage.io
- [x] Pingdom
- [x] Dyn
- [x] Rackspace (they provided a logo, but no description)
- [x] Amazon (AWS)
- [x] Mozilla

**Comment by dstufft** [comment]
I think @jnoller is the best person to ask for the content for the sponsors page for Rackspace (we need a paragraph describing Rackspace-- Think like the paragraphs on [PyCon's sponsor page](https://us.pycon.org/2016/sponsors/).

I can poke the other people via email again.

**Comment by nlhkabu** [comment]
Thanks @dstufft.  In the short term I have removed these from the footer on pypi-theme.  I will make a PR soon.

**Comment by dstufft** [comment]
Just for the record, so I can point folks at this issue instead of repeating myself:

What we need is:

1. A white logo on a transparent background, ideally in ``.svg`` format. This is what will appear in the footer of every page (see https://pypi.io/ for an example of other logos).
2. A full color logo on a transparent background, ideally in ``.svg`` format. This will appear on the sponsors page (it will live at https://pypi.io/sponsors/ but that doesn't exist yet).
3. A paragraph describing your company for the sponsors page (for examples, see [PyCon's sponsor page](https://us.pycon.org/2016/sponsors/).
4. An URL that you'd like us to link to from the footer and sponsor page.
5. Permission to use all of the above on PyPI-- it will be kept in a private repository so that there is no confusion about what licenses apply to it etc.

You can email this stuff to me privately at donald@python.org.

**Comment by dstufft** [comment]
Oops, I found Pingdom's logo in my email-- I forgot to forward it to you. We still don't have a paragraph from them though.

**Comment by dstufft** [comment]
Ok, I've reached out to all of the above.

**Comment by jnoller** [comment]
use the paragraph from here: https://us.pycon.org/2016/sponsors/ - alas all I has are pngs
![rackspace_logo-blk](https://cloud.githubusercontent.com/assets/51528/16620342/b3dd3e12-4357-11e6-9c17-75c5adac7a1c.png)
![rackspace_logo-wht](https://cloud.githubusercontent.com/assets/51528/16620341/b3d46bac-4357-11e6-9496-496caa28c3f9.png)

**Comment by jnoller** [comment]
the second one should be white

**Comment by nlhkabu** [comment]
Thanks @jnoller :)

**Comment by dstufft** [comment]
Thanks @jnoller ✨

**Comment by ewdurbin** [comment]
furnishing statuspage.io's assets on behalf of @stevenklein et. al.

Logo (it's there i promise)

![statuspage_pypi 2](https://cloud.githubusercontent.com/assets/1200832/17352436/89105080-5904-11e6-9a8d-9e5ecd2cba09.png)

Blurb:

StatusPage is the best way to communicate the status of your service with your end-users. We’ve entered an era where almost every company relies on external cloud services. The number of moving pieces and woven dependencies all but insures that even the most well-prepared companies will have the occasional outage. End-users will forgive the occasional downtime if you treat them well by keeping them in the loop when this happens. Thousands of the top companies in web tech rely on StatusPage to communicate with their customers when they’re experiencing outages or degraded performance.

**Comment by pradyunsg** [comment]
@nlhkabu StatusPage.io can be ticked off in the description?

**Comment by dstufft** [comment]
Done

**Comment by brainwane** [comment]
So it looks like what we're missing here is graphics, text, URL, and permission from Amazon and from Mozilla. @dstufft would you ping Amazon and Mozilla again and let them know that we would really like this within the next few weeks?

**Comment by MarkMangoba** [comment]
![aws_logo_smile_1200x630](https://user-images.githubusercontent.com/17626251/37113275-bf462818-21f9-11e8-9c47-9d7997eaa534.png)

Attached is the Amazon Web Services Logo approved for use.  Will touch base with @bwaliszewski on the approved description.

**Comment by di** [comment]
Should we add DataDog? We're definitely using it for Warehouse and I believe the service is being donated.

Should we remove Heroku? I assume they're still donating infra for the PSF but they aren't directly being used by Warehouse.

**Comment by ewdurbin** [comment]
can we get the logo & blurb for status page loaded in from https://github.com/pypa/warehouse/issues/1238#issuecomment-237120940?

**Comment by nlhkabu** [comment]
Status page PR done: https://github.com/python/pypi-theme/pull/23

**Comment by brainwane** [comment]
@MarkMangoba I presume we are still waiting for Mozilla, and I presume the sponsorship we want to mention is the MOSS award?

@nlhkabu Some resources we could maybe use as placeholders while we wait for the final info from Mozilla:

* https://wiki.mozilla.org/MOSS/Talking_About_Your_MOSS_Award
* https://www.mozilla.org/en-US/styleguide/

**Comment by nlhkabu** [comment]
Issues opened on PyPI theme for Datadog https://github.com/python/pypi-theme/issues/29
