### ISSUE TITLE
Predictable file URLs

### ISSUE THREAD

**Issue by toddrme2178** [pypa/warehouse#1239]
It used to be that pypi had urls for files that followed predictable a predictable pattern.  Specifically, the download was of the form `http://pypi.python.org/packages/source/{first letter of package name}/{package name}/{file name}`.  This made it great for automated validation and downloads, since once you got the pattern it would work for all future versions.  The current file names, however, don't have any obvious pattern, instead using some sequence of characters like `https://files.pythonhosted.org/packages/ae/98/3b27e0a3c53ec0d6727eb19da46eed5705fa9250ed28ec0d1df48778c401/Django-1.10a1.tar.gz`.  I think for third-party tools having a simple, predictable file name would be really helpful.  It wouldn't have to be the same pattern, but something that follows a consistent, predictable pattern.

**Comment by dstufft** [comment]
You can use ``https://files.pythonhosted.org/packages/sources/D/Django/1.10.a1.tar.gz``, it will redirect to the correct URL.

**Comment by toddrjen** [comment]
Good to know, but I think it would still be useful if the Downloads list used this URL as well.  This would make it easier for automated scripts, such as package generators, to find.

**Comment by minrk** [comment]
Is there an equivalent predictable URL for wheels, etc.?

**Comment by hobarrera** [comment]
> Is there an equivalent predictable URL for wheels, etc.?

I'd like to subscribe to this, I can't find any predictable URL for wheels either.
