### ISSUE TITLE
Change 'projects' to 'packages'

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1250]
All of these examples should say 'packages' instead of 'projects':

![screenshot from 2016-06-09 08-50-00](https://cloud.githubusercontent.com/assets/3323703/15922383/381c95d6-2e1f-11e6-888c-0e41bbc6373c.png)
![screenshot from 2016-06-09 08-49-54](https://cloud.githubusercontent.com/assets/3323703/15922384/3821a800-2e1f-11e6-9748-a91ec43f1d5e.png)
![screenshot from 2016-06-09 08-49-50](https://cloud.githubusercontent.com/assets/3323703/15922385/3824781e-2e1f-11e6-8c45-e17b2dbf36ec.png)
![screenshot from 2016-06-09 08-50-50](https://cloud.githubusercontent.com/assets/3323703/15922404/52632b94-2e1f-11e6-9017-603eb6b7e26f.png)
![screenshot from 2016-06-09 08-52-45](https://cloud.githubusercontent.com/assets/3323703/15922442/92db7fb4-2e1f-11e6-9eda-b14521ffa06f.png)

There may be more - we'll need to search the templates for them :)

**Comment by gsb-eng** [comment]
@nlhkabu  I think this is a good start for me :), can I fix this?

**Comment by nlhkabu** [comment]
Yes @gsb-eng!  Absolutely!  If you have any problems or need any help getting things working, feel free to ping either myself of @dstufft on #pypa-dev (freenode).  My nick is 'nlh' :)

**Comment by nlhkabu** [comment]
:tada:

**Comment by dstufft** [comment]
Why are we changing this to "packages" rather than "projects"? I'm happy to be convinced why that's a good thing, but I pretty explicitly chose to use projects to try and disambiguate between ``import package`` and ``pip install package``.
