### ISSUE TITLE
UploadError HTTP Error 502: Bad Gateway

### ISSUE THREAD

**Issue by aht007** [pypa/warehouse#12511]
**Describe the bug**
Facing `UploadError HTTP Error 502: Bad Gateway` while uploading a package to PyPI

**Expected behavior**
Package should be uploaded successfully.

**To Reproduce**
https://github.com/openedx/django-wiki/actions/runs/3419471826/jobs/5693100175

**My Platform**
Python3.8, Ubuntu 20 and Github Actions Environment.

**Comment by aht007** [comment]
I can see others are facing this issue as well. https://github.com/pypi/warehouse/issues/12510

**Comment by di** [comment]
Thanks for the report. We were having a resourcing issue with our upload service, but this should be resolved now.
