### ISSUE TITLE
Decide on terminology, document what we decide, be consistent 

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1252]
In #1250 (implemented in #1251) @nlhkabu asked for all of the references to "Project" be changed to "Package", at the risk of incorrectly summarizing her reasoning, she did this because we had introduced the word "package" in a few locations in Warehouse (namely the help page), and because packaging.python.org was using "package" as well. Thus, switching project to package was an attempt to unify the terminology.

I originally purposely used the word project here because it was the supporting definition used in PEP 426. It was the supporting definition in PEP 426 in an attempt to disambiguate the term "package". Currently the term "package" can refer to:

* Something you import.
* A name on PyPI (such as "Django").
* A file that you download and install from PyPI (such as "Django-1.9.tar.gz").
* A generalized name of "something you work on".

So the term "Project" was chosen to represent the second of those things.

There are a couple issues with using the term Project however:

* A lot of people are still going to use the ambiguous term, regardless of what we call it.
* PyPI is named, "Python Package Index" (although that name is bad for other reasons as well).
* The PyPug uses the term "packages" in some locations (though I think it also uses the term "projects" in some locations.

There are several relevant issues on the PyPug issue tracker like, pypa/python-packaging-user-guide#89, pypa/python-packaging-user-guide#87, pypa/python-packaging-user-guide#199, pypa/python-packaging-user-guide#235, pypa/python-packaging-user-guide#106, and pypa/python-packaging-user-guide#25 and more on distutils-sig that I don't feel like digging up right now (yea, there's some history here).

For my part, I think the terminology of "Project" on Warehouse is clearer than the term package and we should go back to using it (and we should be consistent about using it). This leaves the name "PyPI" as a kind of unfortunate vestige, but @ncoghlan suggested tweaking the name to Python Packaging Index, which steps around that particular ambiguity. I'm not sure how I feel about that in particular, but I do know that I feel that the change as implemented in #1251 makes PyPI more difficult to understand. Even on the very front page of Warehouse now, we have:

<img width="658" alt="screen-shot-2016-06-09-09-38-06" src="https://cloud.githubusercontent.com/assets/145979/15931488/f7709558-2e25-11e6-80e6-4f8e122e67d3.png">

Which makes people have to sit there and figure out what kind of "package" this is (is it "Django" or is it "Django-1.0.tar.gz"?).

Now, looking closer at packaging.python.org, I think the change in #1251 still makes us at odds with the definitions used there. In [Installing Packages](https://packaging.python.org/en/latest/installing/) it uses the term "packages", but it states:

> It’s important to note that the term “package” in this context is being used as a synonym for a distribution (i.e. a bundle of software to be installed), not to refer to the kind of package that you import in your Python source code (i.e. a container of modules). It is common in the Python community to refer to a distribution using the term “package”. Using the term “distribution” is often not preferred, because it can easily be confused with a Linux distribution, or another larger software distribution like Python itself.

This would be mapped to "File" on Warehouse, not to "Project". 

In addition, it also has the section [Packaging and Distributing Projects](https://packaging.python.org/en/latest/distributing/) which refers to taking something like "Django", and distributing it via PyPI. Noticeably this uses the term "Project" in a similar way that Warehouse was using it previously to #1251. This use of "Project" also shows up in [Single-sourcing the Project Version](https://packaging.python.org/en/latest/single_source_version/), [Binary Extensions](https://packaging.python.org/en/latest/extensions/), [Supporting multiple Python versions](https://packaging.python.org/en/latest/multiple_python_versions/), [PyPI mirrors and caches](https://packaging.python.org/en/latest/mirrors/), [install_requires vs Requirements files](https://packaging.python.org/en/latest/requirements/), [Installing scientific packages](https://packaging.python.org/en/latest/science/), [Multi-version installs](https://packaging.python.org/en/latest/multi_version_install/), [Supporting Windows using Appyveyor](https://packaging.python.org/en/latest/appveyor/), [Project Summaries](https://packaging.python.org/en/latest/projects/), and is defined in the [Glossary](https://packaging.python.org/en/latest/glossary/).

Given all of this, I think the best course of action is to revert #1251 and continue to use the word "Project" to refer to the overall "thing" in Warehouse (e.g. "Django") and continue to use "File" to refer to the thing that you download, avoiding the word package except where it's needed.

**Comment by dstufft** [comment]
Oh, and I forgot to mention, at the very least, if we're going to stop using the word "Project", then we should do so completely and switch the URLs from ``/project/`` to ``/package/`` (not to be confused with ``/packages/``, which is the URL for downloading files) as well as changing the models and such in the code from ``Project`` to ``Package``.

**Comment by gsb-eng** [comment]
@nlhkabu  Could you please share your stand on this? so that we can act on the PR.

**Comment by ddbeck** [comment]
This nudged me to work on a draft for pypa/python-packaging-user-guide#199. Not knowing how this is going to shake out, as an exercise I tried writing two drafts (both still incomplete) to answer the question "what is a package?" with one in the sense of "project" as a name on PyPI and one in the sense of "package" as a name on PyPI.

What I found was that using "package" in this sense made it harder to distinguish making a file that you can download and install from the act of publishing your software on PyPI. I expect there to be some overlap and fuzziness in terminology, but I think the "project" terminology makes it slightly easier to explain the distinction than the "package" terminology (at least, based on the guidance from the current PyPUG about "distributions"). So perhaps that's a point in favor of reverting to "project."

That said, I'm not opposed to using "package" like this on Warehouse, but I think no matter the terminology selected, it would be helpful if the decision came with guidance about what to call each of:

> * A name on PyPI (such as "Django").
> * A file that you download and install from PyPI (such as "Django-1.9.tar.gz").
> * A generalized name of "something you work on".

Not just one. (I figure that "Something you import" is more or less settled by the [Python documentation](https://docs.python.org/3/tutorial/modules.html#packages).) This would help make the decision, whatever it is, easier to adapt to.

**Comment by dstufft** [comment]
The pre-merge rules of Warehouse were:

* A name on PyPI (such as "Django") is called a "Project".
* A file that you download and install from PyPI (such as "Django-1.9.tar.gz") is called a "File" or a "Download".
* A generalized name of "something you work on", it didn't really have much of a concept of this except in terms of the first, so it would call it a "Project".

I'm pretty sure that "Project" is the right word to use for the first case. I think for the second case is where we're going to end up with the most ambiguity because there are a lot of terms for it in use in the wild, and I think no matter what term we settle on, we'd end up having awkward sentences trying to cram whatever word we choose into it. 

I think part of this comes from the fact that the right word is often fairly context based. I choose to try and avoid package at all in Warehouse because I found that I could generally replace it with other common words (typically "File" or "Download") and be just as clear, because in the context of Warehouse File is fairly unambiguous. Writing isn't my strongest suit though, so it may only be clearer in my own head and not in reality. In particular I struggle a lot to try and "forget" what I know to put myself in a beginners shoes.

**Comment by ncoghlan** [comment]
I don't believe calling a time series of versioned packages a "project" conflicts with the overall service being called the Python Package Index - projects release packages, which developers then compose into applications and services (which may themselves be other PyPI projects).

The PyPI web service then provides a project-centric view that gives prominence to the latest package released by that project based on the assumption that, in the absence of other considerations, developers will want information about the latest available release.

That said, I do sometimes wonder if it might be helpful to more clearly separate our publishing terminology from our runtime environment management terminology.

Publishing (aka "the problem PyPI and twine address"):

- projects publish versioned distribution packages
- each published version of a package is a release
- a release may cover multiple downloadable files (sdist, wheels for different environments)

Runtime Environment Management (aka "the problem most PyPI client tools address"):

- an environment consists of a Python runtime and zero or more installed distribution packages
- each installed distribution package provides metadata about its version and dependency requirements
- each installed distribution package provides zero or more import packages, scripts and other components

When it comes to managing runtime environments, projects only matter in the context of deciding whether or not a particular update to a package is likely to be trustworthy (i.e. I'd trust a new Django release made by the Django project on PyPI, but not one made by J. Random Developer on their own custom domain), but when it comes to publishing releases, the project is the primary organising element (since it defines the authentication and authorisation rules for the publication process).

**Comment by nlhkabu** [comment]
Thanks for your feedback @dstufft, @ncoghlan and @ddbeck.  After hearing your perspectives, I agree that "project" is the better choice.

So... let's revert the last PR and make a new issue for changing "packages" to "projects" throughout the UI.

@ddbeck I wonder whether you also might be able to help me with:

- rewriting the main title "Find, install and publish Python packages with the Python Package Index" (should we just replace 'packages' with 'projects' here?)
- rewriting/improving the content on the help page (https://pypi.io/help/). It might be nice to clarify the terminology on this page too.

**Comment by dstufft** [comment]
> Find, install and publish Python packages with the Python Package Index

Strangely, this use of packages doesn't bother me, maybe because it's in a situation where some vagueness makes sense? I'm not sure that I have a real solid grasp on it :) Mostly my mental model has been prefer ``Project/Release/File`` on PyPI unless all of those sound awkward-ish and then reach for package.

**Comment by dstufft** [comment]
To be clear, that's not to say we shouldn't try to reword it if we can, just that that specific one doesn't bother me much :)

**Comment by dstufft** [comment]
I clicked the fancy revert button and got #1269, not sure if we want to consider this ticket finished with that PR or not.

**Comment by njsmith** [comment]
So just throwing this out there, the PyPI acronym also expands perfectly well to the Python Project Index...?

**Comment by ncoghlan** [comment]
Despite the pre-eminence of projects in the PyPI web UI, the thing you install with "pip install" is still a package, and packages are still what developers come to PyPI to find, install and publish - that's why "package" is correct in the tagline, even though it's de-emphasised elsewhere in the web UI :)

You don't install or publish a project, because a project (in the PyPI sense) primarily represents one or more people with the authority to publish new versions of a given package. We hang additional information around that "Project" entity (home page, version control, issue tracker, release history, etc), but the essential *purpose* of that entity in the workflow is to track publishing permissions (hence the project-centric nature of the delegations of authority in the package signing PEPs).

**Comment by ncoghlan** [comment]
While I've suggested a mild rename myself in the past (Package Index -> Packaging Index), I've personally come to the conclusion that any kind of rebranding would be more trouble than it's worth. We don't have a good way of capturing decisions *not* to do something, though, so I've suggested adding a design & development FAQ to the PyPA site over at https://github.com/pypa/pypa.io/issues/17

**Comment by ddbeck** [comment]
@nlhkabu:

> * rewriting the main title "Find, install and publish Python packages with the Python Package Index (should we just replace 'packages' with 'projects' here?)

I think the current wording is fine, though if you're looking for alternatives maybe we could replace *packages* with *software*? It might be a bit more friendly to newcomers to Python.

> * rewriting/improving the content on the help page (https://pypi.io/help/). It might be nice to clarify the terminology on this page too.

I've got some ideas for the help page. Can you point me to the file where this text is (or open an issue, if it's complicated to change)? I've got a few ideas and maybe it'll be easier to hash out in an issue or PR—and it's probably not germane to this issue, in any case.

**Comment by dstufft** [comment]
@ddbeck https://github.com/pypa/warehouse/blob/master/warehouse/templates/pages/help.html

**Comment by nlhkabu** [comment]
> maybe we could replace packages with software? It might be a bit more friendly to newcomers to Python.

:+1:   What do you think @dstufft ?

@ddbeck  - when changing the help content one thing to note is that we currently link to `#feedback` from the footer, so if you want to change that, you'll also need to change the link:
https://github.com/pypa/warehouse/blob/master/warehouse/templates/base.html#L111

:)

**Comment by dstufft** [comment]
Software sounds fine to me.

**Comment by nlhkabu** [comment]
oh, one thing about this issue that isn't covered by #1270 is the 'document' part.  Where should we document this?  Is it needed in the warehouse docs?  Do you need to open an issue elsewhere?

**Comment by dstufft** [comment]
Yea, probably just in the Warehouse docs.
