### ISSUE TITLE
Download Stats

### ISSUE THREAD

**Issue by micurd** [pypa/warehouse#1253]
Can you please add download stats? Thanks!

**Comment by nlhkabu** [comment]
Thanks for your suggestion @micurd.
We already have a 'download statistics' page on the package detail page, which we intend to populate with relevant statistics. See #787 

At first, this page will be fairly basic, but there are long term plans to improve downloads reporting.  Issues #699 and #188 give some ideas about what direction this might move in.  If you want to add to either of those tickets, please feel free.  In the meantime, I am going to close this issue as a duplicate.
