### ISSUE TITLE
Rename 'Version History & Changelog' to 'Release History & Changelog'

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1254]
This will also require renaming some of the CSS hooks.
What do you think @dstufft ?

**Comment by nlhkabu** [comment]
On second thoughts... maybe this is not a good idea.

**Comment by dstufft** [comment]
I think either is about roughly as clear.

**Comment by dstufft** [comment]
Although I do think maybe it's a bit verbose, maybe one of the following:

* Version History
* Release History
* Change Log
* History

Of all of those, I'm kind of partial to History or Version/Release History.

**Comment by nlhkabu** [comment]
If we agree on @ncoghlan's summary:

>  projects publish versioned distribution packages
    each published version of a package is a release
    a release may cover multiple downloadable files (sdist, wheels for different environments)

Then the best name here would be 'Release History'

**Comment by dstufft** [comment]
Release History sounds good to me!
