### ISSUE TITLE
Determine if there's a better way to render classifiers

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#1265]
Thanks to #1246 we now have classifiers listed on project pages, and they're done in a much nicer/cleaner way than on legacy PyPI, however there's still a bit of an issue with particularly longer classifiers. There may not be a reasonable way to solve this and it's just a problem with long classifiers, but I wanted to raise an issue to track this fact to see if maybe something can be figured out.

For reference, here's what this looks like now:

<img width="313" alt="screen-shot-2016-06-12-14-53-10" src="https://cloud.githubusercontent.com/assets/145979/15993257/9b52a4b6-30ad-11e6-9260-748a965e6297.png">

The thing to look at is the ``Software Development :: Libraries :: Python Modules`` classifier, particularly in how it (doesn't differentiate from two classifiers like ``Python :: 2.7`` and ``Python :: 3``. I'm not sure if there are any great ways of solving this, my ideas are:

* Have a list render a dot so that the start of each entry is more obvious.
* Have it so that overflowed lines are indented (is this even possible?) to make overflowed lines more obvious.
* Break the levels down even further to reduce the situations this happens in.
* Leave it alone and just deal with this tiny wart.

I don't think this is important to get done prior to launch, but I didn't want to forget about it.

/cc @nlhkabu

**Comment by hroncok** [comment]
Adding a dot:
<img width="313" alt="classifiers-dot" src="https://cloud.githubusercontent.com/assets/2401856/16409288/04ec7804-3d1d-11e6-9f10-0c7ca85cc155.png">

Adding a dot **and** indent:
<img width="313" alt="classifiers-dot-indent" src="https://cloud.githubusercontent.com/assets/2401856/16409287/04ec23f4-3d1d-11e6-93b2-83bebbeac3c8.png">

Indent:
<img width="313" alt="classifiers-indent" src="https://cloud.githubusercontent.com/assets/2401856/16409289/04f0bdba-3d1d-11e6-9c87-ce16f975411e.png">

Break down extra level:
<img width="313" alt="classifiers-level" src="https://cloud.githubusercontent.com/assets/2401856/16409290/04f14190-3d1d-11e6-912e-a93487376b51.png">

**Comment by nlhkabu** [comment]
I've been thinking about this recently - my strong preference is for these to be rendered in a tree - as show in the mockup https://github.com/pypa/warehouse/issues/754#issue-117861175 (but without the checkboxes).  I'm therefore going to close this issue and open a new one asking for a new tree design to be built and applied to both this list and the search sidebar.
