### ISSUE TITLE
Change 'packages' to 'projects' throughout the UI

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1270]
See https://github.com/pypa/warehouse/issues/1252 for more information.

This will need to:
- [ ] Change all titles, links and content
- [x] Update the help page, including a description of projects vs packages

**Comment by nlhkabu** [comment]
See https://github.com/pypa/warehouse/issues/1252#issuecomment-225737248 regarding the primary heading.

**Comment by nlhkabu** [comment]
There are still a couple of changes I'd like to make on the homepage here...

"Find, install and publish Python **software** with the Python Package Index"

"PyPI helps you find and install third-party software developed and shared by other members of the Python community. Learn about installing **software**."

"Project authors use PyPI to distribute their software. Learn how to package your Python code for PyPI."

Also, I'm thinking that the links in the footer should either change to:

"Installing Software" and "Uploading Software"

or

"Installing Projects" and "Uploading Projects"

or a combination of the two.

**Comment by dstufft** [comment]
Okay!

**Comment by dstufft** [comment]
I played around with making these changes, and I feel like the "software" wording feels kind of odd and I think I prefer to keep the word package as used in the last few places.
