### ISSUE TITLE
getting-started: talk about $(docker-machine env)

### ISSUE THREAD

**Issue by Carreau** [pypa/warehouse#1276]
I still haven't quite understood when exactly to do that, but when starting I often need to issue a `eval $(docker-machine env)` to get some env variable right. It's not obvious from the getting started docs.

I'll try to writeup something, I guess it's mac and windows only.

I'll see if I can find a way to get it working directly in the makefile.

**Comment by berkerpeksag** [comment]
With Docker for Mac, docker-machine or boot2docker is not needed. I've updated the documentation in https://github.com/pypa/warehouse/pull/1398. I guess we can close this now.
