### ISSUE TITLE
Add "Framework :: AsyncIO" as trove classifier

### ISSUE THREAD

**Issue by GMLudo** [pypa/warehouse#1288]
Hi,

In trove classifier: https://pypi.python.org/pypi?%3Aaction=list_classifiers , you have several ecosystems classifiers like "Framework :: Django" but also "Framework :: Twisted" and "Framework :: IPython".

It should be interesting to add "Framework :: AsyncIO" classifier, because you already have several librairies based on AsyncIO: https://github.com/python/asyncio/wiki/ThirdParty

Have a nice day.

PS: "Original" issue: https://github.com/pypa/pypi-legacy/issues/257

**Comment by sigmavirus24** [comment]
@GMLudo the correct place (I'm told) for this to be requested is https://sourceforge.net/p/pypi/support-requests/

**Comment by alefteris** [comment]
There is an open support request for the addition of the asyncio classifier at the pypi sourceforge project https://sourceforge.net/p/pypi/support-requests/332/ . It was opened in 2014.

Last comment was from @r1chardj0n3s:

> We tend to only add a new classifier once there is a number of projects out there that would need it. How many projects are you aware of that would use such a classifier?

I replied there, but copying it bellow as well:

> There is a list of more than 80 projects using asyncio in the Python wiki https://github.com/python/asyncio/wiki/ThirdParty
>
> Searching at PyPI for packages that support Python 3.5 and have 'asyncio' in their name or description, I get about 190 packages https://pypi.org/search/?q=asyncio&o=&c=Programming+Language+%3A%3A+Python+%3A%3A+3.5
>
> Some packages that are use asyncio have the "aio" shortcut in their name. Searching for this at PyPI I get about 90 results https://pypi.org/search/?q=aio&o=&c=Programming+Language+%3A%3A+Python+%3A%3A+3.5
>
> A popular asyncio http server and client library, aiohttp, has about 70 packages in its ecosystem listed at PyPI https://pypi.org/search/?q=aiohttp&o=&c=Programming+Language+%3A%3A+Python+%3A%3A+3.5

**Comment by ewdurbin** [comment]
Done.

**Comment by GMLudo** [comment]
Hi, 

Thank you to add this trove classifier.

Have a nice week.
