### ISSUE TITLE
Deploy legacy-pypi to legacy.pypi.org for now

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#1294]
Per Donald, as we do the first launch of redirecting pypi.python.org to pypi.io, we will have to deploy legacy-pypi to legacy.pypi.io for now.

> We're going to have to keep the legacy code base running somewhere for people to be able to access it until we maintain feature parity, so that people depending on something that hasn't yet been implemented have some mechanism to continue to do that. Once we reach feature parity (minus and thing we've decided to deprecate/remove) we can shut down the copy of the legacy code base completely and have only warehouse running.

**Comment by brainwane** [comment]
Donald said in IRC:

> (legacy.pypi.io actually exists today but it doesn't work very well because PyPI has hard coded URLs in the configuration, so around the time we do the bump I'll have to deploy a config change to legacy pypi so it knows it's being served at legacy.pypi.io)
> https://legacy.pypi.io/pypi sort of works

**Comment by pradyunsg** [comment]
Is this still valid?

**Comment by dstufft** [comment]
Yea, we still want to do this, it'll just be legacy.pypi.org instead.

**Comment by ewdurbin** [comment]
omg I'm so in.

**Comment by ewdurbin** [comment]
posterity? no... I suppose leaving it at pypi.python.org while we redirect all the non-api traffic attains the same outcomes.

eventually we turn pypi.python.org into a pure redirect then retire it?

**Comment by di** [comment]
> eventually we turn pypi.python.org into a pure redirect then retire it?

Yeah I'm talking about right when we do this, legacy will be otherwise inaccessible, might be worthwhile to keep a host pointed at it in case we missed something (definitely _not_ for posterity).

**Comment by brainwane** [comment]
We don't quite have feature parity yet. 

[Our roadmap](https://wiki.python.org/psf/WarehouseRoadmap) says, first (milestone 4) we launch-and-redirect (and it's ok if we are not 100% at feature parity, because we will keep Legacy around somewhere), then we shut down legacy (milestone 5, "shut down legacy PyPI").

We have [11 open items in the "shut down legacy PyPI" milestone](https://github.com/pypa/warehouse/milestone/7); some are design questions/issues from users who find the new site hard to use, some are accessibility issues, one is the "delete existing pythonhosted docs" functionality we need, one is a regression that affects file downloads for some users, and a few are different parts of the ability to view the trove classifiers on one page. I'd count the accessibility, trove, and file download issues as feature parity issues we need to resolve before shutting down legacy entirely, and I would like to consult with @nlhkabu about the others before we recategorize them.

And I agree with @di:

> might be worthwhile to keep a host pointed at it in case we missed something (definitely *not* for posterity).

**Comment by brainwane** [comment]
I [just spoke with Nicole in IRC](http://kafka.dcpython.org/day/pypa-dev/2018-03-21) and got her opinion that nearly everything that was in the "shut down legacy PyPI" milestone can actually wait till *after* we shut down legacy PyPI.

Therefore I am moving several issues out of "shut down legacy" and into the "post-shutdown" milestone.

**Comment by brainwane** [comment]
The trove classifier view issues are on their way to resolution thanks to Wasim's work, but #3108 is still a blocker to shutting down legacy, per @ewdurbin's opinion in [our meeting last week](https://wiki.python.org/psf/PackagingWG/2018-03-12-Warehouse). Thanks all.

**Comment by brainwane** [comment]
The expectation we've set with the community is that we aim to redirect traffic on the 16th and shut down legacy on the 30th but keep legacy up somewhere for those 2 weeks in between. Even if we re-prioritize our tasks and decide all of the issues in [our "shut down legacy" milestone](https://github.com/pypa/warehouse/milestone/7) are fine to do post-shutdown, the "unknown unknowns" rationale for keeping a deployment of legacy up somewhere (for those two weeks) remains.

**Comment by brainwane** [comment]
Ernest is planning on doing this on Monday.

**Comment by ewdurbin** [comment]
complete.
