### ISSUE TITLE
add minimal webpage to upload.pypi.io

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#1296]
upload.pypi.io is the upload endpoint for twine and setup.py upload. Currently it doesn't have any browser or human facing routes. Right now it's just an API endpoint. People will be a lot more interested in switching to something that has a web presence of some kind. Throwing some HTML up is as simple as writing a template file and adding a few lines of code.

@nlhkabu I'd defer to you regarding design, of course. My suggestion for what it needs to contain:
- an cleaned-up version of the explanation below
- the footer & other standard navigation elements, since they include Help & Contact links

Reasoning for all this, via IRC conversation with Donald:

> We're moving things off of the python.org domain name for security reasons-- the browser sandbox doesn't protect pypi.python.org from somethingelse.python.org, and because of the crushing weight of legacy systems there are parts of python.org that I don't trust their security of and we can't mandate HTTPS on python.org, only on specific sub domains. So PyPI is moving to pypi.io as part of this, and upload specifically is moving to upload.pypi.io (upload.pypi.io is a different subdomain from pypi.io largely to avoid passing uploads through our CDN).
> We need to cut a release for twine to start moving more folks over to it [upload.pypi.io] by default, make the same change in CPython to default to it, and go and convince Debian, Fedora, etc to switch their URLs-- but the service itself is basically done (although we might end up needing to move it off of Heroku).

**Comment by nlhkabu** [comment]
@dstufft :

- What exactly do you want on this page?
- What should the text say?  A rough draft is ok, I can edit it :)
- Should it be a straight HTML/CSS page (like the 500) or can I use the templates?

**Comment by dstufft** [comment]
I'm honestly not sure how important this is or whether we need it at all. I don't really remember the discussions around it to be honest. If we do add it maybe all we really need is to just tell people that this is the API endpoint for uploading files to PyPI, and perhaps they meant to go to https://pypi.org/ or for more information on uploading their files to PyPI, go to https://packaging.python.org/distributing/#uploading-your-project-to-pypi ?

**Comment by nlhkabu** [comment]
@dstufft - can we close this now since the error pages PR?

**Comment by pradyunsg** [comment]
@nlhkabu I think this can be closed since upload.pypi.org now does have a minimal webpage.

/ping @dstufft
