### ISSUE TITLE
Reorder trove classifiers on search sidebar

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1298]
It strikes me that the current ordering is probably not the most useful.

Maybe we reorder to be:

- By Topic
- By Intended Audience
- By Framework
- By Environment
- By License
- By Programming Language
- By Operating System
- By Natural Language
- By Development Status

Thoughts @dstufft ?

**Comment by di** [comment]
(They're currently just alphabetical)

**Comment by dstufft** [comment]
I don't have any great insight here except that I think that License, Programming Language, and Framework are the 3 kinds of classifiers that are most likely to actually be filled out by a project.

**Comment by nlhkabu** [comment]
ok, how about:

    By License
    By Programming Language
    By Framework
    By Topic
    By Intended Audience
    By Environment
    By Operating System
    By Natural Language
    By Development Status

We should also make the first list closed by default...

**Comment by dstufft** [comment]
That seems reasonable, though I'd maybe put ``Programming Language`` first.
