### ISSUE TITLE
Build tree for trove classifiers

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1299]
Ref #1265 and #754 

We need to build a new SCSS block that renders as a tree, as per http://odyniec.net/articles/turning-lists-into-trees/

This should be applied to the trove classifiers in the search sidebar and on the package detail pages.
This will require the markup for each to change to a unordered list.

**Comment by nlhkabu** [comment]
Visual Spec (with checkboxes):

![3e4e544a-8720-11e5-8a52-68c9f882fd1f](https://cloud.githubusercontent.com/assets/145979/11277998/05cf6d90-8eb7-11e5-8a04-e54c97fe9cf5.png)

The standard tree without checkboxes, would be the same, but with the lines joining instead of making boxes.

**Comment by waseem18** [comment]
@nlhkabu I'm looking into this issue - Right now going through http://odyniec.net/articles/turning-lists-into-trees/.

**Comment by nlhkabu** [comment]
sounds great @waseem18 :) thankyou!

**Comment by waseem18** [comment]
Quick update: Till now I was trying it by using recursive for loop which wasn't working well. Will now be trying with recursive macro's. Once I get it working I'll put a WIP PR.

Thanks
