### ISSUE TITLE
Link to statuspage.io

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1304]
As integrating the status indicator is not part of the launch milestone, we should (in the short term) modify the status footer link to say "Check Status" and link to https://status.python.org/

**Comment by berkerpeksag** [comment]
I've adapted statuspage.io in python.org a while ago. I can port it to Warehouse quickly if you prefer over adding a link to https://status.python.org/.

**Comment by nlhkabu** [comment]
Thanks for the offer @berkerpeksag :)

Our preference is to get the integration working - this issue is just because we didn't think it was going to happen before launch.  If you think you can get it done, there is a separate issue open for this at #604

**Comment by berkerpeksag** [comment]
#604 has been fixed so we can close this one now.
