### ISSUE TITLE
Remove legal page, link to https://www.python.org/about/legal/

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1305]
Instead of linking to a separate page, the legal link in the footer can link to https://www.python.org/about/legal/

**Comment by dstufft** [comment]
Let me poke Van about this real quick to make sure that still makes sense to do so here.

**Comment by nlhkabu** [comment]
Note that as per the HTML styleguide, any link should not contain a protocol, e.g. `//mylink.com` not `http://mylink.com`
