### ISSUE TITLE
Remove bio on user page

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1306]
![screenshot from 2016-06-30 06-59-49](https://cloud.githubusercontent.com/assets/3323703/16478202/48023916-3e90-11e6-8f6a-8594dac052c6.png)

This is not currently implemented and should be removed for launch.

**Comment by nlhkabu** [comment]
Given that we have the style for this already designed, I think this is best that we just comment this out in the HTML, removing the placeholder text and replacing it with 'author bio here'

**Comment by benregn** [comment]
Issue resolved in #1379.
