### ISSUE TITLE
Add user bio

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1307]
The original design adds a bio to each contributor.

![screenshot from 2016-06-30 07-00-51](https://cloud.githubusercontent.com/assets/3323703/16478231/78a7f36c-3e90-11e6-8e5e-525c8625a6c4.png)

This is being removed for launch (see #1306), but would be nice to implement in the long term.

**Comment by HndrkMkt** [comment]
I'll get started on this one.

**Comment by HndrkMkt** [comment]
Sorry for the slow progress, I'm a bit stuck in university work. One question regarding the input of the bio: What format should be used here? reStructuredText? Plain text that may contain HTML links? 

As far as I see it, RST would allow more formatting than we intend to have, basically multi-line text with the occasional link. So it could be easiest to write a renderer for text + link.

**Comment by di** [comment]
I think we can just focus this on plaintext right now, and add more advanced rendering later.

**Comment by nlhkabu** [comment]
Closing for lack of progress - does not appear to be high priority.
