### ISSUE TITLE
Remove status indicators, move version indicator

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1308]
![screenshot from 2016-06-30 07-05-51](https://cloud.githubusercontent.com/assets/3323703/16478376/1dd65522-3e91-11e6-82c1-0fb12d408003.png)

As they will not be ready for launch, we want to:
- Remove the dependencies, test and launch status indicators
- Move the version indicator to next to the package title (in the blue banner)

**Comment by dstufft** [comment]
Closed by https://github.com/pypa/warehouse/pull/2016.
