### ISSUE TITLE
Comment out project dependencies tab

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1309]
For launch it is unrealistic that the dependencies tab will be complete.  We should comment it out in the short term.

**Comment by TheJJ100100** [comment]
I didn't realise there were 2 commits in the PR, but I don't know how to rebase them now that I've pushed them and done a Pull Request. But I have commented out the dependency tab and the side bar button.

**Comment by TheJJ100100** [comment]
Close this issue? @nlhkabu

**Comment by nlhkabu** [comment]
For next time @TheJJ100100 - if you use the 'closes' keyword on your commit then the issue will close automatically when the PR is merged.  e.g. "Closes #issueno"

**Comment by TheJJ100100** [comment]
@nlhkabu Just realised that it's not actually commenting out the tab....

**Comment by TheJJ100100** [comment]
![Here](https://cloud.githubusercontent.com/assets/5558617/16542399/527a7448-409e-11e6-9441-00c807a23258.png)

**Comment by TheJJ100100** [comment]
@nlhkabu It's to do with the fact that there is a `{# Tab: Dependencies #}` inside the comment and jinja is seeing the close comment there as a close for the first comment or something.

**Comment by nlhkabu** [comment]
OK.  Let's revert the merge for now.  
If you can then update the PR to remove the extra comment, I'll remerge.
