### ISSUE TITLE
Design alternative version history

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1311]
The current design is not able to be fully implemented before launch, so in the short term, I need to come up with a more simple version that only contains the links to each version.

**Comment by dstufft** [comment]
I think it *might* be nice to also include who actually did the upload for each version here too. That should be available as ``Release.uploader``.

**Comment by brainwane** [comment]
A Python programmer who uses PyPI took a look at pypi.io a few days ago and said it seems pretty nice overall! But he mentioned to me:

> The main complaint I have with it is that it doesn't seem to make it super
duper easy to find the version control homepage for a project (which is
often what I'm looking to do on pypi -- trying to find their code so I can
see if the project is maintained).  And prominently showing data like "last
release" and "last commit to VCS" would probably also be helpful for how I
use pypi.

@nlhkabu I'm not sure whether you'd want to do all of this on the main project page or simply make it more prominent on the version history page, but I figured this data might help you in your design priorities as you do the pre-launch design work.

**Comment by nlhkabu** [comment]
I agree that this information is important.  Currently, it is located in the horizontal bar above the main content:

![screenshot from 2016-07-14 06-44-06](https://cloud.githubusercontent.com/assets/3323703/16829176/81d5ba38-498e-11e6-9bb5-a372c30af653.png)

We are removing the badges bar (directly above it) so it should become more prominent on the page.

The issue is that not all projects provide this information, and when they do, the text for the link is entered by the user (so it could say 'homepage' as in this example, or it could say 'source code', or it could say something else altogether).

There is no separate field in the database for the source code URL - it is just a 'link' to an external page.  So for example, the Django project could have 'links' to djangoproject.com, the source on github, their google group, etc, etc.  These would all be output on this horizontal bar.

 We've managed to get around this issue (a bit) by looking at the URL and providing a brand icon (as you can see in this screenshot) - this should help users identify version control websites, but I'm not sure there is much else we can, or should do.

Regarding last release - this is the first badge in the bar 'latest version' and will be moved next to the main heading.  I'm not sure it it worth tagging this on the search results, as we default to showing the latest version (correct me if I am wrong here @dstufft) in the results.

Last commit to VCS is simply not possible, as we do not store this information.  If we moved 'link to version control' into it's own field, we could probably do this via an API call, but I'm not sure that this is inside the scope of what we want PyPI to be.  Again @dstufft may have some opinions on this.

**Comment by nlhkabu** [comment]
Ah, I just realised what you mean by 'last release' - they want to see the date of the last release...
Noted :)

**Comment by dstufft** [comment]
> The issue is that not all projects provide this information, and when they do, the text for the link is entered by the user (so it could say 'homepage' as in this example, or it could say 'source code', or it could say something else altogether).

This is sort of true, but also sort of not :)

In Python metadata there are two named urls (``home_page`` and ``download_url``) where we control the text, and then there is essentially a dictionary of additional urls where the key is the text and the value is the url. Those we can't control, however we *can* make suggestions and guide people to using certain key names for particular things. So we could publish a recommendation of "Source Code" or whatever we want to point to the VCS location.

> Regarding last release - this is the first badge in the bar 'latest version' and will be moved next to the main heading. I'm not sure it it worth tagging this on the search results, as we default to showing the latest version

The search results show the latest version as of the time of indexing yes. There may be a delay if someone recently released a new version, but generally the latest version.

> Last commit to VCS is simply not possible, as we do not store this information. If we moved 'link to version control' into it's own field, we could probably do this via an API call, but I'm not sure that this is inside the scope of what we want PyPI to be.

I don't think it's something we're likely to get into-- We could offer a field for pointing to the VCS repository itself and then other people could scrape this, but I'm not sure that it's super useful information in general.

**Comment by pradyunsg** [comment]
#2049 resolves this. I guess this can be closed.
