### ISSUE TITLE
Add donation page

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1315]
We would like to add a page for collecting donations for the ongoing development and maintenance of the project.

Something like https://www.djangoproject.com/fundraising/ would be great.

**Comment by nlhkabu** [comment]
Note, that while I can do the design/HTML for this, I will need some help integrating a payment platform.

**Comment by dstufft** [comment]
We're probably not going to be able to integrate a payment platform to begin with, and will need to have actually accepting payments take us to the current donation page. The design should have it in mind to handle that ourselves though, I just need to work with Kurt and the PSF to figure out what is needed to actually do that. I suspect it will require some PHP coding in Drupal on my end.

**Comment by brainwane** [comment]
For right now, just for launch, I think linking to the Python Software Foundation donation page https://www.python.org/psf/donations/ would be ok?

**Comment by nlhkabu** [comment]
Ok, lets move this to post launch.  I'll add a separate issue for adding the link to the UI.

**Comment by nlhkabu** [comment]
Oh, and the link should be donate.pypi.io - I've updated this in the new issue.
