### ISSUE TITLE
Add temporary login page, replace login and register links

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1316]
As we will not be launching with anything meaningful to do in the logged in section, I think we should create a 'temporary login' page that:

- Has a large button redirecting back to the old PyPI
- Explains that the logged in features are on our 'todo' list and will be done soon
- Invites users to contribute to the project
- Asks for donations

Something like (with links added):

"We're currently working on making the logged in pages on PyPI better.  If you'd like to see this happen sooner, please consider contributing to Warehouse, or making a donation (or asking your company to make a donation) towards the ongoing development of the Warehouse project"

We could host this at `/temp-login/' and replace the current login and register links with a link to this page.

**Comment by dstufft** [comment]
It could honestly probably just live where login is now. I don't see any reason to make a special page for this, just add it to the page we already have.

**Comment by nlhkabu** [comment]
hmmm... the only thing is that this requires me to clean up the current login form, which I wasn't planning on doing for launch.  Unless we hide the form altogether for now??

**Comment by dstufft** [comment]
We could just slap a ``{# #}`` around the current log in form in the template.
