### ISSUE TITLE
Test UI across multiple browsers

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1317]
We need to test the UI against the following browsers:
https://warehouse.readthedocs.io/development/frontend/#browser-support

It would also be wise to check the breakpoints on each browser, as well as testing on touch interfaces, e.g.
- iphone
- android
- tablet

**Comment by CrazyPython** [comment]
FYI, [BrowserStack](https://www.browserstack.com) grants free licenses to open-source projects, large and small.

**Comment by nlhkabu** [comment]
To test: tab index on all browsers - see https://github.com/pypa/warehouse/pull/2822#issuecomment-360289508

**Comment by brainwane** [comment]
In [today's Warehouse developers' meeting](https://wiki.python.org/psf/PackagingWG/2018-03-06-Warehouse) we discussed this and I learned of site usage stats from last month (Feb 2018): Chrome 67.76%, Firefox 16.92%, Safari 7.38%, Internet Explorer 2.79%.

**Comment by brainwane** [comment]
Is [this list of workflows](https://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html#workflows) a reasonable one to ask people to test in different browsers?

**Comment by nlhkabu** [comment]
## IE11

![screenshot from 2018-04-02 16-16-26](https://user-images.githubusercontent.com/3323703/38201750-38bcc3cc-3691-11e8-8c9e-bd2a94fef20e.png)

![screenshot from 2018-04-02 16-17-17](https://user-images.githubusercontent.com/3323703/38201784-556f84dc-3691-11e8-84ae-a2df75021956.png)

![screenshot from 2018-04-02 16-17-04](https://user-images.githubusercontent.com/3323703/38201785-558e58b2-3691-11e8-88c5-e721dd8bab7e.png)

![screenshot from 2018-04-02 16-17-42](https://user-images.githubusercontent.com/3323703/38201798-642b168a-3691-11e8-8a4a-009311106b0e.png)

![screenshot from 2018-04-02 16-18-14](https://user-images.githubusercontent.com/3323703/38201810-7715ce3e-3691-11e8-97c0-1aa770ef34c3.png)

![screenshot from 2018-04-02 16-19-07](https://user-images.githubusercontent.com/3323703/38201840-96900cd4-3691-11e8-98e6-d5a6a392d354.png)

![screenshot from 2018-04-02 16-20-19](https://user-images.githubusercontent.com/3323703/38201889-c143c632-3691-11e8-8bcd-ac7ff0f21aef.png)

![screenshot from 2018-04-02 16-21-38](https://user-images.githubusercontent.com/3323703/38201943-f0e400fa-3691-11e8-8daf-f99a5564d34e.png)

**Comment by nlhkabu** [comment]
## Mobile

![screenshot from 2018-04-02 16-38-47](https://user-images.githubusercontent.com/3323703/38202648-5aff325a-3694-11e8-9779-1285d05d9976.png)

![screenshot from 2018-04-02 16-39-38](https://user-images.githubusercontent.com/3323703/38202690-80e71294-3694-11e8-8953-8ba9719131e2.png)

![screenshot from 2018-04-02 16-40-24](https://user-images.githubusercontent.com/3323703/38202705-8fe1efe4-3694-11e8-8c7b-05d65bff8c66.png)

## Tablet

![screenshot from 2018-04-02 16-42-22](https://user-images.githubusercontent.com/3323703/38202775-d7a58160-3694-11e8-925b-600398dab5e9.png)

**Comment by nlhkabu** [comment]
Current browser stats (last month):
![screenshot from 2018-04-02 16-47-44](https://user-images.githubusercontent.com/3323703/38203011-a9693642-3695-11e8-9137-9aa99288bbf4.png)
![screenshot from 2018-04-02 16-47-30](https://user-images.githubusercontent.com/3323703/38203012-a9836f76-3695-11e8-8143-c324ef6ef103.png)

Based on our current browser statistics, the site is rendering well for the **vast majority** of users.
We do have a number of issues in Internet Explorer 11.  I will open tickets for these - however, as Internet Explorer only makes up 2.80% of our users (ie11 93% of those IE users), it is not a "blocking" issue.  

Currently, we show a "not supported" banner for users on ie9 and under.  I suggest we update this to ie10 and below because a) there are very few ie10 users, and b) [microsoft ended support for this a while ago](https://venturebeat.com/2016/01/12/microsoft-ends-support-for-ie8-ie9-ie10-and-windows-8/)

I also found a couple of tablet and mobile issues, for which I will open tickets.  These are higher priority as mobile and tablet make up nearly 8% of users.

**Comment by nlhkabu** [comment]
All found issues opened.  Closing this.  Will revisit if/when needed.
