### ISSUE TITLE
Link to checksum docs on downloads table

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1318]
![screenshot from 2016-06-30 19-20-43](https://cloud.githubusercontent.com/assets/3323703/16499328/d0f19ae8-3ef7-11e6-8eb3-bf2cfb3b653f.png)

The original idea of this design is to have a popover that contains help information appear when the user clicks on the help icon.  This is not going to be possible for launch, so we should instead find an appropriate place to link to.  Ideally, a page that explains what a checksum is and how to use it.

**Comment by nlhkabu** [comment]
Note that as per the HTML styleguide, any link should not contain a protocol, e.g. `//mylink.com` not `http://mylink.com`

**Comment by berkerpeksag** [comment]
https://pip.pypa.io/en/stable/reference/pip_install/#hash-checking-mode would be a good resource to link.

**Comment by timofurrer** [comment]
Was done with #1381
