### ISSUE TITLE
Add help popover

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1319]
![screenshot from 2016-06-30 19-20-43](https://cloud.githubusercontent.com/assets/3323703/16499395/39db0b84-3ef8-11e6-8c45-4ddb07ce5878.png)

The original idea for this icon was to launch a popover containing help information when the user clicks on it.  For launch, we are not going to do this (see #1318), but in the long term it would be good to integrate popovers so that we can reuse this pattern throughout the UI.

**Comment by dstufft** [comment]
Closed by https://github.com/pypa/warehouse/pull/2016.
