### ISSUE TITLE
Add link to PSF donation page

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1321]
We need to add a link to donate.pypi.io somewhere in the UI.

I think we should add it:
1. To the header, after the help link.  Given the small resolution, we may have to hide it on mobile.
2. In the footer. Either as a button (directly above the hr), or next to 'Developed and maintained by the Python community, for the Python community.'

**Comment by dstufft** [comment]
Would it be a crazy idea to put it in a sort of corner banner thing? Like those "Fork me on Github" banners? Like https://github.com/blog/273-github-ribbons. Maybe that's a terrible idea, I dunno!

**Comment by nlhkabu** [comment]
I would usually say yes to this, but given we already have a space for a notification banner at the top of the page, I think this is probably going to be a bit too 'busy'.

Maybe we can:

- Have a donate link in the top menu
- Have a donate link in the footer
- Add a banner at the top of the page for the first month(??) after launch

**Comment by nlhkabu** [comment]
The other advantages of using a notification banner/bar:

1. We already have the HTML and CSS built
2. We can add more information / a catchy 'sales' pitch :P

**Comment by dstufft** [comment]
@nlhkabu I presumed that notification banner was going to go away once we launched?, except for cases of dire need. I'm not opposed to using it for a sales pitch though either.

**Comment by nlhkabu** [comment]
Yes - it will go away. But its perfect for this kind of thing, so why not reuse it? ;)

We probably don't want to apply the fixed positioning though, as it's not as important as the warning banners.

**Comment by dstufft** [comment]
Yea I'm not opposed to the idea :)

**Comment by controversial** [comment]
Once we remove the fixed banner that's there now, could the top bar be fixed? I think that'd work nicely.

**Comment by nchammas** [comment]
Couple of questions:
1. Is this a dup of #1315?
2. I see we have [a link to the PSF donation page](https://github.com/pypa/warehouse/blob/b7a2168c758c1350ec637f5171d9c2de6eb91942/warehouse/templates/accounts/macros.html#L23), but I don't see where on the site it shows up. Is that part of what this issue is about?
