### ISSUE TITLE
Improve security policy / security page content

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1323]
For launch we are going to use the content currently in the Warehouse docs, but in the long term, it would be good to improve the policy to something that does not rely on Donald and Richard answering emails.

Once a new policy is decided on, the security page will need to be updated accordingly.

**Comment by xoviat** [comment]
Apparently the "Slovak National Security Office" (NBU) [has recommended](https://www.bleepingcomputer.com/news/security/ten-malicious-libraries-found-on-pypi-python-package-index/) against using pip as a result of security issues. These types of articles are likely to cause confusion in the Python community.

/cc  @commonclimate

**Comment by brainwane** [comment]
In [today's Warehouse core developers' meeting](https://wiki.python.org/psf/PackagingWG/2018-03-06-Warehouse) we decided to pare down our near-future milestones on [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) so they really only contain the absolutely essential bugfixes and features we need to launch, replace legacy PyPI, and shut down the old site. So I'm moving this issue into a milestone further in the future; sorry for the wait.

**Comment by brainwane** [comment]
Sounds good to me!
