### ISSUE TITLE
Add 'activity log' to each project

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1327]
We want to be able to expose information on the changes that have been made to a project over time.
In particular, this will be useful for viewing which maintainer uploaded different files.

From a UI perspective, this could either be added as an extra tab on the project sidebar, _or_ exposed via a toggle button on the changelog panel.

The data to expose is located here: https://github.com/pypa/warehouse/blob/master/warehouse/packaging/models.py#L420-L461

As part of this issue, we may want to add some more structure to the data collected.

**Comment by dstufft** [comment]
Adding structure to this data will probably depend on *when* it actually gets done. If legacy is shut down then adding structure becomes a lot easier to do than trying to do it prior to that.

**Comment by nlhkabu** [comment]
From my POV this is fine to wait for until after legacy is shut down, so lets go with that :)

**Comment by nlhkabu** [comment]
I think this is a duplicate of #2871
