### ISSUE TITLE
Reduce package card height

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1337]
Now that we have removed uploader information from the card, I think the version looks a bit daft on its own line:

![screenshot from 2016-07-02 10-39-36](https://cloud.githubusercontent.com/assets/3323703/16539644/63e48474-4041-11e6-948e-dc787aab4bee.png)

Suggested fix: move version to next to the package name.

Given that this will make the cards shorter, we can also afford to reduce the margin on each card, which will compress the interface somewhat.

**Comment by controversial** [comment]
I'll try to do this. Unless the cards are fixed-height, what needs to change about the margins?

**Comment by nlhkabu** [comment]
The current margin is `10px 0 20px`, let's try it at `5px 0 15px`.
