### ISSUE TITLE
Do not show links bar if no links are present on the project

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1347]
We want to avoid this situation (see second grey - empty - div):

![screenshot from 2016-07-02 21-32-31](https://cloud.githubusercontent.com/assets/3323703/16542367/941c45f4-409c-11e6-8813-e006537601ac.png)

This should be as simple as wrapping the div in an if statement checking that links exist.

**Comment by controversial** [comment]
This was _not_ easy for a new contributor, but maybe I'm just denser than most. I had to dig into the actual Python code and add a new filter one, unless I missed something. Anyway, I learned something 👍 

Check out #1352

**Comment by brainwane** [comment]
Thanks @controversial -- if you see any other issues that you perceive to be not very easy for new contributors, please feel free to flag them via a comment!

**Comment by controversial** [comment]
Ok @brainwane. Thanks!
