### ISSUE TITLE
Add modal component

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1355]
Required to support #1354

**Comment by nlhkabu** [comment]
We now have a CSS modal in our codebase, closing this.

**Comment by brainwane** [comment]
@controversial I'm sorry for the slow response!

The folks working on Warehouse have recently gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap), and so we're in many cases belatedly replying to older tickets and questions. But for the next few months, I predict we'll be pretty good at replying to new comments and issues/PRs.

We're happy to have contributors work on stuff even if it's marked as post-launch, but we may be mildly slower to review PRs for future milestones if we're barrelling towards a particular deadline.

Thanks and sorry again for the wait. Also, will we see you at [the sprints at PyCon North America](https://mail.python.org/pipermail/distutils-sig/2018-February/031986.html)?
