### ISSUE TITLE
Clicking on cross on applied filter should remove filter

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1369]
When a new filter is applied, this badge is shown in the UI:

![screenshot from 2016-07-04 09-37-34](https://cloud.githubusercontent.com/assets/3323703/16574462/0d47391c-4277-11e6-8557-fd6f1087f094.png)

Currently, nothing happens when you click on the cross on the right - we need to change this so that clicking on the cross removes the filter and removes the badge.

**Comment by wismer** [comment]
@nlhkabu I just chanced on reading this. Should I lump this change as well with #1384 ?

**Comment by di** [comment]
Fixed in #1404.
