### ISSUE TITLE
503 unavailable, now works again.

### ISSUE THREAD

**Issue by Carreau** [pypa/warehouse#1372]
Hi there, I know you are busy, and thanks a lot for warehouse. 

I just got a (small) crash I guess, I was not able to reproduce (around 930 AM Pacific):
```
$ cat ~/.pypirc
[distutils]
index-servers =
    pypi

[pypi]
repository:https://upload.pypi.io/legacy/
username: <username>
password: <passwd>
```

```
$ ls -1 dist/
ipython-5.0.0rc1-py2.py3-none-any.whl
ipython-5.0.0rc1.tar.gz
ipython-5.0.0rc1.zip
```

```
$twine upload dist/*
Uploading distributions to https://upload.pypi.io/legacy/
Uploading ipython-5.0.0rc1-py2.py3-none-any.whl
HTTPError: 503 Server Error: Service Unavailable for url: https://upload.pypi.io/legacy/
```

`ipython-5.0.0rc1-py2.py3-none-any.whl` was though uploaded correctly, and I was able to resume the upload for the sdists. 

So just leaving that there in case you want to look at the logs.. otherwise feel free to close, all is fine on my end now.

**Comment by dstufft** [comment]
I'm going to close this, I see the error and it was a timeout error from the edge while waiting for the request to be processed. It was the only one in the last ~24 hours so I'm going to consider it an isolated error for right now, but I'll monitor it and if I continue to see them I'll dig in deeper.

Thanks!

**Comment by Carreau** [comment]
Thanks a lot, just wanted to make you aware in case. 

BTW I enjoyed hearing you on Talk Python To Me. Thanks for taking the time to do that as well.
