### ISSUE TITLE
Newly uploaded package not appearing on warehouse

### ISSUE THREAD

**Issue by jaraco** [pypa/warehouse#1422]
Hours ago, I uploaded https://pypi.python.org/pypi/jaraco.clipboard/1.3, yet still https://pypi.org/project/jaraco.clipboard/ shows as 1.3. I see that https://pypi.org/project/jaraco.clipboard/1.3 does appear, but 1.3 doesn't show under history or latest version.

**Comment by dstufft** [comment]
Did you upload to PyPI or Warehouse ?

**Comment by jaraco** [comment]
I [uploaded to PyPI](https://travis-ci.org/jaraco/jaraco.clipboard/jobs/150713312#L725).

**Comment by dstufft** [comment]
Pypi doesn't clear warehouse's cache. Warehouse clears its own and legacy's.

**Comment by jaraco** [comment]
The package still reports as 1.2 in warehouse, even if I force refresh. It seems impossible to bust the cache. Can you confirm if you go to the URL behind the cache that the proper latest version is showing? Is there a workaround if this happens?

It sounds like you're saying the only option to avoid this in the future is to never use the legacy PyPI again. Are we at a stage that setuptools should be patching the default behavior for uploads? Should the Travis deployment hook (or twine) be updated to upload to warehouse by default (perhaps they already are)?

**Comment by sigmavirus24** [comment]
> It sounds like you're saying the only option to avoid this in the future is to never use the legacy PyPI again.

That's the understanding I have.

> Are we at a stage that setuptools should be patching the default behavior for uploads?

Can this not be controlled by a `.pypirc` with setuptools?

> Should the Travis deployment hook (or twine) be updated to upload to warehouse by default (perhaps they already are)?

Twine has been uploading to Warehouse since 1.7.0 if the `.pypirc` doesn't specify otherwise.

**Comment by dstufft** [comment]
You can run curl -XPURGE <url>

**Comment by jaraco** [comment]
I ran the PURGE operation but the page still shows 1.2.

```
$ curl -X PURGE https://pypi.org/project/jaraco.clipboard
{"status": "ok", "id": "321-1465859301-4825970"}
```

Aha - the trailing slash is important:

```
$ curl -X PURGE https://pypi.org/project/jaraco.clipboard/            
{"status": "ok", "id": "2640-1469513808-956332"}
$ curl -s https://pypi.org/project/jaraco.clipboard/ -o - | grep 1\\.3
    <h1 class="package-header__name">jaraco.clipboard 1.3</h1>
    <a class="status-badge status-badge--good" href="/project/jaraco.clipboard/1.3/">Latest Version</a>
                <p class="release__version">1.3</p>
                  <td><a href="https://files.pythonhosted.org/packages/e1/5a/f81c335101db94aca040741f8b8495ef751f9b1c33a1656fc20cb203a4ef/jaraco.clipboard-1.3-py2.py3-none-any.whl">
                    jaraco.clipboard-1.3-py2.py3-none-any.whl</a>
                  <td><a href="https://files.pythonhosted.org/packages/a8/a2/254b40d9e4a575e6043fef16f96165429cd8ea250f0619ae7025267d3d97/jaraco.clipboard-1.3.tar.gz">
                    jaraco.clipboard-1.3.tar.gz</a>
```

Problem solved, and thanks for the advice on avoiding this in the future.

**Comment by jaraco** [comment]
> Can this not be controlled by a .pypirc with setuptools?

@sigmavirus24 It seems not. I have pypi.org in my .pypirc, with nothing in a local setup.cfg, but still the upload command, invoked via latest setuptools, uploads the package to pypi.

**Comment by sigmavirus24** [comment]
Weird... I have had a `.pypirc` for a long time and it used to use my credentials from there when I used to use `python setup.py upload`. I guess it just doesn't look for the URL to upload to. *shrug*
