### ISSUE TITLE
Access directly warehouse Docker DB from pypi-legacy ?

### ISSUE THREAD

**Issue by Carreau** [pypa/warehouse#1423]
Hi there, 

I'm trying to get legacy-pypi to work locally, to implement pep-503 (the data-python-requires attributes). 
The information to run pypi-legacy are quite out of date, but IIUC current deployed warehouse and PyPI are sharing a DB; so I guess it is possible to start a legacy-pypi and set-it up to use the docker-db... 

So far I **think** I understood that the db ip is the docker one, usename is `warehouse` so config.ini should be something like... :
```
[database]

;Postgres Database
host = 192.168.99.100; ? db ?
;port = 5432 ; ?? is that the right port 
name = warehouse
user = postgres
password = ??; 
```

I've commented / wrapped in try/except all the boto connexions in pypi-legacy that are trying to connect ... and end ran `python pypi.wsgi` which ends up showing this on the main page : 

```
Database connection failed

Please try again later.
<!-- could not connect to server: Connection refused
	Is the server running on host "192.168.99.100" and accepting
	TCP/IP connections on port 5432?
 -->
```

Now I'm stuck. 

I'm happy to improve the documentation to tell people how to do that, which I've [started with a PR](https://github.com/pypa/pypi-legacy/pull/497), so would gladely get some help/pointers !

Thanks !

**Comment by berkerpeksag** [comment]
I can't help with the Docker part, but wouldn't be easier to download `example.xz` in https://github.com/pypa/warehouse/tree/master/dev and then use it to create the database for pypi-legacy? I haven't tried the idea but, it should be doable in theory :)

**Comment by dstufft** [comment]
Generally when working on legacy PyPI is just use ``example.sql.xz`` like @berkerpeksag to restore to a new database. Sometimes I have to run the migrations on it and such but genreally that's what I Do.

You could adjust ``docker-compose.yml`` so that it exposes the PostgreSQL port though.

**Comment by Carreau** [comment]
Thanks @berkerpeksag and @dstufft ! I'll try that, and if it works update the PyPI-legacy instructions !

> it should be doable in theory

You know the difference between theory and practice ? In theory it's the same.  :-) 

> You could adjust docker-compose.yml so that it exposes the PostgreSQL port though.

Hum... my docker experience is only copy-pasting instructions, but I can try...

**Comment by Carreau** [comment]
Good ! Moving forward, a bit, I can now connect to the database !

```
# url : localhost:port/simple/flit
Error...

Internal Server Error

Traceback (most recent call last):
  File "webui.py", line 489, in run
    self.inner_run()
  File "webui.py", line 744, in inner_run
    return self.run_simple()
  File "webui.py", line 1144, in run_simple
    serial = self.store.last_serial_for_package(path)
  File "store.py", line 1213, in last_serial_for_package
    (package,),
  File "store.py", line 265, in safe_execute
    return cursor.execute(sql, safe_params)
ProgrammingError: column "last_serial" does not exist
LINE 1: SELECT last_serial FROM packages WHERE name = 'flit'
               ^
```

last_serial can be found in commit fc6a6fa5393beec9a351604ae3794c10cc2730d4 of warehouse, from https://github.com/pypa/warehouse/pull/1166 ... anything obvious I would have missed ? 

(note a few other errors, but details I can work around like having to connect through TLS)...

I'm guessing it has to do with `docker-compose run web python -m warehouse db upgrade head` that's likely to trigger `alembic.command.upgrade(config.alembic_config(), revision, **kwargs)` but then it becomes too magic for me.  Thanks !

**Comment by dstufft** [comment]
Yea, you need to run ``docker-compose run web python -m warehouse db upgrade head``.

**Comment by Carreau** [comment]
> Yea, you need to run docker-compose run web python -m warehouse db upgrade head.

Yeah, that's possible if you are running the docker-version, I went with @berkerpeksag advice and imported `example.sql` in a local version of postgres and had no clue how to run the above command on my local version.

I now have a local pypi-legacy that connects to the warehouse db container, and things seem to work !

So closing here I'll document the step on PyPI-legacy !

Thanks  for your help !
