### ISSUE TITLE
Use version in installation instruction 

### ISSUE THREAD

**Issue by kracekumar** [pypa/warehouse#1425]
While visiting the project page, manual displays instruction to install the package `pip install requests`. How about displaying `pip install requests==2.9.0`? This method emphasizes the version user is installing and gives heads up while installing `alpha and beta` versions.

**Comment by dstufft** [comment]
This would need to be something that @nlhkabu takes a look at, though I think it's a nice idea, but *only* on the version specific pages. I think the pages like ``/project/requests/`` should still show ``pip install requests`` while ``/project/requests/2.9.0/`` could show ``pip install requests==2.9.0``.

**Comment by nlhkabu** [comment]
Great idea!  And yes, I agree that it should only be for version specific pages.
