### ISSUE TITLE
Uploading a package repository URL

### ISSUE THREAD

**Issue by amitsaha** [pypa/warehouse#1430]
Hello, I setup warehouse locally on localhost as per the instructions (via docker). Works great!

However, I am now trying to upload a package using `twine`:

```
$ twine register  -u test -p Test123 --repository http://localhost:80 <package>
```

But, I keep getting:

```
KeyError: u"Missing 'http://localhost:80/simple' section from the configuration file\nor not a complete URL in --repository.\nMaybe you have a out-dated '~/.pypirc' format?\nmore info: https://docs.python.org/distutils/packageindex.html#pypirc\n"
```

What is the right repository URL to use? Thanks and I would be happy to add it to the docs as an example.

**Comment by berkerpeksag** [comment]
I think `http://localhost:80` should be `http://localhost:80/legacy/`.

**Comment by amitsaha** [comment]
OK, turns out I had to directly upload and specify *both* repository URL and repository:

```
$ twine upload  -u test -p Testuser123 --repository-url http://localhost:80/legacy/ --repository=http://localhost:80 <wheel>
```

I will leave the issue open for now, in case my command above works for me but is not right way to do it.

**Comment by sigmavirus24** [comment]
@amitsaha why are you opening a twine bug (that's already been [filed](https://github.com/pypa/twine/issues/206)) against *warehouse*?

This should be closed.

**Comment by amitsaha** [comment]
@sigmavirus24 accept my apologies, i wasn't sure where the problem was.
