### ISSUE TITLE
Signed Packages

### ISSUE THREAD

**Issue by Miserlou** [pypa/warehouse#1439]
Since you're re-doing PyPI, can you add the ability to cryptographically sign packages with GPG keys? I really don't like not having a way to ensure that my users are receiving the packages I intended them to receive.

**Comment by dstufft** [comment]
This should already be supported on both Warehouse and in PyPI itself?

**Comment by Miserlou** [comment]
You're right, I didn't know this was possible! Thanks.

Alternately, remove the ability to _not_ do this, or at least surface this in the documentation outside of the 'security' page: https://pypi.python.org/security

**Comment by vladimir-v-diaz** [comment]
@Miserlou 
I'm curious, why remove the ability to *not* do this?

Donald recently made a post to the distutils mailing list outlining some issues with GPG signatures and PyPI: https://mail.python.org/pipermail/distutils-sig/2016-May/028933.html

**Comment by Miserlou** [comment]
Ideally then then client would have some kind of TOFU-awareness/pinning to
avoid some of the problems he's describing there.

I just think that given how extremely hostile the internet is now because
of nasty governments, companies and other bad actors, I want to make it as
hard as possible to use PyPI as a vector for distributing malware.
Currently - it's very, very easy. :(

**Comment by sigmavirus24** [comment]
> Ideally then then client would have some kind of TOFU-awareness/pinning to avoid some of the problems he's describing there. 

Which client? If people are using ez_install, does setuptools now need to know how to pin keys? How should it find them? By short-id? [I hope that's not the answer.](https://lkml.org/lkml/2016/8/15/445). Where does it store those keys? I for one don't want them added to my keyring. I don't know those people, I haven't personally verified their keys. And further, what if the first download I make against their key is one that a malicious actor uploaded? When the real maintainers release a new version, TOFU tells me I can't trust the new package? That provides no security value.

> I want to make it as hard as possible to use PyPI as a vector for distributing malware.

By requiring a PGP key? Bad actors will do whatever they must to distribute malware. What you're actually limiting is someone trying to share their package who's never encountered PGP from doing so. I find it hard to determine how PGP keys prevent malware distribution.

As a side note, PGP makes it harder to have a *team* of people distributing software. If each person has their own signing key, then how does one pick a key to trust when downloading that package? It's poor key hygiene for them to share a signing key, so do they just stop signing things?
