### ISSUE TITLE
Support for proxying remote warehouse repositories when installed locally

### ISSUE THREAD

**Issue by silkentrance** [pypa/warehouse#1455]
Are there any plans to allow configuration of the warehouse so that it will pass requests to remote warehouses as well? See for example Apache Archiva or Nexus.

Having this feature would be very nice.

**Comment by dstufft** [comment]
Hi!

Warehouse isn't really designed to be deployed by anyone other than the PSF in service of PyPI itself (and local developers developing it). This allows us to focus entirely on the features and scenarios that we need for PyPI and instead let projects like [DevPI](http://doc.devpi.net/latest/) handle use cases like this.

Thanks for your interest though!
