### ISSUE TITLE
[Question] : Setting up dev environment in Fedora 24 -- make serve failed !

### ISSUE THREAD

**Issue by mramanathan** [pypa/warehouse#1486]
Trying to setup dev environment on laptop running Fedora 24.

cloned the code base from:
https://github.com/pypa/warehouse.git

**on a new terminal :  make build passed
on a second terminal : make serve failed with these errors:**

ERROR: for worker  no such file or directory
ERROR: for web  no such file or directory
ERROR: for app  no such file or directory
ERROR: for static  no such file or directory
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'
Makefile:91: recipe for target 'serve' failed
make: *** [serve] Error 1

**System and docker info follows:**

*uname -r 
Linux <blah-blah> 4.7.7-200.fc24.x86_64 #1 SMP Sat Oct 8 00:21:59 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

_docker images installed until now:_
warehouse_app
warehouse_static
warehouse_web
warehouse_worker
docker.io/elasticsearch
docker.io/redis
docker.io/rabbitmq
docker.io/python
docker.io/postgres
docker.io/pypa/warehouse-camo
docker.io/hello-world

List of active docker processes / containers:  
postgres:9.5
redis:latest
pypa/warehouse-camo:latest
rabbitmq:latest
elasticsearch:2.2

BTW, all are in state 'Up'.

Wondering what's gone wrong with make serve to throw traceback errors ?

**Comment by di** [comment]
Hi @mramanathan! It looks like you found an old bug in `docker-compose`: https://github.com/docker/compose/issues/3432

You should update your `docker-compose` version, you can do that with `pip install docker-compose --upgrade`.

I'm going to close this issue for now since it's not a problem with Warehouse, but feel free to comment here if you continue to have other issues getting set up.
