### ISSUE TITLE
Process for releasing registered but apparently unused names for reuse

### ISSUE THREAD

**Issue by nchammas** [pypa/warehouse#1487]
What's the process for investigating whether a name registered on PyPI can be released for reuse by another party? Do we file an issue here, submit something via the [feedback form](https://pypi.org/help/#feedback), or something else?

To provide context, some contributors to the [Apache Spark](https://spark.apache.org/) project are gearing up to [package the project for distribution via PyPI](https://github.com/apache/spark/pull/15659). We're considering publishing under the name `pyspark`, since that's the name of the Python API for Apache Spark, and it's how the interactive PySpark shell is invoked. However, it appears that `pyspark` is already registered.

**Comment by dstufft** [comment]
So, we don't currently have a real process for this. It's kind of very adhoc at the moment. It appears pyspark is registered to user `prabinb`. If that username means anything to you then I'd suggest reaching out to them. If not I can send them an email and ask if they mind giving up the name.

**Comment by nchammas** [comment]
Hmm, no I don't recognize that name. @holdenk, do you?

**Comment by holdenk** [comment]
Its close to the name of the person who created SPARK-1267 back in 2014 about adding pip installability to Spark. I can try and see if I can get in touch with them through JIRA (but if we end up needing to use apacha-spark anyways).

**Comment by dstufft** [comment]
If y'all don't know the name I can poke them via the email address they have on file in PyPI's DB and see if they'll give up the name. I just figured if you knew them it'd be easiest that way first.

**Comment by nchammas** [comment]
@holdenk - I've contacted that person on JIRA to see if it's them. See the comments on [SPARK-18128](https://issues.apache.org/jira/browse/SPARK-18128).

**Comment by di** [comment]
Is it possible this person is the same as @prabinb? That user has a fork of https://github.com/apache/spark.

**Comment by nchammas** [comment]
I sounds like that user came through on JIRA and released the registration.

@holdenk - Shall we close this?

**Comment by holdenk** [comment]
Sounds good :)
