### ISSUE TITLE
Trailing slash on search path before query params

### ISSUE THREAD

**Issue by pauricthelodger** [pypa/warehouse#1488]
Hey folks,

Was playing with opensearch and noticed that the url for a warehouse search is `https://pypi.org/search/?q=hello` with a trailing slash between the end of the path and start of the query parameters.

If you try `https://pypi.org/search?q=hello`, it returns the default search list as if no query params were given so just wanted to doublecheck that this was the intended behaviour?

**Comment by dstufft** [comment]
Ah, this is because the redirection from no slash to slash isn't keeping the query string.

**Comment by dstufft** [comment]
Thinking more, I bet it's [vcl/main.vcl#L37-50](https://github.com/pypa/warehouse/blob/be37f23776af28894727e3a1ec4a939706983879/vcl/main.vcl#L37-L50) only expecting a search with a trailing slash. Allowing that to work without a trailing slash should fix it.
