### ISSUE TITLE
Show reverse dependencies on the package page

### ISSUE THREAD

**Issue by jodal** [pypa/warehouse#149]
When using wheel and twine to upload a package, PyPI and Warehouse will have information about the dependencies of said package. It would be very nice to be able to look up the reverse relationship, the dependents, on the package's listing in Warehouse.

**Comment by dstufft** [comment]
This regressed with the move to Pyramid.

**Comment by nlhkabu** [comment]
We have this featured in the new UI and @dstufft has created a new issue (#789) to cover the technical integration, so I am going to close this now.
