### ISSUE TITLE
Show pip installation instructions to include `--pre` as appropriate for latest release

### ISSUE THREAD

**Issue by brettcannon** [pypa/warehouse#1503]
E.g. https://pypi.org/project/azure/ points to 2.0.0rc6, but the instructions on the page say to do `pip install azure` which won't work due to the lack of `--pre` flag in the command.

**Comment by di** [comment]
Nice catch. We might want to do more than just add the `--pre` flag to the command if it's a pre-release, specifically for the users who might not be familiar with pre-releases or might not want a pre-release. Perhaps:

* add a warning or label that the command will give you a pre-release?
* explain to the user that they likely don't want a pre-release?
* somehow give an alternate command to install a non-pre-release version?
* display the latest non-pre-release version instead if a version is not specified, and indicate that a pre-release is available? (this is likely not a great idea).

**Comment by lmazuel** [comment]
Maybe change the first green badge to orange with "Latest pre-release, click here for latest stable"?

My two cents,

**Comment by lmazuel** [comment]
Exemple for Nuget: https://www.nuget.org/packages/Microsoft.Azure.Management.Compute/
Latest stable has a blue tag:

> There is a newer prerelease version of this package available.
See the version list below for details.

And preview versions have an orange box

> This is a prerelease version of Microsoft.Azure.Management.Compute.

**Comment by dstufft** [comment]
FWIW I had always intended for ``/project/<foo>/`` to show the latest non pre-release version (to match what would happen if someone just typed ``pip install foo``) as described in the version selecting in PEP 440.

**Comment by dstufft** [comment]
#1519 should fix this so that the "latest" concept in Warehouse matches what pip does (which comes from PEP 440).
