### ISSUE TITLE
Provide a direct link in the release history to the latest release

### ISSUE THREAD

**Issue by brettcannon** [pypa/warehouse#1504]
I.e. when you go to "Release History" for a project the latest release has no link while all other releases do. This means there's no easy way to grab the URL for the specific current release like you get when you click the "Newer version available" button on an older release.

**Comment by waseem18** [comment]
@di I would like to look into this issue!

**Comment by FlaviaBastos** [comment]
Hey, @waseem18! Are you working on this or could I take it?
