### ISSUE TITLE
"Newer version available" not correct if pre-release page

### ISSUE THREAD

**Issue by lmazuel** [pypa/warehouse#1529]
No big deal, but after the release of #1519, when you are on a *recent* preview package the version badge shows "Newer version available" for the latest stable:

![image](https://cloud.githubusercontent.com/assets/1050156/20896960/efa29c9a-bad4-11e6-8a34-40426930a5cd.png)

This is technically false, this is not a newer version, but the latest stable. I humbly think in this case this might confuse people.

This might be true for a 1.0.0rc1 compared to a 1.0.0, but not for a 2.0.0rc1 compared to a 1.0.0.

FYI @brettcannon

**Comment by dstufft** [comment]
Ah yes. It should maybe be orange or something that just says that this is a pre-release version and the latest stable is X.
