### ISSUE TITLE
Tests depend on `manifest.json` existing

### ISSUE THREAD

**Issue by di** [pypa/warehouse#1536]
Currently, running `make tests` from a clean checkout of Warehouse (namely, before trying to compile any static assets) will fail multiple tests because the file `/app/warehouse/static/dist/manifest.json` will not exist:

```
tests/conftest.py:144:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
warehouse/config.py:360: in configure
    strict=not prevent_http_cache,
warehouse/utils/static.py:20: in __init__
    super().__init__(*args, **kwargs)
/usr/local/lib/python3.5/site-packages/pyramid/static.py:263: in __init__
    self._manifest = self.get_manifest()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <warehouse.utils.static.ManifestCacheBuster object at 0x7fa897670320>

    def get_manifest(self):
>       with open(self.manifest_path, 'rb') as fp:
E       FileNotFoundError: [Errno 2] No such file or directory: '/app/warehouse/static/dist/manifest.json'

/usr/local/lib/python3.5/site-packages/pyramid/static.py:266: FileNotFoundError
```

In Travis, we're running `gulp dist` before running the test suite, so we're not seeing this issue there. Similarly, most developers have at some point compiled the static assets and built this file, so  the tests don't fail.

We should either ensure that this file is built before running the test suite, or fix the tests to not depend on it existing.

**Comment by dstufft** [comment]
The tests generally rely on having ``make serve`` running don't they?

**Comment by dstufft** [comment]
(Maybe they don't and I'm a crazy person though!)

**Comment by di** [comment]
You don't have to run `make serve` before running the tests, if no containers are running, it will start the following:
```
Starting warehouse_rabbitmq_1
Starting warehouse_db_1
Starting warehouse_redis_1
Starting warehouse_elasticsearch_1
```
(but not the static container)

**Comment by di** [comment]
We could fix this by adding `static` to the `links` for the `web` worker, but I wasn't convinced we should necessarily have that dependency just for this file.

**Comment by brainwane** [comment]
In our [meeting today](https://wiki.python.org/psf/PackagingWG/2017-12-19-Warehouse) I asked us to double-check and we confirmed this isn't urgent enough for a near-term milestone.

**Comment by di** [comment]
I would really love it if someone could fix this during the packaging sprints!

**Comment by matt-land** [comment]
Would it be acceptable to test for the presence of manifest file, and  "mark skipped" if the file does not exist yet?

**Comment by Bjwebb** [comment]
@nlhkabu Could I take this issue please.

**Comment by di** [comment]
@Bjwebb We have an open PR for this already: https://github.com/pypa/warehouse/issues/3978

You can help by reviewing that PR though!

**Comment by xni** [comment]
@di, may be it makes sense to mark it for Bloomberg 2018 Event?

**Comment by shevelevs** [comment]
+1, sounds like an issue that could be addressed by https://github.com/orgs/pypa/projects/1

**Comment by di** [comment]
Can someone create a new PR resolving the conflicts from #3978 and verify that it works?
