### ISSUE TITLE
pip Install ran, but Python cannot find the module  

### ISSUE THREAD

**Issue by timheaton** [pypa/warehouse#1604]
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import scrubadub

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import scrubadub
ImportError: No module named scrubadub
>>>

**Comment by di** [comment]
Hi @timheaton, this is the repository for Warehouse, the service which powers https://pypi.org/.

It seems like a better place for your issue might be https://github.com/datascopeanalytics/scrubadub/issues (the repository for `scrubadub`).

**Comment by timheaton** [comment]
ugh, sorry!
