### ISSUE TITLE
docker-machine on DO fails during npm install on build

### ISSUE THREAD

**Issue by tony** [pypa/warehouse#1616]
Everything works OK locally on Sierra.  Docker machine deployments failing for some reason.

0c260a2  

I've isolated it down to this line: https://github.com/pypa/warehouse/blob/master/Dockerfile#L39

512 MB Memory / 20 GB Disk / NYC3 - Ubuntu 16.04.1 x64

```
+ cd /tmp/packages
+ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Killed
ERROR: Service 'app' failed to build: The command '/bin/sh -c set -x     && cd /tmp/packages     && npm install' returned a non-zero code: 137
make: *** [.state/docker-build] Error 1
```

Trying to figure why `npm install` is getting killed.

There's a possibility this could be memory related (node-gyp's building?) and that npm could lead to memory issues. Digging into it.

**Comment by tony** [comment]
1gB digital ocean gets farther:

```
--> Running in 7b6cf6e64ec7
+ cd /tmp/packages
+ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> iltorb@1.0.13 install /tmp/packages/node_modules/iltorb
> node-gyp rebuild



ERROR: Service 'app' failed to build: The command '/bin/sh -c set -x     && cd /tmp/packages     && npm install' returned a non-zero code: 1
make: *** [.state/docker-build] Error 1
```

It is getting stuck building extensions. Continuing

**Comment by di** [comment]
Hi @tony, it's pretty likely that you're running out of memory on the host machine. 512MB is pretty tight for Warehouse to run on.

If you're using Docker machine, [you can increase the memory allocated to the VirtualBox host](http://stackoverflow.com/questions/32834082/how-to-increase-docker-machine-memory-mac). Personally I have this set to 2GB and have had no out-of-memory issues.

I'd also recommend upgrading to [Docker for Mac](https://docs.docker.com/docker-for-mac/) or [Docker for Windows](https://docs.docker.com/docker-for-windows/) (depending on your host OS) if you are able, but it's probably not necessary.

**Comment by tony** [comment]
2gB fixed it.

The other thing is `make initdb`.

```
initdb:
        docker-compose run web psql -h db -d postgres -U postgres -c "DROP DATABASE IF EXISTS warehouse"
        docker-compose run web psql -h db -d postgres -U postgres -c "CREATE DATABASE warehouse ENCODING 'UTF8'"
        xz -d -k dev/$(DB).sql.xz
        docker-compose run web psql -h db -d warehouse -U postgres -v ON_ERROR_STOP=1 -1 -f dev/$(DB).sql
        rm dev/$(DB).sql
        docker-compose run web python -m warehouse db upgrade head
        $(MAKE) reindex
```

The file needs to get copied over.

**Comment by tony** [comment]
@di Re: OS X, yeah Docker For Mac has been great.

**Comment by di** [comment]
@tony It looks like `dev/example.sql` already exists locally for you, so `xz` is refusing to compress over it.

This is probably due to a `make initdb` command being run but not finishing for some reason, and thus not getting to the `rm dev/$(DB).sql` part.

If you `rm dev/example.sql`, `make initdb` should work.

**Comment by tony** [comment]
I'm a tad confused.

```
~/work/warehouse master* 9s
❯ rm dev/example.sql

~/work/warehouse master*
❯ make initdb
docker-compose run web psql -h db -d postgres -U postgres -c "DROP DATABASE IF EXISTS warehouse"
Starting warehouse_elasticsearch_1
DROP DATABASE
docker-compose run web psql -h db -d postgres -U postgres -c "CREATE DATABASE warehouse ENCODING 'UTF8'"
Starting warehouse_elasticsearch_1
CREATE DATABASE
xz -d -k dev/example.sql.xz
docker-compose run web psql -h db -d warehouse -U postgres -v ON_ERROR_STOP=1 -1 -f dev/example.sql
Starting warehouse_elasticsearch_1
dev/example.sql: No such file or directory
make: *** [initdb] Error 1

~/work/warehouse master* 14s
❯ ls dev
clean.sql      example.sql    example.sql.xz
```

**Comment by tony** [comment]
I'm wondering if the reason is, since it's docker-machine (in the cloud), it's in fact looking for `dev/example` on the machine (master in the cloud), instead of my local machine I'm controlling it from.

**Comment by di** [comment]
Yeah, I'm not sure that will work, because docker-compose depends on mounting local volumes into the container. See https://github.com/pypa/warehouse/blob/1f55ed756716bd9e3018d10a6fbf10e409f50594/docker-compose.yml#L25-L38

**Comment by tony** [comment]
D: yeah that may do it

so deployment of warehouse with docker-machine may be a no go?

haven't deployed docker to production before so been experimenting w/ em.

**Comment by dstufft** [comment]
We don't really support the use of Warehouse outside of development and our own production deployment at pypi.org. While It should generally work if you get it set up, it's not really designed for it and we don't document things like one-off data migrations we run outside of alembic or anything like that.

In that vein, our docker setup exists entirely to make local development easier to get setup and is not in any way designed for a production deployment. That file it's trying to copy is a (sanitized) database dump of TestPyPI, so if you're trying to set this up on your own, you don't really need it.

**Comment by tony** [comment]
yea i'm intertwining my docker exploration with pypa/warehouse biz.

Warehouse works like a charm locally on OS X. 

Closing
