### ISSUE TITLE
Properly style the error pages

### ISSUE THREAD

**Issue by alex** [pypa/warehouse#162]
This includes (but is probably not limited too):
- [ ] 500
- [ ] 404
- [ ] 410 (Maybe? Not sure if we'll ever use it.)
- [ ] 403

**Comment by dstufft** [comment]
One thing that I think would be kind of cute to do, is on the 404 page, embed a link to https://www.youtube.com/watch?v=cWDdd5KKhts as an easter-egg referencing both the "unofficial" name of PyPI and the fact that the skit itself is about a cheeseshop that's missing any cheese... essentially a 404 ;)

**Comment by dstufft** [comment]
Bonus points if we stick the real 404 content at the top, then lead into the embedded youtube with a "And now for something completely different".
