### ISSUE TITLE
API to get checksums

### ISSUE THREAD

**Issue by jakirkham** [pypa/warehouse#1638]
It would be nice if there was some way to get the checksum via the API for a particular package (version and format).

**Comment by dstufft** [comment]
There is the legacy JSON interface: https://wiki.python.org/moin/PyPIJSON

**Comment by westurner** [comment]
> There is the legacy JSON interface: https://wiki.python.org/moin/PyPIJSON

- https://pypi.python.org/pypi/pip/json
- https://pypi.org/pypi/pip/json
  - ``curl 'https://pypi.org/pypi/pip/json' | python -m json.tool``
  - ( https://github.com/pypa/warehouse/blob/master/warehouse/routes.py )

**Comment by jakirkham** [comment]
So part of my interest is to get access to the `sha256` checksums. As these are using the legacy interface, it appears it only gives me `md5`.

**Comment by westurner** [comment]
From
https://github.com/pypa/warehouse/blob/master/warehouse/legacy/api/json.py :

```

  "digests": {
                    "md5": f.md5_digest,
                    "sha256": f.sha256_digest,
                },

```

**Comment by jakirkham** [comment]
Yep, sorry, that is what I meant by the edit. Thanks.

**Comment by westurner** [comment]
np

**Comment by dstufft** [comment]
Going to close this since it already exists. Thanks.
