### ISSUE TITLE
Implement a Read Only Flag to prevent any write operations

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#164]
There are times when we need to prevent any state modification on pypi.python.org but we do not need to prevent reading from the database or other storage areas. It would be great if we could prevent all write operations using a toggle somehow.

**Comment by di** [comment]
@dstufft Any ideas about where would be the best place to short-circuit this? Perhaps a `@db.listens_for(db.Session, "before_commit")` or something to abort the commit?

**Comment by dstufft** [comment]
``request.tm.doom()`` should allow the request to continue, but abort it at the last minute.
