### ISSUE TITLE
Request trove classifiers for Pelican

### ISSUE THREAD

**Issue by MinchinWeb** [pypa/warehouse#1650]
I would like to request trove classifiers for Pelican, specifically:

```
Framework :: Pelican
Framework :: Pelican :: Plugins
Framework :: Pelican :: Themes
```

The request has been kicking around for a while, so I apologize in advance if already been dealt with.

Historical record:

- original request (that I could find) -- [Disutils mailing lsit](https://mail.python.org/pipermail/distutils-sig/2013-July/021672.html) -- July 2013
- [Bitbucket ticket](https://bitbucket.org/pypa/pypi/issues/238) -- Feb 2015 -- which was transferred to...
- [PyPI legacy ticket](https://github.com/pypa/pypi-legacy/issues/238) -- which instructed it to be reported here...

**Comment by ewdurbin** [comment]
Done.

**Comment by MinchinWeb** [comment]
Awesome! Thank you!
