### ISSUE TITLE
Request trove classifier for Django 1.11

### ISSUE THREAD

**Issue by timgraham** [pypa/warehouse#1673]
`'Framework :: Django :: 1.11'`

**Comment by claudep** [comment]
Please...

**Comment by timgraham** [comment]
I've asked about the process for adding new trove classifiers on [pypa-dev](https://groups.google.com/d/topic/pypa-dev/zjEICwYioPY/discussion).

**Comment by ewdurbin** [comment]
This was completed https://github.com/pypa/pypi-legacy/issues/624
