### ISSUE TITLE
uploading python 2.7, windows wheels hang

### ISSUE THREAD

**Issue by fgregg** [pypa/warehouse#1674]
Uploading a python 2.7, windows wheel is seeming to hang forever.

Traceback: https://ci.appveyor.com/project/fgregg/dedupe/build/1.0.743/job/7vkuec72gbaiisal#L253

* uploading with `python setup.py bdist_wheel upload`
* uploads work fine with windows and python 3.4, or python 2.7 and other OS
* double checked password
* retried 5 times over 12 hours

**Comment by fgregg** [comment]
I used twine and it uploaded. My, personal issue, is resolved.

**Comment by dstufft** [comment]
I'm not able to reproduce this and since twine seems to resolve it I'm going to assume it was transient.
