### ISSUE TITLE
Search by topic broken ?

### ISSUE THREAD

**Issue by alexgarel** [pypa/warehouse#1712]
Browsing packages, then choosing the Internet / WWW9HTTP / Browser topics gives no result:

https://pypi.org/search/?q=&o=&c=Topic+%3A%3A+Internet+%3A%3A+WWW%2FHTTP+%3A%3A+Browsers

There should be at least the [mechanoid package](https://pypi.org/project/mechanoid/)

Using firefox 50.1:0 on Ubuntu 16.04

**Comment by di** [comment]
This does indeed seem to be a bug with filtering by any classifier, thanks for reporting it.
