### ISSUE TITLE
Search results form layout

### ISSUE THREAD

**Issue by termim** [pypa/warehouse#1727]
The signal to noise ratio for the search results form is extremely low comparing to the old pypi.python.org. The most of the real estate space given to the results itself is empty. This leads to an artificial pagination - 20 results per page and inability to use browser to search the results further.

The footer takes disproportionally big part of the page. Compare it to what is there on github or on the pypi.python.org  

Package name, version and short description should fit into one or two lines and the icon, if at all needed, shouldn't require an additional huge spacing.

**Comment by nlhkabu** [comment]
Thanks for your feedback @termim - I have opened #1988 to address this and other similar feedback.
