### ISSUE TITLE
Packages with an underscore in their name are difficult to find

### ISSUE THREAD

**Issue by sekrause** [pypa/warehouse#1736]
- A search for "[cx_Freeze](https://pypi.org/search/?q=cx_Freeze)" doesn't actually find cx_Freeze.
- A search for "[cx-Freeze](https://pypi.org/search/?q=cx-Freeze)" or "[cx\\_Freeze](https://pypi.org/search/?q=cx%5C_Freeze)" does.

I think it shouldn't be necessary to escape the underscore so that cx_Freeze can be found by searching for its exact name.

**Comment by sohail288** [comment]
I have some further notes:

- searching for [ls_json](https://pypi.org/search/?q=ls_json) yields ls_json
- searching for [tc_aws](https://pypi.org/search/?q=tc_aws) DOES NOT yield tc_aws, instead, escaping the "_", yields [some results including tc_aws](https://pypi.org/search/?q=tc%5C_aws)
- searching for [job_stream](https://pypi.org/search/?q=job_stream) yields job_stream

**Comment by jaddison** [comment]
Using the current Elasticsearch field mappings, I believe that the Elasticsearch `NameAnalyzer` would need to normalize all underscores to hyphens/dashes for index + searching phases.

See https://github.com/pypa/warehouse/blob/3b68bbcf00c074506fa1e867169620a3a2eab81d/warehouse/packaging/search.py#L26

---

I've only just glanced at the code, but a better approach **might** be to get rid of `Project.normalized_name`[1] in favour of using a multi-field[2] for `Project.name`. The multi-field could have the following Elasticsearch field types:

1. `Project.name` -> `text` (this field wouldn't need to be tokenized/analyzed, I don't think)
1. `Project.name.normalized` -> `keyword` (used for exact search/lookup/sorting purposes + URL routing)
1. `Project.name.suggest` -> `completion` (autocomplete purposes)

Notes:
* if using the `completion` field type, there may be some technical reasons to make this its own field (ie. `Project.name_suggest`). Looking for answers here[3]
* it's also possible the autocompletion field might be better off as an edgeNgram-based custom analyzer[4] type setup - depending on requirements

[1] https://github.com/pypa/warehouse/blob/3b68bbcf00c074506fa1e867169620a3a2eab81d/warehouse/packaging/search.py#L37
[2] https://www.elastic.co/guide/en/elasticsearch/reference/5.2/multi-fields.html
[3] https://discuss.elastic.co/t/multi-field-completion-type/79478
[4] https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-analyzer.html

**Comment by di** [comment]
Looking at this now, it no longer seems to be an issue:

* First result for https://pypi.org/search/?q=cx_Freeze is `cx_Freeze`
* First result for https://pypi.org/search/?q=tc_aws is `tc_aws`

In fact, I tried about 20 different packages with underscores in their names and the first result was consistently the corresponding package.
