### ISSUE TITLE
Request trove classifiers for MicroPython

### ISSUE THREAD

**Issue by deshipu** [pypa/warehouse#1744]
I would like to request addition of a trove classifier for MicroPython, specifically:

```
Programming Language :: Python :: Implementation :: MicroPython
```

MicroPython is an implementation of (a subset of) Python 3 for systems that are resource-constrained, in particular, among others, for microcontrollers. The main project page is located at http://micropython.org/ where other information can be found. MicroPython is famous for running on the BBC Micro:bit devices that are used for education in the United Kingdom, but it also runs on a number of other platforms and is used in other disciplines, including space industry.

There is already a number of packages for MicroPython published on PyPi (most of them can be found by searching for "micropython" or "upy"), however, adding this classifier would allow for marking them more consistently.

**Comment by ewdurbin** [comment]
Done.
