### ISSUE TITLE
How do I transfer ownership of packages?

### ISSUE THREAD

**Issue by tejasmanohar** [pypa/warehouse#1745]
How do I transfer package ownership? I want to transfer
- gevent_semaphore_decorator
- gevent_semaphore_decorator
- gevent_ticker

to `segment` on Pypa. I've transferred all of the repos from `tejasmanohar` (me) to `segmentio` (note that the pypa username is `segment` without the `io`) on GitHub to show intent.

- https://github.com/segmentio/gevent-ticker
- https://github.com/segmentio/gevent-semaphore-decorator
- https://github.com/segmentio/gevent-timer

Thanks in advance!

**Comment by di** [comment]
@tejasmanohar You will need to do this through pypi-legacy, not Warehouse, by adding an "ownership" role for the `segment` user to each package:

https://pypi.python.org/pypi?:action=role_form&package_name=gevent_ticker
https://pypi.python.org/pypi?:action=role_form&package_name=gevent_semaphore_decorator
https://pypi.python.org/pypi?:action=role_form&package_name=gevent_timer

Feel free to reply if you have any other issues.

**Comment by tejasmanohar** [comment]
Done! Is there a primary owner or are they all equal? Can I remove my own ownership? I have access to segment anywyays :)

**Comment by di** [comment]
> Is there a primary owner or are they all equal?

They are all equal.

> Can I remove my own ownership?

You can remove your own ownership only if there are other owners.
