### ISSUE TITLE
XML-RPC API issue

### ISSUE THREAD

**Issue by maclover7** [pypa/warehouse#1764]
Hi,

I am trying to use the XML-RPC API provided by Warehouse (pypi.org/pypi), but I keep getting errors when trying to use the `release_data` method. Just a note that I am using Ruby to access the API, but here is the error I'm getting:

```ruby
[18] pry(main)> server.call('release_data', 'django', '1.4')
RuntimeError: wrong/unknown XML-RPC type 'nil'
from /Users/jon/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/xmlrpc-0.3.0/lib/xmlrpc/parser.rb:501:in `startElement'
```

All other API methods (ex: `package_releases`, `list_packages`) seem to be working fine.

**Comment by di** [comment]
Looks like you can set the following configuration for your parser to allow for `nil` values:

```rb
XMLRPC::Config::ENABLE_NIL_PARSER = true
```

See https://github.com/ruby/xmlrpc/blob/master/lib/xmlrpc/parser.rb#L418-L423
