### ISSUE TITLE
Wolframalpha 3.0 usage guide error

### ISSUE THREAD

**Issue by C-Jameson** [pypa/warehouse#1863]
I hope this is the right place to submit this. The code block: 
```
for pod in res.pods:
  for sub in pod.subpods:
  print(sub.text)
```
at https://pypi.org/project/wolframalpha/ is incorrect. The code as written returns 
```
  val = self[name] if name in self else self[attr_name]
KeyError: '@text'

During handling of the above exception, another exception occurred:

  raise AttributeError(name)
AttributeError: text

```
This error can be fixed by amending the code to read:
``` 
for pod in res.pods:
  for sub in pod.subpods:
      print(sub.plaintext)
```

**Comment by di** [comment]
Hi @C-Jameson, this is the repository for the codebase which powers https://pypi.org/.

The `wolframalpha` module's homepage is at https://github.com/jaraco/wolframalpha, you should open this issue there instead.
