### ISSUE TITLE
Trove classifiers l2 to l5 are foreign keys

### ISSUE THREAD

**Issue by Carreau** [pypa/warehouse#1900]
AFAICT, in the trove_classifiers table, L2 to L4 are foreign keys on `id` (of the parent classifier).  Except when they are 0, which I'm not sure how to handle. But L2 is never 0, as it is at worst same-row-id. 

I don't know if that can be useful, at least that should clarify what they are for future readers instead of purely "integers".

**Comment by di** [comment]
👍 Thanks for this bit of knowledge, @Carreau. I'm going to close this since there isn't anything actionable here for us at the moment.

**Comment by Carreau** [comment]
> I'm going to close this since there isn't anything actionable here for us at the moment.

Seem reasonable ! Thanks ! I

'm not a postgres/db person, but if you are looking for action items, change the schema to say they are ` foreign keys` ? Though you might not be able to do that as they may be 0. Looking fwd to warehouse replacing PyPI-legacy also excited (and congratulation) for your funding.
