### ISSUE TITLE
Request trove classifier for Windows 8 and Windows 10

### ISSUE THREAD

**Issue by freakboy3742** [pypa/warehouse#1903]
Trove classifiers exist for all Microsoft Windows versions up to Windows 7. Since then, versions 8, 8.1 and 10 have been released. I propose the addition of the following 3 classifiers:

```
Operating System :: Microsoft :: Windows :: Windows 8
Operating System :: Microsoft :: Windows :: Windows 8.1
Operating System :: Microsoft :: Windows :: Windows 10
```

**Comment by ewdurbin** [comment]
Done!
