### ISSUE TITLE
Suggested search results give the wrong count

### ISSUE THREAD

**Issue by alexwlchan** [pypa/warehouse#1923]
If I run a search on Warehouse that's slightly misspelt – e.g. "betamazx" (https://pypi.org/search/?q=betamazx) – because there aren't any results, it helpfully suggests that maybe I meant something else:

<img width="826" alt="There were no results for '*betamazx*'. Did you mean 'betamax'? (4 results)" src="https://cloud.githubusercontent.com/assets/301220/25083034/89af2008-234c-11e7-9110-b285a846d770.png">

And indeed, the suggestion is helpful – I click the link, and I see search results for "betamax", including the package I was looking for. But the count is wrong – the final page has 14 results, not 4.

Other mistyped searches:

* reqwests suggests "requests (83 results)", but a search for "requests" yields 5,951 results
* caverage suggests "coverage (13 results)", but a search for "coverage" yields 4,916 results
* hiper (3) sends me to hyper (142)

**Comment by di** [comment]
Thanks for the report! It seems like the "suggestions" that elasticsearch gives us is only based on the project name, but our actual search results include hits on other fields as well.

**Comment by bstutes** [comment]
The "actual" search is returning a list of modules that mention they use the "betamax" module somewhere in the project description.  Are you sure you want to label this as a "bug" or should the additional modules be listed just in case as user wants to also see where the module being searched for is used?  I just wanted to be sure before I took a shot at working on this "bug".

**Comment by di** [comment]
This isn't a bug per se, but it definitely appears to the user that the count is off, by saying "4 results" and not something more (or less) specific.

It's going to be near-impossible to get the suggested "results" and the actual number of results to agree. Currently we search across quite a lot of fields:
```python
SEARCH_FIELDS = [
    "author", "author_email", "description", "download_url", "home_page",
    "keywords", "license", "maintainer", "maintainer_email", "normalized_name",
    "platform", "summary",
]
```
We would need to add an individual suggestion to the query for each of these fields, somehow determine which is the "top" suggestion from all of them aggregated together. Then, to get the actual number of results, we would have sum the results for each field, but ensure that we're not double-counting packages that have hits for the "top" suggestion in multiple fields.

It all seems like overkill for a feature that's not particularly useful in the first place -- we only give the user one suggestion, so the number of results doesn't actually matter.

I'd be in favor of just not showing the # of suggested results instead.

**Comment by alexwlchan** [comment]
> I'd be in favor of just not showing the # of suggested results instead.

I think that’s the most sensible fix.

**Comment by bstutes** [comment]
I have issued a pull request for this "bug".  The only commit that matters is 8be1e95.  The others were from cleaning comments about changes made.

**Comment by nlhkabu** [comment]
I believe that we can close this now https://github.com/pypa/warehouse/pull/2028 is merged.  If I am incorrect please reopen.

Thanks for your contribution @bstutes :)
