### ISSUE TITLE
Is there a modern equivalent to PyPI's XML-RPC .top_packages() ?

### ISSUE THREAD

**Issue by cclauss** [pypa/warehouse#1930]
Is there a more modern, supported way of determining __the relative popularity of all PyPI packages?__

The legacy [PyPI XML RPC API](https://warehouse.pypa.io/api-reference/xml-rpc)'s __top_packages()__ call returns a `sorted list of packages ranked by number of downloads.`  My sense is that the `number of downloads` does not include pip installs.  (Is that correct?)

The simple API returns 106,086 while https://pypi.org says 106,147 Projects and top_packages() returns only 96,104.

```python
import bs4
import requests
import xmlrpclib

soup = bs4.BeautifulSoup(requests.get('https://pypi.org/simple/').text, 'lxml')
links = soup.find_all('a')
print(len(links))  # 106,086
print(len(set(links)))  # 106,086

client = xmlrpclib.ServerProxy('https://pypi.org/pypi')
print(len(client.top_packages()))  # 96,104
```

**Comment by dstufft** [comment]
The best method is to query BigQuery directly: https://langui.sh/2016/12/09/data-driven-decisions/

downloads hasn't been reliabily updating for some time :/

**Comment by cclauss** [comment]
Perfect!
