### ISSUE TITLE
Personal Email showing in project page

### ISSUE THREAD

**Issue by gtalarico** [pypa/warehouse#1951]
My apologies if this is not the preferred place to post this.

Last year I accidently pushed a package with my personal email.
I have since removed it, and it's no longer on pypi, but somehow it's still showing here:
https://test.pypi.org/project/foldify/
I don't know where the "Peter" came from.

![image](https://cloud.githubusercontent.com/assets/9513968/25503411/51ea7158-2b68-11e7-860f-99846915ca9e.png)

The pypi project is still there, but my personal info has been removed
https://pypi.python.org/pypi?:action=pkg_edit&name=foldify

Is anyone here able to help me clear that out?

**Comment by di** [comment]
The package you are linking to (https://test.pypi.org/project/foldify/) is on TestPyPI, not PyPI: You can see there is still a release here: https://testpypi.python.org/pypi/foldify/0.3.3

They are separate from each other, so you will need to log into TestPyPI and remove the packages there as well.

**Comment by gtalarico** [comment]
Thank you for your help
