### ISSUE TITLE
Add help text with password policy

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1983]
Related to my work on https://github.com/pypa/warehouse/pull/1982

It would be nice to provide a small piece of help text above the 'select password' section on the registration form.  This help text should explain what our password security policy is.

For example:

> "Choose a password that is over 10 characters long and contains letters, numbers and special characters"

I am happy to put in the text and style it correctly, if I am given a line of text that describes our password requirements.

**Comment by dstufft** [comment]
The answer is that our password policy isn't super easy to put into words like that. A short password with lots of special characters is good, or a long password with only alpha numerics. You also need to avoid things like repeating the same word, or using your username in your password and things of that nature.

Essentially we use the zxcvbn library to test the strength, and if it's < a certain strength we deny it. This does have a javascript implementation as well that we can use to test the strength client side before sending it to the server though, and that same thing can produce strings of text to help the user come up with an acceptable password based upon what they've already added.

**Comment by nlhkabu** [comment]
Ha!  Things are never easy :)

What about:

> It's a good idea for your password to contain letters (both uppercase and lowercase), numbers and special characters. Try not to use common words or repetition.

??
