### ISSUE TITLE
Make lint not working

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1987]
Might just be me... but I am getting this:
![screenshot from 2017-05-13 17-06-06](https://cloud.githubusercontent.com/assets/3323703/26027768/b754190e-380b-11e7-8fa3-0231a1c23a7d.png)

**Comment by dstufft** [comment]
Looks like your env got screwed up somehow. Try deleting the .state directory.

**Comment by nlhkabu** [comment]
thanks @dstufft :)
