### ISSUE TITLE
List name ownership policies, etc, in footer

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1989]
From https://github.com/pypa/warehouse/pull/1980

> It might make sense to keep this in it's own footer item, if only because rather than "Legal", it'd be a convenient to have a place to list other kinds of policies like name ownership and what not (like PEP 541).

When these policies are added, we will need to reinstate the fourth footer column.

@dstufft - can you please make a list of the policies you think are relevant?

**Comment by di** [comment]
Here's what I think could be in a fourth column:
* Terms of Use
* Code of Conduct
* PEP 541 ("Package Index Name Retention", "Package Name Disputes", "Package Rentention", "Packaging Policies", etc)
* Security Policy (could be moved from the "About PyPI" column to make room for #890)
* Privacy Policy

**Comment by nlhkabu** [comment]
@di can you point me towards the legacy privacy policy page?  Or where I would find the content?

**Comment by nlhkabu** [comment]
Also, for "code of conduct" are you talking about https://www.pypa.io/en/latest/code-of-conduct/, or do we want to create a new code of conduct for *users*?

**Comment by di** [comment]
> @di can you point me towards the legacy privacy policy page? Or where I would find the content?

I'm not sure we have one, but we probably should! [Here's the PSF's privacy policy](https://www.python.org/privacy/), and [here's npm's for example](https://www.npmjs.com/policies/privacy).

> Also, for "code of conduct" are you talking about https://www.pypa.io/en/latest/code-of-conduct/, or do we want to create a new code of conduct for users?

I dunno! Maybe it should be both? Although there isn't much user-to-user interaction happening on PyPI. [Here's the PSF's Community CoC for example](https://www.python.org/psf/codeofconduct/).

**Comment by nlhkabu** [comment]
Great! Could we simply use the PSF privacy policy and code of conduct? Who should we talk to about this?  ping @brainwane and/or @lgh2 for guidance.

**Comment by di** [comment]
I think that would be better than nothing for now. Maybe @brainwane can reach out to Ewa and VanL about whether we should have our own, and circle back later.

**Comment by brainwane** [comment]
After checking with Ewa, I've reached out to the `legal@python` & `psf@python` email lists (which include Ewa & VanL) asking for them to let us know which privacy policy & code of conduct the new PyPI should mention, and linking to this issue. I'll note here what I said in the email:

> Privacy: I presume we can use https://www.python.org/privacy/ . Is there anything else we need to add? I believe there are no relevant differences between the old PyPI and the new PyPI in terms of personal information collection but please feel free to check out https://pypi.org to double-check.

> Code of conduct: I presume that the general Python Community Code of Conduct https://www.python.org/psf/codeofconduct/ applies to all people using the PyPI site and publishing code or speech on the site, and that the PyPA code of conduct https://www.pypa.io/en/latest/code-of-conduct/ further applies to the people working on the Warehouse software itself.

**Comment by brainwane** [comment]
Mark Mangoba is pinging Ewa, VanL, _et alia_ about this.

**Comment by brainwane** [comment]
We'll have more on this on Thursday 8 February.

**Comment by di** [comment]
@brainwane Any updates on this?

**Comment by brainwane** [comment]
I've heard from Ewa and Mark. For the code of conduct, we should use https://www.pypa.io/en/latest/code-of-conduct/ , and for the privacy policy, we should use https://www.python.org/privacy/ . Of course it could be that in the future the PSF or PyPA will make policy changes and we can re-review then, but for now, that's the decision.

Specifically for the CoC, we should explicitly mention that this pertains both to Warehouse as a development project and to PyPI as a Python community site.
