### ISSUE TITLE
Warehouse Displays Hidden Version as Latest

### ISSUE THREAD

**Issue by kpayson64** [pypa/warehouse#2022]
On the legacy PyPi site, when I set the "Hide?" field to Yes for the latest version, it doesn't appear on PyPi as the latest release.  Warehouse shows the hidden version as the latest release.

**Comment by dstufft** [comment]
This is working as intended, Warehouse removes the concept of a hidden release (in practice, people ended up largely confused by them, and the UX changes in Warehouse remove the need for them). Once Legacy shuts down we're going to remove the column from the DB entirely.
