### ISSUE TITLE
Send confirmation link in email on new account registration

### ISSUE THREAD

**Issue by nezhar** [pypa/warehouse#2065]
I just wrote my first package that I wanted to publish on PyPI and didn't have an account. I have registered yesterday through the new registration form: https://pypi.org/account/register/. 

The registration process had no issues, the account was directly active and the log in worked. Today I prepared the package for upload but i received a 401 error:
`Upload failed (401): You must be identified to edit package information`

After some research, I saw also other people complaining, and this might happen if the activation link in the email is not clicked. So one problem might be that the activation email is not being sent and the account is directly active.

Since I don't found any way resending an activation link, and the login with the account worked normally I have deleted the account and made another registration using the old PyPI website: https://pypi.python.org/pypi?%3Aaction=register_form

This time I received an activation link, which led me to a page where I also had to accept the submission terms. So probably this part is missing and this is why the authorization failed with the other account.

**Comment by svenevs** [comment]
Hello, I think the same fix needs to happen for test pypi.  The [guide](https://packaging.python.org/guides/using-testpypi/) asks you to register with a link to [https://test.pypi.org/account/register/](https://test.pypi.org/account/register/).  I was getting some [`401` responses as well](https://stackoverflow.com/q/29350703/3814202), and then found this issue.  Using the linked site, I never received a confirmation e-mail.

Solution: I went to [https://testpypi.python.org/pypi](https://testpypi.python.org/pypi) (where the difference is a `.python` after `testpypi`), deleted the account I just made, and re-registered using this site (so following the link to [https://testpypi.python.org/pypi?%3Aaction=register_form](https://testpypi.python.org/pypi?%3Aaction=register_form)) and saw both a terms agreement as well as received a confirmation e-mail letting me finish the registration.

I believe the [https://github.com/pypa/python-packaging-user-guide](https://github.com/pypa/python-packaging-user-guide) repo is the source code, would a PR fixing the `testpypi` URL be helpful or is the problem more complicated?

**Comment by jonemo** [comment]
I can confirm the reported behavior. I just recently wrote up my learnings from publishing a package to PyPI for the first time ([link to my blog post](https://jonemo.github.io/neubertify/2017/09/13/publishing-your-first-pypi-package/)) and found that

* The registration form on test.pypi.org seems to work
* ... but the confirmation email never arrives and there is no indication to the user that one should arrive
* ... therefore users never get to see the terms and cannot activate their account
* ... and then get a confusing error message when attempting to upload a package

The workaround is to use the registration form on pypi.python.org/pypi, but then complete all other steps on pypi.org.

@svenevs: This is my `.pypirc` with URLs for Test PyPI and real PyPI that worked for me:

```
 #~/.pypirc
    
 [distutils]
 index-servers =
   pypi
   pypitest
    
 [pypi]
 repository: https://pypi.org/legacy/
 username: YOUR_USERNAME_GOES_HERE
    
 [pypitest]
 repository: https://test.pypi.org/legacy/
 username: YOUR_USERNAME_GOES_HERE
```

**Comment by svenevs** [comment]
> The workaround is to use the registration form on pypi.python.org/pypi, but then complete all other steps on pypi.org.

Interesting.  It doesn't work for me, I was already registered on "real" pypi before getting the e-mail from the way I went about it (delete, alternative url).  As such, the URL you have gives me `403` errors :S  Hopefully your fix will apply to most situations.  I think I pigeonholed myself somehow.

**Comment by di** [comment]
Branch for this is here: https://github.com/pypa/warehouse/tree/verify-email-on-registration, blocked on merging #2898.
