### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by FRidh** [pypa/warehouse#2087]
The following can be used to obtain a list of all packages that are available via PyPI:
```
with ServerProxy(index) as client:
    packages = client.list_packages()
```
For some packages the site and the json is missing. Why is that so? Is that because packagers remove their package but it doesn't disappear entirely from the database?
Example [xlrd3k](https://pypi.org/pypi/xlrd3k/json)

I was using the following index https://pypi.org/pypi

**Comment by dstufft** [comment]
I think the JSON and page 404's when the package doesn't have any releases and is just registered.

**Comment by FRidh** [comment]
That seems like a plausible reason. Do you know of a method/call to tell whether this is indeed the case?
I have a [script](https://github.com/pypa/warehouse/issues/1478#issuecomment-306050637) that fetches the JSON of each package and stores it. When updating the database the script retries those packages that failed the previous time.

**Comment by pradyunsg** [comment]
@dstufft 

I would have thought there'd be empty mapping for json and some sort of placeholder page saying that this package is registered but does not have any releases?

Is there any specific reason it's not this way?

PS: Is this something I should try doing?

**Comment by FRidh** [comment]
Closing because this is likely then a duplicate of https://github.com/pypa/warehouse/issues/1388.

**Comment by pradyunsg** [comment]
Indeed.

> Is there any specific reason it's not this way?

It seems no one came about to doing it.
