### ISSUE TITLE
Make logged in dropdown work with keyboard

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2127]
At the moment, it's not absolutely obvious where you are on the page. We need to:

- Highlight selected links better 
- Make dropdown work with keyboard (depends on https://github.com/pypa/warehouse/pull/2125)
- Increase contrast on active buttons

It would be nice if this PR could be done in conjunction with #831

**Comment by nlhkabu** [comment]
First and third point now covered by PRs.

Only "Make dropdown work with keyboard" remains.

**Comment by aalmazan** [comment]
Correct me if I'm wrong, but the remaining issue "Only "Make dropdown work with keyboard" remains." seems to already be fixed on the current master. 

Attached gif is in Chrome while pressing TAB to cycle through the fields while logged in. Also tested with Firefox (current) with the same result.

![dropdown](https://user-images.githubusercontent.com/800948/37076287-ce5fce90-218a-11e8-977a-23a009e4290e.gif)

**Comment by di** [comment]
@aalmazan I think what @nlhkabu is referring to is what she bought up in #3038, which is that the user can't tab to the items in the dropdown menu.

**Comment by brainwane** [comment]
I [just spoke with Nicole in IRC](http://kafka.dcpython.org/day/pypa-dev/2018-03-21) and we agreed that this can wait till after we shut down legacy PyPI.
