### ISSUE TITLE
menu overflow

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2139]
![screenshot from 2017-06-23 07-42-11](https://user-images.githubusercontent.com/3323703/27469454-8abce8d4-57e7-11e7-9d21-8ca66f2191d3.png)

@813px wide.

Will need to give more space here, because these links may become longer when translated.

**Comment by pradyunsg** [comment]
Could someone close this?

Off Topic: @nlhkabu "Closes <issue number>" needs to be mentioned in the first post of the PR, for GitHub to auto close things. :)
