### ISSUE TITLE
A questions about this project

### ISSUE THREAD

**Issue by GreenJoey** [pypa/warehouse#2147]
Looking at this project it seems that the warehouse is entirely written from scratch. Why did the community decided to do so? Why existing frameworks like Django or Flask or others not used for the project? 

Just Curious

**Comment by pradyunsg** [comment]
> Why existing frameworks like Django or Flask or others not used for the project?

They are used. This project uses the Pyramid framework.

> warehouse is entirely written from scratch.

Warehouse is a rewrite of the legacy codebase currently running PyPI, using modern tools and practices.

> Why did the community decided to do so?

The reason it was decided to do so (rewrite the PyPI codebase) was that the legacy codebase was extremely difficult to maintain and extend.

**Comment by dstufft** [comment]
Yea, @pradyunsg covered the basis pretty well. Legacy PyPI is HORRIBLE to work on, it doesn't even run locally unless you comment out a bunch of the code. It predates basically every modern tool in web development, including WSGI itself.
