### ISSUE TITLE
How to completely remove a project?

### ISSUE THREAD

**Issue by cbsteh** [pypa/warehouse#2167]
I am the owner of PySawit project but I like to completely remove this project from the Warehouse. I am able to do this at the old PyPi site but I can't find any feature to do this on Warehouse, not even to hide or edit releases.

The reason for deleting my project is I was testing things around, as I am new to this Python installation packaging. Note that I have no users of this project, as it is actually incomplete, so I won't break anyone's code.

Why is there no feature to hide releases or delete the project?

**Comment by dstufft** [comment]
You can delete the project on the legacy PyPI site. That functionality has not yet been added to Warehouse. See https://github.com/pypa/warehouse/issues/424 for where we are tracking this.

**Comment by cbsteh** [comment]
I have already successfully deleted my project at the Legacy PyPi site but my project still appears at Warehouse. I can even download the files from Warehouse. Is this some sort of sync delay issue? I really need my project at Warehouse to be removed.

**Comment by dstufft** [comment]
The two share the same datastore, but Warehouse heavily caches itself in our CDN provider and legacy PyPI doesn't know how to purge the cache on Warehouse. It will fall out of the cache in up to 24 hours.

**Comment by cbsteh** [comment]
Great! Thank you for your help and quick response.

**Comment by cbsteh** [comment]
For posterity:  I used curl X PURGE. Problem solved.
