### ISSUE TITLE
HTTPError: 400 Client Error: home_page

### ISSUE THREAD

**Issue by egorlitvinenko** [pypa/warehouse#2179]
old repo - https://pypi.org/project/schatz/
new setup.py:

```
from setuptools import setup

setup(
    name='schatz',
    version='1.0.1-alpha',
    ...
    description='Schatz integration package for Python 3',
    ...
)
```

Command

```
~/anaconda3/envs/SchatzPython/bin/twine upload dist/schatz-1.0.1a0.tar.gz --skip-existing
Uploading distributions to https://upload.pypi.org/legacy/
Uploading schatz-1.0.1a0.tar.gz
HTTPError: 400 Client Error: home_page: Invalid URI for url: https://upload.pypi.org/legacy/  
```
My .pypirc contains only username and password.

I use twine and posted an issue - https://github.com/pypa/twine/issues/260.
@sigmavirus24 believes it is not twine's problem. 

So why is it happen? What is a problem?

**Comment by sigmavirus24** [comment]
@egorlitvinenko you probably want to check `url=".."` in your `setup.py`.

**Comment by egorlitvinenko** [comment]
I delete url, it works.

**Comment by pradyunsg** [comment]
@egorlitvinenko What was the url you had that was causing this issue?
