### ISSUE TITLE
Can not update documentation of package

### ISSUE THREAD

**Issue by Sung-Huan** [pypa/warehouse#2183]
Dear all,

I tried to update my documentation this morning, but I can not achieve it.

1. Since the platform is updated (pypi.org), the button for uploading documentation is gone. So, I tried to upload it via python setup.py upload_docs

2. When I run python setup.py upload_docs, I got two different results from two different machines.
    a. The script executed and the files were submitted to https://pypi.python.org/pypi successfully. However, when I open the package documentation in http://pythonhosted.org, the documentation didn't be updated.
    b. I used another machine to run python setup.py upload_docs. For this machine, the script could not execute successfully. A error came out:
Upload failed (410): Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)

Does http://pythonhosted.org still work? Or should I change to use https://readthedocs.org/?

Thank you.

Sung-Huan Yu

**Comment by kklmn** [comment]
Hi,
Right, uploading documentation has become much more difficult than it used to be. The web-based method was by far the easiest. Why has it gone?
In general, the whole migration is so depressive, with a lot of hidden requirements (e.g. "incorrect e-mail" that used to be ok) and undone documentation and undone web pages with dead links. It seems that the doers only consider the scenarios they have used and not so many others'. Bad job. Thumbs down.

**Comment by lingthio** [comment]
See Issue #582

**Comment by dstufft** [comment]
Sorry for the long delay in the response, but as @lingthio mentioned, this will be solved by #582 so I'm going to close this issue in favor of that one.
