### ISSUE TITLE
Will it be pypi.org or pypi.io?

### ISSUE THREAD

**Issue by nchammas** [pypa/warehouse#2184]
In light of [this article](https://thehackerblog.com/the-io-error-taking-control-of-all-io-domains-with-a-targeted-registration/) about the `.io` domain, and the fact that the [launch milestone](https://github.com/pypa/warehouse/milestone/1) still mentions pypi.io, I just wanted to double check that the final home of the new PyPI will in fact be pypi.org and not pypi.io (in addition to pypi.python.org, of course). pypi.io redirects to pypi.org, so I assume that's the case.

Is that correct?

**Comment by dstufft** [comment]
The final home of PyPI will be pypi.org yes. The pypi.io domain currently redirects to pypi.org and once we shut down legacy PyPI for good, then pypi.python.org will redirect to pypi.org as well. The pypi.io domain ended up being a temporary domain before we were able to purchase the pypi.org domain name.
