### ISSUE TITLE
Upload fails if classifier in setup.py is tuple rather than list

### ISSUE THREAD

**Issue by gilessbrown** [pypa/warehouse#2185]
When I run `python setup.py sdist upload` I get an error message:

```
(wextracto) gsbrown$ python setup.py sdist upload
running sdist
running egg_info
writing requirements to Wextracto.egg-info/requires.txt
writing Wextracto.egg-info/PKG-INFO
writing top-level names to Wextracto.egg-info/top_level.txt
writing dependency_links to Wextracto.egg-info/dependency_links.txt
writing entry points to Wextracto.egg-info/entry_points.txt
reading manifest file 'Wextracto.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Wextracto.egg-info/SOURCES.txt'
running check
creating Wextracto-0.14.0
creating Wextracto-0.14.0/Wextracto.egg-info
creating Wextracto-0.14.0/wex
creating Wextracto-0.14.0/wex/js
copying files to Wextracto-0.14.0...
<lots of "copying ..." lines snipped>
Writing Wextracto-0.14.0/setup.cfg
Creating tar archive
removing 'Wextracto-0.14.0' (and everything under it)
running upload
Submitting dist/Wextracto-0.14.0.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Development Status :: 4 - Beta')' is not a valid choice for this field
error: Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Development Status :: 4 - Beta')' is not a valid choice for this field
```

That is with a tuple for classifiers as per:
https://github.com/eBay/wextracto/blob/cfa19d36c8054670987705cef172f7e84c1f934c/setup.py#L31

If I change from `(` to `[` (and the matching pair) to make it a list rather than a tuple it uploads successfully.

(Originally raised as pypa/pypi-legacy#670)

**Comment by bucknerns** [comment]
Same issue here thought the Intended Audience classifier was removed based on the error.  


Copying sshaolin.egg-info to build/bdist.linux-x86_64/wheel/sshaolin-0.0.5-py2.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/sshaolin-0.0.5.dist-info/WHEEL
running upload
Submitting /home/local/ANT/bucknath/code/sshaolin/dist/sshaolin-0.0.5-py2.py3-none-any.whl to https://upload.pypi.org/legacy/
Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Intended Audience :: Developers')' is not a valid choice for this field
error: Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Intended Audience :: Developers')' is not a valid choice for this field

**Comment by di** [comment]
This is a distutils problem. In Python 2.7.12, the upload works, but we get the 400-error from Warehouse:

```
Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Development Status :: 3 - Alpha')' is not a valid choice for this field
error: Upload failed (400): classifiers: 'FieldStorage('classifiers', 'Development Status :: 3 - Alpha')' is not a valid choice for this field
```

In Python 3.6.3, we don't even make it to Warehouse:
```
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    keywords='sample setuptools development',
  File "/private/tmp/sampleproject/env/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/Users/di/.pyenv/versions/3.6.3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/di/.pyenv/versions/3.6.3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/di/.pyenv/versions/3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/di/.pyenv/versions/3.6.3/lib/python3.6/distutils/command/upload.py", line 63, in run
    self.upload_file(command, pyversion, filename)
  File "/Users/di/.pyenv/versions/3.6.3/lib/python3.6/distutils/command/upload.py", line 161, in upload_file
    body.write(value)
TypeError: a bytes-like object is required, not 'str'
```

Folks having this issue have two options:
* Upload using [pypa/twine](https://github.com/pypa/twine) instead;
* Use a list instead of a tuple.

**Comment by gilessbrown** [comment]
Can you elaborate on why this is a distutils problem?  It seems to me that if you take client code that was previously working and then change the web service handling requests from that code to generate a 400 then the problem probably sits with the web service rather than the client code (I know this is a gray area).  In particular the message from the 400 is misleading.

**Comment by di** [comment]
Well, with Python 3.x, the request doesn't even get to us, so there doesn't seem to be anything we can do on the Warehouse end of things to fix this.

I suppose there might be a way to interpret the request differently when it has this issue, but to me it seems malformed. For example, if I have:

```
   classifiers=(
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: MIT License',
    ),
```

This is what we get in the request:
```
>>> request.POST.getall('classifiers')
[FieldStorage('classifiers', 'Development Status :: 3 - Alpha')]
```

Where somehow these are becoming the `disposition_options`:
```
>>> request.POST.getall('classifiers').disposition_options
{'name': 'classifiers', 'filename': 'Development Status :: 3 - Alpha'}
```

Whereas with a list:
```
>>> request.POST.getall('classifiers')
['Development Status :: 3 - Alpha', 'Intended Audience :: Developers', 'Topic :: Software Development :: Build Tools', 'License :: OSI Approved :: MIT License']
```

Granted, I am not a distutils/cgi/etc expert, and I can't point a distutils bug specifically, and I may be wrong, but after looking at this for a bit, this is the conclusion I came to.

>  In particular the message from the 400 is misleading.

I agree with this. We can definitely determine when this is happening, so I'll make a PR to give a more reasonable error message.
