### ISSUE TITLE
There doesn't seem to be a way to reset password

### ISSUE THREAD

**Issue by warsaw** [pypa/warehouse#2187]
Go to the login page https://pypi.org/account/login/

I'm pretty sure I have an account, but I don't remember my password (is it the same as on pypi.python.org?).  No matter, I'll just reset it.  But there is no password reset/recovery option on the login page.

**Comment by gsb-eng** [comment]
@warsaw There is a PR #1262 is under review.

**Comment by nlhkabu** [comment]
closing as duplicate of #1228

**Comment by ingenthr** [comment]
@gsb-eng or others, can you identify a workaround for this for now? is it email someone?
