### ISSUE TITLE
Replacing dots with dashes on pip install breaks installation

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2222]
From user feedback form.

The pip install command for packages with dots is transformed to dahes. These don't install. E.g., pip install `biocommons.seqrepo` works, but pip install `biocommons-seqrepo` does not.

![screenshot from 2017-07-22 11-24-27](https://user-images.githubusercontent.com/3323703/28490371-56ddd172-6ed0-11e7-8c8a-c57136514496.png)

**Comment by dstufft** [comment]
I'm not able to reproduce this, as it works fine for me. However I think I can see the argument that we should have ``pip install <foo>`` use the "real" name of the project as the author intended and not the normalized name.
