### ISSUE TITLE
Feedback from pypi feedback form: cannot update pythonhosted

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2224]
It looks like documentation on pythonhosted.org (e.g., https://pythonhosted.org/FireWorks) can no longer be updated through any means(!). I switched to RTD as suggested but need to update the old docs on pythonhosted.org to point to the new docs. Is there a way for me to do this?

**Comment by dstufft** [comment]
There is a button on legacy that allows people to delete their existing documentation. We don't currently have an option for redirecting. Either way, this is a duplicate of #582.
