### ISSUE TITLE
Add to FAQ: why no way to upload file manually

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2225]
Feedback from PyPI form: "Manual Upload URL not working"

> is it me or there's no way to upload packages manually ? this transition kind of sucks because the given link to do manual upload doesn't work (https://upload.pypi.org/legacy/)

**Comment by dstufft** [comment]
There is currently not a way to upload the file manually.

**Comment by di** [comment]
Fixing #2288 might make this more clear that this URL is not the place to do a manual upload.

**Comment by di** [comment]
Current UI:

<img width="879" alt="screen shot 2017-12-11 at 11 47 19 am" src="https://user-images.githubusercontent.com/294415/33845431-11da0d1c-de69-11e7-86b4-7432d525b06b.png">

**Comment by nlhkabu** [comment]
I think we perhaps need to add a question to the FAQ like "Where can I upload my package manually?" or "Why can't I upload my package manually" explaining this - and also pointing to the twine documentation.
