### ISSUE TITLE
PyPI reports that version does not exist -- even though it does

### ISSUE THREAD

**Issue by hobarrera** [pypa/warehouse#2228]
Earlier today, I pushed a new version of a package, but PyPI reports it's not there.
Even though the web UI shows it [[1](https://pypi.python.org/pypi/ocaclient/0.3.2)], [[2](https://pypi.org/project/ocaclient/)], I cant install it:

```
$ pip install ocaclient==0.3.2
Collecting ocaclient==0.3.2
  Could not find a version that satisfies the requirement ocaclient==0.3.2 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1)
No matching distribution found for ocaclient==0.3.2
```

Oddly, the [search results](https://pypi.org/search/?q=ocaclient) also show an outdated version.

**Comment by gtback** [comment]
For me, I'm getting the 0.3.2 version when I `pip install ocaclient`, and the latest version shows in search results. It's possible the indexing was just running a bit slowly.

**Comment by hobarrera** [comment]
Apparently so. Older versions had popped up a few days later. Sorry for the noise!
