### ISSUE TITLE
svgs rendering in black

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2237]
On some browsers the cube svgs are rendering in black:

![screenshot from 2017-07-25 21-18-30](https://user-images.githubusercontent.com/3323703/28591814-e76e76d2-717e-11e7-80e3-fb0dc646e3b0.png)

It should be:

![screenshot from 2017-07-25 21-18-50](https://user-images.githubusercontent.com/3323703/28591813-e7565426-717e-11e7-9d02-32b3d06b6e87.png)

I think this has got to do with the color encoding of the images

**Comment by nlhkabu** [comment]
can reproduce on firefox.  I confirm, it's an SVG issue, not a png issue.

**Comment by alexmuller** [comment]
I can also reproduce this in Firefox 54.

Interestingly though when the SVG is rendered in the browser on its own (outside the PyPI page), it looks identical in Firefox and Chrome:

![screenshot from 2017-08-06 10-07-11](https://user-images.githubusercontent.com/121219/29001965-1762d6f8-7a8f-11e7-8ec3-36168bd4b4e4.png)

![screenshot from 2017-08-06 10-07-25](https://user-images.githubusercontent.com/121219/29001967-1bcf7db8-7a8f-11e7-84a5-5aa1e1723486.png)

**Comment by alexmuller** [comment]
Wow, this took me a bit of time to figure out but was super interesting in the end.

I started off by creating a minimal SVG:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   width="100mm"
   height="100mm"
   viewBox="0 0 100 100"
   version="1.1">
      <path
         style="fill:#f00f00;"
         d="M 0,0 100,0 100,100 0,100 z" />
</svg>
```

I found out quite early on that moving the `fill` out of the inline style and using it as a `fill="#f00f00"` property solved the issue but I wasn't sure why.

I set up another local webserver to serve the SVG file and observed that my little webserver didn't have the problem when serving the image. The only differences between my webserver and warehouse were the HTTP headers, so I worked through them and found out that the `Content-Security-Policy` (CSP) header was causing the styles to not render.

I'm still not exactly sure what the original difference between Chrome and Firefox is, but I observe that behaviour too.

I'll submit a patch for this just now.

**Comment by nlhkabu** [comment]
Brilliant, thankyou @alexmuller :)
