### ISSUE TITLE
Mention PEP 527 on `Invalid file extension`

### ISSUE THREAD

**Issue by boppreh** [pypa/warehouse#2281]
[PEP 527](https://www.python.org/dev/peps/pep-0527/) forbids the upload of any sdist with extension other than `.tar.gz` or `.zip`. Warehouse rejects such uploads with the message `400 Invalid file extension.` ([implementation](https://github.com/pypa/warehouse/blob/2a99b6f8b0ffa66a13d52b493c756cecc8307be1/warehouse/forklift/legacy.py#L763), [test](https://github.com/pypa/warehouse/blob/57f70e977c979f0ca2a2fe640a9362eaf72898af/tests/unit/forklift/test_legacy.py#L904)).

I suggest adding more information to this message, preferably mentioning [PEP 527](https://www.python.org/dev/peps/pep-0527/) and that some older projects have been grandfathered for a temporary period. This prevents users from getting confused by the seemingly inconsistent behavior, and to distinguish between files rejected by PEP 527 and other cases.

**Comment by di** [comment]
Fixed in #2387.
