### ISSUE TITLE
Ignore duplicate files when uploading, instead of throwing error

### ISSUE THREAD

**Issue by rsyring** [pypa/warehouse#2284]
Original complaint: https://gist.github.com/boppreh/ac7522b3a4ac46b4f6010eecddc57f21

> Uploading distributions to https://upload.pypi.org/legacy/
> Uploading package-1.2.3.zip
> HTTPError: 400 Client Error: File already exists. for url: https://upload.pypi.org/legacy/
> 
> It's the exact same file. You could add a check for it and ignore, but no, it had to be an error.

And Donald's email reply on Distutils:

> > It's the exact same file. You could add a check for it and ignore, but no, it had to be an error.
> 
> This seems like a reasonable feature request, please file an issue with Warehouse asking for it so I don’t forget it.

**Comment by dstufft** [comment]
Just to be clear, this should only no-op on files with the exact same hash, if someone tries to upload a different file with the same name that should still get the error as it is today.

**Comment by dstufft** [comment]
Fixed in https://github.com/pypa/warehouse/pull/2419.
