### ISSUE TITLE
Link "pre-production" text in banner to explanation

### ISSUE THREAD

**Issue by rsyring** [pypa/warehouse#2287]
[Original concern](https://gist.github.com/boppreh/ac7522b3a4ac46b4f6010eecddc57f21) and Donald's reply:

> > The new website is "pre-production”.
> 
> This is mostly just a warning at this point that the UI might return funky results, some things might not be great yet, and to not start throwing the full force of people’s production traffic at it. The current hosting arrangement can’t handle the full amount of traffic we get from ``pip install …`` (but uploads are fine!) and we’re working on building on the new infrastructure with our future hosting arrangement that can handle the full production load.

IMO, it would help to link the "pre-production" text in the banner to a page on Warehouse that explains what about Warehouse is pre-production.

**Comment by di** [comment]
We also should add a section to the help page with said explanation.

**Comment by blackHatMonkey** [comment]
@di Where do you think would be the best place to add it?

**Comment by di** [comment]
@blackHatMonkey Somewhere on the [help page](https://github.com/pypa/warehouse/blob/master/warehouse/templates/pages/help.html) would be ideal.

**Comment by dstufft** [comment]
This is effectively done with the PR at https://github.com/pypa/warehouse/pull/2376, the only thing left is for me to edit the banner image.

**Comment by di** [comment]
This is unnecessary if we do #2518 first.
