### ISSUE TITLE
Upload URLs returning a 404 on `GET` is confusing

### ISSUE THREAD

**Issue by pbaranay** [pypa/warehouse#2288]
URLs like https://upload.pypi.org/legacy/ and https://test.pypi.org/legacy/ currently return a 404 error when accessed via `GET`. This led me to believe there was some issue with the new PyPI server (rather than the issue actually being that my `~/.pypirc` file was missing a trailing slash when specifying the test repo).

While you can't fix every problem that exists between the keyboard and chair, it would be great if PyPI returned a more informative response when accessing these URLs.

**Comment by di** [comment]
Agreed. These should probably show the same page you get when you visit `https://upload.pypi.org/`

**Comment by di** [comment]
Fixed in #2408.
