### ISSUE TITLE
Add answer to 'Who maintains PyPI and where and by whom is it hosted?' on help page

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2325]
https://www.reddit.com/r/Python/comments/6ug04h/who_maintains_pypi_and_where_and_by_whom_is_it/

**Comment by di** [comment]
These paragraphs might be a good answer:

> Warehouse is an open source project developed under the umbrella of the Python Packaging Authority (PyPA) and supported by the Python Packaging Working Group (PackagingWG).
>
> The PyPA is an independent group of developers whose goal is to improve and maintain many of the core projects related to Python packaging.
>
> The PackagingWG is a working group of the Python Software Foundation (PSF) whose goal is to raise and disburse funds to support the ongoing improvement of Python packaging.

**Comment by robodair** [comment]
Submitted a PR 👍 

I'm pretty sure hosting is on Fastly/GCP - But if I'm wrong please correct me!
