### ISSUE TITLE
Invalid file extension error when uploading bdist_wininst files

### ISSUE THREAD

**Issue by pkittenis** [pypa/warehouse#2327]
Using twine, uploading an .exe file built on windows via `python setup.py bdist_wininst` fails with

```
twine upload ssh2-python-0.5.3rc2.win32-py2.7.exe 
Uploading distributions to https://upload.pypi.org/legacy/
Uploading ssh2-python-0.5.3rc2.win32-py2.7.exe
HTTPError: 400 Client Error: Invalid file extension. for url: https://upload.pypi.org/legacy/                                                         
```

```
twine --version
twine version 1.9.1 (pkginfo: 1.4.1, requests: 2.18.4, setuptools: 36.2.7,
requests-toolbelt: 0.8.0, tqdm: 4.15.0)
```

Bdist built with the following versions:

```
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
Collecting setuptools
  Downloading setuptools-36.2.7-py2.py3-none-any.whl (477kB)
Collecting twine
  Downloading twine-1.9.1-py2.py3-none-any.whl
```

Looking at the code, it does accept .exe files but only [if filetype is `bdist_wininst`](https://github.com/pypa/warehouse/blob/master/warehouse/forklift/legacy.py#L502).

This .exe was built by `bdist_wininst`, see [appveyor build log here](https://ci.appveyor.com/project/pkittenis/ssh2-python/build/job/55v8xnw486t04755), so I am not sure what the issue is.

I'd be keen to do a PR if someone can point me to what needs changing. 

This may well be setuptools issue instead if there's something missing in the .exe to identify it as a `bdist_wininst` filetype.

**Comment by di** [comment]
The `bdist_wininst` format is no longer a valid format, see [PEP 527 -- Removing Un(der)used file types/extensions on PyPI](https://www.python.org/dev/peps/pep-0527/).

Warehouse will [reject files ending in the `.exe` extension](https://github.com/pypa/warehouse/blob/2a99b6f8b0ffa66a13d52b493c756cecc8307be1/warehouse/forklift/legacy.py#L762-L764) unless your project was [grandfathered in in this migration](https://github.com/pypa/warehouse/blob/b0a9719c25e8e6483bd33ea9b5948d8b84932f64/warehouse/migrations/versions/f404a67e0370_disable_legacy_file_types_unless_a_.py) by already having releases using the legacy file types.

**Comment by pkittenis** [comment]
Thanks for the references 👍
