### ISSUE TITLE
install_requires  not work?

### ISSUE THREAD

**Issue by icecooly** [pypa/warehouse#2332]
install_requires=['python-docx', 'pymysql']

pip install Mysql2docx error

requires will not auto install?

**Comment by di** [comment]
Hi @icecooly. This is the repository for the code which powers https://pypi.org/. In the future, you may want to look for help in the following places:

* for issues with `pip`: https://github.com/pypa/pip
* for issues with `setuptools`: https://github.com/pypa/setuptools

I took a quick look at your `setup.py` and it looks like you have the line `import Mysql2docx` before you call `setup()`. This is making your `setup.py` try to import `docx` before it can be installed. You can safely remove this line from your `setup.py`.

In addition, it looks like your distribution is missing the `README.md` file that it's attempting to use for your `long_description`. 

If you fix these two issues, your package should be installable. You can test this at any time locally by running `python setup.py install`.

**Comment by icecooly** [comment]
thank you very much
