### ISSUE TITLE
twine upload to pypi with --skip-existing not working

### ISSUE THREAD

**Issue by lwanger** [pypa/warehouse#2337]
I am unable to upload a universal wheel to the pypi server. When I do so I get the message:

$ twine upload --skip-existing dist/cooked_input-0.2.5-py2.py3-none-any.whl
Uploading distributions to https://upload.pypi.org/legacy/
  Skipping cooked_input-0.2.5-py2.py3-none-any.whl because it appears to already exist

I can upload if I bump up the version number and release a new distribution.

My ~/.pypirc is (password blotted out for obvious reasons):

[distutils]
index-servers=
    pypi
    testpypi

[pypi]
username = lwanger
password = ********

[testpypi]
repository = https://test.pypi.org/legacy/
username = lwanger
password = ********

My twine version is:

$ twine --version
twine version 1.9.1 (pkginfo: 1.4.1, requests: 2.18.4, setuptools: 36.2.7,
requests-toolbelt: 0.8.0, tqdm: 4.15.0)

I am running Python 3.6.1 on Windows 10

**Comment by di** [comment]
Hi @lwanger, it appears that the distribution `cooked_input-0.2.5-py2.py3-none-any.whl` already exists here: https://pypi.org/project/cooked-input/0.2.5/#files, therefore PyPI will not let you re-upload it. See https://github.com/pypa/packaging-problems/issues/74.

By adding the `--skip-existing` flag to the `twine` command, you are telling `twine` to not fail if a given distribution already exists on PyPI.

**Comment by di** [comment]
I'm going to close this as it doesn't seem to be an issue with Warehouse, but please feel free to comment here if you have additional questions.
