### ISSUE TITLE
Cannot Update My Packages

### ISSUE THREAD

**Issue by Miserlou** [pypa/warehouse#2342]
I've logged into the new system to try to update one of my packages. It shows that I am logged in and that these are my packages, but there is no menu or interface to administer them. What's happening here?

**Comment by Miserlou** [comment]
Even worse, while updating through the legacy site I get a `I/O error (send request)` error, and from setup.py, I get `error: Upload failed (410): Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)` 

This is a small nightmare.

**Comment by Miserlou** [comment]
Can anybody explain to me what's happening with these issues? I need to update a package that a lot of people depend on and right now I can't.

**Comment by di** [comment]
> I've logged into the new system to try to update one of my packages. It shows that I am logged in and that these are my packages, but there is no menu or interface to administer them. What's happening here?

The index at https://pypi.org/ is a pre-production deployment of Warehouse. Work on making Warehouse have feature-parity with the legacy index is currently in progress, and thus it is essentially view-only, so any "administrative" edits still need to be done through the legacy index here: https://pypi.python.org/

> Even worse, while updating through the legacy site I get a `I/O error (send request)` error

I'm assuming here you mean the index at https://pypi.python.org/. I'm not as familiar with the legacy code base, the right place to report a specific issue with it is here: https://github.com/pypa/pypi-legacy

> and from setup.py, I get error: `Upload failed (410): Gone`

I'm not exactly sure what command you ran to produce this, but I'm guessing it was `python setup.py upload`. You should take a look at the links the error messages provide, which describe that uploading to the legacy API (powered by `pypi-legacy`) has been sunsetted, and you should migrate to using the new API (powered by `warehouse`):

* How to migrate to the new API: https://packaging.python.org/guides/migrating-to-pypi-org/#uploading
* More information about the sunset: https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html

**Comment by dstufft** [comment]
I'm going to close this issue as it seems to simply be a case of confusion, and there doesn't seem to be anything more actionable on it beyond what @di has already mentioned.
