### ISSUE TITLE
Pagination for releases on Project Admin doesn't work

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#2378]
The pagination on releases does not appear to be functional in the project admin. It shows the first N releases, but when you click to see all, there is no pagination links and there is no text to indicate what page you're on or how many results there are.

Manually adding a ``?page=2`` *does* work, so this is likely just something wrong in the template.

**Comment by ewdurbin** [comment]
@clgarciga hi!

**Comment by ewdurbin** [comment]
references #2374
