### ISSUE TITLE
IPlantUML 0.0.5 can't be installed

### ISSUE THREAD

**Issue by budebulai** [pypa/warehouse#2381]
Errors occured when pip install iplantuml.
### Error 1: TypeError
C:\Users\Administrator>pip install iplantuml
Collecting iplantuml
  Using cached IPlantUML-0.0.5.tar.gz
Building wheels for collected packages: iplantuml
....
....
File "c:\users\admini~1\appdata\local\temp\pip-build-fw7jij\iplantuml\setup.py", line 79, in initialize_options
      super().initialize_options()
  TypeError: super() takes at least 1 argument (0 given)

### Error 2: no such option "--jarpath"
C:\Users\Administrator>pip install iplantuml --jarpath ./plantuml.jar

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --jarpath

**Comment by di** [comment]
Hi @budebulai, it seems like you found that https://github.com/jbn/IPlantUML is the appropriate place to ask for support with this package, so I'm going to close this report as it doesn't seem to be an issue with Warehouse.
