### ISSUE TITLE
Rendering bug: content from all project tabs is displayed

### ISSUE THREAD

**Issue by alex** [pypa/warehouse#2390]
![](https://screenshots.firefoxusercontent.com/images/eccf4bd3-f8a4-4052-ad74-a35402826e76.png)

As you can see, from the root of the project, the releases are visible, if the screenshot extended further, the files would also be visible.

Previously, the UI had these in seperate "tabs".

**Comment by di** [comment]
Seems like the issue is that the javascript bundle referenced by that page (https://pypi.org/static/js/warehouse.3b55beb2.js)  is 404-ing, that's why the login links on the top are missing as well.

**Comment by di** [comment]
I purged the cache for this page and the issue was resolved. Seems like the actual issue is why the cache was out of date.

@alex Have you seen this on any other project pages?

**Comment by alex** [comment]
Also seeing it on https://pypi.org/project/wheel/

A cache purge fixed it. Going to close this.
