### ISSUE TITLE
GPG Short IDs are vulnerable to collision attacks

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#24]
As @alex mentioned in #23 the GPG Short IDs used by PyPI are vulnerable to collision attacks. Once we strangle out PyPI's legacy code we should update it to use long ids or full fingerprints.

**Comment by dstufft** [comment]
Better idea: GPG sucks and we're just not going to support it and we're going to pretend it doesn't exist. TUF is the way of the future for us.

**Comment by alex** [comment]
TRUE STORY
