### ISSUE TITLE
Increase size limit for Tensorflow related package

### ISSUE THREAD

**Issue by av8ramit** [pypa/warehouse#2467]
Hi @dstufft, I'm an engineer on TensorFlow. I was wondering if it would be possible to get a size increase for the following packages on upload.pypi.org/legacy/ and test.pypi.org/legacy/?

tf-nightly 100MB
tf-nightly-gpu 200MB

Thanks!

**Comment by dstufft** [comment]
I'll try to get to this later today.

**Comment by dstufft** [comment]
This is done on regular PyPI now, it wasn't registered on TestPyPI.
