### ISSUE TITLE
Cannot Upload Large Files

### ISSUE THREAD

**Issue by Miserlou** [pypa/warehouse#2483]
How am I supposed to upload large packages? Where is this limit documented?

```
(env)~/Projects/lambda-packages $ twine upload dist/lambda_packages-0.17*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading lambda_packages-0.17.0-py2-none-any.whl
HTTPError: 400 Client Error: File too large. for url: https://upload.pypi.org/legacy/
```
This error or similar happens if I use any of: `repository: https://pypi.python.org/pypi`, `repository: https://upload.pypi.org/legacy/`, or no entry for `repository`.

Currently, I am unable to update the [lambda-packages](https://github.com/Miserlou/lambda-packages) project because of this undocumented limitation, which is extremely annoying to my users and myself.

The wheel is 129M, the tarball is 69M. This doesn't seem unreasonably large.

Related: 
https://github.com/pypa/warehouse/issues/2342
https://github.com/Miserlou/lambda-packages/issues/61

**Comment by di** [comment]
@Miserlou I've increased the limit for `lambda_packages` to 200MB.

I've also created #2486 to make the error message more clear.

**Comment by Miserlou** [comment]
Thanks very much!

**Comment by menshikh-iv** [comment]
I received the same error when I uploading a new release of [gensim](https://pypi.python.org/pypi/gensim/3.0.1), can you increase limits for gensim too (size of `tar.gz` is `62 MB`)

**Comment by menshikh-iv** [comment]
@di I received the same error when I uploading a new release of [gensim](https://pypi.python.org/pypi/gensim/3.0.1), can you increase limits for gensim too (size of `tar.gz` is `62 MB`)

**Comment by di** [comment]
@menshikh-iv I've increased the limit for `gensim` to 80MB.

For anyone visiting this issue in the future, please create a new issue if you need to request a limit increase.
