### ISSUE TITLE
File size limit error message should include size of the limit

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2486]
Since we don't document the file size limit for uploads anywhere, it'd be nice if the error message when an upload is over the limit includes what the limit is, especially considering that the limits might be different for various projects.

Currently the message is something like:

```
HTTPError: 400 Client Error: File too large. for url: https://upload.pypi.org/legacy/
```

It'd be nice if this was something like:

```
HTTPError: 400 Client Error: File too large (limit for <project_name> is <limit>) for url: https://upload.pypi.org/legacy/
```

**Comment by brainwane** [comment]
In our [meeting today](https://wiki.python.org/psf/PackagingWG/2017-12-19-Warehouse) we decided this belongs in [the first milestone, the MVP for package maintainers](https://github.com/pypa/warehouse/milestone/8).

@Miserlou is working on implementing it in #2487.

**Comment by di** [comment]
I closed #2487, so this issue is still open and available for someone else to pick up as their first contribution.

**Comment by pradyunsg** [comment]
@di 

https://github.com/pypa/warehouse/blob/d12b7c1ff792942b6ba8c91793e4fa6e1f1cf137/warehouse/forklift/legacy.py#L878

It's just the matter of formatting the project name and file size limit from local variables here into the message; correct?

**Comment by di** [comment]
@pradyunsg Yep! Something like:

> File is too large. Limit for project 'foobar' is 60MB.
