### ISSUE TITLE
Alpine Linux segfaults in dev environment

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2523]
Since #2474, I am having an issue in local dev in which `hupper` reloads or crashes on every request, with either something like:
```
Killing server with PID 7.
Starting monitor for PID 25.
```
or:
```
Server with PID 43 exited with code -11.
```
I bisected to determine that this is in fact due to a change in #2474, and it specifically seems like the cause is the switch to `python:3.6.2-alpine3.6`, because changing the base image back to `python:3.6.1-slim` resolves the problem.

~I poked around with `hupper` a bit, and it seems like the cause is that something is writing to the worker's pipe on every request with no value, and thus `self.worker.pipe.recv` is `None` and this triggers a reload for `hupper`. It also doesn't seem to be coming from `hupper` itself.~

I also tried upgrading to `python:3.6.3-alpine3.6` (we should probably do this anyways since it was missed in #2508), but the problem remains.

@dstufft, are you able to reproduce this? My next steps are going to try to minimally reproduce this to share the issue with the `hupper` devs, unless you have any insight.

**Comment by dstufft** [comment]
I have no idea!

**Comment by dstufft** [comment]
I will try to reproduce though.

**Comment by yeraydiazdiaz** [comment]
I'm getting as similar`Server with PID 10 exited with code -11.` on master, Mac OSX Sierra.

**Comment by yeraydiazdiaz** [comment]
Possibly related to the switch to Alpine, when trying to debug this I ran `docker-compose up -d` and hit the home page but `web` service seemed to stop responding. Running `docker-compose up web` showed:

```
web_1            | 2017-10-21T15:00:31+0000 [-] Site starting on 8000
web_1            | 2017-10-21T15:00:31+0000 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site object at 0x7fe3dbdb5dd8>
web_1            | 2017-10-21T15:00:31+0000 [twisted.application.runner._runner.Runner#info] Starting reactor...
web_1            | 2017-10-21T15:00:36+0000 [twisted.python.log#info] "172.22.0.1" - - [21/Oct/2017:15:00:36 +0000] "GET / HTTP/1.1" 200 3009 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0"
.... more requests ...
web_1            | 2017-10-21T15:00:38+0000 [twisted.python.log#info] "172.22.0.1" - - [21/Oct/2017:15:00:38 +0000] "GET /_includes/flash-messages/ HTTP/1.1" 200 4 "http://localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0"
warehouse_web_1 exited with code 139
```

Googling a bit I found [this issue in Pillow](https://github.com/python-pillow/Pillow/issues/1935) which points to Alpine causing segfaults in different projects.

I tried [the suggestion of increasing threading stack size](https://github.com/python-pillow/Pillow/issues/1935#issuecomment-317206056) simply adding:

```
import threading
threading.stack_size(4*80*1024)
```

to `wsgi.py` and it worked fine and also helped with the error `make serve` was throwing.

Worth a try @di?

**Comment by di** [comment]
@yeraydiazdiaz Nice find! Yup, that definitely fixes it.

**Comment by di** [comment]
It seems like this issue in general is due to musl libc having a much smaller stack size than glibc, and some libraries not expecting it to be so small. In this particular case, the segfault is coming from `msgpack-python` when it tries to unpack the session data.

@dstufft, is there any reason why we needed to switch to alpine? Or could we go back to a debian-based image?

**Comment by dstufft** [comment]
We can go back to a Debian based image, I used Alpine because it's smaller and it's package manager makes it easier to remove build dependencies.
