### ISSUE TITLE
My Project does not appear on my user page

### ISSUE THREAD

**Issue by oharaandrew314** [pypa/warehouse#2526]
Hi there,

On [the test Warehouse PyPi](https://test.pypi.org/project/serverless-config/) and [the legacy PyPi](https://pypi.python.org/pypi/serverless-config/0.2.1), my project correctly appears on my corresponding user profiles.  However, it does not on appear on my user profile on [Warehouse PyPi](https://pypi.org/project/serverless-config/), despity my profile being marked as a maintainer.

**Comment by di** [comment]
Hi @oharaandrew314, looking at https://pypi.org/user/ohara.andrew314/ I can see the `serverless-config` package. It seems like since the project was just recently created, the cache for your user page needed to catch up.

**Comment by oharaandrew314** [comment]
Makes sense.  I guess the prod version has a much more aggressive caching policy.  Or I just got lucky.  Thanks for the info.
