### ISSUE TITLE
/simple index pages should be cachable

### ISSUE THREAD

**Issue by cyounkins** [pypa/warehouse#2546]
Pages such as https://pypi.org/simple/numpy/ send an Age header, which is usually much longer than max-age. This causes browsers and Squid to deem the item uncachable due to formula used in https://tools.ietf.org/html/rfc7234#section-4.2.3 , `corrected_initial_age = max(apparent_age, corrected_age_value);` where `corrected_age_value` is roughly the Age header.

It'd be great to make these index pages cachable, and can be done by simply dropping the Age header. I suspect this is what was intended to start with.

IRC:
```
[22:43] <cyounkins> PyPi /simple/ interface appears to send an Age header which is greater than Cache-Control: max-age. Browsers nor Squid will cache it. I think Varnish is misconfigured. Any idea who to contact?
[23:12] <dstufft> cyounkins: Varnish isn't misconfigured, it's just configured to cache it for longer than downstream because we have control over those caches and can ~instantly purge them
[23:18] <cyounkins> dstufft: So you intend to have zero caching downstream of varnish despite the max-age header?
[23:18] <cyounkins> intend -> desire
[23:21] <cyounkins> It's fine for varnish to cache it from the origin for longer than you want anything downstream to cache it, but as configured there is no caching available. A 5-10 min client cache would be lovely and could be done by simply dropping the Age header.
[23:31] <dstufft> cyounkins: mmm, Okay I see what you mean. I was thinking you meant that the fact Varnish was caching for much longer was the misconfiguration, open an issue on github.com/pypa/warehouse
[23:32] <cyounkins> You got it!
[23:32] <dstufft> this is unlikely to get fixed in legacy PyPI (pypi.python.org) but we can get it fixed in the new PyPI (pypi.org) which will hopefully start to serve production traffic in the next few months
[23:33] <dstufft> We should probably just remove the Age header completely like you suggested, or move it to a debug header x-varnish-age or something
```

@dstufft

**Comment by brainwane** [comment]
Thanks for your bug report, @cyounkins, and sorry for the slow response!

Update on the new PyPI, in case you didn't see the news: The folks working on Warehouse have gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- the most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable.

I've verified that my request just now for `https://pypi.org/simple/numpy/` caused a response with the header `Age: 12614`.

Since the effect of this issue on caching will be most noticeable when we flip that switch, I've moved it to that [milestone](https://github.com/pypa/warehouse/milestone/1).

Thanks and sorry again for the wait.

**Comment by brainwane** [comment]
In [yesterday's Warehouse core developers' meeting](https://wiki.python.org/psf/PackagingWG/2018-03-06-Warehouse) we decided to pare down our near-future milestones on [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) so they really only contain the essential bugfixes and features we need to launch, replace legacy PyPI, and shut down the old site. So, I'm moving this issue into a milestone further in the future; sorry for the wait.

**Comment by cyounkins** [comment]
Hello! It looks like `pypi.org` is being served by nginx but I don't see that in the architectural overview. Is that configuration codified somewhere I could look at the Age header configuration?

**Comment by dstufft** [comment]
Uh, I think the Nginx is part of the kubernetes load balancer. The age header comes from Varnish though. Should be able to strip that header in our VCL at https://github.com/python/pypi-infra/blob/449736ca74e914745eb0182cbed3b135c6136378/terraform/warehouse/vcl/main.vcl#L285-L287, where you can see an example of removing the ``Via`` header.

I don't remember the context around this other than the Age header was causing some kind of problem and I see I suggested removing it. If there's a better way to handle it, than removing it, can do that too.

**Comment by cyounkins** [comment]
See https://book.varnish-software.com/3.0/HTTP.html#age

> Consider what happens if you let Varnish cache content for a week, because you can easily invalidate the cache Varnish keeps. If you do not change the Age-header, Varnish will happily inform clients that the content is, for example, two days old, and that the maximum age should be no more than fifteen minutes.

> Browsers will obey this. They will use the reply, but they will also realize that it has exceeded its max-age, so they will not cache it. 

The Phabricator project has seen this issue too: https://phabricator.wikimedia.org/T184534

I can get a PR up no problem, but I want to make sure it's clear: This will allow browsers and other clients to obey `max-age` where they have not been. `https://pypi.org/simple/numpy/` has `max-age` set to `600` = 10 mins. This seems reasonable to me, but if elsewhere you have very high `max-age` it could result in unintended caching.

Upstream of varnish is the nodejs application, right?

**Comment by dstufft** [comment]
Yea, that's the intent we had here, I didn't realize at the time browsers were going to look at, or care at all about the ``Age`` header.

Upstream of Varnish is this Python application.

**Comment by dstufft** [comment]
The fix for this is deployed now. Please confirm and let us know if it's not working as expected, but a quick scan looks like it works to me.

**Comment by cyounkins** [comment]
Looks great, thank you! I hope it lessens your server load a bit.
