### ISSUE TITLE
Can't receive confirmation email

### ISSUE THREAD

**Issue by hubertokf** [pypa/warehouse#2592]
I registered at https://pypi.python.org but never received the confirmation email.

I've tried to request a password reset and no email again. Then I tried to create another account with another gmail email and everything went fine.

What am I missing?

**Comment by di** [comment]
Hi @hubertokf, this is the repository for the next-generation package index. If you're still having issues receiving email, I'd recommend you open an issue over at https://github.com/pypa/pypi-legacy.
