### ISSUE TITLE
pip install gets wrong version

### ISSUE THREAD

**Issue by nottrobin** [pypa/warehouse#2608]
I published version `1.0.5` of `canonicalwebteam.yaml-redirects`, and the new version successfully shows both [on pypi.org](https://pypi.org/project/canonicalwebteam.yaml-redirects/1.0.5/) and [on pypi.python.org](https://pypi.python.org/pypi/canonicalwebteam.yaml-redirects/1.0.5), and `pip search` finds the latest version:

``` bash
$ pip search canonicalwebteam.yaml-redirects | grep canonicalwebteam.yaml-redirects
canonicalwebteam.yaml-redirects (1.0.5)      - A simple redirects utility that uses a YAML file for redirects definitions
```

But `pip install` gets version `1.0.3`:

``` bash
$ pip install canonicalwebteam.yaml-redirects --no-cache-dir
Collecting canonicalwebteam.yaml-redirects
  Downloading canonicalwebteam.yaml-redirects-1.0.3.tar.gz
Operation cancelled by user
$ pip install canonicalwebteam.yaml-redirects==1.0.5 --no-cache-dir
Collecting canonicalwebteam.yaml-redirects==1.0.5
  Could not find a version that satisfies the requirement canonicalwebteam.yaml-redirects==1.0.5 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3)
No matching distribution found for canonicalwebteam.yaml-redirects==1.0.5
```

From inspecting with `pip install -v -v -v`, I can see it's querying this URL to try to find the version to install, which indeed only lists up to 1.0.3:
https://pypi.python.org/simple/canonicalwebteam-yaml-redirects/

It's been this way for about 15 hours at this point.

**Comment by pradyunsg** [comment]
Interesting...

https://pypi.org/simple/canonicalwebteam-yaml-redirects/ does show the newer releases.
https://pypi.python.org/simple/canonicalwebteam-yaml-redirects/ doesn't the newer releases.

It seems to be something Warehouse is doing right but the legacy-pypi isn't. :/

**Comment by pradyunsg** [comment]
Maybe it's the cache being outdated. Try running:

```
curl -X PURGE https://pypi.python.org/pypi/canonicalwebteam-yaml-redirects/ 
```

 (from pypi-legacy's README)

**Comment by nottrobin** [comment]
@pradyunsg alas that didn't help

**Comment by nottrobin** [comment]
I discovered that:

``` python
pip install canonicalwebteam.yaml-redirects --no-cache-dir --index-url https://pypi.org/simple
```

Gets the correct version. But that presumably won't be much help for most people trying to install requirements with a basic `pip install -r requirements.txt` command.

**Comment by pradyunsg** [comment]
I ran `curl -X PURGE https://pypi.python.org/simple/canonicalwebteam-yaml-redirects/ `.

That seems to have fixed it. :)

**Comment by nottrobin** [comment]
@pradyunsg OMG thank you! I don't know why it didn't seem to work for me. But I don't care, it's fixed now :) :) :)

**Comment by di** [comment]
I noticed the same thing yesterday with a newly published package, and purging the cache for the simple page also fixed it. It's probably worth opening an issue over at https://github.com/pypa/pypi-legacy
