### ISSUE TITLE
Project Description layout inconsistency

### ISSUE THREAD

**Issue by Carreau** [pypa/warehouse#2612]
If there are code blocks in your project description, the layout of the first code block is different because of a `:first-child` rule in `_project_description.scss` line 24 that say the display to `inline-block`. Here is a Gif showing what removing this rule does.

![first-child](https://user-images.githubusercontent.com/335567/33230172-cd6adba2-d1de-11e7-9a45-09c485153f90.gif)

**Comment by nlhkabu** [comment]
It appears as though this code has been refactored since this issue was open - there is no longer any `inline-block` style applied.  I'm going to close this on the assumption that this bug no longer exists, but please reopen if I have missed something!

**Comment by di** [comment]
Yes, looking at https://pypi.org/project/cffi_magic/ this seems fixed.
