### ISSUE TITLE
Expected release date for warehouse

### ISSUE THREAD

**Issue by hnykda** [pypa/warehouse#2613]
Hi,

the project has been over two years under development, leaving stalling pypi behind...

I am not able to find out when the switch should finally occur. Is it even planned? Is there some official roadmap? Doesn't this project lack some proper planning? 

It's a pity, because it seems to be really close to what is needed and in the same time, no one contributes to Pypi... I have seen projects such like this, which had been years "one step from production", but were shutdown before they could actually get there, because they were already obsolete...

There is surprisingly little information about the whole project as well. A lot of expectation over 3 years ago, but not a lot of recent stuff. It would be devastating if this die.

Thanks.

**Comment by pradyunsg** [comment]
Hi @hnykda!

Warehouse is already under use. All of the PyPI project uploads happen through Warehouse's API. Further, you'll want to take a look at https://github.com/pypa/warehouse/milestones.

If you want to see this happen faster, I suggest helping out with the remaining issues. :)

**Comment by hnykda** [comment]
Thanks for the answer, it's positive then :+1: .

**Comment by di** [comment]
@hnykda You might be interested in this recent blog post about this project -- it doesn't provide a release date, but it does explain some of your questions: http://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html
