### ISSUE TITLE
Uploading ~650MB to PyPI

### ISSUE THREAD

**Issue by matcross** [pypa/warehouse#2623]
Hi everyone,

This is more of a discussion than a direct 'Issue'. Please let me know if there's a better forum to use.

I'm working on a set of Python interfaces to the NAG Library (which is approx. 1800 mathematical and statistical routines).

We are focusing on usability so are very keen on letting the package be hosted on PyPI.

The package ships with the NAG runtime library and a number of dependent Intel runtimes as well.

We are supporting 64-bit Linux, Mac, and 64-bit Windows. The sizes of the zips are 210MB / 259MB / 181MB respectively.

We would like to supply the whole package in single platform-specific 'blobs' like this for convenience to the user, instead of forcing them to have to assemble together the Python source and binaries from separate downloads. (We tried that in the past and it wasn't too popular.)

I anticipate that we would probably delete older versions of the package when a bug-fix increment is made. Functionality releases might appear two or three times a year. Although it would subvert the utility of package management a little, we could potentially always overwrite the package when a new version becomes available. We could distribute older versions on request directly if a user gets in touch with us.

One another minor complication is that we usually provide two variants for each platform - one enabled with Intel MKL and one without. The latter is only requested in occasional circumstances, so we could also leave its distribution directly up to the NAG website.

I haven't yet set up a page for the package (which is called 'naginterfaces') nor tried anything with the PyPI test system. I hope to get round to that in the next few weeks. I just wanted to test the water first.

Any comments or thoughts you have will be gladly received.

**Comment by dstufft** [comment]
In general we have a file size limit of ~60MB per file, but that's really just a basic sanity check and we have the capability to bump that limit up to whatever is needed on a per project basis. I don't think we've ever denied anyone a request for a larger limit and we generally take the view point that if there is a legitimate use case for some limit to be raised we don't want to force people to do contortions to manage their own project.

It's not entirely clear to me, but are the blobs you're talking about wheel files? If so there should be no issue, you just need to get the name you want registered on PyPI (you can upload an empty sdist at version 0 and then delete that release, but not the project itself) and then ask for a limit increase for your project (the limit is per file) and then you're good to go. You don't need to delete old releases. We're using over a TB of storage at this point, and that is growing rapidly (see https://twitter.com/dstufft/status/925081822358310913) so one project isn't likely to affect the overall usage much.

The only thing we really ask is to just be mindful, of ways you can structure things to be more optimized. If there's some huge data file that never changes, maybe putting that in it's own package that your packages depend on for instance. At the end of the day though, if your project needs the space it needs the space and we want to do whatever we can to accommodate that.

As far as variants go, we don't really have a mechanism for that in the packaging ecosystem yet, but one method I've seen some scientific packages use is to have two packages, ``foo`` and ``foo-mkl`` and people can depend on whichever one matches their platform's capabilities. Another strategy is to include the bits for both the generic and the MKL enhanced versions and have your library dynamically choose which one to import based upon what is available on the system.

**Comment by matcross** [comment]
Thanks for the comments (and generally for being so accommodating).

Yes, I was meaning wheels in the first instance.

I'll follow up with my colleagues here. We might consider totally self-hosting (under the assumption that it shouldn't be too onerous for our users to specify an extra URL to pip), which could also fit better with password-protected delivery that we use in some circumstances.

I'm happy to close this in the meantime, and I'll be back in touch if needed.

Cheers
Mat
