### ISSUE TITLE
User page splits long surname without hyphen

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#2631]
In Chrome and in Firefox on Debian, when I visit my user page https://pypi.org/user/brainwane/ (logged in or logged out), my surname is split onto two lines, without a hyphen.

![pypi-name-screenshot](https://user-images.githubusercontent.com/842790/33415521-33b71b12-d565-11e7-8ad9-7e820d46b483.png)

**Comment by nlhkabu** [comment]
This UI has been updated to use a smaller font size with ellipsis:

![screenshot from 2018-01-31 20-56-12](https://user-images.githubusercontent.com/3323703/35647041-38dcf842-06c9-11e8-8630-016122f81f3e.png)

This design allows for an 18 character unbroken name, before it concatenates.  I hope that this covers the vast majority of people.  Let's reopen if it doesn't !
