### ISSUE TITLE
Additional milestones prior to the Legacy PyPI redirect

### ISSUE THREAD

**Issue by ncoghlan** [pypa/warehouse#2632]
Prompted by @brainwane, this is an issue to discuss some additional milestones prior to https://github.com/pypa/warehouse/milestone/1

I'm thinking we should have at least one such milestone:  "Remove the 'pre-production' banner from pypi.org" (that's currently just a single issue: https://github.com/pypa/warehouse/issues/2518)

Then reaching that milestone can be used to drive additional community testing before we implicitly redirect all traffic from pypi.python.org, as well as advertise legacy.pypi.org as the new stable link for anyone that *really* needs to access the old service for some reason.

**Comment by brainwane** [comment]
@ewdurbin, @dstufft and I will be looking at this in the next few days, figuring out any additional early milestones. (cc @lgh2)

**Comment by brainwane** [comment]
@ncoghlan As you [may have seen in email](https://mail.python.org/pipermail/distutils-sig/2017-December/031803.html) we've now added [a few more milestones](https://github.com/pypa/warehouse/milestones) - I'm going to close this issue as resolved, but am fine with it being reopened if people want to suggest further milestone additions.
