### ISSUE TITLE
getting error when doing "make initdb" step

### ISSUE THREAD

**Issue by wardcomm** [pypa/warehouse#2636]
CREATE DATABASE
xz -d -k dev/example.sql.xz
xz: dev/example.sql.xz: No such file or directory
make: *** [initdb] Error 1

**Comment by di** [comment]
Hi @wardcomm, does [this file](https://github.com/pypa/warehouse/blob/master/dev/example.sql.xz) not exist in your cloned repo?

**Comment by wardcomm** [comment]
i had renamed /dev/example.sql.xz to somethink else and installed these
  ls
  npm install
  yum install curl sudo
  curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
  yum install -y nodejs
  yum install -y gcc-c++ make -y
   npm install
==============================
then i ran "make initdb" from warehouse folder and have the db running and website is working.
so you can close ticket
