### ISSUE TITLE
getting error withe website runing "elasticsearch.exceptions.ConnectionError"

### ISSUE THREAD

**Issue by wardcomm** [pypa/warehouse#2637]
error on webpage when click on http://xxx.xxx.xxx.xxx/search/
=======================================================
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f6f9e88c908>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f6f9e88c908>: Failed to establish a new connection: [Errno 111] Connection refused

**Comment by di** [comment]
Is the elasticsearch container running? `docker-compose ps | grep elastic`

What are the logs from that container? `docker-compose logs elasticsearch`

**Comment by di** [comment]
Hi @wardcomm, I'm going to close this assuming you were able to get this running, but feel free to comment here if you have further problems.
