### ISSUE TITLE
Ability to add new classifiers.

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2649]
On the admin side of things, we need a simple way to add new classifiers.

**Comment by brainwane** [comment]
In our [meeting today](https://wiki.python.org/psf/PackagingWG/2018-02-12-Warehouse) Ernest said that this is something he would like in the admin UI before launch.

**Comment by brainwane** [comment]
@lgh2 is about to start working on this.

**Comment by brainwane** [comment]
In IRC conversation we found out Dustin had already started working on this, so now it's on his plate. :)
