### ISSUE TITLE
Role maintenance for package owners

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2654]
Owners need to be able to add "Maintainer"/"Owner" roles to the packages they own.

Legacy:
<img width="878" alt="screen shot 2017-12-08 at 11 45 57 am" src="https://user-images.githubusercontent.com/294415/33778215-6745c8bc-dc0d-11e7-9c14-5ee69c49547c.png">

**Comment by ehthiede** [comment]
I had this issue today, actually: spent several minutes thinking I was blind before I realized I had to go back to the old website to update roles.

Until this is fixed, could we get something added to the "Common Questions" redirecting people to pypi.python.org ?

**Comment by di** [comment]
Hi @ehthiede, sorry that happened to you!

We have https://github.com/pypa/warehouse/issues/2659 already which should capture this. Additionally, we're planning to ship this milestone in the upcoming weeks, so this specific issue shouldn't be missing for much longer.

**Comment by ehthiede** [comment]
@di Not a problem!  Just felt really stupid for a bit.  Thanks for the prompt update!

-Erik

**Comment by nlhkabu** [comment]
@di could you please create an empty template for this and I will add the HTML/CSS?  then you can hook it up to the back end?

Would that work for you? Thx

**Comment by di** [comment]
@nlhkabu Going to push a branch which is functional but totally unstyled for this today actually, it should be easy to hand off to you for finishing touches.

**Comment by nlhkabu** [comment]
hi @di - I have some time to work on this - is the branch ready? Thx

**Comment by di** [comment]
@nlhkabu Sorry for the delay, the branch is here: https://github.com/pypa/warehouse/tree/role-management

**Comment by sambrightman** [comment]
Are changes from PyPI already intended to propagate to Warehouse? Somebody has transferred ownership to me and it does not show up on Warehouse.

**Comment by di** [comment]
@sambrightman Yes, although Warehouse is heavily cached and any changes from https://pypi.python.org may take a little while to appear on https://pypi.org.

Which project is not showing the change?

**Comment by di** [comment]
@sambrightman Sounds about right.

This ticket was closed because #2705 was merged. Coincidentally, you should now be able to administer project roles from https://pypi.org directly. Any changes made there should appear immediately.
