### ISSUE TITLE
README.rst is not correctly rendered

### ISSUE THREAD

**Issue by paternal** [pypa/warehouse#2656]
I am not sure whether this is a warehouse bug or a [readme_renderer](http://github.com/pypa/readme_renderer) one.

My [README.rst](https://framagit.org/spalax/papersize/blob/2d4fd7f7e9e768d4f09b04e463de3270323a0c2e/README.rst) file [is not rendered](http://pypi.org/project/papersize) on pypi.org. However, although  [readme_renderer](http://github.com/pypa/readme_renderer) is described as "[rendering] long_description/README files in Warehouse", it does not find any error in my file:

~~~sh
$ python setup.py check --restructuredtext
running check
~~~

Now, I have no idea how to debug this…

Additional notes:

- I am using python 3.5.4 (on Debian testing) with an up-to-date version of readme_renderer (version 17.2);
- [restructured-lint](https://pypi.org/project/restructuredtext_lint/) does not see any error either.

-- Louis

**Comment by di** [comment]
Hi @paternal,

When I run a check on your repo, here's the output I get:

```
$ python setup.py check --restructuredtext
running check
warning: Check: :2: (WARNING/2) Title underline too short.

warning: Check:

warning: Check: papersize 📏 Paper size related tools

warning: Check: ====================================

warning: Check: Invalid markup which will not be rendered on PyPI.
```

**Comment by paternal** [comment]
Thanks! I eventually found the problem: it works (`readme_renderer` finds an error in my README.rst) with python2.7 and python3.6, but it does not with python3.5. I reported an issue to `readme_renderer`: pypa/readme_renderer#57

Sorry for the noise,
-- Louis

**Comment by di** [comment]
No worries, thanks for filing that issue!
