### ISSUE TITLE
Warehouse login page missing password reset

### ISSUE THREAD

**Issue by lgh2** [pypa/warehouse#2660]
I noticed that there doesn't appear to be a password reset button on the [Login](https://pypi.org/account/login/) page for Warehouse.  Do you think we should add one, so users can automatically recover their passwords if they forget them?

**Comment by ewdurbin** [comment]
Open PR: https://github.com/pypa/warehouse/pull/1262
Existing Issue: https://github.com/pypa/warehouse/issues/1228

@lgh2 is there something this issue intends to capture that the above issue and PR do not?

**Comment by lgh2** [comment]
I'm sorry Ernest, I didn't see the other issue.
