### ISSUE TITLE
Better error messages when metadata does not validate

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2668]
Currently, if a kwarg in `setup.py` does not pass validation, the response from Warehouse is not really descriptive enough to indicate what the issue is.

For example, if one has an invalid `url`:
```
    url='foobar',
```

The response looks like:
```
HTTPError: 400 Client Error: home_page: Invalid URI for url: http://pypi.org/legacy/
```

This message is confusing because:

* it refers to both `home_page` and `url`
  * the former of which is what the actual metadata field is called (but even still it's `Home-Page` in the specifications
  * the latter of which is what setuptools calls it;
* the error message from twine includes the repo url, but the issue is with the kwarg value (`foobar`)

A better error message might be something like:
```
HTTPError: 400 Client Error: "foobar" is an invalid value for field "Home-Page",
see https://packaging.python.org/specifications/core-metadata/
```

But the ambiguity between `url` and `home-page` remains.

**Comment by alanbato** [comment]
Where is this validation taking place? After some searching I couldn't find the place where the error was being generated. Closes thing I found was this snippet in `forklift/legacy.py`
``` python
if not form.validate():
    for field_name in _error_message_order:
        if field_name in form.errors:
            break
    else:
        field_name = sorted(form.errors.keys())[0]

    raise _exc_with_message(
        HTTPBadRequest,
        "{field}: {msgs[0]}".format(
            field=field_name,
            msgs=form.errors[field_name],
        ),
    )
```

**Comment by di** [comment]
@alanbato Great question. It's a bit confusing, only a part of the error message that comes from Warehouse is what's bolded below:

> HTTPError: 400 Client Error: **home_page: Invalid URI** for url: http://pypi.org/legacy/

You've correctly found where the `home_page: <message>` bit comes from. The "Invalid URI" message comes from the form validation here: https://github.com/pypa/warehouse/blob/2a99b6f8b0ffa66a13d52b493c756cecc8307be1/warehouse/forms.py#L34

**Comment by di** [comment]
Another instance of this occurring to a user here: https://github.com/pypa/twine/issues/289
