### ISSUE TITLE
Flaskify

### ISSUE THREAD

**Issue by sharoonthomas** [pypa/warehouse#267]
Use flask for warehouse.

- [ ] Create main application and use wsgi app from flask application to run warehouse
- [ ] Create blueprints for accounts, legacy, migrations, packaging, search
- [ ] add more...

**Comment by dstufft** [comment]
I'm going to close this, I've started porting Warehouse over to Pyramid to ease the concerns of the custom framework-ish thing I've got going on here. That work is now on the master branch inside this repository. Since we've gone to Pyramid we'll not be converting to Flask.
