### ISSUE TITLE
Deleting Package Completely on pypi warehouse

### ISSUE THREAD

**Issue by tbhaxor** [pypa/warehouse#2670]
I have created a package named `pynimations` on *pypi.org* and also it was uploaded to *pypi.pyton.org*. For this i used _twine upload dist/*_

Unfortunately I have submitted the wrong download URL. So I deleted the whole project :disappointed: on *pypi.python.org*

Now when I am trying to upload the fixed version i am encountered with this error
```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading pynimations-0.2.0.tar.gz
[================================] 5901/5901 - 00:00:07
HTTPError: 400 Client Error: File already exists. for url: https://upload.pypi.org/legacy/

```
I
ps: I am new to pypi

**Comment by ewdurbin** [comment]
@tbhaxor it looks like you figured out the issue, uploading a `.zip` rather than a `.tar.gz` file.

**Comment by tbhaxor** [comment]
@ewdurbin actually i uploaded a package with .tar.gz which contains some bug so i tried to upload the package with same archive format on pypi with `twine upload dist/` for which an error occured which says that file already exists so i used .zip

**Comment by ewdurbin** [comment]
@tbhaxor PyPI does not allow for a filename to be reused, even once a project has been deleted and recreated, so what you experienced is the expected outcome. Sorry for any confusion.
