### ISSUE TITLE
Add readiness notification/link to localhost:80 to `make serve` logs

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#2673]
After a developer runs `make serve`, eventually the process seems to hang; that's when the application's ready for you to view it at localhost:80, but that's not obvious unless you know (see also #2672 which adds a note to the docs to tell you what to look for). The logs say:

~~~
web_1            | 2017-12-13T21:52:01+0000 [-] Site starting on 8000
web_1            | 2017-12-13T21:52:01+0000 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site object at 0x7fbb6dcc4240>
web_1            | 2017-12-13T21:52:01+0000 [twisted.application.runner._runner.Runner#info] Starting reactor...
~~~

which doesn't mention `localhost`, implies port 8000 which doesn't let you see the site, and doesn't provide a clickable link.

@lgh2 suggested we add some message to stdout when it starts the server and it's ready for the developer to view it, like "starting server on http://localhost:80". Is this possible?

**Comment by brainwane** [comment]
From `#pypa-dev` just now:

`<mbacchi>` sumanah: not sure it will be easy or desirable to make the web worker say 'ready...' but worth opening a ticket anyway
`<mbacchi>` the messages you're seeing are all the logs aggregated from the docker compose nodes
`<lghampton>` Why would it not be desirable?
`<sumanah>` mbacchi: are you thinking it might be misleading to tell the dev it's ready?
`<di_codes>` i agree with mbacchi that it’s likely not easy. there isn’t really a great way to determine when all the containers are “ready”
`<mbacchi>` you'd have to make the server process output a ready message but is that just on startup or other operations? I'd suggest that the docs should indicate what to watch for rather than the logs/application spitting out some specific message because over time the ready message will be scrolled up in the history
`<sumanah>` mbacchi: di_codes: I'm fine with us not specifically saying "ok now it's go time!" if we put more explicit "here's what to look for" in the docs, and especially if we provide a clickable link to localhost:80 somewhere nearby in the terminal output
`<sumanah>` https://zulip.readthedocs.io/en/latest/development/setup-vagrant.html#step-3-start-the-development-environment is what I'll probably want to pattern after -- "You will see several lines of output starting with something like:" and "And ending with something similar to:" and then "Now the Zulip server should be running and accessible. Verify this by navigating to http://localhost:9991/ in the browser on your main machine."
`<di_codes>` sumanah: agreed, that is probably the best option
`<sumanah>` di_codes: ahh, the web container might be ready somewhat asynchronously with other necessary containers? 
`<di_codes>` sumanah: yeah, that’s the other problem. usually for me it’s the static container that comes up last

**Comment by brainwane** [comment]
I helped run a [Warehouse sprint night](https://www.meetup.com/nycpython/events/249722192/) last week and ran into this issue; multiple people were just waiting for some signal that `make serve` had completed and was ready. I know it's hard to actually properly trigger some notification at the moment we're ready to serve, but maybe ~5 minutes after a particular process starts, it can run a check and then put a notification in the logs if localhost is ready to view in the browser?  cc @di

**Comment by di** [comment]
I tried a couple things to solve this, but wasn't really pleased with any of them.

I think the best option is still to add a note about what to expect when everything is up and running, like:

> The `make serve` command will eventually stop producing output (but will remain running), and http://localhost:80/ will resolve
