### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by bhack** [pypa/warehouse#2683]
Can you add an Helm Chart to deploy this on kubernetes?

**Comment by ewdurbin** [comment]
@bhack Warehouse is not intended to be run outside of the PSF infrastructure at this time.

We're working on setting up a Kubernetes deployment for warehouse over at https://github.com/python/pypi-infra right now and intend to use helm to manage the manifests.

Note that we do not plan to create a supported helm chart for deploying Warehouse elsewhere as it is not intended to act as a private index.
