### ISSUE TITLE
Fix metadata pytest 3.3.0 and 3.3.1 packages

### ISSUE THREAD

**Issue by nicoddemus** [pypa/warehouse#2700]
Hi, this is a follow up of pytest-dev/pytest#2966, but I will provide a summary below because that thread is quite big. 😅 

Summary follows:

pytest 3.3 dropped support for Python 2.6 and Python 3.3.

To make the transition easier, we added a `python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*',` to our [`setup.py`](https://github.com/pytest-dev/pytest/blob/master/setup.py#L86), so Python 2.6 and 3.3 users doing a `pip install pytest` would still install a compatible version (`3.2.X`).

The problem is that the [metadata required](https://pypi.python.org/simple/pytest/) (use "view source" in your browser) was never uploaded to PyPI due to a bug in the `devpi push` command (devpi/devpi#480), which we use as part of our release process.

This has caused problems for users which still use Python 2.6 or 3.3, because `pip install pytest` will attempt to install `pytest-3.3.X` which no longer supports those versions.

The missing metadata happened in `pytest 3.3.0` and `3.3.1`, until we finally figured out the problem.

Releasing `pytest 3.3.2` with the correct metadata and removing `pytest 3.3.0` and `3.3.1` is one option, but we feel it will then disrupt users which have pinned `pytest` to those versions and are using supported Python versions, further adding to the confusion.

There's one solution that we deem would be ideal (proposed by @jaraco): is to see with you guys if it would be possible to fix the metadata of `pytest 3.3.0` and `3.3.1` directly in the database. Is that a possibility? Would that cause another consequences we are not foreseeing?

**Comment by ewdurbin** [comment]
@nicoddemus if you release a version of pytest (3.3.2 I assume) which includes the `requires_python` you'd like ported back to `3.3.0` and `3.3.1` I can help you out, I'd rather copy the column from your new release than try to hack it in myself :)

**Comment by RonnyPfannschmidt** [comment]
@ewdurbin if i recall correctly we have the same entry in a recent py release, i'll verify in a while

**Comment by ewdurbin** [comment]
@RonnyPfannschmidt not seeing any!

```
=> select name, version, packagetype, requires_python from release_files where name='pytest' and version LIKE '3.3%';
-[ RECORD 1 ]---+------------
name            | pytest
version         | 3.3.0
packagetype     | bdist_wheel
requires_python | 
-[ RECORD 2 ]---+------------
name            | pytest
version         | 3.3.0
packagetype     | sdist
requires_python | 
-[ RECORD 3 ]---+------------
name            | pytest
version         | 3.3.1
packagetype     | bdist_wheel
requires_python | 
-[ RECORD 4 ]---+------------
name            | pytest
version         | 3.3.1
packagetype     | sdist
requires_python | 

```

**Comment by RonnyPfannschmidt** [comment]
@ewdurbin i meant pylib, not pytest, - is that db accessible?

**Comment by nicoddemus** [comment]
Ronny meant the "py" library, not pytest :)

Em dom, 24 de dez de 2017 13:31, Ernest W. Durbin III <
notifications@github.com> escreveu:

**Comment by ewdurbin** [comment]
Sorry I should have been more specific.

The release is to validate admin access and intent, not just for the string in question.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i propose we see to releasing 3.3.2 quickly and then request assistance of @ewdurbin

**Comment by nicoddemus** [comment]
Agreed, I will see to it after the holidays!

Em dom, 24 de dez de 2017 17:58, Ronny Pfannschmidt <
notifications@github.com> escreveu:

**Comment by fschulze** [comment]
@ewdurbin I don't know much of the PyPI internals, but I'm not sure if just adding a field in the db violates the PyPI changelog API. If the ``register`` functionality would still be around, that would have been the way to fix this. You might want to do the same it did. Basically check if a serial number of the db will be necessary or not.

Thanks for the help on this!

**Comment by nicoddemus** [comment]
@ewdurbin I just released 3.3.2 and it does have the correct metadata:

```html
<a href="https://files.pythonhosted.org/packages/38/af/8dcf688d192914928393f931b7b550f2530299bbb08018b2f17efa6aab73/pytest-3.3.2-py2.py3-none-any.whl#sha256=b84878865558194630c6147f44bdaef27222a9f153bbd4a08908b16bf285e0b1" data-requires-python="&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*">pytest-3.3.2-py2.py3-none-any.whl</a><br>
<a href="https://files.pythonhosted.org/packages/d0/00/2546e70b2cc1d3df4e736a43871dfde54855277446cec376f871e36f7e03/pytest-3.3.2.tar.gz#sha256=53548280ede7818f4dc2ad96608b9f08ae2cc2ca3874f2ceb6f97e3583f25bc4" data-requires-python="&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*">pytest-3.3.2.tar.gz</a><br>
```

We would be grateful if you could update `3.3.0` and `3.3.1` to have the same `python_requires`! 👍

**Comment by ewdurbin** [comment]
@nicoddemus thanks, confirmed and looks great. I've been thinking but don't know the _correct_ way to address the very valid and correct concern @fschulze raises. this is on my TODOs.

**Comment by ewdurbin** [comment]
Tested with one of my packages on Test PyPI

```sql
BEGIN;

UPDATE release_files
SET requires_python=(SELECT requires_python
                     FROM release_files
                     WHERE name='clandestined'
                       AND version='6.1.7'
                       AND packagetype='sdist')
WHERE name='clandestined'
  AND version IN ('6.1.5', '6.1.4');

INSERT INTO journals
  (name, version, action, submitted_by, submitted_from)
VALUES
  ('clandestined', '6.1.5', 'update requires_python', 'EWDurbin', '162.243.84.248'),
  ('clandestined', '6.1.4', 'update requires_python', 'EWDurbin', '162.243.84.248');

COMMIT;
```

resulted in

```python
>>> import xmlrpc.client as xmlrpclib
>>> client = xmlrpclib.ServerProxy('https://testpypi.python.org/pypi')
>>> pprint(client.changelog_since_serial(client.changelog_last_serial()-2))
[['clandestined', '6.1.5', 1515112234, 'update requires_python', 340154],
 ['clandestined', '6.1.4', 1515112234, 'update requires_python', 340155]]
```


So, proposed sql statement:

```sql

BEGIN;

UPDATE release_files
SET requires_python=(SELECT requires_python
                     FROM release_files
                     WHERE name='pytest'
                       AND version='3.3.2'
                       AND packagetype='sdist')
WHERE name='clandestined'
  AND version IN ('3.3.0', '3.3.1');

INSERT INTO journals
  (name, version, action, submitted_by, submitted_from)
VALUES
  ('pytest', '3.3.0', 'update requires_python', 'ewdurbin', '162.243.84.248'),
  ('pytest', '3.3.1', 'update requires_python', 'ewdurbin', '162.243.84.248');

COMMIT;

```

**NOTE** I'm not going to futz with _any_ caches so all of this will take 24 hours or so to become real after the statement is executed.

**Comment by ewdurbin** [comment]
@fschulze those journal entries are what pypi would have written back when this stuff was user editable... and what I believe mirrors would be looking for.

**Comment by fschulze** [comment]
@ewdurbin I just wanted to point to the potential issue and it seems like you researched it now. Since I don't know the internals, I trust that this is the way to go. Thanks!

I still think this is a general issue for warehouse though. One other use case is updating the readme, homepage url and similar things without making another release, for example when a project changes it's name

**Comment by ewdurbin** [comment]
@fschulze issues of that nature have been (and are continuing to be) discussed in #2170. Though I thank you for pointing out the changelog issue here.

**Comment by ewdurbin** [comment]
this is done!

```sql
=> select * from journals where submitted_by ilike 'ewdurbin' order by submitted_date desc limit 2;
   id    |  name  | version |         action         |       submitted_date       | submitted_by | submitted_from 
---------+--------+---------+------------------------+----------------------------+--------------+----------------
 3464315 | pytest | 3.3.1   | update requires_python | 2018-01-05 10:44:45.249703 | ewdurbin     | 162.243.84.248
 3464314 | pytest | 3.3.0   | update requires_python | 2018-01-05 10:44:45.249703 | ewdurbin     | 162.243.84.248
(2 rows)

=> select name, version, packagetype, requires_python from release_files where name='pytest' and version LIKE '3.3.%';
  name  | version | packagetype |              requires_python              
--------+---------+-------------+-------------------------------------------
 pytest | 3.3.0   | bdist_wheel | >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
 pytest | 3.3.0   | sdist       | >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
 pytest | 3.3.1   | bdist_wheel | >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
 pytest | 3.3.1   | sdist       | >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
 pytest | 3.3.2   | bdist_wheel | >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
 pytest | 3.3.2   | sdist       | >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
(6 rows)
```

**Comment by nicoddemus** [comment]
@ewdurbin thanks, awesome! I don't see the `data-requires-python` tag for `3.3.0` and `3.3.1` on the [simple index](https://pypi.org/simple/pytest/) yet though. Does it take some time to catch up with the changes?

**Comment by ewdurbin** [comment]
looks good from here @nicoddemus... caches are weird.

```shell
ewd3imac:~ ewdurbin$ curl -s https://pypi.python.org/simple/pytest/ | grep data-req
<a data-requires-python="&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*" href="../../packages/22/06/483d4c1a081bd29586f50572dfbcfc9c78b6269841e3aa706fc37418769e/pytest-3.3.1-py2.py3-none-any.whl#md5=a2a9f7e16edb834d31e4b0e80e64c7f2" rel="internal">pytest-3.3.1-py2.py3-none-any.whl</a><br/>
<a data-requires-python="&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*" href="../../packages/38/af/8dcf688d192914928393f931b7b550f2530299bbb08018b2f17efa6aab73/pytest-3.3.2-py2.py3-none-any.whl#md5=5f7a1be1015c59c6242edf0af4075314" rel="internal">pytest-3.3.2-py2.py3-none-any.whl</a><br/>
<a data-requires-python="&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*" href="../../packages/41/6f/ed63db45ad82db405c77c807d75d66311d385e1b6bf476ec46bde0c9462a/pytest-3.3.0.tar.gz#md5=98a34c3e039192cccaf5df758b084c25" rel="internal">pytest-3.3.0.tar.gz</a><br/>
<a data-requires-python="&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*" href="../../packages/98/ec/3e5ca93027bcf88451afb5924a566e790e5e393d6de734b03044d0826176/pytest-3.3.0-py2.py3-none-any.whl#md5=334ee86af89c9811462b1b39bc2bfbca" rel="internal">pytest-3.3.0-py2.py3-none-any.whl</a><br/>
<a data-requires-python="&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*" href="../../packages/d0/00/2546e70b2cc1d3df4e736a43871dfde54855277446cec376f871e36f7e03/pytest-3.3.2.tar.gz#md5=c3757fbdfebd5d8f402fdd5fc1dcb9b5" rel="internal">pytest-3.3.2.tar.gz</a><br/>
<a data-requires-python="&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*" href="../../packages/fb/ee/ceb80b45e768e67ee848dfd4fc407a4ccfc6d93c904c49fad1e5495a079f/pytest-3.3.1.tar.gz#md5=6c056c2c41dfd2a0766682b942abf39c" rel="internal">pytest-3.3.1.tar.gz</a><br/>
```

**Comment by nicoddemus** [comment]
Oops I was looking at pypi.org instead of pypi.python.org... now I see the metadata as well. Sorry for the noise and thanks again! 😁

**Comment by marscher** [comment]
It would be great, if PyPI users would have an option in the interface to change Requires-Python.

Background: Python2 is dead (long live Python-2) and several projects dropped support for it in recent versions. But lots of projects did not declare requires_python in their metadata. This leads to the situation, that python2 users will try to install recent versions, for which support has been dropped.
The only solution I see on my side, is to hack the requires Requires-Python string into PKG-INFO and re-upload the source archive for every release supporting only Python3 under a different name. This approach seems error-prone and requires lots of care and time.

If you do not intend to integrate such a feature (which I can totally understand), I'd be delighted, if somebody with super-sql-rights (@ewdurbin) could update the python-require string for jpype1 (https://github.com/jpype-project/jpype, https://pypi.org/manage/project/jpype1/releases/ ) to ">=3.5, <4" for all releases <0.7.1

Thank you very much!

**Comment by ewdurbin** [comment]
I caught an enormous amount of shit for doing this, and will not perform such interventions.

**Comment by hugovk** [comment]
An option is for those projects to yank all the Py3-only releases that are _missing_ `python_requires>=3`.

Then pip on Python 2 will skip over those Py3-only releases with `python_requires>=3`, will skip over the yanked ones, and settle on the last Python 2 release.

https://pypi.org/help/#yanked

Better yet, it's probably time to pin every dependency to last-known Py2 versions, they're unlikely to change much.

(Even better, upgrade to Python 3 :)

**Comment by Thrameos** [comment]
I think that was what @marscher experimented with and couldn't get working.   The ability to edit ``python_requires`` without a fresh upload seems like a good option to have not just for Python 2.7 (packages riding dead snakes), but also for future compatibility issues.  After all we are all guessing what version something won't work on in the future ``<4`` but often we discover only later that there is a bug which prevents working.  For example when Python 3.9 was released we discovered there was a bug such that 1.0.x to 1.2.1 would not work.   If someone tries to use a package that was say pinned to "JPype==1.1" then they will get a segfault in Python 3.9 on.   Going back and changing the sdists to prevent would be one option.   We could also backport the fix and rerelease all the patch releases, but that will also take time to do.  

Second question... If ``python_requires`` is good practice is there a warning when uploading packages that it is missing?   Most (all?) current packages should be going in Python 3 only at this point but I could easily see the ``python_requires`` line getting missed. 

The reason this came up is packages that use "unmaintained" packages (such as boilerplate and duckling) have unpinned specifications and are thus grabbing the latest versions while running in py2.  We didn't properly mark our releases starting from the py3 transition.  As we don't have any control of these packages these unmaintained or slow transition packages are creating issues for anyone that tries to use those old py2 only packages.   Though I would happy see everything that is not py3 moved to an archival server until such time as maintainers get their software up to date, we are trying to be good citizens (and at the same time cut down the number of times I see issues caused by people trying to use dead packages.)

**Comment by marscher** [comment]
> I caught an enormous amount of shit for doing this, and will not perform such interventions.

Sorry to hear that. That's exactly why updating such metadata should be an option. Is database replication such a big deal these days anyways?
