### ISSUE TITLE
pytz.timezone in get_localzone() from tzlocal returns empty string

### ISSUE THREAD

**Issue by syracine** [pypa/warehouse#2707]
Hello,

I'm completely new in Python. I install Burp-ui backup software from pip on Debian 8 server running python 2.7.9. When I type the following command in shell, I get the following exception:
```
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tzlocal import get_localzone
>>> tz=get_localzone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python2.7/dist-packages/tzlocal/unix.py", line 70, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/lib/python2.7/dist-packages/pytz/__init__.py", line 191, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: ''
```
My server is located in Quebec, Canada. I install pytz and tzlocal from pip. Do I miss something or is it a bug? I tried it with pytz 2017.3 and tzlocal 1.4. I upgraded to 1.5.1 and the bug appeared again.

Regards

Sylvain Racine

**Comment by di** [comment]
Hi @syracine, this is the issue tracker for the service which powers https://pypi.org/.

You probably want to raise this issue in the `tzlocal` issue tracker here instead: https://github.com/regebro/tzlocal/issues

**Comment by syracine** [comment]
Sorry!
