### ISSUE TITLE
Add documentation for admin logins in dev

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2713]
It would be useful to document:

- Dev Username and password to login at `http://localhost/admin/login/`
- Dev username and password to login at `http://localhost/account/login/`

Maybe we should set up a generic username and password for dev purposes?

e.g.

"username": "username"
"password": "password"

**Comment by ewdurbin** [comment]
perhaps a dedicated `admin` user for test rather than having to use an existing PyPI admin's username.

**Comment by brainwane** [comment]
We discussed this in [today's bug triage meeting](https://wiki.python.org/psf/PackagingWG/2018-01-29-Warehouse).

This should be addressed as part of or while addressing the issue on updating the development database, #2216. It's a developer experience bug. It's already documented but kinda buried [in our development docs](https://warehouse.pypa.io/development/getting-started/?highlight=password#what-did-we-just-do-and-what-is-happening-behind-the-scenes). If I understand correctly, Ernest will talk with Donald and add instructions for logging in into the developer docs.

**Comment by di** [comment]
I put @ewdurbin's comment on #2216 so this issue should be just documentation-only.
