### ISSUE TITLE
Description fails to render on the "latest" page but works on specific version

### ISSUE THREAD

**Issue by axnsan12** [pypa/warehouse#2717]
Description is rendered fine here:
https://pypi.org/project/drf-yasg/1.1.2/

but fails to render on the "latest" page here, even though the latest version is the same as the one above
https://pypi.org/project/drf-yasg/

**Comment by ewdurbin** [comment]
The unrendered readme was cached in the CDN. It's not clear how it got there but it has been cleared and is rendering completely now.

**Comment by axnsan12** [comment]
Was it cleared automatically or manually?

I'm asking because it's not the first time I noticed this happening, so it might be worth investigating further.

**Comment by ewdurbin** [comment]
It was cleared manually via a purge of that page.

I'll file an issue for the problem at large rather than for a specific package.

**Comment by ewdurbin** [comment]
@axnsan12 It's often difficult to determine what's going on with bad renders. Most often I've seen those issues resolved by fixing the `long_description` itself, and haven't seen warehouse doing the wrong thing until this issue.

we'll track in #2718 and prioritize this if it begins to rear its head on a more regular basis.

**Comment by axnsan12** [comment]
Got it 👍 will ping if I catch it again.
