### ISSUE TITLE
ERROR: Service 'web' failed to build: when I run `make build`

### ISSUE THREAD

**Issue by iq8al** [pypa/warehouse#2722]
I'm trying to learn more about the project and followed the instructions on https://warehouse.readthedocs.io/development/getting-started/

On an Ubuntu Xenial AWS machine, I downloaded and installed the docker engine, and under my py3 virtualenv I installed docker composer via pip.

After checking out warehouse, when I run `make build`, it ended with the error like so:

```
npm info lifecycle tar-fs@1.16.0~install: tar-fs@1.16.0
npm info lifecycle prebuild-install@2.4.1~install: prebuild-install@2.4.1
npm info lifecycle iltorb@2.0.3~install: iltorb@2.0.3

> iltorb@2.0.3 install /opt/warehouse/src/node_modules/iltorb
> detect-libc prebuild-install || node-gyp rebuild

ERROR: Service 'web' failed to build: The command '/bin/sh -c set -x     && npm install -g gulp-cli     && npm install' returned a non-zero code: 1
Makefile:83: recipe for target 'build' failed
make: *** [build] Error 1
```
The error happens even after running `make build` multiple times. Is there something I'm missing here?

**Comment by ewdurbin** [comment]
@iq8al no idea! i was able to bring up the project in a clean docker environment (little bomb option in docker for Mac), testing after completely reseting my local copy `git clean -fxd`.

the `detect-libc` thing is a little alarming as your images should be building from the same images as everyone else.

can you paste the output of `docker history warehouse_web` for us?

```
ewd3imac:warehouse ewdurbin$ docker history warehouse_web
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
f5dffdb5ed56        4 minutes ago       /bin/sh -c #(nop) COPY dir:a0ad52156e5d71c...   3.61MB              
8c5150ced76c        4 minutes ago       /bin/sh -c #(nop) COPY dir:1da77264ece61ce...   151MB               
74f6fdbab3d4        4 minutes ago       /bin/sh -c #(nop) COPY dir:c46a8c0b4c72005...   3.8MB               
f61e35294b2c        4 minutes ago       |1 DEVEL=no /bin/sh -c set -x     && apt-g...   40.3MB              
4089c4eba639        4 minutes ago       |1 DEVEL=no /bin/sh -c set -x     && mkdir...   0B                  
dce46bbd6661        4 minutes ago       /bin/sh -c #(nop)  ARG DEVEL=no                 0B                  
48a8d4c5df13        4 minutes ago       /bin/sh -c #(nop) WORKDIR /opt/warehouse/src/   0B                  
b919bd3e244d        4 minutes ago       /bin/sh -c #(nop)  ENV PATH=/opt/warehouse...   0B                  
7d34bdea0baf        4 minutes ago       /bin/sh -c #(nop)  ENV PYTHONPATH=/opt/war...   0B                  
3bfdb6556678        4 minutes ago       /bin/sh -c #(nop)  ENV PYTHONUNBUFFERED=1       0B                  
971a5d5dad01        3 weeks ago         /bin/sh -c #(nop)  CMD ["python3"]              0B                  
<missing>           3 weeks ago         /bin/sh -c set -ex;   apt-get update;  apt...   6.46MB              
<missing>           3 weeks ago         /bin/sh -c #(nop)  ENV PYTHON_PIP_VERSION=...   0B                  
<missing>           3 weeks ago         /bin/sh -c cd /usr/local/bin  && ln -s idl...   32B                 
<missing>           3 weeks ago         /bin/sh -c set -ex  && buildDeps="   dpkg-...   66.8MB              
<missing>           3 weeks ago         /bin/sh -c #(nop)  ENV PYTHON_VERSION=3.6.3     0B                  
<missing>           3 weeks ago         /bin/sh -c #(nop)  ENV GPG_KEY=0D96DF4D411...   0B                  
<missing>           3 weeks ago         /bin/sh -c apt-get update && apt-get insta...   8.4MB               
<missing>           3 weeks ago         /bin/sh -c #(nop)  ENV LANG=C.UTF-8             0B                  
<missing>           3 weeks ago         /bin/sh -c #(nop)  ENV PATH=/usr/local/bin...   0B                  
<missing>           3 weeks ago         /bin/sh -c #(nop)  CMD ["bash"]                 0B                  
<missing>           3 weeks ago         /bin/sh -c #(nop) ADD file:f30a8b5b7cdc9ba...   55.3MB    
```

**Comment by iq8al** [comment]
@ewdurbin Thanks for the response.

Here you go:
```
$ docker history warehouse_web
Error response from daemon: No such image: warehouse_web:latest
```
And if it's of any help, these are what I have:
```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 

$ docker -v
Docker version 17.12.0-ce, build c97c6d6

$ pip show docker-compose
Name: docker-compose
Version: 1.18.0
Summary: Multi-container orchestration for Docker
Home-page: https://www.docker.com/
Author: Docker, Inc.
Author-email: UNKNOWN
License: Apache License 2.0
Location: /home/iqbal/py3/lib/python3.5/site-packages
Requires: PyYAML, docker, requests, websocket-client, cached-property, dockerpty, jsonschema, docopt, six, texttable
```

**Comment by ewdurbin** [comment]
Anyone with a Linux host able to reproduce?

**Comment by ewdurbin** [comment]
@iq8al when I get a chance I might try spinning up a similar AWS instance and giving it a shot, but that's not quite how the development environment is meant to be run. (not saying we won't help you)

**Comment by iq8al** [comment]
Thanks @ewdurbin 
I don't have anything else other than an Ubuntu laptop, so I was planning to play around with the project on an AWS Ubuntu host, or a vagrant Xenial client on my laptop.

**Comment by ewdurbin** [comment]
@iq8al not saying Amazon is to blame, but I'd be curious if you have issues on your local machine. the libc thing is kinda ?! and seems suspect. perhaps there's some bizarro c toolchain hackery on the aws box.

**Comment by iq8al** [comment]
@ewdurbin Unfortunately I experienced the same error on my local Xenial machine (running on Virtualbox using vagrant), with exactly the same versions of what I have on the AWS instance.

**Comment by di** [comment]
@iq8al Do you by chance have a `node_modules` folder in your `warehouse` repo? Did you happen to run `npm install` manually? I _think_ I've seen this before when the containers are attempting to use binaries built for the host OS and not the service, but I could be wrong.

Also if you are still experiencing this and can include a gist of everything that gets output after `make serve` it might be helpful.

**Comment by iq8al** [comment]
@di No, I do not see any `node_modules` folder in the source directory which I ran `make build`

And I've also attached the whole output of `make serve`. For the meantime, I'll take time to understand better how Docker works together with the project, and try to find an environment that can work for myself.

[log.txt](https://github.com/pypa/warehouse/files/1609378/log.txt)

**Comment by di** [comment]
Thanks @iq8al. In your log I'm seeing:

```
npm info using node@v6.11.1
```

Which made me notice that in #2652 I forgot to update the node version in the `Dockerfile`. I fixed this in #2743, could you try pulling the latest changes and trying again?

**Comment by iq8al** [comment]
Thank @di and @brainwane 
I'm not sure if it was the changes that @di pushed, but I gave it another shot to setup and this time I used Digital Ocean, which was simpler to setup (they have droplets that have docket included) and in conclusion I managed to run the `make build`, `make initdb` and now I can see the frontend.

At first, I tried using the smallest droplet, and still got the same error, and after looking through what the `make build` was doing, I tried again manually to execute the part which was failing which was `npm install -g gulp-cli     && npm install`. `npm install` consistently failed without no apparent reason (it just stopped) which I felt reeks of resource issues.

On a hunch I tried the next biggest instance, and this time `make build` passed, but during `make initdb` it kept on failing, but this time on the console which I ran `make serve` it was pretty clear from the error messages that connections to psql was being denied due to insufficient memory.

So finally I started up a 4 GB RAM, 2 vCPUs droplet and this time it built fine. I guess it was just a memory issue.

Thanks for keeping an eye on this!

**Comment by brainwane** [comment]
@iq8al Hope things are going well; let us know if you need a suggestion for a Warehouse task to work on! Thanks.

**Comment by Ravindrakumara** [comment]
C:\Users\*****\Documents\Django\tutorial\Practice_Django\sit-env> docker-compose build
Building web
Step 1/7 : FROM python:3.7
3.7: Pulling from library/python
                                                                                                                                                                        375fbabb8494: Downloading [=========================>                         ]   833 MB/1.664 GB                                                                       c938241e0507: Download complete                                                                                                                                         263b3c974c17: Download complete                                                                                                                                         294910466265: Download complete                                                                                                                                         1603b8e237a6: Download complete                                                                                                                                         88f18a1fc097: Download complete                                                                                                                                         0af1da21a6de: Download complete                                                                                                                                         f89eb0ac82af: Download complete                                                                                                                                         30438d232893: Download complete                                                                                                                                         d8052512fb5c: Download complete   
ERROR: Service 'web' failed to build: stream error: stream ID 13; HTTP_1_1_REQUIRED
