### ISSUE TITLE
Release project "publish" for reuse?

### ISSUE THREAD

**Issue by mortenlj** [pypa/warehouse#2731]
Hi,

We want to publish our tool for publishing python packages, and in the process of preparing we searched pypi to find a suitable name. Somewhat surprised, we found that nobody had released anything with the name "publish", so we went ahead and made that our name, and created https://github.com/fiaas/publish.

Big was the disappointment when we tried uploading and was informed that "The user 'fiaas' is not allowed to upload to project 'publish'".

Since PEP 541 seems to still be in draft and I noticed #1487, I figured I might as well ask if it's possible to transfer ownership of the apparently inactive project "publish" to either my private user "mortenlj", or our organisation-user "fiaas"?

If we assume that PEP 541 is close to how it will look in the end, I think the current "publish" project falls in the "invalid project" category.

**Comment by di** [comment]
@mortenlj I agree, that project would likely fall under the "invalid project" category.

Unfortunately until PEP 541 is accepted, we don't have a formal process to do this in a fair way, so you'll need to hang tight until that happens.

**Comment by mortenlj** [comment]
Hi. Now that PEP541 has been [Accepted](https://mail.python.org/pipermail/python-dev/2018-March/152455.html), any chance of moving this forward? :slightly_smiling_face:

**Comment by yeraydiazdiaz** [comment]
Hello @mortenlj, sorry for the delay on your request.

I have sent @daltonmatos an email asking to clarify his position in this regard. Hopefully we will hear from him soon and move this issue forward.

**Comment by daltonmatos** [comment]
Hello @yeraydiazdiaz, hello @mortenlj.

I'm more than happy to release the `publish` project on Pypi. Let me know what I have to do to properly transfer the project's ownership.

Thanks,

**Comment by yeraydiazdiaz** [comment]
Hi @daltonmatos thanks for getting back to us.

If you visit https://pypi.org/manage/project/publish/collaboration/ you should be able to add @mortenlj whose PyPI username is "mortenlj" as an owner. At that point he can access the same page to administer ownership as he sees fit.

**Comment by daltonmatos** [comment]
Hello all,

I just added @mortenlj as an owner in the `publish` project on Pypi. @mortenlj, I think you can now remove me from the project and become the only owner of it.

Thanks,

**Comment by jamadden** [comment]
@mortenlj Could you please close this issue once you're satisfied in the transfer?

**Comment by mortenlj** [comment]
@daltonmatos : Thanks! I have taken ownership of the project now.
