### ISSUE TITLE
De-duplicate "Owner" and "Maintainer" roles 

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2745]
Currently on pypi-legacy, it's possible for a user to have both the "Owner" and "Maintainer" roles.

However, an "Owner" can do everything a "Maintainer" can do, so it doesn't make sense for a user to be able to have both roles.

In the short term, we decided to add a hack to hide any "duplicate" roles in #2705, and remove the ability to add multiple roles for the same user in Warehouse.

Once pypi-legacy is shut down, we can run a migration which removes any of these "duplicate" roles., and remove this hack.

**Comment by brainwane** [comment]
I think I'm unclear -- what can an Owner do that a Maintainer *can't* do? I am probably doing to open a documentation issue to put that info somewhere users can get at. Thanks.

**Comment by di** [comment]
@brainwane The following information box is included on the 'Collaboration' page where a user has the ability to change these roles:

<img width="825" alt="screen shot 2018-02-09 at 5 00 52 pm" src="https://user-images.githubusercontent.com/294415/36054225-d98ad76c-0dba-11e8-94fd-7dcb72649fd7.png">

I think that should probably suffice in terms of documentation, but it probably wouldn't hurt to duplicate it elsewhere.

**Comment by di** [comment]
Actually, this should probably get revised, because Owners can do other things too now (like delete files, releases, and the entire project).
