### ISSUE TITLE
Inconsistent handling of packages with equivalent version numbers (e.g. v4.1 & v4.1.0)

### ISSUE THREAD

**Issue by ralphwetzel** [pypa/warehouse#2788]
## Situation
Yesterday I uploaded a new release (**v4.1**) of 'theonionbox' to `https://upload.pypi.org/legacy/`.
Short after the upload I discovered that I made a mistake in the packaging process. With the intension to fix this 'silently' = without (relevant) change of the version number, I created a **v4.1.0** package and pushed it to PyPI. PyPI accepted this without complaint.

## Finding
Today, the comparison of the legacy system [pypi.python.org](https://pypi.python.org/) vs the _warehouse_ based [new one](https://pypi.org/) reveals what looks like a difference in the version number sorting algorithm:

[pypi.python.org](https://pypi.python.org/pypi/theonionbox) offers v4.1.0 as the latest version...
<p align='center'>
<img width="80%" alt="4 1 0" src="https://user-images.githubusercontent.com/16342003/34959213-c6736858-fa35-11e7-8f05-11924201219a.png">
</p>

... whereas [pypi.org](https://pypi.org/project/theonionbox/) announces v4.1:
<p align='center'>
<img width="80%" alt="4 1" src="https://user-images.githubusercontent.com/16342003/34959257-02eec3a4-fa36-11e7-81f3-d71f56c5b750.png">
</p>

## Some further remarks

- The [Python source code](https://svn.python.org/projects/stackless/trunk/Lib/distutils/version.py) explains that v4.1 and v4.1.0 are equivalent:
<p align='center'>
<img width="80%" alt="strict" src="https://user-images.githubusercontent.com/16342003/34959520-298f806a-fa37-11e7-96a6-5c48bccae081.png">
</p>

- Performing a `pip install theonionbox` collects v4.1.

- Performing an explicit `pip install theonionbox==4.1.0` collects v4.1 as well.

- The sequencing in the [release history](https://pypi.org/project/theonionbox/#history) of pypi.org displays v4.1.0 prior to v4.1 - which is technically wrong with regard to the upload time:
<p align='center'>
<img width="80%" alt="history" src="https://user-images.githubusercontent.com/16342003/34959868-aaec8292-fa38-11e7-98d1-f3cae7d93fdb.png">
</p>

- Explicitly selecting v4.1.0, [pypi.org](https://pypi.org/project/theonionbox/4.1.0/) as well states that this is the 'Latest Version':
<p align='center'>
<img width="80%" alt="latest" src="https://user-images.githubusercontent.com/16342003/34960655-04808aee-fa3c-11e7-91d4-4eadcd63b649.png">
</p>

- After a click on this 'Latest Version' button ... pypi.org crashed. :anguished:

## Summary

- pypi.python.org and pypi.org are not consistent in the way they handle this special case of version numbering.

- One could argue that pypi.python.org is 'more correct' as it respects the sequencing of the file upload.

## Proposal
- Option A: Change _warehouse_ to follow the legacy algorithm.

- Option B: As the Python source explicitly states, that v4.1 and v4.1.0 are equivalent, _warehouse_ should treat them as equivalent and reject uploads of that kind.

My preference is **Option B**.

**Comment by brainwane** [comment]
@ralphwetzel Thanks for your detailed and thorough bug report, and sorry for the slow response!

I spoke with @di about this and we agree with **Option B**:

~~~
>>> from packaging.version import parse
>>> parse('4.1') == parse('4.1.0')
True
~~~

We get the release for a file upload at https://github.com/pypa/warehouse/blob/master/warehouse/forklift/legacy.py#L798-L803 and the relevant line is `(Release.version == form.version.data)).one()` (assuming the version strings match, not equivalences like `4.1` == `4.1.0`).

You mentioned that pypi.org crashed when you tried to select ‘Latest Version’, and that button ought to go to the page you were already on. Do you remember any details about the crash? Was it an error 500?

Thanks and sorry again for the wait.

**Comment by dstufft** [comment]
Yea, in addition to the "display" version (that keeps track of what the author actually put) we should probably add a normalized version column which is part of the uniqueness of the table, which does things like strip padded zeros and the like.

**Comment by di** [comment]
I feel like this is something the `packaging` module should be able to do, so I made an issue: https://github.com/pypa/packaging/issues/121

**Comment by ralphwetzel** [comment]
@brainwane Yes, it was a 500.

**Comment by brainwane** [comment]
@ralphwetzel Thanks for the report! http://pypi.org/ now has the fix.

**Comment by johnterickson** [comment]
FWIW we (Azure DevOps Artifacts) just encountered this issue when looking at `requests` as both https://pypi.org/project/requests/0.12.01/ and https://pypi.org/project/requests/0.12.1/ exist.  We'll be handling this on our side, but I just wanted to note it here in case others encounter it.
