### ISSUE TITLE
Add release detail page

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2807]
We need to add a release detail page and link to it from the releases page

The release detail page should display:
- the files for a release and a journal for the release
- the ability to delete a release

In `warehouse/templates/manage/project.html` we have two links to this page:

1. via the version number on the left of the table
2. via the 'edit' button in the dropdown

![screenshot from 2018-01-17 06-57-12](https://user-images.githubusercontent.com/3323703/35085158-42f384ea-fc1f-11e7-8ddd-42071c5055b5.png)

These are currently commented out in the code.  We should enable them as part of this issue.

**Comment by nlhkabu** [comment]
A sub ticket of #424

**Comment by di** [comment]
@nlhkabu I pushed a branch which stubs out the individual release view here: https://github.com/pypa/warehouse/tree/individual-release-view

**Comment by nlhkabu** [comment]
Thanks @di :)  I started work on this - however, I don't seem to be able to output the files associated with a release.  `{{ release.files }}` is returning a database query:

![screenshot from 2018-01-31 21-37-54](https://user-images.githubusercontent.com/3323703/35648864-0e28bbee-06cf-11e8-81e3-15989ac4f0c8.png)

I assume this means we need to pass files explicitly via the view?

I am also going to need to list the journal entries for the release - like this:

![screenshot from 2018-01-31 21-37-45](https://user-images.githubusercontent.com/3323703/35648907-2f3211c8-06cf-11e8-9200-78a6882cc329.png)

Would it be possible if you made both of these data available to the template?

**Comment by di** [comment]
@nlhkabu I pushed a commit to the branch which adds the release's files to the view.

The journal entries in that screenshot are for the entire project, not for individual releases. I think we probably want a separate page (maybe something called "Events" or "Project History") at the top level rather than including them here.

**Comment by nlhkabu** [comment]
thank you :)

Let's open a new ticket for the project history - I believe @ewdurbin and I discussed the MVP having these displayed at a release level, but I might be mistaken on that.

**Comment by di** [comment]
Hmm, looks like I'm wrong -- legacy PyPI actually does show a mix of project-level journal entries and release-level journal entries on each release page.

This seems like it would be somewhat confusing to users. IMO it'd be better to have all the journal entries in one place, but perhaps I'm missing something obvious and @ewdurbin can chime in and explain why it's like that on legacy.

**Comment by nlhkabu** [comment]
thanks @di - I opened a new ticket for this - I've copied your comment over :)

**Comment by nlhkabu** [comment]
hi @di - I just noticed I am getting a 404 page when clicking on the 'collaborators' page from the release detail page.  As far as I can tell, all other pages are working as expected. Could you please take a look? Thanks!
