### ISSUE TITLE
Add instructions for creating a new release

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2809]
This block is currently commented out on `warehouse/templates/manage/project.html`.

We should enable it and add help text.

![screenshot from 2018-01-18 07-20-34](https://user-images.githubusercontent.com/3323703/35085326-1765e39e-fc20-11e7-8910-bc776d848eec.png)

**Comment by nlhkabu** [comment]
To be clear, this is the message shown if there are no releases in a project.  As @di raised in the meeting, it is not possible to create a project without a release.

*However* it is possible to delete all releases - so we should show a message in this instance.

Maybe something like:

```
No releases found.  <link to docs>Learn how to make a new release</link>
```

wdyt @di, @ewdurbin ?

**Comment by di** [comment]
I think this makes sense. Also worth mentioning that there are probably a lot of projects registered without releases via the legacy API, so this is worth doing.

**Comment by brainwane** [comment]
We talked about this a little in [today's bug triage meeting](https://wiki.python.org/psf/PackagingWG/2018-01-29-Warehouse). We may want to discuss what chunk of documentation we want to put here versus in [the canonical packaging guide](https://packaging.python.org/tutorials/distributing-packages/).
