### ISSUE TITLE
Link to 'edit project' when logged in user is owner

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2810]
I have added a button in the UI to link *back* the the manage project page, when the user is viewing their project.

![screenshot from 2018-01-18 07-25-07](https://user-images.githubusercontent.com/3323703/35085471-ca4590a4-fc20-11e7-8f2e-4800b119b9fe.png)

This is currently commented out.

**Comment by nlhkabu** [comment]
A sub ticket of #424

**Comment by di** [comment]
This will need it's own client-side-include route.
