### ISSUE TITLE
Document memory requirements to Getting Started guide

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2811]
This has been a recurring issue. Developers will need to allocate ~4GB of memory to Docker in order to run and initialize all the Warehouse services.

**Comment by pradyunsg** [comment]
This is doc-only. This shouldn't be hard.

Would linking to https://stackoverflow.com/a/44533437 be enough for this?

**Comment by pradyunsg** [comment]
... along with the accompanying text + section in the right place and all that. :P

**Comment by di** [comment]
I think it'd be better to provide more specific documentation than just linking to that issue.

That answer doesn't exactly apply here, because `docker-machine` and Virtual box is not part of our recommended environment.

**Comment by pradyunsg** [comment]
> I think it'd be better to provide more specific documentation than just linking to that issue.

Ah yes. Reading it again, that makes sense. It's really just the "how to increase memory" parts we care about.

**Comment by pradyunsg** [comment]
Cool. PR coming right up. :)
