### ISSUE TITLE
Disable "view project" links when project has no releases

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2828]
Currently in the logged-in UI, there are a few places where there are "View" and "View Project" buttons for a maintainer's project, which lead to the project page (e.g. `https://pypi.org/project/<project_name>/`)

However if the project has no releases, the project page will be 404. In this case, we should disable these buttons (via the `disabled` attribute) and add an alt text saying something like "This project has no releases".

**Comment by ramitmittal** [comment]
I'd like to work on it, first timer here.
