### ISSUE TITLE
Manage Account: Delete Account

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2832]
From #423: From the 'manage account' page, a logged-in user should be able to delete their account.

If the user is the sole owner of any projects, this should be disabled and they should be informed that they need to transfer ownership or delete the projects before they can delete their account.

A notification email should be sent to the primary email address when the account is successfully deleted.

**Comment by waseem18** [comment]
@di 
I've started diving into the code and would like to work on this issue.

I'll get back if I get any questions and will put a WIP PR.

**Comment by di** [comment]
Hi @waseem18, I appreciate your enthusiasm! However I've already begun work on this issue. If you're looking for something relevant to work on, I'd recommend searching for issues in upcoming milestones without an assignee. [The project view for this repo might be helpful as well](https://github.com/pypa/warehouse/projects/1).

**Comment by waseem18** [comment]
Thanks for the information @di

**Comment by di** [comment]
There's a branch for this here: https://github.com/pypa/warehouse/tree/delete-account, but it's on top of branches for #2830 and #2831, which should get shipped first.
