### ISSUE TITLE
duplicate footer appears in package page only when not logged in

### ISSUE THREAD

**Issue by johnyf** [pypa/warehouse#2843]
When viewing a package page (appears to apply to any package), the (blue) footer ("Get Help", "About PyPI", "Contributing to PyPI") occurs twice: once below a login prompt and a search text box that appear below the package's title (with the package details below these and the footer), and once at the bottom of the page (the latter as expected).

This behavior occurs only when logged out. In contrast, when logged in, the layout seems as intended: a search text box at the top, and the package title and details contiguously below that search box, with a single footer at the bottom.

**Comment by pradyunsg** [comment]
<img width="565" alt="screen shot 2018-01-26 at 7 05 03 pm" src="https://user-images.githubusercontent.com/3275593/35442066-dc315d82-02cb-11e8-8eeb-d879a8181cab.png">

**Comment by johnyf** [comment]
Indeed, this is how it looks, with the bottom footer appearing after the section of details that starts with "Navigation". Thanks for adding a picture.

**Comment by dstufft** [comment]
Going to guess an HTML include got messed up, i think @di added one here recently?

**Comment by di** [comment]
Yeah, I know what's causing this. On it.

**Comment by di** [comment]
Thanks for the report @johnyf!

**Comment by johnyf** [comment]
Thanks for addressing this issue!
