### ISSUE TITLE
Transfer ownership of peregrine in PyPI namespace

### ISSUE THREAD

**Issue by FlipperPA** [pypa/warehouse#2845]
I had posted this to SourceForge, but is seems issues are being tracked here now. Here's the original ticket I filed: https://sourceforge.net/p/pypi/support-requests/769/

I've got a package ready for release (https://github.com/FlipperPA/peregrine/) for beta. When I use twine to upload, I get the following error:

HTTPError: 403 Client Error: The user 'FlipperPA' is not allowed to upload to project 'peregrine'. See https://pypi.org/help#project-name for more information.

There doesn't appear to be a package called peregrine on PyPI, so I can only surmise that someone registered it but never made any releases. I'd like to take ownership of the package name in the PyPI namespace so I can release, if and when PEP-541 is approved.

Thanks again for all you do.

**Comment by di** [comment]
Hey @FlipperPA, sorry about that. Unfortunately until PEP 541 is accepted, we don't have a formal process to do this in a fair way, so you'll need to hang tight until that happens. Sorry for the inconvenience.

**Comment by ewdurbin** [comment]
@kuasha is the apparent owner of the `peregrine` project name. The easiest way to accomplish this would be for them to transfer ownership. I've emailed the address associated with the PyPI user as well.

**Comment by kuasha** [comment]
My plan was to rename my package cosmos to peregrine- cosmos has so much conflict with so many things - and that why I registered that name. https://github.com/kuasha/peregrine . I understand, its frustrating to see empty packages. I am OK giving up the name since I never uploaded  the package to pypi. @ewdurbin you may transfer the ownership or let me know if I have to do it.

**Comment by di** [comment]
Done! Thank you @kuasha and thanks @FlipperPA for your patience.

**Comment by FlipperPA** [comment]
Thank you all very much! I'm just catching up post-DjangoCon US and this is wonderful.
