### ISSUE TITLE
Package Name Hoarding / Empty packages / Package Reporting

### ISSUE THREAD

**Issue by meichthys** [pypa/warehouse#2848]
I'm a fan of a clean useful repository of packages on pypi. I noticed user 'maxxy' seems to be claiming numerous unused common package names such as:
"error"
"whatsapp"
"ether"
"docket"
and others.

The packages are empty and useless. Their descriptions are all:
  "A simple lib that prints out hello world"

Is there a way to report suspicious or useless packages?
I'm sorry if i overlooked something.

**Comment by meichthys** [comment]
I noticed PEP0541 adresses this issue, but the PEP has not yet been adopted. It would be nice to be able to crowd-source the reporting of name squatting or invalid packages..
https://www.python.org/dev/peps/pep-0541/#invalid-projects

**Comment by di** [comment]
These projects would likely fall under the category of "Invalid Projects" as specified by [PEP 541](https://www.python.org/dev/peps/pep-0541/). Unfortunately until PEP 541 is accepted, we don't have a formal process to do this in a fair way, so we won't remove these until that happens (unless the packages have malicious content).

**Comment by alan-isaac** [comment]
Leaving these packages up is a terrible mistake.  While they may not yet contain malicious content, they are evidently of malicious intent.  At this point, maxxy has squatted 29 names already in use:
https://pypi.org/user/maxxy/

**Comment by meichthys** [comment]
@Alan-Isaac I agree.

**Comment by meichthys** [comment]
PEP 541 was created over a year ago? Who knows how long until it is adopted..

**Comment by di** [comment]
Thanks for the report @meichthys, I had missed that these were all registered today and that a number were typo squatting. This has been resolved.

**Comment by meichthys** [comment]
@di Awesome. Thanks!
