### ISSUE TITLE
Add flake8 plugin to error if flask.session is used directly

### ISSUE THREAD

**Issue by r1chardj0n3s** [pypa/warehouse#285]
We don't want code using flask.session directly accidentally as this could cause caching issues. Access should always be via request.session which is explicit.

**Comment by dstufft** [comment]
I'm going to close this, I've started porting Warehouse over to Pyramid to ease the concerns of the custom framework-ish thing I've got going on here. That work is on the pyramid branch inside this repository. Since we're not using Flask this no longer makes sense.
