### ISSUE TITLE
Display project/release journal

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2871]
Sub ticket of #2734 

We should show the maintainer some history of their project/release.  The current UI looks like this:

![screenshot from 2018-01-31 21-37-45](https://user-images.githubusercontent.com/3323703/35649542-54b93e60-06d1-11e8-9876-2cffb6ba3e87.png)

Questions:

- Should this be on a project level?
- Should this be on a release level?
- Should it be on *both*?
- What milestone should it be in?

On the last question, it's probably not a heap of work for me to get it into the maintainer MVP - so long as the data is ready to go :)

ping @di @ewdurbin @brainwane @dstufft

**Comment by nlhkabu** [comment]
from @di (https://github.com/pypa/warehouse/issues/2807#issuecomment-362085418)

Hmm, looks like I'm wrong -- legacy PyPI actually does show a mix of project-level journal entries and release-level journal entries on each release page.

This seems like it would be somewhat confusing to users. IMO it'd be better to have all the journal entries in one place, but perhaps I'm missing something obvious and @ewdurbin can chime in and explain why it's like that on legacy.

**Comment by di** [comment]
I put this in the Maintainer MVP milestone, since it already exists (in some form) on legacy.

**Comment by di** [comment]
@nlhkabu Branch for you here: https://github.com/pypa/warehouse/tree/project-history
