### ISSUE TITLE
Show avatars, real name on project collaboration page

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2875]
Currently on [the page which allows a package owner to modify collaborators](https://github.com/pypa/warehouse/blob/master/warehouse/templates/manage/roles.html), it only shows the username for each collaborator.

It'd be nice if this page showed the Gravatar image and "real name" for each collaborator as well.

---

**Good First Issue**: This issue is good for first time contributors. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by nlhkabu** [comment]
This issue is actually trickier than expected from a design perspective, because of limited space on tablet and mobile. 

If a contributor wants to output the content, I can help walk through the styling :)

For reference, the CSS for this is located here https://github.com/pypa/warehouse/blob/master/warehouse/static/sass/blocks/_table.scss#L228

**Comment by lgh2** [comment]
I can try working on this one, if that is ok with you all.

**Comment by brainwane** [comment]
So now, thanks to #3047, the avatar is taken care of. Next, the user's wallet name/real name/full name. @alexwlchan would you be interested in working on this?

**Comment by nlhkabu** [comment]
I think we can close this now @brainwane - @lgh2's PR also added the full name :)
