### ISSUE TITLE
Do not link to "Edit" project pages if user is not owner

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2876]
Currently, the list of projects a logged-in user sees at https://pypi.org/manage/projects/ contains projects that they have both the `Owner` and `Maintainer` roles for.

However if the user only has the `Maintainer` role for a project, they do not have the permissions to access the project management pages for that project, and the "Edit" button links to a page that is 404.

Instead, the "Edit" button should be disabled, with a tool tip on it saying something like "You are not an owner of this project".

**Comment by nlhkabu** [comment]
hey @di - I didn't realise this is how this works :/

Maybe we could instead group these under 2 headings 'Owned by You', 'Maintained by You' and hide the edit button in the maintained list?  What do you think?

**Comment by di** [comment]
@nlhkabu I think either would work! The solution I suggested might be better for eventual pagination and longer project lists, though.
