### ISSUE TITLE
error badge broken

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2880]
![screenshot from 2018-02-02 18-12-45](https://user-images.githubusercontent.com/3323703/35748093-b9dbc190-0844-11e8-981a-783a6f64a3e5.png)

Reproduce on https://pypi.org/project/newrelic/2.56.0.42/

I'm not certain, but I think the issue can be fixed here: `warehouse/static/sass/blocks/_status-badge.scss`

**Comment by di** [comment]
This can be reproduced with most badges when the display is condensed:

<img width="805" alt="screen shot 2018-02-20 at 10 31 44 am" src="https://user-images.githubusercontent.com/294415/36436241-540f3d86-1629-11e8-98c7-6b4096a4822d.png">
