### ISSUE TITLE
Request trove classifier for Trio

### ISSUE THREAD

**Issue by njsmith** [pypa/warehouse#2881]
I'd like to request the addition of the trove classifier `Framework :: Trio`, for libraries in the [Trio](https://trio.readthedocs.io) ecosystem. (Examples: [1](https://pypi.python.org/pypi/trioyoyo/1.1.23), [2](https://pypi.python.org/pypi/pytest-trio/0.3.0), [3](https://pypi.python.org/pypi/trio_asyncio/0.3), [4](https://pypi.python.org/pypi/asyncwebsockets/0.2.0), [5](https://pypi.python.org/pypi/multio/0.2.0), [6](https://pypi.python.org/pypi/asks/1.3.9), [7](https://pypi.python.org/pypi/sphinxcontrib-trio/1.0.0), [8](https://pypi.python.org/pypi/discord-curious).) We're reaching the point where I keep being surprised by new libraries I haven't heard of, and I'd rather get the classifier going sooner rather than later to minimize the number of projects we need to track down and add it to...

**Comment by ewdurbin** [comment]
@njsmith would you anticipate versioned sub classifiers?

**Comment by ewdurbin** [comment]
Done!

**Comment by njsmith** [comment]
> would you anticipate versioned sub classifiers?

Not unless we make some terrible mistakes :-)

> Done!

Thank you!
