### ISSUE TITLE
Redirect to project page when user logs in

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2882]
When a user first logs in (or successfully resets their password) , they are currently redirected to the homepage.

It would be nice if they were instead redirected to their projects page at `http://localhost/manage/projects/`

ping @di for feedback and labelling.  I assume we can tag this with 'good first issue'?

**Comment by di** [comment]
Agreed. 👍

**Comment by pradyunsg** [comment]
https://github.com/pypa/warehouse/blob/64510f16148cefe77e7ae69809575c36e484e475/warehouse/accounts/views.py#L119

Just a matter of updating this line, correct?

**Comment by di** [comment]
Yes, and the corresponding tests.

**Comment by waseem18** [comment]
@di @nlhkabu I'm interested in contributing to `warehouse` and would like to start with this good first issue.

**Comment by di** [comment]
Fixed in #2919.
