### ISSUE TITLE
Additional API documentation

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2913]
Our [API Reference](https://warehouse.readthedocs.io/api-reference/) page does not have any documentation for our current JSON APIs:

* `https://pypi.org/pypi/<project_name>/json`
* `https://pypi.org/pypi/<project_name>/<version>/json`

Some discussion about what the different endpoints could be used for would be great as well. For example, the projects endpoint lists all releases for a project, and the release endpoint includes all the files as well as MD5 and SHA256 hashes.

---

**Good First Issue**: This issue is good for first time contributors. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by brainwane** [comment]
In our [meeting today](https://wiki.python.org/psf/PackagingWG/2018-02-12-Warehouse) we discussed this issue. We have a read-only API for programmatic access, and many people want to integrate their tools with our API, so we decided this issue belongs in [milestone 3 (in the next few months), in which we publicize the Warehouse beta](https://github.com/pypa/warehouse/milestone/10).

Also I'm going to break this out into some sub-issues to make it easier to get the minimum done right away (perhaps just example usage like in #1721 plus a little about neighborly usage and rate limits), then add more detail to our API docs later.

**Comment by brainwane** [comment]
Sub-issues:

- #2930 Explain/expand list of current API endpoints/feeds 
- https://github.com/pypa/warehouse/issues/2794#issuecomment-365097451 Explain, in application architecture overview, what parts of the application produce the APIs
- #2931 Document API policies 
- #2929 Add API explorer tool
