### ISSUE TITLE
Pagination for Project History

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2921]
Per #2911: Currently the 'Project History' page just lists all the journal entries for a project, but this could be quite long. We should add pagination for this page.

**Comment by cand126** [comment]
Hi @di, I would like to ask some questions.

1. Is there a mockup for pagination?
2. Does the current API support pagination?

**Comment by di** [comment]
@cand126 Thanks for the questions. This is specifically about the "Project History" in the logged-in UI for project maintainers, it looks like this:

<img width="1154" alt="Screen Shot 2019-03-25 at 11 13 30 AM" src="https://user-images.githubusercontent.com/294415/54935835-1fd95d80-4eef-11e9-8558-1401f145826a.png">

---

<img width="1164" alt="Screen Shot 2019-03-25 at 11 13 35 AM" src="https://user-images.githubusercontent.com/294415/54935840-21a32100-4eef-11e9-9bf2-07c602e3fca2.png">

The pagination buttons are there, but they don't work, and it looks like right now the results are getting truncated as well. This might just require hooking the pagination query parameter up to the query for the Journal entries.

**Comment by cand126** [comment]
@di I created a package with lots of realeases, and the pagination feature seems fine. Each page has 25 items, and the I can navigate to different pages by click the button. The url also indicates the page number.
![Screenshot from 2019-03-29 23-54-19](https://user-images.githubusercontent.com/6241921/55266669-89a29000-527e-11e9-97a5-ac3620346d30.png)
![Screenshot from 2019-03-29 23-54-24](https://user-images.githubusercontent.com/6241921/55266674-8c9d8080-527e-11e9-88fa-312753036fd6.png)
![Screenshot from 2019-03-29 23-54-30](https://user-images.githubusercontent.com/6241921/55266676-90c99e00-527e-11e9-9dd4-7dd069f2003f.png)

**Comment by di** [comment]
Sorry for the goose chase @cand126. I realized that this was due to a misconfiguration of our CDN, which was stripping out URL parameters for these pages. I just updated and it's now fixed.

Thanks for helping debug!
