### ISSUE TITLE
Redirect from login page if user is logged in

### ISSUE THREAD

**Issue by di** [pypa/warehouse#2936]
Currently the ` accounts.login` view will still render even if there's already user logged in.

Since it doesn't make much sense for a user to log in twice, this view should check if there is a logged in user, and redirect to the post-login view if there is. (See #2882 for which view this should be).

---

**Good First Issue**: This issue is good for first time contributors. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by brainwane** [comment]
@waseem18 Would you like to take this on next?

(Until he says yes, this is still up for grabs.)

**Comment by waseem18** [comment]
Absolutely Yes!

I'll start looking into it right away

**Comment by brainwane** [comment]
Cool, thanks, @waseem18 -- if you jump into IRC I have a few more suggestions for you.

**Comment by waseem18** [comment]
Sure, Hopping in

**Comment by waseem18** [comment]
This issue also exists for the view `accounts.register`
