### ISSUE TITLE
I cannot find a way to get contact address for not uploaded (but apparently registered) package

### ISSUE THREAD

**Issue by jgbarah** [pypa/warehouse#2957]
When trying to upload a new 'ceres' package, twine tells me that I have no permissions. I see no package uploaded with that name, so I try to look at the contact point for that package, to find out if they intend to really upload it or they could transfer the name to us. But I don't see any way to find out that address: since there is no package uploaded, there is no contact address either.

Is there any way of sorting this out?

Just in case it matters, message I get from twine:

```
twine upload ceres-0.1.0*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading ceres-0.1.0-py3-none-any.whl
HTTPError: 403 Client Error: The user 'bitergia' is not allowed to upload to project 'ceres'. See https://pypi.org/help#project-name for more information. for url: https://upload.pypi.org/legacy/
```

When I check out https://pypi.python.org/pypi/ceres/ I get:

```
Not Found

Sorry, the page you're looking for couldn't be found.
Perhaps check the URL? 
```

**Comment by di** [comment]
@jgbarah The project exists, it just has no releases. On `pypi.python.org` this will 404, on `pypi.org` it will not: https://pypi.org/project/ceres/

Looks like there's some contact information for the maintainer there, perhaps you can contact them and see if they are willing to transfer ownership of the name to you.
