### ISSUE TITLE
Implement google recaptcha for new user registration

### ISSUE THREAD

**Issue by xoviat** [pypa/warehouse#2974]
Google recaptcha is a free service that is effective at spam control. As it is simple to implement, I would highly recommend doing so to guard against future spam.

**Comment by ewdurbin** [comment]
This is already implemented.
<img width="486" alt="screen shot 2018-02-18 at 1 38 47 pm" src="https://user-images.githubusercontent.com/1200832/36355431-11e973dc-14b1-11e8-84d0-1d704d0b2dda.png">
