### ISSUE TITLE
Login on pypi.org doesn't work with Safari on macOS 10.13.3

### ISSUE THREAD

**Issue by ronaldoussoren** [pypa/warehouse#3000]
The "Help", "Login" and "Register" buttons on the top navigation bar on pypi.org don't work for me using Safari on macOS 10.13.3. In all cases the browser downloads an empty file with a ".dms" suffix.

The "Browse Project" link below the search box works fine, but when I select "AsyncIO" below "By Framework" in the left sidebar I once again get a downloaded file and no other action.

The site works fine using Firefox on the same machine. 

P.S. The same happens with the Safari Technology Preview

**Comment by ronaldoussoren** [comment]
This appears to be a glitch, the site started working again just when I tried to gather more information.

**Comment by brainwane** [comment]
@ronaldoussoren  -- Thanks for the bug report! We had a momentary frontend glitch and it's resolved now. I appreciate you checking and reporting it, though!
