### ISSUE TITLE
show name, not only gravatar on project page

### ISSUE THREAD

**Issue by ThomasWaldmann** [pypa/warehouse#3005]
it only shows the gravatar icon in the maintainers section (in my case some meaningless standard icon as i do not use gravatar), see screenshot from borgbackup project.

![screenshot from 2018-02-20 23-44-34](https://user-images.githubusercontent.com/356103/36453359-15fa56f6-1698-11e8-8d10-a177949db35b.png)

imho, it should display the name as text to the right of the icon.

**Comment by brainwane** [comment]
@ThomasWaldmann Thank you for the report! I agree, it should show the person's name.

I believe this is related to #2875 -- there are multiple pages that should display the person's name alongside the Gravatar.

**Comment by di** [comment]
I think my personal preference would be for this to remain as-is, similar to how this is done on other sites, for example on this very issue:

<img width="240" alt="screen shot 2018-03-15 at 12 13 30 pm" src="https://user-images.githubusercontent.com/294415/37479351-7427ea68-284a-11e8-8ec5-6cf4f6951a2d.png">

We do show the username with a tooltip already:

<img width="319" alt="screen shot 2018-03-15 at 12 16 11 pm" src="https://user-images.githubusercontent.com/294415/37479453-b4e9bf4a-284a-11e8-842b-b2fc6919f4df.png">

I think this is sufficient, but I will defer to @nlhkabu's decision.

**Comment by brainwane** [comment]
For something like a conversation in an individual GitHub issue, which is likely to be almost entirely visited by people who are already familiar with the social context of the team working on a project and who are working together, I think yeah, choosing to display only avatars and then providing names/usernames as mouseovers/tooltips is good. But the context of someone visiting a PyPI project page is more likely to include someone who is unfamiliar with the social context of the project, and so a better comparison might be this GitHub "people in this organization" page, which does include users' display names:

![pypa-people](https://user-images.githubusercontent.com/842790/37650949-e44e0960-2c0c-11e8-895c-7991c0cd87c8.png)
