### ISSUE TITLE
iso 8601 dates (and times)

### ISSUE THREAD

**Issue by ThomasWaldmann** [pypa/warehouse#3010]
Rather than imposing american date / time formatting on the world, can we just use iso 8601?

See link for details: https://xkcd.com/1179/

![screenshot from 2018-02-21 00-23-38](https://user-images.githubusercontent.com/356103/36454760-887f0d70-169d-11e8-91a9-eba7febbc508.png)

![screenshot from 2018-02-21 00-26-15](https://user-images.githubusercontent.com/356103/36454846-e099dfda-169d-11e8-851f-9eaf49bf2cfb.png)

![screenshot from 2018-02-21 00-27-01](https://user-images.githubusercontent.com/356103/36454870-f6ed1720-169d-11e8-8d96-afd79ea3352d.png)

etc. - if you also have time somewhere, make sure to use iso 8601 for that, too.

**Comment by dstufft** [comment]
I think all of our dates go through a localization engine, and at some point we can/will expose the ability for people to select the datetime display that works best for their locale.

**Comment by ThomasWaldmann** [comment]
I don't think full localization (or i18n, like translation) is required or even desired (personally, I always prefer good English over a bad translation and I also prefer ISO datetime over US or German datetime, because it sorts correctly).

But that doesn't mean that it should be localized to USA by default.

That ISO standard is there since ages (and totally makes sense), we finally should implement *that* as default. It's no big thing, just define some format string constants and use them everywhere.

**Comment by ewdurbin** [comment]
I'm +1 for displaying dates/times in ISO-8601 until we setup localization.

**Comment by di** [comment]
I made this comment in the MOSS-grant meeting last week but I'll reproduce my opinon here:

> ISO 8601 is great for machines but "2018-03-12" is more ambiguous than "March 12, 2018" without context for what format the date is in

I will defer to @nlhkabu's decision however.

**Comment by brainwane** [comment]
@nlhkabu I'm deferring to you on how to address this and how to prioritize it. Thanks.

**Comment by brainwane** [comment]
@nlhkabu I would appreciate if you could check on this in your user testing. Thanks!

**Comment by nlhkabu** [comment]
My preference here is to keep it as is:

> For dates, the main guideline is: Always spell out the name of the month. Using a notation like 8/9 is confusing -- is that August 9th or the 8th of September? If you write "Aug. 9" people from all countries will understand it, and it requires only a few more characters. Far better than having customers show up at your hotel thirty days before or after their actual reservations.

https://www.nngroup.com/articles/international-sites-requirements/

However, I can run a user test with ISO dates and see what feeback we get.

**Comment by nlhkabu** [comment]
Also related - timestamps: http://uxmovement.com/content/absolute-vs-relative-timestamps-when-to-use-which/

**Comment by nlhkabu** [comment]
> Avoid confusing users by using a written date format on your timestamp. Write out the month name in full or abbreviated form, but don’t abbreviate the year. An abbreviated year can cause confusion with the day number.

**Comment by nlhkabu** [comment]
For what it's worth (not much as a sample of one) - As someone who writes dates dd/mm/yyyy, I have no problem with "March 4, 2017" as a format.  It's totally clear to me, even if it's not the direction I would choose to write it.

**Comment by nlhkabu** [comment]
I think we can have the best of both world's - see https://github.com/pypa/warehouse/issues/5085

**Comment by nlhkabu** [comment]
Closing this in favor of #5085.  Thanks for opening @ThomasWaldmann
