### ISSUE TITLE
rst rendering

### ISSUE THREAD

**Issue by Alexis-benoist** [pypa/warehouse#3058]
Hello,

I'm updating my [package](https://pypi.python.org/pypi/ERAlchemy/1.2.5) and the [rst](https://gist.github.com/Alexis-benoist/082d505238a405ee0abb4b2c15c1426c) works normally with restview.

The issue is that the rst is valid but isn't rendered. I checked using restview.

I think it's related to the new API because I released a version with a title only readme in [1.2.2](https://pypi.python.org/pypi/ERAlchemy/1.2.2) (and on [warehouse](https://pypi.org/project/ERAlchemy/1.2.2/)) which also does not render.

What do you guys think?

**Comment by paternal** [comment]
Hello,
warehouse uses [readme_renderer](https://github.com/pypa/readme_renderer) to render the `rst` README. You can install it and check your README using:

~~~sh
$ python setup.py check --restructuredtext
running check
warning: Check: :55: (WARNING/2) Inline literal start-string without end-string.

warning: Check: Invalid markup which will not be rendered on PyPI.
~~~

Replacing ``` with ~~~ lines 55 and 62 of your readme fixes the issue.

-- Louis

**Comment by Alexis-benoist** [comment]
I'm very surprised of your answer.

First of all, I cannot see the "```" in the readme.rst uploaded in [PyPi](https://pypi.org/project/ERAlchemy/#files) or on the [gist](https://gist.github.com/Alexis-benoist/082d505238a405ee0abb4b2c15c1426c).

Secondly, the rst passes the check.

Which file are you looking at?

**Comment by paternal** [comment]
> Which file are you looking at?

I cloned the repository, and ran `python setup.py check --restructuredtext` at its root, so I think (I am at work; I cannot reproduce it) it uses [readme.md](https://github.com/Alexis-benoist/eralchemy/blob/master/readme.md), since it is used as the long description of the pypi package (see [setup.py](https://github.com/Alexis-benoist/eralchemy/blob/450979fd7c0951de9d9cb61210e25390aa770baf/setup.py#L3-L8)).

But you are right: I was wrong. I was not looking at the right file, and `readme_renderer` (which is used by warehouse). I am out of ideas now, and I will let a warehouse contributor answer this…

Sorry for the noise,
-- Louis

**Comment by di** [comment]
I was able to reproduce this if I uploaded [the wheel](https://files.pythonhosted.org/packages/e4/64/4114ad9da5bc95691d65f4db9c714dd7b254e3220d0506384e8e27bd260a/ERAlchemy-1.2.7-py2.py3-none-any.whl) first for the release. If I upload the source distribution first, the description renders correctly.

This is interesting, and might be the cause of https://github.com/pypa/warehouse/issues/2718 (and possibly https://github.com/pypa/warehouse/issues/2582). 

@Alexis-benoist, could you let us know what versions of `wheel` and `setuptools` you're using?

Also are you uploading with `twine upload` (if so, what version of `twine`) or with `python setup.py upload` (if so, what version of Python / `distutils`)?

**Comment by jwkvam** [comment]
Can I do a me too? The rst rendered on pypi.org seems to have mangled my gif img.

https://pypi.org/project/bowtie/#description

The old pypi renders it fine.

https://pypi.python.org/pypi/bowtie/

I honestly can't figure out where this url 
```
src="https://warehouse-camo.herokuapp.com/ef2d4931bffa7d88bd7df3d2c31bc217354c829c/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f38363330342f32303034353938382f36396535363738612d613435612d313165362d383533622d3766363061363135633964612e676966"
```
would have come from.

**Comment by Alexis-benoist** [comment]
Here are my dependencies:
```autoflake==1.1
autopep8==1.3.4
bleach==2.1.2
certifi==2018.1.18
chardet==3.0.4
configparser==3.5.0
coverage==3.7.1
docutils==0.14
enum34==1.1.6
ERAlchemy==1.0.16
flake8==3.5.0
Flask==0.10.1
Flask-SQLAlchemy==2.1
html5lib==1.0.1
idna==2.6
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
mccabe==0.6.1
pkginfo==1.4.1
pluggy==0.3.1
psycopg2==2.6.1
py==1.4.31
pycodestyle==2.3.1
pyflakes==1.6.0
Pygments==2.2.0
pygraphviz==1.3.1
pytest==2.9.1
readme-renderer==17.2
requests==2.18.4
requests-toolbelt==0.8.0
restview==2.8.1
six==1.11.0
SQLAlchemy==1.0.12
tox==2.3.1
tqdm==4.19.5
twine==1.9.1
urllib3==1.22
virtualenv==15.0.1
webencodings==0.5.1
Werkzeug==0.11.5
wheel==0.24.0```

I use twine to upload the files as described [here](https://github.com/Alexis-benoist/eralchemy/blob/master/script/make_release.py#L37)

**Comment by di** [comment]
@Alexis-benoist Your `wheel` version seems pretty old, could you try to `pip install -U wheel` and build a new wheel distribution? You could either try uploading it to PyPI or you can link to it here and I can test it locally.

**Comment by di** [comment]
@jwkvam Could I ask you to open a separate issue? We use a [camo](https://github.com/atmos/camo) proxy to route image requests through SSL, and seems like it either failed or didn't like your image for some reason.

**Comment by Alexis-benoist** [comment]
I upgraded wheel and it works.

Thanks!

https://pypi.org/project/ERAlchemy/
