### ISSUE TITLE
Pickling error in primefac

### ISSUE THREAD

**Issue by shortjonescipher** [pypa/warehouse#3066]
When primefac() in primefac.py starts to multifactor, multifactor() starts processes for the various methods, invoking the target factory().

Under Python 2.7.12 on Windows 10 Home version 1709, this gives 'PicklingError: Can't pickle <function factory at 0x055C3970>: it's not found as primefac.factory'.

The fix is to move the factory() definition outside the multifactor() function.

Test using a sufficiently large number, such as 1489576198567193874913874619387459183543154617315437135656, to trigger multifactoring.

**Comment by di** [comment]
Hi @shortjonescipher, this repository is for the code which powers https://pypi.org, not the projects which it hosts.

It seems like you're using https://pypi.org/project/primefac/ which I can't find an issue tracker for, and hasn't been released in a while. Perhaps you might have more luck with [this fork](https://github.com/elliptic-shiho/primefac-fork) instead?
