### ISSUE TITLE
400 Bad CSRF Token

### ISSUE THREAD

**Issue by jan-janssen** [pypa/warehouse#3068]
Hello, 

I just signed up but somehow I have a hard time uploading packages - some times it works but most of the time it fails and when I try to manually login, I sometimes get the following error message. 

```
400 Bad CSRF Token

Access is denied. This server can not verify that your cross-site request forgery token belongs to your login session. Either you supplied the wrong cross-site request forgery token or your session no longer exists. This may be due to session timeout or because browser is not supplying the credentials required, as can happen when the browser has cookies turned off.

check_csrf_token(): Invalid token
```

Best regards 

Jan

**Comment by di** [comment]
Hi @jan-janssen, sorry you're having trouble.

As far as I can tell login for https://pypi.org is working normally. Is it possible you have cookies turned off like the error message is suggesting? Could you give us some details about what browser/OS you're using? Could you tell us what the error message you get when uploading packages is?

**Comment by brainwane** [comment]
@jan-janssen If this error happens to you again, please feel free to reopen this issue and tell us more about how to reproduce it! We've made several improvements to PyPI since you opened this issue, so unless you tell us it's still happening, I think it's probably resolved. Thank you.

**Comment by ronaldoussoren** [comment]
FWIW I get this error as well, but only intermittently and I cannot reproduce it at will.  This is with Safari on macOS 10.14.

If I reload https://pypi.org/ when I get the error I am logged on after all.

Is there information I can collect when this happens again that will make debugging easier?
