### ISSUE TITLE
Do not show 'view project' button when there are no releases

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3069]
## Steps to reproduce

- Login as a package maintainer
- Go to the projects page
- Click on a project
- Delete all releases on the project

## What happens

The project card at the top of the page shows a 'view project' button:

![screenshot from 2018-02-27 08-25-55](https://user-images.githubusercontent.com/3323703/36717975-09b08f46-1b98-11e8-9eb7-5e6c03cc653e.png)

## What should happen

The 'view project' button at the top of the page should not show if there is no release.

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
I think I would prefer if this button was disabled w/ a tooltip, not hidden, as it might not be immediately obvious to a user why the button is present for some projects and not present for others.

@nlhkabu Thoughts?

**Comment by brainwane** [comment]
@nlhkabu I agree with @di who said,

> I think I would prefer if this button was disabled w/ a tooltip, not hidden, as it might not be immediately obvious to a user why the button is present for some projects and not present for others.

so please consider reopening this to add that.

**Comment by di** [comment]
Hmm, I seemed to have merged https://github.com/pypa/warehouse/issues/3257, this might have been my fault.

**Comment by nlhkabu** [comment]
Nope, we can leave it closed.  User testing suggested the button was confusing, so removing it altogether is a better solution :)
