### ISSUE TITLE
handling db transactions in Warehouse

### ISSUE THREAD

**Issue by toumorokoshi** [pypa/warehouse#307]
Right now, warehouse has a pattern of passing in the "app" object into db querying methods:

    def scalar(query, default=None):
        """
        A helper function that takes a query and returns a function that will query
        the database and return a scalar.
        """
        def inner(model, *args, **kwargs):
            val = model.engine.execute(query, *args, **kwargs).scalar()

            if default is not None and val is None:
                return default
            else:
                return val

        return inner

The unfortunate consequence of this pattern is the fact that it becomes very difficult to wrap these methods in transactions. For example, the common pattern for transactions are:

    def db_query_method(model):
        with model.engine.begin() as trans:
            trans.execute(query_1)
            model.db_other_query_method()

However, "db_other_query_method" in this case does not execute in the transaction; it calls model.engine directly, which is outside of the transaction scope.

A threadlocal execution strategy would allow transactions to work with the existing pattern:
http://docs.sqlalchemy.org/en/rel_0_9/core/connections.html#using-the-threadlocal-execution-strategy

Effectively, this works by having the engine globally (local to the thread) enter a transaction. This is an older pattern, and makes it difficult to execute multiple transactions at once.

## Proposed solution

If we make every method static, and accept a SQL connection object instead of a Warehouse App instance, this would allow for very easy composition of transactions:

    def db_query_method(connection):
        with connection.begin() as trans:
            trans.execute(query_1)
            db_other_query_method(trans)

By passing in the transaction, we know that the second query method will be contained inside a transaction. SQLAlchemy also gracefully handles multiple nested transactions.

http://docs.sqlalchemy.org/en/rel_0_9/core/connections.html#nesting-of-transaction-blocks

**Comment by dstufft** [comment]
I'm going to close this, I've started porting Warehouse over to Pyramid to ease the concerns of the custom framework-ish thing I've got going on here. That work is on the pyramid branch inside this repository. As part of that we've switched over to using SQLAlchemy's ORM and the transaction support is handled by passing around an explicit session which is inside of a transaction.
