### ISSUE TITLE
Disabled 'edit' button leads to 404

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3070]
## How to reproduce

- Login as a project maintainer.  The user you log in as must be a 'maintainer' on at least one project
- View your list of projects
- Click on the disabled 'edit' button

![screenshot from 2018-02-27 08-26-10](https://user-images.githubusercontent.com/3323703/36718099-7fb9367a-1b98-11e8-8697-a4ac85ab7cdd.png)

## What happens

Clicking on the button leads to a 404

## What should happen

Clicking on the button should not do anything.

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
Ideally this would be fixed site-wide by adding a `pointer-events: none;` to the disabled link style.

**Comment by waseem18** [comment]
I'll work on this as it's in the current milestone.

**Comment by waseem18** [comment]
@di @nlhkabu I need some help in reproducing this locally. Is there any test maintainer-user (from the local dev environment database) I can login with so that I can reproduce this bug?

**Comment by di** [comment]
@waseem18 Not sure I'm totally understanding your question. You can make any changes you need to in your local dev environment to accounts/roles/etc, so for this:

* Find a package
* Log in as it's owner
* Add some other user as a maintainer
* Log out, and log in as the maintainer
* then this should be reproducible

**Comment by waseem18** [comment]
Thanks for the reply @di . I'll do that.
