### ISSUE TITLE
Old wheels may have broken descriptions

### ISSUE THREAD

**Issue by di** [pypa/warehouse#3084]
In https://github.com/pypa/warehouse/issues/3058 we figured out that a wheel built with `wheel==0.24.0` had a broken description when uploaded to Warehouse. Upgrading to `wheel==0.30.0` fixed it.

If we have a way to determine what version of `wheel` the wheel was built with, we may want to warn the user in some way (from Warehouse? in twine?) that it could result in an incorrectly rendered description.

**Comment by dstufft** [comment]
Look a ``*.dist-info/WHEEL``, that should contain what was used to build it, but not sure if it includes version information or not.

**Comment by di** [comment]
Seems like maybe this issue belongs over at pypa/twine instead since we're not doing much introspection of the distributions.

**Comment by brainwane** [comment]
About how many projects do we currently have where the most recent release has a broken description because of this issue? I presume that's something I could figure out via Google BigQuery if I figured out how to use it.

**Comment by di** [comment]
I don't think it's possible via BigQuery, as Donald said, the version of `wheel` used to build the distribution is in the metadata, but we don't extract it or do any introspection of the file.

I haven't seen many reports about this, and there might not really be a good way to fix it, so this shouldn't be high-priority (folks should just update their `wheel`).

**Comment by di** [comment]
Closing this since we no longer allow uploads with invalid/broken descriptions, so the point is moot.
