### ISSUE TITLE
Add note indicating that changing Gravatar images might take a while to appear

### ISSUE THREAD

**Issue by di** [pypa/warehouse#3086]
Because the user page is cached, if the user changes their Gravatar image, it might take a while before it actually shows up on their profile page.

We should add a note below the "Change Image on Gravatar.com" link informing users that they may not see the change right away.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by brainwane** [comment]
In [today's Warehouse developers' meeting](https://wiki.python.org/psf/PackagingWG/2018-03-06-Warehouse) we decided to pare down our near-future milestones on [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) so they really only contain the essential bugfixes and features we need to launch, replace legacy PyPI, and shut down the old site. So I'm moving this issue into a milestone further in the future.

**Comment by di** [comment]
This is effectively fixed with #3368.
