### ISSUE TITLE
"Internal Server Error" on "Register" link

### ISSUE THREAD

**Issue by torbengb** [pypa/warehouse#3093]
I wanted to register as a new user, but the "[Register](https://pypi.org/account/register/)" link gives me an "Internal Server Error". 

I doubt this is related to my system, but here are my specs:
- Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- Ubuntu Linux 17.04 64-bit
- tried the above on https://pypi.org/account/register/ and also on https://test.pypi.org/account/register/ -- same error on both addresses.

**Comment by di** [comment]
Thanks for the report, we are aware and working on a fix.

**Comment by di** [comment]
@torbengb This should be fixed now. Just wanted to reiterate that we really appreciate you taking the time to make a report!
