### ISSUE TITLE
Make Test PyPI visually more distinct from canonical PyPI

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3104]
https://test.pypi.org/ looks so much like https://pypi.org/ visually -- same colors, same `favicon.ico`, same logo, same `<title>`, etc. -- that when the two are in tabs next to each other, it's harder to distinguish them than I'd like, which might lead to accidents.

Can we make them look more different visually while still preserving the functional parity between Test PyPI and canonical PyPI?

**Comment by nlhkabu** [comment]
@di - is there a way of adding `class="test-pypi"` to the `<body>` tag when the site is https://test.pypi.org/?
If we can do this, I can create some CSS rules to change the styles :)

**Comment by di** [comment]
Yes, we can use the `warehouse.domain` setting to determine which domain we're on, similar to here: https://github.com/pypa/warehouse/blob/fec6e17bc29e449c9dff270ce7eab698d89a3d37/warehouse/templates/robots.txt#L4-L13
