### ISSUE TITLE
Unable to set full name

### ISSUE THREAD

**Issue by mauritsvanrees** [pypa/warehouse#3116]
On https://pypi.org/manage/account/ I tried setting a Full Name. I filled the field and clicked on the Update Account button.
This seemed to have no effect. When I scrolled down, I saw under Account Emails that the 'Add Email' input was marked with an error: 'Please fill out this field'. So somehow the Add Email field is required even when I only want to fill in the Update Account form.
Refreshing the page did not help: the full name was not saved.
I tested it on test.pypi.org for good measure, but got the same result.

Browser: both Safari 11.0.3 and Chrome 64.0.3282.186 on Mac OSX 10.13.3

BTW, kudos for adding a list of projects for which I am the sole owner under Delete Account. I saw two in there that I immediately fixed. Very helpful! 👍

**Comment by di** [comment]
Thanks for the report @mauritsvanrees! This should be fixed in #3117 and will be deployed momentarily.

**Comment by mauritsvanrees** [comment]
I can confirm that this works on test.pypi.org now. Thank you! 👍
