### ISSUE TITLE
“test your bus factor” promo page

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3121]
A user said:

> kudos for adding a list of projects for which I am the sole owner under Delete Account. I saw two in there that I immediately fixed. Very helpful! :+1: 

@di suggested that this is a serendipitous "bus factor" feature and suggested we create a small page to promote it.

My spec:

* This is outside of the usual project URL structure, maybe at something like pypi.org/win-the-lottery
* copy would be something like:

> If you won the lottery, do you have co-maintainers who could step up and take care of your packages? Check your list of projects (LINK, OR INCLUDE THIS LIST IN THE PAGE) to check.
> And check https://libraries.io/experiments/bus-factor?platforms=PyPI for packages that are depended upon by many other packages but have only ever had a handful of contributors commit to the project. You can help out!

* make it shareable with the usual social media buttons

**Comment by pradyunsg** [comment]
I really like this idea.

**Comment by nlhkabu** [comment]
related: https://github.com/pypa/warehouse/issues/3127

**Comment by di** [comment]
Since this was my idea, I'm going to close this as "so incredibly low-priority that it's not even worth keeping the issue open".
