### ISSUE TITLE
Two authors' names get rendered as one mailto on project page

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3123]
The Maintainers section of https://pypi.org/project/pypiserver/

says:

`Author: Kostis Anagnostopoulos <[redacted1]@gmail.com>Matthew Planchard <[redacted2]@gmail.com>`

Page source:

`<p><strong>Author:</strong> <a href="mailto:[redacted1]@gmail.com">Kostis Anagnostopoulos &lt;ankostis@gmail.com&gt;Matthew Planchard &lt;[redacted2]@gmail.com&gt;</a></p>`

There is one `href mailto` link that points to the first person's email address, and visually, at least in Chrome and Firefox on my machine, there's no space between the `>` and the second person's name.

![meta-email-warehouse-render-bug](https://user-images.githubusercontent.com/842790/36924213-c28aed90-1e3b-11e8-8c29-7cfe017313f1.png)

**Comment by di** [comment]
It's because that's exactly how they have it configured for their project:

```
maintainer=("Kostis Anagnostopoulos <ankostis@gmail.com>"
            "Matthew Planchard <mplanchard@gmail.com>"),
maintainer_email="ankostis@gmail.com",
```
