### ISSUE TITLE
Make callout block component dismissible (optionally)

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3126]
Right now, we have 2 notification bars at the top of PyPI.io

It would be nice to allow the users to dismiss these notifications, *and* remember that they've been dismissed.

If someone would be willing to make a PR with a simple 'close' link, I can style the button :)

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by nlhkabu** [comment]
@di - I feel like I should apply the 'good first issue' label here, but I'm not sure about the complexity of adding a cookie, etc.  Can you please confirm? Thx

**Comment by nlhkabu** [comment]
I should be more specific here - we don't necessarily want to make **all** of the `notification-bar`s dismiss-able - just the option to dismiss them in **some** cases.

In the same way, it would be nice for users to be able to remove documentation information boxes (`callout-block` component) *and* for PyPI to remember this preference, e.g.

![screenshot from 2018-03-07 07-09-39](https://user-images.githubusercontent.com/3323703/37078391-02625f68-21d7-11e8-96fd-7b326bb31b1d.png)

Again, we don't want to make all `callout-block`s dismiss-able - just in some cases :)

**Comment by di** [comment]
So, ideally, we could add a "dismissable" controller that would hide the target element, which we could reuse for pretty much anything.

**Comment by nlhkabu** [comment]
I can make a PR with the appropriate CSS styles if someone else can provide the JS :)

**Comment by brainwane** [comment]
@aalmazan now that cryvate's started working again on that other issue, would you like to try this one?

**Comment by aalmazan** [comment]
@brainwane Sure thing. Submitted a partial PR with a quick question in #3202 .

**Comment by nlhkabu** [comment]
Notification bars are now dismissible, thanks to https://github.com/pypa/warehouse/pull/3202
This issue now only relates to the `callout-block` component, which we'd also like the user to be able to dismiss :)

**Comment by di** [comment]
@99 is working on this!

**Comment by ewjoachim** [comment]
I see this ticket is linked to a merged PR. Should we close it or is it still applicable ?
