### ISSUE TITLE
Add "how do I keep up?" to FAQ

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3139]
The [help page/FAQ](https://pypi.org/help/) should include something like:

> Q. How do I keep up with upcoming changes to PyPI?

> A. Subscribe to [the pypi-announce mailing list](https://mail.python.org/mm3/mailman3/lists/pypi-announce.python.org/) and [read PyPI-related blog posts on the PSF blog](https://pyfound.blogspot.com/search/label/pypi) ([Atom feed](https://pyfound.blogspot.com/feeds/posts/default/-/pypi), [RSS feed](https://pyfound.blogspot.com/feeds/posts/default/-/pypi?alt=rss)).

(At some future point, this will expand to include, for instance, https://www.pypa.io/en/latest/roadmap/ . But for right now, the announcement mailing list and the PSF blog posts labelled "pypi" are enough.)

--------

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by brainwane** [comment]
@pgadige let us know if you're interested in working on this!

**Comment by brainwane** [comment]
Thanks, @pgadige. If you are trying to figure out how to approach this, https://github.com/pypa/warehouse/blame/master/warehouse/templates/pages/help.html and https://github.com/pypa/warehouse/commits/master/warehouse/templates/pages/help.html may help. :)

**Comment by brainwane** [comment]
@pgadige How's this going? Do you need any help?

**Comment by pgadige** [comment]
@brainwane apologies for the delay/inactivity. I'd gone deep into the rabbit hole while exploring Jinja2 templates. Now, I can understand what's happening inside help/FAQ page. If I'm stuck, I shall seek help on the IRC. Thank you :)

**Comment by pgadige** [comment]
@brainwane I think the 'About' section will be a good place to hold the above specific question. I'd like to know your thoughts on this.
