### ISSUE TITLE
Collaborators form: Change default selection to 'maintainer'

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3156]
**From user testing:**

On the management collaborators page (`manage/project/<projectname>/collaboration/`) - we have a form to add a new owner or maintainer:

![screenshot from 2018-03-07 07-29-08](https://user-images.githubusercontent.com/3323703/37079139-75f933a0-21d9-11e8-8714-a3ba170ff919.png)

Currently, the default selected value is 'owner' - we should change the order, so that the default value is 'maintainer'.

Reason: Adding a maintainer is less dangerous :)

--------

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by nlhkabu** [comment]
For consistency, we should also change the order of the information above the table, so that maintainer is listed first.

![screenshot from 2018-03-07 08-29-05](https://user-images.githubusercontent.com/3323703/37081832-9a0abaee-21e2-11e8-9db9-79a56b0cb1bb.png)

Related to #3157

**Comment by brainwane** [comment]
@aalmazan Would you be interested in doing this?

**Comment by jMuzsik** [comment]
Hi, I'll work on this, and I can do https://github.com/pypa/warehouse/issues/3157 simultaneously.

Ought I use the exact text used in specified in https://github.com/pypa/warehouse/issues/3157 or is there anything else that should be edited in this view? 

Thanks!

**Comment by nlhkabu** [comment]
Great! thanks @jMuzsik! Yes, let's go with the exact text - thank you!

**Comment by di** [comment]
Fixed in #3313.
