### ISSUE TITLE
Improve owner/maintainer documentation

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3157]
**From user testing:**

On the 'collaborators' page in the management UI, we currently have information about what an owner and maintainer can do:

![screenshot from 2018-03-07 08-29-05](https://user-images.githubusercontent.com/3323703/37081549-aa7bc0e0-21e1-11e8-9d49-9708d0ab9cbf.png)

I think that we could improve this to be more specific about what each user can delete:

> **Owner**
> Owns a project, may add other collaborators for that project, and upload releases for a project.
> May delete files or releases. Can delete the entire project.
> 
> **Maintainer**
> May upload releases for a project. Cannot add collaborators, delete files, delete releases or delete the project.

cc @brainwane for help with this text.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by brainwane** [comment]
This is a followup to #2745, and, to some extent, to #2059.

**Comment by di** [comment]
Fixed in #3313.
