### ISSUE TITLE
Project count maxes out at 10000

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3161]
On https://pypi.org/search/?q=&o=-created:

It seems as though the project counter can only go up to 10,000?

![screenshot from 2018-03-07 20-25-32](https://user-images.githubusercontent.com/3323703/37116277-b8926b20-2245-11e8-81ad-6eafc99c72ee.png)

@di - I assume there is a technical restriction at play here?

Would it be possible to display `10,000+` instead?

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
Yes, elasticsearch limits our results to 10K. I think it'd be reasonable to say something else here when the number of results are exactly 10K. Instead of "10,000+", we could say "Thousands of projects" or something similar?

**Comment by nlhkabu** [comment]
I think the `+` is more accurate.  If we were to say "thousands of projects", I would (as a user) assume it was more than a thousand, but less than "tens of thousands".  Also, `+` doesn't require any fancy translations (when/if the time comes).

**Comment by nlhkabu** [comment]
Closed by https://github.com/pypa/warehouse/pull/3193
