### ISSUE TITLE
Change delete confirmation models

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3162]
**From user testing:**

1. The placeholder text in the delete modal can be confusing.  We should remove it.
2. Typing the full file name is very painful

### Delete File
![screenshot from 2018-03-07 20-44-40](https://user-images.githubusercontent.com/3323703/37117262-a1dd9da2-2248-11e8-939b-3d79476a8812.png)

- Remove placeholder text
- Make confirmation "Confirm the project name (<strong>`projectname`</strong>) to continue" / "Project Name"

### Delete release
![screenshot from 2018-03-07 20-44-27](https://user-images.githubusercontent.com/3323703/37117264-a1fe340e-2248-11e8-9869-538079ab494e.png)

- Make confirmation "Confirm the release (<strong>`releasenumber`</strong>) to continue."
- Remove placeholder text

### Delete project
![screenshot from 2018-03-07 20-44-05](https://user-images.githubusercontent.com/3323703/37117266-a21dbbee-2248-11e8-9249-593c1f7f7cda.png)

- "Confirm the project name (<strong>`projectname`</strong>) to continue."
- Remove placeholder text
- Change label to "Project Name" (titlecase)

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by nlhkabu** [comment]
Not sure if this should be labelled with `Good First Issue` @di?

**Comment by di** [comment]
Removing the placeholder and titlecasing the label should be easy enough. We should probably make changing the actual confirmation field a separate issue though.

**Comment by di** [comment]
If we do remove the placeholder, we should make it a little more clear what the exact string we want the user to type is, right now it's just mixed into the title and not differentiated.

**Comment by nlhkabu** [comment]
Yes, you're right.  I've updated the spec.  I'll open a separate ticket for changing the confirmation on the file modal.

**Comment by nlhkabu** [comment]
Relies on: #3163

**Comment by nlhkabu** [comment]
@brainwane - FYI this was one of the biggest problems identified in user testing, so if we could point new contributors towards it and #3163, that would be great !

**Comment by yeraydiazdiaz** [comment]
I just tested this on `master` and it's working as described, via #3378 and #3467 I believe.

Should we close this?

**Comment by di** [comment]
Hmm, odd this didn't automatically close when I merged #3378.

Thanks @yeraydiazdiaz!
