### ISSUE TITLE
rename `.notification-bar--warning`

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3164]
The current code is:

```
  &--warning {
    background-color: $danger-color;
  }
```

Given we are using the danger color, we should rename this modifier to `.notification-bar--danger`.  We also need to find any place in the codebase where this is being used and update the class.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by alexwlchan** [comment]
Per @brainwane’s suggestion, I’m going to take this one on.
