### ISSUE TITLE
Audit copywriting against styleguide

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3167]
As per [our documentation](https://warehouse.readthedocs.io/ui-principles/#write-clearly-with-consistent-style-and-terminology), Warehouse uses the [material design writing styleguide](https://material.google.com/style/writing.html).

We should cross check our UIs to ensure that we are meeting these guidelines - in particular in relation to [capitalization and punctuation](https://material.io/guidelines/style/writing.html#writing-capitalization-punctuation).

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by nlhkabu** [comment]
To audit:

- [ ] Templates (`/warehouse/templates`)
- [ ] PyPI theme (I will need to make this PR as it is on a separate repository)
- [ ] All "flash" messages, e.g. `request.session.flash` and corresponding tests
- [ ] All error messages, e.g. https://github.com/pypa/warehouse/blob/master/warehouse/manage/forms.py#L30

**Comment by nlhkabu** [comment]
A few places in the templates we seem to have missed:

![screenshot from 2018-04-10 13-40-16](https://user-images.githubusercontent.com/3323703/38581523-0dc24b22-3d05-11e8-9ccb-d0f09b392629.png)
![screenshot from 2018-04-10 13-40-20](https://user-images.githubusercontent.com/3323703/38581524-0de3777a-3d05-11e8-9b20-61dd710b9af2.png)
![screenshot from 2018-04-10 13-45-45](https://user-images.githubusercontent.com/3323703/38581526-0e3132bc-3d05-11e8-896c-1b7813bccc69.png)
![screenshot from 2018-04-10 13-46-05](https://user-images.githubusercontent.com/3323703/38581528-0e4bc2a8-3d05-11e8-9377-ed64a3f6cbc8.png)
![screenshot from 2018-04-10 13-41-13](https://user-images.githubusercontent.com/3323703/38581529-0e7b78e0-3d05-11e8-91fa-7ee89b22babd.png)
![screenshot from 2018-04-10 21-23-06](https://user-images.githubusercontent.com/3323703/38581651-60011ada-3d05-11e8-9b13-5d59807dda80.png)

**Comment by hugovk** [comment]
See PR https://github.com/pypa/warehouse/pull/3609.

**Comment by nlhkabu** [comment]
Flash messages addressed by https://github.com/pypa/warehouse/pull/3830.

Still todo:

- [ ] PyPI theme (I will need to make this PR as it is on a separate repository)
- [ ] All error messages, e.g. https://github.com/pypa/warehouse/blob/master/warehouse/manage/forms.py#L30

**Comment by huangy22** [comment]
Address the form error messages by #3846.

**Comment by di** [comment]
There still seems to be a lot to do here. Just a search for the word "please" in the codebase produces a few files that probably need to be entirely gone over:

* `warehouse/forklift/legacy.py`
* `warehouse/legacy/api/xmlrpc/views.py`
* `warehouse/static/js/warehouse/index.js`
* `warehouse/static/js/warehouse/utils/forms.js`
* `warehouse/templates/base.html`
* `warehouse/templates/accounts/request-password-reset.html`
* `warehouse/templates/pages/security.html`
* `warehouse/templates/pages/help.html`
* `warehouse/templates/upload.html`
* `warehouse/templates/email/verify-email.body.txt`
* `warehouse/templates/email/password-reset.body.txt`

as well as a lot of documentation:

* `docs/roadmap.rst`
* `docs/application.rst`
* `docs/development/index.rst`
* `docs/development/reviewing-patches.rst`
* `docs/development/submitting-patches.rst`
* `docs/development/getting-started.rst`
* `docs/api-reference/index.rst`
* `docs/api-reference/xml-rpc.rst`
* `docs/api-reference/integration-guide.rst`
* `docs/security.rst`
* `docs/ui-principles.rst`

**Comment by hugovk** [comment]
Material Design have restructured their website without adding redirects. 

Here's the new link to the writing styleguide: https://material.io/design/usability/accessibility.html#writing

**Comment by hugovk** [comment]
Also looks like they've removed a lot of the writing advice and examples from the new site.

Here's a link to the most-recent old version from the Internet Archive:

https://web.archive.org/web/20180410101124/https://material.io/guidelines/style/writing.html

**Comment by acangiani** [comment]
@nlhkabu, we(@mferi & @acangiani) are working on this issue.

**Comment by mferi** [comment]
"Please" left on warehouse/forklift/legacy.py and its test. Otherwise seems clean.

**Comment by mferi** [comment]
@nlhkabu 
"Bugas & feedback"
Aspersen is not used consistenly on the website. Should it be a plane "and"?
<img width="246" alt="screen shot 2018-07-28 at 16 27 18" src="https://user-images.githubusercontent.com/9561519/43358050-6d32b0aa-9283-11e8-8164-fbef2abe8a69.png">

**Comment by mferi** [comment]
@nlhkabu 
I would say that lower case here makes sense to keep the style: eg. 
<img width="274" alt="screen shot 2018-07-28 at 16 31 55" src="https://user-images.githubusercontent.com/9561519/43358085-0c6872b8-9284-11e8-8b02-b01b633ebf23.png">
"By topic" or even "by topic"

**Comment by mferi** [comment]
@nlhkabu working on it!

**Comment by hugovk** [comment]
> 4. Change filter list titles to 'By licence', 'By environment', etc.

Looks like the text that comes after "By" are generated from the top-level classifiers: https://pypi.org/pypi?%3Aaction=list_classifiers

https://github.com/pypa/warehouse/blob/af3784d4341da7e6b1b24864f55bd0205f648390/warehouse/templates/search/results.html#L104-L121

**Comment by nlhkabu** [comment]
Closing this issue as it appears we've covered all use cases.  Thanks to all contributors!
