### ISSUE TITLE
Can't receive verification Email, can't upload module!

### ISSUE THREAD

**Issue by shinalone** [pypa/warehouse#3172]
- ***Question:***
On 2017/10/09, I had already confirmed link in Email, and uploaded 3 modules. But now I can't upload modules, because in [new pypi page](https://pypi.org/manage/account/) I crazily click 'send verifaction-Email' more times, I have not received any emails about pypi untill today.

```
#twine upload dist/*
HTTPError: 400 Client Error: User 'UlionTse' has no verified email addresses, please verify 
at least one address before registering a new project on PyPI. See https://pypi.org/help/#
verified-email for more information. for url: https://upload.pypi.org/legacy/
```

- ***Maybe:***
I ensure it's not about network, and I looked for spam of my Email. 
Maybe it causes that old account changed to new account, or pure question of 'send Email', or Manual review, or database, or about [outlook](https://outlook.live.com/)?

***[PLEASE HELP, THANKS!]()***
-------------------------------------------------------------------------
- ***Some Pictures:***

![](https://i.imgur.com/biLgEhS.png)
-------------------------------------------------------------------------
![](https://i.imgur.com/l9blRXj.png)
-------------------------------------------------------------------------
![](https://i.imgur.com/qfwB3Jg.png)
-------------------------------------------------------------------------

***[PLEASE HELP, THANKS!]()***

**Comment by ewdurbin** [comment]
outlook.com is blocking our sending IP I'll take a look.

**Comment by ewdurbin** [comment]
as are live.com, hotmail.com etc... requesting our mail provider look into the issue.

**Comment by shinalone** [comment]
@ewdurbin Thanks a lot.

**Comment by xlcnd** [comment]
Same with me!

**Comment by ewdurbin** [comment]
Still working on this, we're looking at alternatives for sending mail as a result of poor response from our current mail provider.

**Comment by xlcnd** [comment]
I solved the problem by using a non-Microsoft address!

**Comment by ewdurbin** [comment]
We should be good for now! We're going to complete our work to move to a new Mail provider to avoid this in the future.

**Comment by ogdans3** [comment]
Is this still an issue? I have not received any email confirmation after multiple resends and trying three different email addresses: outlook, hotmail and gmail.

**Comment by marfcg** [comment]
Sorry for respawning this closed issue, but I'm having a similar problem with an institutional email that is under outlook as well.
The primary e-mail for my PyPi account is from gmail, which is already verified. I've added my institutional e-mail as a secondary address but I'm not receiving the confirmation e-mail there. I've tried the "resend" button without any luck.
I wonder if you are still facing issues with outlook?

The main issue for me is that I have a package that was registered by a collaborator in which I'm identified as author with my institutional e-mail, not the gmail one. Therefore, PyPi does not allow me to update this package.

Cheers!

**Comment by ewdurbin** [comment]
@marfcg I've checked our email delivery records, and can see two confirmation emails dispatched to what appear to be the address you're referencing.

One at Jun 21, 2018, 8:11:32 PM and another at Jun 21, 2018, 8:25:43 PM (Times UTC).

Based on our visibility the emails were both accepted and delivered.

We're no longer using the mail provider referenced in this issue initially and haven't had any indication of delivery issues for any specific provider thus far.

If the emails aren't in your spam folder or some other email filter, please let me know and I'll reach out to the address on your PyPI account, which appears to be `marfcg`

**Comment by ewdurbin** [comment]
As far as managing the referenced package, that permission must be granted to your user name. The Authors field in Metadata does not grant that privilege.

**Comment by marfcg** [comment]
Thanks for checking this out so quickly, @ewdurbin 
I have just rechecked my e-mail address at fiocruz.br and still no sign of it. Not even on junk/unwanted/trash folders from outlook.

Regarding the package, the user who published it previously (the maintainer) must grant me permission directly?

**Comment by ewdurbin** [comment]
@marfcg, yes the existing maintainer must grant your user `marcfg` on PyPI Maintainer or Owner role via the management UI on pypi.org

I’ll email you directly to debug your email deliverability issues further.

**Comment by fraserw** [comment]
I am experience the same issue as above with testpypi and my gmail address (username fraserw). I have a verified email with pypi, but can't get testpypi to send me a verification email. Meaning I can't test update my package.

**Comment by JasDevs** [comment]
Hi I know its a couple years later but I am also having this issue, I have resent the email about 4 times and I havent gotten it, do you know why?

**Comment by ewjoachim** [comment]
Please create your own issue, it's probably unrelated. If you're sure it's related, link to this issue.
