### ISSUE TITLE
Make error message (for invalid project name) work with Test PyPI

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3186]
Right now, when someone tries to upload a package to PyPI but the project name they want to use is not a project name we allow, the error message we send them includes -- hardcoded -- the URL https://pypi.org. Instead, we should use Pyramid's URL routing to refer to the URL of the PyPI in question, thus ensuring that we send error messages that, as appropriate, refer to pypi.org, test.pypi.org, or any other future PyPI.

To fix this, look at `warehouse/forklift/legacy.py` and `tests/unit/forklift/test_legacy.py` ([the test is `test_fails_with_invalid_names`](https://github.com/pypa/warehouse/blob/master/tests/unit/forklift/test_legacy.py#L872)), and make changes similar to the changes I made in #3183. If you're used to string substitution/string formatting in Python, this should be a relatively approachable first Warehouse issue.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by pgadige** [comment]
I'm working on this issue.

**Comment by brainwane** [comment]
Hi @pgadige! Saw your question in IRC about logging in within your local developer environment. As Dustin said, check https://warehouse.readthedocs.io/development/getting-started/#logging-in-to-warehouse . Glad to have you joining us!

You mentioned you're interested in the larger process of building something like Warehouse. I recommend you take a look at:

* [the PyPA's list of presentations and articles](https://www.pypa.io/en/latest/presentations/)
* [PyPA's history of Python packaging](https://www.pypa.io/en/latest/history/)
* [the Warehouse roadmap](https://wiki.python.org/psf/WarehouseRoadmap)
* [blog posts, mailing list messages, and notes from our core developer meetings](https://wiki.python.org/psf/PackagingWG)
* [Warehouse application overview](https://warehouse.readthedocs.io/application/)
