### ISSUE TITLE
Refactor dropdowns

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3194]
To make the dropdowns keyboard accessible, we should follow this guide: https://www.w3.org/WAI/tutorials/menus/flyout/

At the same time, we should fix a bug we found - that sometimes the dropdown are being cut off:

![screenshot from 2018-03-09 06-14-28](https://user-images.githubusercontent.com/3323703/37193345-4ac7cb7c-2361-11e8-8d50-d8cd04bdf5f2.png)

ping @alexwlchan - could you please post your screenshots here? Thx

**Comment by alexwlchan** [comment]
Here’s a couple more screenshots from our user testing session last Thursday:

![screen shot 2018-03-08 at 06 38 41](https://user-images.githubusercontent.com/301220/37368811-3318db96-26ff-11e8-965b-fd361080265d.png)

![screen shot 2018-03-08 at 07 13 39](https://user-images.githubusercontent.com/301220/37368821-3b061ada-26ff-11e8-9d06-e5a0315bd1b6.png)

![screen shot 2018-03-08 at 07 14 17](https://user-images.githubusercontent.com/301220/37368826-3d8d1ede-26ff-11e8-8b40-9bca2cda9dab.png)

![screen shot 2018-03-08 at 07 14 21](https://user-images.githubusercontent.com/301220/37368830-42e88ec2-26ff-11e8-97b7-979c4d0a9352.png)

**Comment by brainwane** [comment]
@nlhkabu About how hard is this to fix -- that is to say, do you think you can fix it this week? I'm trying to figure out when we are going to announce the beta.

**Comment by nlhkabu** [comment]
@brainwane - I'm a bit behind on this one.  Starting tonight.  I imagine we could have it merged by early next week.

**Comment by nlhkabu** [comment]
@brainwane - this is a little more complex than I initially thought.  PR is in progress, but probably won't get merged until next week.  To be clear, I don't think this needs to block publicising beta - the current solution we have *works* - just not for keyboard-only users.

**Comment by brainwane** [comment]
OK, thanks for the update @nlhkabu, moving to a later milestone!
