### ISSUE TITLE
Link to documentation goes nowhere

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3195]
On `/manage/project/<project>/release/<release>/` we have this documentation box:

![screenshot from 2018-03-09 06-21-12](https://user-images.githubusercontent.com/3323703/37193517-399910c6-2362-11e8-8fc0-a60d950ab346.png)

Currently, the URL is set to: `href="TODO"` :)

We need to find the appropriate documentation in the [Pyhon Packaging User Guide](https://packaging.python.org/) and link to it.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by brainwane** [comment]
The URL we should link to is: https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi
