### ISSUE TITLE
Improve links in management UI

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3196]
## Release page

on `/manage/project/<project>/releases/`, we link to `/manage/project/<project>/releases/<release>` in two places:

![screenshot from 2018-03-09 06-25-47](https://user-images.githubusercontent.com/3323703/37193709-f319f740-2362-11e8-84b1-dcc7231c3fa3.png)

![screenshot from 2018-03-09 06-25-56](https://user-images.githubusercontent.com/3323703/37193712-f358ce48-2362-11e8-825f-56e3bb36de16.png)

We should:

1. Change the 'edit' dropdown to say 'Manage'
2. Add a "Manage version" title to the version number link

## Release detail page

On the release detail page: `/manage/project/<project>/releases/<release>`:

![screenshot from 2018-03-09 06-25-38](https://user-images.githubusercontent.com/3323703/37193710-f336228a-2362-11e8-818f-2dccc4b47d27.png)

We should:

1. Add a "Download file" title to the download link
2. Restructure the HTML so that the link underline does not extend beyond the text (currently, the space between the text and the file size is underlined)

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by pgadige** [comment]
I'm working on this issue.  Does "title" refer to the corresponding anchor tag's `title` attribute?

**Comment by nlhkabu** [comment]
Yes it does @pgadige :)
