### ISSUE TITLE
Add confirmation modal when adding a new owner to a project

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3201]
Right now, the process for adding an owner to a project is pretty easy (maybe too easy) - just add user, select the dropdown value and click save.

I had feedback in user tests that it might be a good idea to add a confirmation modal process when adding a new **owner** (not maintainer) to a project.

The workflow would be something like this:

1. If the user clicks on either "add" or "save" with "owner" selected:

#### Add
![screenshot from 2018-03-09 07-08-42](https://user-images.githubusercontent.com/3323703/37194975-c83ab96e-2368-11e8-8a1c-638f87919181.png)

#### Save
![screenshot from 2018-03-09 07-08-55](https://user-images.githubusercontent.com/3323703/37194974-c8148a14-2368-11e8-9320-1278244a7984.png)

2. Show a modal asking for confirmation, e.g.

![screenshot from 2018-03-09 07-11-47](https://user-images.githubusercontent.com/3323703/37195050-269ef43e-2369-11e8-9f7a-87849fe6c680.png)

Bonus:

It would be nice to:

1. show the full name and gravatar in the modal
2. List the permissions the new owner will have in a `ul`

**Comment by nlhkabu** [comment]
I'm looking for feedback on this one:

1. does this add value
2. would this get too annoying?

**Comment by dstufft** [comment]
For comparison, Github doesn't require any sort of confirmation to add someone as a contributor to a repository. I don't think we need it either, you can undo the action pretty easily by just removing them after it's been done. Ideally I think these sorts of confirmations are best left for actions that cannot be undone.

**Comment by brainwane** [comment]
I think adding someone as an *owner* is pretty rare and does deserve an "are you sure? you could make them a maintainer instead" modal.

**Comment by dstufft** [comment]
I might be weird? I almost never use the maintainer role, if I trust someone enough to let them ship software in my name I generally trust them to also add maintainers too.

**Comment by di** [comment]
I agree w/ Donald, let's keep these confirmation dialogs just for destructive actions.

**Comment by nlhkabu** [comment]
Ok, this makes sense. Closing this issue. Will reopen if raised again in the future.  Thanks for your feedback :)
