### ISSUE TITLE
Extend documentation on project settings page

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3215]
From user testing:

It would be helpful if we could instruct users on how to update meta data associated with their project.  This is particularly true for cases where the old UI allowed updates (e.g. release summaries) but the new one does not.

Thanks to https://github.com/pypa/warehouse/pull/3169, we already have information about project links.
We should extend this to include other meta data (author name/email, classifiers, etc.)

@brainwane - would it be possible to make a list of all of the data a user can't edit via Warehouse?

Would it make sense to document this in Warehouse - or should we move it into the user guide and link to it from Warehouse?

cc @di for reference.

**Comment by di** [comment]
@brainwane already did this in #3177, I think.

**Comment by nlhkabu** [comment]
Aha! So she did! Closing this then - sorry for the noise :)
