### ISSUE TITLE
Warehouse needs a register page

### ISSUE THREAD

**Issue by toumorokoshi** [pypa/warehouse#322]
This is a proposal to add a register page to warehouse. The base functionality would mirror what's provided on the current pypi register page:

https://pypi.python.org/pypi?%3Aaction=register_form

**Comment by karan** [comment]
+1 to "Sign Up with Github".

**Comment by demianbrecht** [comment]
FWIW, having the ability to register an arbitrary authentication policy would be super helpful for those planning to adopt warehouse behind a corporate firewall and similar environments. In these cases, it might be helpful to be able to strip /all/ auth mechanisms other than some custom method.

**Comment by dstufft** [comment]
This should actually be completed now.
