### ISSUE TITLE
Add `required` attribute to input element in Request Password Reset page

### ISSUE THREAD

**Issue by waseem18** [pypa/warehouse#3223]
In [Request Password Reset](https://pypi.org/account/request-password-reset) page the input element doesn't have `required` attribute. Hitting `Request Password Reset` button with empty input sends a POST call and then adds `This field is required` message.
It's better to have a `required` attribute which marks the input as required.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: *If your pull request makes a visual change*, please include a screenshot of your update. This helps our team give you feedback faster.

**Comment by nlhkabu** [comment]
Thanks @waseem18 :)
