### ISSUE TITLE
License metadata seems to be ignored

### ISSUE THREAD

**Issue by pganssle** [pypa/warehouse#3225]
When I made the latest release of `python-dateutil`, it came along with a license change from BSD to Apache / BSD dual licensed.  I updated the `license=` metadata in `setup.py`, but I forgot to update the trove classifiers.

[The page on PyPI](https://pypi.python.org/pypi/python-dateutil/2.7.0) shows the license as "Apache 2.0" as I would expect. [The page on warehouse](https://pypi.org/project/python-dateutil/) shows the license as "BSD License". I'm assuming it's pulling that from the trove classifier? Shouldn't it pull it from the `license` field if that is populated?

**Comment by di** [comment]
Thanks for raising @pganssle, this was indeed a small bug with the way we were handling the presence of licenses in both the [`Classifier` field](https://packaging.python.org/specifications/core-metadata/#classifier-multiple-use) and the [`License` field](https://packaging.python.org/specifications/core-metadata/#license-optional).

Based on the specification above, I would suggest the following `setup.py` for future releases:

```python
setup(
    ...
    classifiers=[
        ....
        'License :: OSI Approved :: BSD License',
        'License :: OSI Approved :: Apache Software License',
        ....
    ],
    license = 'Dual License'
    ...
)
```

Which will show up on pypi.org as:

> License: BSD License, Apache Software License (Dual License)

Also, in #pypa on IRC you said: 

> Did I screw this up? https://test.pypi.org/project/python-dateutil/
> I'm listed as Author.
> But setup.py has me as maintainer: https://github.com/dateutil/dateutil/blob/master/setup.py#L33

But looking at the metadata for the 2.7.0 source distribution, all I'm seeing is:

```
Author: Paul Ganssle
Author-email: dateutil@python.org
```

which leads me to think that this was changed after you made the distribution file, but let me know if you're still having issues with it.

**Comment by dstufft** [comment]
I think distutils or maybe setuptools has a bug where if you specify a maintainer it sets that as the author in the metadata.

**Comment by pganssle** [comment]
@di Thanks for the response. I updated the trove classifiers, I think your idea of changing `license=` to **Dual License** is a good idea, I'll do that shortly.

With regards to the maintainer/author thing, I've opened an issue about it: pypa/setuptools#1288, I'm also going to open one for distutils.

**Comment by di** [comment]
Yeah, that seems like a bug. Warehouse will correctly handle the presence of any or all of the Author/Maintainer metadata fields, if they're correctly provided.
