### ISSUE TITLE
Project description displaying UNKNOWN after release update

### ISSUE THREAD

**Issue by willingc** [pypa/warehouse#3229]
Howdy folks. We just uploaded a jupyter_client release update. The project description classifier is still displaying UNKNOWN. Other classifiers such as the Links section updated beautifully (thanks!). Not sure if this is a configuration error on our part or an issue. There's a screenshot below and a link to the line in our `setup.py` source.

<img width="1406" alt="screen shot 2018-03-12 at 9 19 57 am" src="https://user-images.githubusercontent.com/2680980/37296178-64727ee6-25d7-11e8-8649-89ceff102206.png">

https://github.com/jupyter/jupyter_client/blob/master/setup.py#L63

**Comment by dstufft** [comment]
It is confusingly named, but ``description`` is the summary you see in the grey area up above. The field you're looking at is ``long_description`` in ``setup.py``.

**Comment by willingc** [comment]
Thanks @dstufft. That makes complete sense now. I'll reread the docs and see if I can submit a PR to clarify.

**Comment by brainwane** [comment]
Thanks, @willingc. Quick question -- as a PyPI package maintainer, where would you expect to see some helpful text about how to define what goes in those different areas of the page?

**Comment by willingc** [comment]
@brainwane I opened a PR where I would have found it helpful. https://github.com/pypa/python-packaging-user-guide/pull/456 :smile:
