### ISSUE TITLE
Header sits on top of anchors

### ISSUE THREAD

**Issue by alex** [pypa/warehouse#323]
If you click the setuptools "3.8" link, for example, the warehouse header bar is on top of the content: https://warehouse.python.org/project/setuptools/#id1

**Comment by dstufft** [comment]
I'm going to close this, I've started porting Warehouse over to Pyramid to ease the concerns of the custom framework-ish thing I've got going on here. That work is now on the master branch inside this repository. That work does not currently have this problem.
