### ISSUE TITLE
PyPI says it's down

### ISSUE THREAD

**Issue by jakirkham** [pypa/warehouse#3247]
Tried to download an sdist from PyPI and got a `HTTP 503 BACKEND IS UNHEALTHY` error message. Then tried to visit the website and got this.

<img width="1552" alt="screen shot 2018-03-13 at 23 07 40" src="https://user-images.githubusercontent.com/3019665/37381405-5bf33eda-2713-11e8-8ec1-b622f402d492.png">

**Comment by jakirkham** [comment]
Here's a [CI log]( https://circleci.com/gh/conda-forge/pykwalify-feedstock/35 ) showing the 503 error message. Also seeing this locally.

**Comment by brainwane** [comment]
Thanks, @jakirkham. I'm seeing it up for me right now, and https://downforeveryoneorjustme.com/pypi.org says it's up, and https://status.python.org/ looks mostly good too -- I do see a couple 503s just now, which may be the ones served to you. And I can `wget https://pypi.io/packages/source/p/pykwalify/pykwalify-1.6.1.tar.gz` just fine. Are you still getting a 503? On pypi.io as well as pypi.org?

**Comment by jakirkham** [comment]
Yep, now seems good. Thanks. :)

**Comment by di** [comment]
@ewdurbin Is this `conveyor` acting up?

@jakirkham Any reason you're using the `pypi.io` domain and not `pypi.org`?

**Comment by jakirkham** [comment]
I tried both. That just happened to be the one that was in the screenshot.

**Comment by ewdurbin** [comment]
This was a temporary failure due to scaling the conveyor deploy down significantly on accident, whoops.
