### ISSUE TITLE
Pressing Esc key should close modals

### ISSUE THREAD

**Issue by waseem18** [pypa/warehouse#3248]
Right now clicking on `x` icon present on the top-right of the modal is the only way to close it.

Ideally the modal would also be closed when the user presses their `Esc` key.

**Comment by di** [comment]
Revised this to be more clear that this is about closing the modal when the user presses the `ESC` key on their keyboard.

**Comment by jMuzsik** [comment]
Hi, it's cool I work on this? 

I can continue working on first issues as well. Open to whatever. Any issues you'd recommend?

But as for this one, are there keywords that I can use to assure that I find each modal? As in, do they all have a class of `modal` or will this demand going through the site and finding each instance of a modal? If that is so, do you mind pointing me to a few to start? 

Thanks!

**Comment by di** [comment]
@jMuzsik Absolutely! If you feel comfortable moving on from the "good first issues" then feel free. This would be a good one.

All the modals are created with this macro, so you should only have to change it once: https://github.com/pypa/warehouse/blob/fe7d676886a58a3500afe40181595ec4d50f0f51/warehouse/templates/manage/manage_base.html#L61-L93

**Comment by jMuzsik** [comment]
I can work on #3198 at the same time because it is in the exact same place, sounds good?

**Comment by di** [comment]
Fixed in #3392.
