### ISSUE TITLE
[RFC] can the project main page can support markdown ?

### ISSUE THREAD

**Issue by netroby** [pypa/warehouse#3249]
Hello , dear develop community.

Can we support markdown at the project home page?

https://pypi.org/project/py-cn-phone-area-code/

I want put very simple example to show user how to play with my lib.

**Comment by brainwane** [comment]
Hi, @netroby.

We're working on supporting Markdown, but we don't have it yet. My colleague Dustin is working on several tasks that need to all be completed before you can have Markdown in your project's main PyPI page. https://github.com/pypa/warehouse/issues/869#issuecomment-340928703 is the comment where he lists out those tasks. You can subscribe to that issue on GitHub to get a notification when it's fixed and resolved.

https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi may help you -- also, you might like to use [pandoc](http://pandoc.org/) so you can write Markdown and then turn it into reStructuredText for the README.

Best wishes. I'm closing this as a duplicate, but thank you for sharing your needs, and for using PyPI.
