### ISSUE TITLE
Email notification for demoted/removed user

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3264]
Followup to #1000: we should email the user (and possibly all the other owners/maintainers of a project as well) when they were an owner/maintainer of a project but have just been demoted or removed from the project.

> if a user is removed from a [maintainer or owner] role, then that user should also be emailed (e.g., to prevent an attacker who has compromised one owner, from silently removing other owners of a package, prior to uploading a new malicious package, thereby circumventing #997).

-- @edmorley

**Comment by brainwane** [comment]
To do this the right way, we should wait till we have #5863 implemented, so we can draw on the event logging and use it to trigger this notification.

**Comment by rascalking** [comment]
I finally got the code in #3853 rebased on master, and am looking at driving the notifications from the event logging.  I don't see any triggers or signal plumbing in #6339.  When you say the event logging should trigger the notification, are you talking about calling these notifications directly from `Project.record_event` and `User.record_event`?  Or are you looking for us to use the db signals to watch for `UserEvent` objects being created?

**Comment by brainwane** [comment]
I defer to @di and @ewdurbin and @yeraydiazdiaz on this.

**Comment by brainwane** [comment]
@di do you have some feedback on @rascalking's question?

**Comment by di** [comment]
I think either could work. I think it would be probably more straightforward to just do this in `*.record_event`, and probably more thorough to hook into `ProjectEvent`/`UserEvent` object creation.

I think what would be even more powerful is if every `Event` was published to our task queue, and for every individual type of event, there was a way to resolve asynchronous actions that should happen as a result of that event, like sending an email. That's a bit more than what we're asking for here right now though.

**Comment by di** [comment]
@rascalking Any updates here? Are you still working on this?

**Comment by rascalking** [comment]
Sorry, I don't think I'm going to be able to finish this.

**Comment by brainwane** [comment]
Thank you, @patelneel55!
