### ISSUE TITLE
Make 'manage' and 'view' buttons align right

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3266]
In the list of packages for logged in users, we show 'manage' and 'view' buttons:

![screenshot from 2018-03-15 07-13-18](https://user-images.githubusercontent.com/3323703/37448973-6dc42d82-2820-11e8-868e-e42f43d9d101.png)

Right now, there is an approx 20px gap at the right of the 'view' button. It would be better if these could align *right* in the card.

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, please include a screenshot in your Pull Request.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by saxenanurag** [comment]
<img width="916" alt="screen shot 2018-03-24 at 21 28 08" src="https://user-images.githubusercontent.com/1815699/37870736-b54d684e-2faa-11e8-8883-eaf3e3f0da25.png">

Is this what you are looking for?

**Comment by nlhkabu** [comment]
perfect @saxenanurag !
