### ISSUE TITLE
Cosmetic bug: link underline extends into whitespace

### ISSUE THREAD

**Issue by alexwlchan** [pypa/warehouse#3274]
I grabbed this screenshot in user testing last week – I’ve forgotten the context, but I think it was in the list of files on a release page. Nitpicky detail: the link underline should really stop at `.gz`, and not continue into the space.

![screen shot 2018-03-08 at 06 53 45](https://user-images.githubusercontent.com/301220/37491494-f8367482-2895-11e8-9a9d-ead9e2d7962c.png)

I suspect this is just a whitespace tweak in `release.html`; I'd fix it myself, but I don't have time right now.

**Comment by di** [comment]
Thanks @alexwlchan!

**Comment by varunotelli** [comment]
I'd like to work on this issue.

**Comment by nlhkabu** [comment]
Hi @alexwlchan - thanks for opening this.  This issue is covered in https://github.com/pypa/warehouse/issues/3196 - are you happy for me to close this?

**Comment by alexwlchan** [comment]
Ah, I missed it!
