### ISSUE TITLE
Consistency issues when mirroring pypi.python.org

### ISSUE THREAD

**Issue by Alphadelta14** [pypa/warehouse#3276]
We run a local artifactory cluster, and when trying to update some packages, we are getting empty lists from the remote pypi.python.org.
I noticed that https://status.python.org/ says there is a migration in progress, but this is affecting our CI every couple of minutes with various packages.

```
17:30:15   Could not find a version that satisfies the requirement sh==1.12.13 (from -r base.txt (line 47)) (from versions: )
...
17:33:57   Could not find a version that satisfies the requirement virtualenv==15.1 (from -r /tmp/rpm_workspace/rpmbuild/BUILD/dependencies/runtime-base/pip-external.txt (line 7)) (from versions: )
```

**Comment by ewdurbin** [comment]
dupe #3275 let's collect issues related to artifactory there.
