### ISSUE TITLE
Warehouse file order differs from legacy PyPI file list

### ISSUE THREAD

**Issue by clintharrison** [pypa/warehouse#3284]
Tonight, while load testing of pypi.org was ongoing, we saw some failures in automated systems that use `--require-hashes` with `pip install`, as ordering on the package file list page changed.

The specific package we saw break was `pandas` at version `0.12.0`. We had a single hash for `pandas-0.12.0.tar.gz`. A few of our hosts were served from the legacy PyPI service, which succeeded as normal. The Warehouse endpoint, however, failed, since `pandas-0.12.0.zip` now preceded `pandas-0.12.0.tar.gz` in the file list.

At the moment, you can see that https://pypi.org/simple/pandas/ and https://pypi.python.org/simple/pandas/ differ by searching for `pandas-0.12.0.tar.gz` and `pandas-0.12.0.zip` and comparing the position.

**Comment by di** [comment]
Could you tell us what version of `pip` was used, and if you were using an intermediary or mirrored index? The order of the distributions shouldn't cause an issue.

**Comment by clintharrison** [comment]
We were using `pip` version 9.0.1 with no explicit index specified, so the default `https://pypi.python.org/simple`.

I can reproduce this currently with a local Python 2.7 install:
```
$ pip --version
pip 9.0.1
```
```
$ pip install --index-url https://pypi.python.org/simple pandas==0.12.0
Collecting pandas==0.12.0
  Downloading pandas-0.12.0.tar.gz (3.2MB)
```
```
$ pip install --index-url https://pypi.org/simple pandas==0.12.0
Collecting pandas==0.12.0
  Downloading https://files.pythonhosted.org/packages/49/32/61120c7350105faa1533211fe3226ca6e71cd08a50e6e137e0baee50d186/pandas-0.12.0.zip (3.4MB)
```

From a cursory look at [_link_package_versions()](https://github.com/pypa/pip/blob/9.0.1/pip/index.py#L605) it seems that the ordering between `.zip` and `.tar.gz` ultimately does come down to the order on the links page.

**Comment by dstufft** [comment]
Yea, pip respects the order files are given to it by the index as the final tie breaker when it sorts files, so the order in ``/simple/`` can change what file gets installed.

**Comment by di** [comment]
@clintharrison Is there a reason why you need to install from a `.tar.gz` and not `.zip`? If not, I would recommend adding hashes for both source distributions for that release. Newer releases are no longer allowed to have multiple types of sdists so this shouldn't be a problem moving forward.

However #3292 will "fix" this behavior so that `.tar.gz` sdists will come before `.zips`, so you shouldn't actually have to do anything to resolve this.

**Comment by di** [comment]
Also thanks for the report @clintharrison!

**Comment by clintharrison** [comment]
@di thank you for the quick fix! There was no particular reason, simply an oversight on our side, not realizing that there existed both sdists. We have since added both hashes and using the Warehouse served simple index worked just fine 💯
