### ISSUE TITLE
Hard fail on invalid markup with explicit description type

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#3285]
When we're given an explicit description type (Markdown, Rst, etc) we should attempt to render it during upload, and if it's invalid then we should hard fail the upload.

**Comment by di** [comment]
I think this is only really applicable for reStructuredText, the markdown renderer will always return something even if it's not perfectly valid markdown (or even if it isn't actually markdown all).

**Comment by dstufft** [comment]
Even if those renders always pass i think there is till value in doing it. For example it’s catch errors in cleaning the html as well. The general idea is that people semi regularly hit broken readme and avoiding that up front seems like a net positive.

**Comment by konstin** [comment]
It would be very valuable if any rendering error would at least be reported in the history tab; Currently it's hard to understand why the project description is suddenly displayed in plain text instead of rst.

**Comment by di** [comment]
Fixed in #5835.
