### ISSUE TITLE
Project badges service

### ISSUE THREAD

**Issue by oberstet** [pypa/warehouse#330]
For Python projects, it can be nice to have "badges" (small images, like Travis etc) with package downloads per month on their homepage. This informs and attracts new users.

There is a service for that: https://pypip.in

E.g. https://pypip.in/download/autobahn/badge.png

However, the service isn't terrible stable (right now, it's broken). And it would be nice if PyPI itself would provide such a service.

The numbers presented should be exactly the same regardless of source:
- PyPI project page
- badge rendering service
- PyPI API

The image should be available in two formats:
- png
- svg

**Comment by szepeviktor** [comment]
@oberstet Please see https://github.com/pypa/pypi-legacy/issues/513

**Comment by timcera** [comment]
pypip.in hasn't worked for awhile.

What I have been using is http://shields.io/

Regardless, the download counts don't work right now at pypi.org or pypi.python.org.

**Comment by jab** [comment]
Maybe this can be closed in preference to a solution based on #787 (which I just upvoted 😊) and shields.io? @brainwane et al.

**Comment by di** [comment]
Agreed. It is not likely that PyPI will ever have such a service, however it is likely that we will ship #787 and services like shields.io will once again be able to provide badges for download counts.

Closing this, but thanks to @oberstet for the feature request and identifying the need (and thanks to @jab for pointing out the alternative).
