### ISSUE TITLE
Claiming package name

### ISSUE THREAD

**Issue by x3medima17** [pypa/warehouse#3312]
We are core team of the [iroha](https://github.com/hyperledger/iroha) project. Today I tried to upload a package to PyPI, and `iroha` name was already occupied, somebody uploaded our package there and now we don't have any write permissions. 
What can we do to reobtain the access?
Thank you!

**Comment by brainwane** [comment]
Hi, @x3medima17. I see that [there's a PyPI project for `iroha`](https://pypi.org/project/iroha/#history). If I understand you correctly, [user account `iroha-pypi`](https://pypi.org/user/iroha-pypi/) is some person or group other than you, and they uploaded an `iroha` project on PyPI. Is that right? You mention that you'd like to "reobtain" the access; did you previously have a package uploaded for `iroha`, or did the `iroha-pypi` account create the first upload for that PyPI project?

(potentially a [PEP 541](https://www.python.org/dev/peps/pep-0541/) situation)

**Comment by brainwane** [comment]
@x3medima17 I looked at https://github.com/hyperledger/iroha/pull/936/files . I think `iroha-pypi` *is you* and you should [do a pypi.org password reset](https://pypi.org/account/request-password-reset/) and see if that helps you sort this out.

**Comment by x3medima17** [comment]
@brainwane I wish it was me, but actually we were not fast enough to occupy the name, because we planned to upload it after our next release.
I have been testing our lib on [](https://testpypi.python.org/pypi)

**Comment by di** [comment]
@x3medima17 The email address for the `iroha-pypi` account is on [your maintainers list](https://github.com/hyperledger/iroha/blob/master/MAINTAINERS.md) and corresponds with @satelliteyes, have you checked with them?

**Comment by x3medima17** [comment]
@di We have written a letter to our community. Yeah, one of them had registered as `iroha-pypi`, now he gave us all account details!
Thank you for quick response!

**Comment by ewdurbin** [comment]
@x3medima17 can you confirm that you've gotten what you need?

**Comment by brainwane** [comment]
@x3medima17 I am assuming you have this taken care of. Please reopen if I am wrong. :) And thank you for using PyPI!
