### ISSUE TITLE
Support CORS on JSON API

### ISSUE THREAD

**Issue by oberstet** [pypa/warehouse#333]
Say I want to show project stats like monthly downloads on the project page. Fetching this from client side JavaScript allows me to retain a completely static project page (can be hosted on a CDN).

However, the JSON API does not set `Access-Control-Allow-Origin` header - no CORS support.

Test:
https://github.com/oberstet/scratchbox/blob/master/js/badges/pypi.html

For comparison, this is what GitHub does with it's API:
https://github.com/oberstet/scratchbox/blob/master/js/badges/github.html

If above would work, that makes #330 void (for me) - if the API doesn't get rate limited or such ..

**Comment by oberstet** [comment]
Still fails for me: "XMLHttpRequest cannot load https://pypi.python.org/PyPI/autobahn/json. Request header field Content-type is not allowed by Access-Control-Allow-Headers."

**Comment by dstufft** [comment]
Hrmph. Ok

**Comment by dstufft** [comment]
I'll add more headers to that then :)

**Comment by oberstet** [comment]
Thanks!

**Comment by oberstet** [comment]
The HTML here https://github.com/oberstet/scratchbox/blob/master/js/badges/pypi.html demonstrates the issue ..

**Comment by dstufft** [comment]
I took a look at your file, and if I edited out ``req.setRequestHeader("Content-type", "application/json; charset=utf-8");`` it worked fine. You're not sending a body along so there's no real reason to set a ``Content-Type`` on the request is there?
