### ISSUE TITLE
Markdown codeblocks have extra styling

### ISSUE THREAD

**Issue by di** [pypa/warehouse#3330]
E.g. for https://pypi.org/project/pip-upgrade-outdated/1.0b3/

<img width="812" alt="screen shot 2018-03-21 at 11 07 05 am" src="https://user-images.githubusercontent.com/294415/37721637-096019dc-2cf8-11e8-9a24-620a28503756.png">

@nlhkabu Let me know if need to be able to reproduce this in dev.

**Comment by nlhkabu** [comment]
thanks @di.  Yes, I can't seem to find a project on dev with this issue.  Could you please help me to reproduce?  Thanks! :)

**Comment by di** [comment]
OK, you'll need to upload the following file to your local dev instance of Warehouse with Twine, there's instructions here: https://warehouse.readthedocs.io/development/reviewing-patches/#testing-with-twine

[pip_upgrade_outdated-1.0b3.tar.gz](https://github.com/pypa/warehouse/files/1836425/pip_upgrade_outdated-1.0b3.tar.gz)
