### ISSUE TITLE
make (some?) email templates noreply

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3331]
Warehouse sends automated email notifications (`warehouse/templates/email/`). Most should be noreply and we should update the FROM address, headers, and body accordingly, including text about replying to PyPI admins.

Nice-to-have: change the email address based on what project we're emailing about, as GitHub does (example: `pip@noreply.pypi.org`). 

(Future plans: Once we have #3231 we'll be updating the email templates again, ideally so people can reply to the emails to start a support ticket. But let's not block on that.)

@ewdurbin is this something a volunteer can help with, or is it something that really requires current PyPI admins' expertise, in which case we should take off the `help needed` label?

**Comment by di** [comment]
I think _all_ notification emails should be `noreply`, and the notice at the bottom of them should be changed to encourage folks to send a separate email to `admins@` rather than replying.

> Nice-to-have: change the email address based on what project we're emailing about, as GitHub does (example: pip@noreply.pypi.org).

We should make this a separate issue.

> @ewdurbin is this something a volunteer can help with, or is it something that really requires current PyPI admins' expertise, in which case we should take off the help needed label?

Once @ewdurbin sets up the `noreply` address, this is something a volunteer could do.

**Comment by chriskuehl** [comment]
I got an email today:

```
From: PyPI <noreply@pypi.org>
To: ckuehl <(my address)>
Subject: [PyPI] Collaborator added notification

You have been added as Owner to the PyPI project (project) by (owner).

Congratulations!

If this was a mistake, you can reply to this email directly to communicate with
the PyPI administrators.
```

Unsure if the `noreply@pypi.org` address is actually monitored, but definitely seems weird to be told I can reply to this email directly, when that would mean emailing `noreply@` :)

**Comment by dstufft** [comment]
We're sending all emails from a ``noreply@{test.}pypi.org`` address, and the templates have recently been updated to remove the mention about replying to the email. I don't think there's anything else to do on this ticket, so closing it!
