### ISSUE TITLE
Unnecessary purges on `User` model change

### ISSUE THREAD

**Issue by di** [pypa/warehouse#3336]
Currently right now any time the `User` model changes, we purge all the cache keys for that user's project.

This includes attribute changes that don't actually affect the project pages, like `last_login`, `password` etc.

We should filter out "purge-able" attribute changes and only issue purges when necessary. Said attributes include:
* `username`
* `name`
* `emails`

**Comment by ewdurbin** [comment]
it also issues an `all-projects` which purges `/simple`

**Comment by di** [comment]
Hmm, shouldn't be...

**Comment by ewdurbin** [comment]
my bad, sneaky edited my original comment after checking logs more closely.

**Comment by brainwane** [comment]
Ernest mentioned we need this before launching beta, because otherwise it's so costly to serve users who have many projects each.
