### ISSUE TITLE
font-family declaration missing alternative fonts

### ISSUE THREAD

**Issue by jodal** [pypa/warehouse#337]
https://warehouse.python.org seems to use the following CSS font-family declaration:

``` css
font-family: "Gotham Narrow SSm A","Gotham Narrow SSm B";
```

This font is not available in Chrome on Linux, and the declaration does not list any alternatives, or even "sans-serif" as the type of font. As a result, the page is rendered with the default serif font.

**Comment by dstufft** [comment]
I'm going to close this, the problem no longer exists on the master branch, and when that's ready to be deployed it'll update on warehouse.python.org.
