### ISSUE TITLE
notification bars no longer stack on load

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3380]
When the page loads, the 'sticky' notification bar completely covers the donation bar:

![screenshot from 2018-03-23 06-41-37](https://user-images.githubusercontent.com/3323703/37815076-4c3fda4e-2e65-11e8-8063-9c78bba2368b.png)

If you resize the browser, the display reverts back to what it should be:

![screenshot from 2018-03-23 06-41-30](https://user-images.githubusercontent.com/3323703/37815077-4c6298c2-2e65-11e8-9973-fe394c84d8e6.png)

IIRC, the sticky bar works by calculating the height of all sticky notifications and then adding this padding to the body:

![screenshot from 2018-03-23 06-45-08](https://user-images.githubusercontent.com/3323703/37815182-c5510b9c-2e65-11e8-84d2-e16a52e5f616.png)

This seems to be working fine when the page is resized, but not on load

**Comment by di** [comment]
This might be because dismissable notifications briefly are hidden on load, we probably need to move whatever is figuring out the height to later in the page render.

**Comment by jMuzsik** [comment]
Actually, I do not know how to replicate this behavior. As, `The actual content for this include is defined in pypi-theme`, the include of the `warning-banner.html` so i'll work on something else unless there is someway to replicate it elsewhere.

**Comment by di** [comment]
@jMuzsik Yeah, since `pypi-theme` is a private repo, this will likely be something one of us needs to debug. Thanks for taking a look at it though!
