### ISSUE TITLE
tab index incorrect on `manage/account/`

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3381]
When tabbing through `/manage/account` I noticed that the tab index is incorrect.  This is because we're setting a custom tab order on the login page, then reusing the code elsewhere.

We should audit all of the pages where password fields appear and make sure that the tab index makes sense.  Where appropriate, we should also consider adding autofocus to the first field.

### Pages to review (post comments below)

- [x] Login page 
- [x] Registration page
- [ ] Reset password page (in reset password workflow)
- [ ] Manage account page (when logged in)

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by nlhkabu** [comment]
## Registration page

This page is ok, but would be better if:

1. the 'name' field was focused on load
2. the 'show password' checkbox came *after* the password fields and register button in the tab order

**Comment by cheungnj** [comment]
I'd like to work on this.
