### ISSUE TITLE
Missing Purges

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#3383]
Noticed this while setting up new mirror. We don't seem to be purging `project/<normalized_name>` key when projects are deleted.

This leads bandersnatch to get confused and fall behind until the key is purged so the JSON api returns a 404

**Comment by ewdurbin** [comment]
Also appears to miss purges due to maintainership changes and _pypi_hidden (legacy) changes.

**Comment by dstufft** [comment]
Legacy doesn't purge Warehouse at all

**Comment by dstufft** [comment]
fine with me, pypi_hidden is useless in warehouse anyways.

**Comment by ewdurbin** [comment]
👍

**Comment by ewdurbin** [comment]
pypi-legacy interference resolved in https://github.com/pypa/pypi-legacy/pull/785

Still need maintainer changes to purge `project/` keys though.

**Comment by di** [comment]
Should just require adding:
```
    config.register_origin_cache_keys(
         Role,
         purge_keys=[
             key_factory("user/{obj.user.username}"),
             key_factory("project/{obj.project.normalized_name}")
         ],
     )
```
