### ISSUE TITLE
Add owner to pypi package 'infrared'

### ISSUE THREAD

**Issue by iranzo** [pypa/warehouse#3384]
Hi,
Our colleague Yair forgot the password used for pypi package and as he moved to another company he cannot also reset the password.

What is the procedure to recover control over the package so that we can add new versions to it?

Thanks!
Pablo

**Comment by di** [comment]
@iranzo What's the PyPI account and package in question?

**Comment by iranzo** [comment]
Hi @di !

yfried is the user, and yfried@redhat (.com) was the email. (https://pypi.org/user/yfried/) 

Project is Infrared at: https://pypi.org/project/infrared/ and as listed in the Author, the project email associated is rhos-infrared@redhat (.com)

Project repo is at: https://github.com/redhat-openstack/infrared 

My colleague @ovorobio was trying to upload new version and is when the issue was discovered

(mine, just in case is iranzo) (https://pypi.org/user/iranzo/)

**Comment by di** [comment]
@iranzo So the project will still be owned/maintained by Redhat, correct?

Would it be possible to send me an email at `di@di.codes` from `rhos-infrared@redhat.com`?

**Comment by iranzo** [comment]
Emailed via @redhat email rhos-infrared is a mailing list for project

**Comment by di** [comment]
This should be resolved, @iranzo is now an owner of https://pypi.org/project/infrared/.
