### ISSUE TITLE
Redirect load testing issues.

### ISSUE THREAD

**Issue by sentania** [pypa/warehouse#3394]
From a RHEL 7.4 system with pip 9.0.1 I am receiving invalid certificate issues that began this afternoon

Edit: The example below was with pip 8.1.2, but I received on a similar system with pip 9.0.1 installed.

It began around 4 PM CT:
msg": "stdout: Collecting pexpect\n  Could not fetch URL https://pypi.python.org/simple/pexpect/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579) - skipping\n\n:stderr:   Could not find a version that satisfies the requirement pexpect (from versions: )\nNo matching distribution found for pexpect\nYou are using pip version 8.1.2, however version 9.0.3 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"

This was in the middle of deploying a large batch of servers, the first 11 worked, 12th and all subsequent failed due to this.

**Comment by ewdurbin** [comment]
@sentania can you provide the output of 

```
openssl s_client -connect pypi.org:443
```

from an affected server?

**Comment by ewdurbin** [comment]
also:

```
openssl s_client -connect pypi.python.org:443
```
and
```
openssl s_client -connect files.pythonhosted.org:443
```
please.

**Comment by ewdurbin** [comment]
@sentania is there an HTTP proxy involved? we had a similar report in #3395 that turned out to be a proxy configuration.

**Comment by sentania** [comment]
There is a Palo in the middle doing filtering/ssl cracking/etc.

I will get the output of those commands later if the testing is still happening

**Comment by ewdurbin** [comment]
Thanks @sentania, you'll need to configure your proxy (what I assume "Palo" is) to appropriately handle the domains:

pypi.python.org
pypi.org
files.pythonhosted.org

**Comment by sentania** [comment]
We've been good since the testing seems to have wrapped up.  Thanks for the feedback.
