### ISSUE TITLE
Load testing related to issues with python get-pip.py

### ISSUE THREAD

**Issue by khabbabs** [pypa/warehouse#3395]
Trying to install pip with python get-pip.py script and getting weird errors which I wasn't getting several hours ago. 

Collecting pip
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)': /simple/pip/
  Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)) - skipping
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip

any help would be greatly appreciated. 

Thanks

**Comment by ewdurbin** [comment]
@khabbabs can you provide the output of:

```
openssl s_client -connect pypi.org:443
```

**Comment by ewdurbin** [comment]
also:

```
openssl s_client -connect pypi.python.org:443
```
and

```
openssl s_client -connect files.pythonhosted.org:443
```
please.

**Comment by khabbabs** [comment]
Hey sorry just found an error with my proxy settings. Apologies for creating a useless issue.

regards,
Khabbabs

**Comment by nadendla-sandeep** [comment]
what had  you done to overcome that issue
