### ISSUE TITLE
Package pages should have clear install instructions

### ISSUE THREAD

**Issue by hickford** [pypa/warehouse#340]
(repost from  https://github.com/pypa/packaging-problems/issues/47 )

Package pages on Warehouse should have clear `pip install` instructions to help users. At the moment https://warehouse.python.org/project/MechanicalSoup/ (say) has only a list of downloads. Many Python users wouldn't know what to do with a `.whl` or `.tar.gz`.

Package managers for other languages show install instructions in large friendly letters:

* https://www.npmjs.org/package/express
* https://rubygems.org/gems/rails

Npm actually puts the instruction eg. `npm install express` at the top of the page. It's probably the most important line there.

**Comment by nlhkabu** [comment]
Addressed in the new UI.
