### ISSUE TITLE
Nit: change the color of the warning banner

### ISSUE THREAD

**Issue by ambv** [pypa/warehouse#3426]
Now that the project is in beta (congratulations!), we no longer need *BIG SCARY WARNINGS*. Instead, pastel yellow would be clear enough without being a distraction anymore. It would also compose with the blue of the theme to form the Pythonic colors 😄

I realize this is a nit but I hope since this is trivial enough to implement, it's not too much to ask.

**Comment by brainwane** [comment]
@nlhkabu I defer to your thoughts here!

Thank you @ambv for your suggestion.

**Comment by brainwane** [comment]
Thanks again @ambv!
