### ISSUE TITLE
Remove X-Forwarded-Proto/X-Forwarded-Port h2o workaround

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3428]
[In `warehouse/utils/wsgi.py`](https://github.com/pypa/warehouse/blob/master/warehouse/utils/wsgi.py#L51-L58) we note that once https://github.com/h2o/h2o/issues/883 is solved, we can remove a few lines about `X-Forwarded-Port` and `X-Forwarded-Proto`. They resolved that issue in May 2016 and [have released several new versions since then](https://h2o.examp1e.net/). OK to remove workaround?

Followup to b8b9f385382cd659750c694cf8b1b3db6f1f6d35 .

**Comment by dstufft** [comment]
We don't even use h2o anymore, so it can just be removed I think
