### ISSUE TITLE
Way to populate with a bunch of real data?

### ISSUE THREAD

**Issue by msabramo** [pypa/warehouse#343]
Is there a way to download a SQL dump with a bunch of real world package data?

It doesn't need to be the whole of PyPI but maybe a few thousand records for top downloaded packages?

**Comment by msabramo** [comment]
I think @dstufft said that he didn't want to do a fake backend (storage abstraction)?

In that case, can we get the database dump then?

**Comment by msabramo** [comment]
How about a smallish SQL dump?

**Comment by msabramo** [comment]
If I had a bit of data, I might be able to do a bit of work on the pyramid branch.

**Comment by dstufft** [comment]
This is on my TODO list, I just have to sit down and sanitize some data to ensure there is no PII in it.
