### ISSUE TITLE
Improved error message when attempting upload to Warehouse via twine with an invalid trove classifier

### ISSUE THREAD

**Issue by bskinn** [pypa/warehouse#3430]
I just now uploaded a new release to PyPI. Initially, I had made a typo in one of my trove classifiers (`Topic :: Testing` instead of `Topic :: Software Development :: Testing`).

The error returned by `twine` when I attempted to upload to Warehouse was mostly unhelpful, other than indicating something was wrong with my classifiers:

```
HTTPError: 400 Client Error: ['License :: OSI Approved :: MIT License', 'Natural Language :: English', 'Intended Audience :: Developers', 'Operating System :: OS Independent', 'Programming Language :: Python :: 3 :: Only', 'Programming Language :: Python :: 3.4', 'Programming Languag for url: https://upload.pypi.org/legacy/
```

The error returned by `twine` when I attempted an upload to `testpypi`, though, pointed me (eventually) to the problematic classifier:

```
HTTPError: 400 Client Error: ['License :: OSI Approved :: MIT License', 'Natural Language :: English', 'Intended Audience :: Developers', 'Operating System :: OS Independent', 'Programming Language :: Python :: 3 :: Only', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'Topic :: Software Development :: Libraries :: Python Modules', 'Topic :: Testing', 'Development Status :: 4 - Beta'] is an invalid value for Classifier. Error: 'Topic :: Testing' is not a valid choice for this field see https://packaging.python.org/specifications/core-metadata for url: https://test.pypi.org/legacy/
```

A more succinct, targeted error message here would be hugely helpful.

FWIW, it almost looks like Warehouse tried to generate the same message as legacy, but it got clipped?

**Comment by ewdurbin** [comment]
https://github.com/pypa/warehouse/blob/e7bacffd8bb505b3811750f3b4e366ab1b3d157d/warehouse/forklift/legacy.py#L415-L417 is the field we'd need to update. I _think_ we could improve the error message with a custom validator?

**Comment by brainwane** [comment]
Thanks, @bskinn. I just want to make sure -- are you saying this is a regression and worse behavior, compared to legacy PyPI?

**Comment by bskinn** [comment]
@brainwane Yes, it appears to be a regression -- with legacy PyPI, the full error message was echoed to console, and so I was at least able to immediately see the offending classifier, even if I had to stare at it for a bit to find the relevant part, at the end.

**Comment by bskinn** [comment]
Thanks much, @di!

**Comment by di** [comment]
Thanks for the report @bskinn!

**Comment by yanivmm** [comment]
Hi
Have you able to solve the problem?

**Comment by di** [comment]
Hi @yanivmm, if you're having problems please open a [new issue](https://github.com/pypa/warehouse/issues/new/choose).
