### ISSUE TITLE
Rename color variables to make more sense

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3435]
To be done after https://github.com/pypa/warehouse/pull/3433 is merged.

1. Rename `primary-color` to `highlight-color`
2. Rename `brand-color` to `primary-color`
3. Rename `brand-color-soft` to `primary-color-light`

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by nitinprakash96** [comment]
I'd like to work on this one.

**Comment by brainwane** [comment]
@nitinprakash96 Please go ahead! Let us know how it's going.
