### ISSUE TITLE
Make it clear if the login at pypi.org is the same as pypi.python.org

### ISSUE THREAD

**Issue by Flimm** [pypa/warehouse#3437]
On this log-in page, the user is asked to enter a username and password: https://pypi.org/account/login/

It's not clear from the login page whether the username and password is meant to be the same as the one at https://pypi.python.org , or if the user is supposed to register and have two separate accounts.

Could a message be added to the login page explaining this?

**Comment by brainwane** [comment]
Thanks, @Flimm! pypi.org uses the same username and password as pypi.python.org but you're right, that isn't clear right now. My colleague Ernest has now submitted a pull request to fix this: #3439.

**Comment by di** [comment]
Fixed in #3439.
