### ISSUE TITLE
Markdown long description on wheel rendered as restructured text

### ISSUE THREAD

**Issue by pevogam** [pypa/warehouse#3438]
Hi, the project description as seen in https://pypi.org/project/guibot/ does not render as markdown *despite* me setting the long_description_content_type='text/markdown' option. Interestingly, when I did the same upload in the test repository, it also didn't render as markdown initially but did so after forceful refreshing in about 30 minutes. The same however did not happen at the production PyPI repo. Perhaps a relevant problem with refreshing is that when I search for the package through the page search engine, it returns a result which keeps having old version https://pypi.org/search/?q=guibot (0.11.4) and not the newer (0.20.1) despite days passing as well.

**Comment by ewdurbin** [comment]
@pevogam it doesn't look like `Description-Content-Type` was set at upload time.

Can you confirm that this package was uploaded using `setuptools>=38.6.0` and `twine>=1.11.0`? For more detail see https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

**Comment by pevogam** [comment]
Sure, I have already checked the versions as well. This is the setuptools version

    Python 2.7.13 (default, May 10 2017, 20:04:28) 
    [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import setuptools
    >>> print setuptools.__version__
    39.0.1

and this is the twine version:

    $ twine --version
    twine version 1.11.0 (pkginfo: 1.4.2, requests: 2.18.4, setuptools: 39.0.1,
    requests-toolbelt: 0.8.0, tqdm: 4.19.8)

I uploaded a previous version package without the `Description-Content-Type` first but the last uploaded version has this value set. Besides this, I have tested the newer version on the test repo where the `Description-Content-Type` was never missed (from the very beginning) and it still displayed restructured text first *but* after some refreshing finally started displaying Markdown. The same did not happen with the production repo.

**Comment by ewdurbin** [comment]
<img width="175" alt="screen shot 2018-03-27 at 5 50 22 am" src="https://user-images.githubusercontent.com/1200832/37960117-c33a2724-3182-11e8-8183-0518c4adcfca.png">

The version `0.20.1` uploaded to upload.pypi.org at `2018-03-23 13:58:59.920985` does not have the `Description-Content-Type` set. I've checked and this same version is on test.pypi.org, and also does not have this field set.

It looks like you've removed previous releases, so I'm unable to look at the progression of values over previous versions.

**Comment by pevogam** [comment]
Is it possible that the `setuptools` module reuses some cache? I have made sure to erase anything in advance before repackaging. This is my *setup.py*:

```python
#!/usr/bin/python

from setuptools import setup
from os import path

p = path.abspath(path.dirname(__file__))
with open(path.join(p, '../README.md')) as f:
    README = f.read()

setup(
    name='guibot',
    version='0.20.1',
    description='GUI automation tool',
    long_description=README,
    long_description_content_type='text/markdown',

    install_requires=[
        "Pillow",
        'numpy',
        'opencv-contrib-python',
    ],
    tests_require=[
        'PyQt4',
    ],

    url='http://guibot.org',
    maintainer='Intra2net',
    maintainer_email='opensource@intra2net.com',
    download_url='',

    packages=['guibot'],
    package_dir={'guibot': '../guibot'},

    classifiers=[
          'Development Status :: 3 - Alpha',
          'Environment :: Console',
          'Intended Audience :: End Users/Desktop',
          'Intended Audience :: Developers',
          'Intended Audience :: System Administrators',
          'License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)',
          'Operating System :: MacOS :: MacOS X',
          'Operating System :: Microsoft :: Windows',
          'Operating System :: POSIX',
          'Programming Language :: Python',
          'Programming Language :: Python :: 2.7',
          'Topic :: Desktop Environment',
          'Topic :: Multimedia :: Graphics',
          'Topic :: Scientific/Engineering :: Artificial Intelligence',
          'Topic :: Software Development :: Testing',
          'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
```

**Comment by ewdurbin** [comment]
@pevogam how are you uploading the distribution that setuptools creates?

**Comment by pevogam** [comment]
I am uploading to https://upload.pypi.org/legacy/ as I followed instructions in a migration tutorial so this could be to culprit? The [official page](https://packaging.python.org/tutorials/distributing-packages/) for this doesn't contain an address for this instruction. If the address is wrong then I wonder why I still see the new package on the web page.

In fact, you can see that the required setting for markdown is available from the [source distribution](https://files.pythonhosted.org/packages/9c/45/1cea5c415d26be9798b73ed1656495e47f91cb610af9f2414a3c0df3e1cd/guibot-0.20.1.tar.gz)

**Comment by ewdurbin** [comment]
no, that's the correct endpoint. you are uploading with `twine`?

**Comment by pevogam** [comment]
Yes, as per the instructions from https://packaging.python.org/tutorials/distributing-packages/ I do

    twine upload dist/*

**Comment by ewdurbin** [comment]
bizarre. I just tested locally and everything is working as anticipated.

```shell
$ twine upload -r local guibot-0.20.1.tar.gz 
Uploading distributions to http://localhost/legacy/
Uploading guibot-0.20.1.tar.gz
100%|█████████████████████████████████████████████████████████████████████████| 7.64k/7.64k [00:00<00:00, 83.7kB/s]
$ twine --version
twine version 1.11.0 (pkginfo: 1.4.2, requests: 2.18.4, setuptools: 39.0.1,
```

<img width="1032" alt="screen shot 2018-03-27 at 6 15 52 am" src="https://user-images.githubusercontent.com/1200832/37961531-8917e546-3186-11e8-8826-1939737fba48.png">

**Comment by pevogam** [comment]
Can you verify that the actually uploaded [source distribution](https://files.pythonhosted.org/packages/9c/45/1cea5c415d26be9798b73ed1656495e47f91cb610af9f2414a3c0df3e1cd/guibot-0.20.1.tar.gz) contains the required field? Could it be some cache on the production server that didn't respect this field compared to your local machine?

**Comment by ewdurbin** [comment]
@pevogam distributions are not modified and are not cached by the upload endpoints. we explicitly accept, store, and serve exactly what clients upload.

**Comment by ewdurbin** [comment]
@pevogam unfortunately that's not for sure the case. are you _positive_ that you uploaded the distribution for `0.20.1` on `2018-03-23 13:59:01.211308` using `twine==1.11.0`?

I'd be interested to see if creating a new release `0.20.2` and making _sure_ to upload with `twine==1.11.0` resolves the issue.

**Comment by pevogam** [comment]
I am sure I used the correct version since I installed twine especially for this purpose (using Fedora and automatically pulling the latest available version). But if you would like, we can wait until the next revision and I will reopen this if the issue reappears.

Strangely as I said before, the markdown was also not rendered on the test pypi repo at first but rendered later on (in ~30 minutes). I uploaded to the production repo *after* this.

Feel free to close this issue for the time being if you think my suggestion is good to try.

**Comment by di** [comment]
This is because https://github.com/pypa/wheel/pull/232 hasn't been released yet: your wheel has the wrong metadata version, twine has uploaded your wheel before the source distribution, and PyPI only considers the metadata for the first distribution it sees for a release.

I mention this in https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi, basically you need to do:

```
$ twine upload dist/<filename>.tar.gz
$ twine upload dist/<filename>.whl
```
instead.

**Comment by pevogam** [comment]
I see. Although this still doesn't explain why the rendering would succeed on the test repo and not on the production repo. Perhaps a race condition where they get uploaded in the correct order? When [pypa/wheel#232](https://github.com/pypa/wheel/pull/232) is released will it fix this issue right away or do affected packages need an additional upload with incremented version?

**Comment by di** [comment]
It seems to me like the same issue exists on the test repo: https://test.pypi.org/project/guibot/

Since it's not possible to edit the incorrect wheel metadata after uploading to PyPI, you'd need to make a new release (by incrementing the version).

**Comment by di** [comment]
Closing this as it's not technically an issue with Warehouse, but feel free to comment here if you're still having issues.

**Comment by pevogam** [comment]
Yes, I suggested that we do the same as I want to test your solution but I cannot force an increment in our version just because of the specifics of your implementation. Since you don't allow for package update even when it was caused by technical difficulties in the system I will have to wait for our next revision to possibly update this issue on my side. Thanks!

**Comment by brainwane** [comment]
@pevogam I hope [Test PyPI](https://packaging.python.org/guides/using-testpypi/) helps you test this!

**Comment by brainwane** [comment]
Now that `wheel` 0.31.0 is out, I've suggested we add guidance to https://packaging.python.org/guides/making-a-pypi-friendly-readme/ giving people those minimum version numbers to make description rendering work properly:

* `pkginfo>=1.4.2`
* `twine>=1.11.0`
* `setuptools>=38.6.0`
* `wheel>=0.31.0`

Then https://packaging.python.org/tutorials/distributing-packages/#readme-rst-readme-md could link to that.

**Comment by gtalarico** [comment]
I was having a similar issue, package kept getting rejected for invalid long_desc (was in markdown and text/markdown was specified in setup.py)
running `pip install --upgrade setuptools wheel`
solved it for me.

**Comment by greyli** [comment]
@di It seems that the issue still exists after [pypa/wheel#232](https://github.com/pypa/wheel/pull/232) released. I upload the package with `twine upload dist/*` but only wheel upload success.

**Comment by javatechy** [comment]
It works if your 
setuptools is upgraded to version 38.6.0 or newer

twine is upgraded to version 1.11.0 or newer

wheel is upgraded to version 0.31.0 or newer

**Comment by vikram-sahu** [comment]
> It works if your
> setuptools is upgraded to version 38.6.0 or newer
> 
> twine is upgraded to version 1.11.0 or newer
> 
> wheel is upgraded to version 0.31.0 or newer


version ::
>>> import wheel
>>> print(wheel.__version__)
0.33.6
>>> print(twine.__version__)
2.0.0
>>> import setuptools
>>> print(setuptools.__version__)
41.6.0

Still getting this weird issues.
[vikram.sahu@NL587 pepipost-sdk-python]$ twine upload dist/*
Enter your username: DX-Team
Enter your password: 
Uploading distributions to https://upload.pypi.org/legacy/
Uploading pepipost-2.6.1-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.7k/36.7k [00:01<00:00, 19.1kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for Url: https://upload.pypi.org/legacy/

can anyone help me? for the first release, I didn't face such issues

**Comment by jamadden** [comment]
@vikram-sahu If you're still having problems, please open an issue in https://github.com/pypa/pypi-support/issues/. There's not an issue template, but it will help to see exactly what you're trying to upload (i.e., attach your wheel file to the issue). 

I'll note that commonly if the `long_description` truly isn't RST, this often means that the `long_description_content_type` wasn't set, or that it wasn't readable because of other problems in the metadata, most often extra newlines in fields that are supposed to be one line, such as `description=` or `license=`.

**Comment by vikram-sahu** [comment]
> @vikram-sahu If you're still having problems, please open an issue in https://github.com/pypa/pypi-support/issues/. There's not an issue template, but it will help to see exactly what you're trying to upload (i.e., attach your wheel file to the issue).
> 
> I'll note that commonly if the `long_description` truly isn't RST, this often means that the `long_description_content_type` wasn't set, or that it wasn't readable because of other problems in the metadata, most often extra newlines in fields that are supposed to be one line, such as `description=` or `license=`.

Thanks @jamadden for helping with comment. so i have checked this whl file using ` twine check dist/*` it is gving me the below error 

```bash
Checking dist/pepipost-2.5.0-py3-none-any.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 158: Warning: Block quote ends without a blank line; unexpected unindent.
  warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
Checking dist/pepipost-2.5.0.tar.gz: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 158: Warning: Block quote ends without a blank line; unexpected unindent.
  warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
```
I have been debugging with my Readme.md file ( made a standalone script and parse the file it is getting properly converted to RST format)

**Comment by jamadden** [comment]
@vikram-sahu If you're still having problems, please open an issue in https://github.com/pypa/pypi-support/issues/. There's not an issue template, but it will help to see exactly what you're trying to upload (i.e., attach your wheel file to the issue). Please stop replying to closed issues.
