### ISSUE TITLE
markdown not rendered properly

### ISSUE THREAD

**Issue by nschloe** [pypa/warehouse#3442]
I followed @di's [write-up](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi) for getting markdown rendering for one of my projects, [orthopy](https://github.com/nschloe/orthopy). Unfortunately, [on pypi.org it's still rendered as plaintext](https://pypi.org/project/orthopy/). This is with
```
$ twine --version
twine version 1.11.0 (pkginfo: 1.4.2, requests: 2.18.4, setuptools: 39.0.1,
requests-toolbelt: 0.8.0, tqdm: 4.19.8)
```
One thing I did differently from the blog post is that I created wheels
```
$ python3 setup.py bdist_wheel --universal
```
instead of an`sdist`.

Any idea what might be going wrong?

**Comment by di** [comment]
You're hitting an issue with `wheel` that has been fixed but hasn't been released yet (https://github.com/pypa/wheel/pull/232), sorry about that!

See my comment here: https://github.com/pypa/warehouse/issues/3438#issuecomment-376501335

**Comment by nschloe** [comment]
Thanks for the clarification!

**Comment by nschloe** [comment]
@di Here's another one, this time with the wheels workaround, but the markdown doesn't render properly: https://pypi.org/project/pygmsh/. Perhaps it's the HTML tags? Let me know if I should open a new bug or if we can discuss this here.

**Comment by di** [comment]
FYI @nschloe, [a new release of `wheel` has been made](https://pypi.org/project/wheel/0.31.0/) so the workaround is no longer necessary.

**Comment by nschloe** [comment]
Nice, thanks for letting me know!
