### ISSUE TITLE
markdown tables not rendered properly

### ISSUE THREAD

**Issue by nschloe** [pypa/warehouse#3449]
Compare https://pypi.org/project/orthopy/#description and https://github.com/nschloe/orthopy#triangle.

**Comment by brainwane** [comment]
Thanks for the report, @nschloe! Checking this out.

**Comment by di** [comment]
This is because CommonMark doesn't support tables. When we add support for GFM this will be possible.

**Comment by brainwane** [comment]
@nschloe I'm going to close this as a duplicate, but please check #3322 and https://github.com/pypa/packaging-problems/issues/126 to see the work progressing towards getting this working well for you. Thanks for testing and reporting!

**Comment by nschloe** [comment]
Thanks everyone for the quick replies!
