### ISSUE TITLE
Clarify "classifiers"/"filters" wording

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3452]
Per conversation on python-list ([1](https://mail.python.org/pipermail/python-list/2018-March/732164.html), [2](https://mail.python.org/pipermail/python-list/2018-March/732200.html)), the "Filter projects" section on the left-hand side of the page is not clearly related to the "list of classifiers", and

> "Classifiers" is what the relevant package metadata is called, but it's not exactly what the average user would refer to that data as.

What can we do to both serve people who don't know what classifiers are and people who know that term and are specifically thinking in terms of classifiers?

**Comment by brainwane** [comment]
#3410 adds an FAQ entry about adding a new classifier. As we get more consistent about talking about filters and classifiers, I'd like us to update this wording or add another FAQ to clarify where the "Trove"/"classifier" wording and master list originated.

**Comment by drunkwcodes** [comment]
Maybe introducing https://github.com/nepsilon/search-query-parser and letting users to type search queries like "Framework:Django" in the search bar will help promoting classifiers.

**Comment by nlhkabu** [comment]
We could do something like this:

## Filter by classifier :information_source: 

Hovering your mouse over the icon could then launch a tooltip that describes what a classifier is.
@brainwane could you provide some appropriate text for this?

**Comment by brainwane** [comment]
[Gregory Ewing brought up](https://groups.google.com/d/msg/comp.lang.python/ZKCluJ7hKjY/X-7DGpyWBQAJ) "Categories" which seems, to me, a very sensible name for what we're talking about.

Here's text for the tooltip:

> Each project's maintainers give PyPI a list of "trove classifiers" to use to categorize each release, describing who it's for, what systems it can run on, and how mature it is.

**Comment by brainwane** [comment]
(Background, in case anyone wants to add an FAQ item: the original list of trove classifiers [was drawn from Freshmeat and SourceForge lists](https://www.python.org/dev/peps/pep-0301/#distutils-trove-classification).)

@drunkwcodes that's an interesting idea! I'm going to open a separate ticket for that. Thanks for bringing it up.
