### ISSUE TITLE
change filter reference to respond to search page width

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3454]
![pypi-narrow-no-classifiers](https://user-images.githubusercontent.com/842790/38037486-f95e430e-3276-11e8-8569-9e34971539a2.png)

Per [this python-list post](https://mail.python.org/pipermail/python-list/2018-March/732168.html) -- a person seeing nothing on the left-hand side of https://pypi.org/search/ says,

> For me, that's a window width issue. The sidebar with the filters only shows when the window is wide enough. Unfortunately, the text mentioning it doesn't change, so this should be fixed.

**Comment by wm75** [comment]
@brainwane thanks for filing this!

**Comment by brainwane** [comment]
I've gotten further user reports of this issue. One person emailed me:

> Whether the filter list is shown on the left side is a matter of browser window width.  I’ve tried it with:
> * Apple’s Safari
> * Google Chrome
> * Mozilla Firefox
> * Opera

> I do use various add-ons on Safari, Chrome and Firefox, but I used no add-ons at all with Opera (it was a fresh installation this morning with zero configurations).

> Simply make your browser window narrow enough and the list on the left is replaced with an “Add Filter” button underneath.  Clicking on that button results in “Filter Projects" overlaying part of the regular window.  You must click on the “X” to close the list.

> That makes the statement, “...select a filter from the list of classifiers on the left.” a bit problematic, because the list is only on the left when the browser window is sufficiently wide.

> I am running on a MacBook Pro at macOS 10.13.3 (High Sierra), which is currently the latest version of macOS.

and follows up:

> I also just tried it on my iPad Air 2 (9.7” screen) using Safari.  I see the filter list on the left in landscape mode, but only see the button underneath in portrait mode. 

> I am still at iOS 11.2.5 on my iPad.

Separately, [Terry Reedy writes](https://groups.google.com/d/msg/comp.lang.python/ZKCluJ7hKjY/6tqVhSaABQAJ):

> This is a window width issue.  Full screen (on my monitor), the categories work fine, and clicking on them appears to work.  When I narrow the browser window to about 1100 pixels, the category list 'to the left' disappears and is replaced by an [Add filter] box.  When this happens, "from the list of classifiers on the left." should be replaced by "by clicking the button below." 

---------------

What can we do here to be properly responsive? I like Reedy's suggestion. I would like us to prioritize this since I'm getting several user reports of this problem.
