### ISSUE TITLE
I wish to publish a version of qfragment, but my filesize is too large.

### ISSUE THREAD

**Issue by buckmaxwell** [pypa/warehouse#3456]
Hello, I am a developer for Quill.org.  We maintain a new package in early development called qfragment -- it aims to detect and give feedback on how to correct different types of sentence fragments.  The new version includes a large portion of the languagetool project packaged with it, so the total distribution is around ~150mb and may grow a bit more.  I believe the limit is 60mb.  

Can we get a boosted limit? We will work to reduce the distribution size in the meantime but will have trouble keeping it under the threshold.

**Comment by ewdurbin** [comment]
@buckmaxwell sure, we can bump the limit if have an understanding of what requires the package size to be larger than 60MB.

**Comment by buckmaxwell** [comment]
Thank you.  The package size is bumped because of libraries that are/will be required for natural language processing. We will work to keep the packages as slim as we can. Please tell me when you bump it so I can deploy the newer version.

**Comment by ewdurbin** [comment]
@buckmaxwell thanks. limit is applied. we ask that you limit the frequency of releases in order to keep the footprint of the project as low as possible for PyPI and the folks who maintain mirrors of PyPI (A current full mirror is ~1.3TB)

**Comment by buckmaxwell** [comment]
Sounds good @ewdurbin
