### ISSUE TITLE
Ability to increase file size limit on per-project basis?

### ISSUE THREAD

**Issue by r1chardj0n3s** [pypa/warehouse#346]
Once in a while (three times in the years we've been hosting files) we get a request from a user to exceed the hard-coded file size limit in PyPI. Maybe there should be some way to cater for them? Maybe it's too much to ask to handle just their extremely rare use-case?

**Comment by thewtex** [comment]
Hello, This issue effects me and I am adding a note here (many people probably encounter this issue, but they do not make noise about it).  I think it is also a chicken-and-egg (chicken-and-wheel? :-P) problem for getting more scientific Python packages on SciPy. A per-project increase would be helpful.  Thanks for improving PyPi :-).
