### ISSUE TITLE
Problem getting conda package to show up in PyPI search

### ISSUE THREAD

**Issue by AaronV77** [pypa/warehouse#3471]
Hello, I created a PyPi package earlier this week for the first time, and the package is not showing up in the search on the new PyPi Wearhouse site? This is an issue because I cannot create a Conda package from my PyPi package without hacking the meta.yaml file and putting the correct URL inside. 

The URL that the conda-build is trying to use from the metadata is the following: https://pypi.io/packages/source/n/ncep_client/ncep_client-1.0.0.tar.gz, but I get a 404 error when trying to use this URL.

If I use this URL: https://files.pythonhosted.org/packages/06/f6/bebe6589fd5ab44951947dcaea6993c61d70d97d0263913446ea6cc02733/ncep_client-1.0.0.tar.gz, everything works correctly and runs smoothly.  

All in all the Conda guys told me that I should contact you guys and see what the problem is? Also I'm not ruling out a user error by any means because this was my first time making a PyPi package.

Thanks, 

My package name is: ncep_client

**Comment by ewdurbin** [comment]
we're working on resolving a memory consumption issue with search reindex in #3470, which should resolve the out of date indexes soon.

**Comment by ewdurbin** [comment]
Note: you should be using pypi.org rather than pypi.io for the url `https://pypi.io/packages/source/n/ncep_client/ncep_client-1.0.0.tar.gz` if you'd like to use that interface.

Also, since the `/packages/source/` urls are generated from the JSON api, they may lag somewhat due to caching.

**Comment by AaronV77** [comment]
Alright thanks for the timely response, I can wait patiently.

**Comment by ewdurbin** [comment]
I'm not familiar with conda's resolver or the meta.yaml file, but the canonical place to get information on released files is the simple index `https://pypi.org/simple/`. To be clear the deterministic URLs referenced (`/packages/source...`) are mainly supported for legacy clients which rely on them.

**Comment by AaronV77** [comment]
Hey @ewdurbin what should my .pypric look like? I have the following:

[distutils]
index-servers =
    pypi
    test

[pypi]
repository:https://pypi.org/pypi
username:yourname
password:yourpassword

[test]
repository:https://test.pypi.org/pypi
username:yourname
password:yourpassword

and I keep getting the following error:

HTTPError: 410 Client Error: This API has moved to https://upload.pypi.org/legacy/. See TODO for more information. for url: https://pypi.org/pypi

any help? Also I had the correct stuff to begin with when uploading a package to PyPi, so I don't know where conda pulled that pypi.io url from.

Thanks.

**Comment by brainwane** [comment]
@AaronV77 do Ernest's instructions solve this problem for you?

Also, I'd love your assistance spreading the word to the conda/Anaconda community about the need to migrate to the new PyPI. https://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html would be a good link to spread around.

**Comment by AaronV77** [comment]
@brainwane, yes the do and I will spread the word around on what happened. I have an issue open on their their build site right now so I will include this issue number and the new information.

@ewdurbin I have everything updated on my end with having the correct .pypric and everything seems to be working correctly now. I created a new release of the source and everything uploaded correctly, and when I went to do the conda package everything connected correctly. So I have no clue where twine uploads a package if the .pypric does not explicitly have a repo url for pypi?

I still cannot get the package to show up in the search but in the end half the problem was user error.  Any idea when the search will start to work correctly?

**Comment by brainwane** [comment]
@AaronV77 We're working on fixing the search in pull request #3470 which will probably take a few days to review and merge.

Thanks for sharing the news about the new PyPI with the conda folks!

If `twine` is not told an explicit repo URL to upload to, it defaults to `https://upload.pypi.org/legacy/`. https://twine.readthedocs.io/en/latest/#options has more on that.

**Comment by brainwane** [comment]
@AaronV77, does the package show up for you when you search PyPI now?

**Comment by AaronV77** [comment]
Hey @brainwane it does~! We are good to go now! Thanks.

**Comment by nateshmbhat** [comment]
other packages like "webbot" are also not showing up

**Comment by ewdurbin** [comment]
@nateshmbhat It appears that webbot's first release occurred within the last couple hours. The indexing task only runs every 3 hours, so new projects take some time to show up in search.
