### ISSUE TITLE
Document User-Agent filtering for clients with broken redirect handling

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3490]
We should update https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi to advise people on user agent filtering.

So we should add a bullet point in `docs/api-reference/integration-guide.rst` that says:

* All APIs: Starting in mid-April 2018, we will be redirecting pypi.python.org API calls to hit pypi.org instead. `User-Agent` filtering is in place on legacy PyPI to account for some known-broken clients that we've determined can't handle the redirect, but once we shut down legacy PyPI (probably by April 30th), that filtering will no longer help and those clients will break. To fix affected clients, please update them to hit pypi.org directly.

Followup to #3275.

---------------

**Good First Issue**: This issue is good for first time contributors. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, in [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or on the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
I'm not sure the bit about the user agents is necessary? I think all affected/broken clients already know that we're special-casing their user agents, and this isn't relevant to average users.

**Comment by brainwane** [comment]
@ncoghlan my recollection is that you wanted this added to the migration guide but I can't remember where you said that - perhaps in https://github.com/pypa/packaging-problems/issues/ someplace?

**Comment by di** [comment]
Also, any user-agent filtering is going to be irrelevant as soon as we launch (which is shortly) so this information will quickly become out of date.

**Comment by ncoghlan** [comment]
It was in a Packaging WG thread - I'd like the user agent filtering to be public, so even folks intermittently accessing legacy PyPI know they can ask for a couple of weeks grace before the old site is shut down completely. (Plus it provides some additional transparency around some of the work happening to help provide a smooth migration)

**Comment by ncoghlan** [comment]
Thanks!
