### ISSUE TITLE
Warehouse prompts for munged project name when deleting project with period character

### ISSUE THREAD

**Issue by jaraco** [pypa/warehouse#3491]
Today, I went to delete the [jaraco.persona](https://pypi.org/project/jaraco.persona), but when I did, it did not accept the name of the project as confirmation:

![image](https://user-images.githubusercontent.com/308610/38175298-67a850fa-35a8-11e8-8f96-64b6acd8357a.png)

Instead, it wanted a munged name with the period replaced by a dash.

![image](https://user-images.githubusercontent.com/308610/38175310-8fd48882-35a8-11e8-80d2-de705dd950fa.png)

Granted, it's just an annoyance, but given that it's prompting for the project to ensure the correct project is being deleted, it's quite surprising that the munged name is being demanded.

I'd like for warehouse not to munge names at all (I'm not sure what requirement drove the desire to munge names), but if it must, it should at least hide that detail from the user consistently.

**Comment by jaraco** [comment]
It also seems to require the user to enter normalized case:

![image](https://user-images.githubusercontent.com/308610/38175384-9052d538-35a9-11e8-99b0-d51f6d6fcb27.png)

**Comment by jaraco** [comment]
(I suggest it shouldn't)

**Comment by di** [comment]
I think it makes sense to use the non-normalized version of the project name here.

**Comment by brainwane** [comment]
@saxenanurag would you like to work on this next?

**Comment by brainwane** [comment]
@saxenanurag how is this going?

**Comment by saxenanurag** [comment]
Hi @brainwane 
Been trying to work on this. Unfortunately, I am getting this error: 

```
~/Sites/warehouse master 6s
❯ make initdb
docker-compose run --rm web psql -h db -d postgres -U postgres -c "DROP DATABASE IF EXISTS warehouse"
Starting warehouse_notdatadog_1 ... done
Starting warehouse_elasticsearch_1 ... done
Starting warehouse_rabbitmq_1      ... done
Starting warehouse_db_1            ... done
Starting warehouse_redis_1         ... done
psql: could not translate host name "db" to address: Name or service not known
make: *** [initdb] Error 2
```
Any thoughts on how to fix this?

**Comment by saxenanurag** [comment]
Nevermind. I ran `docker prune -a` to delete everything and ran `make build`, `make initdb` and `make serve` again and my local site is working now. 😄

**Comment by brainwane** [comment]
Great! @saxenanurag will we see a work-in-progress PR from you soon? :)

**Comment by saxenanurag** [comment]
Yes @brainwane

**Comment by brainwane** [comment]
@saxenanurag Thanks! What will you work on next?

**Comment by saxenanurag** [comment]
@brainwane I have to look at the list. Do you have anything in mind?

**Comment by brainwane** [comment]
@saxenanurag I don't have anything in particular in mind, no -- please go ahead and look at the list. The "help wanted" issue label may be useful to look at.
