### ISSUE TITLE
ie11: password strength indicator not working

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3509]
### How to reproduce

- Use IE11
- Try to register an account

### What happens

The password strength bar is not filled

![screenshot from 2018-04-02 16-19-07](https://user-images.githubusercontent.com/3323703/38201840-96900cd4-3691-11e8-98e6-d5a6a392d354.png)

### What should happen

See other browsers :)

@yeraydiazdiaz is this something you could look into? It is not high priority as ie11 users make up less than 3% of our users.

**Comment by nlhkabu** [comment]
Note: I could not see any errors in the dev console when reproducing this :(

**Comment by di** [comment]
This might be fixed by #3535.

**Comment by nlhkabu** [comment]
Yes, I have tested and confirm it is fixed :) Thanks @yeraydiazdiaz and @di
