### ISSUE TITLE
ie11: modal button not disabled

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3512]
### How to reproduce

- Use IE11
- Log in
- Go to any project
- Try to delete the project
- If you have no projects, try instead to delete your account

### What happens

The delete button is enabled

![screenshot from 2018-04-02 16-21-38](https://user-images.githubusercontent.com/3323703/38203947-dce6727a-3698-11e8-855f-d900d50269ed.png)

### What should happen

The delete button should be disabled until the correct string is entered into the input.

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, please include a screenshot in your Pull Request.

**Comment by di** [comment]
This (and some other IE11 issues) might be because the JS is failing somehow. Could you check the devtools console for errors when testing?

**Comment by di** [comment]
Weird! Well, at least it's gracefully degrading 🙂

**Comment by nlhkabu** [comment]
I could be looking in the wrong place :/  But yes, I'm not too worried about this one because it's not at all "broken" for ie11 users, just not the same experience.

**Comment by yeraydiazdiaz** [comment]
@di possibly https://github.com/pypa/warehouse/pull/3535 helps?

**Comment by di** [comment]
@yeraydiazdiaz Indeed I think it does. @nlhkabu might want to re-test some of these IE11 issues where JS is broken now that that is merged.

**Comment by di** [comment]
@aalmazan Would you be able to re-test this issue?

**Comment by aalmazan** [comment]
@di The Delete Project modal works as expected for me here on Win7 + IE11 with the current master 166247c.

**Comment by aalmazan** [comment]
Yes, that's correct.

![ie11-modal-button](https://user-images.githubusercontent.com/800948/38288498-15725076-3786-11e8-9772-fef0864199e0.gif)
(Ignoring the modal not being centered)

**Comment by di** [comment]
Great, thanks @aalmazan! Closing this then.
