### ISSUE TITLE
ie11: filter badge has no padding on right

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3514]
## How to reproduce

- Use IE11
- Go to the search results page, and apply a filter (e.g. https://pypi.org/search/?q=&c=Framework+%3A%3A+AsyncIO)

### What happens

The filter is applied, with no padding between the end of the word and the remove button:

![screenshot from 2018-04-02 16-29-37](https://user-images.githubusercontent.com/3323703/38202261-0e0226de-3693-11e8-9a3d-faac0ba7d374.png)

### What should happen

There should be padding between the end of the word and the remove button:

![screenshot from 2018-04-02 17-14-16](https://user-images.githubusercontent.com/3323703/38204072-4a482980-3699-11e8-8df4-faa9f7fc5f61.png)

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, please include a screenshot in your Pull Request.

**Comment by aalmazan** [comment]
Cant seem to reproduce this on the live environment.

![selection_037](https://user-images.githubusercontent.com/800948/38289241-14096fd6-378a-11e8-8478-4cc9203f9c60.png)

**Comment by nlhkabu** [comment]
Thanks @aalmazan.  Retested on my side and I am also no longer seeing the problem:

![screenshot from 2018-04-07 07-04-16](https://user-images.githubusercontent.com/3323703/38451975-f9ad5d28-3a31-11e8-9530-ce7c0a654014.png)

Will close and reopen if required !
