### ISSUE TITLE
ie11: tooltip underlined

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3515]
### How to reproduce

1. Use IE11
2. Go to any project with a `pip install` instruction box (e.g. https://pypi.org/project/Django/)
3. Put your mouse over the 'copy' icon

### What happens

The tooltip appears, with underlined text

![screenshot from 2018-04-02 16-31-46](https://user-images.githubusercontent.com/3323703/38202391-688c63a8-3693-11e8-871d-47065df7940f.png)

### What should happen

The tooltip should appear, but the text should not be underlined

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, please include a screenshot in your Pull Request.

**Comment by torokokill** [comment]
From the looks of it, ie11 is prioritizing the `.package-header button` selector with `text-decoration: underline` over the `.tooltipped::after` with `text-decoration: none`; the opposite behaviour of other browsers. 

Considering that this button's text doesn't show an underline on any browser (and isn't designed to?), would removing the `text-decoration` rules in `.package-header button` be appropriate?

**Comment by griselleong** [comment]
Would like to work on this
