### ISSUE TITLE
ie11: notification bar does not close

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3516]
### How to reproduce

- Use ie11
- Go the the homepage (with cookies cleared)
- try to dismiss the beta notification bar

### What happens

Nothing :(

### What should happen

The message should dissapear

**Comment by nlhkabu** [comment]
Note: I'm not getting any JS errors in devtools :(

**Comment by di** [comment]
The original behavior (nothing happens at all) was fixed by #3535.

The current behavior (white space is left behind) should be fixed by #3420.

**Comment by nlhkabu** [comment]
Tested - Fixed :tada:
