### ISSUE TITLE
Show browser warning banner for ie10 and below

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3517]
Currently, we show a "not supported" banner for users on ie9 and under.  I suggest we update this to ie10 and below because a) there are very few ie10 users, and b) [microsoft ended support for this a while ago](https://venturebeat.com/2016/01/12/microsoft-ends-support-for-ie8-ie9-ie10-and-windows-8/)

The code for changing this is here: https://github.com/pypa/warehouse/blob/master/warehouse/templates/base.html#L100

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by contrepoint** [comment]
Hi Nicole! 
@ewdurbin and I just spent some time pairing on this and have a solution in mind that should work. However, we have problems testing it on an IE10 browser. Do you have suggestions for a testing workflow we can use? Thanks so much!
-Janice

**Comment by contrepoint** [comment]
@nlhkabu @ewdurbin perhaps you could could request free testing from [Crossbrowsertesting.com](https://crossbrowsertesting.com/open-source/request) for this project, since it is open source.

**Comment by nlhkabu** [comment]
hi @contrepoint - we are in the process of applying for an open source account with BrowserStack.  In the meantime, if you want to make a PR, I can test it with my personal account?

**Comment by pradyunsg** [comment]
Can close now. :)
