### ISSUE TITLE
Mobile and Tablet: Search icon position too far to right

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3518]
### How to reproduce

- Use an apple mobile or tablet device

### What happens

The 'search' icon in the search bar is stuck to the right hand side of the input

![screenshot from 2018-04-02 16-42-22](https://user-images.githubusercontent.com/3323703/38202775-d7a58160-3694-11e8-925b-600398dab5e9.png)

### What should happen

There should be space between the edge of the input and the icon, e.g.

![screenshot from 2018-04-02 17-56-58](https://user-images.githubusercontent.com/3323703/38205667-4b262d06-369f-11e8-9652-a014a94b5600.png)

---

**Screenshot Required**: Please include a screenshot of your update. This helps our team give you feedback faster.

**Comment by yeraydiazdiaz** [comment]
I can't reproduce using iOS 11.1 in my iPhone SE or in the Simulator for any device. Here's what it looks like for iPad in the simulator:

<img width="915" alt="screen shot 2018-04-22 at 18 22 40" src="https://user-images.githubusercontent.com/6739793/39097887-5f82b240-465a-11e8-9f51-dc5cf424911c.png">

Is it possible it happens only on earlier versions?

**Comment by nlhkabu** [comment]
I believe this was fixed with https://github.com/pypa/warehouse/pull/5139
