### ISSUE TITLE
Support HEAD request to files.pythonhosted.org

### ISSUE THREAD

**Issue by yuvalreches** [pypa/warehouse#3536]
As part of the changes you've made all the packages are now hosted under https://files.pythonhosted.org/

In JFrog Artifactory we have to configure this URL as part of any PyPI remote repository.

Artifactory provides a way for verifying remote URLs are operational / reachable:
We perform _HEAD_ request to the URL and verify HTTP 200 response.

However when trying to reach https://files.pythonhosted.org/ via _HEAD_ request the response is _HTTP 404_.

Would it be possible to change the behavior and respond with **_HTTP 200_**?
This will help our users to be certain that their connectivity to PyPI is valid.

(Note that until now we've performed _HEAD_ against https://pypi.python.org and got _HTTP 200_ response).

**Comment by dstufft** [comment]
Can you be clear, are you talking specifically about something like ``curl -XHEAD https://files.pythonhosted.org/`` or like, ``curl -XHEAD https://files.pythonhosted.org/packages/b0/e1/eab4fc3752e3d240468a8c0b284607899d2fbfb236a56b7377a329aa8d09/requests-2.18.4.tar.gz``?

**Comment by yuvalreches** [comment]
Specifically about `curl -XHEAD https://files.pythonhosted.org/ `

**Comment by dstufft** [comment]
Yea we should be able to make that happen.

**Comment by brainwane** [comment]
Also, @yuvalreches, welcome to GitHub (I see this is the first issue you've ever opened)!

Just in case you haven't seen them yet, I want to point you to our [documentation on Warehouse and its APIs](https://warehouse.pypa.io/), our live chat channel [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), and the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev). And [here's our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap).

**Comment by brainwane** [comment]
I presume this is to mitigate #3275?

**Comment by yuvalreches** [comment]
@brainwane you are correct, this is part of the JFrog efforts of #3275 :)

**Comment by ewdurbin** [comment]
Supporting a HEAD to `files.pythonhosted.org` is effectively checking the health of Fastly and S3.

I'm not convinced this adds sufficient value, as I'm pretty sure we'd just be sending a synthetic response from Fastly. @dstufft any ideas?

**Comment by mgedmin** [comment]
It would presumably allow corporate users to make sure their firewall is allowing outgoing connections to files.pythonhosted.org.

**Comment by ewdurbin** [comment]
We've shipped a new fastly service and index page for files.pythonhosted.org that supports this.


```
>>> import requests
>>> requests.head('https://files.pythonhosted.org')
<Response [200]>
```
