### ISSUE TITLE
GFM markdown - <details> tags not rendering

### ISSUE THREAD

**Issue by michael-lazar** [pypa/warehouse#3539]
Thanks for adding markdown support!

I just tried uploading one of my projects with the ``long_description_content_type='text/markdown'``. Overall it looks good (apart for the relative links, which I will need to fix manually). However, I noticed that the ``<details>`` tags aren't being rendered correctly. This might have to do with the quote blocks that I put inside of the HTML tags, but the page renders correctly on Github.

Reference (see the ``FAQ`` section at the bottom):

https://test.pypi.org/project/rtv/1.22.1.post1/
https://github.com/michael-lazar/rtv/blob/master/README.md#faq

**Comment by di** [comment]
Thanks for the report! Moved to https://github.com/pypa/readme_renderer/issues/76.
