### ISSUE TITLE
ctypes simple API missing all pacakges

### ISSUE THREAD

**Issue by cooperlees** [pypa/warehouse#3551]
Hi all,

Don't know if this is a warehouse specific problem but the simple API for ctypes is missing all the packages in the HTML. It seems to be broken @ both pypi.org + pypi.python.org (didn't check if they point at the same thing) - i.e.
- https://pypi.org/project/ctypes/
- https://pypi.python.org/simple/ctypes/

The package page only lists on Warehouse - i.e.:
- https://pypi.org/project/ctypes/
NOT
- https://pypi.python.org/pypi/ctypes/

This is also causing my bandersnatch internal mirror to replicate this bug too. How can we debug why this is occurring?

**Comment by cooperlees** [comment]
I'm going to look at adding an optional feature to bandersnatch to allow an admin to ask for X copies of index.html for the Simple API files to allow comparison of changes etc. if things unexpectedly change:
https://bitbucket.org/pypa/bandersnatch/issues/106/look-at-keeping-x-old-indexhtml-files-for
- Low priority tho.

**Comment by di** [comment]
Closing because I don't think there's anything for us to do here.
