### ISSUE TITLE
Consider increasing image size restriction to 10MB

### ISSUE THREAD

**Issue by JakobGM** [pypa/warehouse#3552]
Hi!

I could not find any previous discussion of why exactly ``5MB`` has been chosen as the limit for embedded images in PyPI descriptions, so excuse me if this has already been set in stone.

I want to argue that ``10MB`` is a better image size restriction, as this is already the restriction imposed on legacy PyPI and on GitHub. 

Coordinating these restrictions across these platforms allows package maintainers to only confirm successful embedding of images on *one* site.

Examples:
- [x] [Legacy PyPI](https://pypi.python.org/pypi/astrality/0.6)
- [x] [GitHub](https://github.com/JakobGM/astrality)
- [ ] [Warehouse](https://pypi.org/project/astrality/)

**Comment by di** [comment]
> I could not find any previous discussion of why exactly 5MB has been chosen as the limit for embedded images in PyPI descriptions, so excuse me if this has already been set in stone.

5MB has been chosen because it is the default for https://github.com/atmos/camo, which we use to proxy images for Warehouse. 

> I want to argue that 10MB is a better image size restriction, as this is already the restriction imposed on legacy PyPI and on GitHub.

As far as I can tell, Github has no limit on image sizes at all.

Legacy PyPI also has no image size limit, because it doesn't use a proxy and links directly to the image instead.

> Coordinating these restrictions across these platforms allows package maintainers to only confirm successful embedding of images on one site.

While it might be as simple as changing the default file size for camo, I can't say with certainty that it will be able to handle images >5MB.

We're planning on moving away from using camo to proxy these images in the future, and we'll take into consideration this limitation when building it's replacement.

In the meantime, you might want to try compressing your GIF, either by reducing the resolution or speeding it up, to get it under the 5MB limit.

**Comment by JakobGM** [comment]
Thanks for the reply, @di!

I was not aware of the lack of a size restriction on legacy PyPI, my bad.

But it seems that GitHub has such a restriction, and it is set to ``10MB``.

- [This StackOverflow answer](https://stackoverflow.com/a/46701929) claims the limit to be ``10MB``.
- I have tested it myself a month ago. [This commit](https://github.com/JakobGM/astrality/commit/edc36b2708dc5991374090ac395df20c9c47c342) with the large GIF from [this issue](https://github.com/JakobGM/astrality/issues/1) resulted in the error message ``content length exceeded`` when embedding the GIF within the ``README.rst``.

The same size restriction does *not* apply to embedded image files within GitHub issues. The excact restrictions are documented [here](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by di** [comment]
Thanks for digging that up! In that case it seems reasonable to increase the limit to 10MB (as long as camo can handle it), we'll do some investigating and update this issue accordingly.

**Comment by JakobGM** [comment]
Great, I'm glad to help!

Seems that GitHub [also uses camo](https://help.github.com/articles/about-anonymized-image-urls/), so it should (at least in theory) work.

**Comment by di** [comment]
This has been done! The limit is now 10MB. Thanks @JakobGM.

**Comment by erikswed** [comment]
Was the limit lowered again? I can't get a GIF 9MB to work from a remote server!

**Comment by erikswed** [comment]
> Was the limit lowered again? I can't get a GIF 9MB to work from a remote server!

Yea it was a -5Mb works

**Comment by di** [comment]
Currently set to 10000000 bytes, I don't think it's changed. Can you provide a link to a release with a broken image?

**Comment by erikswed** [comment]
Here is my [repo ](https://github.com/erikswed/Greta-100-React-Web-App)and you see the animated GIF playing. It has a size of 4-5MB and I have tried for hours to get a "Bigger" version of this animation but GitHub refuse to display it above 5MB

**Comment by di** [comment]
Are you talking about a Python project on pypi.org or a repo on GitHub? This issue tracker is for the codebase behind pypi.org, we can't help you with your GitHub repo.

**Comment by erikswed** [comment]
> Are you talking about a Python project on pypi.org or a repo on GitHub? This issue tracker is for the codebase behind pypi.org, we can't help you with your GitHub repo.

Good Lord your right LOL

**Comment by fepegar** [comment]
> Currently set to 10000000 bytes, I don't think it's changed. Can you provide a link to a release with a broken image?

Sorry for bumping this (shall I open a new issue?). 

I have a GIF in my README whose size is 9 347 836 bytes and is not being displayed on PyPI. Is that expected?

File: https://github.com/fepegar/torchio/blob/main/docs/images/fpg_progressive.gif
README code: https://github.com/fepegar/torchio/blob/39343c8b9ff529b24aa4a0965f746994742c99cd/README.md?plain=1#L107
PyPI: https://pypi.org/project/torchio/
