### ISSUE TITLE
Merge 'statistics' and 'GitHub Statistics'

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3557]
Right now, we have two sections in the sidebar of a package that deal with statistics:

![screenshot from 2018-04-05 07-21-13](https://user-images.githubusercontent.com/3323703/38350168-1216fa5e-38a2-11e8-92b9-0900e6e1d56a.png)

It would be nice to either group these together, or merge them into one section.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: *If your pull request makes a visual change*, please include a screenshot of your update. This helps our team give you feedback faster.

**Comment by tomfbiz** [comment]
I'm working on this
