### ISSUE TITLE
Keep tabs inside modal

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3558]
## How to reproduce

- Log in
- Use your keyboard only
- Open a modal with your keyboard (either delete release, delete project, delete account)
- Tab through the modal

## What happens

- After you open the modal, you can tab through the content of the modal \o/
- However, once you have tabbed through each button/field, the tab index then moves to the content *under* the modal :(

## What should happen

Once a modal is opened, the user can only tab within the modal.  E.g. there is a tab "loop".

Souce:
https://www.marcozehe.de/2015/02/05/advanced-aria-tip-2-accessible-modal-dialogs/

> On the very last element of your dialog, add a special keyPress handler that traps the forward tab key to redirect it to the first element of the dialog. Otherwise, tab would jump outside the dialog into the surrounding document or to the browser UI, and we don’t want that.

> Likewise, add a keyPress handler to the very first focusable element inside the dialog that traps the shift+tab key combination so the backwards tab order also doesn’t leave the dialog.

**Comment by di** [comment]
Fixed by #3619.
