### ISSUE TITLE
Request trove classifier: Wagtail

### ISSUE THREAD

**Issue by chosak** [pypa/warehouse#3570]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

`Framework :: Wagtail`

It'd be great to have versioned sub-classifiers, e.g. `Framework :: Wagtail :: 2.0`. I can provide a list of common versions if necessary.

## Why do you want to add this classifier?

[Wagtail](https://wagtail.io) is a popular CMS based on Django.

The Wagtail package ecosystem is healthy. There are currently [170 results](https://pypi.org/search/?q=wagtail) on PyPI for "wagtail", and dozens of packages listed on the [Awesome Wagtail](https://github.com/springload/awesome-wagtail) site.

Wagtail's most recent release is version [2.0.1](https://pypi.org/project/wagtail/2.0.1/); the 2.0 release introduced some significant changes versus 1.x. Some Wagtail packages have been updated to be compatible with 2.0, while some only support the older or newer versions.

It would be useful to have a Trove classifier for Wagtail to allow users to more easily find packages on PyPI, especially if they can find packages that are compatible with their version.

**Comment by di** [comment]
@chosak Could you list the major/minor versions that you'd propose to add?

**Comment by di** [comment]
I've added the following classifiers: 

```
Framework :: Wagtail
Framework :: Wagtail :: 1
Framework :: Wagtail :: 2
```
