### ISSUE TITLE
"no verified email addresses" error message generates wrong URL for pypi.org help

### ISSUE THREAD

**Issue by whitequark** [pypa/warehouse#3578]
I'm trying to upload a package using `python3 setup.py sdist upload`. It fails:
```
error: Upload failed (400): User 'whitequark' has no verified email addresses, please verify at least one address before registering a new project on PyPI. See https://upload.pypi.org/help/#verified-email for more information.
```

Sure. The document it links to says:
> You can manage your account's email addresses in your [Profile](https://upload.pypi.org/manage/account/). This also allows for sending a new confirmation email for users who signed up in the past, before we began enforcing this policy.

The Profile link is broken and leads to a 404 page.

Sure. Maybe I could reset my password instead. The help page says:

> You should be able to [reset your password](https://upload.pypi.org/account/reset-password/) on the site; you'll receive an email with a password reset link.

The reset password link is also broken and leads to a 404 page.

In addition there are no account management functions whatsoever linked from anywhere on [upload.pypi.org](https://upload.pypi.org).

**Comment by pradyunsg** [comment]
Ah, the link to Profile should be to pypi.org, not upload.pypi.org.

**Comment by whitequark** [comment]
That worked, thanks!

**Comment by di** [comment]
Looks like this is a bug in how we're generating URLs in our error messages. Thanks for the report!

**Comment by whitequark** [comment]
I think the URL in the error is fine? At least, it correctly leads me to the help page. It's the others that return 404.

**Comment by di** [comment]
The help page is actually at https://pypi.org/help/, the upload domain shouldn't be displaying it.

**Comment by brainwane** [comment]
This affected another user: https://github.com/pypa/packaging-problems/issues/137#issuecomment-379971088
