### ISSUE TITLE
Add "Desktop version" link to mobile page

### ISSUE THREAD

**Issue by nschloe** [pypa/warehouse#3588]
The mobile pypi.org page does not provide the same capabilities as the desktop page. For example, no GitHub statistic in the nav bar.
![p](https://user-images.githubusercontent.com/181628/38490000-2eb0b148-3be8-11e8-93a3-43cb30eba048.jpg)
That's fine though. Sometimes, it may be useful to access the full information on the desktop page even when on mobile. For this, GitHub adds a "Desktop version" button on the bottom of each page.
![dv](https://user-images.githubusercontent.com/181628/38490105-74154e2e-3be8-11e8-9846-8a821b2a2d21.jpg)
Perhaps that's something that warehouse could adopt.

**Comment by brainwane** [comment]
In a sense, this is a regression, since legacy PyPI on mobile showed the user all the functionality of the desktop version. But I'll defer to @nlhkabu on whether this is a blocker for shutting down legacy, and I am inclined to say it's not.

@yeraydiazdiaz is this something you could advise on?

**Comment by brainwane** [comment]
And thanks for filing this, @nschloe! The need for a "desktop version" link has bothered me and I think it's bothered @ewdurbin too, and I'm glad you filed it since we hadn't done so yet!

**Comment by nlhkabu** [comment]
We're using CSS media queries to restyle the site on smaller resolutions, so it looks like we'll have to manually specify the viewport width to do this:

https://stackoverflow.com/questions/36030080/how-to-make-a-responsive-website-render-the-desktop-version-on-a-mobile

**Comment by nlhkabu** [comment]
I've added a WIP PR: https://github.com/pypa/warehouse/pull/3602
This implements the HTML and CSS only.  I will need help to add the appropriate JavaScript.
