### ISSUE TITLE
Provide feedback to users about email delivery issues

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#3590]
Once https://github.com/pypa/warehouse/pull/3580 is merged, Warehouse will begin tracking delivery issues for email addresses we have on file, and can ultimately un-verify a particular email address due to those reasons. We'll want to expose those reasons to end users so that they understand what has occurred to their email addresses on file.

This gives us the following states an email address can be in:

1. Unverified because the email has had a hard failure during delivery.
2. Unverified because the email had too many transient delivery failures, and we've given up sending to that address and we're treating it as a hard failure.
3.  Unverified because the user has marked an email from this address as spam, and their ISP or email provider has forwarded that complaint on to us.
4. Unverified because it is brand new and has yet to be verified:
5. Verified, but we've been having transient issues sending email to this address, if they don't go away this will be upgraded to the (2) case.
6. Verified, no issues.

I can handle wiring this up in the code once we have the design side sorted out for how it should be implemented.

**Comment by brainwane** [comment]
@nlhkabu is this something you could work on, and is it amenable to work at the sprint at EuroPython? @yeraydiazdiaz do you have any thoughts?

Relevant to finishing #3632.

**Comment by yeraydiazdiaz** [comment]
maybe we could use tooltips for this feedback? so it doesn't interfere with the action column

<img width="837" alt="verified-warning" src="https://user-images.githubusercontent.com/6739793/43679135-d3d0cc72-9817-11e8-9a69-e5ec04efa640.png">
