### ISSUE TITLE
Hide version number in the delete version confirmation?

### ISSUE THREAD

**Issue by williamjmorenor** [pypa/warehouse#3612]
Hello currently wharehouse show a confirmation step before to delete a version of a project and show the version to delete.

![image](https://user-images.githubusercontent.com/3522386/38587140-a6f658d8-3cdd-11e8-8a6f-78b295698d66.png)

In the same window it ask to the user to enter the version, github make something similar before delete a repo but do not show the repo name.

Hide the version number sound like a good idea to make really hard to delete the wrong version in warehouse?

**Comment by nlhkabu** [comment]
hi @williamjmorenor - I ran this scenario in user testing, and all participants liked that the release number was there.  Some even copy pasted it.  It is particularly useful if the version naming convention is unusual.

In this case, I don't think that the action is so destructive that we want to make it frustrating for the user to delete the version.  The model should be enough to prevent mistakes.  At the end of the day, we need to treat our users as capable adults... ;)

**Comment by williamjmorenor** [comment]
OK, make sence, thanks.
