### ISSUE TITLE
Not getting account verification emails

### ISSUE THREAD

**Issue by icarito** [pypa/warehouse#3621]
Hi, I'm trying to publish my first pypi package and I'm getting errors that my email isn't verified - but I'm not getting any verification emails even clicking for a resend (no error, it says it was sent) but it never arrives in my mailbox (or spam folder)

**Comment by Humbedooh** [comment]
I can corroborate this - I've tried with multiple addresses, none of them got an email so far.

**Comment by ewdurbin** [comment]
@icarito @Humbedooh Sorry for the disruption, a reconfiguration in our mail sending temporarily broke email sending from 2018-04-11T07:00:00Z til 2018-04-11T10:00:00Z

Emails queued during this time will be retried and should send in the next 30 minutes or so. If they do are not sent, please let us know.

**Comment by fogine** [comment]
Still not getting any account veryfication emails from https://test.pypi.org.

I got account veryfication email from live: https://pypi.org.

**Comment by ewdurbin** [comment]
TestPyPI's email configuration was not fixed at the same time as PyPI's! Sorry for that, should be resolved shortly.
