### ISSUE TITLE
package not available on https://pypi.org

### ISSUE THREAD

**Issue by deadc0de6** [pypa/warehouse#3622]
I recently published a [tool](https://github.com/deadc0de6/cploy) on pypi and although it is available under <https://pypi.python.org/pypi/cploy>, it doesn't appear in searches on <https://pypi.org/search/?q=cploy>.

I'm however able to see it when logged in on <https://pypi.org/manage/projects/> under *Your projects*.

Do I need to do any additional process for it to get indexed and to appear in searches ?

**Comment by ewdurbin** [comment]
Your project is visible at https://pypi.org/pypi/cploy, but our search indexing is currently way behind due to a bug. We're working to resolve this!

**Comment by deadc0de6** [comment]
oh ok, thanks for the info!
