### ISSUE TITLE
RFE: display date in project list

### ISSUE THREAD

**Issue by larsks** [pypa/warehouse#3626]
The project list in the Warehouse allows sorting projects by "Date last updated". Unfortunately, that date isn't displayed in the list itself, which reduces the utility of the sorting. It would be nice to differentiate between "these projects have all been updated recently" vs "the most recent project was udpated last year and the rest more than three years ago".  This helps filter out stale results.

**Comment by brainwane** [comment]
Thanks for the suggestion, @larsks!

**Comment by ewdurbin** [comment]
Is this resolved now?

**Comment by nlhkabu** [comment]
Yes :)
