### ISSUE TITLE
Search results not showing latest release of a package

### ISSUE THREAD

**Issue by mayeut** [pypa/warehouse#3631]
https://pypi.org/search/?q=pybase64 shows the expected package as first result but with 0.2.1 release instead of latest 0.4.0
https://pypi.python.org/pypi?%3Aaction=search&term=pybase64&submit=search shows the correct release.

The same for another package:
https://pypi.org/search/?q=python-miio shows 0.3.8
https://pypi.python.org/pypi?%3Aaction=search&term=python-miio&submit=search shows 0.3.9

**Comment by di** [comment]
The search index hasn't been updated in a while due to some performance issues, see https://github.com/pypa/warehouse/pull/3470

**Comment by ewdurbin** [comment]
resolved.
