### ISSUE TITLE
Incorrect RST rendering

### ISSUE THREAD

**Issue by yuvadm** [pypa/warehouse#3640]
The `README.rst` on https://pypi.org/project/viewstate/ is not rendered at all.

This is despite the following check passing without errors:

```
$ python setup.py check --restructuredtext
running check
warning: check: Title underline too short. (line 2)
```

Interestingly enough, on a previous version  at https://pypi.org/project/viewstate/0.4.0/ it was rendered just fine. Might this have something to do with an `html` code-block that was added?

**Comment by di** [comment]
Thanks for the report. I'm guessing you're talking about https://pypi.org/project/viewstate/0.4.1/, and it seems like you've resolved it now.

FWIW, that check output is indicating that there is an error, and if you `pip install -U readme_renderer`, you'll get a slightly more informative output in the future.
