### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by durganavaneeth** [pypa/warehouse#3642]
No matching distribution found for PyYAML==3.12 (from xxx->-r requirements.txt (line 1))
[Pipeline] echo
pip install failed with error: hudson.AbortException: script returned exit code 1

**Comment by brainwane** [comment]
Hi @durganavaneeth -- what happens if you try that pip install command again with a `-vvv` flag for more verbose reporting?

**Comment by durganavaneeth** [comment]
the issue is fixed and its not actually because of pip package . Its a handshake error which we can bale to fix it :) thanks

**Comment by brainwane** [comment]
Thanks!
