### ISSUE TITLE
Can't upload to test site via Twine

### ISSUE THREAD

**Issue by snelson3** [pypa/warehouse#3644]
My pypirc looks like (with other servers and username/password omitted)

```
[distutils]
index-servers =
   pypitest

[pypitest]
repository=https://test.pypi.org/legacy
username=****
password=****
```

When I try to run the following twine command 

```
twine upload -r pypitest myPackage.whl
```

I get this error

```
RedirectDetected: "https://test.pypi.org/legacy" attempted to redirect to "https://test.pypi.org/legacy/" during upload. Aborting...
```

I am using the latest version of twine as of yesterday and am on High Sierra.

**Comment by AaronV77** [comment]
Hello, please make sure to check that the name is spelt correctly ".pypirc, and change the heading of your pypi test to just test, like this:

```
[distutils]
index-servers =
    pypi
    test

[test]
repository:https://test.pypi.org/legacy/
```

If that still doesn't work, check back. Thanks

**Comment by di** [comment]
Take a look at https://packaging.python.org/guides/using-testpypi/#setting-up-testpypi-in-pypirc

The correct URL is `https://test.pypi.org/legacy/` (with a trailing slash). Does changing it in your `.pypirc` fix your issue?

**Comment by di** [comment]
@AaronV77 The header doesn't need to change, it can be whatever they want, as long as it's the same as what they're passing via `-r`.

**Comment by snelson3** [comment]
Yep adding the trailing slash worked. Thank you!
