### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by matthewdias** [pypa/warehouse#3645]
probably due to the load testing happening right now, this happens for trying to install any package.

```
  Could not fetch URL https://pypi.python.org/simple/upgrade/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement upgrade (from versions: )
No matching distribution found for upgrade
```

**Comment by brewneaux** [comment]
Seconded:

```
13:15:49 13:15:49 C:\Jenkins\workspace\e-WVXSGA3LYY>C:\tools\python\python.exe -m pip install --upgrade pip --verbose 
13:15:49 13:15:49 Getting page https://pypi.python.org/simple/pip/
13:15:49 13:15:49 Starting new HTTPS connection (1): pypi.python.org
13:15:50 13:15:50 "GET /simple/pip/ HTTP/1.1" 302 98
13:15:50 13:15:50 Starting new HTTPS connection (1): pypi.org
13:15:51 13:15:51 Could not fetch URL https://pypi.python.org/simple/pip/: connection error: EOF occurred in violation of protocol (_ssl.c:590) - skipping
13:15:51 13:15:51 1 location(s) to search for versions of pip:
13:15:51 13:15:51 * https://pypi.python.org/simple/pip/
13:15:51 13:15:51 Getting page https://pypi.python.org/simple/pip/
13:15:51 13:15:51 Resetting dropped connection: pypi.python.org
13:15:51 13:15:51 "GET /simple/pip/ HTTP/1.1" 302 98
13:15:51 13:15:51 Starting new HTTPS connection (2): pypi.org
13:15:51 13:15:51 Could not fetch URL https://pypi.python.org/simple/pip/: connection error: EOF occurred in violation of protocol (_ssl.c:590) - skipping
13:15:51 13:15:51 Installed version (7.1.2) is most up-to-date (past versions: none)
13:15:51 13:15:51 Requirement already up-to-date: pip in c:\tools\python\lib\site-packages
13:15:51 13:15:51 Cleaning up...
13:15:51 13:15:51 You are using pip version 7.1.2, however version 9.0.3 is available.
13:15:51 13:15:51 You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

Running in our Jenkins environment:
Windows Server 2012 R 2
Python 2.7.11 (due to infrastructure team requirements)

**Comment by brainwane** [comment]
What versions of OpenSSL and `pip` are you running? What output do you get when you run 

`openssl s_client -connect pypi.org:443`

and

`openssl s_client -connect files.pythonhosted.org:443`

https://mail.python.org/pipermail/python-announce-list/2018-April/011885.html may be relevant.

**Comment by brainwane** [comment]
To upgrade to the latest pip (9.0.3) to connect to the Python Package Index securely:

    curl https://bootstrap.pypa.io/get-pip.py | python

**Comment by rveachkc** [comment]
This is happening for me on pip 9.0.3, Python 3.6.5, RHEL 7.4.

```
# pip -vvv install django
Collecting django
  1 location(s) to search for versions of django:
  * https://pypi.python.org/simple/django/
  Getting page https://pypi.python.org/simple/django/
  Looking up "https://pypi.python.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  https://pypi.python.org:443 "GET /simple/django/ HTTP/1.1" 302 98
  Status code 302 not in [200, 203, 300, 301]
  Looking up "https://pypi.org/simple/django/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org
  Incremented Retry for (url='/simple/django/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/django/
```

```
# curl -V
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.28.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```

```
# curl https://pypi.python.org/simple/django/ --trace-ascii -
== Info: About to connect() to pypi.python.org port 443 (#0)
== Info:   Trying 151.101.184.223...
== Info: Connected to pypi.python.org (151.101.184.223) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
== Info: Server certificate:
== Info:        subject: CN=www.python.org,O=Python Software Foundation,L=Wolfeboro,ST=New Hampshire,C=US,serialNumber=3359300,incorporationState=Delaware,incorporationCountry=US,businessCategory=Private Organization
== Info:        start date: Mar 28 00:00:00 2018 GMT
== Info:        expire date: Sep 27 12:00:00 2018 GMT
== Info:        common name: www.python.org
== Info:        issuer: CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
=> Send header, 93 bytes (0x5d)
0000: GET /simple/django/ HTTP/1.1
001e: User-Agent: curl/7.29.0
0037: Host: pypi.python.org
004e: Accept: */*
005b:
<= Recv header, 20 bytes (0x14)
0000: HTTP/1.1 302 Found
<= Recv header, 17 bytes (0x11)
0000: Server: Varnish
<= Recv header, 16 bytes (0x10)
0000: Retry-After: 0
<= Recv header, 43 bytes (0x2b)
0000: Location: https://pypi.org/simple/django/
<= Recv header, 40 bytes (0x28)
0000: Content-Type: text/html; charset=UTF-8
<= Recv header, 20 bytes (0x14)
0000: Content-Length: 98
<= Recv header, 22 bytes (0x16)
0000: Accept-Ranges: bytes
<= Recv header, 37 bytes (0x25)
0000: Date: Thu, 12 Apr 2018 18:15:53 GMT
<= Recv header, 18 bytes (0x12)
0000: Via: 1.1 varnish
<= Recv header, 19 bytes (0x13)
0000: Connection: close
<= Recv header, 33 bytes (0x21)
0000: X-Served-By: cache-mdw17343-MDW
<= Recv header, 14 bytes (0xe)
0000: X-Cache: HIT
<= Recv header, 17 bytes (0x11)
0000: X-Cache-Hits: 0
<= Recv header, 37 bytes (0x25)
0000: X-Timer: S1523556953.148089,VS0,VE0
<= Recv header, 23 bytes (0x17)
0000: X-Frame-Options: deny
<= Recv header, 33 bytes (0x21)
0000: X-XSS-Protection: 1; mode=block
<= Recv header, 33 bytes (0x21)
0000: X-Content-Type-Options: nosniff
<= Recv header, 41 bytes (0x29)
0000: X-Permitted-Cross-Domain-Policies: none
<= Recv header, 2 bytes (0x2)
0000:
<= Recv data, 98 bytes (0x62)
0000: <html><head><title>302 Found</title></head><body><center><h1>302
0040:  Found</h1></center></body></html>
<html><head><title>302 Found</title></head><body><center><h1>302 Found</h1></center></body></html>== Info: Closing connection 0
```

```
# curl https://pypi.org/simple/django/ --trace-ascii -
== Info: About to connect() to pypi.org port 443 (#0)
== Info:   Trying 151.101.64.223...
== Info: Connected to pypi.org (151.101.64.223) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: NSS error -5961 (PR_CONNECT_RESET_ERROR)
== Info: TCP connection reset by peer
== Info: Closing connection 0
curl: (35) TCP connection reset by peer
```

**Comment by ewdurbin** [comment]
Just as a diagnostic: Every TLS error we've had reported that wasn't strictly lack of support for TLSv1.2 thus far has ended up being a Proxy issue. @matthewdias @brewneaux is your client behind an HTTP proxy or mitm box of some kind?

**Comment by brewneaux** [comment]
@brainwane  - We are not running openssl on this windows machine.

@ewdurbin - Nope, no proxy or anything.

**Comment by ewdurbin** [comment]
load testing is complete for the day. is this still reproducible?

**Comment by pydsigner** [comment]
I have an SSL issue that does not reproduce after the switch back.

```
PS C:\Users\ > python -V
Python 3.6.1
PS C:\Users\ > python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2k  26 Jan 2017
PS C:\Users\ > python -m pip install -vU pip
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
1 location(s) to search for versions of pip:
* https://pypi.python.org/simple/pip/
Getting page https://pypi.python.org/simple/pip/
Looking up "https://pypi.python.org/simple/pip/" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
"GET /simple/pip/ HTTP/1.1" 302 98
Status code 302 not in [200, 203, 300, 301]
Looking up "https://pypi.org/simple/pip/" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.org
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping
Installed version (9.0.1) is most up-to-date (past versions: none)
Requirement already up-to-date: pip in c:\users\e99689\appdata\local\programs\python\python36\lib\site-packages
Cleaning up...
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

I can access the page in web browsers fine, but not with requests. Hoping it's not some nasty VPN issue because I reproduced it on 3 other computers on the same network, all running Windows 10/Python 3.6

**Comment by matthewdias** [comment]
No proxy here @ewdurbin. still reproducing.

**Comment by matthewdias** [comment]
upgrading to pip 9.0.3 did the trick

**Comment by cranticumar** [comment]
Python: 2.7.3
OS: Windows 7

c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS
 certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarn
ing.
  InsecurePlatformWarning
  Could not fetch URL https://pypi.python.org/simple/pyopenssl/: There was a problem confirming the ssl certificate: [Errno 1] _ssl.c:504: e
rror:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version - skipping
  Could not find a version that satisfies the requirement pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" (from urllib3==1.17
) (from versions: )
No matching distribution found for pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" (from urllib3==1.17)
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is n
ot available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a n
ewer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarn
ing.
  InsecurePlatformWarning

**Comment by alex** [comment]
Your easiest option is to use a newer release of Python.

**Comment by cranticumar** [comment]
I cannot move to higher versions of Python due to heavy dependencies I have for my project. I might run into compatibility issues or might need a lot of code changes.

This started happening from last 1 week.

Just FYI.... PIP version we use: 9.0.1

**Comment by alex** [comment]
I would not expect significant breakages moving to a newer Python 2.7 release.

This is caused by the deprecation and removal of TLS1.0/1.1, Python 2.7.3 on Windows comes with an older version of OpenSSL: https://status.python.org/incidents/hdx7w97m5hr8

Your other option if you're stuck on exactly Python 2.7.3 is to build your own Python linked against a newer OpenSSL.

**Comment by brewneaux** [comment]
This is still an issue for us: we are not running any different version of SSL than what comes with Python 2.7.11, and cannot upgrade pip either:

```
13:31:29 13:31:29 C:\Jenkins\workspace\4-WEX55NLNAH>C:\tools\python\python.exe -m pip install --upgrade pip --verbose 
13:31:29 13:31:29 Getting page https://pypi.python.org/simple/pip/
13:31:29 13:31:29 Starting new HTTPS connection (1): pypi.python.org
13:31:30 13:31:30 "GET /simple/pip/ HTTP/1.1" 302 98
13:31:30 13:31:30 Starting new HTTPS connection (1): pypi.org
13:31:31 13:31:31 Could not fetch URL https://pypi.python.org/simple/pip/: connection error: EOF occurred in violation of protocol (_ssl.c:590) - skipping
13:31:31 13:31:31 1 location(s) to search for versions of pip:
13:31:31 13:31:31 * https://pypi.python.org/simple/pip/
13:31:31 13:31:31 Getting page https://pypi.python.org/simple/pip/
13:31:31 13:31:31 Resetting dropped connection: pypi.python.org
13:31:31 13:31:31 "GET /simple/pip/ HTTP/1.1" 302 98
13:31:31 13:31:31 Starting new HTTPS connection (2): pypi.org
13:31:32 13:31:32 Could not fetch URL https://pypi.python.org/simple/pip/: connection error: EOF occurred in violation of protocol (_ssl.c:590) - skipping
13:31:32 13:31:32 Installed version (7.1.2) is most up-to-date (past versions: none)
13:31:32 13:31:32 Requirement already up-to-date: pip in c:\tools\python\lib\site-packages
13:31:32 13:31:32 Cleaning up...
13:31:32 13:31:32 Starting new HTTPS connection (1): pypi.python.org
13:31:33 13:31:33 "GET /pypi/pip/json HTTP/1.1" 302 98
13:31:33 13:31:33 Starting new HTTPS connection (1): pypi.org
13:31:33 13:31:33 There was an error checking the latest version of pip
13:31:33 13:31:33 Traceback (most recent call last):
13:31:33 13:31:33   File "C:\tools\python\lib\site-packages\pip\utils\outdated.py", line 126, in pip_version_check
13:31:33 13:31:33     headers={"Accept": "application/json"},
13:31:33 13:31:33   File "C:\tools\python\lib\site-packages\pip\_vendor\requests\sessions.py", line 477, in get
13:31:33 13:31:33     return self.request('GET', url, **kwargs)
13:31:33 13:31:33   File "C:\tools\python\lib\site-packages\pip\download.py", line 373, in request
13:31:33 13:31:33     return super(PipSession, self).request(method, url, *args, **kwargs)
13:31:33 13:31:33   File "C:\tools\python\lib\site-packages\pip\_vendor\requests\sessions.py", line 465, in request
13:31:33 13:31:33     resp = self.send(prep, **send_kwargs)
13:31:33 13:31:33   File "C:\tools\python\lib\site-packages\pip\_vendor\requests\sessions.py", line 594, in send
13:31:33 13:31:33     history = [resp for resp in gen] if allow_redirects else []
13:31:33 13:31:33   File "C:\tools\python\lib\site-packages\pip\_vendor\requests\sessions.py", line 196, in resolve_redirects
13:31:33 13:31:33     **adapter_kwargs
13:31:33 13:31:33   File "C:\tools\python\lib\site-packages\pip\_vendor\requests\sessions.py", line 573, in send
13:31:33 13:31:33     r = adapter.send(request, **kwargs)
13:31:33 13:31:33   File "C:\tools\python\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 46, in send
13:31:33 13:31:33     resp = super(CacheControlAdapter, self).send(request, **kw)
13:31:33 13:31:33   File "C:\tools\python\lib\site-packages\pip\_vendor\requests\adapters.py", line 431, in send
13:31:33 13:31:33     raise SSLError(e, request=request)
13:31:33 13:31:33 SSLError: EOF occurred in violation of protocol (_ssl.c:590)
```

**Comment by alex** [comment]
Are you running on a network with a proxy or MITM device of some sort?

**Comment by alex** [comment]
Can you tell me what `python -c "import ssl; print(ssl.OPENSSL_VERSION)` prints?

**Comment by brewneaux** [comment]
OpenSSL 1.0.2d 9 Jul 2015

**Comment by alex** [comment]
Something else is going on here, the errors you're seeing are unrelated to the TLS1.2 requirement, assuming you aren't behind a proxy of any sort.

**Comment by brainwane** [comment]
Folks in this thread might like to review #3720 which adds TLS deprecation help to http://pypi.org/help/.

**Comment by pydsigner** [comment]
Update: the CERTIFICATE_VERIFY_FAILED issue was indeed a network policy issue and has been resolved.

**Comment by awallace-cray** [comment]
We have 18 nightly CI build failures, so far, all with errors with CERTIFICATE_VERIFY_FAILED from pip install or similar. For example
```
python /ptmp/jenkins/<snip>/chpl-virtualenv/bin/pip install \
-U --force-reinstall  -r chpldoc-requirements.txt 
Collecting Jinja2==2.8 (from -r chpldoc-requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /packages/96/a1/c56bc4d99dc2663514a8481511e80eba8994133ae75eebdadfc91a5597d9/Jinja2-2.8-py2.py3-none-any.whl
```
Most occurred between 7:00-7:45am UTC, with a few outliers as recently as 13:03 UTC.

**Comment by alex** [comment]
Certificate verify failed is a different error from the TLS1.0 issues that this issue is for. I suspect we're not going to be able to diagnose it without more info on your system and network.

**Comment by awallace-cray** [comment]
SLES-12 Linux. 
OpenSSL 1.0.2j-fips  26 Sep 2016. 
Corporate LAN, no proxy. 

Right now, these commands work. So does pip install. 
openssl s_client -connect pypi.org:443
openssl s_client -connect pypi.python.org:443
openssl s_client -connect files.pythonhosted.org:443

**Comment by alex** [comment]
Can you paste the certificate (everything between `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` ) you see when you run the `openssl s_client` command?

**Comment by dstufft** [comment]
System time wrong?

**Comment by awallace-cray** [comment]
No other indications of incorrect system time, AFAIK. 
I should have mentioned, these errors occurred across several machines, all SLES-12. A few outliers may have a different openssl version- the other 8 machines are identical.

**Comment by awallace-cray** [comment]
Found a bit of legacy on our side, left over from years ago and mostly forgotten. 
`$HOME/.pip/pip.conf` contained `[global] cert = DigiCert_High_Assurance_EV_Root_CA.pem`
That cert file exists. 

A developer here thought removing that pip.conf file helped avoid the CERTIFICATE_VERIFY_FAILED. 
So I removed the copy that Jenkins sees, even though it didn't seem to make a difference to me.

**Comment by alex** [comment]
You should remove that option, PyPI does not guarantee what CA it'll use, and in fact while pypi.org uses that DigiCert CA, files.pythonhosted.org which serves the actual files is using a different CA.

**Comment by awallace-cray** [comment]
> are you still experiencing these problems?

No, None seen since my last comment. 
Thanks.

**Comment by matthewdias** [comment]
gonna close this for now. feel free to reopen if necessary.

**Comment by MheniMerz** [comment]
Hi all.

i'm having the same issue when trying to run [devstack](https://docs.openstack.org/devstack/latest/) which is trying to get `pip` using the following command *i added the verbose parameter*
```cmd
sudo -H -E python /opt/stack/devstack/files/get-pip.py -c /opt/stack/devstack/tools/cap-pip.txt --verbose
```
i get this output, and it just hangs there forever then tries four more times and quits.
```
Created temporary directory: /tmp/pip-ephem-wheel-cache-WNf2he
Created temporary directory: /tmp/pip-req-tracker-YNDzMb
Created requirements tracker '/tmp/pip-req-tracker-YNDzMb'
Created temporary directory: /tmp/pip-install-qbbm3e
Setting pip!=8,<10 (from -c /opt/stack/devstack/tools/cap-pip.txt (line 1)) extras to: ()
Collecting pip!=8,<10 (from -c /opt/stack/devstack/tools/cap-pip.txt (line 1))
  1 location(s) to search for versions of pip:
  * https://pypi.org/simple/pip/
  Getting page https://pypi.org/simple/pip/
  Looking up "https://pypi.org/simple/pip/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org:443
```
My machine is sitting behind a proxy, that uses a **white list** to allow some domain names, these domains are allowed.
```
# python
.pypa.io
.python.org
.pypi.org
.pythonhosted.org
```
and also we use our **own certificate**

i can get the page with a curl `curl -v pypi.org:443` but this is the output i get with the verbose mode.
```
* Rebuilt URL to: www.pypi.org:443/
*   Trying X.X.X.X...
* Connected to X.X.X.X (X.X.X.X) port XXYY (#0)
> GET http://www.pypi.org:443/ HTTP/1.1
> Host: www.pypi.org:443
> User-Agent: curl/7.47.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 503 Service Unavailable
< Server: squid/3.5.12
< Mime-Version: 1.0
< Date: Fri, 24 Aug 2018 15:55:36 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3601
< X-Squid-Error: ERR_CONNECT_FAIL 101
< Vary: Accept-Language
< Content-Language: en
< X-Cache: MISS from dns
< X-Cache-Lookup: MISS from dns:XXYY
< Via: 1.1 dns (squid/3.5.12)
< Connection: close
< 
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
...
</body></html>
* Closing connection 0
```

but when i run an openssl i get nothing `sudo openssl s_client -connect pypi.org:443`

Please any help is appreciated.
this thing is driving me nuts.
Thank you.

**Comment by ewdurbin** [comment]
@MheniMerz the 503 response is coming from squid, which is a well known HTTP caching/forwarding service. In order to understand what is going on, you'll need to contact the administrators of the squid proxy for more information.

**Comment by MheniMerz** [comment]
i can see from the squid access logs that there is a TCP_MISS for www.pypi.org.

which means the proxy doesn't have the content stored in the cache and it should go out to the net to get the content.

**Comment by MheniMerz** [comment]
i have managed to force pip to use the proxy by modifying the command to the following

```cmd
sudo -H -E python /opt/stack/devstack/files/get-pip.py \
    --proxy="http://X.X.X.X:XXYY" \
    -c /opt/stack/devstack/tools/cap-pip.txt --verbose
```
but now I'm getting a new error suggesting that my certificate is not enough.

```
  Starting new HTTPS connection (1): pypi.org:443
  Incremented Retry for (url='/simple/pip/'): Retry(total=4, connect=None, 
  read=None, redirect=None, status=None)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) 
  after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] 
  certificate verify failed (_ssl.c:590)'),)': /simple/pip/
```

anyone had this before?

**Comment by ewdurbin** [comment]
Hi @MheniMerz, maintainers of PyPI aren't equipped to assist with specific setups involving corporate proxies, firewalls, caching proxies, or other "Man in the Middle" type infrastructure.

The error above indicates that you may still be connecting to such a proxy.

The only guidance I can provide would be:
  - ensure you are using an up to date version of pip, you can upgrade pip without PyPI using https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py
  - if the problem persists, it _appears_ that you may still be connecting via a proxy. you should ensure that the the Certificate Authority for that proxy is in the trust store that pip uses, though I'm not sure how to confirm that.

**Comment by MheniMerz** [comment]
thank you for your help. problem was solved by adding some domain names as `trusted-host`

```
sudo -H -E python /opt/stack/devstack/files/get-pip.py \
    --proxy="http://X.X.X.X:XXYY" \
    --trusted-host pypi.org\
    --trusted-host files.pythonhosted.org
    -c /opt/stack/devstack/tools/cap-pip.txt --verbose
```
But since the script I'm using has hundreds of similar calls to pip. is there a config file or somewhere i can set all calls to use these parameters instead of changing them one by one ?
Thanks again.
Mheni

**Comment by di** [comment]
See https://pip.pypa.io/en/stable/user_guide/#configuration

**Comment by dtantsur** [comment]
Seems broken (again?) without a way to recover on the latest CentOS 7 cloud image:
```
$ sudo python get-pip.py --trusted-host pypi.org --trusted-host files.pythonhosted.org --verbose
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Created temporary directory: /tmp/pip-ephem-wheel-cache-_S3U42
Created temporary directory: /tmp/pip-req-tracker-6YkdVV
Created requirements tracker '/tmp/pip-req-tracker-6YkdVV'
Created temporary directory: /tmp/pip-install-HpbS35
Collecting pip
  1 location(s) to search for versions of pip:
  * https://pypi.org/simple/pip/
  Getting page https://pypi.org/simple/pip/
  Starting new HTTPS connection (1): pypi.org:443
  Incremented Retry for (url='/simple/pip/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL] unknown error (_ssl.c:618)'),)': /simple/pip/
  Starting new HTTPS connection (2): pypi.org:443
fips.c(145): OpenSSL internal error, assertion failed: FATAL FIPS SELFTEST FAILURE
Aborted
```
Versions:
```
$ python --version
Python 2.7.5
$ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2k-fips  26 Jan 2017
```

No tricks I've tried so far have helped. VirtualEnv behaves the same way. `--trusted-host` doesn't change anything, nor does `PYTHONHTTPSVERIFY=0`. Updating pip is not possible because `get-pip.py` fails with the same error as you can see above. I tried to update pip from a tarball in a venv, but it did not help either. And thanks to the whole TLS hype, the new pypi.org doesn't have a plain HTTP version. :(

Any hints?

**Comment by di** [comment]
@dtantsur I can't reproduce:

```
$ docker run -it centos:7
[root@d1c5b696f7cd /]# curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
[root@d1c5b696f7cd /]# python get-pip.py
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl (1.4MB)
     |################################| 1.4MB 1.2MB/s
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
     |################################| 583kB 7.8MB/s
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-19.1 setuptools-41.0.1 wheel-0.33.1
[root@d1c5b696f7cd /]# python --version
Python 2.7.5
[root@d1c5b696f7cd /]# python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2k-fips  26 Jan 2017
[root@d1c5b696f7cd /]#

**Comment by dtantsur** [comment]
Yeah, it seems to be something tricky. As I noted, the only non-standard thing about my VM is that it's a nested VM. I'll work on a better reproducer, if it's possible.
