### ISSUE TITLE
Rename netcdftime to cftime

### ISSUE THREAD

**Issue by jhamman** [pypa/warehouse#3646]
Per https://github.com/Unidata/cftime/issues/36, we are renaming an existing repository. `netcdftime` is being renamed `cftime`. 

My understanding is that the best way to request an admin's help for renaming a package is via this issue tracker. If that is not the case, feel free to close and direct me to a more appropriate venue.

**Comment by di** [comment]
@jhamman Renaming an existing package isn't really advisable. Consider that anyone installing `cftime==1.0.0a2` would still need to `import netcdftime`, this would probably be confusing for your users. Also, anything currently depending on the `netcdftime` project would suddenly have their dependencies broken.

Considering that `netcdftime` is relatively new and only has two alpha releases, perhaps it would be better to just register the `cftime` project and publish future releases there, and either deprecate or deleting the `netcdftime` project?

**Comment by jhamman** [comment]
We don't really have existing users as such. I am fine creating a new package though so I have done that. Thanks for the input.
