### ISSUE TITLE
Cannot fetch index base URL https://pypi.python.org/simple/

### ISSUE THREAD

**Issue by fsignoret** [pypa/warehouse#3654]
Hello,

While performing command: 
pip install packaging "subprocess32>=3.2.7"

I am getting the following error:

Downloading/unpacking packaging
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement packaging
Cleaning up...
No distributions at all found for packaging
Storing debug log for failure in /root/.pip/pip.log

This started to appear yesterday, and continues today.

Regards,
Florian

**Comment by ewdurbin** [comment]
Hello @fsignoret thanks for your bug report.

Can you note the version of:

- Operating System
- TLS/SSL Implementation
- Python
- pip

In the environment?

Also the output of `pip install -vvv packaging "subprocess32>=3.2.7"` would be helpful.

**Comment by fsignoret** [comment]
Operating system: Linux 3.10.0-514.el7.x86_64
OpenSSL 1.0.1f 6 Jan 2014
Python 2.7.6
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
[pip-install-output.txt](https://github.com/pypa/warehouse/files/1906965/pip-install-output.txt)

**Comment by ewdurbin** [comment]
@fsignoret based on your replies, I see you're running Ubuntu Trusty (14.04)

in an environment prepared similarly with the latest patches from ubuntu:

```
root@d6ad985b3cbf:/# openssl version
OpenSSL 1.0.1f 6 Jan 2014
root@d6ad985b3cbf:/# python --version
Python 2.7.6
root@d6ad985b3cbf:/# pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
root@d6ad985b3cbf:/# pip install packaging "subprocess32>=3.2.7"
Downloading/unpacking packaging
  Downloading packaging-17.1-py2.py3-none-any.whl
Downloading/unpacking subprocess32>=3.2.7
  Downloading subprocess32-3.2.7.tar.gz (54kB): 54kB downloaded
  Running setup.py (path:/tmp/pip_build_root/subprocess32/setup.py) egg_info for package subprocess32
    
    warning: no files found matching '*.h'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.hg*'
Downloading/unpacking pyparsing>=2.0.2 (from packaging)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from packaging)
Installing collected packages: packaging, subprocess32, pyparsing
  Running setup.py install for subprocess32
    building '_posixsubprocess' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c _posixsubprocess.c -o build/temp.linux-x86_64-2.7/_posixsubprocess.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/_posixsubprocess.o -o build/lib.linux-x86_64-2.7/_posixsubprocess.so
    
    warning: no files found matching '*.h'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.hg*'
Successfully installed packaging subprocess32 pyparsing
Cleaning up...
```

Specific package versions (from `dpkg -l`):

```
python                           2.7.5-5ubuntu3
python-pip                       1.5.4-1ubuntu4
openssl                          1.0.1f-1ubuntu2.24
```

Can you confirm you're running the latest of all those packages?

**Comment by fsignoret** [comment]
python         2.7.5-5ubunt
python-pip     1.5.4-1ubunt
openssl        1.0.1f-1ubun

root@8c41fcbc2d07:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

**Comment by ewdurbin** [comment]
@fsignoret not clear from your output if you've truncated the results or if you have not applied the latest versions, note the suffixes on the package versions in my output.

**Comment by fsignoret** [comment]
python                                       2.7.5-5ubuntu3
python-pip                                 1.5.4-1ubuntu4
openssl                                      1.0.1f-1ubuntu2

**Comment by ewdurbin** [comment]
@fsignoret please update openssl and try again, it appears to be several patch levels behind.

**Comment by fsignoret** [comment]
Upgrading openssl fixes it.
Thanks!

**Comment by fsignoret** [comment]
Hello,
The issue is back.
Looks like the openssl upgrade has actually not fixed it.

**Comment by ewdurbin** [comment]
@fsignoret can you provide logs.

output of `pip install` with `-vvv` flag at least.

**Comment by fsignoret** [comment]
Here are the logs

[error_python.txt](https://github.com/pypa/warehouse/files/1927963/error_python.txt)

Things to note:
- error appeared between Apr 16, 2018 12:03 PM and Apr 17, 2018 1:59 PM
- it is working from our local machine, but is failing from amazon machine

**Comment by fsignoret** [comment]
Can this help?

root@8c41fcbc2d07:/# wget https://pypi.python.org/simple/packaging/
--2018-04-19 14:06:07--  https://pypi.python.org/simple/packaging/
Resolving pypi.python.org (pypi.python.org)... 151.101.0.223, 151.101.64.223, 151.101.128.223, ...
Connecting to pypi.python.org (pypi.python.org)|151.101.0.223|:443... connected.
Unable to establish SSL connection.

**Comment by ewdurbin** [comment]
@fsignoret from the same machine (`8c41fcbc2d07`) please execute

`openssl s_client -connect pypi.python.org:443`
`openssl s_client -connect pypi.org:443`
`openssl s_client -connect files.pythonhosted.org:443`

and provide the output. it sounds like your client does not support TLSv1.2

**Comment by fsignoret** [comment]
[openssl_output.txt](https://github.com/pypa/warehouse/files/1928083/openssl_output.txt)

**Comment by fsignoret** [comment]
I finally decided to build my docker image on a local machine to avoid the problem.
