### ISSUE TITLE
Expand tested cases for custom URL icons; remove Gratipay

### ISSUE THREAD

**Issue by bskinn** [pypa/warehouse#3658]
#3643 successfully added the GH stats pane for projects with `www.github.com` homepage URLs, but it didn't update the template so that the Octocat icon shows next to the 'Homepage' link.

[Project](https://pypi.org/project/rmsd/) using `https://github.com/...` homepage link:

![with gh-icon](https://user-images.githubusercontent.com/11325439/38738801-1079d850-3f01-11e8-888e-1ef6a3c82e73.png)

[Project](https://pypi.org/project/sphobjinv/) using `https://www.github.com/...` homepage link:

![without gh-icon](https://user-images.githubusercontent.com/11325439/38738843-2fa470e6-3f01-11e8-8ca6-3c262a946c29.png)

**Barring any strong objections w/in the next couple of hours, I'll open a PR to fix by editing the [`url_icon` template macro](https://github.com/pypa/warehouse/blob/3390621ddc49c0708b9ae767de6356820276f22e/warehouse/templates/packaging/detail.html#L22-L23) appropriately.**

**Comment by bskinn** [comment]
Actually, it looks like all of the special-icon cases for Github, Bitbucket, Gratipay, and Twitter should perhaps be expanded?

**Comment by di** [comment]
@bskinn Sounds good. Gratipay is dead (RIP) so maybe we should stop special-casing their links.
