### ISSUE TITLE
Request trove classifier: Eclipse Public License 2.0 (EPL-2.0)

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3660]
Request to add a new Trove classifier, copied from @amotl's note in https://github.com/pypa/pypi-legacy/issues/794 .

## The name of the classifier you would like to add
License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)

## Why do you want to add this classifier?
Dear PyPI team,

i am following up on #722, thanks @brainwane for bringing this up again.

The fine [mqttwarn project](https://github.com/jpmens/mqttwarn) is using the Eclipse Public License 1.0 [1] and is probably about to update this to the version 2.0 [2] of the same license. However, the [list of Trove classifiers for PyPI](https://pypi.python.org/pypi?%3Aaction=list_classifiers) does not include the updated version yet.

The list already contains an entry for version 1.0:
`License :: OSI Approved :: Eclipse Public License 1.0 (EPL-1.0)`

So, could we include the classifier for the new version?
`License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)`

Thanks in advance and keep up the good work on PyPI!

[1] https://www.eclipse.org/org/documents/epl-v10.php
[2] https://www.eclipse.org/legal/epl-2.0/

**Comment by amotl** [comment]
Thanks @brainwane! Let me add that the EPL-2.0 license already seems to have been aproved by the OSI: https://opensource.org/licenses/EPL-2.0.

This could make the designated inclusion into the list of Trove classifiers more easy as we don't have to wait for an approval like it happened with the [EUPL 1.2 license](https://github.com/pypa/pypi-legacy/issues/722).

Thanks again for your efforts!

**Comment by di** [comment]
I've added the `License :: OSI Approved :: Eclipse Public License 2.0 (EPL-2.0)` classifier, thanks!

**Comment by amotl** [comment]
Thanks, @di!
