### ISSUE TITLE
Package publication error

### ISSUE THREAD

**Issue by sr-murthy** [pypa/warehouse#3672]
I'm a co-author of the oasislmf package

https://pypi.python.org/pypi?:action=display&name=oasislmf&version=1.0.8

but I'm unable to upload a new version of this `1.0.9`. I normally use `twine`. I'm getting the following error message

    HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/

I have checked that my login credentials in the `.pypirc` file are correct, and this is the first time I've had problems in publishing the package.

I'm using `twine` version `1.10.0`, Python 2.7.10 (in a virtual env.), on Mac OS X 10.13.3.

**Comment by ewdurbin** [comment]
Hello @sr-murthy!

I see two upload attempts recently matching the environment you specified and a username that is associated with the oasislmf package. I also note that the username has successfully logged into PyPI recently.

Assuming you can log in to pypi.org with the username/password in your `.pypirc`, I'd first ask that you try the upload with the latest release of twine `1.11.0`.

The error message you're receiving indeed indicates that the password being supplied to upload.pypi.org is incorrect, so it may be that the upload client (`twine` in this case) is sending the wrong username and password.

**Comment by sr-murthy** [comment]
This is bizarre - the password I thought worked, and which was saved in the `.pypirc` file, did not work. So I requested a password reset. On clicking the link and setting the new password I receive the following error page

![screen shot 2018-04-14 at 18 59 54](https://user-images.githubusercontent.com/9358070/38771177-3cb46c44-4016-11e8-80c9-6dc2c913fc81.png)

**Comment by ewdurbin** [comment]
@sr-murthy this is very likely a breaking change in warehouse that broke password resets for pypi-legacy.

Please use https://pypi.org/account/request-password-reset/ to request a reset. Sorry for the confusion.

**Comment by sr-murthy** [comment]
Thanks. Could you possibly check whether I have two separate emails associated with a single account, or whether there are two accouns with different emails? The password reset email from that last link was sent to my personal email, which is the primary email I use for commits to GitHub. Previously another password reset email I requested via pypi.org was sent to my work email.

**Comment by sr-murthy** [comment]
After upgrading `twine` I managed to publish it. Thanks.

**Comment by ewdurbin** [comment]
@sr-murthy once you're logged in to pypi.org, you can view and manage your email addresses at https://pypi.org/manage/account/. I see two addresses associated with one account. Resets are sent to the one marked as Primary.
