### ISSUE TITLE
Open issues count on PyPI is open issues + open pull requests on GitHub

### ISSUE THREAD

**Issue by jrbourbeau** [pypa/warehouse#3673]
The "Open issues" number currently quoted on PyPI for a project is the number of open issues plus the number of open pull requests for the project GitHub repo. 

For instance (at the time of submitting this issue) the dask project has 405 open issues on PyPI (https://pypi.org/project/dask/), while on the corresponding GitHub repo (https://github.com/dask/dask/) there are 364 open issues and 41 open pull requests. 

This may not be an error as I could be misinterpreting what "Open issues" should mean on PyPI. But my initial interpretation is that the number of open issues on PyPI should match the number of open issues on GitHub.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
Github considers pull requests to be "issues" and doesn't provide a way in the API we're using to discern between the two without making multiple requests. From [here](https://developer.github.com/v3/issues/):

> As far as the API is concerned, every pull request is an issue, but not every issue is a pull request.

We might want to change "Open Issues" to something like "Issues/PRs" instead.
