### ISSUE TITLE
Project page not purged when new release is made

### ISSUE THREAD

**Issue by pv** [pypa/warehouse#3694]
I uploaded a release on Pypi using twine, but not all files at once so twine was run multiple times.
The "Download files" page on warehouse now shows fewer files than the page on old pypi:
https://pypi.org/project/scipy/1.1.0rc1/#files
vs.
https://pypi.python.org/pypi/scipy

It may be some cache effect, but on the other hand it's been several hours now and it has not updated.
(If it'll eventually sync, that's ok with me, but opening an issue here just in case this is some issue with warehouse.)

**Comment by ewdurbin** [comment]
unfortunately logs for that celery task are long gone. anecdotally I haven't seen any purge api calls fail to Fastly, though we should be retrying in that case.

this project uploaded a large number of files, and at least _one_ of the purges "stuck".

we may want to ask Fastly if they begin debouncing at some point if we issue 10+ purges for the same key in quick succession.

**Comment by dstufft** [comment]
Yea I know what this is, the ``ORIGIN_CACHE`` variable is still pointing to the old service_id, we need to update it in the configuration to point to the new one. That's a secure variable so I can't recover it, so whenever @ewdurbin wakes up he can do it :)

We can also probably delete ``FASTLY_KEY`` and ``FASTLY_SERVICE`` from the configuration, the ``bin/release`` used that, but it doesn't anymore.

**Comment by phihag** [comment]
Can somebody do the magic manual purge for my package `ipaddress` as well?

**Comment by ewdurbin** [comment]
configuration updated. it's deploying now. after that I'll issue a purge all, after which purges should be working with the new service id.

**Comment by papachoco** [comment]
Thanks a lot

**Comment by allfro** [comment]
Hi all,

I appear to have the same issue with my package 'canari'. Version 3.3.1 is not showing up as a candidate when using pip. It works when using easy_install for some reason.
