### ISSUE TITLE
pypi.org showing older releases as default

### ISSUE THREAD

**Issue by hugovk** [pypa/warehouse#3699]
This doesn't happen on every project, but here's three I have found.

https://pypi.python.org/pypi/gevent/ shows the latest newest 1.3b1 (released two days ago). Great!

https://pypi.org/project/gevent/ shows an older 1.2.2 (Jun 5, 2017). Why not 1.3b1?

https://pypi.org/project/gevent/#history does know about the newest 1.3b1, as well as intermediate 1.3a2 and 1.3a1.

How come the latest is not shown? Is it a project setting, a bug, or something else?

---

The JSON endpoints show the same as above: 
* Newest: https://pypi.python.org/pypi/gevent/json
* Older: https://pypi.org/pypi/gevent/json

---

Some other projects showing different versions:

django-filter:
* Newest: https://pypi.python.org/pypi/django-filter/ 2.0.0.dev1 (Oct 24, 2017)
* Older: https://pypi.org/project/django-filter/ 1.1.0 (Oct 19, 2017)

Twisted:
* Newest: https://pypi.python.org/pypi/Twisted/ 18.4.0rc1 (Mar 31, 2018)
* Older: https://pypi.org/project/Twisted/ 17.9.0 (Sep 23, 2017)

(I don't manage any of these projects.)

**Comment by dstufft** [comment]
Warehouse only shows the latest non-prerelease version (because this is what pip will actually install), unless only pre-releases exist.

**Comment by hugovk** [comment]
Thanks!
