### ISSUE TITLE
Where to report spam packages?

### ISSUE THREAD

**Issue by hongquan** [pypa/warehouse#3701]
I found these spam/junk packages:

https://pypi.org/project/spam/
https://pypi.org/project/0/

Is there any place to report spam packages?

**Comment by di** [comment]
Thanks for the report @hongquan. Neither of those look like actual spam, they just seem to be people testing releases, so they're fine to stay (there are a lot of packages like this).

**Comment by hongquan** [comment]
Ah, thanks for explanation.
