### ISSUE TITLE
New PyPI: can't download some packages' files because of broken redirect

### ISSUE THREAD

**Issue by juraseg** [pypa/warehouse#3704]
Can't download package files for some packages. pip outputs error "TooManyRedirects: Exceeded 30 redirects." Same issue when downloading in browser.

The packages in question:
- argon2_cffi (https://pypi.org/project/argon2_cffi/18.1.0/#files)
- argon2pure (https://pypi.org/project/argon2pure/#files)
(May be there are more, I only checked these too).

It just happened that I was playing with argon2_cffi right before [this](https://github.com/pypa/warehouse/milestone/1) happened, the packages were working just fine. Then I went away for an hour, and when I was back I couldn't install the package using pip.

**Comment by alex** [comment]
Currently being tracked here: https://status.python.org/incidents/1y1f44q6srh2

**Comment by ewdurbin** [comment]
duplicate #3702
