### ISSUE TITLE
No search results on pypi.org

### ISSUE THREAD

**Issue by davisagli** [pypa/warehouse#3711]
I'm not currently seeing any search results; https://pypi.org/search/?q=numpy is an example but I'm getting 0 results regardless of the query.

**Comment by ewdurbin** [comment]
@davisagli thanks for report, investigating.

**Comment by ewdurbin** [comment]
we've rolled back the initial attempt at incremental index updates for now as they were leading to this occasionally.

**Comment by vabi** [comment]
It is happening... again. Search from pip isn't working as well (if it's related).
