### ISSUE TITLE
Confusing package with name "all" on pypi

### ISSUE THREAD

**Issue by asmaier** [pypa/warehouse#3713]
When typing

    pip install --upgrade all

I expected to upgrade all existing installed packages. Instead a package named "all" was installed. This package https://pypi.org/project/all/ doesn't provide any information on what it does and who the author is. Because of the confusing name, I suggest this package should be renamed or maybe removed from pypi.

**Comment by ewdurbin** [comment]
Thank you. This project has been pulled by administrative action.

Primarily based on the concern of typosquatting such a command invocation.
