### ISSUE TITLE
Behavior Difference in Search

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#3717]
The previous search let you OR multiple things together to get the results for both, you could see this in the behavior of ``pip search pip initools``, however the new search is not returning both. We need to decide if this is now expected behavior, or fix it.

**Comment by ewdurbin** [comment]
@dstufft I believe this is resolved in #3827 can you confirm?

**Comment by wimglenn** [comment]
This seems resolved in warehouse (using xmlrpc client directly to search for "pip initools" is working ok).  But still would need to be addressed in pip cli.  

    pip search pip initools  # crash, unhandled error in xml rpc call time
    pip search "pip initools"  # does not return results

**Comment by jamadden** [comment]
This certainly seems fixed to me:

```console
$ pip --version
pip 18.1 from //lib/python3.7/site-packages/pip (python 3.7)
$ pip search pip | grep -i initools
$ pip search initools | grep -i initools
INITools (0.3.1)  - Tools for parsing and using INI-style files
$ pip search pip initools | grep -i initools
INITools (0.3.1)                     - Tools for parsing and using INI-style files
```
