### ISSUE TITLE
Package size limit request: distaster-new-pos

### ISSUE THREAD

**Issue by Mariobai** [pypa/warehouse#3727]
The name of the project：disaster-new-pos
The size of your release, in megabytes: 200MB.
Which index/indexes you need the increase for (PyPI, Test PyPI, or both): both

The reason for this space is that the project has a trained neural network model that needs to be uploaded.

thank you very much.
from: mario

**Comment by di** [comment]
@Mariobai Could you explain why you need such a large distribution? It's not clear to me what the `disaster-new-pos` project is.

**Comment by Mariobai** [comment]
Thank you very much for your reply。disaster-new pos project is a named entity recognition porject in the field of disaster。Because it is oriented toward Chinese. So I trained a Chinese participle model with CRF. The size of this model is 183M. At the same time, I trained a bi-gru neural network model in the field of Chinese disaster, with the size of 104M. Therefore, I need about 200M space.

**Comment by di** [comment]
@Mariobai Is it possible for you to publish the project on Github so I can take a look at it? I see https://github.com/Mariobai/Disaster-new-NER-on-Chinese but that doesn't seem to have the models.

**Comment by di** [comment]
Closing due to lack of response.
