### ISSUE TITLE
openimageio is not available

### ISSUE THREAD

**Issue by figo2264** [pypa/warehouse#3730]
Hello, Guys.

My python application requires openimageio package.

When I tried to install the application via pip, it failed with the following message.

  Getting page https://pypi.python.org/simple/openimageio/
  Looking up "https://pypi.python.org/simple/openimageio/" in the cache
  No cache entry available
  Resetting dropped connection: pypi.python.org
  "GET /simple/openimageio/ HTTP/1.1" 302 98
  Status code 302 not in [200, 203, 300, 301]
  Looking up "https://pypi.org/simple/openimageio/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org
  "GET /simple/openimageio/ HTTP/1.1" 404 13
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/openimageio/: 404 Client Error: Not Found for url: https://pypi.org/simple/openimageio/ - skipping

Has the openimageio moved to another place?

**Comment by di** [comment]
It seems like the `openimageio` project either never existed, or has been deleted by it's author. You might want to reach out to the maintainers of that project directly.

**Comment by figo2264** [comment]
No, it used to be there on the old pypi, but it was gone after the renewal.

**Comment by di** [comment]
@figo2264 The "old pypi" and pypi.org have always shared the same data store, so there was no data loss in the transition. I'd recommend contacting the maintainers of the project directly, they have contact information listed here: https://github.com/OpenImageIO/oiio#contact
