### ISSUE TITLE
XML-RPC doesn't support MultiCall

### ISSUE THREAD

**Issue by PrimozGodec** [pypa/warehouse#3734]
New API differ from the old API (`pypi.python.org/pypi/`):

* ~`search` method work different e.g. `search({'keywords': "orange3 add-on"})` returns empty list because of space~
* `MultiCall` is not supported. 

I know that this API is deprecated but would ask if there is an option to make functionalities work same to support old versions of the softwares.

**Comment by ewdurbin** [comment]
Search issue is likely #3717

MultiCall must not be supported by our RPC implementation, https://github.com/Pylons/pyramid_rpc

**Comment by espoelstra** [comment]
@PrimozGodec if you point to https://legacy.pypi.org does that address your needs for the time being, and eventually do you want/expect the new API to support some of the same functionality?

**Comment by mcdonc** [comment]
FTR, something like this (untested) in warehouse/legacy/api/xmlrpc/views.py is one way to go to support this:

```
@xmlrpc_method(method='system.multicall')
def multicall(request):
    args = request.rpc_args
    responses = []
    for arg in args:
        name = arg.get('methodName')
        params = arg.get('params')
        if name == 'system.multicall':
            raise Exception
        if not name:
            raise Exception
        subreq = Request.blank('/RPC2', base_url=request.application_url)
        subreq.method = 'POST'
        subreq.body = xmlrpclib.dumps(arg)
        response = request.invoke_subrequest(subreq, use_tweens=True)
        responses.append(xmlrpc.loads(response.body))
    return responses
```
