### ISSUE TITLE
cache/stash long_descriptions rendered by readme_render 

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#3739]
RE https://github.com/pypa/readme_renderer/issues/95

A handful of long descriptions have _long_ render times, such as https://gitlab.com/hansroh/skitai/blob/master/README.rst.

A proposed solution:

- Store `long_description` as usual at upload time.
- Call a task to attempt to render the long description.
- Task renders long_description and stores resulting html with the version number of readme_renderer
- When rendering a project page, check for rendered version and fallback to attempting render
- On readme_renderer upgrade, have some mechanism to rerender all readmes via the same celery task as above.

**Comment by ewdurbin** [comment]
cc @jonparrott

**Comment by jonparrott** [comment]
Research notes (for my own benefit/for the benefit of whoever takes this on):

1. Current un-rendered `description` field is [here](https://github.com/pypa/warehouse/blob/7947068a27fd9184d93a2089b882656fb60d2704/warehouse/packaging/models.py#L338).
2. The description is only rendered for HTML views and is done in the template [here](https://github.com/pypa/warehouse/blob/b86fe0351cdbaacb36a5d8c080a1a380300aa4c5/warehouse/templates/packaging/detail.html#L266) using the `readme` filter.
3. The filter `readme` is defined [here](https://github.com/pypa/warehouse/blob/b86fe0351cdbaacb36a5d8c080a1a380300aa4c5/warehouse/filters.py#L75).

For the benefit of accomplishing this task and testability, we should likely pull the rendering logic out of the context filter and into its own thing (not sure where they would live yet) and just have the filter be a thin wrapper. We could then use the common function from both the task and the templates.

**Comment by di** [comment]
Might not even be necessary to keep it as a filter, it could be passed into the template from the view instead, which would make it a little easier to determine a cache key.

**Comment by jonparrott** [comment]
That could definitely work.
