### ISSUE TITLE
Typosquatting on `requests` and a number of other simple words

### ISSUE THREAD

**Issue by selik** [pypa/warehouse#3743]
I'm not sure of the intent, but the `request` https://pypi.org/project/request/ module seems suspicious. There's not much code there, but it installs a little chain of dependencies with frustratingly generic names. Most disturbing is the dependency on `get` https://pypi.org/project/get/ which ships what appears to be a small binary file, at least according to GitHub.

The package author has been quite active recently, posting many modules that appear to replace or duplicate common system tasks. They may be practice or example projects, but I'd like another pair of eyes to verify.

**Comment by ewdurbin** [comment]
This is being discussed in another forum. Thanks for reporting.

Note that if you're unsure wether an issue meets the standard for security or not, please err on the side of caution.
