### ISSUE TITLE
flup : ImportError: No module named _thread 

### ISSUE THREAD

**Issue by thijsvanderkraan** [pypa/warehouse#3747]
Using the flup 1.0.3 with python 2.7 causes the following error:

ImportError: No module named _thread

Analysis:
The module tread has been renamed to _tread in python 3.x. It seems some of the import statements were updated to support both names, but not all. Also, a mix of both names are used in the code, even within the same file. 

Proposal:
Replacing all 'import thread' and 'import _thread' statements with a try/except and using only 'thread' to refer to the module will fix the problem, see [solution.txt](https://github.com/pypa/warehouse/files/1923801/solution.txt)

**Comment by ewdurbin** [comment]
Hello @thijsvanderkraan unfortunately this issue tracker is for the Python Package Index itself, not for the projects hosted there.

https://pypi.org/project/flup does not list any issue tracker, but perhaps you can find some way to contact the author at the noted homepage: https://www.saddi.com/software/flup/
