### ISSUE TITLE
add explanation of file download link structure to docs

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3754]
We should add Ernest's explanation https://github.com/pypa/warehouse/issues/3738#issuecomment-382083526 to https://warehouse.readthedocs.io/api-reference/integration-guide/#integration-guide . The file to update is `docs/api-reference/integration-guide.rst`.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by julieqiu** [comment]
I'll work on this
