### ISSUE TITLE
pypi.org: Python 3.5 new keywords, async and await, not syntax highlighted

### ISSUE THREAD

**Issue by gjcarneiro** [pypa/warehouse#3770]
See for instance https://pypi.org/project/influxdbpusher/

It has code snippets  with `async def` and `await`, which are not being properly highlighted as keywords.

**Comment by di** [comment]
Moved to https://github.com/pypa/readme_renderer/issues/96.

**Comment by jonparrott** [comment]
looks like it might just be that we need to use the "python3" lexer by default: http://pygments.org/demo/6734166/
