### ISSUE TITLE
Incorrect README.rst Rendering

### ISSUE THREAD

**Issue by stephen-bunn** [pypa/warehouse#3785]
The `long_description` for https://pypi.org/project/bethesda-structs/ is not rendering any of the given RestructuredText correctly. I'm not sure if my README is doing anything wrong, but `readme_renderer` does not detect any errors.

![image](https://user-images.githubusercontent.com/4956855/39090586-c0e059a2-45b0-11e8-8d5e-71d6abf63aa4.png)

I would expect the rst to be rendered similar to the [Github repo's rendering](https://github.com/stephen-bunn/bethesda-structs) 

Past running `check` I'm not quite sure how to debug this.

**Comment by jamadden** [comment]
I find that [restview's](https://pypi.org/project/restview/) `--pypi` mode finds errors that 'setup.py check' misses. In this case:

```console
$ wget https://files.pythonhosted.org/packages/69/e3/f8d4f0a7c87e200020ddf46dd4b8c476ed12ce0b24db56e077c75e04ed4a/bethesda-structs-0.1.1.tar.gz
--2018-04-22 06:51:02--  
2018-04-22 06:51:02 (2.24 MB/s) - ‘bethesda-structs-0.1.1.tar.gz’ saved [37927/37927]
$ tar -xf bethesda-structs-0.1.1.tar.gz
$ cd ./bethesda-structs-0.1.1/
$ restview --pypi README.rst
Listening on http://localhost:64928/
README.rst:6: (WARNING/2) "raw" directive disabled.
```

And the resulting HTML:

<img width="1166" alt="screen shot 2018-04-22 at 06 54 07" src="https://user-images.githubusercontent.com/1256082/39094729-07e884e8-45fa-11e8-9286-ff4b2d2c25a2.png">

**Comment by stephen-bunn** [comment]
Thanks for the help! This has resolved my issue.
I'll be sure to run my RSTs through restview before publishing to pypi.
