### ISSUE TITLE
Request trove classifier for Tibetan

### ISSUE THREAD

**Issue by eroux** [pypa/warehouse#3787]
Request to add a new Trove classifier.

## The name of the classifier you would like to add
`Natural Language :: Tibetan`

## Why do you want to add this classifier?
Esukhia is building an ecosystem of Python libraries for Tibetan NLP (tokenization, spell checking, phonetics, etc.), it would be useful to have this classifier for them, especially since other languages exist.

**Comment by di** [comment]
Done! Thanks @eroux.

**Comment by eroux** [comment]
thanks!
