### ISSUE TITLE
Expose long_description_content_type in JSON API

### ISSUE THREAD

**Issue by nixjdm** [pypa/warehouse#3798]
Feature request: Add  'long_description_content_type' to JSON API in 'info': section, alongside the existing 'description'

Now that PyPI supports Markdown and more than one kind of content type for long descriptions, it would be helpful to be able to see what the content type is with the JSON API. Otherwise it is more difficult to correctly interpret the 'description', since it isn't immediately obvious if it's reStructuredText or Markdown with which variant.

I'm willing to try this if I'm pointed in the right general direction :) If someone else can get it done trivially that's fine too.

**Comment by di** [comment]
@nixjdm Sounds like a good idea. Here's where the `description` field is added: https://github.com/pypa/warehouse/blob/338d6a102939c6452c0b6825924151d1b8b09301/warehouse/legacy/api/json.py#L157

**Comment by nixjdm** [comment]
@di should I leave the xmlrpc api for release_data alone, or update that as well?

**Comment by di** [comment]
@nixjdm I can't see any reason why it would hurt to add it there as well.

**Comment by nixjdm** [comment]
Alright, will do.
