### ISSUE TITLE
Redirect legacy classifier filter URLs

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3799]
Some projects' documentation ([example](https://github.com/sphinx-doc/sphinx/pull/4891)) points to legacy PyPI URLs for classifier-based searches like

https://pypi.python.org/pypi/?:action=browse&c=599

Could we have those redirect?

**Comment by ewdurbin** [comment]
@dstufft @di thoughts here?

I'm neutral here. If there is a trivial way of supporting a URL rewrite we should consider it.

As far as I know, archival services do not generally respect query parameters so while we would be breaking links... I'm not sure how damaging this is to the web overall.

**Comment by dstufft** [comment]
It wouldn't be hard to support I don't think. You're just adding another legacy API in ``warehouse/legacy/api/pypi.py`` and looking up the classifier by ID, and redirecting to the search page for that classifier.

**Comment by di** [comment]
I think this is totally doable, see what we do for `list_classifiers` here: https://github.com/pypa/warehouse/blob/d8269247e43123feeeb7632d89f4698b58f1cb8a/warehouse/legacy/api/pypi.py#L80-L92

**Comment by di** [comment]
Note that regular search links (without classifiers) should probably be supported as well, e.g:

https://legacy.pypi.org/pypi?%3Aaction=search&term=foobar&submit=search
should redirect to:
https://pypi.org/search/?q=foobar
