### ISSUE TITLE
De-emphasize the downloadable files

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#381]
Currently on PyPI and Warehouse the list of files to download is a major part of the project detail page. However an overwhelming majority of downloads of files come from automated clients (see below) which will never use this list. It seems to me that we would be better off finding a way to de-emphasize this list of files in some way (behind a modal? I don't know). After talking with @r1chardj0n3s I don't believe flat out removing this list of files is the right answer.

![stacked-installer-pct](https://cloud.githubusercontent.com/assets/145979/6548993/db208cc2-c5e0-11e4-8141-7cb2231db19c.png)

**Comment by nlhkabu** [comment]
Done on the new UI!
