### ISSUE TITLE
Lektor Trove Classifiers

### ISSUE THREAD

**Issue by nixjdm** [pypa/warehouse#3813]
Request to add two new Trove classifiers.

## The name of the classifiers you would like to add
`Framework :: Lektor`
`Framework :: Lektor :: Plugins`

## Why do you want to add this classifier?
Lektor is a static site generator and framework that has plugins, which are Python packages/modules. I would like these classifiers to more easily discover plugins, forks, and related projects. This has been done, for instance, [for Pelican](https://pypi.org/pypi?%3Aaction=list_classifiers).

At the moment, I suspect a few dozen projects could use the `Framework :: Lektor :: Plugins` classifier, and that is a subset of the other classifier. Here is a list of Lektor plugins that the community has submitted to getlektor.com https://www.getlektor.com/docs/plugins/list/ I plan on searching pypi.org for others that are not mentioned and reaching out to them as well.

**Comment by di** [comment]
@nixjdm Could you explain why a user would choose one of these suggested classifiers over the other?

I think the only reason `Framework :: Pelican :: Plugins` exists is because `Framework :: Pelican :: Themes` exists as well, and I suspect that just `Framework :: Lektor` would probably suffice here.

**Comment by nixjdm** [comment]
@di On second thought, I agree, actually. `Framework :: Lektor` alone should be fine. Most Lektor packages are plugins.

Lektor themes exist, but at the moment anyway, they are not python packages or installable with pip. Perhaps when/if that ever changes those subsets can be added. Right now there's now there's not enough of a use for the additional classifier.

**Comment by di** [comment]
OK, I've added the classifier `Framework :: Lektor`:

https://pypi.org/search/?c=Framework+%3A%3A+Lektor

**Comment by nixjdm** [comment]
Thanks @di!
