### ISSUE TITLE
Set focus to search box when tab key pressed

### ISSUE THREAD

**Issue by bittner** [pypa/warehouse#3814]
Given I'm on the Warehouse start page
and I want to use just the keyboard to search for a package
when I press my keyboard's `<Tab>` key once (or max. twice)
then I should be able to type the package name
and press `<Return>`, or `<Tab>`+`<Space>`/`<Return>` alternatively
to get the search triggered.

Current Behavior
---------------

When I press `<Tab>`
then the browser walks through all elements of the website in their natural order
and I need to press `<Tab>` for 8 times before I arrive at the search input field.

Implementation Details
---------------

1. Add a `tabindex="1"` attribute to [search input field](https://github.com/pypa/warehouse/blob/master/warehouse/templates/index.html#L53)
1. Add a `tabindex="2"` attribute to [button tag](https://github.com/pypa/warehouse/blob/master/warehouse/templates/index.html#L54)

Related Issues
----------------

- #831
- #2824
- #3576

**Comment by nlhkabu** [comment]
Hi @bittner, thanks for opening this. I've moved this to #3440, where there is already a discussion underway :)
