### ISSUE TITLE
pip search not working if pkg name contains '-'

### ISSUE THREAD

**Issue by Ayub-Khan** [pypa/warehouse#3819]
* Pip version:
9.0.1 and 10.0.1
* Python version:
python 2 and python 3
* Operating system:
Ubuntu

### Description:

pip search edx-i18n-tools
Expected Behavior : 
It should show the version and summery of latest version
Actual Behavior : 
shows Nothing

pip search edx-ace
Expected Behavior : 
It should show the version and summery of latest version
Actual Behavior : 
shows Nothing

pip search edxval
Expected Behavior : 
It should show the version and summery of latest version
Actual Behavior : 
shows correctly

###Another issue
search also not works if the word is not in lower case in pkg description
ie.
pip search internationalization
It should show all the libraries which have Internationalization/internationalization in their pkg description
only shows one with name internationalization. 

###Another issue
Search also does not work if query string is not in lower case
ie. 
pip search edx
works shows a list

pip search edX
shows nothing
it should show the same list as 'pip search edx'
pip search EDX
it should show the same list as 'pip search edx'

https://github.com/pypa/pip/issues/5332

**Comment by ewdurbin** [comment]
I think the results for all provided examples make more sense in the "main" search.

Looks like we should be able to make results for `pip search` more sensible by applying the same search logic/boosting. I'm gonna approach this shortly.

**Comment by ewdurbin** [comment]
all reported issue here were resolved in #3827

**Comment by Ayub-Khan** [comment]
@ewdurbin thanks a lot for fixing the issue. I ran the following command to verify the behavior 
pip search edx-i18n
pip search django-filter
It is working fine but it seems it is showing all results for 'edx' combined with all results of 'i18n'. it is treating it as two different strings django and filter and showing the union of result sets for both. it should only show the results if whole query string is in name or summry right ?

**Comment by ewdurbin** [comment]
@Ayub-Khan I believe your theory is correct, though I'm not sure how to improve that.
