### ISSUE TITLE
Unable to log into account on pypi.org and test.pypi.org

### ISSUE THREAD

**Issue by koliber** [pypa/warehouse#3825]
Every time I try to log into the web-based account, I get a "user not found" error. 

![image](https://user-images.githubusercontent.com/1017317/39291671-10b0b6f8-4934-11e8-95ee-0722fbfa88ab.png)

 I tried many things.

What I did:

1. Created an account at pypi.com with the email address `krystian@goodgrids.com`
2. DID NOT click on the verification email (missed it)
3. Tried logging in, and got the above error.
4. Tried resetting password. Succeeded and got into the account. I logged out.
5. Tried logging in, and got the above error.
6. Tried various things, the exact order of which I do not remember. This included changing the password internally, doing more password resets. I've manually typed in the password, and used my 1Password password manager. Always met with same results. 

I also am experiencing the same issue on `test.pypi.org`. I even went as far as completely deleting my account, signing up from scratch, and correctly verifying my email address. I get the same error.

**Comment by ewdurbin** [comment]
Hello @koliber! Logins to PyPI are performed with the username specified at signup not email addresses.

Does this help you?

**Comment by koliber** [comment]
That's it!  I wrongly assumed it's the email address.
