### ISSUE TITLE
Expose project_urls in JSON API

### ISSUE THREAD

**Issue by nixjdm** [pypa/warehouse#3831]
https://packaging.python.org/tutorials/distributing-packages/#project-urls

Related to #3798 / #3820

I realized project_urls is not currently exposed by the JSON API. I propose adding it.

Though the keys in the project_urls dict can be anything, they're fairly standardized, enough to be useful when querying for them over and API. For example, [Flask's API response](https://pypi.org/pypi/Flask/json) lists its home_page as https://www.palletsprojects.com/p/flask/ (not it's github account which is fairly typical), and puts it's GitHub link in `project_urls['Code']`, which is not currently in the API response.

**Comment by nixjdm** [comment]
Sure :) It's so similar it'd be no problem, especially after the other PR get's in.

**Comment by tomdottom** [comment]
@nixjdm I was wondering how work was going on this feature?

**Comment by nixjdm** [comment]
I had to take off from doing this for a while, but it's done, with pending review as a pull request #4184!
