### ISSUE TITLE
Firefox: fix alignment of buttons

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#3840]
![screenshot from 2018-04-27 07-09-00](https://user-images.githubusercontent.com/3323703/39347258-e70ff334-49e9-11e8-879e-b950d6453e11.png)

**Comment by di** [comment]
I can't reproduce this in Firefox 59.0.2.

**Comment by waseem18** [comment]
I'm able to reproduce this in Firefox 59.0.2. Weird. I use Ubuntu by the way.

![m](https://user-images.githubusercontent.com/5843007/39407876-e906e0f0-4bea-11e8-84e1-e90c8740fc97.png)

**Comment by rixx** [comment]
Persists up to Firefox 63 currently.

**Comment by manikos** [comment]
Two solutions I found:

- Change [``_package-snippet.scss``](https://github.com/pypa/warehouse/blob/master/warehouse/static/sass/blocks/_package-snippet.scss#L79) to ``width: 170px;``

or

- Change [``_package-snippet.scss``](https://github.com/pypa/warehouse/blob/master/warehouse/static/sass/blocks/_package-snippet.scss#L87) to ``margin-right: 3px;``

**Comment by nlhkabu** [comment]
@manikos if we use 170px width, how does that render on other browsers? e.g. chrome, safari? Thanks

**Comment by manikos** [comment]
Tested on Chrome and renders without any visual problems. Have not tested on Safari, neither on IE.

**Comment by nlhkabu** [comment]
thanks @manikos.  If you want to go ahead and make a PR, I can then test it across a range of browsers with my browserstack account :)
