### ISSUE TITLE
Redirect files &/or display action URLs from legacy

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3845]
I see some users using legacy URLs like:

* https://pypi.python.org/pypi?:action=files&name=limix&version=1.0.14 (on legacy: https://legacy.pypi.org/pypi?:action=files&name=limix&version=1.0.14 )
* https://pypi.python.org/pypi?:action=display&name=craft-ai (on legacy: https://legacy.pypi.org/pypi?:action=display&name=craft-ai )
* https://pypi.python.org/pypi?:action=display&name=text_progress_bar (on legacy: https://legacy.pypi.org/pypi?:action=display&name=text_progress_bar )

It'd be nice to redirect the display URLs and, potentially, the files URLs to Warehouse.

Followup to #3799.

**Comment by ewdurbin** [comment]
Working on this.
