### ISSUE TITLE
Search filters put 'Programming Language :: Python :: N :: Only' checkboxes in an odd place

### ISSUE THREAD

**Issue by bskinn** [pypa/warehouse#3851]
The search-filter checkboxes are sorting the `Programming Language :: Python :: N :: Only` checkboxes below all of the respective `N.n` checkboxes, instead of placing them immediately below the `N` checkboxes:

![more logical place for the checkboxes](https://user-images.githubusercontent.com/11325439/39403120-473fcd40-4b40-11e8-8be2-665ef38aa267.png)

This is highly nonintuitive, at least to me.

This may be low priority given that, e.g., #2442 and/or #3462 would presumably change the UI considerably.

**Comment by waseem18** [comment]
I second this. 'Only' checkbox is a bit confusing. As @bskinn mentioned we should probably place 'Only' below '2' and '3'.

**Comment by Cheukting** [comment]
@nlhkabu do you want me to have a look at it?

**Comment by nlhkabu** [comment]
@dstufft is this something for you to look at?

**Comment by di** [comment]
This seems to have resolved itself. https://pypi.org/search/?q= currently shows the following: 

<img width="237" alt="Screen Shot 2020-04-02 at 9 41 42 PM" src="https://user-images.githubusercontent.com/294415/78318587-c6a50080-752a-11ea-9310-cb58232ab33a.png">
