### ISSUE TITLE
use CSP: sandbox on /simple/ pages

### ISSUE THREAD

**Issue by alex** [pypa/warehouse#3857]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox + https://www.youtube.com/watch?v=fbhW37JZtSA&feature=youtu.be

I believe this is a great fit for /simple/, which don't need any ability to do anthing but have a simple HTML structure.

I _think_ we can replace the whole current header with `Content-Security-Policy: sandbox allow-top-navigations`.

**Comment by devd** [comment]
I think that makes sense. noodling on this, I suspect `default-src: 'none'` is enough but why not both? Good defense in depth.

**Comment by alex** [comment]
Thanks @devd!

@dstufft Can you suggest where in the codebase the right place to _override_ the CSP for `/simple/` pages is?
