### ISSUE TITLE
Unicode decoding error?

### ISSUE THREAD

**Issue by callahad** [pypa/warehouse#3858]
https://pypi.org/project/iconv/ displays the author as "Martin v. LÃ¶wis"

:(

**Comment by di** [comment]
That's how it was provided to PyPI in the metadata, unfortunately there's not much we can do about that. You might want to inform the owner of the project instead. Thanks for the report though!

**Comment by callahad** [comment]
I'm admittedly *very uninformed* as to the guts of Python packaging, but the `PKG-INFO` and `setup.py` files in the archive both seem to have a correct UTF-8 encoding of "Martin v. Löwis".

```python
>>> line = open('PKG-INFO', 'rb').readlines()[5]
>>> line.decode('utf-8')
'Author: Martin v. Löwis\n'
>>> line.decode('iso-8859-1')
'Author: Martin v. LÃ¶wis\n'
```

What's the correct way to use UTF-8 in package metadata?

**Comment by callahad** [comment]
(...oh no. is this still part of Python 2's ascii legacy?)

**Comment by dstufft** [comment]
Warehouse/PyPI doesn't inspect the uploaded files, it gets sent alongside the file upload as form encoded data, so if whatever uploaded the file didn't properly send it, then you'll get that.

**Comment by callahad** [comment]
Ah, right. Thanks @dstufft!
