### ISSUE TITLE
Run `make serve` and `make initdb` simultaneously?

### ISSUE THREAD

**Issue by lgh2** [pypa/warehouse#3861]
At the NYC Python/PyLadies mini-sprint, one of the attendees was following the [instructions in the documentation](https://warehouse.readthedocs.io/development/getting-started/) to set up his development environment.  He was confused about whether `make serve` and `make initdb` should be run sequentially or simultaneously. 

I have always been running the commands simultaneously (I run `make serve`, and while that is printing things to stdout I run `make initdb` in another terminal window). It's always worked for me. Should we tell people to run the commands simultaneously in the documentation?

**Comment by di** [comment]
Maybe we just need to ditch the "Quickstart for Developers with Docker experience" section entirely? The detailed instructions are pretty clear about this particular step.

**Comment by lgh2** [comment]
That would probably fix some of the confusion.

Out of curiosity, when you are setting up your environment, do you run `make serve` and `make initdb` simultaneously?

**Comment by di** [comment]
The database needs to be up before it can be initialized, so the correct thing to do would be to run `make serve` in one terminal, and once the database is up, run `make initdb` in another (since `make serve` will run indefinitely`).
