### ISSUE TITLE
create manual testing guide

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3872]
To help less-skilled-at-coding newcomers at sprints contribute to Warehouse, I'd like for us to have a manual testing guide like [Zulip's](https://zulip.readthedocs.io/en/latest/testing/manual-testing.html).

Rough ideas/inspirations:

A lot of our core has 100% unit test coverage, so we don't need to waste time testing the upload base case, JSON, the Simple API, and so on.

https://docs.google.com/presentation/d/1JHTvs58DaHJzha8aN8oz_IYaiyZlupgioAB3d5MnnFw is the slide @lgh2 made to guide participants at a one-evening sprint last week. We asked people to work through tutorials, and tried to watch their developer setup experiences in ways reminiscent of SpinachCon https://blog.openhatch.org/2014/spinachcon-zero-a-huge-success/ or Wikimedia Foundation's new contributor reports https://blog.wikimedia.org/2014/03/25/seeing-through-the-eyes-of-new-technical-contributors/ .

Per http://thebraidytester.com/downloads/YouAreNotDoneYet.pdf , if we were to make a manual testing guide to give useful tasks to very new people at the sprint, frontend testing and testing weird filenames, dates, and graphics might be a thing new folks could do. (Printing is a bit harder for a sprint, but I'm sure there are people who want to print PyPI project pages to show other people, or print to PDF to share in, like, a tenure review packet.) We could ask people to work through the PyPUG tutorials, test them with varying inputs (such as weird files & filenames, and pre-releases of other parts of the PyPA toolchain), and note any bugs that emerge. We could expand https://warehouse.pypa.io/development/reviewing-patches/?#testing-with-twine and have newcomers test open PRs.

@jonparrott mentioned that Google has "something similar we call 'friction logging' internally."

**Comment by jonparrott** [comment]
So I'm not as helpful at defining *scenarios* to test, but the friction log template we have internally is really useful to give testers a little bit of structure to record their experience and helps extract actionable tasks.

I've externalized this template and made it PyPA-ready [here](https://docs.google.com/document/d/1kcEv9c_diZbqdXk2VkVu6miHz62hUoxxzfIo5ILnESM/edit). Hopefully this is useful. @brainwane I can give you edit access to this so you can tweak it as necessary.

**Comment by brainwane** [comment]
@nlhkabu I think this might be useful for you to use at the Europython sprints. I did not prepare in time to use it at PyCon sprints but I think it would have been useful.

**Comment by nlhkabu** [comment]
assigned to @mferi at the europython sprints :)
