### ISSUE TITLE
Add rel="noopener" guidance to developer docs

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3877]
When using `target="_blank_"` for a hyperlink (usually to an external site), we should always set `rel="noopener"`.

Add these instructions to:

* https://warehouse.readthedocs.io/development/reviewing-patches/#grammar-and-style
* https://warehouse.readthedocs.io/development/frontend/#html-code-style

You'll find both those files within the `docs/` [directory](https://github.com/pypa/warehouse/tree/master/docs).

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, please work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, please feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by pgadige** [comment]
I'm working on this.

**Comment by shahnevil0** [comment]
I'm working on this (i.e. continuing from where @pgadige left off)
