### ISSUE TITLE
Implement the Daytime URL

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#388]
Figure out if we need the ``/daytime`` URL and if we do implement it.

**Comment by dstufft** [comment]
The ``/daytime`` endpoint was originally put into place to support the mirroring protocol so that mirrors could know what time the server thought it was and could ask for all the changes since a particular time. However this was error prone and now we have an API that allows them to ask for all the changes since a particular journal entry.

It looks like bandersnatch doesn't use the ``/daytime`` endpoint, some legacy mirrors probably do but they are likely already broken by other changes we've made to the mirroring pages. Unless @hpk42 says that devpi uses the ``/daytime`` endpoint and it can't be easily modified to not use, I'm going to say that Warehouse just doesn't support it.

**Comment by hpk42** [comment]
On Thu, Mar 19, 2015 at 01:40 -0700, Donald Stufft wrote:
> The ``/daytime`` endpoint was originally put into place to support the mirroring protocol so that mirrors could know what time the server thought it was and could ask for all the changes since a particular time. However this was error prone and now we have an API that allows them to ask for all the changes since a particular journal entry.
> 
> It looks like bandersnatch doesn't use the ``/daytime`` endpoint, some legacy mirrors probably do but they are likely already broken by other changes we've made to the mirroring pages. Unless @hpk42 says that devpi uses the ``/daytime`` endpoint and it can't be easily modified to not use, I'm going to say that Warehouse just doesn't support it.

devpi does not use any timestamping, just serials.

thanks for notifying.
holger


> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/pypa/warehouse/issues/388#issuecomment-83421523

-- 
about me:    http://holgerkrekel.net/about-me/
contracting: http://merlinux.eu

**Comment by dstufft** [comment]
Cool, going to close this then and say that Warehouse doesn't support this API. Thanks @hpk42!
