### ISSUE TITLE
Markdown rendering of requests page

### ISSUE THREAD

**Issue by abulka** [pypa/warehouse#3884]
https://pypi.org/project/requests/
The markdown doesn't render at all and just appears raw. Viewing on iPhone. 
Not sure if this unique to that project or a more global problem. Am mobile and wanted to flag this but cannot supply more info at present.

**Comment by brainwane** [comment]
Thanks for the note @abulka. cc @kennethreitz 

The `requests` [README](https://github.com/requests/requests/blob/master/README.rst) is actually in reStructuredText, and `requests`'s [`setup.py`](https://github.com/requests/requests/blob/master/setup.py) file, which instructs other packaging and distribution tools on how to make and interpret the package, doesn't mention that it's `.rst`. The `requests` maintainers can follow https://packaging.python.org/guides/making-a-pypi-friendly-readme/ for their next release to make sure the description renders well.

Hope this helps!
