### ISSUE TITLE
remove Heroku config

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#3886]
Some configuration files seem to refer to Heroku, and as far as I understand, we no longer have any Heroku dependencies. Am I wrong?

I did a `git grep` and found that we should look at:

- [ ]  `bin/post_compile`
- [ ]  a TODO note in `bin/redis-tls`
- [ ]  `config/nginx.conf.erb`
- [ ]  `vcl/main.vcl`
- [ ] `runtime.txt`
- [ ]  documentation in `docs/application.rst`

**Comment by ewdurbin** [comment]
That can (and should) be changed :-D

**Comment by brainwane** [comment]
Is Test PyPI still on Heroku?

**Comment by ewdurbin** [comment]
No longer! It was migrated to the same hosting as Prod PyPI a few weeks ago.

**Comment by sk1u** [comment]
@nlhkabu I'd like to work on this, please. EuroPython2018

**Comment by nlhkabu** [comment]
Assigned to @sk1u at EuroPython sprints :)

**Comment by di** [comment]
I think most of this was done in https://github.com/pypa/warehouse/pull/4330, but it would be good to double check that we got everything.

**Comment by sk1u** [comment]
Good morning, @nlhkabu . this was addressed in https://github.com/pypa/warehouse/pull/4375 which was since merged. thank you!

**Comment by nlhkabu** [comment]
Great, thanks @sk1u !

**Comment by nlhkabu** [comment]
@sk1u in case you didn't know: you can automatically close the issue when the PR is merged with [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/).

This makes it easier for us to manage our issue tracker and keep track of what's been fixed.

Thanks again for your PR! Let me know if there is another issue you are interested in working on :)
