### ISSUE TITLE
Implement DOAP

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#391]
Determine if we need to keep DOAP or if we can get rid of it. If keeping it then we need to implement it. See some discussion on #58.

**Comment by msabramo** [comment]
My guess is no one knows what DOAP is. I've seen it on PyPI and had no clue and looked it up one time and concluded that it was something that was in vogue a long time ago and never really caught on?

**Comment by r1chardj0n3s** [comment]
Believe it or not, I've had people ping me about it only very recently, so
it's being used. No idea how much though, or for what purpose.
