### ISSUE TITLE
Request for ownership of abandoned dinnerbone/mcstatus

### ISSUE THREAD

**Issue by kevinkjt2000** [pypa/warehouse#3910]
As per discussion near the bottom of https://github.com/pypa/warehouse/issues/1506, I decided to open an issue here to make this request.

I dislike that it has come to this, but I feel it necessary to take action in effort to either grab the attention of the author, or maintain the project myself.  It has been over a year since the last release of mcstatus to pypi.  Attempts to contact the author, Dinnerbone, by raising a PR on GitHub have failed https://github.com/Dinnerbone/mcstatus/pull/56  As did tweeting https://twitter.com/MarkL4YG/status/929362396317175808

**Comment by yeraydiazdiaz** [comment]
Hello @kevinkjt2000, I have sent an email to @dinnerbone regarding your request. Hopefully we will hear from him soon and move forwards with it.

**Comment by yeraydiazdiaz** [comment]
Hello @kevinkjt2000, @Dinnerbone has not responded in a timely fashion and the project is thus considered abandoned. However, before transferring ownership all requirements listed in [the corresponding section of PEP 541](https://www.python.org/dev/peps/pep-0541/#removal-of-an-abandoned-project) need to be satisfied:

- [x] The project has been determined abandoned by the rules described above;
- [x] The candidate is able to demonstrate their own failed attempts to contact the existing owner;
- [ ] The candidate is able to demonstrate that the project suggested to reuse the name already exists and meets notability requirements;
- [ ] The candidate is able to demonstrate why a fork under a different name is not an acceptable workaround;
- [ ] Download statistics on the Package Index for the existing package indicate project is not being used; and
- [ ] The maintainers of the Package Index don't have any additional reservations.

I'm concerned however about the download statistics, [pepy.tech shows ~300 downloads a week and almos 2.5k downloads a month](https://pepy.tech/project/mcstatus) which I think we need to respect, which leads me to ask if if you've considered creating a fork under a different name.

Let us know what you think.

**Comment by kevinkjt2000** [comment]
Where are `notability requirements` listed?  This seems vague to me in the PEP 541 document.  I do have a fork that I would like to release, and I even successfully tested publishing to the test pypi (about a year or so ago). 
 https://github.com/kevinkjt2000/mcstatus

Are pypi maintainers okay with having lots of little forks with alternate names?  To me that seems confusing and chaotic.  In my opinion, packages with zero active authors do not belong on pypi.  If that is not convincing enough, I may consider taking another name, but will likely just withdraw this request instead.

Yes the package is downloaded a fair bit, because it still works (mostly); however, PRs and issues are being ignored by the author.  I would want to leave dinnerbone as a co-owner too, in case he returns (i.e. stops blatantly ignoring his github, twitter, and email).  All I want is the ability to collaborate and have permission to publish a package where the original author is inactive.  I think of this situation as if it was someone from the community stepping in, after someone died, to continue maintenance (and possibly features? not likely, but I would at least review/accept PRs from others instead of ignoring them).

**Comment by kevinkjt2000** [comment]
Should I fork, rename, and slowly steal away the users?  Personally, that feels odd to me.

**Comment by MarkL4YG** [comment]
I would favor a fork under the same name. The current project has several issues where PRs are already available.
I would say users benefits from fixes being finally applied after years are bigger than the possible drawbacks given a pledge of the new maintainers to not break existing (API) contracts without proper notice.
Semantic versioning would also help with this.
I would also offer to maintain the project regarding PR review, issues and code updates when required.

**Comment by MarkL4YG** [comment]
Let me ask: Is it possible to convince you of the benefits that everyone would gain from updates to the same package if we explicitly write transition documentation with specific pledges on how the development in the project continues including what will (bug fixes, additional features, ...) and will not (breaking changes) be done ?

**Comment by Iphex** [comment]
Just want to add, I am in full support of this. I use this library and even messaged the author on twitter. He just ignores everything tho :( I do not want to tell every user who uses my project to go into dinnerbones libary and edit bugfixes in ( also, editing in bugfixes for every virtualenv :(). That feels terrible. I personally feel like using the same name would be helpful, since it is referenced a lot, but forces users to use a buggy version (and probably give up whatever they were trying to do, I was close to this too.)

**Comment by Dinnerbone** [comment]
Hey everyone,

I'm sorry for not catching and dealing with this much sooner.

I have no issues with transferring ownership, I (clearly) do not have time to maintain this project myself anymore. To that end, I have added `kevinkjt2000` as Owner on pypi.org, and to my github repository. I do not mind, however, if you'd rather fork it and move it somewhere else, either.

Sorry again for not handling this in a nice way.

<3

**Comment by MarkL4YG** [comment]
@Dinnerbone Thank you so much for your response and allowing us to continue development! :raised_hands:

**Comment by jamadden** [comment]
@Dinnerbone Thanks for responding.

@kevinkjt2000 If you're satisfied, could you please close this issue?

**Comment by kevinkjt2000** [comment]
Whoa!  Was not expecting this turn of events!  Thanks Dinnerbone!

**Comment by kevinkjt2000** [comment]
Thanks again @Dinnerbone !  I was able to release a new version and respond to a large number of the open issues.
