### ISSUE TITLE
Unable to upload my project

### ISSUE THREAD

**Issue by scardosoabreu** [pypa/warehouse#3912]
unable to authenticate with correct credentials

I can login https://pypi.python.org/pypi with my username password so I am sure they are correct

But I cannot upload my package. I always get

Upload failed (403): Invalid or non-existent authentication information.
error: Upload failed (403): Invalid or non-existent authentication information.

**Comment by di** [comment]
@scardosoabreu What command are you using to upload? Have you created a `.pypirc` file? 

You might find this guide helpful: https://packaging.python.org/tutorials/distributing-packages/#create-an-account

**Comment by scardosoabreu** [comment]
Yes, I  created the .pypirc file but I just figured it out: I changed the name of the file and tried again using twine upload dist/*
The first time I was trying: python3 setup.py sdist upload and it was returnig the error.
Worked fine now!
thank you!!

**Comment by di** [comment]
Great, closing this then, but feel free to comment if you have additional questions.
