### ISSUE TITLE
Missing legacy redirection from pypi.python.org/pypi/

### ISSUE THREAD

**Issue by JulienPalard** [pypa/warehouse#3914]
**Describe the bug**
Redirections from `https://pypi.python.org/pypi/` are not handled (only redirected to `https://pypi.org/pypi/` by varnish (fastly)).

As https://pypi.org/pypi/ does not exists, it creates some broken links.

**Expected behavior**
A 301 to `https://pypi.org/`, simply.

**To Reproduce**
```$ curl -sI https://pypi.python.org/pypi/
HTTP/2 301 
server: Varnish
retry-after: 0
location: https://pypi.org/pypi/
[...redacted for readability...]
```

**Comment by brainwane** [comment]
Per @JulienPalard:

>  it's a missing route in warehouse, .... probably in `warehouse/routes.py` around line 327.

**Comment by stloma** [comment]
I can add this legacy redirect, thanks!
