### ISSUE TITLE
Flask-FeatureFlags abandoned - PEP 541 transfer 

### ISSUE THREAD

**Issue by galund** [pypa/warehouse#3931]
Per #1506 and PEP 541, I'd like to ask you to transfer the ownership of https://pypi.org/project/Flask-FeatureFlags/ to me (user name `georgelundgds`).

No pull requests have landed on the original source at https://github.com/trustrachel/Flask-FeatureFlags since 2015, and multiple attempts to contact the author have failed. The address listed on pypi is not currently accepting emails.

We need to update this (tiny) library for compatibility with Flask 1.0.

Please advise on the necessary steps. For data protection reasons I'll provide any evidence needed via a non-public channel.

Thanks
George

**Comment by benvand** [comment]
+1

**Comment by yeraydiazdiaz** [comment]
Hello @galund, I've sent an email to @trustrachel regarding your request but, as you mention, it is no longer accepting incoming emails. Hopefully we can hear back through this issue and clarify the position about this package.

In the meantime, and according to the [project transferral rules in PEP 541](https://www.python.org/dev/peps/pep-0541/#continued-maintenance-of-an-abandoned-project), could you provide a currently maintained fork of the project?

**Comment by galund** [comment]
Hi, I'm afraid because the project was abandoned and we had no response, we stopped using this library, and so no longer maintain a fork. The fork we had is archived at https://github.com/alphagov/Flask-FeatureFlags/

**Comment by yeraydiazdiaz** [comment]
Thanks for letting us know, and sorry for the delay in responding to this issue.
