### ISSUE TITLE
Not all rows are getting pulled

### ISSUE THREAD

**Issue by 0ashu0** [pypa/warehouse#3936]
**Describe the bug**
Not all rows of data are being shown in the output. In the end of output, the summary does show total expected records. But the total number of rows are not complete, in between some rows are missing

**Expected behavior**
Number of rows in summary should match the total fetched rows. Correct behavior is that all records should get fetched.

**To Reproduce**
Just run the sample code for 1 year at minute level. expected rows should be around 1.4k but fetched records are around only 60.

**My Platform**

**Additional context**
https://www.protectedtext.com/githubissuelink

password
githubissuelink

**Comment by jamadden** [comment]
The link you included is to a code snippet using `googlefinance.client`:
```python
from googlefinance.client import get_price_data, get_prices_data, get_prices_time_data

param = {
    'q': "SBIN", # Stock symbol (ex: "AAPL")
    'i': "3600", # Interval size in seconds ("86400" = 1 day intervals)
    'x': "NSE", # Stock exchange symbol on which stock is traded (ex: "NASD")
    'p': "1Y" # Period (Ex: "1Y" = 1 year)
}

df = get_price_data(param)
print(df)
```

This tracker is for the software that runs pypi.org only, it cannot help with the packages distributed and installed from there. If you're trying to report an issue with `googlefinance.client` you'll need to get in touch with the maintainers of that project.
