### ISSUE TITLE
Multiprocess Bug in python on ubuntu 16.04

### ISSUE THREAD

**Issue by LittleLampChen** [pypa/warehouse#3958]
**Describe the bug**

It would return all zeros when I apply resamplefiter in multiprocess program on python.
**Expected behavior**

This happens when I processing the 3D image data in multiprocess on python. Sometime, it happens.
Not only resampler operation, but also other function, like deformations. (The image data is 0 or 1.)
**To Reproduce**

Call the function in multiprocess in python on ubuntu 16.04.
**My Platform**

**Additional context**

**Comment by di** [comment]
This is the issue tracker for the code that runs `pypi.org`, not the projects on it. You'll need to reach out to the maintainers of the specific project you're having problems with.
