### ISSUE TITLE
From Github tags to new release on Pypi using bot

### ISSUE THREAD

**Issue by scls19fr** [pypa/warehouse#3963]
Hello,

Publishing a new release of a Python package could be much easier.

GitHub tags could be an easy way to achieve this task.
Moreover it will avoid to have a tag on Pypi which doesn't exists on Github.

In Julialang we have attobot https://github.com/attobot/attobot

I wonder if such feature couldn't be implemented for the Pypi infrastructure.

Kind regards

**Comment by webknjaz** [comment]
I'd like to also add that there's GitHub Deployment API for this, which I'm currently exploring for a similar reason.

**Comment by di** [comment]
Recommended way to do this is by the PyPA's officially supported GitHub Action: https://github.com/pypa/gh-action-pypi-publish
