### ISSUE TITLE
Fail upload if rST description does not render

### ISSUE THREAD

**Issue by di** [pypa/warehouse#3966]
If the reStructuredText `long_description` does not render, let's fail the upload instead of just rendering it as plaintext, and raise a meaningful error to the user.

**Comment by theacodes** [comment]
#3760 should help - you can call `warehouse.utils.readme.render` to check and see if the description is valid.

**Comment by dstufft** [comment]
Reopening this since the change got reverted.

**Comment by di** [comment]
Looking at the user's project and their Travis build logs in https://github.com/pypa/warehouse/pull/4099, I can't see why the upload would have failed. 

* The project: https://github.com/ocefpaf/erddapy
* The failed build (indicating correct versions of setuptools/twine/wheel): https://travis-ci.org/pyoceans/erddapy/jobs/385360404#L1591
* The eventual release (missing `Description-Content-Type`): https://pypi.org/admin/projects/erddapy/release/0.1.8

We should probably experiment with this Travis feature and figure out if it was somehow user error, or if there's actually something broken about the way Travis deploys to PyPI.

**Comment by dstufft** [comment]
Solved in https://github.com/pypa/warehouse/pull/5835
