### ISSUE TITLE
[ui] url hijacking on page load

### ISSUE THREAD

**Issue by ofek** [pypa/warehouse#3997]
**Describe the bug**
On page load there is some JS that hijacks the url to focus on the `#description` anchor.

![anchor](https://user-images.githubusercontent.com/9677399/40083155-480115d0-5861-11e8-810f-25747241271c.PNG)

**Expected behavior**
Do nothing with users' urls, as there is important info above that should be immediately visible:

![correct](https://user-images.githubusercontent.com/9677399/40083375-ebd1844c-5861-11e8-8bd4-538aa43bc3bc.PNG)

**Additional context**
I think this caused it https://github.com/pypa/warehouse/pull/3829 cc @nlhkabu @di

**Comment by di** [comment]
@ofek I think you're right. @yeraydiazdiaz could you take a look?

**Comment by yeraydiazdiaz** [comment]
sure, should be easier now that it's a Stimulus controller 👍

**Comment by di** [comment]
@yeraydiazdiaz To be clear, I think this is a bug in the new stimulus controller.

**Comment by yeraydiazdiaz** [comment]
Definitely, it's a consequence of how we're (ab)using anchors to store the state of the tabs. I was thinking of using Stimilus's state management API instead.
