### ISSUE TITLE
transfer / release / claim invalid project `forge` (pep-541)

### ISSUE THREAD

**Issue by dfee** [pypa/warehouse#4001]
According to [PEP-0541](https://www.python.org/dev/peps/pep-0541/#invalid-projects), projects that conform to the following behavior are subject to removal `project is name squatting (package has no functionality or is empty);`.

[`forge`](https://pypi.org/project/forge) is an example of a project like this:
- v0.0 was initially published on Mar 19, 2010 with no code and project description: "not released yet" 
- it's 2018 (8 years later on Friday) and there has been no update.

I've attempted to get a hold of Mark Ramm (by email, linkedin, and twitter) to transfer ownership, and haven't heard back from him.

I've also sought resolution on the [pypa-dev mailing list](https://groups.google.com/forum/#!topic/pypa-dev/qT77cpK2ck8), and was directed here.

Unlike other PEP-541 requests, this seems pretty clear cut. Let me know how to proceed.

**Comment by dfee** [comment]
@brainwane where does the current process stand? I've looked through the tickets and can't figure out if the `PEP 541` workflow is inactive, if I need to provide more information, etc.

Do you / pypa have any clarity on when these sorts of issues will be resolved? Is it in my best interest to publish my software under a different name, or to wait? Again, if the answer is "wait", then how long?

Thanks

**Comment by yeraydiazdiaz** [comment]
Hello @dfee, sorry for the delay on processing this request.

I've tried contacting Mark by email and hopefully he will come back to us soon regarding your claim. 

As you mention the project has a single empty release which falls under [the name squatting bullet point of invalid projects category in PEP 541](https://www.python.org/dev/peps/pep-0541/#invalid-projects). If it's ok with you we'll give Mark some time respond to my email and otherwise take action.

**Comment by yeraydiazdiaz** [comment]
Hello @dfee, Mark has not responded in a timely fashion to my attempt to contact him so we'll proceed to transfer ownership of the package to you.

Can you confirm your PyPI username for me, please?

**Comment by dfee** [comment]
Sure: `dfee`.

**Comment by di** [comment]
Done. Please note that you won't be able to make a release with version `0`, `0.0`, `0.0.0`, etc. as this was previously used.
