### ISSUE TITLE
Python projects' README.rst: Local referencing of image location now presents broken image

### ISSUE THREAD

**Issue by jeff00seattle** [pypa/warehouse#4005]
**Describe the bug**
Several projects that I am contributing to, I have been able to use a local reference to an image when adding to README.rst. However, recently within the last couple of months, local referencing no longer work. 

**Expected behavior**
Images should be viewable within `README.rst` either if locally or remotely referenced, as they had been viewable in 2018 March.

**To Reproduce**
For example, Pypi.org project `requests_mv_integrations`:

In this project's `README.rst` images are referenced locally:
```
.. image:: ./images/requests_mv_integrations.png
```
Images are viewable in `README.rst` on Homepage Github:
https://github.com/TuneLab/requests-mv-integrations/blob/master/README.rst

However, now these same images are broken on Pypi.org:
https://pypi.org/project/requests-mv-integrations/#description

And yes, locally referenced images have been included in `MANIFEST.in`:
https://github.com/TuneLab/requests-mv-integrations/blob/master/MANIFEST.in
```
recursive-include images *.png
```

This was not the case in 2018 March the last time I did an upload to Pypi.org 

**Additional context**
I investigated project `requests2` and it images are still viewable, however, this projects README.rst is using external referencing of images. This is not convenient and not reasonable because typically MANFEST when :
https://raw.githubusercontent.com/requests/requests/master/README.rst
```
.. image:: https://raw.githubusercontent.com/requests/requests/master/docs/_static/requests-logo-small.png
```

**Comment by nlhkabu** [comment]
@di would you be able to look into / respond to this? Thx :)

**Comment by ewdurbin** [comment]
PyPI does not and has never served images from the contents of uploaded distributions. I'm not sure how it would have been working before.

The only way to have images displayed in the description is for those images to be hosted somewhere that our image proxy ([warehouse-camo](https://github.com/pypa/warehouse-camo)], based on [camo](https://github.com/atmos/camo)] can retrieve it.

**Comment by di** [comment]
Images must be externally hosted, and this requirement has always existed. We don't expose individual files within a distribution, so this feature is not really possible, either. Sorry!
