### ISSUE TITLE
No emails from test.pypi.org

### ISSUE THREAD

**Issue by divenex** [pypa/warehouse#4009]
I registered to test.pypi.org but never received any confirmation email and consequently cannot activate my account.

Here is what I tried:

- I tried registering different users names, with different email addresses but never received any confirmation email to those addresses either. 
- I tried the menu "resend confirmation email" without success. 
- I also tried a password reset, but still got no email.
- I checked that the email is not in the spam folder. 
- Finally, using the **same** username and email on pypi.org worked as expected: I received the confirmation email and could verify my email.

**Comment by di** [comment]
@divenex Could you email me at `di@python.org` with the email address and username of the account?

**Comment by divenex** [comment]
Done, thank you very much

**Comment by di** [comment]
Looks like TestPyPI is having trouble sending mail to `@outlook.com` addresses in general.

We are planning to switch the mail service we use for it in the near future, however in the meantime, anyone else having this issue: send me a message (`di@python.org`) from your `@outlook.com` address with your TestPyPI username.

**Comment by wohali** [comment]
@di I am also unable to receive email to my `@apache.org` address, or my personal address. I will email you directly for assistance.

**Comment by di** [comment]
At the moment TestPyPI is not sending any emails at all, anyone currently having issues please hang tight while we sort it out.

**Comment by di** [comment]
This has been resolved (all emails from TestPyPI to any address should be working).

**Comment by GaryBloom** [comment]
I've been waiting about four hours for  verification emails to my hotmail.com address. Is this an issue once again?

**Comment by ewdurbin** [comment]
Hi @GaryBloom, looking at the delivery logs for TestPyPI, I see the email verification attempts.

Both have been reported as delivered by hotmail servers. Have you checked your spam or any other filters you might have configured?

**Comment by GaryBloom** [comment]
Ouch! I'm so embarrassed! They were sitting in my spam folder. Sometimes I forget that I have TWO. 🙂
Thanks so much! Sorry to have bothered you!
________________________________
