### ISSUE TITLE
Support CSS Sourcemaps

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#401]
Do we want to generate CSS Sourcemaps? If so how do we generate them?

**Comment by nlhkabu** [comment]
Yes,  This article might be helpful: https://medium.com/@toolmantim/getting-started-with-css-sourcemaps-and-in-browser-sass-editing-b4daab987fb0#.wv4414pac

**Comment by dstufft** [comment]
Cool! This may be made more complicated by our overall pipeline, but I can't imagine we're the first people to need to process these files like we are.
