### ISSUE TITLE
Create "Moderator" level User and corresponding permissions

### ISSUE THREAD

**Issue by di** [pypa/warehouse#4011]
Currently on PyPI, we have two types of users:
* regular users
* administrators (for which `User.is_superuser` is true)
* (There is also a field `User.is_staff` but I believe it's unused).

It'd be great to add an intermediate level of user, "Moderator", which has the ability to do the following:
* view all the existing `/admin` views (but read-only)
* set upload limits
* add classifiers
* etc

The "Moderator" user should not be able to:
* change emails (including verified or active status)
* delete projects
* nuke users

(cc @99)

**Comment by di** [comment]
Agreed. I think the steps to address this, roughly broken up by PRs, would be:
* Add a new field/migration to the `User` model, as well as corresponding UI in `/admin` for administrators to toggle this flag for users;
* Add ACLs for various `/admin` POST endpoints, as well as conditionals in the HTML templates to hide actions that are not enabled for moderators, and to make fields not appear editable;
* Add back these actions as "request/recommendation" actions that get raised to administrators. This could piggyback on the system we use for #3896.

**Comment by dstufft** [comment]
Yea, that seems like a great path forward.

**Comment by crwilcox** [comment]
I am going to start working on this. I have the first part complete (add new field and migration as well as adding is_moderator as settable in admin UIs) https://github.com/pypa/warehouse/pull/5249/files

**Comment by crwilcox** [comment]
@di @dstufft I am moving on to `Add ACLs for various /admin POST endpoints, as well as conditionals in the HTML templates to hide actions that are not enabled for moderators, and to make fields not appear editable;`

Do you have a starting list of activities you would like to allow moderators to do? For instance, should moderators be able to mark other users as having a verified email?

**Comment by di** [comment]
@crwilcox See the issue body:

> view all the existing /admin views (but read-only)
> set upload limits
> add classifiers

**Comment by di** [comment]
#5249 is merged, we can now set users as moderators.

@jamadden @yeraydiazdiaz Would you like to be moderators?

**Comment by yeraydiazdiaz** [comment]
That’s a yes for me, thanks ☺️

**Comment by crwilcox** [comment]
@theacodes volunteered if you want additional moderators.

**Comment by pradyunsg** [comment]
I volunteer too, if you need more eyes and hands on deck. :)

**Comment by jamadden** [comment]
@ewdurbin I got your Slack invite, thank you. Would it be possible to switch it to the alternate address for my PyPI account?

**Comment by ewdurbin** [comment]
absolutely. will do.

**Comment by di** [comment]
Hey, we have moderators now! Closing this.
