### ISSUE TITLE
Redirect loop when requesting missing package

### ISSUE THREAD

**Issue by jbergknoff-rival** [pypa/warehouse#4012]
**Describe the bug**
When I `curl -v https://pypi.org/pypi/bogus/1.0.0/json` with an invalid package/version combination, I get put in an infinite redirect loop. If the package/version combination is correct, then the data is served as expected.

I noticed this because the `license_finder` gem just now started having issues when looking for my team's internal (non-PyPi) packages. Previously, it hadn't complained.

**Expected behavior**
For an invalid package/version combination, I'd expect a 404 (or whatever the previous behavior was).

**To Reproduce**
`curl -v https://pypi.org/pypi/bogus/1.0.0/json`, note that the `Location` header leads you to the same URL.

**My Platform**
Pretty sure my platform isn't relevant. I've reproduced the problem both from my personal internet connection as well as within AWS.

**Additional context**
Adding @dstufft @di as suggested on IRC.

**Comment by dstufft** [comment]
I'm guessing this is likely fallout from https://github.com/pypa/warehouse/pull/3971.

**Comment by di** [comment]
Looks like this is because we use `@notfound_view_config(append_slash=HTTPMovedPermanently)` with our exception view, so when it's not found, it gets a redirect to the same URL with the trailing slash.
