### ISSUE TITLE
Add trailing slash redirects to JSON API 

### ISSUE THREAD

**Issue by di** [pypa/warehouse#4016]
The JSON API currently resolves URLs like `https://pypi.org/pypi/pip/json`, however adding a trailing slash (e.g. `https://pypi.org/pypi/pip/json/`) results in a 404, even though trailing slashes were valid in legacy PyPI.

PR https://github.com/pypa/warehouse/pull/3971 was an attempt to fix this, but because we have Pyramid configured to automatically add a trailing slash in the event of a 404, this resulted in a redirect loop.

**Comment by alexbecker** [comment]
Is the fix for this to change the Pyramid configuration to special-case this? Or to support `https://pypi.org/pypi/pip/json/` without redirecting?
