### ISSUE TITLE
Test PyPI should include the `--index-url` argument for the pip install command.

### ISSUE THREAD

**Issue by theacodes** [pypa/warehouse#4018]
**What's the problem this feature will solve?**
Copy-pasting the pip install command on Test PyPI won't actually install from Test PyPI

**Describe the solution you'd like**
instead of `pip install package_name` we should show `pip install --index-url https://test.pypi.org/simple/ package_name`

**Additional context**
It would also be super awesome if pip just had an alias for this, e.g. `pip install --with-test-pypi package_name`.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by fitodic** [comment]
@nlhkabu Can I try this one?

**Comment by nlhkabu** [comment]
Great @fitodic

**Comment by nlhkabu** [comment]
@fitodic GitHub wont let me assign this to you - so I'll assign it to me so no one else takes it :)

**Comment by nlhkabu** [comment]
Removing the sprint label to reserve :)

**Comment by fitodic** [comment]
Thanks :+1:

**Comment by fitodic** [comment]
@nlhkabu I've just noticed there's already a pull request for this issue: https://github.com/pypa/warehouse/pull/4044

Should I move on?

**Comment by nlhkabu** [comment]
ah, yes sorry.  I will remove this from the sprint list.  my mistake!

**Comment by di** [comment]
Fixed in #4941.
