### ISSUE TITLE
"How to access old website of pypi for repositories"

### ISSUE THREAD

**Issue by SabaKauser** [pypa/warehouse#4020]
**Describe the bug**

Hello,
I could find only this topic very close to my concern. 
Until few days back, we were able to access old legacy website of pypi and it had information that was important and I do not see it appearing in new website under my project. 
My project is python ibm_db driver and I would like to gain access to old page temporarily to backup the screenshots and other needed data. 
Could you please grant me access to it.

**Expected behavior**

I need access to old page temporarily.

**To Reproduce**

https://pypi.org/project/ibm_db/#description  

**My Platform**

**Additional context**

**Comment by di** [comment]
Legacy PyPI is no longer online. The best you could do is find your package on various web archiving services, for example:

* https://web.archive.org/web/20160829195835/https://pypi.python.org/pypi/ibm_db/
