### ISSUE TITLE
Add admin ability to reassign project to another user

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#4022]
Legacy PyPI allowed admins to take over an existing project, but Warehouse doesn't have a mechanism to allow an admin to re-assign a project to another user.

**Comment by nanuxbe** [comment]
@nlhkabu I'm going to work on this during the ep18 sprints.

The plan is to add an expandable section at the bottom of the project's "view" page in the admin similar to "Delete Project" or "Set Upload Limit"

**Comment by di** [comment]
Since a project might have multiple owners, it would be ideal if this feature allowed us to add/remove roles for a given project.

**Comment by di** [comment]
(Also probably worth mentioning that the users in the dev DB with admin access are `dstufft`, `ewdurbin` and `di`)

**Comment by nanuxbe** [comment]
So far...

Both collapsed:
![screenshot 2018-07-28 at 18 30 58](https://user-images.githubusercontent.com/1215070/43358584-81dcc7e6-9294-11e8-960c-9553682204a4.png)

Both expanded:
![screenshot 2018-07-28 at 18 31 12](https://user-images.githubusercontent.com/1215070/43358588-8c256140-9294-11e8-9a00-7e99a133edbb.png)

**Comment by nlhkabu** [comment]
Can we please make the text:

`"To delete role "blah" for "blah", type the role name:`

- remove placeholder ;)
