### ISSUE TITLE
Searching for coverage produces xmlrpc.client.Fault: <Fault -32500: 'application error'>

### ISSUE THREAD

**Issue by nedbat** [pypa/warehouse#4028]
Sorry: I don't know where the fault and fix lie, so I am trying a few different bug trackers.

* Pip version: 10.0.1
* Python version: 3.6.5
* Operating system: Mac 10.13.4

### Description:

(as reported in https://github.com/nedbat/coveragepy/issues/50 and https://github.com/pypa/pip/issues/5414)

Try to search for "coverage", get an error:

```
$ pip --version
pip 10.0.1 from /usr/local/virtualenvs/prz3/lib/python3.6/site-packages/pip (python 3.6)

$ python -V
Python 3.6.5

$ pip search coverage
Exception:
Traceback (most recent call last):
  File "/usr/local/virtualenvs/prz3/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/virtualenvs/prz3/lib/python3.6/site-packages/pip/_internal/commands/search.py", line 48, in run
    pypi_hits = self.search(query, options)
  File "/usr/local/virtualenvs/prz3/lib/python3.6/site-packages/pip/_internal/commands/search.py", line 65, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/local/pythonz/pythons/CPython-3.6.5/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/pythonz/pythons/CPython-3.6.5/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/local/virtualenvs/prz3/lib/python3.6/site-packages/pip/_internal/download.py", line 792, in request
    return self.parse_response(response.raw)
  File "/usr/local/pythonz/pythons/CPython-3.6.5/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/local/pythonz/pythons/CPython-3.6.5/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: 'application error'>

$
```

I've tried searching for a bunch of other things, and none of the other terms caused errors: "requests", "cov", "cover", "coverage.py", "cog", "wfwefwefwefwefwef", etc.

This might be something about the [coverage](https://pypi.org/project/coverage) package itself, but what?

**Comment by dstufft** [comment]
It's a warehouse bug most likely, not entirely sure what off hand as nothing relevant is showing up in sentry if I do a search. It'll probably require trying to reproduce against a local copy of Warehouse to figure out what's happening.

**Comment by randomir** [comment]
`warehouse` fails with the same error also when searching for `sqlite` (in addition to `coverage` and `config`). It works for `sqlit`/`sqlite2`/`coverag`/`conf`/`configg`/etc.

But, what's **interesting**, it's failing only for those keywords used in `name` XML-RPC param, not in `summary`.

So, calling `search` RPC method (`POST` to `https://pypi.org/pypi`) with `name, summary = 'coverag', 'coverage'` works correctly (request body below). But by default `pip search coverage` will set both `name, summary = 'coverage', 'coverage'` -- and that will fail.

```
<?xml version='1.0'?>
<methodCall>
    <methodName>search</methodName>
    <params>
        <param>
            <value>
                <struct>
                    <member>
                        <name>name</name>
                        <value>
                            <array>
                                <data>
                                    <value>
                                        <string>coverag</string>
                                    </value>
                                </data>
                            </array>
                        </value>
                    </member>
                    <member>
                        <name>summary</name>
                        <value>
                            <array>
                                <data>
                                    <value>
                                        <string>coverage</string>
                                    </value>
                                </data>
                            </array>
                        </value>
                    </member>
                </struct>
            </value>
        </param>
        <param>
            <value>
                <string>or</string>
            </value>
        </param>
    </params>
</methodCall>
```

**Comment by randomir** [comment]
Another data point: no error when using `and` operator, instead of `or`.

**Comment by randomir** [comment]
Also, I can **not reproduce this bug on a fresh docker container**, initialized as described here: https://warehouse.readthedocs.io/development/getting-started/.

Sorry, you'll have to trace it on your (prod) system.

But looks like caching could have something to do with this.

**Comment by pradyunsg** [comment]
Also: https://github.com/pypa/pip/issues/5435

**Comment by randomir** [comment]
Update: searching for coverage, config, etc. now works.

Bug fixed? What was the problem?

**Comment by di** [comment]
Fixed in https://github.com/pypa/warehouse/pull/4180.

**Comment by nedbat** [comment]
@di I'm confused: what is "summary", and why doesn't coverage have one?  Is there something I've left out of the package?

**Comment by dstufft** [comment]
Coverage has a summary, it correlates with the ``description`` keyword in ``setup.py``. Not sure why that change would have fixed it.

**Comment by di** [comment]
Because some of the other results for `pip search coverage` don't have a summary, so it would have resulted in an error for the entire search.
