### ISSUE TITLE
Finish implementing the User Profile

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#403]
Right now the user profiles (``/user/<username>/``) is primarily just some placeholder content that doesn't have any real function. Actually implement a reasonable profile page.

**Comment by vladimir-v-diaz** [comment]
After I'm done reading the installation instructions, setting up, etc., I would like to work on this issue.

**Comment by nlhkabu** [comment]
I'm going to close this as we now have a page for this in the new UI
