### ISSUE TITLE
File too large. Size limit exemption

### ISSUE THREAD

**Issue by jadsonbr** [pypa/warehouse#4031]
**Project name:** pyreportjasper
**Size:** 78 MB
**For:** PyPI and Test PyPI

**Comment by di** [comment]
@jadsonbr Can you explain what this project is and why it is so large?

**Comment by jadsonbr** [comment]
It is an abstraction to generate reports in python with JasperReport java library. It was necessary to include dependency maps. So it got a little big.

**Comment by jadsonbr** [comment]
@di Can you tell me how long this liberation process takes?

**Comment by di** [comment]
@jadsonbr I've set the limit for `pyreportjasper` to 80MB on both PyPI and TestPyPI.
