### ISSUE TITLE
pypi says my project has no description but it does

### ISSUE THREAD

**Issue by msoulier** [pypa/warehouse#4036]
https://pypi.org/project/tftpy/

"The author of this package has not provided a project description"

msoulier@anton:~/work/tftpy$ grep description setup.py
      description='Python TFTP library',

So, I'm confused. What must I do?

**Comment by di** [comment]
You should set the `long_description` kwarg in `setup.py`: https://packaging.python.org/tutorials/distributing-packages/?highlight=long_description#description

**Comment by helloDestroyerOfWorlds** [comment]
Wow this is just a really, really bad way for pypi to behave.  So much so I'm re-opening issue until something is done about it.

I just spend > 20 hours troubleshooting this error because I couldn't find this answer because this was closed.  Had to dig around for so long and wasted so much time!
