### ISSUE TITLE
django-plans abandoned - PEP 541 transfer

### ISSUE THREAD

**Issue by Alir3z4** [pypa/warehouse#4037]
Per #1506 and PEP 541, I'd like to ask you to transfer the ownership of https://pypi.org/project/django-plans/ to me (user name alir3z4).

I have contacted the package owner several times and no response, both via Email as well as mentioning them on the original repo https://github.com/cypreess/django-plans/issues/57#issuecomment-348817473 which neither @swappsco or @cdvv7788 replied.

The package https://pypi.org/project/django-plans/ is at https://github.com/swappsco/django-plans and a fork of original project at https://github.com/cypreess/django-plans.

I'm the maintainer of the original project https://github.com/cypreess/django-plans and we're currently since the fork has taken up the name.

Thanks,
Alireza Savand

**Comment by cdvv7788** [comment]
@Alir3z4 Hi. Sorry for not answering before. I added you as "owner" on pypi. Don't know how to remove myself. Please check if you can do it.

**Comment by Alir3z4** [comment]
@cdvv7788 Thanks for the help, I confirm the maintainership now.
