### ISSUE TITLE
Gravatars are broken on pypi.org

### ISSUE THREAD

**Issue by anowlcalledjosh** [pypa/warehouse#4043]
Gravatars across PyPI are not loading because of HTTP 504s from https://warehouse-camo.cmh1.psfhosted.org.

To reproduce: Load a [project page](https://pypi.org/project/Flask/) or [user page](https://pypi.org/user/davidism/), and look at the maintainers list or (lack of) profile picture.

I'm using Chrome 67.0.3396.48 (beta channel) on Ubuntu 16.04.4.

Example of part of the maintainers list for Flask:

![image](https://user-images.githubusercontent.com/9433472/40270461-c7c22076-5b85-11e8-9d7e-db053ebdd492.png)

Logs:

![image](https://user-images.githubusercontent.com/9433472/40270479-364ba986-5b86-11e8-9d22-30569954b8b1.png)

**Comment by nlhkabu** [comment]
I can reproduce - in fact, I was just about to open a ticket for this.  Thanks for beating me to it @anowlcalledjosh :)

**Comment by ewdurbin** [comment]
Thanks for report. Gonna look into the reasons why, but it appears that the TLS certificates for the service expired and were not renewed.

This is resolved for now.
