### ISSUE TITLE
Visual Design: swap syntax highlighting colors

### ISSUE THREAD

**Issue by mixmastamyk** [pypa/warehouse#4047]
Not a biggie, but keywords being highlighted in blue is more common. If swapped with the integer color, keywords could be blue and numbers green.

Believe that would match the site colors better as well, as the keywords stand out a lot.

![shot](https://user-images.githubusercontent.com/767039/40273592-a19be84a-5b77-11e8-904a-cae6daef2d3a.png)

Thanks, awesome job.

**Comment by nlhkabu** [comment]
thanks for the suggestion @mixmastamyk.
Is there a particular example you can site for blue keywords being more common?

**Comment by mixmastamyk** [comment]
There are no studies per se, but blue is for keywords in the default themes of stackoverflow and MS Visual Studio:

- https://stackoverflow.com/q/231767/450917
- http://www.hanselman.com/blog/ChangingYourColorsInVisualStudioNETBlackVersusWhite.aspx
- https://code.visualstudio.com/docs/getstarted/themes

As mentioned it might fit with the site better, the keywords are common in python, bold, and demand focus.  It might be a good idea for them to match the main site color, a nice medium to dark blue.

Dunno, take a look and let's hear what you think?  Easy to change temporarily in a browser's dev tools.

**Comment by nividonis** [comment]
@nlhkabu Can I take this one?

**Comment by nlhkabu** [comment]
Yes! Let me know if you need help finding the SCSS :)

**Comment by mixmastamyk** [comment]
Nice, like your can do attitude.  ;-)
