### ISSUE TITLE
TestPyPI login page says None where it should say something else

### ISSUE THREAD

**Issue by pradyunsg** [pypa/warehouse#4050]
**Describe the bug**
The login page on TestPyPI says: "Accounts from None work too!"

**Expected behavior**
Instead of "None", something else should be said there. 

**To Reproduce**
https://test.pypi.org/account/login/

**My Platform**
I don't expect this to be browser specific but I'm using FF 60 on MacOS.

**Additional context**

<img width="1345" alt="screen shot 2018-05-21 at 12 34 40 pm" src="https://user-images.githubusercontent.com/3275593/40294472-57ac2790-5cf3-11e8-9d6b-b1a59628d1f4.png">

**Comment by ewdurbin** [comment]
Ah! this is a remnant from when pypi.python.org and pypi.org were running separately! we can simply remove the clause.
