### ISSUE TITLE
OpenGLContext 2.3.0b1 安装时出现 invalid syntax

### ISSUE THREAD

**Issue by JamesHui97** [pypa/warehouse#4053]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by jamadden** [comment]
Thanks for your report, but this is not the correct place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help with packages installed from there. You'll need to contact the maintainers of that project. Its [project page](https://pypi.org/project/OpenGLContext/) has an email address for the maintainer and a link to the project home page.
