### ISSUE TITLE
Workarounding problem with "gi" package name conflict

### ISSUE THREAD

**Issue by galkinvv** [pypa/warehouse#4054]
There were an issue https://github.com/pypa/pypi-legacy/issues/759 about problems caused by gi package in pypi repo.

It was closed because no consensus was made. I'm creating this issue to propose and discuss another  solution and (as I hope) get reach to original package owner https://github.com/inconditus @inconditus

The typical problem scenario with "gi" package is following:
* a lot of python software is written with gobject-instrospection with "import gi" statement.
* somebody tries to run/install such software from source
* if no python gobject-introspecion module is installed - python says that can't import "gi" package
* in attempt to install it the `pip3 install gi` is executed.
* the command above installs python2 package from https://pypi.org/project/gi
* after this running the software fails with a strange exception, and a question appear in a bugtracker/forum etc

examples of such exceptions:
* quoted "gi/__init__.py, line 39 print url" in google by now gives by now 28 different results in different projects (this is message arising while trying to use package with py3)
* pair of quoted strings "gi.require_version" "has no attribute require_version" gives over 200 results in google, I think it is python2 usages.

The main point of original discussion in https://github.com/pypa/pypi-legacy/issues/759 is that gi package by itself is fine and can be useful, so I propose a resolution that keeps it but modifies in a way to be less error-prone:
* mark package as python2-only so it can't be mis-installed with pip on python3, so the problem would phase out in the future
* write description to it's pypi page clarifying that it isn't related to gnome-introspection.

(I'll try to reach the package owner by email and include link to this issue in the mail text)

**Comment by yeraydiazdiaz** [comment]
I'm closing this as the `gi` package currently has no releases and is therefore not installable.
