### ISSUE TITLE
My user isn't allowed to upload to project

### ISSUE THREAD

**Issue by charlsagente** [pypa/warehouse#4057]
I already submitted my project into test.pypi.org and was working fine, but when trying to go to your 'live' server I receive the following error: 

```
twine upload dist/*
The user 'charlsagente' isn't allowed to upload to project 'python-settings'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

Can you help me find the issue?

**Comment by ewdurbin** [comment]
Another user registered this project name with PyPI on May 14, 2018 and immediately removed the project.

We're still working to formalize the process, but this appears to be a PEP 541 issue.

**Comment by charlsagente** [comment]
Thanks for your help. 
Should I wait until the name is available? or just change my project name?

**Comment by di** [comment]
@charlsagente Either would be a reasonable thing to do. We don't currently have a timeline for when we will start processing PEP 541 requests, so if you'd like to publish your package sooner than later, renaming it is probably the way to go.

**Comment by yeraydiazdiaz** [comment]
Hello @charlsagente, sorry for the delay in processing this request.

Expanding on what @ewdurbin commented, the project `python-setting` currently has no releases and therefore falls under name squatting in the ["Invalid projects" section of PEP 541](https://www.python.org/dev/peps/pep-0541/#invalid-projects) and thus is subceptible for removal.

I've sent an email to @mkurek regarding your claim, hopefully we will hear from him soon and move forward with your claim.

**Comment by mkurek** [comment]
@yeraydiazdiaz feel free to delete/transfer this project on pypi 😉

**Comment by charlsagente** [comment]
Awesome guys, thanks for the help

**Comment by yeraydiazdiaz** [comment]
Thanks for responding so quickly @mkurek. 

If @charlsagente can verify the PyPI username it might be best to add him as an owner of the project yourself if you don't mind. We prefer this so transferrals are between users and moderation is minimised.

**Comment by mkurek** [comment]
@charlsagente i've made you an owner of python-settings project on pypi.

**Comment by yeraydiazdiaz** [comment]
Thank you @mkurek and @charlsagente

**Comment by mit1280** [comment]
This is due to uploading the same file more than ones. If you will change version or name of tar file then you will be able to upload your file on PyPI. Before that make sure that in **dist/** you have only one file which is you wanna upload.

if you use mac then you can see files present in dist folder using below command:

write-in terminal
`ls dist/`

if you want to remove any file from that folder then run below command
`rm dist/file_name`
