### ISSUE TITLE
Please increase my pypi upload file size limit

### ISSUE THREAD

**Issue by zylo117** [pypa/warehouse#4068]
The name of the project: tensorflow-gpu-macosx
The size of your release, in megabytes: 94.6MB (maybe a little bigger in the later version)
Which index/indexes you need the increase for (PyPI, Test PyPI, or both): both

Please help me increase my upload limit, thank you

**Comment by yeraydiazdiaz** [comment]
Hi @zylo117, sorry for the delay on addressing this issue.

Could you clarify the reason you're moving from 20MB to ~95MB?

**Comment by zylo117** [comment]
Because the whl that I wanted to upload is bigger than 20MB. Most of the components are pre-compiled binary, so it's much bigger than normal source pypi package tar.gz. I pre-compiled it because the compilation would take hours, it's not wise to do so on every user's computer. My repo is here, https://github.com/zylo117/tensorflow-gpu-macosx

**Comment by yeraydiazdiaz** [comment]
Can I ask what is the use case for this package?

Our concern is that it might be misleading to users as there is [explicitly no GPU support in Tensorflow](https://www.tensorflow.org/install/source#install_gpu_support_optional_linux_only). Also there doesn't seem to be any modern Macs with Nvidia graphics cards.

**Comment by zylo117** [comment]
Just wanted to share. Tensorflow did have a official python package called tensorflow-gpu while there is also another official pkg call tensorflow. And tensorflow team stop gpu support on mac since version 1.2. I found a solution to solve it and would like to share it to the public. According to my repo's issues, there are plenty of developers use eGPU on Mac, and also there are hackintosh users who use actual PCI-e NVIDIA GPU.

**Comment by yeraydiazdiaz** [comment]
Thanks for clarifying @zylo117. I've increased the upload limit to 120 MB in pypi.org.

The project is not in test.pypi.org though, let us know if you also need an increase there at some point.
