### ISSUE TITLE
docker:dind cannot connect to files.pythonhosted.org

### ISSUE THREAD

**Issue by ntcong** [pypa/warehouse#4069]
I have filed a problem with docker:dind and using pip here https://github.com/docker-library/docker/issues/112
The problem comes in like a few days ago., the connection to files.pythonhosted.org is extremely unstable, I can only do a successful pip install 1 package with several retry. 
Connection to pypi is fine, just files.pythonhosted.org has problem (and almost all others hosting I can try have no problem)

```shell
;; ANSWER SECTION:
files.pythonhosted.org. 29      IN      CNAME   dualstack.r.ssl.global.fastly.net.
dualstack.r.ssl.global.fastly.net. 29 IN A      151.101.1.63
dualstack.r.ssl.global.fastly.net. 29 IN A      151.101.65.63
dualstack.r.ssl.global.fastly.net. 29 IN A      151.101.129.63
dualstack.r.ssl.global.fastly.net. 29 IN A      151.101.193.63
```

### Traceroutes
```shell
traceroute files.pythonhosted.org
<Replace with your output>
```
### HTTPS Requests
```shell
root@f0a2f26d65e1:/# curl -vvv -I --ipv4 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz
*   Trying 151.101.1.63...
* TCP_NODELAY set
* Connected to files.pythonhosted.org (151.101.1.63) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
- hanging here
```

```shell
root@f0a2f26d65e1:/# echo -n | openssl s_client -4 -connect files.pythonhosted.org:443
CONNECTED(00000003)
- hanging here
```

**Comment by ntcong** [comment]
I ran it in a k8s cluster (setup with kubespray and flannel network plugin).

- With ubuntu image it ran fine.
- With docker:dind image it got handshake failure

In the linked issue I posted the exact command I used

**Comment by yosifkit** [comment]
> The docker:dind image does not have an ssl library installed by default; you'll need to `apk add` it:
> 
> ```console
> $ docker run -it --rm docker:dind sh
> / # apk add --no-cache libressl
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
> (1/2) Installing libressl2.6-libtls (2.6.3-r0)
> (2/2) Installing libressl (2.6.3-r0)
> Executing busybox-1.27.2-r7.trigger
> OK: 17 MiB in 38 packages
> / # wget https://files.pythonhosted.org/packages/25/4d/c8228419346a0e84aec202a43e181afc6572b861d38f8a0306dbce6abef0/Django-1.11.13-py2.py3-none-any.whl
> Connecting to files.pythonhosted.org (151.101.53.63:443)
> Django-1.11.13-py2.p 100% |*****************************************|  6785k  0:00:00 ETA
> / # 
> ```

https://github.com/docker-library/docker/issues/112#issuecomment-391427250

**Comment by jansmets** [comment]
I found this to be an MTU problem with dind, I'm running on bare metal k8s with flannel overlay network. Setting dind --mtu to 1450 (1500-50(vxlan)) resolved this for me.
