### ISSUE TITLE
Complete the Project Detail page

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#407]
There are a number of features left out on the project detail pages:

* [ ] Provides-Dist support.
* [ ] Requires-Dist support.
* [ ] Project URLs/Bugtrack URLs/Any other URLs.

**Comment by vladimir-v-diaz** [comment]
Working on this issue.

**Comment by nlhkabu** [comment]
@dstufft are you happy to close this given the new UI?

**Comment by dstufft** [comment]
Yes.
