### ISSUE TITLE
"How to mark a release as newest in pypi"

### ISSUE THREAD

**Issue by SabaKauser** [pypa/warehouse#4075]
Hello,
I am owner of ibm_db package that is available here -> https://pypi.org/project/ibm_db/2.0.8/
I had made a new release 2.0.8a that I was thinking to be picked as latest according to timestamp. However, pypi seem to have naming convention according to which it is considered pre-release.
I do not plan to make a new release with new name as I do not have any functional new development and hence it would be considerable effort to make a new release just for changing name.
I am looking forward for some solutions to solve this without making a new release.
1. is it possible to rename 2.0.8a to 2.0.9?
2. Would pypi pick 2.0.8a as new release if I delete 2.0.8 from list?
3. Is there any other possible solution available to have 2.0.8a considered as latest release.

Thanks in advance!

**Comment by dstufft** [comment]
PyPI (and pip, etc) follow PEP 440, which sees 2.0.8a as an alpha release. There's not a way to rename the version and deleting ``2.0.8`` won't make ``2.0.8a`` be seen as the latest. You'll need to release something ``2.0.9`` os similar.
