### ISSUE TITLE
Design the Login/Logout/Register/Reset Pass Pages

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#408]
The Log in, log out, and register pages need to be designed so that they function and look good.

**Comment by dstufft** [comment]
Note: We need to support federated auth like PyPI currently does, however I'd like to de-emphasize it. Something like what bitbucket has done except without the buttons along the bottom, just a small link to enable the federated auth.

<img width="322" alt="screen-shot-2015-11-16-12-33-16" src="https://cloud.githubusercontent.com/assets/145979/11189490/5ce00b36-8c5e-11e5-8b41-54fe19b4276e.png">

**Comment by ewdurbin** [comment]
@dstufft thought's on breaking auth/login out into a separate concern completely? there have been requests for centralized identity management/SSO for Python in the past, and I'm fairly confident we could get an OAuth2 provider setup with a small effort.

This would allow PyPI to only be a consumer of a single OAuth2 Provider that *we* control. This would obviously require migrating users and somehow maintaining username/passwords for cli tools.

**Comment by dstufft** [comment]
@ewdurbin I have wanted to do that for a long time, I even added a ``id.python.org`` to the EV certificate from Digicert to do it. The main thing that would need to be solved is if we're making a centralized identity/SSO for Python is how do we combine all of the various identity silo's into a single one?

**Comment by ewdurbin** [comment]
@dstufft slowly and with some anger! I'm actually quite motivated to get to work on an `id.python.org`.

give me a week and let's see where that lands. PyPI can be an initial example for other projects/silos to follow.

**Comment by dstufft** [comment]
@ewdurbin Sounds great!

In my head, we migrated the CLI to just authenticate using a password grant instead of checking against the local user database. That wouldn't require any changes to the client side of things, just PyPI would use that to authenticate against ``id.python.org`` instead. When we work on Upload API v2 we can add a different oauth flow to that and deprecate/remove the password flow for PyPI at that point.

**Comment by nlhkabu** [comment]
Given that the logged in section is not going to be ready for launch, I am moving this out of the launch milestone.  This should be one of the first items to look at post launch.

**Comment by dstufft** [comment]
Someone has done some design work for these pages now (which I've tagged with the needs design review label) so I'm going to go ahead and close this.
