### ISSUE TITLE
Claim package `fibra`

### ISSUE THREAD

**Issue by mfrasca** [pypa/warehouse#4081]
- the [most recent pypi release of `fibra`](https://pypi.org/project/fibra/) is from 2009, 
- `fibra` does not run in Python3
- the author put [`fibra` on github](https://github.com/simonwittber/fibra/). however, that project has only one commit, from 2011,

- I have reconstructed history in [a separate fibra repository](https://github.com/mfrasca/fibra/),
- I made a start at porting fibra to python2/3

- I need fibra for a program I'm migrating to Python3

**Comment by jamadden** [comment]
This would fall under the umbrella of [PEP 541](https://www.python.org/dev/peps/pep-0541/), I think. The Warehouse admins are currently working on the tooling necessary to support that, so there's a backlog that's waiting to be processed. 

In the meantime, there are several steps the PEP outlines that [have to be completed](https://www.python.org/dev/peps/pep-0541/#continued-maintenance-of-an-abandoned-project) by the person wishing to claim the name of an abandoned project.

**Comment by mfrasca** [comment]
never mind, author is alive and well, and he added me to the maintainers.
