### ISSUE TITLE
Claim package name 'paws'

### ISSUE THREAD

**Issue by funkybob** [pypa/warehouse#4082]
Warehouse shows "Last released: Aug 19, 2012"

It has only one release, v0.0

pip reports:
  Could not find a version that satisfies the requirement paws (from versions: )
No matching distribution found for paws

**Comment by jamadden** [comment]
This would fall under the umbrella of [PEP 541](https://www.python.org/dev/peps/pep-0541/), I think. The Warehouse admins are currently working on the tooling necessary to support that, so there's a backlog that's waiting to be processed. 

In the meantime, there are several steps the PEP outlines that [have to be completed](https://www.python.org/dev/peps/pep-0541/#continued-maintenance-of-an-abandoned-project) by the person wishing to claim the name of an abandoned project.

**Comment by funkybob** [comment]
I've attempted to contact the maintainer, and will wait the 6 weeks as per the PEP.

However, I believe this package falls under the category of "Invalid Project", as per the clause:

- project is name squatting (package has no functionality or is empty);

**Comment by funkybob** [comment]
I got a reply from the original owner, who has graciously granted me ownership of the package.
