### ISSUE TITLE
API endpoint notification page not showing on test.pypi.org

### ISSUE THREAD

**Issue by ncoghlan** [pypa/warehouse#4087]
While investigating https://github.com/pypa/packaging-problems/issues/155 I found that while https://upload.pypi.org/legacy/ is showing the custom "API Endpoint" page from https://github.com/pypa/warehouse/pull/2408 as expected, https://test.pypi.org/legacy/ is showing the regular 404 error page.

**Comment by di** [comment]
I set the `FORKLIFT_DOMAIN` for our TestPyPI deployment to `test.pypi.org`, the "API Endpoint" page now appears at https://test.pypi.org/legacy/.
