### ISSUE TITLE
Need for file size limit increase

### ISSUE THREAD

**Issue by faltsi** [pypa/warehouse#4089]
We are planning initial release for Qt for Python, but unfortunately our wheels are a bit bigger than allowed to be uploaded to pypi.org. The project name in test.pypi.org is PySide2 and it will be the same in pypi.org. At the moment there are no Pyside2 packages in pypi.org only in test.pypi.org, while I try to avoid uploading any dummy packages and I was hoping that you could allow as to exceed the limit in both indexes (I'm not sure if it is possible to make the exception in pypi.org until initial packages are there). Currently the biggest wheel is 160 M.

**Comment by cmaureir** [comment]
Qt for Python was released using Qt servers, but it's really inconvenient to leave the wheels outside PyPi, is there a way to help speed up this process?

**Comment by di** [comment]
Hi @faltsi and @cmaureir, sorry for the delay in response.

Unfortunately we can't increase the limit until the project exists on PyPI, so you will have to create a dummy release that can later be deleted (perhaps version `0`)?

Let me know when that's done and I'll increase the limit.

**Comment by faltsi** [comment]
Thanks @di! I'll upload some dummy files to pypi today.

**Comment by faltsi** [comment]
Dummy files are now in place in pypi.org. Project name PySide2

**Comment by ewdurbin** [comment]
Upload limit lifted to 200M on test.pypi.org and pypi.org
