### ISSUE TITLE
"aws" package on pip confusing

### ISSUE THREAD

**Issue by drydenp** [pypa/warehouse#4097]
It's a little bit annoying that there exists an "aws" package which is obviously then not "awscli" but I only noticed that after I had spent half an hour trying to get it running ;-).

pip(3) install aws -- will install a python2 package that will subsequently not run, and pip(2) install aws -- will install a version that requires an older version of fabric, and which will subsequently also not run because a newer version is installed.

So it wouldn't be so bad if the "fake" aws was actually in working state, but it isn't.

**Comment by jamadden** [comment]
Thanks for your report!

This tracker is only for issues with the software that runs pypi.org itself. It cannot help with packages distributed or installed from there. For that, you'll need to contact the maintainers of the project. (There is [already an issue open](https://github.com/eofs/aws/issues/2).)

There are certain circumstances, [outlined in PEP 541](https://www.python.org/dev/peps/pep-0541/#abandoned-projects), when a project name can be removed or transferred. Tooling is being developed to address those cases, but is not yet ready.

**Comment by pradyunsg** [comment]
It might be useful to ask let the folks maintaining awscli to take a look at the situation and see if they can resolve this situation from their end, if they have control over the package.

**Comment by yeraydiazdiaz** [comment]
I agree the best course of action would be for `awscli` to take ownership of the `aws` project. If anyone in the team is interested please open a formal PEP 541 request as a separate issue.
