### ISSUE TITLE
File size limit exemption for package itur

### ISSUE THREAD

**Issue by iportillo** [pypa/warehouse#4102]
Hello,

I am trying to upload a new version of [itur](https://pypi.org/project/itur/), a package that implements the recommendations of the [International Telecommunications Union](https://www.itu.int/rec/R-REC-P/en) (ITU-R) to compute the atmospheric attenuation suffered by a satellite. 

The recommendations include a large number of text files (whicht are an integral part of the recommendations) to compute the atmospheric attenuation. This test files contain statistcs of several atmospheric varaibles (monthly temperature, pressure, etc.) that are used as inputs for the algorithms in the recommendations. I have tried to minimize the number of files required (several recommendations include more than 200 MB of text-data), but seems that this still not enough.

Since these files need to be included within the itur package, I am hitting the file-size limit.  Thus, I would like to request a size limit exemption for this package. Please, find below the information of the project:

**The name of the project:** itur
**The size of your release, in megabytes:** 150
**Which index/indexes you need the increase for (PyPI, Test PyPI, or both):** Both
**GitHub repository:**  [https://github.com/iportillo/ITU-Rpy](https://github.com/iportillo/ITU-Rpy)

I am using twine and below is a log of the output I get.
```
twine upload dist/* -u <username> -p <password>
Uploading distributions to https://upload.pypi.org/legacy/
Uploading itur-0.2.0-py2.py3-none-any.whl
HTTPError: 400 Client Error: File too large. Limit for project 'itur' is 60 MB. 
See https://pypi.org/help/#file-size-limit for url: https://upload.pypi.org/legacy/
```

Thanks for your help!
Inigo

**Comment by iportillo** [comment]
Hi, I just wanted to check what's the status of this request?

Thanks for your help,
Inigo

**Comment by di** [comment]
HI @iportillo, I've set the limit for `itur` to 200MB on PyPI, but I'm not seeing the project on TestPyPI. You'll need to make a release there before I can increase the limit.

**Comment by iportillo** [comment]
@di Thank you so much for your help.
