### ISSUE TITLE
Increase in the project size.

### ISSUE THREAD

**Issue by sidgurun** [pypa/warehouse#4113]
Hello,

I am trying to upload a new version of LyaRT;Grid, a package that enables astrophysicist to get the Lyman alpha line properties including a complex radiative transfer treatment in a fast and simple way. 

This package uses several machine learning and interpolation algorithms in order to infer the physical properties of Lyman alpha emission lines. The grids and machine learning trained algorithms are quite dense in order to achieve an excellent performance. As a result, the hard-disk size of these files gets quite big and thus the package hits the maximum file-size limit. Thus, I would like to request a size limit exemption for this package. Please, find below the information of the project:

**The name of the project:** LyaRT-Grid (although in the setup.py is LyaRT_Grid) 
**The size of your release, in megabytes:** 150 
**Which index/indexes you need the increase for (PyPI, Test PyPI, or both):** Both

I am using twine and below is a log of the output I get.

twine upload dist/* 
Uploading distributions to https://upload.pypi.org/legacy/
Uploading LyaRT_Grid-0.0.2-py2-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.3k/10.3k [00:01<00:00, 5.98kB/s]
Uploading LyaRT_Grid-0.0.2.tar.gz
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 123M/123M [00:38<00:00, 3.31MB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: File too large. Limit for project 'LyaRT-Grid' is 60 MB. See https://pypi.org/help/#file-size-limit

Cheers,
Siddhartha

**Comment by webknjaz** [comment]
Dup #4089

**Comment by sidgurun** [comment]
Hello,

How much time does it take the expansion of the limit for projects?

**Comment by sidgurun** [comment]
Hi,
Over the past month the size of the project has grown up to 800MB, so if finally the project size is increase it would be grate if it goes up to 1GB.

Tahnks!

**Comment by di** [comment]
Hi @sidgurun, 1000MB is quite large (this would be the largest distribution ever on PyPI). Have you considered any alternative ways to ship this data along with your package?

**Comment by sidgurun** [comment]
Hi, 

For now I have a function that check if the auxiliary data can be find. If the data is not found the code download it. However this is a little bit tedious, as the user has to run these functions to complete installation... 

I tried to find a way to automatically download the data after the installation but I didn't manage. 

I understand that 1000MB might be too much. So, do you know any efficient way to download auxiliary data during (or just after) the installation?

**Comment by webknjaz** [comment]
You can extend install command in setup.py, but that will only work for source dists, not binary wheels

**Comment by sidgurun** [comment]
Okey, thanks. I managed. Now when I execute  `pip install LyaRT_Grid ` it automatically downloads the external data. However I would appreciate if I could store this data en pypi if possible.

**Comment by yeraydiazdiaz** [comment]
Hi @sidgurun, given the size of your data I believe you'll need to settle for an external download solution. Other packages that require extra data ask the user to explicitly download the data, for example [NLTK](http://www.nltk.org/data.html).

I will now close this issue, feel free to reply if you have any questions and sorry for the delay on the resolution.
