### ISSUE TITLE
Provide default value to math.pow()

### ISSUE THREAD

**Issue by bhaskar-nair2** [pypa/warehouse#4117]
The basic math lib has-
`math.pow(x,y)`
But in practice, if a developer does not specify the value of y, can we not make it 2 by default, thus making the function
`math.pow(x,y=2)`

This is will make the function more convenient to use because if the developer has not specified a power inside a power function, then he probably was just squaring the value.  

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by ewdurbin** [comment]
Hi @bhaskar-nair2! this issue tracker is for issues relating to https://pypi.org.

Your issue appears to be related to the standard library's [`math.pow`](https://docs.python.org/3/library/math.html#math.pow) function.

If you'd like to file this issue with the Python language itself, https://bugs.python.org would be a better place for such a report.
