### ISSUE TITLE
font-weight 300 is too light to read

### ISSUE THREAD

**Issue by TitanSnow** [pypa/warehouse#4137]
https://github.com/pypa/warehouse/blob/e1f61c6bb1f84bd3ec35aed765765fc28caaf069/warehouse/static/sass/settings/_fonts.scss#L35
https://github.com/pypa/warehouse/blob/e1f61c6bb1f84bd3ec35aed765765fc28caaf069/warehouse/static/sass/settings/_fonts.scss#L17

The `$base-font-weight` is set to 300. For "Source Sans Pro", it means "Source Sans Pro ExtraLight", which is too light to read the text comfortably:
![screenshot](https://user-images.githubusercontent.com/19969470/41076319-96c8f2c0-6a43-11e8-986e-76f94fd47aa2.png)

This situation happens when webfont is not loaded properly, e.g. lose connection to fonts.googleapis.com

**Comment by nlhkabu** [comment]
hi @TitanSnow - thanks for reporting this.  As you have found the problem code, would you be able to make a PR changing the `300` value to `500`?  Does this solve the problem?

Thanks :)
