### ISSUE TITLE
Figure a user abstraction

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#414]
Right now we just return the ``User`` model anywhere we need to pass around a user object. Does this make sense? Do we need to support some sort of anonymous user or is ``None`` a good anonymous user?

**Comment by nlhkabu** [comment]
@dstufft - can you please check the milestone on this?  Is it required for launch?

**Comment by dstufft** [comment]
We can probably just close this out completely. It's unlikely we're going to need to replace ``User`` objects anytime soon.
