### ISSUE TITLE
Continued maintenance of abandoned project "rison"

### ISSUE THREAD

**Issue by betodealmeida** [pypa/warehouse#4140]
The [rison](https://pypi.org/project/rison/) package is a decoder for the Rison serialization format (similar to JSON, but optimized for URIs). It was last updated in 2010, the homepage and downloadable links are 404, and the author can't be reached through the listed email address. I actually was able to contact them through a different email address, and they told me (1) they no longer have access to the registered email nor (2) the password, and (3) were fine with me taking over the package

I currently maintain a Python encoder/decoder for Rison (https://github.com/betodealmeida/python-rison) which is published as [prison](https://pypi.org/project/prison/) in PyPI, but I would strongly prefer to use the name "rison".

My PyPI username is "roberto".

**Comment by betodealmeida** [comment]
@jamadden any update? Do you need anything from me?

**Comment by yeraydiazdiaz** [comment]
Hi @betodealmeida, apologies for the delay on processing this request.

I contacted the author and he confirmed he's happy to transfer the "rison" project to you, we will proceed to do so soon.

**Comment by di** [comment]
Done. Please note that you won't be able to make a release with the version `1.1` as this was previously used.
