### ISSUE TITLE
long_description broken when uploading wheel

### ISSUE THREAD

**Issue by Kautenja** [pypa/warehouse#4149]
**Describe the bug**

I'm seeing broken descriptions when releasing new wheels made with the latest version of wheel. I had been using twine to upload, but using `python setup.py bdist_wheel upload` produces the same problem. I can get the long description to render when I upload the raw source only (`python setup.py sdist upload`), but when I switch to uploading the wheel, the long description breaks. I've confirmed this issue with two separate projects so it seems easily reproducible.

**Expected behavior**

`python setup.py bdist_wheel upload` should upload the wheel and result in the long description being rendered on PyPi.org.

**To Reproduce**

1. create a new project with a `setup.py`:

```python
from setuptools import setup
setup(
    ...
    long_description='# Top Level Header',
    long_description_content_type='text/markdown',
    ...
)    
```

2. try to release using `python setup.py bdist_wheel upload` or `python setup.py bdist_wheel && twine upload dist/*`
3. observe that the project's page on PyPi is not rendering the markdown long_description

**My Platform**

| package    | version |
|:-----------|:--------|
| wheel         | 0.31.1    |
| setuptools | 39.0.1    |
| twine          | 1.11.0    |

**Comment by di** [comment]
@Kautenja Can you link to the projects with broken descriptions?

Twine should be working, but distutils (`python setup.py upload`) doesn't support Metadata 2.1, so if you want to use a Markdown description, you must use twine to upload.

**Comment by Kautenja** [comment]
Yes the projects are https://pypi.org/project/gym-tetris/ and https://pypi.org/project/gym-super-mario-bros/

Oddly, after revisiting the projects, it appears that the offending line is actually trying to upload _both_ source and wheel, causing the failure to render long_description:

```shell
python setup.py sdist bdist_wheel && twine upload dist/*
```

uploading _just_ the source or _just_ the wheel using either of the below commands works as expected with the long_description being rendered.

```shell
python setup.py bdist_wheel && twine upload dist/*
```

```shell
python setup.py sdist && twine upload dist/*
```

Perhaps uploading both the source and the wheel is simply not a supported feature?

**Comment by Kautenja** [comment]
After publishing a new release just now (`python setup.py bdist_wheel && twine upload dist/*`) for https://pypi.org/project/gym-tetris/, it appears rendering of `long_description` has randomly stopped working again.

**Comment by di** [comment]
@Kautenja The `.whl` distribution for `gym-tetris==1.2.0` was built with `wheel==0.30.0`.

```
$ unzip -c gym_tetris-1.2.0-py3-none-any.whl gym_tetris-1.2.0.dist-info/WHEEL | grep Generator
Generator: bdist_wheel (0.30.0)
```

You need to use `wheel>=0.31.0` here, versions before that do not support Metadata 2.1.

**Comment by Kautenja** [comment]
It seems that the issue has resolved itself. I can now upload both source and wheel without a hitch reliably. Perhaps the version of `wheel` was to blame all along. Closing this issue.
