### ISSUE TITLE
Use new Bitbucket logo

### ISSUE THREAD

**Issue by hugovk** [pypa/warehouse#4153]
**Describe the bug**
Atlassian updated their logos last September to be more abstract. The old Bitbucket logo is used for homepage links on PyPI.

**To Reproduce**
1. Visit a project whose homepage is on Bitbucket (eg. https://pypi.org/project/pager/)
2. Check the logo

**Actual behavior**

The logo is the old Bitbucket logo:

![image](https://user-images.githubusercontent.com/1324225/41216723-254fb0ca-6d5e-11e8-9630-153117e18ab8.png)

**Expected behavior**

The logo is the same as the current Bitbucket logo:

![image](https://user-images.githubusercontent.com/1324225/41216859-b11cff18-6d5e-11e8-93ea-04dd0b14a187.png)

**Additional context**
* https://www.atlassian.com/blog/announcements/our-bold-new-brand
* https://atlassian.design/guidelines/brand/logos
* https://atlassian.design/guidelines/marketing/resources/logo-files

**Comment by ewdurbin** [comment]
Looks like we need to update to a newer version of "Font Awesome" and we'll get an updated logo.

**Comment by ewdurbin** [comment]
Resolved.

**Comment by hugovk** [comment]
Thanks, confirmed updated.
