### ISSUE TITLE
Transfer of project bootstrapped

### ISSUE THREAD

**Issue by spencebeecher** [pypa/warehouse#4157]
bootstrapped is an open source project that I maintain on github: https://github.com/facebookincubator/bootstrapped/

Thomas Grainger did me a kindness and uploaded bootstrapped to pypi to make is more accessible for all. 

Now I am having trouble getting into contact with Thomas (I have sent a couple of emails) and I have some issues stacking up on the project (namely that it is broken on pypi): https://github.com/facebookincubator/bootstrapped/issues

I am cited as an author of the library but I would very much like to be able to uplaod new packages.

Thanks!

**Comment by di** [comment]
@graingert Are you able to transfer this project to @spencebeecher?

**Comment by spencebeecher** [comment]
Hi @graingert !!! it is: spencebeecher 

Thank you very much!
-Spencer

**Comment by spencebeecher** [comment]
@graingert - will you have a chance to look at this soon?

**Comment by graingert** [comment]
added

**Comment by ewdurbin** [comment]
confirmed.

**Comment by ewdurbin** [comment]
Depending on the intended outcome, I might suggest that @graingert elevate @spencebeecher from "Maintainer" to "Owner" of the project if the intent is a complete transfer of the project.
