### ISSUE TITLE
why I cannot manage my project on PYPI suddenly?

### ISSUE THREAD

**Issue by mingxiaoh** [pypa/warehouse#4163]
I can manage my project"ideep4py" this morning, but now I cannot manage it anymore, the "manage" button turns to "gray" on "https://pypi.org/manage/projects/". Besides, uploading a new file right after deleting an old file will always report "reuse name" issue. But if we wait for a long time(maybe one or two hours) to upload new file, it will work ok.

**Comment by di** [comment]
@mingxiaoh You have the "Maintainer" role for this project, which means that you can only upload releases for a package. It looks like your role was changed by the `Intel-MLT` owner on 2018-02-05 -- you should take this up with your team if that's incorrect.

With regards to uploading/deleting, please be aware that once a given file or filename has been uploaded to PyPI, it cannot be uploaded again, even after the original has been deleted. Instead, you'll need to create a new distribution with a different filename by changing the version.
