### ISSUE TITLE
classifer for Intel avx2 and Intel avx512

### ISSUE THREAD

**Issue by mingxiaoh** [pypa/warehouse#4165]
hello, we would like to differ instructions types, specifically, due to the fact that a package built on Intel avx2 cannot work on Intel avx512, and vice versa, so we need to upload different packages(one is for Intel avx2, another is for Intel avx512). Is it possible that you help add such a classifier? Thanks in advance.

**Comment by dstufft** [comment]
PyPI classifiers do not let you differentiate different files from each other, they are purely documentation for end users to be able to determine some information about packages, or to find packages related to a specific topic.

What you're looking for is to be able to upload wheels that are differentiated by CPU instructions, and that isn't currently able to be done. Adding that feature to the Python packaging tool chain will require a PEP and working with the [distutils-sig](https://mail.python.org/mm3/mailman3/lists/distutils-sig.python.org/) mailing list.
