### ISSUE TITLE
Redirect users to the login view when they don't have permission

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#417]
We need to configure Pyramid so that it will redirect users to the login view whenever they don't have permission to do something (maybe conditionally on if they are already logged in).

**Comment by ghickman** [comment]
I'll pick this one up.

**Comment by ghickman** [comment]
@dstufft – do we have a list of places that need redirecting?

**Comment by dstufft** [comment]
@ghickman no, but Pyramid has a built in method for this where you can tell it to do something like this for the forbidden view. I think it's a view decoratored like:

``@view_config(context=HTTPForbidden)``

which will cause that view to be used anytime a ``HTTPForbidden`` exception is raised.

**Comment by ghickman** [comment]
I've run out of time to get a patch out for this unfortunately. There's a working view in my [branch](https://github.com/ghickman/warehouse/tree/redirect-unauthed-users) but it's untested. If anyone else wants to pick up this issue then please feel free.
