### ISSUE TITLE
get a file size limit exemption or increase for our projects

### ISSUE THREAD

**Issue by mingxiaoh** [pypa/warehouse#4172]
Hello, would you please help increase the limit for our projects? Thanks in advance.
The name of the project: "ideep4py" and "ideep4py_avx2"
The size of your release, in megabytes: about 90MB per file.
Which index/indexes you need the increase for (PyPI, Test PyPI, or both): both

**Comment by di** [comment]
Hi @mingxiaoh, I've increased the limits for `ideep4py` and `ideep4py_avx2` to 100MB on both PyPI and TestPyPI.
