### ISSUE TITLE
File size limit increase for bagpipes

### ISSUE THREAD

**Issue by ACCarnall** [pypa/warehouse#4174]
I'd like to distribute a piece of astronomical software through PyPI, but it includes a large data table which is > 60MB, would it be possible to get the size limit for this project increased?

The name of the project: bagpipes
The size of your release, in megabytes: 210
Which index/indexes you need the increase for: PyPI

**Comment by di** [comment]
Hi @ACCarnall, I've increased the limit for `bagpipes` to 250MB on PyPI.

This is on the larger side as far as packages go, so please be mindful of how often you make a new release.
