### ISSUE TITLE
travis deployment succeeded but package doesn't show on pypi.org

### ISSUE THREAD

**Issue by cjw296** [pypa/warehouse#4177]
**Describe the bug**
My release job successfully deployed as per the [Travis deploy-to-pypi stuff](https://github.com/Simplistix/testfixtures/blob/master/.travis.yml#L57-L66):

https://travis-ci.org/Simplistix/testfixtures/jobs/392417795#L890-L896

**Expected behavior**

The testfixtures 6.2.0 relesae to show up here: https://pypi.org/project/testfixtures/

**To Reproduce**

See travis job output and config above.

**My Platform**

Travis

**Additional context**

This worked the last time I did a release of this package, which was on 6th June 2018.
If this is a Travis problem, pointers on what they need to fix would be very gratefully received.

**Comment by ewdurbin** [comment]
Logs for upload don't show any issues, but there's no record of the purge tasks being enqueued or executed. This appears to be a bug on the warehouse side for sure.

**Comment by ewdurbin** [comment]
@cjw296 I manually issued purge tasks and now the project page and simple index for testfixtures show your most recent releases.

we're going to have to investigate this a bit more closely. do you mind if I close this issue and open a new one in it's place that is more general?

**Comment by cjw296** [comment]
@ewdurbin - thanks for the amazingly quick response on this! As to what happens with this issue, I'm more than happy for you to tackle however you see fit; closing is fine, but if you just want to re-title and repurpose, that's all good too..
