### ISSUE TITLE
pbkdf2-ctypes missing from simple index

### ISSUE THREAD

**Issue by jaraco** [pypa/warehouse#4178]
The pbkdf2-ctypes package clearly has an [entry for 0.99.4](https://pypi.org/project/pbkdf2-ctypes/0.99.4/). And if one clicks on the Download link, it does lead to a downloadable file. But that latest version is mysteriously missing from [the simple index](https://pypi.org/simple/pbkdf2-ctypes/).

Why would that be? Can it be repaired?

**Comment by ewdurbin** [comment]
@jaraco there's no indication in the journal that a distribution was uploaded.

<img width="989" alt="screen shot 2018-06-14 at 4 52 18 pm" src="https://user-images.githubusercontent.com/1200832/41437763-5efb6e26-6ff3-11e8-88ab-a04b2f133dee.png">

**Comment by ewdurbin** [comment]
The download link is from the Metadata set on the release:

```
Download-URL: https://github.com/michele-comitini/pbkdf2_ctypes/archive/0.99.4.zip
```

**Comment by jaraco** [comment]
aah. Got it. Thanks. I'll go to the package to see if I can convince them to upload a release.
