### ISSUE TITLE
Purge tasks fail silently on upload

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#4183]
Investigating #4177, I noted the following symptoms:

- `purge_key` task for `project/{normalized_name}`, `user/{username}`, and `all-projects` purge keys did not appear in worker logs at all
- logs for upload pods showed no sign of error
- sentry showed no sign of error

Two uploads occurred near in time but neither had successful purge tasks, journals:

name | version | date | submitted_by | action
-- | -- | -- | -- | --
testfixtures | 6.2.0 | 2018-06-14 19:55:08.015725 | chrisw | add source file testfixtures-6.2.0.tar.gz
testfixtures | 6.2.0 | 2018-06-14 19:55:06.938226 | chrisw | add py2.py3 file testfixtures-6.2.0-py2.py3-none-any.whl
testfixtures | 6.2.0 | 2018-06-14 19:55:06.938226 | chrisw | new release

**Comment by ewdurbin** [comment]
Another case reported in https://github.com/pypa/warehouse/issues/3694#issuecomment-403189065 with the same symptom.

I believe this may be related to a memory leak in Celery that we see on occasion that is very similar in appearance to https://github.com/celery/celery/issues/4843.

From worker logs:

```
pypi-warehouse-worker-5d64dcc868-xqdmw worker [2018-07-07 17:40:06,066: WARNING/MainProcess] process with pid=7904 already exited
pypi-warehouse-worker-5d64dcc868-xqdmw worker [2018-07-07 17:40:06,072: ERROR/MainProcess] Process 'ForkPoolWorker-9862' pid:9926 exited with 'signal 9 (SIGKILL)'
pypi-warehouse-worker-5d64dcc868-xqdmw worker [2018-07-07 17:40:06,083: ERROR/MainProcess] Process 'ForkPoolWorker-9860' pid:9924 exited with 'signal 9 (SIGKILL)'
pypi-warehouse-worker-5d64dcc868-xqdmw worker [2018-07-07 17:40:09,830: WARNING/MainProcess] process with pid=9926 already exited
pypi-warehouse-worker-5d64dcc868-xqdmw worker [2018-07-07 17:40:09,832: WARNING/MainProcess] process with pid=5166 already exited
pypi-warehouse-worker-5d64dcc868-xqdmw worker [2018-07-07 17:40:09,832: WARNING/MainProcess] process with pid=8789 already exited
pypi-warehouse-worker-5d64dcc868-xqdmw worker [2018-07-07 17:40:09,833: ERROR/MainProcess] Process 'ForkPoolWorker-9865' pid:9929 exited with 'signal 9 (SIGKILL)'
pypi-warehouse-worker-5d64dcc868-xqdmw worker [2018-07-07 17:40:09,844: ERROR/MainProcess] Process 'ForkPoolWorker-9863' pid:9927 exited with 'signal 9 (SIGKILL)'
```

which indicates that as memory consumption rises in the `MainProcess`, recycling `ForkPoolWorker`s doesn't help and they keep getting slammed by the OOM killer.

**Comment by nlhkabu** [comment]
@ewdurbin is this something you or Dustin need to look at, or can we open it up to the community?  If so, can you please apply tags? Thx

**Comment by ewdurbin** [comment]
with #4421 we've migrated to a new broker for our async tasks and have not seen a worker memory leak in the last 24 hours since deploy.

![image](https://user-images.githubusercontent.com/1200832/43538826-174aa2a4-9591-11e8-82d3-ec56ee299972.png)

So we'll keep an eye on this issue and hope it is resolved!

**Comment by dstufft** [comment]
Going to close out the issue, the celery issue seems to be stabilized. If we get any more reports of failed purges we can re-evaluate then and re-open.
