### ISSUE TITLE
Claim package name 'orion' (squatting)

### ISSUE THREAD

**Issue by bouthilx** [pypa/warehouse#4189]
Name was claimed on Nov 10, 2010, yet there is no description nor any release. I believe this falls in the category "Invalid project" of [PEP-541](https://www.python.org/dev/peps/pep-0541/).

> - project is name squatting (package has no functionality or is empty);

I tried to contact the owner at the only address available on the PyPi package page, on Apr 20, May 8 and May 30 but did not get any answer back. The same user has other projects which were updated recently (May 10), namely [Ming](https://pypi.org/project/Ming/). This suggest the corresponding address  should still be valid during the period I tried to contact him. For what it is worth, this user seems to have a total of 5 squatting namespaces; [wiseguy](https://pypi.org/project/wiseguy/), [Orion](https://pypi.org/project/orion/), [Allura](https://pypi.org/project/allura/), [forge](https://pypi.org/project/forge/) and [pyrite](https://pypi.org/project/pyrite/).

Our project, [Oríon](https://github.com/mila-udem/orion/), is ready for a first beta release and we would appreciate very much if we could claim this squatted namespace.

**Comment by yeraydiazdiaz** [comment]
Hello @bouthilx, apologies for the delay in processing this request.

Could you confirm your PyPI username for the transfer, please?

**Comment by bouthilx** [comment]
:tada: !!! Awesome! :smile:
My username on PyPi is bouthilx: https://pypi.org/user/bouthilx/

**Comment by bouthilx** [comment]
@yeraydiazdiaz Do you have any idea when would the transfer take place?

**Comment by ewdurbin** [comment]
complete.

**Comment by bouthilx** [comment]
Thanks! :)
