### ISSUE TITLE
visuspy

### ISSUE THREAD

**Issue by scrgiorgio** [pypa/warehouse#4196]
I'm getting the following error (file-size policy limit):

HTTPError: 400 Client Error: File too large. Limit for project 'visuspy' is 60 MB. See https://pypi.org/help/#file-size-limit for url: https://upload.pypi.org/legacy/

could you increase this limit for visuspy project? I'm expecting file size to be <100MB

**Comment by di** [comment]
Hi @scrgiorgio, I'm not seeing any projects named `visuspy`. If this is the first time you're making a release, you'll need to make a throwaway release that's under the 60MB limit before we can increase the limit.

Also, could you give some background on the package and why it needs a larger distribution size?

**Comment by scrgiorgio** [comment]
Hi the project name is now openvisus. I'm pretty sure that for some
platforms it can reach 60+MB. Would it be possible to add it as an
exception for big Data project? Please look for visus/ Pascucci on the web
to understand what it will be inside... Thanks Giorgio scorzelli.

Il mer 4 lug 2018, 16:44 Dustin Ingram <notifications@github.com> ha
scritto:

**Comment by di** [comment]
This is a bit old and it seems like the `openvisus` project has been making releases without problems, so I'm going to close this, but feel free to reopen if this is still necessary.

**Comment by scrgiorgio** [comment]
if it was possible to increase the size to 100mb.
We had to remove some files from the pip in order to upload it.
Thanks.

**Comment by di** [comment]
Hi @scrgiorgio, I'm happy to do this if you can give me some details about what file this project needs to include that make it so large, and why.

You might also want to add a description to https://pypi.org/project/OpenVisus/, it's difficult for me to understand what this project is for.

**Comment by scrgiorgio** [comment]
Hi,

Visus is a very mature and complex project for exploring huge datasets.
We released it to open source just few months ago (we didn't have much time
to show off it since we are still in the bug-fixing phase).

Maybe this paper best describes what it does:
https://pdfs.semanticscholar.org/614b/68225a84e9d134eb37a925cf6917d6d35af5.pdf

The wheel is so huge because we use a mix of C++ and python.

We embed and extend python using the same libraries (which I think it's
pretty cool and innovative).

You can start Visus Viewer and run an embedded python interpreter 'inside'.
Python will help the viewer to transform data using for example OpenCV
and/or numpy.

Or you can run the python interpreter (in the usual/common way) and then
run from there the VisusViewer and 'drive' it using the SWIG automatically
generated API.

The wheels contains a lot of documentation, examples, scripts, sample
datasets etc.
And also the libraries are multiple and 'fat': from Kernel, to multi
dimensional viewing, to Dataflow, to Gpu computation etc.
Also for Windows we switch a lot from Release to Debug and we need to
distribute also the *.pdb (debug symbols).

That's the reason why the wheels are so big.
Thanks again for your help.
Giorgio.

Il giorno mer 12 set 2018 alle ore 18:37 Dustin Ingram <
notifications@github.com> ha scritto:

**Comment by di** [comment]
Thanks for the explanation. I've increased the limit for `openvisus` to 100MB on PyPI.
