### ISSUE TITLE
Request for File Size Limit Exemption or Increase for Tendenci

### ISSUE THREAD

**Issue by jennyq** [pypa/warehouse#4200]
Hi,

After added python 3 support to our project, we tried to distribute the .whl files along with the .tar.gz file, but encountered "HTTPError: 400 Client Error: File too large. Limit for project 'tendenci' is 60 MB.". Could you please increase the file size limit or exemption (if possible) for the Tendenci project? Thanks!

The name of the project: Tendenci https://github.com/tendenci/tendenci https://pypi.org/project/tendenci/
The size of our release, in megabytes: 71.2M
The Indexes we need the increase: both PyPI and Test PyPI

**Comment by di** [comment]
Hi @jennyq, I've set the limit for `tendenci` to 100MB for both PyPI and TestPyPI.
