### ISSUE TITLE
AttributeError: module 'eml_parser' has no attribute 'decode'

### ISSUE THREAD

**Issue by Beelal** [pypa/warehouse#4218]
import datetime
import json
import eml_parser

def json_serial(obj):
    if isinstance(obj, datetime.datetime):
        serial = obj.isoformat()
        return serial

with open('1.eml', 'rb') as fhdl:
    raw_email = fhdl.read()

parsed_eml = eml_parser.eml_parser.decode_email_b(raw_email)

print(json.dumps(parsed_eml, default=json_serial))

----------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-04d125c36cc6> in <module>()
     13     raw_email = fhdl.read()
     14 
---> 15 parsed_eml = eml_parser.eml_parser.decode_email_b(raw_email)
     16 
     17 print(json.dumps(parsed_eml, default=json_serial))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/eml_parser/eml_parser.py in decode_email_b(eml_file, include_raw_body, include_attachment_data, pconf, policy)
    320     msg = email.message_from_bytes(eml_file, policy=policy)
    321 
--> 322     return parse_email(msg, include_raw_body, include_attachment_data, pconf)
    323 
    324 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/eml_parser/eml_parser.py in parse_email(msg, include_raw_body, include_attachment_data, pconf)
    426     # parse and decode subject
    427     subject = msg.get('subject', '')
--> 428     headers_struc['subject'] = eml_parser.decode.decode_field(subject)
    429 
    430     # If parsing had problem... report it...

AttributeError: module 'eml_parser' has no attribute 'decode'

**Comment by di** [comment]
This is the repository for the code that powers https://pypi.org.

You should raise this on the issue tracker for the `eml-parser` project instead: https://github.com/GOVCERT-LU/eml_parser/issues

**Comment by Beelal** [comment]
Sorry posted accidentally here :-(
