### ISSUE TITLE
Enable users to modify their own account

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#423]
We need pages that allow users to modify their own account (email, password, etc).

**Comment by nlhkabu** [comment]
This is not going to be ready for launch, but should be one of the first items addressed after launch.

**Comment by nlhkabu** [comment]
- [ ] Update email
- [ ] Update password
- [ ] Update PGP ?
- [ ] Link OpenID to account 
- [ ] Delete Account

**Comment by nlhkabu** [comment]
Current design/layout:
![pypi-update-details](https://cloud.githubusercontent.com/assets/3323703/16544325/9c922e94-40f9-11e6-8d2d-7bbfd71777f2.png)

**Comment by gsb-eng** [comment]
@dstufft : Could you please confirm below points?
1. A user can have a single email registered with the current register feature, correct? (But, Schema has been designed to accommodate multiple emails)
2. The update email here is supposed to be updating primary email, correct?
3. How about adding additional security here, Verifying current password for any update?

**Comment by nkanaev** [comment]
what's the status of the ticket? @gsb-eng, are you working on this?

**Comment by gsb-eng** [comment]
@nkanaev Yes, I'm working on this.

**Comment by WhyNotHugo** [comment]
Not sure if this is the right place to ask: Given that account deletion is currently not implemented, how would one delete one's account? Is there some alternative channel where this can be requested? I've an old account (which even still has some co-ownerships!!) that I'd like to get rid of.

**Comment by brainwane** [comment]
In our [meeting today](https://wiki.python.org/psf/PackagingWG/2017-12-19-Warehouse) we decided this belongs in the first milestone, the MVP for package maintainers.

**Comment by di** [comment]
I broke this up as follows:
* Change public info: #2829 
* Change emails: #2830 
* Change password: #2831 
* Delete account: #2832 

PGP ids [have gone away in legacy](https://github.com/pypa/pypi-legacy/pull/762) and [we are not currently supporting federated auth](https://github.com/pypa/warehouse/issues/61).

**Comment by di** [comment]
@WhyNotHugo Sorry for the late reply: Account deletion still works for [legacy-pypi](https://pypi.python.org/pypi?%3Aaction=user_form), you should be able to delete your account there once you transfer ownership of any projects (or remove the projects entirely)
