### ISSUE TITLE
Enable pages to delete, hide, unhide a project/release/file

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#424]
We need UI that will allow users to modify the things they register and upload to Warehouse.

**Comment by nlhkabu** [comment]
current layout:

![pypi-upload](https://cloud.githubusercontent.com/assets/3323703/16544303/d6a69508-40f8-11e6-9cf7-375457770c1d.png)

**Comment by J08nY** [comment]
How is this not implemented yet, when the legacy API no longer allows editing releases?

> Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)

There currently seems to be no way to edit a project/release/file on PyPi.org. How was the old API allowed to be shut-down when the new one lacks significant functionality?

**Comment by brainwane** [comment]
In our [meeting today](https://wiki.python.org/psf/PackagingWG/2017-12-19-Warehouse) we discussed this issue and the larger question of release metadata immutability. Per @dstufft's [email to `distutils-sig`](https://mail.python.org/pipermail/distutils-sig/2017-December/031826.html) (reproduced in https://github.com/pypa/warehouse/issues/2170#issuecomment-352866597 ), we decided that we're going to narrow this issue to focus on the features we do want to implement:

* giving package managers a way to delete their own files, releases, and projects
* giving package maintainers a way to manage hidden vs unhidden releases

As I understand it, that set of features does belong in [the first milestone, the MVP for package maintainers](https://github.com/pypa/warehouse/milestone/8). @dstufft, @ewdurbin, @di and others, please correct me if I'm wrong.

**Comment by nlhkabu** [comment]
As per @dstufft's comment here - https://github.com/pypa/warehouse/issues/2734#issuecomment-355788559 - we can remove "giving package maintainers a way to manage hidden vs unhidden releases
" from this specification.
