### ISSUE TITLE
Issues with using on PC without Python

### ISSUE THREAD

**Issue by marobr001** [pypa/warehouse#4240]
Hi, I've recently made a simple drawing program, some basic GUI and I added few hotkeys based on this module function: add_hotkey(). As long as I'm running program on my primary PC (where I've got Python), it works perfectly. The problem beggins when I want it to use hotkeys on another PC (which hasn't got Python installed). I've "packed" the code into .exe application via pyinstaller module. When the program is started (on 2nd PC), it opens, it acts as it should, but when I press the hotkey, the program crashes, writting error: The program paint.exe has stopped working. Could you please help me resolve this issue?

**Comment by jamadden** [comment]
Thank you for your report, but unfortunately this is not the place for it. This tracker is only for the software that runs pypi.org itself. It cannot help with modules installed from there or with general Python questions. 

In a rough descending order based only on my guess about where you might find an answer, you might try targeting your question to the pyinstaller maintainers, or [python-list](https://mail.python.org/mailman/listinfo/python-list), or stackoverflow, or the [Python subreddit](https://www.reddit.com/r/Python/).
