### ISSUE TITLE
Claim Ownership of Open3D Package

### ISSUE THREAD

**Issue by takanokage** [pypa/warehouse#4243]
Describe the bug
This is a fake package.
I have contacted the author (Matthew Brett) of the Transforms3D code and he said he did not create the pypi package named Open3D. 
The actual name of the underlying library is Transforms3D.

User fizoo who created the Open3D package:
- https://pypi.org/user/fizoo/
- is name-squatting Open3D
- stole the identity of: Matthew Brett
- uses fake email address: fizoo@gmail.com
- has no commitment to improve the package; he's not the author of the code.

Home page is fake:
https://github.com/fizoo/transforms3d

To Reproduce
https://pypi.org/project/open3d/

Additional context
Following PEP-541 and trying to get maintainer control over the package.

My team and I have been developing Open3D for 3 years now and we're committed to improve it and maintain it for a long time.

**Comment by ewdurbin** [comment]
Hi @takanokage what PyPI usernames should this project be transferred to?

**Comment by takanokage** [comment]
The Open3D project should be transferred to https://pypi.org/user/Open3D/

Adding here German and Yixing who are currently responsible for this side
of the project.

Thank you and best regards,
Dan

**Comment by takanokage** [comment]
@yxlao, @germanros1987

**Comment by ewdurbin** [comment]
The Project has been transferred to the Open3D user. Please do not remove the existing release open3d==0.1.1.

**Comment by takanokage** [comment]
Thank you!

**Comment by yxlao** [comment]
@ewdurbin thank you!

**Comment by germanros1987** [comment]
Many thanks!
