### ISSUE TITLE
Exception "not well-formed (invalid token)" while retrieving data for release 0.8.0 of fuzzywuzzy package

### ISSUE THREAD

**Issue by AleBoi** [pypa/warehouse#4247]
I use an XML-based API to get the data about roughly 200+ libraries and their various versions. I constantly get the following error for version 0.8.0 of the fuzzywuzzy library:
ExpatError: not well-formed (invalid token): line 249, column 0

LOCALS

currrent_release = '0.8.0'
egg_name = 'fuzzywuzzy'
err = ExpatError('not well-formed (invalid token): line 249, column 0',)
firstRelease = ''
i = 13
release = '0.14.0'
release_data = {'maintainer': None, 'docs_url': None, 'project_url': [], 'maintainer_email': None, 'cheesecake_code_kwalitee_id': None, 'obsoletes_dist': [], 'keywords': None, 'package_url': 'htt
releases = ['0.1', '0.2', '0.3.0', '0.3.1', '0.3.2', '0.3.3', '0.4.0', '0.5.0', '0.6.0', '0.6.1', '0.6.2', '0.7.0', '0.8.0', '0.8.1', '0.8.2', '0.9.0', '0.10.0', '0.11.0', '0.11.1', '0.12.0',

Requests for all other versions and libraries work as expected.

Here is the data for the version 0.8.0:
>>> pprint.pprint(c.release_urls('fuzzywuzzy', '0.8.0'))
[{'comment_text': '',
  'digests': {'md5': '3aaf3ae602ed5e8bba4e30af881d2d1f',
              'sha256': '3845ecd7c790beae111a2d3956b4ba80fe1113eecf045c4b364394eaa01ad9ce'},
  'downloads': -1,
  'filename': 'fuzzywuzzy-0.8.0.tar.gz',
  'has_sig': False,
  'md5_digest': '3aaf3ae602ed5e8bba4e30af881d2d1f',
  'packagetype': 'sdist',
  'path': '7c/3d/914c9a03628a58edc4b34d154ce833e61fbfa01742c6d8b5f9c433121ddc/fuzzywuzzy-0.8.0.tar.gz',
  'python_version': 'source',
  'sha256_digest': '3845ecd7c790beae111a2d3956b4ba80fe1113eecf045c4b364394eaa01ad9ce',
  'size': 16684,
  'upload_time': '2015-11-16T07:04:03.752140Z',
  'url': 'https://files.pythonhosted.org/packages/7c/3d/914c9a03628a58edc4b34d154ce833e61fbfa01742c6d8b5f9c433121ddc/fuzzywuzzy-0.8.0.tar.gz'}]

Here is the data for the subsequent version 0.8.1:
pprint.pprint(c.release_urls('fuzzywuzzy', '0.8.1'))
[{'comment_text': '',
  'digests': {'md5': '423042f6f299409dceba4955e095fdf0',
              'sha256': '7d3d9242d89b77b2bfef63a4f95c3a4c9c512604f71749981e1182c4e3ccadd2'},
  'downloads': -1,
  'filename': 'fuzzywuzzy-0.8.1-py2-none-any.whl',
  'has_sig': False,
  'md5_digest': '423042f6f299409dceba4955e095fdf0',
  'packagetype': 'bdist_wheel',
  'path': '13/64/fc83a392a54f71ec27166766a2aceb9677e9621b5198a75c51a83b7da62e/fuzzywuzzy-0.8.1-py2-none-any.whl',
  'python_version': '2.7',
  'sha256_digest': '7d3d9242d89b77b2bfef63a4f95c3a4c9c512604f71749981e1182c4e3ccadd2',
  'size': 13939,
  'upload_time': '2016-01-25T17:15:53.692811Z',
  'url': 'https://files.pythonhosted.org/packages/13/64/fc83a392a54f71ec27166766a2aceb9677e9621b5198a75c51a83b7da62e/fuzzywuzzy-0.8.1-py2-none-any.whl'},
 {'comment_text': '',
  'digests': {'md5': 'eac7243ade8e4ed717b11291b70b9846',
              'sha256': 'd940bcf50b0046354fe0e9955389dd17b3771a22c5c62f92e99c449e6dc6aac6'},
  'downloads': -1,
  'filename': 'fuzzywuzzy-0.8.1.tar.gz',
  'has_sig': False,
  'md5_digest': 'eac7243ade8e4ed717b11291b70b9846',
  'packagetype': 'sdist',
  'path': '87/70/4dbdf522c6fd817c4cfdafc890cf2e25ce8f8d1006570b3a6efab0f522ad/fuzzywuzzy-0.8.1.tar.gz',
  'python_version': 'source',
  'sha256_digest': 'd940bcf50b0046354fe0e9955389dd17b3771a22c5c62f92e99c449e6dc6aac6',
  'size': 16739,
  'upload_time': '2016-01-25T17:15:35.488508Z',
  'url': 'https://files.pythonhosted.org/packages/87/70/4dbdf522c6fd817c4cfdafc890cf2e25ce8f8d1006570b3a6efab0f522ad/fuzzywuzzy-0.8.1.tar.gz'}]

I do not see any difference other than a missing section for a wheel distribution, which might be expected.

**Comment by ewdurbin** [comment]
Hello @AleBoi!

Can you provide code that will reproduce the error you're seeing? It's not clear what the steps to reproduce are, and I'm unable to detect any clear difference between the release metadata for the two versions used in your examples.

Also as an aside, the [JSON API](https://warehouse.readthedocs.io/api-reference/json/) is recommended over XMLRPC and provides nearly all of the same information as the `release_data` call.

**Comment by dstufft** [comment]
Closing this as it hasn't had a response in > 30 days. If you're still having issues, feel free to reopen or open a new issue. Thanks!
