### ISSUE TITLE
Classifiers UI?

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#425]
Determine if we need to support browsing by classifiers, and if so we need to implement that UI. We also need a page that lists all of the available classifiers.

**Comment by ryanhiebert** [comment]
I'm going to add a page that list the classifiers.

**Comment by ryanhiebert** [comment]
And I'm struggling with Pyramid. Going to run through some tutorials and read some more code. I'll let this go for now, but get it back when I've gotten through a Pyramid tutorial.

**Comment by nlhkabu** [comment]
Closing this as the new UI deals with it.
