### ISSUE TITLE
Lay down the start of an admin UI

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#426]
Warehouse needs an admin UI, badly. This should be something which is either automatic or simple to add new admin stuff to.

**Comment by karan** [comment]
What would be the purpose of this? Who would use it and for what?

**Comment by dstufft** [comment]
It would be for me (or any other PyPI administrator) so that instead of editing things by sshing into the database server and manually crafting SQL (which is error prone) there's a nice little GUI that can be used. It doesn't need to be amazing or anything, just something that can have workflows added to it for whatever things the admin has to do.

**Comment by karan** [comment]
> whatever things the admin has to do

Could you list some of those please?

**Comment by ismail-s** [comment]
#574 could be done on such a page.

**Comment by nlhkabu** [comment]
A couple of questions on this @dstufft  - 

1. Is this required for shut down?  Or can we move it to high priority post launch?
2. Can you provide me with a list of things you want to be able to do in the admin?

**Comment by dstufft** [comment]
It's not required for shut down, we don't currently have an admin UI, just a script we can run or manually mucking about in the DB. I've just woke up, but I'll get a list together.

**Comment by brainwane** [comment]
An admin UI here is meant for the administrators of the PyPI platform itself, correct? (As opposed to package maintainers who are uploading/modifying stuff related to their Python packages & listings.)

**Comment by dstufft** [comment]
@brainwane correct.

**Comment by ewdurbin** [comment]
We've been shipping admin features built up off of #1532!
