### ISSUE TITLE
Claim package 'dtrx'

### ISSUE THREAD

**Issue by ChrisJefferson** [pypa/warehouse#4279]
The package 'dtrx' provides a simple way of uncompressing a large number of compression formats, and deals with the common problems of spewing files in the current directory.

The package is still useful, but it has not been updated since 2011, so it required --allow-external.

I have tried emailing the author, Brett Smith, ( @brettcs ), but he seems unresponsive.

While I could add a new package with a different name, dtrx is mentioned in many webpages, and I know many people who use the existing name.

**Comment by jamadden** [comment]
This may qualify as an [abandoned project under PEP 541](https://www.python.org/dev/peps/pep-0541/#abandoned-projects).

**Comment by yeraydiazdiaz** [comment]
Hello @ChrisJefferson, apologies for the delay in tackling this issue.

I've emailed @brettcs to the email address set the project as well as his GitHub profile. Since it shows there's been some activity on his part in GitHub we would really appreciate it if he could clarify his position in regards to this project.

**Comment by ChrisJefferson** [comment]
I would also be interested if he replies. I can understand if dtrx isn't interesting enough for him to want to continue, but I, and many others, find it a practical and useful tool

**Comment by verhovsky** [comment]
I've been doing some (pretty superficial) work on my fork of the project, can I have it instead? https://github.com/verhovsky/dtrx

**Comment by yeraydiazdiaz** [comment]
@ChrisJefferson was the first one to claim it so the transfer, if successful, would be to him.

Under his ownership he can then choose to add more owners and contributors as he sees fit.

**Comment by ChrisJefferson** [comment]
(sorry for slow replies this week, I am on holiday)

I am very happy to have a group in charge - - my main interest is in seeing dtrx continue and be useful. I don't feel it needs major rewrites, but obviously there are always new compression systems, and obviously python 3.

**Comment by yeraydiazdiaz** [comment]
I've tried contacting the original author many times and he seems unresponsive, therefore the project can be considered abandoned.

@ChrisJefferson could you confirm your PyPI username for the onwership transfer, please?

**Comment by ChrisJefferson** [comment]
My PyPI username is also ChrisJefferson

**Comment by ewdurbin** [comment]
Transfer complete.
