### ISSUE TITLE
Claim Ownership of jenkins and jenkins-python packages

### ISSUE THREAD

**Issue by ssbarnea** [pypa/warehouse#4294]
There are two packages published on pypi which are not maintained and are likely to create confusions for users of python-jenkins library. 

Original project: https://pypi.org/project/python-jenkins/ -- installs "jenkins" module.
Project one: https://pypi.org/project/jenkins/ installs "jenkins" module which is a 15 line checksum library, clearly not something used in real life. Source at https://github.com/lgastako/jenkins/ -- **last release 9 years ago**
Project two: https://pypi.org/project/jenkins-python/ with source at https://github.com/armata/jenkins-python, **last release 2 years ago.**

If current owners of these projects are still interested in keeping a package published on pypi, they could easily rename their package to make it clear, probably naming it "jenkins_hash" or something similar that would not confuse users or overlap the namespaces.

Once this is done, these should be transformed into aliases so any of the next 3 operations will have the same result:

```
pip install python-jenkins
pip install jenkins
pip install jenkins-python
```

@lgastako @armata

**Comment by di** [comment]
It's not possible to rename a package on PyPI, but if you want to try and take over these projects and make new (proper) releases, it looks like they would qualify as an "abandoned" projects under PEP 541.

First step would be to reach out to the owner/maintainer to see if they would be willing to transfer without PyPI admins needing to intervene.

**Comment by ssbarnea** [comment]
Both maintainers awere contacted, one back in April and another one yesterday. There are linked tickets to their trackers (both are on github). 

When I said about rename I ment re-publish under a new name and transfer ownership of the old one. 

I remeber that pypi used to support aliases for package name but if this is no longer supported we can transform them into “forward” packages, empty ones that only list the correct one in their requirements. I think I used this trick once in the past.

**Comment by ssbarnea** [comment]
@di Can we do someting about this? I never got any kind of reply from the current owner of the jenkins namespace.

**Comment by di** [comment]
@ssbarnea It looks like the owner of `jenkins-python` complied with your request. Have you reached out to the current owners of the `python-jenkins` project to confirm that this is actually something they want?

**Comment by zxiiro** [comment]
@di Yes, we are the python-jenkins maintainers and this is something we want. Thanks!

**Comment by di** [comment]
@zxiiro You don't appear to be one of the project owners, can you get one of the people listed to respond? https://pypi.org/project/python-jenkins/

**Comment by zxiiro** [comment]
@di I asked the OpenStack Foundation to add me explicitly to the python-jenkins pypi page. Is this enough to prove that I am a maintainer of this project?

**Comment by fungi** [comment]
To be clear, it's the sysadmins in the OpenDev community, not the OSF staff (though I happen to wear both hats at different times).

**Comment by di** [comment]
Thanks, I've added `javacruft` and `zxiiro` as owners of the `jenkins` project. I believe this issue should now be resolved?

**Comment by zxiiro** [comment]
Yes thank you.

**Comment by ssbarnea** [comment]
@zxiiro While from PyPA point of view the issue was sorted, we stil need to start publishing wheels under jenkins name. This also makes me think that maybe it is the time to to move jenkins packages (jenkins+jjb) out of openstack and to github repos, as this could make maintenance much easier for people without gerrit/zuul experience.

**Comment by di** [comment]
Please take this discussion elsewhere, thanks!
