### ISSUE TITLE
more space for project needed

### ISSUE THREAD

**Issue by ttinies** [pypa/warehouse#4300]
pypi username: versentiedge
The name of the project: sc2maptool (version 1.0.6)
The size of your release, in megabytes: 70MB
Which index/indexes need the increase: PyPI only

This project is directed toward AI research toward mastering Starcraft 2.  The repository is expected to grow ~5MB every three months, but is not ever expected to overrun 100MB.

**Comment by di** [comment]
I've increased the limit for `sc2maptool` to 100MB on PyPI.

**Comment by ttinies** [comment]
thanks!
