### ISSUE TITLE
File size limit exemption request

### ISSUE THREAD

**Issue by jlcontreras** [pypa/warehouse#4306]
Hi, I am trying to upload a new version of my project and have run into the 60MB file size limit. The details of my project are the following:

Project name: mxnet-jetson
Release size: 73.5MB (next releases may need some additional space)
Index: PyPI

Thank you!

**Comment by di** [comment]
Hi @jlcontreras, can you give some detail about this package and why it needs the additional space?

**Comment by jlcontreras** [comment]
Hi Dustin, 

The package is a Jetson specific build of Apache's MXNet deep learning framework. It needs some additional space so it can be compatible with both JetsonTX1 and JetsonTX2.

(I modified the package name to mxnet-jetson instead of money-jetson-tx2, as it makes more sense with the above)

Let me know if you need additional info, thanks!

**Comment by di** [comment]
@jlcontreras I've increased the limit for `mxnet-jetson` to 100MB.
