### ISSUE TITLE
add further troubleshooting instructions for dev environment

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#4309]
https://warehouse.readthedocs.io/development/getting-started/#troubleshooting should include:

* If you run `make tests` and get: `psycopg2.ProgrammingError: database "tests" already exists` , that can happen when the tests are running and abruptly killed in such a way that it doesn’t have time to clean up the test databases; a `make initdb` should fix it.

* If you run `make tests` and get warnings like this:

~~~
tests/unit/packaging/test_services.py::TestLocalFileStorage::()::test_basic_init
  /opt/warehouse/src/warehouse/packaging/services.py:35: RuntimeWarning: LocalFileStorage is intended only for use in development, you should not use it in production due to the lack of safe guards for safely locating files on disk.
     RuntimeWarning,
~~~

`LocalFileStorage` warnings are expected (though it'd be nice if we found some way to supress those in tests scenarios), and you might be able to `make purge` to reset everything and try again.

* If `make purge` fails with a permission error, check ownership and permissions on `warehouse/static`. `docker-compose` is spawning containers with docker. Generally on Linux that process is running as root. so when it writes files back to the file system as the static container does those are owned by root. So your docker daemon would be running as root, so your user  doesn't have permission to remove the files written by the containers.   `sudo make purge` will work.

* If `make initdb` fails with a timeout like `urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x8beca733c3c8>, 'Connection to elasticsearch timed out. (connect timeout=30)')`, you might need to increase the amount of memory allocated to docker, since elasticsearch wants a lot of memory (Dustin gives warehouse ~4GB locally). (Let's point to an explanation of how to do that.)

**Comment by ewdurbin** [comment]
the note on `LocalFileStorage` is disjoint from the guidance on `make purge`

The second bullet point is probably better specified as:

* If you run make tests and get warnings like this:

```
tests/unit/packaging/test_services.py::TestLocalFileStorage::()::test_basic_init
  /opt/warehouse/src/warehouse/packaging/services.py:35: RuntimeWarning: LocalFileStorage is intended only for use in development, you should not use it in production due to the lack of safe guards for safely locating files on disk.
     RuntimeWarning,
```

`LocalDocsStorage` and `LocalFileStorage` warnings are expected (though it'd be nice if we found some way to supress those in tests scenarios).

**Comment by di** [comment]
We could just remove them: https://github.com/pypa/warehouse/blob/c3a2393481ab0aa461486664a2ab3137c0bd5e0b/warehouse/packaging/services.py#L27-L36

I don't think we're going to accidentally configure PyPI/TestPyPI to use local file storage.

**Comment by asfaltboy** [comment]
@nlhkabu I can take on this ticket

**Comment by nlhkabu** [comment]
Great!  I've assigned to myself (as I can't assign to you), but consider it reserved :)

**Comment by di** [comment]
The warning message during testing was fixed in https://github.com/pypa/warehouse/pull/4360.
