### ISSUE TITLE
PEP 470 or Offsite Hosting

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#431]
We need to get PEP 470 approved and implemented, or we need to add the offsite hosting links to ``/simple/`` as well as the ability to register URLs in the web UI.

**Comment by dstufft** [comment]
Today, PEP 470 was accepted ([d7cc3a1e7c9f](https://hg.python.org/peps/rev/d7cc3a1e7c9f)) and we'll use the migration from PyPI legacy to Warehouse to implement the very last part of that PEP, which is the ultimate removal of links that aren't hosted on PyPI from the ``/simple/`` pages. Given that, there is no pending issues here for offsite hosting other than the changes we need to make on PyPI legacy to handle the transition.

**Comment by ewdurbin** [comment]
`its_happening.gif`

**Comment by dstufft** [comment]
![qpabq5x](https://cloud.githubusercontent.com/assets/145979/9648492/4ad505f4-51b7-11e5-9107-2980aa6d6868.gif)

**Comment by ewdurbin** [comment]
^ that one
