### ISSUE TITLE
Add rate limiting to the XMLRPC Api

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#4321]
Currently whenever we get a big burst of XMLRPC requests, our service can start timing out and raising 5xx errors. We should introduce rate limiting in the XMLRPC API in order to force clients to slow their roll and not hammer us too hard.

**Comment by waseem18** [comment]
@dstufft I previously worked with API rate limiters and would like to take this up.

**Comment by di** [comment]
Added in #4553.

**Comment by pradyunsg** [comment]
Can we increase this limit a little bit?

pip's test suite hits this limit in CI, which has broken all our CI pipelines and is blocking all PR merges. :(

/cc @ewdurbin @brainwane

**Comment by di** [comment]
@pradyunsg We recently reduced the limit because the API was being abused and exhausting PyPI's backend resources.

The current limit is 2 per second / 30 per minute, so depending on how pip uses the XML-RPC APIs, you could add a delay to the affected tests.

**Comment by pradyunsg** [comment]
Coolieo. https://github.com/pypa/pip/pull/9051 should make it possible to work around those.

FWIW, I'm a +1 on giving a farewell to the `search` endpoint.
