### ISSUE TITLE
Deprecate & Remove X-PyPI-Last-Serial on File Responses

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#433]
Ideally we'd like to not serve the file responses via the Warehouse web application, however we currently need to do this in order to add the ``X-PyPI-Last-Serial`` responses. Bandersnatch is currently using this, so it would be great to investigate what it's being used for and if we can safely deprecate and remove it.

**Comment by r1chardj0n3s** [comment]
This isn't just *used by* Bandersnatch, it was added specifically *for*
Bandersnatch :)

**Comment by dstufft** [comment]
Yea, I just wasn't sure if anyone else was using it or not.

**Comment by dstufft** [comment]
Ok, I've talked to @ctheune and Bandersnatch is going to remove the need for this. Changes to PyPI (disallowing delete + reupload as a general case) remove the primary need for this since the contents located at a file URL are likely never going to change except to possibly be deleted.

**Comment by dralley** [comment]
@dstufft This also needs to be removed from the documentation

https://github.com/pypa/warehouse/blob/69869dbd993b447822496034a72ec211289b9b6c/docs/api-reference/legacy.rst
