### ISSUE TITLE
blocking raven-js breaks JS

### ISSUE THREAD

**Issue by wm75** [pypa/warehouse#4336]
- Tested under Fedora with a variety of browsers (Firefox, Vivaldi, Falkon) and under macOS with Safari -

In the `Download files` section of pypi packages you are supposed to have access to the sha256 sum of any downloadable file. However, while there is a corresponding element `SHA256` that says `Copy to Clipboard` when you hover over it, the actual sum is not displayed nor does the advertised copying work. Instead, the only way to get the sha256 sum is through inspecting the element with your web browser's document inspector, which reveals, for example, sth like this:

```
<a class="-js-copy-hash table__sha256-link tooltipped tooltipped-s" aria-label="Copy to clipboard" data-original-label="Copy to clipboard" data-clipboard-text="28f231ea66ad7cb7b901eb60fc5ab8e7cbe637df7792ed4953f6a44b253fee7f">
                      <i class="fa fa-copy" aria-hidden="true"></i>
                      <span class="sr-only">Copy SHA256 hash</span>
                      SHA256
                    </a>
```

My expectation would be that clicking on the SHA256 element brings up a text box-like element with the checksum and either copies it to the clipboard directly or has a button allowing me to do this.

**Comment by wm75** [comment]
Thanks @di for testing. I'm not blocking JavaScript, but you put me on the right track. I was trying this at work and it turns out that our DNS server had cdn.ravenjs.com blacklisted, which you seem to be relying on to pull in the raven-js library. Removing the domain from the blacklist solved the problem :+1:

**Comment by wm75** [comment]
One suggestion though: the sha256 functionality would be a lot more convenient to use if the checksum was displayed in addition to just being copied to the clipboard. I'm thinking of something along the lines of github projects' `Clone or download` button that would first reveal the checksum in a small pop-up element, then lets you copy to the clipboard from there.

**Comment by di** [comment]
Hmm, I'm a little confused how that script (which we use for frontend crash analytics) would prevent the rest of our JS from working. Might be worth looking into more.

I'll let @nlhkabu chime in with thoughts about making the hash visible as well as copy-able.

**Comment by nlhkabu** [comment]
Hi @wm75, thanks for opening this ticket :)

We've had other feedback that it might be useful to display checksums without the need for JS (see https://github.com/pypa/warehouse/issues/3828) so it's already on the 'to look into list.'

Given we have an existing issue, I'm going to rename this to reflect the raven-js problem you experienced.

**Comment by yeraydiazdiaz** [comment]
The [base template includes the Raven script](https://github.com/pypa/warehouse/blob/master/warehouse/templates/base.html#L102-L106) which is then [loaded on index.js](https://github.com/pypa/warehouse/blob/master/warehouse/static/js/warehouse/index.js#L48-L54) and crashes if unavailable. Should be a straight-forward fix.
