### ISSUE TITLE
PyPI Removes First Line When Installing

### ISSUE THREAD

**Issue by Stunner** [pypa/warehouse#4338]
**Describe the bug**
The sha-bang line: `#!/usr/bin/env python` is removed from my Python script when installed from test.pypi.org. This breaks my script and prevents it from being run from the shell.

**Expected behavior**
Expect my entire script to remain unmodified so that it works properly.

**To Reproduce**
I put together a video showing this entire process (cut and slightly sped up for brevity): https://youtu.be/YyRH1oXDqHE

**My Platform**
Initially encountered in macOS 10.12.6.
Recording done within macOS Mojave beta 2.

**Additional context**
The repository I am trying to upload is available from here: https://github.com/Stunner/findmissing
I have not committed the setup.py file as I was waiting to upload it to PyPI before doing so, but if you think it would help with diagnosing the issue just let me know and I can push the commit.

**Comment by jamadden** [comment]
PyPI has nothing to do with installing a distribution. You probably want pip or setuptools. You should probably use a [setuptools console entry point](
http://python-packaging.readthedocs.io/en/latest/command-line-scripts.htm) to create scripts for you n

**Comment by Stunner** [comment]
That link you provided is broken. Could you fix it please @jamadden ?

**Comment by jamadden** [comment]
The final 'l' was missing from '.html'; fixed. There's also [setuptools own documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation)
