### ISSUE TITLE
Markdown doesn't rendered correctly even set long_description_content_type

### ISSUE THREAD

**Issue by hsiaoyi0504** [pypa/warehouse#4341]
My project at PyPI: https://pypi.org/project/gff3tool/1.4.2

Libraries used:
```
wheel==0.31.1
setuptools==39.1.0
twine==1.11.0
```

**Comment by hsiaoyi0504** [comment]
Same files can be correctly used under following tools and versions (linux).
```
wheel (0.31.1)
setuptools (40.0.0)
twine (1.11.0)
```

**Comment by hsiaoyi0504** [comment]
@di You are right. I use Windows build that. I will report to setuptools and report the update back.

**Comment by di** [comment]
@hsiaoyi0504 Great, I'm going to close this issue in the meantime since there's not much Warehouse can do here, but feel free to comment if there's any other way we can help.

**Comment by di** [comment]
@youreccentricity You have a bug in your `setup.py` file, you're not returning anything from this function: https://github.com/youreccentricity/colorlicious/blob/7408519ab5803213b67b6dfe0a6b22777608101b/setup.py#L42-L44
