### ISSUE TITLE
prospective question about using Pypi behind complicated comms

### ISSUE THREAD

**Issue by caliloo** [pypa/warehouse#4347]
Hi, 

I've spent most of my professional life working at the "wrong end" (in the network sense, it was the right end in terms of life interests :) ) of high latency, high loss, high jitter sat com links (but not necessarily low bandwidth). Sometimes for long missions. or even reaaally long ones (years). It means that pyPI is often mostly unusable for me, and I've had to resort to other ways to install and deploy python packages.

In a more general sense, to access pyPI, the dimensions of the bad comms problem that you have to consider in order to solve it are mostly : 
* compute power at the remote end
* bandwidth between the sites
* latency between the sites

I'm interested in doing some prospective work on what it would take to solve this problem (in my usual remote setting first, and then perhaps in a more general sense by exploring a bit the dimensions outlined). To this end, I'm curious as to how I can access metrics of pypi (size of the "repo", number of uploads and updates /day/hr, etc... And how I can access a detailed technical description of the architecture of Pypi.

Thanks in advance !
Charles

**Comment by brainwane** [comment]
@caliloo Thanks for being interested in doing this work! Does https://warehouse.readthedocs.io/application/ help (regarding the architecture)? (Please also see #2794 for some more on this.)

**Comment by pradyunsg** [comment]
There's also a public dashboard for PyPI at https://p.datadoghq.com/sb/7dc8b3250-85dcf667bd which contains the information such as the size of the repo, traffic statistics and so on.

**Comment by brainwane** [comment]
@caliloo I'm checking in -- do the existing dashboard and architecture documentation help?

**Comment by caliloo** [comment]
Thanks for checking in !
The existing dashboard tells me that the repo is 4.65 TB, and not growing too fast, so there is probably a lot of feasibility in doing a daily dump or some such thing to feed a local pypi. I have to admit I didn't go much farther because of other fun that has cropped up (fartherhood earlier than planned) :) But it hasn't left my todolist...

Next for me would be to understand the ins and outs of module distribution to the public in terms of compiled/not compiled stuff.
And read the architecture doc to grok what happens behind the scene at pypi with versioning, storage (and versioning+storage eventual interrelations), eventual precompilations, and publications.
These is something I'm pretty sure I dont know yet about how modules are distributed by pypi when they carry parts in C or as binary objects (is that even possible), in relation to the requester's arch (i386/arm/ etc...).

Actually, I might just put a module of mine on pypi to understand this better.
So to answer directly,  yes the dashboard helps a little, and let me see about the arch doc :)

**Comment by caliloo** [comment]
btw, I'm fine with closing this issue, if you're in a housekeeping spree.
