### ISSUE TITLE
Trove Classifier Request: Typing

### ISSUE THREAD

**Issue by tailhook** [pypa/warehouse#4348]
Request to add a new Trove classifier.

## The name of the classifier you would like to add
Something like this:

* `Programming Language :: Python :: Typing`

But I'm sure this isn't perfect name, so I'm open to bikeshedding.

## Why do you want to add this classifier?

This should show, that source code either covered by type annotations, or has a `.pyi` files that accompany sources. Also package should include `py.typed` file as far as I understand.

**Comment by ewdurbin** [comment]
highlighting a selection of top contributors from the typing module itself to solicit opinions on this classifier name, thought it seems reasonable to me.

@gvanrossum @ilevkivskyi @ambv @vlasovskikh

**Comment by gvanrossum** [comment]
- I'm not sure how we would spread the word that people should add this classifier.
- I'd name it "Typed" rather than "Typing".

**Comment by tailhook** [comment]
> I'm not sure how we would spread the word that people should add this classifier.

Looks like this: http://py3readiness.org/ was a great idea, and may be repeated.

> I'd name it "Typed" rather than "Typing".

When searching a list I was looking for `mypy` and `typing` not sure if I would find Typed. Anyway, may be full name like this would be nice:

* ``Typing :: Typed``

Another thought, we may want to distinguish type bindings using `.pyi` and fully typechecked modules. But I'm not sure if it makes sense.

**Comment by gvanrossum** [comment]
"Typing :: Typed" is fine.

Distinguishing between the two approaches seems overkill, and in fact it's
totally fine to use a mixture (or use .pyi files to cover extension modules
but inline annotations for the rest).

**Comment by asvetlov** [comment]
In aiohttp we have both stubs and inline annotations

**Comment by ilevkivskyi** [comment]
FWIW I am equally fine with both `Typing` and `Typed`.

**Comment by dstufft** [comment]
Just to clarify, y'all would like: ``Programming Language :: Python :: Typing :: Typed`` as your classifier?

**Comment by tailhook** [comment]
I expected bare `Typing :: Typed`.

**Comment by asvetlov** [comment]
`Programming Language :: Python` makes sense for me

**Comment by ambv** [comment]
There's no precedent in specifying features of the language used in a project by classifiers under "Programming Language :: Python". I think what we're after here is closer to what "Framework ::" is doing. Thus, I would like to see a bare "Typing :: Typed".

**Comment by ethanhs** [comment]
I agree with @ambv, I think the bare "Typing::Typed" spelling makes sense.

**Comment by ewdurbin** [comment]
`Typing :: Typed` has been added on pypi.org and test.pypi.org

happy annotating!

**Comment by ilevkivskyi** [comment]
Great, thanks!
