### ISSUE TITLE
Link to infrastructure dashboard from footer

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#4349]
We have a (really cool!) DataDog dashboard that shows information about the infrastructure powering PyPI.  It would be great to link to this from our footer.

Proposal:

- Add link to `https://p.datadoghq.com/sb/7dc8b3250-85dcf667bd` under the 'About us' title in the footer
- The link should be placed in the second position (under the status link)
- The link should have the title 'Infrastructure dashboard'

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: Please include a screenshot of your update. This helps our team give you feedback faster.

**Comment by ewdurbin** [comment]
Alternative chortling that is a little less ugly. `https://dtdg.co/pypi`

**Comment by Sparkycz** [comment]
![Uploading add_link_infrastructure-dashboard.png…](screenshot of the solution)
