### ISSUE TITLE
Randomly receiving TCP RST on TCP handshake every now and than.

### ISSUE THREAD

**Issue by snarlistic** [pypa/warehouse#4355]
Ever since the afternoon(CEST) of Tuesday July 24th we are randomly receiving TCP RST's on our TCP handshakes every now and than. Not all the time and not always the same IP. Please find attached some anonymised tcpdump data.

[fail_151.101.64.223.txt](https://github.com/pypa/warehouse/files/2236596/fail_151.101.64.223.txt)
[fail_151.101.128.223.txt](https://github.com/pypa/warehouse/files/2236597/fail_151.101.128.223.txt)
[good_151.101.64.223.txt](https://github.com/pypa/warehouse/files/2236598/good_151.101.64.223.txt)

**Comment by ewdurbin** [comment]
@snarlistic can you please provide diagnostics per the issue template for Network Access Issues? 

https://github.com/pypa/warehouse/issues/new?template=access-issues.md

Are these errors when pip installing?

**Comment by snarlistic** [comment]
Please accept my apologies. I used the form, but left out what I thought was not important. And after reconsidering the template I still feel all the needed information is in the tcpdump data files. Please correct me if I'm wrong.

This happens when I run the following command: /usr/bin/pip install -q --upgrade <package name>, actually Puppet is running it for me automatically.

**Comment by ewdurbin** [comment]
do you have any of the log output from the pip command?

At the very least, this appears to be something we'd be escalating to our CDN provider so the Fastly-Debug information would be helpful

```
### Fastly Debug
    Note that this output is optional, as it encodes identifying information
    about your browser, public IP, and location.

    We'll remove this output from the issue before closing, but do not feel
    comfortable making it required for all users.

    If you have a browser that reproduces your access issue, go to
    https://fastly-debug.com, when the page has loaded copy and paste the
    base64 encoded blob at the top of the page into the box below, and
    uncomment this section.

    Note that you may need to disable ad-blockers and privacy protection
    extensions in order for this page to operate, as it makes numerous calls
    to servers on our CDN's network that look concerning to those tools.
```

If you'd like to transmit that privately, you can email it to ernest@python.org and optionally encrypt it with my GPG public key `22ADAE0FC41E160AD1596B118F8E423168928420`

**Comment by snarlistic** [comment]
I've sent you an email with the requested data attached. Hope this helps you explain the problem to Fastly or solve it yourself.

Please do note I expect most people will not experience this problem, since I expect them not to use this old version (9.0.1) of pip that features a broken retry mechanism, that we unfortunately do use. We could, and I think should, use a new version of pip, but this would only mask the real problem.

**Comment by snarlistic** [comment]
Please close the ticket at your CDN provider, since we managed to solve this issue with our cloud provider.

As the next document describes, Fastly uses anycast for some of its services: [https://www.fastly.com/blog/building-and-scaling-fastly-network-part-2-balancing-requests]
Our cloud provider had some trouble with a certain route that suffered packet loss and this caused packets to use different routes to Fastly, causing the packets of one TCP-session to arrive at different end points. The end point that had not yet seen the SYN packet of course returned a RST packet when it received packets of a connection it did not know anything about.

So please accept my apologies for opening this issue with you. Hopefully this issue will help others when they experience similar problems.

**Comment by di** [comment]
Glad you got that resolved @snarlistic! Going to close this issue.
