### ISSUE TITLE
Check licence in files

### ISSUE THREAD

**Issue by stanl3y** [pypa/warehouse#4389]
We should check licences in the following files:

```
./blocks/_tooltip.scss 
./settings/_neat.scss
./tools/bourbon/*
./tools/neat/*
./resets/_reset.scss
./resets/_boxsizing.scss
./resets/_normalize.scss
```

**Comment by evemorgen** [comment]
will do, here is a PR: #4399

**Comment by evemorgen** [comment]
I belive we can mark this issue with `Europython-2018-sprint` label

**Comment by evemorgen** [comment]
Since #4399 has been merged, I think this one can be closed

**Comment by ewdurbin** [comment]
thank you @evemorgen
