### ISSUE TITLE
steamline test pypi usage after prune/on new use wrt credential setup and mail verification

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/warehouse#4393]
## scenario

i wanted to test some changes for setuptools_scm on test_pypi - so i ran the travis deploy against it,
the first item i ran into the need to create a new distinct user, which then needs to be verified

## what should have happened

* ideally testpypi would have inherited my credentials from pypi and/or just created a dummy/accept any/the first password user
* still nice would have been the drop of the email verification requirement

an awesome perk would be expected/regular pruning on top of that

**Comment by di** [comment]
Thanks for the feature request @RonnyPfannschmidt! 

Our long term plans are to eliminate TestPyPI entirely (see https://github.com/pypa/warehouse/issues/726) so we won't be adding anything that further differentiates TestPyPI's behavior from PyPI.

In the meantime, we also want to keep PyPI and TestPyPI's datastores totally insulated from each other, so while I agree that it is painful to have to create and maintain two accounts, we don't plan to change that as long as TestPyPI is around.

Given that, I'm going to close this PR, but thanks again for raising this and hopefully https://github.com/pypa/warehouse/issues/726 eventually resolves this friction for you.
