### ISSUE TITLE
bpy Package file size limit increase

### ISSUE THREAD

**Issue by TylerGubala** [pypa/warehouse#4395]
Hello,

I am the maintainer of a Python module called 'bpy', which is a Python interface into the Blender 3d application.

Because the module requires large binaries to be built, the resulting bdist_wheel (which is, in my opinion, the best option for distributing built binary distributions of packages such as this) is > 66.2MB, which goes over the 60MB upload limit, resulting in this error:

```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading bpy-1.2.2a23-cp36-cp36m-win_amd64.whl
100%|█████████████| 66.2M/66.2M [00:26<00:00, 2.58MB/s]
HTTPError: 400 Client Error: File too large. Limit for project 'bpy' is 60 MB. See https://pypi.org/help/#file-size-limit for url: https://upload.pypi.org/legacy/
```

I believe I placed my issue originally in the wrong place, as I found this issue and thought that my issue should be placed under pypa/packaging-problems

https://github.com/pypa/packaging-problems/issues/86

When really the recommendation based on 

https://pypi.org/help/#file-size-limit

Says to post the issue here.

Being able to upload this bdist_wheel will, I believe be able to allow me to close out several issues on the project, so many thanks in advance if the size limit can be increased!

**Comment by di** [comment]
I've set the upload limit to 100MB for `bpy` on PyPI.
