### ISSUE TITLE
Create demo project for code highlighting styles

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#4400]
Yesterday, we did some work to improve the code highlighting (see https://github.com/pypa/warehouse/issues/4047). 

I'd like to continue to improve our code highlighting theme.

It would be great to upload a 'code-highlighting-demo' project to PyPI that we could use for testing code highlighting.  It would need to show as many colors as possible in the readme.

We could then add a section in the documentation that explains how the code highlighting works, and where to find this demo project.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**:  please include a screenshot of your update. This helps our team give you feedback faster.

**Comment by nlhkabu** [comment]
Related to #3939

**Comment by evemorgen** [comment]
I'm willing to take this one, good to go?

**Comment by nlhkabu** [comment]
Yes, great @evemorgen :)

**Comment by evemorgen** [comment]
Two quick questions:
  * I guess there should be separate repo in pypa for that?
  * I cannot make up my mind whether it should be one big chunk of code or reasonable number of smaller ones that shows different stuff. Any suggestions?

**Comment by nlhkabu** [comment]
The other demo project we have is a private project (see https://pypi.org/project/markdown-description-example/), so if you're happy to do this under your private account, I think this would be ok.

Maybe a few different ones, that include different languages? Python would be the most obvious, but some READMEs also have other languages in them - bash, JS, etc.

**Comment by evemorgen** [comment]
So the Pypi project is here: https://pypi.org/project/pypi-code-highlighting-demo/
And repo is here: https://github.com/evemorgen/pypi-code-highlighting-demo

Any suggestions would be appreciated :)
Also, which section of docs should include information about syntax highlighting? I couldn't find one

**Comment by di** [comment]
Thanks @evemorgen! That looks great, could you add my user `di` as a owner of the project on PyPI?

**Comment by evemorgen** [comment]
Sure thing, that's what I did

**Comment by nlhkabu** [comment]
Thanks @evemorgen.

I think we can add a link to this project from the CSS section here: https://warehouse.readthedocs.io/development/frontend/#scss-style-and-structure

**Comment by ewdurbin** [comment]
Can someone duplicate this upload to test.pypi.org? Then it will can included in the sanitized database dump used for local development.

**Comment by di** [comment]
@evemorgen Would you be able to do that?

**Comment by evemorgen** [comment]
Yep, there it is: https://test.pypi.org/project/pypi-code-highlighting-demo/

**Comment by ewdurbin** [comment]
Thank you! I’ll create a new dev database dump today!


On August 2, 2018 at 12:39:10 PM, Patryk Gałczyński (
notifications@github.com) wrote:

Yep, there it is: https://test.pypi.org/project/pypi-code-highlighting-demo/

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/pypa/warehouse/issues/4400#issuecomment-409990692>, or mute
the thread

**Comment by nlhkabu** [comment]
Closing this.  Thanks @evemorgen for setting this up!

**Comment by evemorgen** [comment]
> Later today

became two months later but it finally is there! 😄
