### ISSUE TITLE
Dev documentation: document expected code format

### ISSUE THREAD

**Issue by nanuxbe** [pypa/warehouse#4409]
There is no documentation about expected code format (ie. max line length, how function call and import should be splitted over multiple lines)

I guess this is valid for both python and js

**Comment by ewdurbin** [comment]
Our code formatting standard for Python was originally PEP 8, as documented at https://warehouse.readthedocs.io/development/submitting-patches/#code, however we recently [migrated to an automated code reformatter called "black"](https://github.com/pypa/warehouse/pull/3367) (see https://pypi.org/project/black/ for a basic description).

For Python code formatting, we should update the [developer documentation](https://github.com/pypa/warehouse/blob/master/docs/development/submitting-patches.rst#code) to specify that our code style is now what is provided by black, and not PEP 8.
