### ISSUE TITLE
claiming ownership of package pathpy

### ISSUE THREAD

**Issue by IngoScholtes** [pypa/warehouse#4413]
### Description

I am the maintainer of [pathpy](https://github.com/IngoScholtes/pathpy) an OpenSource data analytics package that has been under development since more than three years.

We recently started to prepare the release of pathpy via pypi, creating a project on the test server to see whether things are working as expected, see here:

https://test.pypi.org/project/pathpy/

When we wanted to release the package, we realized that the project name has been squatted by the user wbengtson, see here: https://pypi.org/project/pathpy/

This user has claimed a total of 1151 project names - apparantly in an automated fashion - and none of them seems to contain actual code, see here: https://pypi.org/user/wbengtson/ 

I thus request the transfer of ownership of the package pathpy, which - according to the criteria listed in PEP-541 - qualifies as an *invalid package*.

I understand that the transfer of ownership is a critical operation. However, I argue that in this case at least condition 2 in the published "Procedure for Transferring PyPI Name Ownership" is met. In addition, I would assume that an - apparantly automated - squatting of more than a 1000 package names with no actual code being published, violates pypi's code of conduct.

### To Reproduce
Follow links included above

### Additional context
Claiming maintainer control over invalid package (for the reason of name squatting) according to [PEP-541](https://www.python.org/dev/peps/pep-0541/#id27)

**Comment by IngoScholtes** [comment]
Any news on this case? I just see that in similar recent cases the transfer has been approved.

**Comment by di** [comment]
This has been resolved.
