### ISSUE TITLE
[query] Can a project have multiple maintainers?

### ISSUE THREAD

**Issue by kwill** [pypa/warehouse#4414]
*I couldn't find an answer in the Warehouse / PyPA docs, apologies if it's there but I missed it.*

I am the co-maintainer of a project. Both maintainers expect to be able to upload new releases to PyPI. Is this possible?

As a bonus, is it possible to signal a "primary" maintainer, who can add/remove other maintainers?

**Comment by heuermh** [comment]
Ping for update on this issue, I'm having the same trouble.  There seems to be no UI for a user to request the maintainer role for a project from the project owner.  If the project owner is non-responsive, what is the process for adding alternate project owner(s) and maintainer(s)?  The link above is broken.

**Comment by di** [comment]
@heuermh Correct, you cannot currently request ownership/maintainership. See #4861 for a related feature request.

If the owner is unresponsive, the process is: https://www.python.org/dev/peps/pep-0541/

**Comment by kwill** [comment]
@ewdurbin For reference the documentation I was looking at was https://packaging.python.org -- I tried a couple of pages based on their titles, and tried searching for "upload" and "privileges". A new search for "collaborators", "maintainer" and "owner" doesn't turn up anything either.

It should also be clear that this is only available *after* the project is first uploaded, i.e. I can't designate "subaccounts" from my account, only per (existing) project.

**Comment by nlhkabu** [comment]
Maybe we should add the following to our FAQ:

> Q: I want to become a maintainer of a project on PyPI - how do I request this?
> A: Currently, there is no way to request ownership or maintainership of a project via the PyPI interface. Instead you should contact the current owner of the project. Many project owners provide their contact details when uploading their packages; these are exposed in the PyPI interface in the 'author' link.
If an owner is unresponsive, you should follow the [PEP 541](https://www.python.org/dev/peps/pep-0541/) process to resolve any conflict.

@di is this accurate? Is there a difference between our 'author' field and ownership?

**Comment by heuermh** [comment]
Thank you, @nlhkabu!
