### ISSUE TITLE
Request to add Trove Classifier Framework :: Guillotina

### ISSUE THREAD

**Issue by bloodbare** [pypa/warehouse#4415]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: Guillotina`

## Why do you want to add this classifier?

Guillotina project is growing in terms of libraries and add-ons and a classifier would make tracking them easier. Its a new framework based on Plone and Pyramid ideas with asyncio base.

Right now there are:
https://pypi.org/project/guillotina-rediscache/
https://pypi.org/project/guillotina-dbusers/
https://pypi.org/project/guillotina-elasticsearch/
https://pypi.org/project/guillotina/
https://pypi.org/project/guillotina-statsd/
https://pypi.org/project/guillotina-prometheus/
https://pypi.org/project/guillotina-s3storage/
https://pypi.org/project/guillotina-gcloudstorage/
https://pypi.org/project/guillotina-hive/
https://pypi.org/project/guillotina-pgcatalog/
https://pypi.org/project/guillotina-cms/

**Comment by tkimnguyen** [comment]
I'm a member of the Plone Foundation board. We know there was some question on the naming of the Guillotina package, but we have not heard anything since the summer. Can this proceed? Thank you

**Comment by ewdurbin** [comment]
Sorry for the delayed response on this issue.

The PSF board discussed via mailing list and the consensus was to not add this trove classifier.
