### ISSUE TITLE
Manage button greyed out for a maintainer

### ISSUE THREAD

**Issue by MatMaul** [pypa/warehouse#4423]
Hi,
I am one of the maintainer (NOT the owner) of the pynetgear library.

I can see the project in my projects list on pypi.org, and myself in the maintainers list, however the manage button is greyed out and I can't do anything.

I also tried to push directly with sdist upload, I also get an error.
I tried to change my password, no luck.

cf here for a screenshot:
https://github.com/home-assistant/home-assistant/issues/15078#issuecomment-409056109

**Comment by balloob** [comment]
I think that `python3 setup.py sdist upload` has been deprecated as it uses an unsecure connection. Try this:

```
pip3 install twine
rm -rf dist
python3 setup.py sdist
python3 -m twine upload dist/*
```

**Comment by MatMaul** [comment]
Ah and the manage is only for the owner ? Make sense actually... I'll try this at home thanks.

**Comment by ewdurbin** [comment]
Confirming that PyPI has two roles for collaborators on projects:

## Maintainer
Can upload releases for a package. Cannot add collaborators. Cannot delete files, releases, or the project.

## Owner
Can upload releases. Can add other collaborators. Can delete files, releases, or the entire project.

So the greyed out button is intended to indicate that your role is `Maintainer`, but doesn't make that clear in the UI.

As far as your issues uploading to pypi, `setup.py sdist upload` is in the process of being deprecated in setuptools, but is not yet. You should confirm that your username, password, and the upload endpoint you're submitting to all match up.

If you continue to have issues uploading, sharing your logs from the CLI would be helpful in further debugging!

**Comment by MatMaul** [comment]
Great thanks you all, got it working with twine.
