### ISSUE TITLE
Obvious licensing and trademark issues with various packages

### ISSUE THREAD

**Issue by KeyWeeUsr** [pypa/warehouse#4427]
Please remove these empty packages from [this profile](https://pypi.org/user/rodmena)("rodmena" or "ourway") which have nothing to do related to any of these companies and are most likely just placeholders perhaps for scamming, parking or trolling. Notice the description `a nice memory for future`:

* [toyota](https://www.toyota.com/support/legal-terms)
* [walmart](https://corporate.walmart.com/terms-of-use)
* nba
* [mehrnews](https://en.wikipedia.org/wiki/Mehr_News_Agency)
* [irib](https://www.irib.ir)
* [appido](http://appido.us)
* [chrome](https://www.google.com/permissions/trademark/trademark-list.html)
* [macbook](https://www.apple.com/legal/intellectual-property/trademark/appletmlist.html)
* [osx](https://www.apple.com/legal/intellectual-property/trademark/appletmlist.html)
* [android](https://developer.android.com/distribute/marketing-tools/brand-guidelines)
* [ios](https://www.apple.com/legal/intellectual-property/trademark/appletmlist.html)
* [apple](https://www.apple.com/legal/intellectual-property/trademark/appletmlist.html)
* [htc](https://www.htc.com)
* [sony](https://www.sony.net/copyright/Trademarks.html)
* [samsung](https://www.samsung.com/us/common/legal.html)
* [ubuntu](https://www.ubuntu.com/legal/trademarks)
* [debian](https://www.debian.org/trademark)
* [redhat](https://brand.redhat.com/logos/trademarks)
* angular

and perhaps more.

![image](https://user-images.githubusercontent.com/8825439/43471050-59cc7f32-94ea-11e8-991a-38b094bcc943.png)

**Comment by di** [comment]
Addressed, thanks.
