### ISSUE TITLE
Python package installation issue using pip 

### ISSUE THREAD

**Issue by Manikandankasi01** [pypa/warehouse#4438]
Im not able to install python package in my system. getting below error recently.

```
"Could not find a version that satisfies the requirement xlrd (from versions: )
No matching distribution found for xlrd"
```

python version 3.5
pip version 7.1.2
OS: Windows 10

**Comment by brainwane** [comment]
@Manikandankasi01 Could you please [upgrade](https://pip.pypa.io/en/stable/installing/#upgrading-pip) pip? [The latest pip is pip 18.0](https://pypi.org/project/pip/) -- please tell us whether the problem still happens after you upgrade. Thanks!

**Comment by Manikandankasi01** [comment]
Thanks Brainwane for quick reply.

now im getting some additional error message SSL certification issue.
current pip version : 18.0 

"Could not fetch URL https://pypi.org/simple/xlrd/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/xlrd/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)'))) - skipping
  Could not find a version that satisfies the requirement xlrd (from versions: )
No matching distribution found for xlrd" 

could you pls advice me how to resolve this certification issue.
i tried "pip --trusted-host pypi.org install xlrd" didn't help me.

Thanks in Advance.
Mani

**Comment by brainwane** [comment]
@Manikandankasi01 Please see https://pypi.org/help/#tls-deprecation .

The specific steps you need to take will depend on your operating system version, where your installation of Python originated (python.org, your OS vendor, or an intermediate distributor), and the installed versions of Python, `setuptools`, and `pip`. So we will also need to know your OS and installation details, and the output of `pip install --upgrade -vvv pip`.

**Comment by Manikandankasi01** [comment]
Hi Brainwane,

OS : Windows 10
find below for output of pip install --upgrade --vvv pip

C:\Users\manikandankasi>pip install --upgrade -vvv pip
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Created temporary directory: C:\Users\MANIKA~1\AppData\Local\Temp\pip-ephem-wheel-cache-2q11lmjr
Created temporary directory: C:\Users\MANIKA~1\AppData\Local\Temp\pip-req-tracker-1ehojkwj
Created requirements tracker 'C:\\Users\\MANIKA~1\\AppData\\Local\\Temp\\pip-req-tracker-1ehojkwj'
Created temporary directory: C:\Users\MANIKA~1\AppData\Local\Temp\pip-install-6936281y
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Looking up "https://pypi.org/simple/pip/" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.org:443
Incremented Retry for (url='/simple/pip/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)'))': /simple/pip/
Starting new HTTPS connection (2): pypi.org:443
Incremented Retry for (url='/simple/pip/'): Retry(total=3, connect=None, read=None, redirect=None, status=None)
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)'))': /simple/pip/
Starting new HTTPS connection (3): pypi.org:443
Incremented Retry for (url='/simple/pip/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)'))': /simple/pip/
Starting new HTTPS connection (4): pypi.org:443
Incremented Retry for (url='/simple/pip/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)'))': /simple/pip/
Starting new HTTPS connection (5): pypi.org:443
Incremented Retry for (url='/simple/pip/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)'))': /simple/pip/
Starting new HTTPS connection (6): pypi.org:443
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)'))) - skipping
Installed version (18.0) is most up-to-date (past versions: none)
Requirement already up-to-date: pip in c:\python36\lib\site-packages (18.0)
Cleaning up...
Removed build tracker 'C:\\Users\\MANIKA~1\\AppData\\Local\\Temp\\pip-req-tracker-1ehojkwj'

Thanks,
Mani

**Comment by brainwane** [comment]
@Manikandankasi01 I'm sorry, I missed this. Were you able to resolve your problem? If not, I suggest you get more immediate help using [the `#pypa` channel on Freenode IRC](https://webchat.freenode.net/?channels=%23pypa).

**Comment by di** [comment]
Hi @Manikandankasi01, if you're still having problems, you should open an issue on pip's issue tracker instead: https://github.com/pypa/pip/issues

There are a number of similar open issues already which might help you:
* https://github.com/pypa/pip/issues/5622
* https://github.com/pypa/pip/issues/5465
* https://github.com/pypa/pip/issues/4459
