### ISSUE TITLE
Version lookup should take PEP 440 normalization into account

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#445]
Looking up `1.0.0.0.0` should return `1.0` if it exists, etc.

**Comment by dstufft** [comment]
We probably don't need this at launch, legacy PyPI doesn't do this (and it'll be easier to do once legacy PyPI is gone since we won't have to implement it twice).

**Comment by brainwane** [comment]
Dustin was just working on version normalization in pypa/packaging#121 so this will be shipped soon.
