### ISSUE TITLE
Persistant "Unverified Email"

### ISSUE THREAD

**Issue by stevebeisner** [pypa/warehouse#4456]
I've registered and received several emails, but 
"my account" shows "unverified" email.  I've requested
resend of email to verify several times, but never 
received any.  Checks for mis-direction to spam
folder(s) are negative.

How do I verify my email address?

**Comment by dstufft** [comment]
What's your account name on PyPI?

**Comment by stevebeisner** [comment]
"stevebeisner"     email is beisner@alum.mit.edu

BTW I know the email address is correct because I've received
other PyPI emails, just no verification emails.

**Comment by ssokolow** [comment]
Same. I just received an e-mail asking me to verify my account but, when I asked it to resend the verification e-mail (to the same address that the "please verify" message had just arrived via), it never arrived.

Nothing in my spam bin.

**Comment by stevebeisner** [comment]
OK... got it. Thanks.

**Comment by ewdurbin** [comment]
@ssokolow similarly, can you provide your PyPI username so we can take a closer look?

**Comment by ssokolow** [comment]
My PyPI username is the same as here. "ssokolow"

**Comment by dstufft** [comment]
Cool, was just going to say that beisner@alum.mit.edu email looks like it was accepted by the receiving MTA.

It may take a few minutes for emails to arrive since (due to the email campaign) we're sending at a higher rate than normal. If anyone doesn't get their email, plus comment with PyPI username and/or the email address so we can take a look at our logs.

**Comment by ssokolow** [comment]
...and it just arrived now.

**Comment by ssokolow** [comment]
I suppose I was a little impatient, given that, when I first created my account, I tried to verify multiple times, never got an e-mail, and wound up having to ask to be manually verified somehow about a year later.

**Comment by ewdurbin** [comment]
Our Celery worker pool got a bit behind with all of the tasks being generated by the email campaign. We're scaling it up temporarily to help speed up sending.

**Comment by ewdurbin** [comment]
Okay, we're all caught up and sending emails from pypi.org as quickly as is reasonable.
