### ISSUE TITLE
Cannot verify an email

### ISSUE THREAD

**Issue by aikipooh** [pypa/warehouse#4464]
**Describe the bug**
I've added a new address: pooh@aikipooh.name, and the mail with verification link doesn't come.

**Expected behavior**
Mail must arrive.

**To Reproduce**
Maybe send some test mail to this address from the mailserver that handles verification mails?

**My Platform**
I believe this may be because aikipooh.name is IPv6 only.

**Additional context**

**Comment by di** [comment]
Yes, the email to that domain has permanently bounced:

> 553 5.1.2 Unknown mail server. Could not find a mail server for aikipooh.name

We're sending email from Amazon SES which I imagine can handle most configurations of mail servers.

You might want to make sure your DNS is properly configured? I'm not sure this the desired result:

```
$ dig aikipooh.name MX

; <<>> DiG 9.10.6 <<>> aikipooh.name MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20347
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;aikipooh.name.			IN	MX

;; ANSWER SECTION:
aikipooh.name.		1799	IN	MX	10 aikipooh.name.

;; Query time: 282 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Aug 04 08:05:28 CDT 2018
;; MSG SIZE  rcvd: 58
```

(Specifically I think the answer should resolve to an IP and not the same name)

**Comment by aikipooh** [comment]
Oh, amazon is retarded too:(
So there are no options for me to use IPv6, you won't migrate from SES so I understand?

**Comment by ewdurbin** [comment]
@aikipooh we don't plan to migrate off of SES in this case, is IPv4 not an option for `MX` on your domain at all? Additionally please try to keep your comments within our [Code of Conduct](https://www.pypa.io/en/latest/code-of-conduct/).

**Comment by aikipooh** [comment]
@ewdurbin Speaking about IPv4, it's not '80s, it's almost an end of a first quarter of 21 century out there.
What about the code of conduct? You find amazon being retarded a personal attack? They're not the only one at that, github cannot send to IPv6 too.

**Comment by youssefsharief** [comment]
I am also unable to verify my email address so I am not able to upload my package
