### ISSUE TITLE
Add javascript/frontend validation of breached passwords

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#4470]
In https://github.com/pypa/warehouse/pull/4468 we've started blocking new passwords (via registration, reset, or password change) that have previously been in a data breach of a compromised website. However, that validation currently only occurs server side, it would be nice to also have it occur client side.

This can happen in two ways:

* Have the client JS hit the HIBP API directly, effectively re-implementing the logic that exists in the Python code.
* Have the client JS hit a private API endpoint on Warehouse, that calls into the logic that exists there.
  * If we do this, what should this API look like? Do we want to just send the password over the wire (since that's going to happen on submit anyways?), do we want to prehash it with sha1 and send that over the wire? Or do we want to reimplement the HIBP api in Warehouse? (this would only prevent leaking our users PII via additional http requests to an external service).

Of course, the other question is whether we want to do this or not. It's hard to do it without either reimplementing logic, or sending the password to Warehouse as the user is typing it, neither of which are ideal. Maybe having this validation happen only server side is ok?

**Comment by yeraydiazdiaz** [comment]
I see value in having the registration form perform this check in the frontend alongside having the strength one using zxcvbn. Admittedtly the logic is simpler in that case but this one [doesn't look that difficult to replicate](https://github.com/pypa/warehouse/blob/master/warehouse/accounts/services.py#L356-L408).

Maybe we could call the HIBP API only when the user focuses away from the password field and onto and/or when focusing on the confirmation input instead on every keypress?

**Comment by brainwane** [comment]
We'd be interested in having volunteers do this work and add this feature to Warehouse! @yeraydiazdiaz is this something you're interested in working on?

**Comment by yeraydiazdiaz** [comment]
Hi @brainwane, nice to have you back 🙂 

Yeah, I could throw some cycles at this.

**Comment by brainwane** [comment]
@yeraydiazdiaz great! Have you had any time to poke at this?

**Comment by yeraydiazdiaz** [comment]
@brainwane I started some time ago but never got far with it, I may get some time to work on this soon though.

**Comment by brainwane** [comment]
That would be great if you could, @yeraydiazdiaz! We get many requests for this feature.

**Comment by brainwane** [comment]
Thanks, all, for working on this!
