### ISSUE TITLE
Notify & restrict users with breached/compromised passwords

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#4471]
As a follow up to https://github.com/pypa/warehouse/pull/4468, we should figure out the best way to get people who have an *existing* password that has been breached/compromised to change their password to something that hasn't been reused. This is somewhat complicated by the fact that we (rightfully) cannot access the plaintext password *except* when the user is logging into the site.

A few ideas for what we could possibly do here:

* Just check on user login and send a flash message asking them to change their password.
* Causing an error to occur in the basic authentication scheme whenever a user tries to login with breached credentials.
  * This would effectively block uploads until the user changes their password to a good one.
* Trigger an email anytime the user authenticates with breached credentials, telling them their credentials have been breached, and asking them to change them.
* Flag the user account as having a compromised/breached password, and display a persistent warning in the UI (similar to unverified email).
  * One potential issue with this is that it leaks additional persistent data about the user's password into the database. If a database gets leaked, an attacker would have a list of users to focus on to try and attempt to break because they have passwords that likely exist in their password dictionary.
* Store a flag in the user's session indicating they have a compromised/breached password, and prevent accessing any other features until they rectify this situation.
  * This has similar problems to storing a flag in the database, except the storage is time limited to how long the user's session can live (I think 12 hours?), which drastically decreases the potential risk. It also lives in a separate system (currently, though there is some desire to move sessions into the database) so it would require compromising two systems instead of one.

One thing to keep in mind, is that for a lot of users, they very rarely log into the UI, and their primary interaction is using an upload client like ``twine`` so a strategy that relies entirely on signals in the UI is not likely to reach a large portion of users. Another thing to keep in mind is that in the future, we are almost certainly going to move to some form of an API key (https://github.com/pypa/warehouse/issues/994).

Given that, I think the right answer here is likely:

- Store a flag in the user's session (or perhaps the DB?) and prevent them from doing anything else in the UI, until they've changed their password.
   - If we have a flag stored in the database, maybe we want to periodically send out an email telling them to change their password? This could get spammy though.
- Block basic authentication when a compromised password is being used.
   - This effectively blocks uploads for now, however in the future when we add API keys, if someone is using an API key, it will *not* block their authentication then.
   - If we're storing the flag for the first item in the DB, then trying to authenticate with a compromised password in the database should also set that flag.

This means that immediately, having a compromised password more or less blocks your ability to do anything until you change it. However once we get API keys, you'll still be able to upload if your account has a compromised password (since presumably the API key isn't also compromised). If an attacker finds a compromised password and logs into the user's account with it, they'll be forced to change the password before they can use the account for anything else, which will trigger an email to the primary address on file indicating that the password has been changed. If they didn't change their password they'll ideally freak out appropriately and start reseting passwords and contacting us.

**Comment by dstufft** [comment]
I was doing some research on this, and it looks like Amazon might preemptively look for people's login credentials in password breaches, and will not only block the user from accessing the site, but will disable their account until they go through the account reset flow [source](https://twitter.com/paulpitchford/status/845310800713699328/photo/1).

**Comment by ewdurbin** [comment]
I'm +1 for the active approach of simply failing authentication when a compromised password is used.

As far as rolling this out, It might make sense to begin with maintainers of projects in top N of download counts then move to 10*N, 100*N, 1000*N, etc... as we get feedback on the impact and user experience of having your upload fail for a new/surprising reason.

Maintainers of well known and heavily used packages are the most likely to take action and understand the importance. Rolling this out in stages improves the security of the broader ecosystem immediately and offers us a chance to work out the snags before enforcing for all users of PyPI.

**Comment by dstufft** [comment]
Ok new idea. Whenever someone authenticates with compromised credentials, we fail the authentication with an appropriate error message, at the same time we invalidate the password on the account and require users to reset their password.

Last night I was doing a fair amount of research on this topic, and I've been thinking about it, and I think the above is the correct way to go, and it's not super unusual. As I mentioned previously, Amazon is currently invalidating passwords on accounts with compromised credentials, and I've looked into what a number of other people are doing:

* [Eve Online](https://twitter.com/stebets/status/989907333441605632) sends an email to warn users.
* [Kogan](https://www.kogan.com/au/password-safety/) blocks creating new passwords, does not (currently?) do anything for existing accounts.
* [Bittylicious](https://blog.bittylicious.com/2018/02/have-i-been-pwned/) blocks creating new passwords, prevents certain classes of users from logging in if their passwords is compromised.

I've mentioned this to @ewdurbin, but I feel like limiting by top N packages doesn't exactly give us the segmentation we're looking for. Because we already have a natural segmentation happening in that we're only going to be able to run the check on users who are currently authenticating to PyPI.

FTR, the number of users who have logged into the site in the past 24 hours is 1501, so in a single day period of time during one of our most active days, the total possible number of users affected was ~1.5k. Our metrics on how many *users* are authenticating, but rather how many total authentications are happening. That is currently at 798 (which doesn't quite cover 24 hours). 

Because we're only tracking authentications, we have to try and make some guesses here. However, we can see that ~71 of them were from users logging in via the website. Since it's unlikely that people are logging in 2-3+ times in the web in a 24 hour period of time (logging in isn't very useful general). I'd say we can say that would be ~70 affected users. Next if we look at basic auth, we can see 727 affected authentications. Trying to look at the distribution of users who logged in since then, and how many times they logged in, I'm going to guess there is another 60-70 users affected. For a total of roughly ~140 affected users in the last 24h. 

Given that. I feel like a sample of ~140 users/day isn't the worst possible outcome here and is vastly simpler to add.
