### ISSUE TITLE
Verification emails not arriving at "@stfc.ac.uk" domain

### ISSUE THREAD

**Issue by agstephens** [pypa/warehouse#4473]
Hi, 

I'm not receiving PyPI verification emails at this domain `stfc.ac.uk`. My email is ag.stephens @ stfc.ac.uk . I have received verification emails for my other email address "@ncas.ac.uk" so I can confirm that it is working.

I am logged into the user portal (https://pypi.org/manage/account/#account-emails) and clicking the "Resend verification email".

Thanks

**Comment by ewdurbin** [comment]
Hello @agstephens! I've confirmed that I can see three emails with Subject "[PyPI] Email verification" that reported to be successfully delivered to this address by our provider.

Dates (UTC):

- Aug 6, 2018, 10:03:19 AM
- Aug 6, 2018, 10:10:53 AM
- Aug 6, 2018, 1:49:12 PM

The sender is `noreply@pypi.org`. Have you checked spam folder and ensured it wasn't caught in any filters in your inbox?

**Comment by agstephens** [comment]
Thanks @ewdurbin, I have tried putting `@pypi.org` in my Junk Mail allowed senders list but no luck. I suspect it is getting filtered at the site firewall. I will chase it up with my colleagues. Many thanks for getting back to me so quickly.
