### ISSUE TITLE
Docs missing what "warehouse" is or should be in the future

### ISSUE THREAD

**Issue by guettli** [pypa/warehouse#448]
I looked at this page:

https://warehouse.readthedocs.org/en/latest/

I am missing what warehouse is or should be in the future.

**Comment by dstufft** [comment]
What sort of thing are you looking for there? Warehouse is "PyPI 2.0", I'm not sure how best to describe it.

**Comment by msabramo** [comment]
Here's a stab at describing it. 

Warehouse is a new code base that implements a Python package index. It is being actively developed and the plan is that it will eventually power http://pypi.python.org (PyPI) and replace an older code base that is currently powering PyPI. You can see Warehouse in production at xxx. 

Warehouse is built on top of the Pyramid web application framework and uses PostgreSQL, Elasticsearch, etc.

The goal is to improve PyPI by making it:

- be more user-friendly
- have a more modern look
- more features
- remove legacy APIs
- have more maintainable code with test coverage, docs, etc.

**Comment by guettli** [comment]
Thank you very much.
