### ISSUE TITLE
pywinio install issue.

### ISSUE THREAD

**Issue by TongAriel** [pypa/warehouse#4480]
Describe the bug
   pip install pywinio show error message as below.
Collecting pywinio
  Using cached https://files.pythonhosted.org/packages/21/49/4e86ad4ec72018a5608a06802edd6d7282440654763395fcc1d4256ab0f0/pywinio-0.3.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\xxx\appdata\local\temp\pip-install-hw_v4n\pywinio\setup.py", line 8, in <module>
        with open('README.rst', encoding='utf-8') as readme_file, \
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\xxx\appdata\local\temp\pip-install-hw_v4n\pywinio\

Expected behavior
  install success.
To Reproduce
  Always.
My Platform
  Microsoft Windows [版本 10.0.17134.137], 64 bit
Additional context
  pip version 18.0

**Comment by ewdurbin** [comment]
Hello @TongAriel! This issue tracker is for the software that runs https://pypi.org itself, not projects hosted there.

You should file your issue with the pywinio project at https://github.com/starofrainnight/pywinio/issues

**Comment by TongAriel** [comment]
Thanks. I will follow it.
