### ISSUE TITLE
File size limit exemption (tensorflow-rocm)

### ISSUE THREAD

**Issue by parallelo** [pypa/warehouse#4485]
Hi,

We would like to host the [ROCm-targeted port of TensorFlow](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream) on PyPI.  However, we hit the 60MB limit when trying to upload to test.pypi.org.  In the meantime, we have created placeholder `0.0.1`-versioned projects for `tensorflow-rocm` on both Test PyPI and PyPI.  

Details:  
- Project name:  `tensorflow-rocm`
- Size:  114 MB initially, but could eventually be more
- Indexes:  both Test PyPI and PyPI

For some context, the builds for tensorflow derivatives tend to be reasonably large.  For example, [the `tensorflow-gpu` package](https://pypi.org/project/tensorflow-gpu/#files) is in the range of 100-200+ MB.

Please let us know how to move forward.  

Best,

Jeff

**Comment by di** [comment]
I've increased the limit for `tensorflow-rocm` on both PyPI and TestPyPI to 200MB.

Please try to be conservative with how often you make new releases (i.e., don't push nightlies).

**Comment by parallelo** [comment]
Sure, no prob.  Many thanks.
