### ISSUE TITLE
Upgrade the Travis CI server to be ready for Python 3.7

### ISSUE THREAD

**Issue by cclauss** [pypa/warehouse#4488]
**What's the problem this feature will solve?**
Upgrade PyPI to run on Python 3.7 instead of the Python 3.6.

**Describe the solution you'd like**

PyPI's Travis CI server is not compatible with travis-ci/travis-ci#9069 because the worker is still Trusty, not [Xenial as requested in .travis.yml](https://github.com/pypa/warehouse/pull/4487/files#diff-354f30a63fb0907d4ad57269548329e3R1) so the proposed solution is to upgrade that server so it is compatible with travis-ci/travis-ci#9069

**Additional context**

* https://travis-ci.org/pypa/warehouse/jobs/413453666 shows the failure on PyPI's current Travis CI server
    * Generated by #4487
* travis-ci/travis-ci#9069 works on https://travis-ci.org or https://travis-ci.com but not on PyPI's current Travis CI server

**Comment by ewdurbin** [comment]
Thank you. This is blocked until Celery supports Python 3.7
