### ISSUE TITLE
503 response adding a Maintainer to a project

### ISSUE THREAD

**Issue by mhrivnak** [pypa/warehouse#4496]
**Describe the bug**
When I try to add a Maintainer to a project I own, I get a 503 response and the "Sorry, something went wrong" page.

**Expected behavior**
The Maintainer should be added, or an error message should be displayed explaining what I did wrong.

**To Reproduce**
As the project owner, go to this page: https://pypi.org/manage/project/radiotherm/collaboration/

Type in "craftyguy" as the username and click the "Add" button.

I can see that a POST request happens to https://pypi.org/manage/project/radiotherm/collaboration/, and the response code is 503.

I also tried adding them as an Owner, but I got the same result.

**My Platform**

Chrome on Linux Version 67.0.3396.62 (Official Build) beta (64-bit)

**Additional context**

**Comment by dstufft** [comment]
Sorry, this is a bug due to a change that was pushed out. Will have it fixed shortly.

**Comment by dstufft** [comment]
Should be fixed now, sorry about that.

**Comment by mhrivnak** [comment]
We've all been there! Thanks for the quick fix. I can confirm it is now working.
