### ISSUE TITLE
File size limit exemption: py-agender

### ISSUE THREAD

**Issue by aristofun** [pypa/warehouse#4501]
- py-agender
- release currently ~190MB, but may potentially grow up to 300-400 with improved DL networks
- both Test and PyPi limits 

The goal is to provide easy "install and go" solution, without any dancing for end user. That's why it's critical to pack neural network weights file, which has to be downloaded anyway.

Thank you in advance.

**Comment by dstufft** [comment]
I've gone ahead and bumped your limit to 300MB on both PyPI and TestPyPI.

Please keep in mind that when you're uploading larger files, you're going to more quickly consume space, which can make life difficult for some of the downstream consumers of PyPI (particularly mirror operators). We generally ask projects with very large file sizes to avoid publishing nightly releases or using extremely fast release cycles on PyPI.

Thanks!

**Comment by aristofun** [comment]
Thank you! No nightly releases then )
