### ISSUE TITLE
PEP 541: Ownership of the 'dots' name

### ISSUE THREAD

**Issue by pradyunsg** [pypa/warehouse#4536]
My intent is to polish up the code I use to manage my dotfiles, and release it as tool, for reuse. The `dots` name is appropriate as this would be a short name, which is preferable for a CLI tool.

I've emailed the author of the tool at Sat, 11 Aug 2018 10:58:23 +0530 and the mail was successfully delivered almost immediately. I'm filing this issue eagerly, so that I don't lose track of this. :)

**Comment by jamadden** [comment]
The owner seems to be @espeed

**Comment by pradyunsg** [comment]
Thanks @jamadden! It seems to me that their last activity on GH was in December 2015.

**Comment by yeraydiazdiaz** [comment]
GitHub reports some recent activity from @espeed, regardless I believe this classifies as an [invalid project](https://www.python.org/dev/peps/pep-0541/#invalid-projects) since there package is empty.

**Comment by di** [comment]
Confirmed that `dots` is an invalid project, and have added `pradyunsg` as an owner.

**Comment by pradyunsg** [comment]
Awesome! Thanks @jamadden, @yeraydiazdiaz and @di! ^>^
