### ISSUE TITLE
Can not change my primary email address (Upload failed)

### ISSUE THREAD

**Issue by Jesus89** [pypa/warehouse#4560]
**Describe the bug**

I can not verify my primary account because it no longer exists. I can not change the primary email address to another address. Bad news: I can no publish packages anymore :(

```
error: Upload failed (400): User 'X' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.for more information.
``` 

**Expected behavior**

It would be great to be able to change the primary address.

**To Reproduce**

1. Go to https://pypi.org/manage/account/
2. Try to change the primary email address

Do I need to wait for the feature to be implemented? Is there a workaround that allows me to publish packages with my account? Thanks!

**Comment by dstufft** [comment]
Add another email address to your account. Once you add that additional email address you can verify that new one. Once you have verified it you can promote that new address to your primary.

**Comment by Jesus89** [comment]
Thanks for the super-fast help! :tada:
