### ISSUE TITLE
pypi search fails

### ISSUE THREAD

**Issue by ArneLeijon** [pypa/warehouse#4561]
I uploaded two projects with twine to pypi.org, after testing at test.pypi.org.
Both projects install correctly from pypi with pip, but one of them does not show up in pypi search.

In browsers Firefox and Safari:

https://pypi.org/search/?q=PairedCompCalc
finds "0 projects for PairedCompCalc", 
but

https://pypi.org/project/PairedCompCalc
shows my project description page correctly.

https://pypi.org/search/?q=samppy
finds my project correctly.

After I log in to pypi.org, or test.pypi.org, both projects PairedCompCalc and samppy show up correctly in my project list.

Both project searches work correctly on test.pypi.org

**My Platform**
Mac OS 10.13.6
Firefox 61.0.2
Safari 11.1.2

**Comment by ewdurbin** [comment]
It appears that this may be related to failed retry logic in our Celery/SQS setup that handles partial index updates.

**Comment by ewdurbin** [comment]
I believe this is resolved.
