### ISSUE TITLE
Claim pupil-labs account on PyPI

### ISSUE THREAD

**Issue by papr** [pypa/warehouse#4566]
Dear maintainers,

I work for [pupil-labs](https://github.com/orgs/pupil-labs/teams/pupil-devs) and we would like to claim the [`pupil-labs`](https://pypi.org/user/pupil-labs/) account on PyPI.

pypi@pupil-labs.com can be used for further authentication.

We are aware of https://pypi.org/help/#project-name-claim and asked in the #pypa Freenode channel for help. It was suggested to open an issue here.

We are currently planning on separating the core logic of our applications into a python package that we would like to publish on PyPI. In order to do so, we would like to claim the PyPI account mentioned above. It does not have any projects to it and it seems to be otherwise inactive.

Please let me know if you need any further information or action from our side and thank you for your help!

**Comment by ewdurbin** [comment]
Hi @papr. This account is currently associated with an email account for pupil-labs.org and was registered 2016-08-30 which is also their last login, it doesn't have any projects or history associated with it.

There are no MX records or other DNS for this domain, so I feel reasonable releasing it.

The primary email address for this account name has been updated to the one provided. You can issue a password reset to recover the account now.
