### ISSUE TITLE
HTTPError: 403 Client Error: The user '' isn't allowed to upload to project 'iotedgedev'.

### ISSUE THREAD

**Issue by jongio** [pypa/warehouse#4607]
**Describe the bug**
Trying to upload via twine.  New project. Not registered, but getting this:

`HTTPError: 403 Client Error: The user '' isn't allowed to upload to project 'iotedgedev'. See https://test.pypi.org/help/#project-name for more information. for url: https://test.pypi.org/legacy/
`
This is a 404: https://test.pypi.org/project/iotedgedev/

My code works if I change the package name...but would like to not do that.

**Expected behavior**
Uploads the package

**To Reproduce**

Try to upload to that project.

**My Platform**
using git bash

**Additional context**

**Comment by ewdurbin** [comment]
Hello @jongio this project name has already been registered on test.pypi.org and pypi.org.

The users have uploaded releases to PyPI at https://pypi.org/p/iotedgedev, but do not appear to have created any releases on Test PyPI.

As the project name is taken and appears to be an active project it seems selecting another name is your best path forward.

**Comment by jongio** [comment]
@ewdurbin There is something fishy going on because the project should be registered to my account. I would like to research who created the project because it is likely me or someone on my team. Can you help me track this down?

**Comment by ewdurbin** [comment]
Test PyPI and PyPI are completely isolated from one another. Can you confirm that you want to be uploading to TestPyPI?

Taking a closer look, it sure does appear that you're one of the owners on the real PyPI!

**Comment by jongio** [comment]
Yes, I want to upload the same name to both test and prod pypi, otherwise I would need lots of name replacements through my code and scripts. 

Can you add me to that test project or let me know who created it?

Thanks a lot.

**Comment by ewdurbin** [comment]
@jongio the existing project with no releases has been removed. you can now register it using your TestPyPI user

**Comment by jongio** [comment]
@ewdurbin - I retired and get this error:

`HTTPError: 400 Client Error: This filename has already been used, use a different version. See https://test.pypi.org/help/#file-name-reuse for url: https://test.pypi.org/legacy/`

**Comment by jongio** [comment]
I repushed with a different version in the file name and it worked!  Not sure why the other name would have a conflict if there were no releases.  

I'm now uploading!  Thanks a lot for your help.  REALLY appreciate it.

**Comment by mett96** [comment]
Hi I have the same error of "jongio".

```
HTTPError: 403 Client Error: The user 'Sankios' isn't allowed to upload to project 'simple_logger'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

This error occurred when I try to upload the new package to pypi.org. 

I checked that a package simple_logger already exists, but I named my package **simple-logger**.

Is the name changed during the upload?

This is a part of my setup.py file 
```
setuptools.setup(
    name="simple-logger",
    version="0.0.1",
```

**Comment by jamadden** [comment]
> I checked that a package `simple_logger` already exists, but I named my package `simple-logger`.
> Is the name changed during the upload?

Yes. PEP 503 defines the PyPI API and states that [all project names are normalized](https://www.python.org/dev/peps/pep-0503/#normalized-names): 

> The name should be lowercased with all runs of the characters `.`, `-`, or `_` replaced with a single `-` character. 

Thus, the names `simple-logger` and `simple_logger` are equivalent.

**Comment by mett96** [comment]
@jamadden thanks for the explanation

**Comment by AnhQuoc533** [comment]
Hi @jamadden, I have a similar problem to while trying to upload my package to PyPi (not TestPyPi):
```
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         The user '...' isn't allowed to upload to project 'neural_network'. See https://pypi.org/help/#project-name for more information.
```
I did check and didn't see any uploaded package with the name _neural_network_ or _neural-network_. Can you help me check this error, please?
My package name is _neural-network_ and the project name is _neural_network_.
Thank you.

**Comment by di** [comment]
Please see https://pypi.org/help/#project-name, which explains why this is happening and what you can do about it.
