### ISSUE TITLE
PEP 541: Ownership of the "nox" name

### ISSUE THREAD

**Issue by theacodes** [pypa/warehouse#4610]
👋 I'd like to take ownership of the "nox" name. It appears this name is registered but a package was never published. See https://pypi.org/project/nox/ (note that it's a *very* different 404 page).

Because of this, I have no way of contacting the owner and it appears this has been abandoned for quite some time.

I currently own the "nox-automation" but would like to shorten our name to just "nox".

Thanks!

**Comment by di** [comment]
@Ashald Great! The easiest thing to do would be to add @theacodes as an owner of the project.

**Comment by Ashald** [comment]
@theacodes can you confirm that this is you https://pypi.org/user/theacodes/ please?

**Comment by theacodes** [comment]
That's me! Thank you so much, @Ashald!

**Comment by Ashald** [comment]
Assigned you an `owner` role. Unfortunately, I cannot remove myself from being an owner. Maybe you can do that?

And you're more than welcome

**Comment by theacodes** [comment]
Done, thanks again!
