### ISSUE TITLE
Should upload a command line tool? (missing in FAQ)

### ISSUE THREAD

**Issue by vporton** [pypa/warehouse#4611]
**What's the problem this feature will solve?**

I have created a command line utility using Python. It has Python API, but this API was created only to be a component of the command line utility, not to be used independently. I am unsure whether I should upload it to PyPI. Or does PyPI is only for Python _libraries_? (not for example for command line utilities or daemons)

Is it enough that I distribute my tool at GitHub? Or where else should I distribute it?

**Describe the solution you'd like**

It should be in FAQ.

**Comment by vporton** [comment]
https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html "This is useful for ... just taking advantage of the setuptools / PyPI infrastructure to distribute a command line tool that happens to use Python." So it seems that uploading to pypi for programs (not libraries) in Python is advised for

**Comment by ewdurbin** [comment]
@vporton indeed! Using PyPI for this purpose is a valid use case!
