### ISSUE TITLE
Claim ownership of daisy package

### ISSUE THREAD

**Issue by funkey** [pypa/warehouse#4612]
I would like to take over package "daisy", which under PEP 541 is an "Invalid Project":

> [Invalid projects](https://www.python.org/dev/peps/pep-0541/#invalid-projects)
> A project published on the Package Index meeting ANY of the following is considered invalid and will be removed from the Index:
> * [...]
> * project is name squatting (package has no functionality or is empty);

The package was last updated in 2014 and contains only an empty `__init__.py`. The project homepage leads nowhere. I contacted the author but did not receive an answer.

**Comment by funkey** [comment]
How shall we proceed? If it is more convenient, please feel free to reach out to me by e-mail.

**Comment by funkey** [comment]
Just as a friendly reminder, I am still interested in taking over package "daisy". Please let me know how to proceed. Thanks a lot.

**Comment by jakirkham** [comment]
Is there additional information needed here?

**Comment by yeraydiazdiaz** [comment]
Hello @funkey, apologies for the delay in processing this request.

The project is indeed invalid so we will proceed with the transfer. Could you confirm your PyPI username, please?

**Comment by funkey** [comment]
Hi @yeraydiazdiaz,

My PyPI username is `funkey`, just as my github handle. Thank you very much!

**Comment by ewdurbin** [comment]
Transfer complete.
