### ISSUE TITLE
Request to add classifier License :: OSI Approved :: SIL Open Font License & License :: GUST Font License

### ISSUE THREAD

**Issue by JonasT** [pypa/warehouse#4617]
Request to add a new Trove classifier

## The name of the classifier you would like to add
`License :: OSI Approved :: SIL Open Font License`.
`License :: GUST Font License`.

## Why do you want to add this classifier?
Some programs like games or UI libraries may want to include some data files directly, and for many modern games and UI libraries specifically, this may include `*.ttf` fonts.
The most common font license is probably the `SIL Open Font License (OFL)`, and another one used for the quite sizeable book font package `Tex Gyre` is the [GUST FONT License](http://www.gust.org.pl/projects/e-foundry/licenses/GUST-FONT-LICENSE.txt/view).

I want those two classifiers personally because I include a very small selection of fonts licensed under both in my repository as data files (because otherwise I'd need a dependency to LaTeX with their package manager or other rather complicated things for a few small `.ttf` files), so unless those two classifiers are added, I can't properly classify my project. (I got an error message when trying to upload it with those two unknown classifiers sadly, otherwise I would have just put them anyway and let it be)

**Comment by JonasT** [comment]
Yes, that looks good. The fonts I use seem to be OFL 1.1 and GUST 1.0, respectively, so that would work fine for my particular project. (Not sure which other versions might be in circulation)

**Comment by di** [comment]
I've added the above classifiers. Thanks for the report!
