### ISSUE TITLE
Reclaim my account (alfateam123)

### ISSUE THREAD

**Issue by alfateam123** [pypa/warehouse#4622]
Hi,

I am https://pypi.org/user/alfateam123/ . I did not use this account for a long time, and it seems that I used an old email account that does not exist anymore (alfateam123@nwa.xyz).

The only package owned by that account, [moesearch](https://pypi.org/project/moesearch/), is based on the [moesearch github repository](https://github.com/alfateam123/moesearch), that I own. I'd like to publish a new version of the package.

Let me know if you need some more information to verify my account!

**Comment by di** [comment]
Hi @alfateam123, can you email me at `di@python.org`? Thanks!

**Comment by di** [comment]
Resolved.
