### ISSUE TITLE
Add link to PyPI Twitter account in footer

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#4630]
We should add a link to the PyPI twitter account (https://twitter.com/PyPI) in the footer somewhere.

This will, perhaps, require a reorganisation of the footer columns, to make each column have more or less of the same number of links

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: Please include a screenshot of your update. This helps our team give you feedback faster.

**Comment by kwasielew** [comment]
Hey guys, I would like to contribute to this task, I've prepared quick solution:
![footer-warehouse](https://user-images.githubusercontent.com/17218744/45926792-7b1e9900-bf28-11e8-8ebc-807e0d795928.png)
but most probably this is not the best place for link, do you have suggestions where to place Twitter link/rearrange columns? Thanks

**Comment by nlhkabu** [comment]
Hi @kwasielew,

How about be move the status onto it's own line below the columns? Currently this is a bit awkward anyway, because it can wrap onto two lines easily. Something like this:

![screenshot from 2018-09-28 07-13-55](https://user-images.githubusercontent.com/3323703/46191106-22ffe200-c2ee-11e8-8983-c96f7ceb935d.png)

**Comment by Gouravchawla** [comment]
It seems this issue has already been resolved. Can this be closed now?
