### ISSUE TITLE
Clean up nonsense packages?

### ISSUE THREAD

**Issue by smurfix** [pypa/warehouse#4635]
What should I do when I encounter packages which are obviously nonsense, or a user (like "hassanj") who uploads 100+ such packages (named w/ variations of "asdasdasdasd")?

I don't think ignoring such packages/users is a good long-term solution.

**Comment by di** [comment]
Hi @smurfix, as long as the package doesn't seem to be malicious, feel free to ignore it.

We have [PEP 541](https://www.python.org/dev/peps/pep-0541/) which allows us to remove invalid or abandoned projects, but in practice we really only remove these packages if a user reaches out to us wanting to actively use a package name that is being squatted on.
