### ISSUE TITLE
Transfer yarn-api-client project to different account 

### ISSUE THREAD

**Issue by toidi** [pypa/warehouse#4637]
Hi there, I'm maintainer of https://pypi.org/project/yarn-api-client/
Github link https://github.com/toidi/hadoop-yarn-api-python-client

At the beginning I used company's corporate email for my pypi.python.org account.
I don't have an access to that email now.

Please transfer `yarn-api-client` to pypi.org account with username `toidi`.

Old ticket for reference: https://github.com/pypa/pypi-legacy/issues/479

**Comment by di** [comment]
Hi @toidi, I've sent you an email about this.

**Comment by toidi** [comment]
Thanks!
