### ISSUE TITLE
Unable to login or Reset Password of asposeemail account

### ISSUE THREAD

**Issue by aspose-cloud** [pypa/warehouse#4648]
Hi,

I am Sohail, Aspose Cloud Support Manager. Every time I try to log into **asposeemail** account I receive following error:
"This password appears in a breach or has been compromised and cannot be used."

I tried to reset the password of this account, though PyPI shows a message that "We have sent an email to your registered email address." but I never receive an email at following account:
email@aspose.com

Please help us in logging into **asposeemail** account. Thank you.

**Comment by ewdurbin** [comment]
I can confirm that 10 password reset request emails were sent to `email@aspose.com` from `noreply@pypi.org` with subject "[PyPI] Password reset request".

All of these were successfully delivered by our email provider.

Can you confirm that these emails were not misdirected by a filter, noted as spam, or caught up in some other hold?

**Comment by aspose-cloud** [comment]
@ewdurbin 

Thank you for your prompt reply.

Unfortunately, we have not received any email at `email@aspose.com`, I checked the **Junk E-Mail Folder** too.

Earlier we have successfully reset passwords of our other products e.g. `words@aspose.com`, `cells@aspose.com` and `slides@aspose.com`.

I have requested our Platform team to diagnose why we are not getting "Password Reset" emails at `email@aspose.com`.

**Comment by ewdurbin** [comment]
@2017alan what is your PyPI username?

**Comment by 2017alan** [comment]
it's  **alanwang17**    , thank you.

**Comment by ewdurbin** [comment]
@2017alan I'm seeing that all Password Reset Request emails sent for your account showed as delivered by our mail provider. Can you confirm that these emails were not misdirected by a filter, noted as spam, or caught up in some other hold?

**Comment by ewdurbin** [comment]
@aspose-cloud were you able to get any additional information?

**Comment by aspose-cloud** [comment]
@ewdurbin 

`email@aspose.com` email address is functional. We are receiving all emails on this account except from PyPI. Please suggest is there any other way to reset the password, we are unable to update [asposeemailcloud](https://pypi.org/project/asposeemailcloud/) package.

**Comment by di** [comment]
@aspose-cloud Is there another email we could try for the account instead?

**Comment by di** [comment]
@aspose-cloud That email address is already in use by another PyPI account, is there another email you can use instead?

We could also transfer the projects owned by the `asposeemail` account to that account if you'd prefer.

**Comment by aspose-cloud** [comment]
@di 

Please check if `marketplace@aspose.com` could work.

**Comment by di** [comment]
@aspose-cloud There's already an account with that email address as well.

**Comment by aspose-cloud** [comment]
@di 

We actually want to upload `asposeemailcloud` latest package under [asposecloud](https://pypi.org/user/asposecloud/) account.

You may simply delete [asposeemailcloud](https://pypi.org/project/asposeemailcloud/) from [asposeemail](https://pypi.org/user/asposeemail/) account, we will upload updated package under [asposecloud](https://pypi.org/user/asposecloud/) account.

If this is not possible, please use muhammad.sohail@aspose.com email address.

**Comment by di** [comment]
I've updated the email address to be `muhammad.sohail@aspose.com` and initiated a password reset request, please close this issue once you've regained control of the account.

**Comment by aspose-cloud** [comment]
@di 

Unfortunately, I have not received any password reset email at `muhammad.sohail@aspose.com`. 

I even tried to reset the password by entering email here https://pypi.org/account/request-password-reset/. But again no email in Inbox or Spam folder.

**Comment by di** [comment]
@aspose-cloud I've got logs showing five reset emails delivered in the last 24 hours to that address and accepted by the `aspose.com` mailserver. I also don't have any other reports of this happening elsewhere.

I'd recommend either talking to whoever manages your mailserver and determining why the server is accepting messages but not delivering them, or you'll need to give me an email address that uses a different domain.

**Comment by aspose-cloud** [comment]
@di 
Please use `msohailismail@gmail.com` email address.

Between thank you for your continuous support.

**Comment by di** [comment]
@aspose-cloud You should have an email with the subject "[PyPI] Password reset request" in your inbox.

**Comment by aspose-cloud** [comment]
@di Yes, I have received the email. Thank you so much.
