### ISSUE TITLE
Cannot access account james.mcmahon

### ISSUE THREAD

**Issue by James1345** [pypa/warehouse#4649]
Recently started recieving an error that a verified email address is needed. Couldn't even remember my username. Entered my email address for forgotten password (james1345@googlemail.com) and received a message that no such email address was in the PyPi systme (also tried james1345@gmail.com). Sure enough, I could register a new account with the email address.

Eventually found my old username was james.mcmahon. Asked for password reset for that account. Have not received a password email. Don't know where the email is going, but it's going to none of my accounts that forward to my inbox. Can I get an account reset on that account (or just get my email address associated to the account)

**Comment by ewdurbin** [comment]
Hello @James1345! The email address associated with the account is on the intouch-ltd.com domain, if you no longer have access to that address?

**Comment by James1345** [comment]
I didn't realise that was still the address associated with that account. I've not had that address for years

**Comment by ewdurbin** [comment]
@James1345 I've updated the email address to james1345@googlemail.com for this user and you should be able to complete a password reset.

For verification I looked at the metadata on previously uploaded projects and noted that `james1345@googlemail.com` had been supplied as author-email on everything previously uploaded.
