### ISSUE TITLE
package size limit increase request

### ISSUE THREAD

**Issue by jamesalbert** [pypa/warehouse#4650]
Package name: jenkenv
link: https://pypi.org/project/jenkenv/
size: 121M
index: PyPI only is fine.

Reason: I use a pre-built distribution of a dynamically linked java package (jenkinsfile-runner).

While the build is 121M, an increase to 150M would be preferred for future-proofing. Let me know if you need anymore info from me.

**Comment by di** [comment]
Hi @jamesalbert, could you give us some more details about what the package does? The description on PyPI is empty and https://github.com/jamesalbert/jenkenv is 404.

**Comment by jamesalbert** [comment]
No worries. It creates virtual environments for people using jenkinsfile-runner. Provides a workflow along the lines of:
```
jenkenv install 2.121.3
jenkenv use local 2.121.3
jenkenv run-jenkins # install your desired plugins at localhost:8080
jenkenv run Jenkinsfile
```

Source isn't public yet, will do that tonight, but I wanted to get a working build going first.

**Comment by jamesalbert** [comment]
I've also added `long_description` after I uploaded so it will have more details in the next upload :)

**Comment by jamesalbert** [comment]
in any case, repo is public now https://github.com/jamesalbert/jenkenv

link to jenkinsfile-runner for reference https://github.com/kohsuke/jenkinsfile-runner

**Comment by di** [comment]
@jamesalbert I've set the limit for `jenkenv` to 150MB on PyPI.

**Comment by jamesalbert** [comment]
@di you rock, ty!
