### ISSUE TITLE
issue about pypyodbc.py that 1.2323E-2(-0.012323) will read as b"E-2" from xxx.mdb file

### ISSUE THREAD

**Issue by freeworldabc** [pypa/warehouse#4658]
**Describe the bug**

1.read data from xx.mdb file
2.the data is : -0.06737877 
3.but have some err as below:
--------------------------err info start----------------------------
b'5.0'
b'-0.1081777'
b'6.0'
b'E-2'   
Traceback (most recent call last):
  File "C:\tiger\1_python\python_ericsson\ericsson_access_data_arrange_ota\do_ac
cess_data_arrange_ota.py", line 198, in <module>
    main_running(sys.argv[1])
  File "C:\tiger\1_python\python_ericsson\ericsson_access_data_arrange_ota\do_ac
cess_data_arrange_ota.py", line 166, in main_running
    arrange_data(filename)
  File "C:\tiger\1_python\python_ericsson\ericsson_access_data_arrange_ota\do_ac
cess_data_arrange_ota.py", line 90, in arrange_data
    (data1,data2)=get_data_access(db_filename)
  File "C:\tiger\1_python\python_ericsson\ericsson_access_data_arrange_ota\do_ac
cess_data_arrange_ota.py", line 66, in get_data_access
    sel_data1 = mdb_sel(cur, sql)
  File "C:\tiger\1_python\python_ericsson\ericsson_access_data_arrange_ota\py\pu
blic_access_db.py", line 89, in mdb_sel
    return cur.fetchall()
  File "C:\Users\ENNYIQI\AppData\Local\Programs\Python\Python36\lib\site-package
s\pypyodbc.py", line 1840, in fetchall
    row = self.fetchone()
  File "C:\Users\ENNYIQI\AppData\Local\Programs\Python\Python36\lib\site-package
s\pypyodbc.py", line 1897, in fetchone
    value_list.append(buf_cvt_func(alloc_buffer.value))
ValueError: could not convert string to float: b'E-2'
--------------------------err info end----------------------------

**Expected behavior**

the data should read as one of below:
should be:1 or 2,not 3
1-----------------correct---------------------------
b'5.0'
b'-0.1081777'
b'6.0'
b'-0.06737877 '   
2--------------------correct------------------------
b'5.0'
b'-0.1081777'
b'6.0'
b'6.737877E-2 '   

3--------------------err ------------------------
b'5.0'
b'-0.1081777'
b'6.0'
b'E-2 '   

**To Reproduce**

**My Platform**

system info:
windos7    micro office 2016 for xxm.mdb

python info:
C:\Users\ENNYIQI>python
 Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD6
 4)] on win32
 Type "help", "copyright", "credits" or "license" for more information.

**Additional context**

**Comment by freeworldabc** [comment]
thanks for coder  help first for repair the issue ASAP!

**Comment by freeworldabc** [comment]
python info:

C:\Users\ENNYIQI>python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

**Comment by jamadden** [comment]
Thanks for the report, but unfortunately this is not the correct place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help with packages distributed or installed from there. You'll need to contact the maintainers of that project. If that project is https://pypi.org/project/pypyodbc/, then the tracker you want is https://github.com/jiangwen365/pypyodbc/issues. It looks like this may be this issue: https://github.com/jiangwen365/pypyodbc/issues/30
