### ISSUE TITLE
How do we translate interactions with client software?

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#466]
It's fairly obvious how we can handle translations for web UI users, but what about messages we send down the wire to things like ``python setup.py upload``? It's probably too late to do anything about translating that API but what about for future APIs?

Ideas:

* Include a unique, unchanging message id with any message that client software can use as part of their own internal i18n system.
* Simply respect the ``Accept-Language`` header and expect clients to transmit an acceptable ``Accept-Language`` header for whatever language their users are in.

**Comment by nlhkabu** [comment]
@dstufft given we are putting a hold on translations, is this issue still necessary?

**Comment by dstufft** [comment]
Nope it's not needed anymore, I just missed it.
