### ISSUE TITLE
Trove Classifier: MirOS License

### ISSUE THREAD

**Issue by macheins** [pypa/warehouse#4660]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `License :: OSI Approved :: MirOS License`

## Why do you want to add this classifier?

[The MirOS License](https://www.mirbsd.org/MirOS-Licence.htm) is an [OSI approved](https://opensource.org/licenses/MirOS) license.

**Comment by di** [comment]
Thanks! I've added the classifier `License :: OSI Approved :: MirOS License (MirOS)` (including the SPDX identifier).
