### ISSUE TITLE
bpy-build Package file size limit increase

### ISSUE THREAD

**Issue by TylerGubala** [pypa/warehouse#4661]
Hello!

I filed an issue a while back, requesting a package I maintain, `bpy`'s file size to increase.

https://github.com/pypa/warehouse/issues/4395

However upon further consideration, I actually want to separate the concerns of the built binaries into their own python package, called `bpy-build`. 

Therefore, the built wheel files (the reason for increasing the package file size for `bpy` originally) are going to exist in `bpy-build` from now on.

Could I request that the package `bpy-build` have it's package file size increased? The package `bpy` can be reduced back to the default size as it will no longer be housing the built binaries.

Thanks in advance!

**Comment by di** [comment]
I've set the upload limit for `bpy-build` to 100MB on PyPI.
