### ISSUE TITLE
Display a dates in the timezone of the viewer

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#4662]
**Describe the bug**

I've just published a set of dists and the date in the file table is Sep 3, while it's already Sep 4 in my tz (01:33 am at the time of writing)

**Expected behavior**

Show the date in my timezone, so that it'd not cause confusion.

**To Reproduce**

Set different timezone on your computer

**My Platform**

N/A

**Additional context**

N/A

**Comment by pradyunsg** [comment]
Could you post a SS?

**Comment by pradyunsg** [comment]
Wait, that's unnecessary. Nvm me.

**Comment by jamadden** [comment]
I'm guessing 'Screen Shot'

**Comment by webknjaz** [comment]
Ah, thanks :)

**Comment by pradyunsg** [comment]
> I'm guessing 'Screen Shot'

Yeah.

**Comment by yeraydiazdiaz** [comment]
Had a quick look at this issue and seems we're "humanizing" the date of the release in the Jinja template, which relies on the [`request.locale`](https://github.com/pypa/warehouse/blob/master/warehouse/i18n/filters.py#L24). I searched the Webob docs for it and looks like [it's not "fully calculated"](https://docs.pylonsproject.org/projects/webob/en/stable/differences.html?highlight=locale#id11).

I'm not familiar with Pyramid and Webob enough to know what that means but from the docs seems we should format based on timezone, not locale, which I don't know if it's retrievable in the backend. Can someone advise?

The only alternative I see is to create a simple Stimulus controller so we can access the browser's timezone information.

**Comment by yeraydiazdiaz** [comment]
I guess the formatting *is* dependant on the locale, but the timestamp is always in UTC.

I'll implement the controller I mentioned before.
