### ISSUE TITLE
Blocked Pypi repo name

### ISSUE THREAD

**Issue by omarryhan** [pypa/warehouse#4664]
After huge frustration with setuptools and pypi's legacy API, I uploaded a library 'flask-stateless-auth' with false personal info by mistake.

When I fixed them and tried to re-upload in hopes that my current repo would replace the existing one, it wouldn't.

So I deleted the old repo from pypi and tried again, and it also wouldn't upload bringing me a 403 error. I then checked: https://pypi.org/help/#file-name-reuse and read that it's not possible to regain the name even after you delete the repo from pypi. Is there any way around this?

Thanks,

**Comment by di** [comment]
@omarryhan That error message is about the inability to reuse the _filename_ (project name + version number + distribution type). You should still be able to upload a new file (with a different filename) for a given project: just increment the version number.

**Comment by omarryhan** [comment]
I just did that and it gave me the same error:

HTTPError: 400 Client Error: This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/

**Comment by omarryhan** [comment]
I guess I messed up when I deleted the original repository from Pypi, I could've just incremented the version number and it probably would've worked. :/

**Comment by omarryhan** [comment]
@di Thanks it works now!, I tried deleting the old dist files and `twine upload dist/*` again and it worked.

**Comment by di** [comment]
Great! In the future you can use the `--skip-existing` flag with twine to skip the distributions that have already been uploaded.
