### ISSUE TITLE
I own dozens of projects but two but get a permission denied error when trying to upload a new version

### ISSUE THREAD

**Issue by nutjob4life** [pypa/warehouse#4672]
**Describe the bug**
I was updating a bunch of my projects on PyPI, but two of them failed:
* eke.site
* jpl.mcl.site.sciencedata
The error message for both was: ```Upload failed (403): The user 'nutjob' isn't allowed to upload to project PROJECT-NAME```
However, I am *indeed* the owner of both projects. (And yes, my PyPI username is nutjob.)

**Expected behavior**
I expect to be able to upload new versions to *all* projects I own.

**To Reproduce**
I use `jarn.mkrelease` with the command ```mkrelease -d pypi```.

**My Platform**
The tool to upload to PyPI is `jarn.mkrelease` version 4.1. What doesn't make sense is that I updated a dozen other projects today, but just these two give the 403 error.

**Comment by di** [comment]
@nutjob4life It doesn't look like you currently have the owner role for either of these projects. Specifically:
* For `eke.site`, you were removed as an owner when the entire project was removed on 2017-09-11.
* For `jpl.mcl.site.sciencedata`, you have never had any role for this project.

Do you see either of these projects when you visit https://pypi.org/manage/projects/?

**Comment by nutjob4life** [comment]
Wait `eke.site` was *removed*? But it shows up right here: https://pypi.org/project/eke.site/

And as for `jpl.ml.site.sciencedata`, you are right. Human error. PEBKAC.

**Comment by di** [comment]
@nutjob4life Yes, the entire project was removed on 2017-09-11, then it was re-created and [these four releases](https://pypi.org/project/eke.site/#history) were made.

**Comment by nutjob4life** [comment]
The owner is listed as Sean Kelly; that's me.

**Comment by nutjob4life** [comment]
Oh! I guess I didn't scroll down enough.

All right, he's my colleague. I'll ask him to add me as a maintainer.

Thank you for your time @di!
