### ISSUE TITLE
Increasing size limit for paddlepaddle_gpu

### ISSUE THREAD

**Issue by typhoonzero** [pypa/warehouse#4677]
Hi, our recently released version `paddlepaddle_gpu-0.15` hit the package size limit this day, we try to publish several versions compatible for different CUDA support for deep learning developers that may have some different environment.

The package built with cuda9.0 support currently is over 100MB can you please help to increase this to around 150MB, we'll make effort to reduce the package size in later releases. thanks.

**Comment by typhoonzero** [comment]
Related: https://github.com/pypa/warehouse/issues/4019

**Comment by di** [comment]
@typhoonzero Can you give us some more details about this package? Looking at https://pypi.org/project/paddlepaddle/ and https://pypi.org/project/paddlepaddle-gpu/, there are no descriptions for these packages and they don't link to any documentation, homepage or repository.

**Comment by typhoonzero** [comment]
Hi the homepage is: http://www.paddlepaddle.org/en, and project on github is: https://github.com/PaddlePaddle/Paddle. Thanks

**Comment by di** [comment]
@typhoonzero I've increased the limit for `paddlepaddle_gpu` to 150MB on PyPI. Please be mindful about how often you make a release at this size.
