### ISSUE TITLE
Request for maintainership of 'clcache' package

### ISSUE THREAD

**Issue by frerich** [pypa/warehouse#4678]
I'm the maintainer of the Python program [clcache](https://github.com/frerich/clcache). A bit more than a year ago, a kind contributor by the GitHub user name of 'xoviat' went ahead and registered a [clcache package](https://pypi.org/project/clcache/) on PyPi.

Earlier today I cut a [new release (v4.2.0)](https://github.com/frerich/clcache/releases/tag/v4.2.0); shortly thereafter, frerich/clcache#325 was filed, asking for this new version to be published on PyPi.

I only now notice that I'm not able to do that: the existing clcache package on PyPi appears to be owned by a PyPi user by the name of [ghost555](https://pypi.org/user/ghost555/). I can't seem to be able to contact him by any means - the GitHub account 'xoviat' was deleted and there is no email to be found of either 'xoviat' or 'ghost555'. I'm slightly worried that he may be AWOL.

Is there any way for me to share (or claim) maintainership for the clcache package such that I can upload a new version?

**Comment by frerich** [comment]
I noticed a relevant [FAQ entry](https://pypi.org/help/#project-name-claim) which references #1506 -- but seeing that that ticket has been open for almost two years, I wonder whether there's maybe a faster way to upload a new version of PyPi than waiting on a proper reclaim process to be established. :-]

**Comment by di** [comment]
Hi @frerich, I'm aware that 'xoviat' has seemingly disappeared. It's a shame they didn't give you ownership of the package before they did.

Since the project points to your github repository, I think we can help you regain ownership of it.

What's your PyPI username?

**Comment by frerich** [comment]
@di That sounds great, thanks a lot! My PyPI username is 'frerich'.

**Comment by di** [comment]
This is currently blocked on merging #4405, hang tight!

**Comment by di** [comment]
@frerich I've added you as an owner of the `clcache` package.

**Comment by frerich** [comment]
@di Excellent, it worked - thanks a lot!
