### ISSUE TITLE
Fix casing of commonmark package name

### ISSUE THREAD

**Issue by nikolas** [pypa/warehouse#4679]
Hi, I maintain the commonmark package on pypi, and I have a question about the package name. When I navigate to https://pypi.org/project/commonmark, this gets rewritten to https://pypi.org/project/CommonMark. However, on the pypi test site that I just uploaded to, the package name stays correctly at commonmark: https://test.pypi.org/project/commonmark/  Can someone fix this to make "commonmark" the canonical package name?

Thanks

**Comment by di** [comment]
@nikolas Thanks for the report. As a policy, we don't do special-case SQL queries for things like this.

I created https://github.com/pypa/warehouse/issues/4680 which captures the overall issue and proposes a change that would fix this for anyone in the future as well.

**Comment by nikolas** [comment]
Thank you, I'll close this issue, then.
