### ISSUE TITLE
Add some statistics report in public

### ISSUE THREAD

**Issue by tbhaxor** [pypa/warehouse#4681]
**What's the problem this feature will solve?**
It will help the developers to choose library wisely. More downloads are shown means more reliable and have better support than others.

**Describe the solution you'd like**
Add statistics of the following
1. Total Downloads
2. Weekly Downloads
3. Rating (depends on downloads and release and issue closed)

**Additional context**

NIL

**Comment by paternal** [comment]
I think this is a duplicate of #787 and pypa/pypi-legacy#254 (for the statistics), and #991 (for the rating, although this is not exactly what you were suggesting).

**Comment by di** [comment]
Closing as a duplicate of #787 and #991.
