### ISSUE TITLE
MXNet TensorRT releases requires higher limits

### ISSUE THREAD

**Issue by KellenSunderland** [pypa/warehouse#4686]
Hello, I'd like to request some slightly higher limits for two of my packages.  These distributions are MXNet packages that are optimized for neural network inference on specific GPUs.   Unfortunately this code brings the compressed wheel size over the limits for PyPi.  As a work around I'm shipping code that will be JIT'd on the client side, but this introduced a large delay when the library is first loaded, and it disables some of the GPU specific optimizeations, neither of which is desirable for users.

The name of the project:
mxnet-tensorrt-cu92 and mxnet-tensorrt-cu90

The size of your release, in megabytes:
150 should be more than enough for portable optimized builds supporting major GPU architectures.

Which index/indexes you need the increase for (PyPI, Test PyPI, or both):
PyPI

**Comment by di** [comment]
@KellenSunderland I've set the limit for `mxnet-tensorrt-cu92` and `mxnet-tensorrt-cu90` to 150MB on PyPI. Please be mindful about how often you make releases of these packages, [`mxnet-*` projects currently occupy 9 out of the top 15 projects on PyPI by total package size](https://pypi.org/stats/).

**Comment by KellenSunderland** [comment]
Thanks for the quick fix.  That's a lot of usage.  I'll follow up and see if that amount of storage is really required.
