### ISSUE TITLE
File Size Limit Exemption for sparknlp

### ISSUE THREAD

**Issue by danilojsl** [pypa/warehouse#4691]
Hi,

On behalf of [spark-nlp project](https://nlp.johnsnowlabs.com/), I kindly ask you if you can exempt us from the file size limit. 

We have a growing community of people using our API. We want to make things easier for our python's users, so we decided to use pip installation. But when embedding a jar file into the project, we received a size file error message. 

The jar file size is 80 Mb, hope you can help us with this.

Regards,
John Snow Labs Team

**Comment by di** [comment]
@danilojsl I've set the limit for `spark-nlp` to 100MB on PyPI.
