### ISSUE TITLE
SHA256 hash of packages accessible only with javascript-powered gui web browser

### ISSUE THREAD

**Issue by xHire** [pypa/warehouse#4714]
**Describe the bug**
I can’t access SHA256 hash of downloaded packages if I don’t have a javascript-powered gui web browser at hand.

**Expected behavior**
I would expect to be able to download the hash in a separate file, as is standard with most FLOSS projects. I could then just `sha256sum -c file_with_the_checksum` and be sure it’s OK. (A less ideal option would be to show the hash directly on the page, but that’s a lot less preferable option.)

**To Reproduce**
Visit any pypi project, e.g., https://pypi.org/project/snakeoil/, from lynx and try accessing “Copy SHA256 hash” ⸮link⸮ of any file.

**Additional context**
Just as there are situations where I don’t have `pypi` installed and need to download individual files, there are situations where I don’t have a javascript-powered (nor gui) web browser. Having to download the whole page, extract manually the hash from its source code and then verify it… uh, that’s really frustrating.

**Comment by di** [comment]
You can get hashes via our [JSON API](https://warehouse.readthedocs.io/api-reference/json/), for example:

```
$ curl -s https://pypi.org/pypi/snakeoil/json | jq '.releases."0.7.5"[].digests.sha256'
"33ddfcde89f7f116d15bf49f9c2c7d88755e69a8c54f15e20fd342445878b22e"
"c4abcdc07fce89194ced34856015fe67dee5b5a8238a99a7476e2c5091f513c7"
"7d5324cc7e414ae2b0106810f6ebba0b660a73a7531ebb53d907bedaad8c62ed"
"93e9a6ef0748dbdad5ea6f33956eafc2649f4eb60180c8caa5d0959a22218fc3"
"0e539959074c96b5010907bdadecb3bcd8c2f4f36b6132e781888967efd158d4"
"7c3d6018134e8e6ec2c929296205fd0ef135b7a0a5684910ca64180c81cd46d0"
"7f9852940317e205b880e0e56e1dd5de324c3d20166c4a9ddb4be5f11a11ac69"
"14496f6dd98ec7603403c90b73ca2cdc2d402606635bc8a906b6d4f1c2169f43"
"ce8e3bfbb2175734ad2f37aec90f097e6d1946e85082e7f0cc968828053f6e25"
"5a147cbf4ed12d55a473dd3b5288ca1ac82ab34ff3a11f908b6920bd772cb916"
"2cbcd8b39d0f05c76e734840ef87796b1acfd9dd4c6d352253a7b5b91be7f4c3"
```

The "click to copy" feature should gracefully degrade when JavaScript is not available though, so I'll leave this issue open to fix that.

**Comment by nlhkabu** [comment]
Closing this as the hashes have now been moved to a modal, which can be opened without JavaScript:

![Screenshot from 2019-08-06 08-00-15](https://user-images.githubusercontent.com/3323703/62517937-4f469200-b820-11e9-8015-8abc6cfce679.png)

The "copy" buttons will not work for users without JS enabled, but the user can easily copy the hash manually.
