### ISSUE TITLE
pyBullet installation - URL to MS link tools is not working

### ISSUE THREAD

**Issue by ph-dev-2016** [pypa/warehouse#4716]
**Describe the bug**

I tried to install pybullet with command "pip install pybullet"
Among other things the command tries to build something, but it fails.
There is an error message
" error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools"

**the bug:** that http-URL does not work. Currently (September 2018) a working URL is
https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Expected behavior**

typing the URL in web browser opens a web page where I can download MS build tools.
But it doesn't, probably because the URL is obsolete.

**To Reproduce**

**My Platform**

Windows7 64bit
Chrome browser

**Additional context**

**Comment by jamadden** [comment]
Thank you for the report.

This repository is only for issues with the software that runs pypi.org itself. It cannot help with installing packages distributed there.

However, I did some checking, and the source of that error message appears to be [setuptools](https://github.com/pypa/setuptools/blob/e50d77efb25d9db04a87ceea483d6b74fc58cd91/setuptools/msvc.py#L204). The [link was changed in setuptools 40.1.0](https://github.com/pypa/setuptools/commit/209e3ac20fa69c7352e28b2aeeb2898fbbbf87d4), so updating the version of setuptools installed should resolve this issue.
