### ISSUE TITLE
do we have a warehouse docker image ? 

### ISSUE THREAD

**Issue by mkaja** [pypa/warehouse#4722]
we are planning to install warehouse locally in our environment and want to know whether any docker image is there to get started .

**Comment by di** [comment]
Nope, we don't support or recommend using Warehouse for anything but being https://pypi.org.

You might be better off using a 3rd party tool, see:
* https://packaging.python.org/guides/index-mirrors-and-caches/?highlight=devpi
* https://packaging.python.org/guides/hosting-your-own-index/?highlight=devpi
* There are also many for-profit options available like Artifactory, GemFury, etc.

**Comment by kamikaze** [comment]
this is so selfish, guys...
