### ISSUE TITLE
Question: Is it a bug or any hack attempt ?

### ISSUE THREAD

**Issue by tbhaxor** [pypa/warehouse#4725]
I was looking for registered packages (i want to choose unregistered name for my package)
and when i scrolled down i saw this
![image](https://user-images.githubusercontent.com/28386721/45670776-5057cd80-bb41-11e8-8712-6d6c0c754cff.png)
so i want to ask. What is it?

**Comment by jamadden** [comment]
What you're seeing is an "easter egg" reference to Monty Python rendered by warehouse's [404 template](https://github.com/pypa/warehouse/blob/master/warehouse/templates/404.html#L26). See discussion in https://github.com/pypa/warehouse/pull/2051
