### ISSUE TITLE
https://test.pypi.org/account/register/ [Create Account] greyed out

### ISSUE THREAD

**Issue by Glottotopia** [pypa/warehouse#4727]
I want to create an account at https://test.pypi.org/account/register/, but the [Create account] button remains greyed out even after filling in all fields.

I assume that this is related to some javascript issue, but I have allowed all scripts. 

## My Platform
* Ubuntu 16.04.5 LTS
* Firefox, Chromium and Google Chrome alike. Firefox has a script blocker, the other two browsers do not. 
![screenshot_2018-09-18_13-55-30](https://user-images.githubusercontent.com/1553576/45685712-91081480-bb4a-11e8-8b45-7a4757741eed.png)

**Comment by di** [comment]
@Glottotopia Can you check the JS console in any of those browsers and tell us if you're seeing any errors? Are you seeing any changes in the "password strength" gauge when you change the password?

**Comment by hmpf** [comment]
I see this in firefox and chromium. The password strength gauge never changes.

**Comment by Glottotopia** [comment]
- disable scriptblockers
- click in the password textarea. Type one key.

Pasting the password will not trigger the gauge, but keydown will.

**Comment by hmpf** [comment]
I see the following in the dev tools:
```
Source map error: request failed with status 404
Resource URL: https://test.pypi.org/static/js/vendor/zxcvbn.9cf6916d.js
Source Map URL: zxcvbn.js.map
```

**Comment by hmpf** [comment]
Yep, looks like the gauge cannot handle paste.

**Comment by yeraydiazdiaz** [comment]
sure, I'll take a look 👍
