### ISSUE TITLE
user add to warehouse

### ISSUE THREAD

**Issue by mkaja** [pypa/warehouse#4738]
1. can we  add a new user to upload the packages
2. does all the packages are stored in psql db?

**Comment by di** [comment]
Hi @mkaja, not sure I entirely understand. Are you trying to do development on Warehouse locally?

**Comment by mkaja** [comment]
yes @di

**Comment by di** [comment]
You can add a new user just like you would on `pypi.org` by filling out the registration form.

When running Warehouse locally, it uses a local file storage service to store uploaded packages on-disk: https://github.com/pypa/warehouse/blob/739c4782821ee8df2aadefa9928b0c559ea77e29/warehouse/packaging/services.py#L28-L42

**Comment by di** [comment]
Closing this as I think the question's been answered, feel free to comment if you have more questions.
