### ISSUE TITLE
JSON API omits timezone and microseconds from upload_time

### ISSUE THREAD

**Issue by jwodder** [pypa/warehouse#4751]
When a request is made to `https://pypi.org/pypi/$PROJECT/json` or `https://pypi.org/pypi/$PROJECT/$VERSION/json`, the `"upload_time"` fields in the response contain no timezone information and has no sub-second precision (e.g., `"2018-09-22T19:16:05"`).  Compare this to the XML-RPC API, in which the `"upload_time"` fields in the data returned by the `release_urls` method all end with `Z` and have microsecond precision (e.g., `"2018-09-22T19:16:05.067954Z"`).

**Comment by 30sergey** [comment]
[](url)

**Comment by gsb-eng** [comment]
@di Adding micro seconds might break existing API users, If so how do we handle that?

 How bad is adding a new field in the JSON with `upload_time_with_tz`?

**Comment by di** [comment]
@gsb-eng Yes, see #4752. I think we'll need to add a new field, perhaps we can come up with a better name than `upload_time_with_tz`.

**Comment by di** [comment]
The new field is `upload_time_iso_8601`.
