### ISSUE TITLE
File size limit increase for emojilib

### ISSUE THREAD

**Issue by pine** [pypa/warehouse#4755]
Hello. I'm developing image processing library using C extensions. Could you increase the size limit for this project?

- The name of the project: emojilib
- The size of your release, in megabytes: 68 MB
- Which index/indexes you need the increase for (PyPI, Test PyPI, or both): both

Thank you.

**Comment by di** [comment]
@pine I've increased the limit for `emojilib` to 100MB on both PyPI and TestPyPI.

**Comment by pine** [comment]
@di Thank you!
