### ISSUE TITLE
PEP 541: transfer ownership of abandoned 'pynini' package

### ISSUE THREAD

**Issue by kylebgorman** [pypa/warehouse#4756]
I would like to request to transfer owernship of the name 'pynini' to myself. This project is abandoned since there have been only one alpha release over two years ago and I have repeatedly been unable to contact the apparent maintainer (https://github.com/daffidilly/pynini/issues/1) by filing an issue on GitHub. (Interestingly, this package appeared just weeks after my project of the same name was announced and released.) There is no further contact information for the author.

I wish to use this namespace for my project Pynini (pynini.opengrm.org) which predates the creation of the abandoned package.  An argument might be made that this package is more notable than the abandoned one, since it has a relatively large academic user base, extensive training materials (https://www.oreilly.com/ideas/how-to-get-superior-text-processing-in-python-with-pynini), etc.

I understand that the PEP 541 procedures are just being put together so please direct this request appropriately.

Thanks,
Kyle Gorman
City University of New York / Google

**Comment by kylebgorman** [comment]
Gentle bump of this issue

**Comment by yeraydiazdiaz** [comment]
Hello @kylebgorman, apologies for the delay in processing this request.

I have emailed @daffidilly requesting to clarify his position in regards to this project. Hopefully we will hear back soon and move forwards with this request.

**Comment by kylebgorman** [comment]
Gentle ping, any news here?

**Comment by yeraydiazdiaz** [comment]
Hi @kylebgorman, unfortunately I have no news as of yet, the [reachability section of PEP 541](https://www.python.org/dev/peps/pep-0541/#reachability) states that we need to try at least three times for a maximum period of six weeks since the first contact.

I've written a follow up email and I'm waiting to hear back. Once the six weeks period is over we can move forwards with your request.

**Comment by yeraydiazdiaz** [comment]
@kylebgorman I've attempted contact with the current owner but have not received response thus this project is considered abandoned and we can proceed with the transfer to you.

Could you please confirm your PyPI username?

**Comment by kylebgorman** [comment]
Yes, it's also `kylebgorman`: https://pypi.org/user/kylebgorman/

**Comment by yeraydiazdiaz** [comment]
Thanks, I will ask an admin to transfer the project to you.

**Comment by ewdurbin** [comment]
transfer complete.
