### ISSUE TITLE
Request for maintainership of 'Flask-InfluxDB' package

### ISSUE THREAD

**Issue by btashton** [pypa/warehouse#4759]
I was the maintainer for this project when it was under the Ombitron organization.  The project was originally at `https://github.com/ombitron/flask-influxdb` this has been reconfigured in github to be upstreamed to `https://github.com/btashton/flask-influxdb`.   There is an open issue to cut a new release, but I cannot do this because I no longer control the pypi account which this was registered under.

**Comment by ewdurbin** [comment]
Hello @btashton! Given that the URL in the latest release matches and forwards to the new repo, this seems OK, also that the email address associated with the Owner user appears to have belonged to you.

Can you confirm your PyPI user name?

**Comment by btashton** [comment]
@ewdurbin my username is btashton

**Comment by ewdurbin** [comment]
complete.
