### ISSUE TITLE
File size limit increase for Ray.

### ISSUE THREAD

**Issue by robertnishihara** [pypa/warehouse#4761]
Hi, I'm developing a library for parallel and distributed Python https://github.com/ray-project/ray. Could you increase the size limit for this project?

- Project Name: ray https://pypi.org/project/ray/
- Size of current release 64MB
- Indexes: both test PyPI and PyPI

Thanks a lot for the help!

**Comment by robertnishihara** [comment]
Please let me know if there's other information I can provide or some way I can help with this. Thanks a lot :)

**Comment by di** [comment]
@robertnishihara I've set the upload limit for `ray` to 100MB on PyPI and TestPyPI.

**Comment by robertnishihara** [comment]
@di Thanks so much!
