### ISSUE TITLE
Requesting ownership change of "keystone" name

### ISSUE THREAD

**Issue by dhellmann** [pypa/warehouse#4770]
The Keystone project created by Dan Crosta appears to be abandoned, and we would like to publish packages for the OpenStack Keystone project to PyPI.

Monty Taylor tried to reach Dan on 17 Nov 2017 and again on 8 Jan 2018, without success.

The last release published to https://pypi.org/project/Keystone was in 2012 and the last commit to the related git repo https://github.com/dcrosta/keystone was in 2013.

**Comment by di** [comment]
@dcrosta, would you be willing to transfer the `Keystone` package name to @dhellmann?

**Comment by dhellmann** [comment]
Ah, yes, I should have made that clear. My PyPI account is "doughellmann" and if you transfer it to me I can do the work needed to set it up for our CI system to publish packages.

**Comment by emonty** [comment]
No worries - Thanks for getting back to us. Yes, if you just go to:

https://pypi.org/manage/project/keystone/collaboration/

and add doughellmann as owner that would do it.

Thanks so much for helping us out - we really appreciate it!

**Comment by dcrosta** [comment]
OK @dhellmann -- it's all yours.

**Comment by dhellmann** [comment]
Thank you @dcrosta , I appreciate your willingness to work with us on this!
