### ISSUE TITLE
Requesting ownership change of "congress" name

### ISSUE THREAD

**Issue by dhellmann** [pypa/warehouse#4771]
The "congress" project created by Derek Arnold appears abandoned, and we would like to publish packages for the OpenStack Congress project using that name.

The only release of the existing project was published in Feb 2011 and the GitHub repo https://github.com/lysol/congress was last updated in April 2011.

I have tried to read Derek via GitHub today (https://github.com/lysol/congress/issues/2).

If the ownership is changed to "doughellmann" I can do the work to set things up so we can publish packages.

**Comment by yeraydiazdiaz** [comment]
Hello @dhellmann, apologies for the delay in processing this request.

I've emailed @lysol regarding your request and he seems to have some recent activity in GitHub so hopefully he'll respond quickly and give an answer to your request.

**Comment by dhellmann** [comment]
OK, well, with the lack of response earlier we went with a different name. https://pypi.org/project/openstack-congress/

I think we can close this and not worry about it.
