### ISSUE TITLE
Migrate away from using natural primary keys

### ISSUE THREAD

**Issue by di** [pypa/warehouse#4772]
A number of our tables currently have natural primary keys, such as:

* The `packages` table (used by the `Project` model)
* The `releases` table (used by the `Release` model)
* (...this may be all of them)

We should migrate away from natural keys and use surrogate keys instead where appropriate, e.g.:

```python
id = Column(Integer, primary_key=True, nullable=False)
```

This will require a DB migration and possibly a maintenance period.

**Comment by steiza** [comment]
I'm going to start working on this as part of the PyPA sprints. If anyone is interested in pairing, let me know!

**Comment by ewdurbin** [comment]
Ah, this is already pretty far along in my court @steiza. Given that it will require an admin to roll out (potential downtime, db backups, etc). I'll continue on it!

**Comment by yeraydiazdiaz** [comment]
@ewdurbin is there anything else pending for this issue or should can it be closed?
