### ISSUE TITLE
Inconsistency in release details for library versions in JSON API.

### ISSUE THREAD

**Issue by hendychua** [pypa/warehouse#4775]
**Describe the bug**
The API `https://pypi.org/pypi/<library>/json` is inconsistent in how release details are shown. For example https://pypi.org/pypi/requests/json, under "releases" some versions map to an array with release details while some versions (e.g. 0.0.1, 2.15.0) map to an empty array. These versions are listed on PyPI's website.

**Expected behavior**
Release details for all versions should be present in the response.

**To Reproduce**
Send a `GET` request to `https://pypi.org/pypi/requests/json`.

**My Platform**
N/A.

**Additional context**
N/A.

**Comment by hendychua** [comment]
I see. That's what I thought but just wanted to seek clarification that it is indeed the case.

If no distributions are available for the version, should the version be removed from the API response (and also the library's PyPI page)?

I am using the API to get library versions but I noticed I'm not getting certain versions and the reason is due to the empty arrays. Is it safe to assume that if the distributions array is empty, then technically it isn't a valid release, and I can ignore the version?

**Comment by di** [comment]
> If no distributions are available for the version, should the version be removed from the API response (and also the library's PyPI page)?

No, I don't think so. There's a a difference between a release with no distributions and a release that doesn't exist.

> I am using the API to get library versions but I noticed I'm not getting certain versions and the reason is due to the empty arrays. Is it safe to assume that if the distributions array is empty, then technically it isn't a valid release, and I can ignore the version?

If there are no distributions available, you can assume it's not currently installable, but that doesn't mean it's an invalid release. I can't say wether you should ignore the version or not, I'm not sure what you're doing with the API.

**Comment by hendychua** [comment]
I see. Understood. Thank you for clarifying.
