### ISSUE TITLE
Numpy import fails

### ISSUE THREAD

**Issue by gururchandran** [pypa/warehouse#4777]
**Numpy import fails when I updated numpy package in conda to 1.15.2.**
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/anaconda/lib/python3.6/site-packages/numpy/core/__init__.py in <module>()
     15 try:
---> 16     from . import multiarray
     17 except ImportError as exc:

ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-12-d004031e498e> in <module>()
----> 1 import numpy as np

~/anaconda/lib/python3.6/site-packages/numpy/__init__.py in <module>()
    140         return loader(*packages, **options)
    141 
--> 142     from . import add_newdocs
    143     __all__ = ['add_newdocs',
    144                'ModuleDeprecationWarning',

~/anaconda/lib/python3.6/site-packages/numpy/add_newdocs.py in <module>()
     11 from __future__ import division, absolute_import, print_function
     12 
---> 13 from numpy.lib import add_newdoc
     14 
     15 ###############################################################################

~/anaconda/lib/python3.6/site-packages/numpy/lib/__init__.py in <module>()
      6 from numpy.version import version as __version__
      7 
----> 8 from .type_check import *
      9 from .index_tricks import *
     10 from .function_base import *

~/anaconda/lib/python3.6/site-packages/numpy/lib/type_check.py in <module>()
      9            'common_type']
     10 
---> 11 import numpy.core.numeric as _nx
     12 from numpy.core.numeric import asarray, asanyarray, array, isnan, zeros
     13 from .ufunclike import isneginf, isposinf

~/anaconda/lib/python3.6/site-packages/numpy/core/__init__.py in <module>()
     24 Original error was: %s
     25 """ % (exc,)
---> 26     raise ImportError(msg)
     27 finally:
     28     for envkey in env_added:

ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory

**Comment by gururchandran** [comment]
> ## **Numpy import fails when I updated numpy package in conda to 1.15.2.**
> ImportError Traceback (most recent call last)
> ~/anaconda/lib/python3.6/site-packages/numpy/core/**init**.py in ()
> 15 try:
> ---> 16 from . import multiarray
> 17 except ImportError as exc:
> 
> ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError Traceback (most recent call last)
> in ()
> ----> 1 import numpy as np
> 
> ~/anaconda/lib/python3.6/site-packages/numpy/**init**.py in ()
> 140 return loader(*packages, **options)
> 141
> --> 142 from . import add_newdocs
> 143 **all** = ['add_newdocs',
> 144 'ModuleDeprecationWarning',
> 
> ~/anaconda/lib/python3.6/site-packages/numpy/add_newdocs.py in ()
> 11 from **future** import division, absolute_import, print_function
> 12
> ---> 13 from numpy.lib import add_newdoc
> 14
> 15 ###############################################################################
> 
> ~/anaconda/lib/python3.6/site-packages/numpy/lib/**init**.py in ()
> 6 from numpy.version import version as **version**
> 7
> ----> 8 from .type_check import *
> 9 from .index_tricks import *
> 10 from .function_base import *
> 
> ~/anaconda/lib/python3.6/site-packages/numpy/lib/type_check.py in ()
> 9 'common_type']
> 10
> ---> 11 import numpy.core.numeric as _nx
> 12 from numpy.core.numeric import asarray, asanyarray, array, isnan, zeros
> 13 from .ufunclike import isneginf, isposinf
> 
> ~/anaconda/lib/python3.6/site-packages/numpy/core/**init**.py in ()
> 24 Original error was: %s
> 25 """ % (exc,)
> ---> 26 raise ImportError(msg)
> 27 finally:
> 28 for envkey in env_added:
> 
> ImportError:
> Importing the multiarray numpy extension module failed. Most
> likely you are trying to import a failed build of numpy.
> If you're working with a numpy git repo, try `git clean -xdf` (removes all
> files not under version control). Otherwise reinstall numpy.
> 
> Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory

PS: I downgraded numpy package and it worked for me. There's an issue with the numpy package source file which shows multiarray numpy extension module missing.
       conda install numpy=1.15.1(previous version works fine)

**Comment by jamadden** [comment]
Thanks for the report, but unfortunately this tracker is not the correct place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help with packages distributed or installed from there. You'll need to contact the maintainers of numpy or conda instead.
