### ISSUE TITLE
PyPI strips out `align="center"` for headers in markdown

### ISSUE THREAD

**Issue by darrikonn** [pypa/warehouse#4791]
# What?
Can't align headers to the center. This is possibly for paragraphs, using:
```html
<p align="center">my text</p>
```
and this also works on Github when rendering markdowns. But this does not work in `PyPI` project description.
I set:
```cfg
long_description_content_type='text/markdown'
```
in my `setup.py`.

## Expected outcome
Header to be center aligned.
```html
<h1 align="center">td-cli</h1>
```

## Actual outcome
```html
<h1>td-cli</h1>
```

# What I tried
Tried adding inline style:
```html
<h1 style="text-align: center;">td-cli</h1>
```

Tried wrapping header with `<center>`, both outside and inside:
```html
<center><h1>td-cli</h1></center>
```
```html
<h1><center>td-cli</center></h1>
```

Tried using other headers:
```html
h2, h3, ...
```

---
### Screenshot

![image](https://user-images.githubusercontent.com/5694851/46299545-15b65200-c591-11e8-993f-efde4a164050.png)

**Comment by di** [comment]
Thanks for the report. Can you open this issue at https://github.com/pypa/readme_renderer instead?

**Comment by darrikonn** [comment]
Will do, thanks!
https://github.com/pypa/readme_renderer/issues/126
