### ISSUE TITLE
project_urls is being ignored on PyPI

### ISSUE THREAD

**Issue by nicolaiarocci** [pypa/warehouse#4809]
**Describe the bug**
On PyPI, the latest release of my project is not showing the additional links from `project_urls`. Stats from GitHub are also not there (I suppose this is a consequence of the former problem, as there are no github links in `url`).

**Expected behavior**
Links from `project_urls` and GitHub stats should appear on the project page.

**To Reproduce**
- [Eve page on PyPI](https://pypi.org/project/Eve/)
- [my setup.py](https://github.com/pyeve/eve/blob/master/setup.py#L36)

I [downloaded the .tar.gz from PyPI](
https://files.pythonhosted.org/packages/f4/97/046c61c3a2ea4453dbc2bcff0efad55842d8778d509ef163ae6fa340aecd/Eve-0.8.1.tar.gz), and the metadata is there (and looks ok to me).

Not sure if I am being dumb here, or there is an issue on PyPI side. If the former, apologies.

**Comment by di** [comment]
Hi @nicolaiarocci, how did you upload your distribution? It looks like you might have used `python setup.py upload` (which is now deprecated) instead of using [`twine`](https://pypi.org/project/twine/), which caused some of the newer metadata fields to not be included in the upload.

**Comment by nicolaiarocci** [comment]
Good point @di I might have used the old syntax. Old habits die hard I guess.
