### ISSUE TITLE
File size limit increase request

### ISSUE THREAD

**Issue by Aculeasis** [pypa/warehouse#4817]
Hello, I'm created [project](https://github.com/Aculeasis/rhvoice-wrapper-data) provides libraries and data from RHVoice speech synthesizer. Voices data is very large.

- The name of the project: [rhvoice-wrapper-data](https://pypi.org/project/rhvoice-wrapper-data/)
- The size of your release: 74MB
- Index: PyPI

Thanks a lot for the help!

**Comment by di** [comment]
@Aculeasis I've set the limit for `rhvoice-wrapper-data` to 100MB on PyPI.
