### ISSUE TITLE
File size limit exemption (klayout)

### ISSUE THREAD

**Issue by thomaslima** [pypa/warehouse#4819]
Dear all,

I'd like to request a file size limit exemption for a package that we are trying to upload to pypi. Due to some sort of compilation issue that I am unaware of, the linux wheels are 80.5Mb, whereas the macOS wheels are 7.7Mb. I'd like, however, to make the project available in pypi so we can have beta testers help us while we work on optimizing the package size. Indices: pypi and test-pypi

GitHub link: https://github.com/klayoutmatthias/klayout

Thank you,
Thomas

**Comment by di** [comment]
@thomaslima I've set the limit for `klayout` to 100MB on PyPI and TestPyPI.

**Comment by thomaslima** [comment]
Thank you!

Thomas Ferreira de Lima
tlima@princeton.edu<mailto:tlima@princeton.edu>



On Oct 8, 2018, at 13:08, Dustin Ingram <notifications@github.com<mailto:notifications@github.com>> wrote:


@thomaslima<https://github.com/thomaslima> I've set the limit for klayout to 100MB on PyPI and TestPyPI.
