### ISSUE TITLE
cup abandoned - PEP 541 - Ownership transfer

### ISSUE THREAD

**Issue by mythmgn** [pypa/warehouse#4820]
Hi dear admins,

I'd like to request an ownership transfer of pypi project cup to me (username: mythmgn)

The project has not been maintained since **2014**.  I tried to contact the owner (email addr pavanmishra@gmail.com), but got **no response**. I searched him on facebook and linkdin, and found no one.

The opensource project I lead is here: 
repo of github: https://github.com/baidu/CUP
docs of cup: http://docs.iobusy.com/docs/cup/

Thank you very much.  

-- Gallon Ma

Original cup project info:
pypi: https://pypi.org/project/cup/
repo of github: https://github.com/pavanmishra/cup
author email: pavanmishra@gmail.com

**Comment by jamadden** [comment]
@pavanmishra doesn't seem to have [any recent activity](https://github.com/pavanmishra) on GitHub, but it might be worth opening an issues [on the repository](https://github.com/pavanmishra/cup/issues).

**Comment by mythmgn** [comment]
hi @jamadden 

six weeks has been passed away.   We still cannot reach Pavan.  No response.
Is it OK to go ahead with the transfer?   Thanks.

--mythmgn

**Comment by mythmgn** [comment]
@jamadden  anything else that I can do to get this issue moving?   

Thx.

**Comment by jamadden** [comment]
There’s not much more I can do. We can try pinging the admins (@di) directly, but please remember that PyPI is mostly a volunteer project. Patience is appreciated, sincerely.

**Comment by mythmgn** [comment]
@jamadden   
Thought I might need to do sth else.   Not very family with the transfer procedure.  
Thanks very much for the explanation.   👍

**Comment by mythmgn** [comment]
The original owner Paven showed up and helped with the procedure. 
 Ownership transfer has been done.  This issue is closed. 

Thank you all for the help.  @jamadden  @di
