### ISSUE TITLE
Overwrite V1.0.0 package for PaddlePaddle

### ISSUE THREAD

**Issue by JiabinYang** [pypa/warehouse#4824]
Hi,    

This is paddle-dev, we meet a problem that we uploaded the some wrong packages on V1.0.0：
<img width="852" alt="2018-10-09 7 50 30" src="https://user-images.githubusercontent.com/22361972/46667575-9d890580-cbfc-11e8-8dcd-a2bf65e714d1.png">

<img width="787" alt="2018-10-09 7 52 34" src="https://user-images.githubusercontent.com/22361972/46667675-e80a8200-cbfc-11e8-80e7-d068bd62ca14.png">

Now we'd like to overwrite these uploads and is there any way for us to do that?

Plz help us with that and THANKS A LOT!

**Comment by jamadden** [comment]
Hi @JiabinYang ! [PyPI does not allow reuse of filenames](https://pypi.org/help/#file-name-reuse). The reasoning is two-fold.

- It makes it easier for us to manage the multitude of files that PyPI serves without having to worry about collisions or stale content/versions.
- It prevents malicious actors from replacing a known good package URL with a nasty payload in the event that they compromise a users credentials.

To make a change, you'll need to upload with a different version number (such as 1.0.0.post0 if it's just a packaging change).

(See other issues like #4736)
