### ISSUE TITLE
primefac 1.1 process 5 ValueError: gmpy does not handle infinity

### ISSUE THREAD

**Issue by ghjwp7** [pypa/warehouse#4844]
[If there is a different site for primefac 1.1 bug reports, please let me know; or if this is a previously-reported problem.]

I downloaded primefac-1.1.tar.gz from https://pypi.org/project/primefac/ and tar xzf'd it and said `./primefac s` where s is a large number shown below.  Problem: An error message appeared, "ValueError: gmpy does not handle infinity", as shown in following transcript.

Note, `python --version` shows "Python 2.7.12", gmpy version appears to be gmpy-1.17, `uname -a` shows "Linux mita 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux", and `free` shows 

     total        used        free      shared  buff/cache   available
     Mem:       32800772    15661784     1379632     1690020    15759356    14834292
     Swap:      75599864           0    75599864

Transcript:
```
mita ~/src/primes/pyfac/primefac-1.1 > ./primefac.py 999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999820999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999379000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111159 ;ps
999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999820999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999379000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111159:Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./primefac.py", line 593, in factory
    def factory(method, n, output): output.put((method(n), str(method).split()[1]))
  File "./primefac.py", line 451, in mpqs
    min_prime = mpz(thresh*3)
ValueError: gmpy does not handle infinity
^Z
[1]+  Stopped                 ./primefac.py 999999999999999[snip]000111159
  PID TTY          TIME CMD
22257 pts/45   00:00:00 bash
23536 pts/45   00:00:00 python
23538 pts/45   00:00:23 python
23539 pts/45   00:00:23 python
23540 pts/45   00:00:22 python
23541 pts/45   00:00:22 python
23542 pts/45   00:00:12 python <defunct>
23568 pts/45   00:00:00 ps

mita ~/src/primes/pyfac/primefac-1.1 > kill -9 23536

```

**Comment by di** [comment]
Thanks for the report, but unfortunately this tracker is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with packages distributed or installed from there. You'll need to contact the maintainers of this package instead.

**Comment by ghjwp7** [comment]
@di, thanks, I'll try to contact the primefac maintainer.

Note, perhaps you could add that sentence, "This tracker is only for issues with the software that runs https://pypi.org itself", to the "Bug reports." line at https://github.com/pypa/warehouse/blob/master/CONTRIBUTING.rst and also in the section at https://pypi.org/help/#feedback , which is where the "Bugs and feedback" link at the bottom of https://pypi.org/project/primefac/ goes to.
