### ISSUE TITLE
PEP 541: Request to transfer ownership of python-flint

### ISSUE THREAD

**Issue by fredrik-johansson** [pypa/warehouse#4848]
Hi, I'm the author of python-flint

https://github.com/fredrik-johansson/python-flint

https://pypi.org/project/python-flint/

The PyPi package was kindly created by @xoviat ("ghost555" on PyPi) who unfortunately has disappeared without providing a means of contact (I saw that this also affected some other projects recently).

It would be helpful if you could transfer ownership to me. My PyPi username is "fredrik".

**Comment by di** [comment]
Done!

**Comment by fredrik-johansson** [comment]
That was fast. Thank you!
