### ISSUE TITLE
Unable to view results in any meaningful way (like the old site)

### ISSUE THREAD

**Issue by p-baum** [pypa/warehouse#4849]
**Describe the bug**
The "order by" box has no helpful option such as "by popularity" or "by downloads".  As a result searches are a mishmash of abandoned rubbish rendering the website utterly useless.  Nice one.

**Expected behavior**
I expect to be able to search and find popular packages for solving common problems.  If I cannot do this, what is the site for? Please explain.

**To Reproduce**
N/A

**My Platform**
Applicable to all users

**Additional context**
That you have taken a functional website central to python development and rendered it useless is something to be very ashamed of.  Please fix this or upload the old useful site so we may continue our work.

**Comment by ewdurbin** [comment]
Hello! The report here is similar enough to #3932 and #727 that I will close it as a duplicate.

Additionally the tone and approach taken in the language used is unnecessarily harsh. I'm going to lock this issue after closing and ask that @p-baum remember that participation here falls under the [PyPA Code of Conduct](https://www.pypa.io/en/latest/code-of-conduct/) and that "Trolling or insulting/derogatory comments" are not acceptable behavior.
