### ISSUE TITLE
Transfer my cityscapesscripts to mcordts please

### ISSUE THREAD

**Issue by acgtyrant** [pypa/warehouse#4856]
See https://pypi.org/project/cityscapesScripts/ and https://github.com/mcordts/cityscapesScripts/pull/39#issuecomment-429558888.

**Comment by di** [comment]
@acgtyrant It looks like you're the maintainer of this package, are you not able to transfer it?

**Comment by acgtyrant** [comment]
@di I do not find any transfer page in the PyPI, I only find `delete project` in the settings page.

**Comment by acgtyrant** [comment]
I tranferred the ownship successfully.
