### ISSUE TITLE
Increase size limit request 

### ISSUE THREAD

**Issue by savin-berlin** [pypa/warehouse#4859]
Hey folk, 

I would like to ask you to increase the size limit for the package "zas-rep-tools" to 340 MB, because there are also inside few pretrained models for pos-tagging and also other NLP engines.

P.S.: i already publish this request here: https://github.com/pypa/packaging-problems/issues/204
But as I read in documentation, those request should be published here,  I have also published it here. 

Thx you in advance =)
E.

**Comment by jamadden** [comment]
Do those models change at the same rate as the rest of the package? If not, might it make sense to split the package up into several different packages? An advantage would be that the large parts that change more slowly can be cached and reused.

**Comment by savin-berlin** [comment]
you right, they not. but the thing is, that's this package (+ cli-interface) is more or less for linguists, who are not so in common with programming. and my idea was to ensure that the work with this package is so easy that it just could be possible. so, and to split it into several packages will raise the complexity of the setup  up, what could be an additional challenge for the use, which could be saved up. 
And die to the current situation im planing just publish this version without any new versions of it (maybe in the future could come 1-2 additional versions, but not really more.)

**Comment by jamadden** [comment]
Does splitting it up really add much work for the end user, though? They're going to have to install this package with a tool like pip (`pip install zas-rep-tools`). If this package has an install time dependency on the other packages, then those will be picked up automatically and installed with the same single command.

**Comment by savin-berlin** [comment]
ok, you right. I thought about other way.. 
I will do it, but than I need the limit increase for other package with this models. I already create it under following name: 'zas_rep_tools_data'.
Could you please increase the space for  this package to 310 mb.

**Comment by di** [comment]
I've set the upload limit for `zas-rep-tools` to 340 MB on PyPI. This is quite large, please be mindful of how often you make a new release.
