### ISSUE TITLE
PEP 541: transfer ownership of abandoned 'utidylib package

### ISSUE THREAD

**Issue by nijel** [pypa/warehouse#4860]
I would like to request to transfer ownership of the name 'utidylib' to myself. I've agreed with original uTidylib author (Cory Dodt) to take over the maintenance of the package (few years ago), however it is owned by somebody else on the pypi, so he can not transfer the package ownership to me. Unfortunately I was not able to find any contacts for this user (cntrlr). Is it possible either to transfer ownership to me (nijel) or at least to get contacts for cntrlr?

I understand that the PEP 541 procedures are just being put together (https://github.com/pypa/warehouse/issues/1506) so please direct this request appropriately, but this seems to be the place to collect the requests right now.

**Comment by nijel** [comment]
Just to summary [abandonment state](https://www.python.org/dev/peps/pep-0541/#continued-maintenance-of-an-abandoned-project):

* I got permission from the original autor, but he does not control the pypi entry
* There is no way for me to contact pypi entry owner (see https://github.com/pypa/warehouse/issues/933)
* The code is now actively maintained by https://github.com/nijel/utidylib
* Changing the name is of course possible, but that's probably not what people depending on this would expect

**Comment by yeraydiazdiaz** [comment]
Hello @nijel, apologies for the delay in processing this request.

It appears that `cntrlr` is the sole owner of [uTidylib](https://pypi.org/project/uTidylib/), he should be able to transfer the project to you.

Tagging @corydodt as I believe that's his GitHub user, apologies if it's not.

**Comment by corydodt** [comment]
Hi,

This is @corydodt on github. My pypi user is also corydodt (
https://pypi.org/user/corydodt/). @cntrlr is someone else entirely. I think
the last time I updated utidylib, pypi didn't even exist yet, so I never
created a project there and it does not currently belong to me.

C

_____________________

**Comment by yeraydiazdiaz** [comment]
Right, sorry for the confusion, I will try to contact the owner via email.

**Comment by corydodt** [comment]
No worries, best of luck!
_____________________

**Comment by Cntrlr** [comment]
Hello. As I can see something strange has happened around me. I probably indeed have tried to use utidylib some time ago but the think that I may be it's owner surprises me greatly. I need to check this out guys. If you need something please contact me immediately and I will do my best to help you.

**Comment by yeraydiazdiaz** [comment]
Hi @Cntrlr. I believe Cory tagged your GitHub account since it matches [PyPI user "cntrlr"](https://pypi.org/user/cntrlr/) which sounds like it's not you, if that's the case please disregard this issue 🙂 

 I already tried contacting the owner via email and am waiting for a response.

**Comment by Cntrlr** [comment]
I already did check all my accounts and this is not mine for sure. I hope this case will be resolved quickly. Good luck!

**Comment by yeraydiazdiaz** [comment]
@nijel I've tried emailing the owner of the package but the address is now deactivated so the project can now be considered abandoned.

I will ask an admin to proceed to transfer ownership to you.

**Comment by ewdurbin** [comment]
transfer complete.

**Comment by nijel** [comment]
Thanks!
