### ISSUE TITLE
PEP 541: ownership of the 'some' package

### ISSUE THREAD

**Issue by anowlcalledjosh** [pypa/warehouse#4878]
I believe that the [some](https://pypi.org/project/some/) package on PyPI should be considered invalid per PEP 541:

> A project published on the Package Index meeting ANY of the following is considered invalid and will be removed from the Index:
>
> - project is name squatting (package has no functionality or is empty);

since the package has exactly one release (over two years ago), consisting of a setup.py that contains only a description, an email address, and a URL for the home page (which doesn't exist, not even in archive.org), and no other meaningful files.

Please could ownership of the name be transferred to me so I can publish my own [some](https://github.com/anowlcalledjosh/some) package? My PyPI username is anowlcalledjosh.

I contacted the uploader via the email address listed in the package on the 15th of October, but have not received a reply.

**Comment by yeraydiazdiaz** [comment]
Hi @anowlcalledjosh, apologies for the delay in processing this request.

The project is indeed invalid so we will proceed to transfer it if you are still interested.

**Comment by anowlcalledjosh** [comment]
No worries! I'm still interested in using that name, yep.

**Comment by ewdurbin** [comment]
complete.
