### ISSUE TITLE
PEP 541: Requesting ownership transfer of package name "Qt"

### ISSUE THREAD

**Issue by empyrical** [pypa/warehouse#4885]
The package in question:

https://pypi.org/project/Qt/

It appears to be a package that has been registered, but has no releases. As a result, it has no information page on it and I have no way of contacting its current owner.

I am reaching out to see if this package name could possibly be released for the [Qt for Python](https://wiki.qt.io/Qt_for_Python) project. Right now, it's still on its old `PySide2` package name, but a future package name change is in the cards, and I think just "`qt`" would be the best  and shortest option.

My PyPi username is `empyrical`. If the username can be released, I'll bring this up with the QfP team and add them to it.

**Comment by yeraydiazdiaz** [comment]
Hello @empyrical, apologies for the delay in processing this request.

The project page indeed has no releases so it can be transferred if you are still interested.

**Comment by empyrical** [comment]
Hey!

> apologies for the delay in processing this request.

No problem! :)

> it can be transferred if you are still interested.

Yes, I am still interested.

**Comment by di** [comment]
Confirmed that `qt` is an invalid project, and have added `empyrical` as an owner.
