### ISSUE TITLE
Increase size limit request

### ISSUE THREAD

**Issue by ibarbech** [pypa/warehouse#4887]
Hey folk,

I would like to ask you to increase the size limit for the package "learnbot-dsl" to 80 MB
I need upload a file.data to the project run successfully.
[https://pypi.org/project/learnbot-dsl/](https://pypi.org/project/learnbot-dsl/)
Thx you in advance =)

**Comment by ibarbech** [comment]
Can you notify me if the size limit has been extended?

Thank you

**Comment by di** [comment]
I've set the upload limit for `learnbot-dsl` to 100 MB on PyPI.

**Comment by ibarbech** [comment]
Thank you.
