### ISSUE TITLE
 File size limit increase request

### ISSUE THREAD

**Issue by zijwang** [pypa/warehouse#4896]
Hi, 

I am working on a [package](https://test.pypi.org/manage/project/genderperformr) as a code/model release for one of my papers. I wanted to include two pytorch models discussed in the paper, which are relatively large. 

The size of your release: 98MB
Index: TestPyPI and (later) PyPI

Thanks in advance!

**Comment by di** [comment]
I've set the upload limit for `genderperformr` to 100 MB on TestPyPI. You'll need to create a release of the project on PyPI before I can increase the limit.

**Comment by zijwang** [comment]
@di I have created a release also on PyPI. Please see whether you could increase the limit now. Thanks!

**Comment by di** [comment]
I've set the upload limit for `genderperformr` to 100 MB on PyPI.
