### ISSUE TITLE
cleanup all users in db

### ISSUE THREAD

**Issue by mkaja** [pypa/warehouse#4900]
we are cloning warehouse and creating an internal one for our environment- we are trying to get rid of all users - is there any easy way to do it ?
bcrypt$$2a$16$xq9g/NAFoiOtFkGpk/kgjOiPDPs1/pMG0GHeDHWHSOd9IY7Fah.yC	2018-08-03 17:03:32.861842	f	Henryhat		f	f	2018-08-03 17:03:32.861842	9	2018-08-03 16:38:13.55536	8aa5b520-6325-4b7c-ac92-4306ebad9397
bcrypt$$2a$16$xq9g/NAFoiOtFkGpk/kgjOiPDPs1/pMG0GHeDHWHSOd9IY7Fah.yC	2018-08-03 17:03:32.861842	f	Jacalyneagensils		f	f	2018-08-03 17:03:32.861842	e	2018-08-03 16:38:13.55536	6af7184d-2260-49e3-ab13-bf740d77b4bc
bcrypt$$2a$16$xq9g/NAFoiOtFkGpk/kgjOiPDPs1/pMG0GHeDHWHSOd9IY7Fah.yC	2018-08-03 17:03:32.861842	f	uyuutosa		f	t	2018-08-03 17:03:32.861842	6	2018-08-03 16:38:13.55536	9d870024-7f02-4824

**Comment by di** [comment]
Nope, we don't support or recommend using Warehouse for anything but being https://pypi.org.

You might be better off using a 3rd party tool, see:
* https://packaging.python.org/guides/index-mirrors-and-caches/
* https://packaging.python.org/guides/hosting-your-own-index/
* There are also many for-profit options available like Artifactory, GemFury, etc.
