### ISSUE TITLE
Request for package size increase for tf-nightly-gpu-2.0-preview tf-nightly-2.0-preview

### ISSUE THREAD

**Issue by annarev** [pypa/warehouse#4904]
Can we get package size increase for tf-nightly-gpu-2.0-preview and tf-nightly-2.0-preview packages? Specifically, we are requesting the following size limits:
tf-nightly-gpu-2.0-preview: 360M (current size of our wheel is a little over 300M)
tf-nightly-2.0-preview: 100M (current size of our wheel is at 80MB)

(As a note, we are deprecating tf-nightly-xla-gpu package, which I requested package size increase earlier - #191 (comment). I am going to delete all of its versions.)

**Comment by di** [comment]
I've set the limit for `tf-nightly-gpu-2.0-preview` to 400MB  and set the limit for `` to 100MB on PyPI.
