### ISSUE TITLE
Potential malicious packages/name squatting

### ISSUE THREAD

**Issue by timkpaine** [pypa/warehouse#4916]
These three packages look like forks of the corresponding packages (without the 3 appended), and have identical PyPI homepages except for the maintainers field. It doesn't look like theres any malicious code yet, but it would be super easy to do so and keep the home page looking "authentic". 

https://pypi.org/project/empyrical3/
original:
https://pypi.org/project/empyrical/

https://pypi.org/project/pyfolio3/
original:
https://pypi.org/project/pyfolio/

https://pypi.org/project/cufflinks3/
original:
https://pypi.org/project/cufflinks/

**Comment by dhirschfeld** [comment]
Even if it's not actively malicious it's too easy for even experienced users to be confused and end up installing code they didn't mean to. `cufflinks3` `0.14.5` is ***not*** the same code as `cufflinks` `0.14.5` so it should be very clear to users that this is the case.

This is exacerbated by the fact that a number of the packages aren't forks of the upstream repo but are instead wholesale copies such that there is no easy way to view what changes have been made. 

Whilst the code is open source and so people are free to fork a project it should be made very clear that it is a fork and the author should be change to reflect that fact:
https://github.com/liudengfeng/cufflinks/blob/1f655392f822c6aaebbd24d3c49b9dcd7f55e2be/setup.py#L12-L13

IMO simply adding a `3` to the name is absolutely not good enough and makes this an instance of typo-squatting.

If @liudengfeng wants to publish their forked packages then they should rename them to something easily distinguishable as being different code - e.g. a prefix of `ldf-` *might* be acceptable to distinguish the package whilst still showing it's lineage.

Even if the package is renamed I would still require that the PyPI page clearly state that it is a fork of the upstream repo

**Comment by dhirschfeld** [comment]
As it is, I think they should be removed.

**Comment by timkpaine** [comment]
also in most cases where forking occurs, the previous package is no longer maintained, and the new package makes it very clear that it is distinct from the original.

**Comment by di** [comment]
This has been resolved, as far as the potential for typo-squatting goes.

If individual projects still have an issue with the forks, they need to take that up with the maintainer directly.
