### ISSUE TITLE
PEP 541: Claiming the fixlib package

### ISSUE THREAD

**Issue by djc** [pypa/warehouse#4917]
I'm the original author of the [fixlib](https://pypi.org/project/fixlib/) package, from when I was working for a now-wound down startup. As such, the email address, homepage and original repository are no longer accessible -- and the last release dates from 2010.

I'd like to reclaim ownership with my personal PyPI account (djc) in order to upload a newer release that has a number of fixes (new repository is [on GitHub](https://github.com/djc/fixlib)).

**Comment by yeraydiazdiaz** [comment]
Hello @djc, sorry for the delay in processing this request.

I will now contact the administrators to change ownership of the package to your new PyPI user.

**Comment by djc** [comment]
@yeraydiazdiaz thank you!

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by djc** [comment]
Thank you!
