### ISSUE TITLE
Claim name of removed package "acid"

### ISSUE THREAD

**Issue by ekohilas** [pypa/warehouse#4919]
Hi PyPi,

I would like to claim the package name "acid".
I understand that [PEP541](https://www.python.org/dev/peps/pep-0541/) has been accepted and a system for this is in the works however I would like to enquire regardless as all the current issues that are to do with packages that are still existing on pypi.org

As far as I understand, this package has been removed, and is nowhere to be found, nor a user to be contacted. The [package url](https://pypi.org/project/acid/) 404's and pip reports: 
```
python -m pip install acid
Collecting acid
  Could not find a version that satisfies the requirement acid (from versions: )
No matching distribution found for acid
```

Seeing as this is a removed project whose name cannot be re-registered, is there anything that can be done now or will I have to wait?

**Comment by yeraydiazdiaz** [comment]
Hello @ekohilas, apologies for the delay in processing this request.

As you mention the package is invalid as the original owner deleted all releases in 2014.

Can you confirm your PyPI username to complete the transfer, please?

**Comment by ekohilas** [comment]
Hi @yeraydiazdiaz, thank you for your reply!

My pypi username is `ekohilas`,
apologies for not including it earlier.

Cheers,
Evan.

**Comment by di** [comment]
Confirmed that `acid` is an invalid project, and have added `ekohilas` as an owner.
