### ISSUE TITLE
Transfer ownership of abandoned hyperwallet-sdk package

### ISSUE THREAD

**Issue by gmeyer-hw** [pypa/warehouse#4922]
I would like to request to transfer ownership of https://pypi.org/project/hyperwallet-sdk/ to myself (gmeyer - pypi.org  account).  The maintainer no longer release new versions on PyPI repository since Oct 11, 2017, to the version 1.1.1 and I’ve pushed some new features in the git repository (https://github.com/hyperwallet/python-sdk) and I would like to publish the most recent implementations.

**Comment by jamadden** [comment]
Have you attempted to contact the PyPI maintainer, who would appear to be @dharrison-hw? Or using the listed contact address at devsupport@hyperwallet.com ?

**Comment by gmeyer-hw** [comment]
I've tried to contact @dharrison-hw but he no longer works for Hyperwallet and he doesn't have access to PyPI account.  This is the main reason I claimed the ownership of the Hyperwallet-SDK.  
And this email devsupport@hyperwallet.com is our product support email.

**Comment by gmeyer-hw** [comment]
I've tried to contact @dharrison-hw but I don't have any answered.
