### ISSUE TITLE
Transfer of ownership of image-match package

### ISSUE THREAD

**Issue by rhsimplex** [pypa/warehouse#4938]
Hi,

I am the original author of [image-match](https://pypi.org/project/image-match/) , requesting transfer of Pypi ownership from ascribe to myself (username: rhsimplex).

Current github: https://github.com/EdjoLabs/image-match
Former github: https://github.com/ascribe/image-match (note the redirect)
Troy McConaghy, @ttmc, an administrator at ascribe, can confirm the transfer of ownership and that the ascribe pypi access keys have been lost.

cc: @excerebrose

**Comment by rhsimplex** [comment]
@jamadden Thanks, any way to get this moving?

**Comment by yeraydiazdiaz** [comment]
Hello @rhsimplex, apologies for the delay in processing this request.

The `ascribe` user is the owner of [other projects as well](https://pypi.org/user/ascribe/), the best course of action in my opinion would be to reset the password for the user to regain control over all the projects and have the owner transfer them accordingly.

Would @ttmc be able to do that? We're happy to assist in any way.

**Comment by rhsimplex** [comment]
I believe the access keys have been lost and the original maintainer of the ascribe organization is long gone, @ttmc can you confirm?

**Comment by yeraydiazdiaz** [comment]
Hi @rhsimplex, given @ttmc has not responded and you appear as the contact email, I will now contact an administrator to proceed to adding your PyPI user`rhsimplex` as an owner of the `image-match` project.

**Comment by rhsimplex** [comment]
Thank you very much @yeraydiazdiaz =)

**Comment by ewdurbin** [comment]
`rhsimplex` added as Owner.

**Comment by ttmc** [comment]
Hi, sorry I didn't reply sooner. Yes, this change is fine with me.
