### ISSUE TITLE
Transfer of ownership and conversion to lowercase of the Monero package

### ISSUE THREAD

**Issue by emesik** [pypa/warehouse#4966]
As I signaled before in #2859, the `Monero` package name [has been squatted](https://pypi.org/project/Monero/). Nine months have passed since its creation and no working code appeared since then.

I'm a developer of the `monero-python` package which already had 9 releases:
* Github: https://pypi.org/project/monero-python/
* PyPi: https://github.com/emesik/monero-python

I'd like to get rid of the `-python` suffix, which is obviously redundant in PyPi, and move it to lowercase `monero`.

**Comment by ewdurbin** [comment]
Done. Please note that you won't be able to make a release with the version 0.1 as this was previously used.

**Comment by ewdurbin** [comment]
Also, note that you can change the display case when uploading your first release by setting the name appropriately in the metadata sent to create the release.
