### ISSUE TITLE
PEP 541: ownership of the 'exp' package

### ISSUE THREAD

**Issue by davidenunes** [pypa/warehouse#4968]
I would like to take over package "[exp](https://pypi.org/project/exp/)", which under PEP 541 is an "Invalid Project", I would like to publish my own package with the same name.

The package was "released" in [Jul 5, 2018](https://pypi.org/project/exp/#history), but it is empty, the project homepage does not exist, and I couldn't find any contact from the maintainer to contact him. The package doesn't contain any e-mail, nor does the [author](https://pypi.org/user/vmalloc/) homepage.

my pypi username: [davidenunes](https://pypi.org/user/davidenunes)

thanks in advance

**Comment by jamadden** [comment]
It appears that the PyPI author might be the github user @vmalloc based on the repo links in their other repositories. Have you tried pinging them to ask for a transfer?

**Comment by davidenunes** [comment]
I found that as well and tried to find the @vmalloc contact on his personal webpage, but no e-mail to be found, any recommendation ?

**Comment by vmalloc** [comment]
Hi, yeah it's me... I released it more or less by mistake (was looking for a project name and tried it without picking up on it).

I can release it if you want - what is the process for doing this and making sure it gets transferred to @davidenunes ?

**Comment by di** [comment]
@vmalloc You'll need to go to https://pypi.org/manage/project/exp/collaboration/ and add `davidenunes` as an "Owner".

**Comment by davidenunes** [comment]
Hi, thanks for your response @vmalloc , I didn't know how to contact you without creating an issue somewhere :) I appreciate it.

**Comment by vmalloc** [comment]
Done!

**Comment by davidenunes** [comment]
confirmed :+1:, thanks @vmalloc and everyone :)
