### ISSUE TITLE
Update list of directories in documentation

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#4969]
The high-level "how this application works" documentation in https://warehouse.readthedocs.io/application/#file-and-directory-structure has a list of "Directories within the repository" that needs refreshing. 

Look at the directory structure within `warehouse/` and update the text in `docs/application.rst`.

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: *If your pull request makes a visual change*, include a screenshot of your update. This helps our team give you feedback faster.

**Comment by melsyt** [comment]
I alphabetized the list and added the following: 

- emails
- metrics
- search

I put down my best guess for short descriptions (not sure what to say for search..). Happy to update the doc if I can get some suggestions! 

<img width="740" alt="file_dir" src="https://user-images.githubusercontent.com/42623406/47619773-a280fc80-dab8-11e8-9544-cdc3983f14db.png">
