### ISSUE TITLE
Request trove classifier for Hypothesis

### ISSUE THREAD

**Issue by Zac-HD** [pypa/warehouse#4973]
Request to add a new Trove classifier, `Framework :: Hypothesis` for the [Hypothesis](https://hypothesis.works/) testing ecosystem.

### Why do you want to add this classifier?

There are already tens of packages on PyPI that extend Hypothesis, by providing custom strategies or integrating with another framework (here's [a curated subset](https://hypothesis.readthedocs.io/en/latest/strategies.html)).  I estimate that there are 30-60 packages already on PyPI that could use this new classifier.

This classifier request is prompted by HypothesisWorks/hypothesis#1661, which observes - in my experience correctly - that it is increasingly difficult to distinguish packages that *extend* Hypothesis from those that simply *use* Hypothesis with keyword or dependency searches.  A new trove classifier `Framework :: Hypothesis`, like `Framework :: Pytest`, would make it much easier to search for Hypothesis extensions and integrations.

**Comment by di** [comment]
I've added this classifier.

**Comment by Zac-HD** [comment]
Thanks @di - much appreciated!
