### ISSUE TITLE
Requesting ownership of invalid `vx` package

### ISSUE THREAD

**Issue by paulmelnikow** [pypa/warehouse#5002]
The [vx package](https://pypi.org/project/vx/) appears to be invalid. It was published once, and is empty.

I sent @matkallada an email on October 2 asking if he would transfer the name, and followed up twice, but did not hear back.

The project I would like to publish is currently at https://pypi.org/project/vector-shortcuts/, though it's traditionally been imported as `vx`.

Thanks so much!

**Comment by MatKallada** [comment]
@paulmelnikow I never received any e-mails from you. Which e-mail did you send it to?

**Comment by paulmelnikow** [comment]
Thanks for responding!

I sent it to mattkallada@gmail.com… which it looks like I misread from your website. One t, not two. Sorry about that!

Here's what I sent:

> Hi Matt!
> 
> I’m breaking out a piece of a library called blmath, and it contains vector shortcuts for linear algebra. It’s traditionally used from the `vx` namespace:
> 
> https://github.com/metabolize/blmath/blob/master/blmath/numerics/vector_shortcuts.py#L7
> 
> A natural place to publish the library would be at `vx`, which I noticed you have registered as a test library and don’t seem to be using:
> 
> https://pypi.org/project/vx/0.1/
> 
> Would you be willing to transfer the name over to me?
> 
> All best,
> Paul

**Comment by paulmelnikow** [comment]
These packages are identical, and were published in the last hour:

1. https://pypi.org/project/force/0.1.1/#history
2. https://pypi.org/project/vortex/0.1.1/#history
3. https://pypi.org/project/vx/0.1.1/#history

I'm surprised at this response to my post! PEP 541 does not allow name squatting.

**Comment by MatKallada** [comment]
@paulmelnikow 

These names are in use and absolutely aren't name squatting. Frankly, I'm a bit appalled at your request. I've updated them accordingly with my updated e-mail information.

As per the PEP 541 regulations, I amicably encourage you to look for another name. I do understand where you are coming from and I know how this can be frustrating. I wish you all the best for your project.

**Comment by yeraydiazdiaz** [comment]
Hello @paulmelnikow, I'm closing this issue since @MatKallada has stated his intention of keeping the project name.
