### ISSUE TITLE
pypi shows old package version number

### ISSUE THREAD

**Issue by johny-c** [pypa/warehouse#5003]
Hi all, I'm author/maintainer of the package [pylmnn](https://github.com/johny-c/pylmnn). I updated my package and uploaded the new versions to pypi. When I search for the package on [pypi.org](https://pypi.org/search/?q=pylmnn), I see an old release number next to the package name (1.5.2), but after clicking I can see the new versions. Same with pip, when I search, I see the old version number, but when I install, the latest version is installed. This also results in this confusing message from pip:
`PyLMNN (1.5.2)  - Large Margin Nearest Neighbor implementation in python`
`INSTALLED: 1.6.2`
`LATEST:    1.5.2`

**Comment by johny-c** [comment]
Seems to be fixed now for my package.

**Comment by yeraydiazdiaz** [comment]
Closing as it seems to be fixed.
