### ISSUE TITLE
"pkg_resources.DistributionNotFound: warehouse==15.0.dev0" during migration

### ISSUE THREAD

**Issue by karan** [pypa/warehouse#501]
I am trying to setup the dev env using https://warehouse.readthedocs.org/development/getting-started/.

These worked just fine:

```
$ docker-compose run web psql -h db -d postgres -U postgres -c "CREATE DATABASE warehouse ENCODING 'UTF8'"
$ xz -d -k dev/example.sql.xz
$ docker-compose run web psql -h db -d warehouse -U postgres -v ON_ERROR_STOP=1 -1 -f dev/example.sql
$ rm dev/example.sql
```

However, running the last statement (migration) throws an exception

```
$ docker-compose run web warehouse -c dev/config.yml db upgrade head
Starting warehouse_db_1...
Starting warehouse_redis_1...
Traceback (most recent call last):
  File "/usr/local/bin/warehouse", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: warehouse==15.0.dev0
```

Tried `docker-compose build` to rebuild the image, but nothing changed.

Anyone knows why this is happening and how to solve it?

I'm on OS X 10.10.2 with py2.7.9 and py3.4.2 on system.

**Comment by dstufft** [comment]
Try doing:

``docker-compose run web pip install -e .``

**Comment by karan** [comment]
Great!

That worked.

Now running `docker-compose up` runs the servers but the app still doesn't work. 404 on boot2docker ip address.

![image](https://cloud.githubusercontent.com/assets/3261985/7216260/fa1b2a00-e5ad-11e4-8179-991cfa35200a.png)

**Comment by dstufft** [comment]
There's no index view currently (see #492), try ``/project/jasmin/``.

**Comment by karan** [comment]
AHa! Got it to work.
