### ISSUE TITLE
Transfer ownership of "Deluge"

### ISSUE THREAD

**Issue by cas--** [pypa/warehouse#5010]
I am the lead developer of [Deluge](http://deluge-torrent.org/) and was attempting to upload it to pypi but I have found that `igor.fraa` (un)helpfully uploaded a single development version https://pypi.org/project/deluge/#history several years ago. I don't know who they are, they are not part of the Deluge team, and I have no way of contacting them to claim ownership.

I am looking to release Deluge and point users to pypi and it would be very annoying if users find `pip install deluge` is installing an ancient version.

**Comment by cas--** [comment]
Has anyone started the process? I am reliant on PyPi maintainers fixing this.

Also waiting six weeks seems excessive, in this instance the maintainer has clearly abandoned it and is our project code.

**Comment by cas--** [comment]
@igorfraa Are you the same user as `igor.fraa` on PyPi?

**Comment by igorfraa** [comment]
> @igorfraa Are you the same user as `igor.fraa` on PyPi?

Hello @cas-- , yes it was me. I have spent some time with porting Deluge to GTK3 but later abandoned this work. 

I've just removed the project from pypi, so please go ahead with releasing.

**Comment by cas--** [comment]
Excellent, thanks for that!
