### ISSUE TITLE
New packages not appearing in pypi.org/simple index

### ISSUE THREAD

**Issue by matthewwardrop** [pypa/warehouse#5017]
**Describe the bug**
I recently uploaded a new package to the PyPI (https://pypi.org/project/adnotatio-server/), and it successfully appears at https://pypi.org/simple/adnotatio-server/, but not in the index at https://pypi.org/simple/. Prior to today, packages uploaded in this manner appear in this index straight away, so I am not sure if there is something going on with the index cache. I have checked on some other new packages, and they seem to be experiencing this also.

Note that installation via `pip` still works fine, but if the package does not appear in this index, mirrors and proxies of the pypi index cannot pick up the package.

**Expected behavior**
The package (`adnotatio-server`) should appear in the global list of packages.

**To Reproduce**
`$ curl https://pypi.org/simple/  | grep adnotatio-server`

**Comment by di** [comment]
This seems to be resolved now, and we've had other reports of stale caches (like #4892) so I'll close this as a duplicate. Thanks for the report!
