### ISSUE TITLE
Restore access to account David.Pursehouse

### ISSUE THREAD

**Issue by dpursehouse** [pypa/warehouse#5026]
I am unable to log in due to the error `This password appears in a breach or has been compromised and cannot be used`.

I've submitted a reset request via the website, but have not received the email.

I suspect the problem is that the email address on the account is one that I no longer have access to (it's at my previous employer and I probably forgot to change it when I moved).

**Comment by dpursehouse** [comment]
Update: I confirmed that the account has the old email address.  Requesting a reset with my current email address failed, but requesting with the old email address went through OK (although I no longer have access to it, so can't complete the reset).

**Comment by di** [comment]
@dpursehouse Please email me at `di@python.org`.
