### ISSUE TITLE
Use Pyramid "pshell" for warehouse shell

### ISSUE THREAD

**Issue by domenkozar** [pypa/warehouse#504]
See http://pyramid.readthedocs.org/en/latest/narr/commandline.html#extending-the-shell

Using `pshell` eases the whole setup of Configurator.

**Comment by dstufft** [comment]
I'm going to close this, there doesn't appear to be a way to use ``pshell`` that doesn't involve using an ``.ini`` file, and we don't have one of those (nor do we need one).
