### ISSUE TITLE
Add actual date and time to 'timeago' dates

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#5085]
As per feedback here:

Right now, we display a humanized version of the date / time.  

As per feedback here: https://github.com/pypa/warehouse/pull/4402#issuecomment-410383106

> sometimes, I forget when I have released my package since I have 40+ packages. So I resorted to look at pypi for more info. However, github releases and pypi at moment both love moment.js and also give some time ago. Still I could not find the exact date when a version is released.

For this, I think we should add a tooltip that shows *on hover*, e.g.

![screenshot from 2018-11-18 15-14-36](https://user-images.githubusercontent.com/3323703/48674475-b3b3ab00-eb44-11e8-9c7c-6501914206b6.png)

The datetime in the tooltip should follow an international format, e.g `YYYY-MM-DD hh:mm`

this would also solve https://github.com/pypa/warehouse/issues/3010 by providing both a "human friendly" format and technical format.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: Please include a screenshot of your update. This helps our team give you feedback faster.

**Comment by darkHarry** [comment]
Hi! This is my first time contributing to warehouse and I'd like to work on this issue.
I couldn't find any project with very recent release history in the dev environment hence there is no "4 min ago" or "about 4 hours ago".
**Screenshot:**
![tooltip](https://user-images.githubusercontent.com/20538494/50300685-2947c980-04ab-11e9-88fa-79cf650cc6eb.jpg)

**Comment by di** [comment]
Hey @darkHarry, thanks for working on this. Indeed, the packages in the dev environment will be a few weeks old. You'll need to either:

* manually change the creation date via [the interactive shell](https://warehouse.pypa.io/development/getting-started/?highlight=shell#running-the-interactive-shell)
* [upload a new package to your development instance with `twine`](https://warehouse.pypa.io/development/reviewing-patches/?highlight=twine#testing-with-twine)

Let us know if you have any issues with either of these.

**Comment by di** [comment]
(Also, it would be great to include a time zone with the full datetime as well!)

**Comment by darkHarry** [comment]
I just checked the Project's release created datetime object and it's tzinfo (time zone info) attribute is None. So, I don't see any way to fetch the time zone. Any other place to look for it?

**Comment by dstufft** [comment]
Pretty sure we store everything in the database using UTC.

**Comment by darkHarry** [comment]
Hi @di! 
I realized whilst browsing pypi that the tooltip is in UTC which isn't convenient for different timezone users.
It would be better to localize it while displaying improving UX.

**Comment by darkHarry** [comment]
yeah, sure.
