### ISSUE TITLE
"Invalid Date" displayed in Safari

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#5087]
**Describe the bug**

When viewing release history in Safari 12.0.1 on MacOS 10.13.6 dates are rendered as `Invalid Date`.

![screen shot 2018-11-19 at 9 54 03 am](https://user-images.githubusercontent.com/1200832/48720436-ae5e6b00-ebed-11e8-838b-5ef5d60c9ecb.png)

**Expected behavior**

New localized macros added in #5041 should render a humanized/localized date.

**To Reproduce**

View https://pypi.org/project/pip/#history in an affected browser.

**My Platform**

MacOS 10.13.6
Safari 12.0.1

**Additional context**

Ensured JavaScript execution is enabled, no errors in console.

**Comment by nlhkabu** [comment]
@yeraydiazdiaz would you be able to look into this one?

**Comment by yeraydiazdiaz** [comment]
Sure thing
