### ISSUE TITLE
Requesting ownership transfer of package "django-autoslug"

### ISSUE THREAD

**Issue by justinmayer** [pypa/warehouse#5088]
Hi folks. I am the maintainer of [django-autoslug](
https://github.com/justinmayer/django-autoslug). The original author, @neithere, was kind enough to transfer the project to me but forgot to do the same for the PyPI package.

GitHub repo transfer confirmation:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/1503700/48733408-3b162280-ec08-11e8-94e8-e6ec064b9094.png">

[Multiple contact attempts](
https://github.com/justinmayer/django-autoslug/issues/49#issuecomment-416552564) over several months have not yielded any responses, and therefore I haven't been able to issue a new release containing compatibility support for recent versions of Django.

Could you help transfer ownership of this package? My PyPi username is: `jmayer`

**Comment by di** [comment]
I've added `jmayer` as an owner of `django-autoslug`.
