### ISSUE TITLE
Transfer ownership for package "ABBA"

### ISSUE THREAD

**Issue by gostevehoward** [pypa/warehouse#5095]
Hi, I uploaded the package [ABBA](https://pypi.org/project/ABBA/) under a PyPI account `Steve.Howard` registered to my email at my previous company. I have long since lost access to that email account. I do have control of the [GitHub repository](https://github.com/thumbtack/abba) under this GitHub account (`gostevehoward`). Can you transfer ownership of the "ABBA" package to my new PyPI username `gostevehoward`? A user posted a message to our repo about Python 3 incompatibility and I wanted to put an updated version on PyPI. Let me know if I can help, and sorry for the inconvenience.

**Comment by yeraydiazdiaz** [comment]
Hi @gostevehoward, I will now contact the administators to transfer the project to your new PyPI user.

Btw, best project name ever 😄

**Comment by gostevehoward** [comment]
Thank you so much for your help @yeraydiazdiaz !

**Comment by ewdurbin** [comment]
Transfer complete.

**Comment by gostevehoward** [comment]
Thank you @ewdurbin !
