### ISSUE TITLE
New Masonite Trove Classifier

### ISSUE THREAD

**Issue by josephmancuso** [pypa/warehouse#5112]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: Masonite`

## Why do you want to add this classifier?

I would like to add this classifier for the Masonite framework in order to better categorize it on PyPi for other developers. There is currently no classifier like this once but there are plenty for other frameworks. Currently I expect around 15 projects to be able to use this classifier as well as all Masonite packages in the future both official and unofficial.

Thank you :)

**Comment by josephmancuso** [comment]
Here is a link to the framework: [Masonite](https://github.com/masoniteframework/masonite)

**Comment by ewdurbin** [comment]
All set!
