### ISSUE TITLE
PEP 541: transfer ownership of unmaintained `smpplib`

### ISSUE THREAD

**Issue by eigenein** [pypa/warehouse#5122]
Hi,

We, @eigenein and @podshumok, would like to transfer ownership of the name [`smpplib`](https://pypi.org/project/smpplib/) to both of us. The current PyPI package is just a copy from SourceForge to GitHub and is not maintained since **2010**. [The related repo](https://github.com/takinbo/smpplib) is also not maintained since that and has only **1** star and **1** fork.

On the other hand, [our repo](https://github.com/python-smpplib/python-smpplib) is forked from the same codebase, actively maintained and has **50** stars and **76** forks. In the [related issue](https://github.com/python-smpplib/python-smpplib/issues/45) there're also users who are asking us to publish our package to PyPI.

We've reached @takinbo in private, asked for ownership transfer and got a refusal. This doesn't seem like a good situation to have drastically outdated package on PyPI while having an active repo, and doesn't seem to contribute to a healthier community. Could you step in please?

References #1506.

**Comment by takinbo** [comment]
I raised a [concern](https://github.com/dominictarr/event-stream/issues/116) about passing on the name of the version of the package that I maintain and they weren't addressed or responded to. I also mentioned in my response to @eigenein that I was happy to receive a PR but for some reason, he only wanted the name for his fork of the project.

Considering the fact that his team has in deed, made updates on the library and are actively maintaining it, I'm happy to release the name provided there are assurances about the security implications. Are there recommendations on how to handle change of maintainers for PyPI packages?

**Comment by eigenein** [comment]
> I raised a concern about passing on the name of the version of the package that I maintain and they weren't addressed or responded to.

The concern is raised for a different tech stack. There're also version pinning and `pip` hash checking mode already in place to address it.

> I also mentioned in my response to @eigenein that I was happy to receive a PR but for some reason, he only wanted the name for his fork of the project.

I'm very sorry and I didn't want to say that last time, but "some reason" is a common sense to have the package administered by its actual maintainers. What you say is: "Just because I have acquired the name earlier, your contributions will be published exceptionally through me and under my name". I'm sorry if it may sound rude.

I've raised the issue to get PyPI administrators involved into that because obviously we can not agree and it's time to get it managed officially according to the current guidelines.

CC: @podshumok

**Comment by podshumok** [comment]
Hello @takinbo!
What kind of assurances do you expect? For a few years now we are helping people with their issues with the library, we are fixing bugs, reviewing and accepting PRs. This is public activity, one can just visit the repository and see who is doing what. Thanks to community efforts library has now a non-blocking mode and simple tests with CD, README, a way to keep persistent message_ids, python3 support, helpers for Unicode multipart messages.
Google search for smpplib points to our version. Third-party tutorials have direct instructions to not `pip install smpplib` and to clone our repository instead or do `pip install git+https://github.com/podshumok/smpplib`. "smpplib" questions on stackoverflow are also about using our fork.
One of the issues we are facing IRL is that people are installing your fork with `pip` thinking that they are going to get all the features I mentioned above. (hence download statistics you see for your package). But just in case we will leave your version there so people still will be able to install it if the want to.
PyPI don't support PRs and porting every single PR we had to your fork is unrealistic.
Changing package maintainer with new pypi is easy - just login - open Your projects, pick smpplib and change maintainers. Please don't hesitate to ask any (more) specific questions if you have them.
My nickname there is the same - `@podshumok`.

I hope we all are on the same page here and in 2019 devops and developers who need python-smpplib will get a simple and intuitive way to install the library. HNY!

**Comment by takinbo** [comment]
Thanks @podshumok for the detailed explanation. I never intended to squat on the name and I'm actually glad the project is being maintained. I'll work on the change of maintainers on the package. HNY!

**Comment by jeking3** [comment]
If the maintainership and ownership has been addressed, can this be closed?

**Comment by podshumok** [comment]
I do have access

**Comment by podshumok** [comment]
Thank you all for you time :)
