### ISSUE TITLE
Increase our project limit size

### ISSUE THREAD

**Issue by aslepko** [pypa/warehouse#5123]
We are about to release nGraph, Intel’s high performance Neural Network Compiler.
https://github.com/NervanaSystems/ngraph/

We would like to release our binary packages on PyPI. The complete package for nGraph is slightly above 100MB, due to a number of compiled dependencies, so we would like to request an increase of the file size limit on the following projects to 150 MB:

The name of the project: `ngraph-core`
The size of your release, in megabytes: 150MB
Which index/indexes you need the increase for (PyPI, Test PyPI, or both): both

The name of the project: `ngraph-tensorflow`
The size of your release, in megabytes: 150MB
Which index/indexes you need the increase for (PyPI, Test PyPI, or both): both

The name of the project: `ngraph-mxnet`
The size of your release, in megabytes: 150MB
Which index/indexes you need the increase for (PyPI, Test PyPI, or both): both

The name of the project: `ngraph-onnx`
The size of your release, in megabytes: 150MB
Which index/indexes you need the increase for (PyPI, Test PyPI, or both): both

**Comment by ewdurbin** [comment]
Hi @aslepko! Projects must be registered on the index before we can update their limit. If you can upload source distributions for your initial releases to both testpypi and pypi the limits can be updated for you to upload your binary releases.

Once you've uploaded releases for all of the projects, reply to this issue.

**Comment by aslepko** [comment]
Hi @ewdurbin , we just uploaded initial packages to test.pypi and pypi. One of the project names has changed, the request to increase the upload limit remains the same, however, for all projects. The project names are:
ngraph-tensorflow-bridge, ngraph-mxnet, ngraph-core, ngraph-onnx
Thanks a lot!

**Comment by ewdurbin** [comment]
all set!
