### ISSUE TITLE
Increase size limit for Intel's cpu-optimized tensorflow packages

### ISSUE THREAD

**Issue by ashahba** [pypa/warehouse#5126]
Hi @dstufft, I'm an engineer working on Intel cpu-optimized packages for TensorFlow. I was wondering if it would be possible to get a size increase for the following packages on upload.pypi.org/ and test.pypi.org/?

```
intel_tensorflow-1.11.0-cp27-cp27mu-linux_x86_64.whl ==> 125MB
intel_tensorflow-1.11.0-cp34-cp34m-linux_x86_64.whl ==> 125MB
intel_tensorflow-1.11.0-cp36-cp36m-linux_x86_64.whl ==> 125MB
intel_tensorflow-1.11.0-cp35-cp35m-linux_x86_64.whl ==> 125MB
```

so that we can upload them to where `mkl` project is hosted here: https://pypi.org/project/mkl
Thanks!

**Comment by ashahba** [comment]
This is related to https://github.com/pypa/packaging-problems/issues/206

**Comment by ashahba** [comment]
Thanks @jamadden

**Comment by di** [comment]
Hi @ashahba, I'm confused, is your project called `mkl` or is it called `intel_tensorflow`?

**Comment by s1113950** [comment]
We have an `mkl` account right now but the package we would like to upload would be `intel_tensorflow`. There should already be an `mkl` package that is separate :smile:

**Comment by di** [comment]
There isn't a project on PyPI called `intel_tensorflow`. You'll need to upload an empty release to create the project first. I'd recommend using version number `0.0.0` and deleting the release afterwards (the project will remain).

**Comment by s1113950** [comment]
Sounds good. Thanks for the help!

**Comment by ashahba** [comment]
@di here is the home of the project: `intel-tensorflow`
https://pypi.org/project/intel-tensorflow/

**Comment by di** [comment]
I've set the upload limit for `intel-tensorflow` to 125MB on PyPI.
