### ISSUE TITLE
Request for size limit increase for cupy-cuda100 package

### ISSUE THREAD

**Issue by kmaehashi** [pypa/warehouse#5137]
Hello,

I would like to request a size limit increase for `cupy-cuda100` package to distribute [CuPy](https://github.com/cupy/cupy) wheels, because it contains dependency libraries (CUDA etc.).
The size of the wheel is currently approx. 300 MB. Could you please increase the limit to 350 MB?

Thanks in advance!

**Comment by jamadden** [comment]
I can't find that package on PyPI currently. In order to adjust size limits, [the package needs to exist](https://github.com/pypa/warehouse/issues/5123#issuecomment-442830428).  Uploading a source distribution (sdist) first will register the project.

**Comment by kmaehashi** [comment]
@jamadden Thank you for the followup.
I already uploaded and deleted the sdist, so the package should be in the database (although https://pypi.org/project/cupy-cuda100/ returns 404). 

----

![screen shot 2018-11-29 at 23 15 15](https://user-images.githubusercontent.com/939877/49227551-ae037280-f42c-11e8-8995-6def93ecd365.png)

**Comment by di** [comment]
I've set the upload limit for `cupy-cuda100` to 350MB on PyPI.

**Comment by kmaehashi** [comment]
Thank you!
