### ISSUE TITLE
Request to increase the onnxruntime-gpu package size limit.

### ISSUE THREAD

**Issue by pranavsharma** [pypa/warehouse#5146]
* A link to your project on PyPI (or Test PyPI) - https://pypi.org/project/onnxruntime-gpu/
   * The size of your release, in megabytes - about 300MB.
   * Which index/indexes you need the increase for (PyPI, Test PyPI, or both) - PyPI
   * A brief description of your project - ONNX Runtime enables high-performance evaluation of trained machine learning (ML) models while keeping resource usage low. Building on Microsoft’s dedication to the Open Neural Network Exchange (ONNX) community, it supports traditional ML models as well as Deep Learning algorithms in the ONNX-ML format. Documentation is available at Python Bindings for ONNX Runtime.
   * Reason for increase: Since our last release we've now implemented many more CUDA kernels in our code and Linux exposes all symbols by default. Hence the increase in the binary size.

Thanks a lot.

**Comment by di** [comment]
I've set the upload limit for `onnxruntime-gpu` to 300MB on PyPI.

**Comment by pranavsharma** [comment]
Thanks a lot for the quick response.
