### ISSUE TITLE
Increase size limit request

### ISSUE THREAD

**Issue by Dapid** [pypa/warehouse#5147]
Hi,

I'd like to request [PconsC4][1]. It is a trained deep learning model that requires 253 MB of storage. I was told [here][2] to request the increased limit here.
Thank you!

   [1]: https://pypi.org/project/pconsc4/
   [2]: https://github.com/pypa/packaging-problems/issues/167

**Comment by ruohoruotsi** [comment]
Did you not ever get your limit?

**Comment by Dapid** [comment]
No.

**Comment by jamadden** [comment]
Apologies for the delay.  The PyPI moderation team wasn't established until January and some tickets in the backlog were missed.

I've set the upload limit for PconsC4 on pypi.org to 300MB.
