### ISSUE TITLE
Progress meter bug fix request

### ISSUE THREAD

**Issue by Cby19961020** [pypa/warehouse#5149]
Hi there I noticed a minor issue with regards to the progress meter feature.
Please refer to Demo_DulipcateFileFinder.py, line 27 
"if not sg.OneLineProgressMeter('Counting Duplicates', idx + 1, total_files, 'Counting Duplicate Files'): "

This will cause the program to skip the first file from folder and start from the second file. If statement start counting from 0 and idx+1 will make the program start from the second file instead. 
The issue is not shown in this particular program because in line 46 
"  msg = '{} Files processed\n {} Duplicates found'.format(total_file, dup_count)"
;the total_file is displayed, if you were to change total_file into idx you'd receive a number that is one less than total_file.

However if you use idx instead of idx +1 in line 27 the progress meter will not complete.(i.e stops one before the len(total_files)

**Comment by di** [comment]
Thanks for the report, but it doesn’t belong here. This tracker is for https://pypi.org itself. We can't help with packages distributed on PyPI. You’ll need to contact the package maintainers or community instead.
