### ISSUE TITLE
JSON API missing release

### ISSUE THREAD

**Issue by schettino72** [pypa/warehouse#515]
Using the warehouse API `https://warehouse.python.org/pypi/pytest/json` the response has no info on latest py.test release. The end of the response (as of now) looks like:

```
   "2.7.1": []}, "urls": []}
```

The response from `https://pypi.python.org/pypi/pytest/json` is ok.

I would guess this is a cache issue, so might not be easily reproducible in the future!

**Comment by dstufft** [comment]
This is because warehouse.python.org was broken and a new release that has the fixed code hasn't yet been deployed. Going to go ahead and close this since the problem doesn't exist in the current master branch.
