### ISSUE TITLE
Increase size limit for Intel's cpu-optimized tensorflow packages on PyPi test.

### ISSUE THREAD

**Issue by ashahba** [pypa/warehouse#5150]
@di,
I recently filed a ticket here: https://github.com/pypa/warehouse/issues/5126 to increase the file size limit for Intel optimized TensorFlow packages which was approved for the PyPi.

However I think I forgot to mention that we need the same limits `125MB` for the test PyPi as well.
So that is what this ticket is for.

I have initiated the test project here: https://test.pypi.org/project/intel-tensorflow/ which we like to have it increased to `125MB` for now.

Thanks.

**Comment by di** [comment]
I've set the upload limit for `intel-tensorflow` to 125MB on Test PyPI.

**Comment by ashahba** [comment]
Thanks @di
