### ISSUE TITLE
PEP 541: Transfer ownership of pyhdf to python-hdf4 maintainer

### ISSUE THREAD

**Issue by djhoese** [pypa/warehouse#5157]
The python-hdf4 package has become a popular fork of the pyhdf package which has not seen any updates in 10 years. The python-hdf4 package adds python 3 support and other bug fixes. The related project issue is https://github.com/fhs/python-hdf4/issues/13

I think @fhs and @hdfeos should be given maintainership. @teoliphant is a maintainer of the package on PyPI so if he has any information/feedback on this I wouldn't mind hearing it.

As mentioned in the related issue, pyhdf's naming has been an issue for a long time but now especially that there is a `pyhdf` package on [conda-forge](https://github.com/conda-forge/pyhdf-feedstock) with the original name but everyone using PyPI has gotten used to downloading `python-hdf4`. The conda package points to @hdfeos's copy of the library which is actually a fork of `python-hdf4`. I'm hoping that this ownership transfer is the start of a single `pyhdf` package.

If there is another way to do this (related: #1506) let me know.

**Comment by djhoese** [comment]
What is the next step with this? Should I "try harder" at contacting the original maintainers?

**Comment by pradyunsg** [comment]
Hi! Sorry for the delayed response here.

Have you tried to contact Travis Oliphant via any medium, other than the GitHub mention on this issue? If not, I'd suggest dropping him an email and seeing if he's willing to transfer the package name to you.

In case he does not respond for a while, feel free to ping on this issue again.

**Comment by djhoese** [comment]
Just sent an email, thanks.

**Comment by teoliphant** [comment]
Hey all.  So sorry for the delayed response.   Do I understand correctly that python-hdf4 is a fork of pyhdf that would like to have the pyhdf name on PyPI, because it is a more maintained version of the library? 

This make sense.  I'm very happy to add new maintainers to the PyPI project.  I have added fhs as a maintainer.  I am happy to add djhoese if you tell me your PyPI name.  Thanks for the email.

**Comment by djhoese** [comment]
@teoliphant Thanks for replying! My username is `dhoese` on PyPI. Thanks.

**Comment by fhs** [comment]
Thanks @teoliphant. I'll be making a new release after I've updated the name in setup.py, documentation, etc. I think I'll change the repo name to `pyhdf` as well.

@djhoese I've created https://github.com/fhs/python-hdf4/pull/22 with the changes but I think more changes are need.

**Comment by fhs** [comment]
New version of pyhdf has been published in PyPI. This issue can be closed.
