### ISSUE TITLE
PEP 541: Ownership of 'pitstop' package

### ISSUE THREAD

**Issue by darvid** [pypa/warehouse#5158]
Hi,
I would like to register the name 'pitstop' but publishing returns a 403. The [project page](https://pypi.org/project/pitstop/) does not appear to exist, so I'm assuming no releases were ever uploaded.

My PyPI username is the same as my Github username.

**Comment by yeraydiazdiaz** [comment]
Hello @darvid, indeed the project has no releases and is thus considered invalid.

I will contact the administrators to proceed with the transfer.

**Comment by ewdurbin** [comment]
Transfer complete.
