### ISSUE TITLE
Wheel size limit increase requested for google-nucleus

### ISSUE THREAD

**Issue by ThomasColthurst** [pypa/warehouse#5172]
* A link to your project on PyPI (or Test PyPI):  https://pypi.org/project/google-nucleus/ and https://test.pypi.org/project/google-nucleus/
* The size of your release, in megabytes:  The wheel file for v0.2.1 which we would like to release is 74M.
Which index/indexes you need the increase for (PyPI, Test PyPI, or both):  Both, please
* A brief description of your project, including the reason for the additional size:  Nucleus is a project for reading and writing genomic data, and for making it easy to use genomic data and machine learning together.  Nucleus depends on the TensorFlow package, but for performance reasons, v0.2.1 increased the amount of TensorFlow which is compiled into Nucleus object files.  This lead to the increased size of the wheel file.

**Comment by di** [comment]
I've set the limit for `google-nucleus` to 100MB on both PyPI and TestPyPI.
