### ISSUE TITLE
[UI] `Requires: Python` in meta section is poorly rendered

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#5173]
**Describe the bug**

When it's long (like `Requires: Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*`) the part of it gets overlayed by the main long-description content.

**Expected behavior**

I think it's probably worth splitting the conditions by comma and showing them as a list.

**To Reproduce**

https://test.pypi.org/project/ansible-lint/3.5.2.dev43/
Only `>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.` part is visible on screen.

**My Platform**
N/A

**Additional context**

N/A

**Comment by di** [comment]
Here's a screenshot for posterity:

<img width="418" alt="screen shot 2018-12-07 at 11 57 04 am" src="https://user-images.githubusercontent.com/294415/49664358-485c4b00-fa17-11e8-88b1-375a58e944a9.png">

**Comment by webknjaz** [comment]
Thanks, I didn't have a screenshotting tool when submitting this :)
