### ISSUE TITLE
PyPI size limit increase for DB Connect Spark connector

### ISSUE THREAD

**Issue by ericl** [pypa/warehouse#5179]
Hi, similar to https://github.com/pypa/packaging-problems/issues/90 and https://github.com/pypa/packaging-problems/issues/221, we'd like to ship a pypi package that bundles Spark jars. This package is a Spark connector that allows Databricks users to run code remotely from their local machine: https://pypi.org/project/databricks-connect/

The size of these jars is ~230 MB total. Would it be possible to bump the limit for `databricks-connect` to 280MB on test.pypi.org and pypi.org?

Since we are necessarily building these packages from a different tree than pyspark is, it's unfortunately not possible to depend on the pyspark binaries. I've uploaded dummy packages that don't include jars on https://test.pypi.org/project/databricks-connect/ and https://pypi.org/project/databricks-connect/ for now.

**Comment by di** [comment]
I've set the upload limit for `databricks-connect` to 280MB on both PyPI and TestPyPI.

Please be mindful of how often you make releases at this size.

**Comment by ericl** [comment]
Thanks @di , we'll keep that in mind!
