### ISSUE TITLE
Possible to rename package due to _ vs - ?

### ISSUE THREAD

**Issue by maxandersen** [pypa/warehouse#5190]
I can't find clear info if renaming of projects like `homeassistant_cli` to `homeassistant-cli` is supported/allowed ? 

I tried to update all scripts etc. using _ to - but seems pypi insists on calling it homeassistant_cli because that was what the very first upload by accident had in it.

Can you help rename https://pypi.org/project/homeassistant_cli/ to https://pypi.org/project/homeassistant-cli/ so things are more clean - or is only option to delete the old and create new ? 

Thank you!

**Comment by di** [comment]
Just merged a PR which should make this possible. Give it 15 mins to deploy, after which making a new release should allow you to change things like capitalization or dots/dashes/underscores.

**Comment by maxandersen** [comment]
btw. it worked :) https://pypi.org/project/homeassistant-cli/ now shows up properly. thank you!
