### ISSUE TITLE
Size limit increase request

### ISSUE THREAD

**Issue by montebhoover** [pypa/warehouse#5191]
Project name: nimbusml -  https://pypi.org/project/nimbusml/

Index requested for increase: Test PyPI

We were granted an increase for our project on standard PyPI index in #4901, and I was wondering if we could get a size limit increase on the Test index as well.  We have wheels ranging from 70-90 MB for Linux/Mac/Windows, their size being a result of including ML.NET binaries from https://github.com/dotnet/machinelearning .

Thanks! -Monte

**Comment by di** [comment]
I've set the upload limit for `nimbusml` to 100 MB on TestPyPI.
