### ISSUE TITLE
Requesting to delete invalid grpcio-channelz package

### ISSUE THREAD

**Issue by srini100** [pypa/warehouse#5196]
Recently someone uploaded junk [grpcio-channelz](https://pypi.org/project/grpcio-channelz/) pkgs for multiple future releases which is blocking [grpc.io project](https://grpc.io/) from releasing official pkgs. This [user](https://pypi.org/user/rahul.magul/) is not associated with grpc.io project and using the project name without authorization.

Please delete this pkg as it misleads gRPC users. Please transfer the pkg name to [grpc-packages](https://pypi.org/user/grpc-packages/) such that we can reuse the release numbers.

Thanks!

**Comment by jamadden** [comment]
I’m not an admin, I just help triage issues.

**Comment by srini100** [comment]
This got resolved. Thanks.

**Comment by anadon** [comment]
I'd like to re-open this on the related 'grpc' package which in name squatting for 'grpcio' and is too broken to install.  There doesn't seem to be a good way for reporting these issues.

**Comment by srini100** [comment]
Which pkg is that? Can you open a new issue?
