### ISSUE TITLE
Searching by exact package name does not work as expected.

### ISSUE THREAD

**Issue by zopyx** [pypa/warehouse#5200]
Official PyPI.

Searching for my package 

https://pypi.org/project/xmldirector.connector/

with query `xmldirector.connector`.

Does not reveal any useful hits. 

Expected behavior: matches with exact package names should be first. Instead I see unrelated hits that have either `xmldirector` or `connector` in the package name.

**Comment by ewdurbin** [comment]
Looks like it's a fairly new project, so the search index may take some time to "see it".

Our search infrastructure attempts to update the index with each release, but that occasionally fails. There is a full sync every 6 hours, so occasionally new projects may take up to 6 hours to show in results.

I'm going to investigate to see if there is anything going wrong in our incremental search index update now just to be sure.

**Comment by ewdurbin** [comment]
Certainly looks like the incremental search update failed for some reason not once, but three times for this project. Looks like a reemergence of something like #4183

**Comment by crwilcox** [comment]
Searching today returns the package as the top result. https://pypi.org/search/?q=xmldirector.connector

**Comment by zopyx** [comment]
much better
