### ISSUE TITLE
Expand getting started doc to be more contributor friendly

### ISSUE THREAD

**Issue by willingc** [pypa/warehouse#521]
Reorganize the getting started doc (getting-started.rst) to clarify the development setup for new contributors.

-  [x] Get the Warehouse source code
-  [x] Set up development container environment
       * Install Docker
       * Install Docker-compose
       * Install tox
-  [x] Running a Warehouse instance
       * Tips on IP addresses and ports when using Docker
-  [x] Running tests
-  [x] Building documentation
       * Provide instructions for working on the docs without setting up a Docker container

**Comment by dstufft** [comment]
Just to clarify for anyone looking at this ticket, if there's something easier for people than Docker we can totally switch. There's not really a whole lot set in stone in Warehouse. We can make some drastic changes if it makes things easier.

**Comment by willingc** [comment]
@dstufft I was able to get all up and running last night with the exception of the a local instance of the database with data (I was able to do with an empty database). I think that I need to install xz on my mac to deal with the second line here:
![screen shot 2015-05-23 at 2 39 59 pm](https://cloud.githubusercontent.com/assets/2680980/7785852/2b2e9308-015a-11e5-8f89-37c2a000cf36.png)

**Comment by dstufft** [comment]
Ah yea, maybe we should have something other than xz then. I only used xz because it makes smaller files.

**Comment by dstufft** [comment]
Fixed!
