### ISSUE TITLE
Increase size limit request

### ISSUE THREAD

**Issue by pzhokhov** [pypa/warehouse#5214]
- A link to your project on PyPI (or Test PyPI):  https://pypi.org/project/roboschool/
- The size of your release, in megabytes: 100 
- Which index/indexes you need the increase for (PyPI, Test PyPI, or both): PyPI
- A brief description of your project, including the reason for the additional size:
   Roboschool (https://github.com/openai/roboschool) is a simulator of robotics environments. It takes control inputs for a simulated robot (humanoid, ant, reaching arm) and provides reward signal (e.g. how fast does the simulated humanoid runs) as well as rendering capabilities. The bulk of the size is in rendering and math libraries (qt and boost) that one could set up manually, but for the ease of the installation process we include into the binaries.

**Comment by di** [comment]
I've set the limit for `roboschool` to 100MB on PyPI.

**Comment by pzhokhov** [comment]
Thanks a lot @di !
