### ISSUE TITLE
Display "last released" date in sorted-by-relevance search results 

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#5222]
When the user [searches for, e.g., `short-url`](https://pypi.org/search/?q=short-url), in the default view (sorted by relevance), we could display the last-released date on each item, just as we do [when sorting by last updated](https://pypi.org/search/?q=short-url&o=-created). 

Requested by @koobs in IRC (`#pypa-dev`) today:

> Makes it easier to filter 'relevance results' by last updated for large result sets
> when you search on PyPI, it defaults to a 'Relevance' search. the results in this Relevance (order by) mode dont display 'Last updated' attribute of the package in the results
> When you switch to 'Last updated' order by, 'Last updated' values are shown
> What I'm proposing is exposing/displaying the 'Last updated' values in the 'Relevance' order by case as well
> Allowing users to use the 'relevance' matching which highlights (as expected) 'more' relevant results, but also allows them to see last updated, instead of going to the package page, to see last updated
> my example case: https://pypi.org/search/?q=short+url
> when you switch that search to last updated, most of the results aren't relevant for the search terms any more
<koobs> im looking for 'relevent' results 'updated recently'
<koobs> without 'Last updated' being displayed in relevence mode, i cant do that
~~~

**Comment by sanjaysiddhanti** [comment]
I can work on this issue

**Comment by brainwane** [comment]
Great! Please go ahead!

**Comment by brainwane** [comment]
Thanks, @sanjaysiddhanti! What will you be working on next?

**Comment by sanjaysiddhanti** [comment]
@brainwane I'm not sure -- do you have any suggestions?

I was working on the spec for https://github.com/pypa/warehouse/issues/8158, but we might be at a blocker there because we don't want to commit such a large file to the git repo and slow everything down.

**Comment by sanjaysiddhanti** [comment]
Would be happy to work on any issues you have in mind, or I can look through the open issues

**Comment by brainwane** [comment]
@sanjaysiddhanti I think you should go ahead and look through the ["help needed" issues](https://github.com/pypa/warehouse/labels/help%20needed)!
