### ISSUE TITLE
Increase size limit request for robotframework-SikuliLibrary

### ISSUE THREAD

**Issue by rainmanwy** [pypa/warehouse#5239]
hello,

project link: [robotframework-SikuliLibrary](https://pypi.org/project/robotframework-SikuliLibrary/)
package size: 100MB
Which index/indexes you need the increase for: pypi
project description: a package include a jar file.

As this project need publish with a jar file, size is over 60MB. Could you help to increase size limit of this project.

Thank you very much!

**Comment by di** [comment]
I've set the upload limit for `robotframework-SikuliLibrary` to 100MB on PyPI.
