### ISSUE TITLE
Copyright end-date in footers needs updating

### ISSUE THREAD

**Issue by holdenweb** [pypa/warehouse#524]
Harsh Gupta <gupta.harsh96@gmail.com> points out in email to webmaster@ that the page footer still shows "Copyright © 1990-2014, Python Software Foundation." The easy fix is a change to the templates, but it might be better to simply dynamically substitute the current year for the second date.

Is this the correct repo for the current PyPI?

**Comment by dstufft** [comment]
I updated this on the live site, leaving this issue open we so get the date dynamically generated in Warehouse.
