### ISSUE TITLE
Ownership of python-christofides package

### ISSUE THREAD

**Issue by SimonDeRidder** [pypa/warehouse#5255]
Hi,
I've contacted the current owner @dsrahul30 of the [python-christofides](https://pypi.org/project/python-christofides/) package about a month ago, but he hasn't answered.
I'd like to make this package python3 compatible, as well as improving performance.
Perhaps it should also be renamed to just "christofides", the same as the module name
My PyPI username is SimonDR.

**Comment by SimonDeRidder** [comment]
Hi @crwilcox,  I already made a fork and submitted a pull request back in october, with no reaction, and as the last commit is from April 2017, I assume @dsrahul has abandoned it.
I guess I could just release under a new name.
It seems cleaner to just continue where he left off, but I can live with either solution.

**Comment by yeraydiazdiaz** [comment]
Hi @SimonDeRidder. Seems @dsrahul30 has two projects with Christofides in the title:

https://pypi.org/project/Christofides/
https://pypi.org/project/python-christofides/

The former has a higher version number than the latter which seems to match the GitHub repository. Could you confirm which of the two you would like to take ownership of?

In the meantime I will email @@dsrahul30 to try and clarify his position regarding these projects.

**Comment by SimonDeRidder** [comment]
Hi @yeraydiazdiaz ,
Sorry for the late answer.
There seems to be little difference between the two other than the name and version,
so I suppose the former would be the best choice to keep, with the latest version number and the simpler name.

**Comment by yeraydiazdiaz** [comment]
Thanks @SimonDeRidder . I will now contact an administrator to proceed to adding your PyPI username `SimonDR` as an owner of the `christofides` project.

**Comment by ewdurbin** [comment]
`SimonDR` added as Owner to `Christofides` and `python-christofides`
