### ISSUE TITLE
Markdown does not render on test.pypi

### ISSUE THREAD

**Issue by kimyen** [pypa/warehouse#5276]
**Describe the bug**

Markdown does not render on test.pypi

**Expected behavior**
The same branch (same source code) are use in pypi, and the markdown is rendered: https://pypi.org/project/synapseclient/ (version 1.9.0)

**To Reproduce**
Run the following script: https://raw.githubusercontent.com/Sage-Bionetworks/CI-Build-Tools/master/py-pkg/staging-deploy.sh
In case someone looks at this bug report after the link above has changed, I include a copy of the content:
```
# This script, when run from Jenkins, releases the python package to test.pypi.org.

# Parameters
# GITHUB_USERNAME -- The Github user who is running this build
# GITHUB_ACCOUNT -- The target Github account
# GITHUB_TOKEN -- The Github token that grants access to GITHUB_ACCOUNT for GITHUB_USERNAME
# EMAIL -- The email of the user in GITHUB_USERNAME
# REPO_NAME -- The Github repo to get the Python code from
# GIT_BRANCH -- The release candidate branch
# TESTPYPI_USERNAME -- The test.pypi.org user
# TESTPYPI_PASSWORD -- The test.pypi.org user's password

# remove the last build clone
set +e
rm -R ${REPO_NAME}
set -e

# create .pypirc file
echo [distutils] > ~/.pypirc
echo index-servers=testpypi >> ~/.pypirc
echo >> ~/.pypirc
echo [testpypi] >> ~/.pypirc
echo repository: https://test.pypi.org/legacy/ >> ~/.pypirc
echo username:$TESTPYPI_USERNAME >> ~/.pypirc
echo password:$TESTPYPI_PASSWORD >> ~/.pypirc

# clone the Github repo
git clone https://github.com/${GITHUB_ACCOUNT}/${REPO_NAME}.git

cd ${REPO_NAME}
git config user.name "${GITHUB_USERNAME}"
git config user.email "${EMAIL}"

export VERSION=`echo $(echo ${GIT_BRANCH}.$BUILD_NUMBER | sed 's/origin\/v//g; s/-rc//g')`
git checkout ${GIT_BRANCH}

# update version
sed "s|\"latestVersion\":.*$|\"latestVersion\":\"$VERSION\",|g" synapseclient/synapsePythonClient > temp
rm synapseclient/synapsePythonClient
mv temp synapseclient/synapsePythonClient
python3 setup.py install

# create distribution
python3 setup.py sdist

# upload to testpypi 
twine upload --repository testpypi dist/*

# clean up
cd ..
rm -rf ${REPO_NAME}
```

Result in test.pypi with markdown not rendered: https://test.pypi.org/project/synapseclient/ (version 1.9.0.42)

**My Platform**
OS
```
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-104-generic x86_64)
```
Python version
```
$ python3
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
Twine version
```
$twine --version
twine version 1.11.0 (pkginfo: 1.5.0.1, requests: 2.9.1, setuptools: 40.6.3,
requests-toolbelt: 0.8.0, tqdm: 4.29.0)
```

`setup.py` includes information as instructed: https://github.com/Sage-Bionetworks/synapsePythonClient/blob/v1.9.0-rc/setup.py

**Additional context**
The successful version on pypi was pushed before we started to test out test.pypi. The specific platform detailed used in releasing that version is not recorded.

**Comment by di** [comment]
Something's off with your deployment environment. [This release](https://test.pypi.org/project/synapseclient/1.9.0.42/) was built with:

> twine/1.11.0 pkginfo/1.5.0.1 requests/2.9.1 setuptools/33.1.1 requests-toolbelt/0.8.0 tqdm/4.29.0 CPython/3.6.7

The problem is `setuptools==33.1.1`, it needs to be `setuptools>=38.6.0`. I'd recommend specifically `pip install`-ing specific versions of `twine` and `setuptools` at the beginning of your deployment script.

**Comment by kimyen** [comment]
@di, thank you for looking into this. In the build machine, I have `python` (2.7) and `python3` (3.6.7). I used `python3 -m pip ...` to install `setuptools` and `apt-get` to install `twine`.

As you can see above the version of `setuptools` shown up with `twine` version is 40.6.3.
The version of `setuptools` in `python3` is:
```
$ python3
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'40.6.3'
>>> 
```
To be honest, I installed and uninstall `setuptools` and pip several times to get this version. What I don't understand is when does `setuptools` comes into play? during building the distribution? or during `twine` upload? and how to I verify the `setuptools` version that was used at runtime?

**Comment by kimyen** [comment]
> I'd recommend specifically pip install-ing specific versions of twine and setuptools at the beginning of your deployment script.

This works perfectly! Thank you very much. I installed the twine and setuptools as ubuntu user. The user who is running the script is a different user. Adding the installation step in to build script ensure that the environment is correct each time the scrip run.

**Comment by di** [comment]
The version of `setuptools` comes into play when running `python setup.py sdist` due to the `from setuptools import setup` in your `setup.py` file.

Twine reports which versions of various packages are present when you upload the distribution, which is where "setuptools/33.1.1" came from.

What's the output of the following commands?

```
$ python -m twine --version
$ python3 -m twine --version
```

**Comment by kimyen** [comment]
Here is the output:
```
ubuntu@ip-10-11-62-183:~$ python -m twine --version
/usr/bin/python: No module named twine
ubuntu@ip-10-11-62-183:~$ python3 -m twine --version
twine version 1.11.0 (pkginfo: 1.5.0.1, requests: 2.9.1, setuptools: 40.6.3,
requests-toolbelt: 0.8.0, tqdm: 4.29.0)
```
I am getting these info as `ubuntu`. I am not sure if this is relevant to when I run the script, as `jenkins` user.
