### ISSUE TITLE
Problem with Pyinstaller when using ITKPython

### ISSUE THREAD

**Issue by sshamekhi** [pypa/warehouse#5282]
Dear all,
I am using ITKPython, My codes are working well in PyCharm with *.py format but after making a standalone *.exe file via PyInstaller some errors occure as follow:

Traceback (most recent call last):
File “RSG_V_0.py”, line 27, in <module>
File “site-packages\itkExtras.py”, line 449, in imread
File “site-packages\itkLazy.py”, line 40, in getattribute
AttributeError: ‘LazyITKModule’ object has no attribute ‘ImageFileReader’
[29316] Failed to execute script RSG_V_0
Would you please show me the way to solve these kind of problems. By the way, already I test my PyInstaller with a simple print.py, In fact PyInstaller is working correctly without ITK filters.

Thanks
Sina

**Comment by jamadden** [comment]
Thank you for the report, but unfortunately this is not the correct place for it. This tracker is only for issues with the software that runs pypi.org itself ("warehouse"). For issues with packages installed from there you'll need to contact the appropriate support forum.
