### ISSUE TITLE
Lost credentials

### ISSUE THREAD

**Issue by gabor-boros** [pypa/warehouse#5284]
Dear devs,

I'm working with RethinkDB as a contributor and a core developer. When we took over RethinkDB almost all the credentials lost, including PyPi credentials.

I would like to kindly ask you to help me resolve this issue, because we really would like to release a new version of rethinkdb package.

Thank you in advance

**Comment by ewdurbin** [comment]
Hello @gabor-boros! I see the project currently belongs to a user with an @rethinkdb.com email address. Can you have someone from RethinkDB email ernest@python.org?

**Comment by gabor-boros** [comment]
Hello Ernest,

Unfortunately not, because rethinkdb organization went black in 2016 and the project became open source.

The original maintenance of the open source project was done by the ex employees, but they left the repos abandoned. 

A small group of contributors (including me) pick up the project and started a fork (RebirthDB). After Linux foundation seen that we care about the DB they gave the right to us to merge the fork and they gave the permissions and credentials to us to maintain the original Rethinkdb repos.

Unfortunately they lost the PyPi (and some other) credentials which are needed for deployments.

This is the shorter version of the story.

Unfortunately I wasn’t able to send you a mail, but my email is gabor.brs@gmail.com 

Thank you in advance,
Gábor

**Comment by ewdurbin** [comment]
So the MX records are defunct?

I didn’t get a bounce emailing the current registered address.

**Comment by gabor-boros** [comment]
They are not defunct because the domain was paid by LF, but as I know we have no access to it.

**Comment by ewdurbin** [comment]
Hi @gabor-boros, I see that you and @grandquista have both been consistent contributors to the revival of the project at rethinkdb/rethinkdb-python. Can each of you provide your pypi.org user account names?

**Comment by gabor-boros** [comment]
@ewdurbin, Sure. My user is `gabor-boros`. Unfortunately, I do not know @grandquista's.

**Comment by grandquista** [comment]
I have no personal account on pypi.org. I can register “grandquista” if needed.

**Comment by ewdurbin** [comment]
Yes, it would be preferred if I was able to transfer ownership to two users rather than just one... to keep such a lock out from happening again :)

**Comment by grandquista** [comment]
@ewdurbin I have registered the username `grandquista`.

**Comment by gabor-boros** [comment]
@ewdurbin Is there anything what we can do from our side?

**Comment by ewdurbin** [comment]
Owner role on `rethinkdb` project has been transferred to `gabor-boros` and `grandquista`.

**Comment by gabor-boros** [comment]
Thank you @ewdurbin! Shame on me, but I forgot to ask you to do the same on test.pypi.org. Could you please help with that as well? 😓

**Comment by ewdurbin** [comment]
@gabor-boros done, please add `grandquista` when they've created an account on test.pypi.org
