### ISSUE TITLE
how to get real sql like example.sql.xz matches packages pulled by bandersnatch?

### ISSUE THREAD

**Issue by hermithuang** [pypa/warehouse#5305]
I am buliding a platform serves pypi. I make warehouse web works and use bandersnatch pull real packages from pypi.python.org.  
It seems that the example.sql.xz in dev directory not match the real packages pulled by bandersnatch

So how can i get the right sql  dump to postgredb, then when i click download in warehouse page could get right packages?

thanks a lot

**Comment by di** [comment]
Sorry, we don't support using Warehouse for anything other than being https://pypi.org. There is no way for us to give you a DB dump of PyPI. You'd be better off using software designed to be a PyPI mirror or cache, see ["Package index mirrors and caches"](https://packaging.python.org/guides/index-mirrors-and-caches/).
