### ISSUE TITLE
Request trove classifier: Django 2.2

### ISSUE THREAD

**Issue by michael-k** [pypa/warehouse#5317]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `'Framework :: Django :: 2.2'`

## Why do you want to add this classifier?

Django 2.2 alpha is now released, see https://www.djangoproject.com/weblog/2019/jan/17/django-22-alpha-1/.
See also pypa/warehouse#4090 (previous request for Django 2.1)

**Comment by ewdurbin** [comment]
Done!

**Comment by michael-k** [comment]
That was quick, nice! :)
If it was already available before I opened the issue: I found no matching request, and it wasn't available [18 hours ago](https://github.com/carltongibson/django-filter/commit/8e917de6c90d3d5512d71bae05dc463ecaebc88b).

**Comment by ewdurbin** [comment]
We've got some much better admin tooling to create these quickly, and it is especially for established projects/classifiers. This issue just happened to be the first thing I saw logging into my email this morning :)
