### ISSUE TITLE
Claim package name 'bbox'

### ISSUE THREAD

**Issue by varunagrawal** [pypa/warehouse#5322]
Hi PyPI admins,

I wish to claim the package name "bbox" which ~~is currently~~ was owned by Dustin Tran. I have already emailed Dustin and he has graciously released the package name. Please refer to the attached PDF detailing our email transaction [Gmail - bbox package on PyPI.pdf](https://github.com/pypa/warehouse/files/2784091/Gmail.-.bbox.package.on.PyPI.1.pdf).

This is a PEP 541 related issue. Looking forward to hearing from you!

**Comment by di** [comment]
@varunagrawal The current owner should be able to add you as a new owner on PyPI, is there some reason they can't do this?

**Comment by varunagrawal** [comment]
@di I just checked. https://pypi.org/project/bbox/ throws a 404 and running `twine upload dist/*` gives me
```
HTTPError: 403 Client Error: The user 'varunagrawal' isn't allowed to upload to project 'bbox'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by ewdurbin** [comment]
The Project had all Releases removed by the maintainer on 2018-08-02, but was not itself deleted. This leads to the 404 (no Releases to render) and the inability to register again (the Project still registered to the original owner).

**Comment by ewdurbin** [comment]
I've sent an email to the Project owner (ccing PyPI admins) to ask for a response per PEP 541's reachability clause.

**Comment by varunagrawal** [comment]
What is the correct process to unregister a package on PyPI?

**Comment by dustinvtran** [comment]
Hmm apologies for the hiccup. I think I deleted the project. @varunagrawal Can you register the package now? I'm getting 404 on all pages.

**Comment by varunagrawal** [comment]
Yup it worked. Thanks @ewdurbin and @dustinvtran!
