### ISSUE TITLE
Uploaded to PyPi, but not able to download

### ISSUE THREAD

**Issue by willnx** [pypa/warehouse#5329]
**Describe the bug**

I uploaded an update to https://pypi.org/project/vlab-ipam-api/ yesterday.
Today, when I try to install that update, pip3 says it doesn't exist.
When I check the PyPi website, I find the updated package: https://pypi.org/project/vlab-ipam-api/2019.1.23/

**Expected behavior**

I expect to download packages that exist on PyPi.

**To Reproduce**

 https://pypi.org/project/vlab-ipam-api/2019.1.23/

**My Platform**

Ubuntu Server 18.04
Python 3.6.7
Pip3 9.0.1

**Additional context**

![image](https://user-images.githubusercontent.com/12264343/51619761-da47e680-1ee5-11e9-8ff0-7f8ef69f39a9.png)

**Comment by di** [comment]
This was a minor hiccup with cache purging on our end, essentially a duplicate of #4892.
