### ISSUE TITLE
Misrenders option lists in long_description

### ISSUE THREAD

**Issue by mgedmin** [pypa/warehouse#533]
Take a look at https://warehouse.python.org/project/restview/#synopsis:
![screenshot](https://cloud.githubusercontent.com/assets/159967/8002941/61ba66b0-0b7b-11e5-9bf2-e38a32fcecde.png)

Those `<kbd>` and `<var>` tags are how docutils renders [option lists](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#option-lists).

Looks like you have some kind of a whitelist-based HTML scrubber post-processor that doesn't realize these are valid (if ancient) HTML tags.

BTW the same problem [shows up on PyPI](https://pypi.python.org/pypi/restview/#synopsis).

**Comment by dstufft** [comment]
Ah, yea- We need to add them to the whitelist on https://github.com/pypa/readme
