### ISSUE TITLE
New serial causing bandersnatch to generate no link Simple HTML files

### ISSUE THREAD

**Issue by cooperlees** [pypa/warehouse#5331]
**Describe the bug**
I can not see evidence of a new [black](https://pypi.org/project/black/) release today but for some reason 3 of my production bandersnatch mirrors generated ano link index.html. Example:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Links for black</title>
  </head>
  <body>
    <h1>Links for black</h1>

  </body>
</html>
```
- Is there somewhere I can find out why black got a new serial and thus bandersnatch wanted to regenerate the Simple HTML?
- Bandersnatch logging showed no errors and that everything worked as expected

If this is just an internal error or a known problem please just link me to that and we can close this :).

**Expected behavior**
Only generate a new serial on new versions. (I could be wrong here)

**To Reproduce**
Not sure here - As asked above, is there a log somewhere to see why a new serial was generated? Or some datasource I / the general public have access to?
- I *could* run a new bandersnatch instance with 3.1.1 and see if I get a blank simple index.html on my laptop using the whitelist feature to only mirror black if you feel that could be nice to see.

**My Platform**
OS: CentOS
Client = Bandersnatch 3.1.1

**Additional context**
Have opened https://github.com/pypa/bandersnatch/issues/140 as this is probably a bandersnatch issue.

**Comment by di** [comment]
Can confirm that there is not a new release of `black`, but there were some changes to the roles for owners of that project today. This would result in a cache purge across any project-specific pages, so it seems likely that this caused the new serial, but it's not clear to me if it should have or not.

**Comment by ewdurbin** [comment]
Also confirming that these changes occurred, and that they indeed each lead to an increment of the serial.

Journal:

<img width="715" alt="screen shot 2019-01-23 at 2 28 08 pm" src="https://user-images.githubusercontent.com/1200832/51631651-4264ef80-1f1b-11e9-8f7d-bc09257169b2.png">

<img width="523" alt="screen shot 2019-01-23 at 2 29 52 pm" src="https://user-images.githubusercontent.com/1200832/51631694-60325480-1f1b-11e9-8fe5-be5d6bacbde1.png">

The internal bandersnatch mirror is handling this fine, so I do believe it's a potential regression in bandersnatch.

It's also possible that some CDN purging issues we're seeing at the moment may be a compounding factor.

**Comment by ewdurbin** [comment]
For reference, internal PyPI bandersnatch is running 2.2.1

**Comment by cooperlees** [comment]
Cheers for the info @ewdurbin  - I'll try repro on my laptop this afternoon with bandersnatch trunk.

**Comment by cooperlees** [comment]
Making the CI job try and install black and not remove the temp repo on the filesystem I can repro on my laptop. Will dig in a debug.
Diff to trunk: https://pastebin.com/pDDpYH7a

Will close this if I can make a suitable fix in bandersnatch code or submit a PR to Warehouse.

**Comment by cooperlees** [comment]
Root caused - Loading all the bandersnatch plugins by default creates unexpected implicit behavior. Tured that off. PR up. Can close here:
https://github.com/pypa/bandersnatch/pull/142
