### ISSUE TITLE
PEP 541: transfer ownership of unmaintained `catalyst`

### ISSUE THREAD

**Issue by Scitator** [pypa/warehouse#5332]
Hi,

I would like to transfer ownership of the name [`catalyst`](https://pypi.org/project/catalyst/). The current PyPI package is lost from the GitHub and is not maintained since first release in 2016.

On the other hand, [our repo](https://github.com/catalyst-team/catalyst) is actively maintained and has 400+ stars and 40+ forks. There're also users who are asking us to publish our package to PyPI with correct name. (It's a bit weird when you need to install `catalyst-ti`, but `import catalyst` or use `catalyst-dl`/`catalyst-rl` in the command line - with correct name, there is no such issue).

This doesn't seem like a good situation to have drastically outdated package on PyPI while having an active repo, and doesn't seem to contribute to a healthier community. Could you step in please?

References https://github.com/pypa/warehouse/issues/1506.

**Comment by Scitator** [comment]
@jamadden Yup, waiting for the response.
Nevertheless, is there any time limit for such cases? Or how do such processes usually go?

**Comment by jamadden** [comment]
[PEP 541](https://www.python.org/dev/peps/pep-0541/) specifies the official process, including definitions of 'reachability' and 'abandoned projects'.

**Comment by Scitator** [comment]
Thanks to Fabian van der Werf the ownership have been transferred.
