### ISSUE TITLE
Broken link in FAQ

### ISSUE THREAD

**Issue by Hornwitser** [pypa/warehouse#5342]
**Describe the bug**

The [How do I become a owner/maintainer of a project on PyPI?](https://pypi.org/help/#request-ownership) section of the FAQ links to the _How do I claim an abandoned or previously registered project name?_ section using the wrong url  (`https://pypi.org/help/project-name-claim`)

**Expected behavior**

The section linked correctly

**To Reproduce**

Go to https://pypi.org/help/#request-ownership and click on the how do I claim abandoned packages link

**My Platform**

Android Chrome, but shouldn't matter.

**Additional context**

None

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
Thanks for the report. This should be linking to `https://pypi.org/help/#project-name-claim` instead.

I've marked this as a good first issue.
