### ISSUE TITLE
Web site guidance has a missing link for abandoned projects

### ISSUE THREAD

**Issue by jeking3** [pypa/warehouse#5345]
I went to the web site looking for guidance on abandoned projects:
https://pypi.org/help/#request-ownership

The link in that section for "How do I claim an abandoned or previously registered project name?" which links to https://pypi.org/help/project-name-claim is dead.

I am on the Apache Thrift PMC and our PMC chair, who is the only maintainer of the thrift package, has gone unresponsive.  I need guidance on getting added to the thrift project as a maintainer so I can upload the 0.12.0 release to pypi. Thanks.

**Comment by jeking3** [comment]
Looks like it's missing an anchor at the beginning; the information is directly above it.

**Comment by yeraydiazdiaz** [comment]
Thanks for reporting this @jeking3. You're right, it's just missing an anchor. Will be fixed soon.

**Comment by yeraydiazdiaz** [comment]
Seems it's already been reported in #5342. Closing.
