### ISSUE TITLE
Latest release(14.2.1) not installable via pip

### ISSUE THREAD

**Issue by mdomke** [pypa/warehouse#535]
I'm currently not able to install the latest released version (14.2.1) of `warehouse`, because `recliner` is still a package dependency. `recliner` itself relies on `bleach-py3k` which is not installable. AFAIK `recliner` has been replaced by `readme`, but no release has been made with these changed dependencies.

```
Collecting bleach-py3k>=1.2 (from recliner>=0.3.1->warehouse)
  Could not find a version that satisfies the requirement bleach-py3k>=1.2 (from recliner>=0.3.1->warehouse) (from versions: )
No matching distribution found for bleach-py3k>=1.2 (from recliner>=0.3.1->warehouse)
```

**Comment by dstufft** [comment]
I should probably just delete the versions of Warehouse on PyPI. We're not currently using it or updating it so it's fairly confusing to have it there I think.

**Comment by dstufft** [comment]
I went ahead and removed all of the releases since it's an older iteration of Warehouse and we aren't currently releasing anything to PyPI.
