### ISSUE TITLE
Pypi package size limit for Analytics Zoo

### ISSUE THREAD

**Issue by jason-dai** [pypa/warehouse#5359]
I wonder if it is possible to increase the limit of https://pypi.org/project/analytics-zoo/ to 120MB? 

Analytics Zoo (https://github.com/intel-analytics/analytics-zoo) is a unified analytics + AI platform for distributed TensorFlow, Keras and BigDL on Apache Spark; and the reason for the large size (esp. for the upcoming releases) is that it will include more .so files for hardware accelerations, model optimizations, etc.

**Comment by jamadden** [comment]
I've set the upload limit to 120MB.
