### ISSUE TITLE
spark-nlp 1.8.1 timeout when installing

### ISSUE THREAD

**Issue by danilojsl** [pypa/warehouse#5364]
**Describe the bug**

We are facing problems when installing spark-nlp with version 1.8.1. It works with 1.8.0, but with 1.8.1 displays this error:
```
 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/21/8f/342b465d77a44f61b58fdacd372c7e5133e083e492cc7187fcb8a4dde524/spark_nlp-1.8.1-py2.py3-none-any.whl
Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/21/8f/342b465d77a44f61b58fdacd372c7e5133e083e492cc7187fcb8a4dde524/spark_nlp-1.8.1-py2.py3-none-any.whl (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",))
```
**Expected behavior**

Install as previous versions

**To Reproduce**

pip install spark-nlp

**My Platform**

We tested on 2 different machines with 2 different OS (MAC OS Sierra, Linux Fedora)
We also tested downloading the packages from https://pypi.org/ and it works without problems.

**Additional context**

**Comment by jamadden** [comment]
I cannot reproduce locally (United States, AT&T Uverse, macOS):
```console
$ pip install spark-nlp
Collecting spark-nlp
  Downloading https://files.pythonhosted.org/packages/21/8f/342b465d77a44f61b58fdacd372c7e5133e083e492cc7187fcb8a4dde524/spark_nlp-1.8.1-py2.py3-none-any.whl (94.6MB)
    100% |████████████████████████████████| 94.6MB 284kB/s
Installing collected packages: spark-nlp
Successfully installed spark-nlp-1.8.1
```

Perhaps this is a CDN issue? If you'd like to provide the information outlined in https://github.com/pypa/warehouse/blob/master/.github/ISSUE_TEMPLATE/access-issues.md it might be helpful to troubleshoot.

**Comment by danilojsl** [comment]
Yes, it's working right now. It seems was some network issue somewhere on the Internet. Thanks
