### ISSUE TITLE
Claim package `mlpack`

### ISSUE THREAD

**Issue by rcurtin** [pypa/warehouse#5365]
Hi there, this is a ported issue pypa-legacy#789, which never received a response and was closed.  So I wanted to reopen it here and see if we could get it figured out. :+1:

This issue is in the same vein as pypa-legacy#789. I maintain the mlpack project (https://github.com/mlpack/mlpack), and we recently added Python bindings, but the name 'mlpack' is claimed so we were forced to take 'mlpack3'. For our users it would be much easier if we could say 'pip install mlpack' instead of 'pip install mlpack3'.

I'd like to claim 'mlpack' under PEP 541, since I was not able to contact the package maintainer, and the package has seen no development or updates in many months.

I know the process is not ready yet, and I am not in a hurry, but I wanted to open this issue so that when the PEP 541 process is implemented, this can be handled.

Thanks! (and of course let me know if any more information is needed)

**Comment by janek** [comment]
I'd like to second this request, as a user of mlpack (https://github.com/mlpack/mlpack). 

I was going through the installation process today and lost quite a bit of time being confused about what I installed. 

The package named 'mlpack' contains two functions and is clearly abandoned. @rcurtin's mlpack is pretty popular and growing fast, it would be great to save everyone's time and confusion by giving him the name.

**Comment by rcurtin** [comment]
Hi there, is there any way to get an update on this one?  I've been waiting for quite a long time on this.  I don't mean to pester, but the current situation is confusing for our users.  (In fact I am updating this today because I just helped a user debug their mlpack installation only to find that they had installed the wrong package.)

**Comment by rcurtin** [comment]
@dstufft @nlhkabu @woodruffw @jamadden sorry to tag each of you and add to your notifications, but I have no idea how to help get this issue resolved.  Can any of you help or possibly point me at the right people who can?  Thank you so much!

**Comment by yeraydiazdiaz** [comment]
Hi @rcurtin, apologies for the delay in processing this request.

I believe GitHub user @scipsycho is the owner of the package and this is the [repo](https://github.com/scipsycho/mlpack) though it doesn't seem to match the current release in PyPI.

@scipsycho could you clarify your position regarding this project? Would you consider transferring ownership to @rcurtin?

**Comment by rcurtin** [comment]
Hi @yeraydiazdiaz, I tried making contact quite some time ago and never heard back.  I considered the package abandoned.

**Comment by yeraydiazdiaz** [comment]
I understand @rcurtin. Moderators need to make contact in an "official" capacity though, sometimes can be more receptive to us. Hopefully we'll get a response soon.

**Comment by scipsycho** [comment]
Hi,
I am sorry but I was out of station for a while. Yes, I am the owner of the package `mlpack`.  As far as the position goes, I am currently making the package for myself. Why do you need the ownership of this package?

Regards,
Dharmesh Singh

On 08-Sep-2019, at 9:24 PM, Yeray Diaz Diaz <notifications@github.com<mailto:notifications@github.com>> wrote:


I understand @rcurtin<https://github.com/rcurtin>. Moderators need to make contact in an "official" capacity though, sometimes can be more receptive to us. Hopefully we'll get a response soon.

**Comment by rcurtin** [comment]
Hey @scipsycho, thanks for responding!  Our library mlpack (https://mlpack.org/) has been one of the primary C++ machine learning libraries since 2007.  Recently we have added Python bindings, and making these easy to install via `pip` is really important for us and our users.  Right now they have to do `pip install mlpack3`, and we regularly get issues opened where someone did `pip install mlpack` and they don't understand why that didn't get them the mlpack library.  If you'd be willing to relinquish the name, it would be greatly appreciated by us and it would make our lives significantly easier. :-D Let me know what you think.

Thanks!

Ryan

**Comment by scipsycho** [comment]
Oh! Fine by me. If it helps you, why not. So, what’s the procedure? I would change the name to `mlpackage` then.

Regards,
Dharmesh Singh

On 14-Sep-2019, at 11:34 PM, Ryan Curtin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @scipsycho<https://github.com/scipsycho>, thanks for responding! Our library mlpack (https://mlpack.org/) has been one of the primary C++ machine learning libraries since 2007. Recently we have added Python bindings, and making these easy to install via pip is really important for us and our users. Right now they have to do pip install mlpack3, and we regularly get issues opened where someone did pip install mlpack and they don't understand why that didn't get them the mlpack library. If you'd be willing to relinquish the name, it would be greatly appreciated by us and it would make our lives significantly easier. :-D Let me know what you think.

Thanks!

Ryan

**Comment by di** [comment]
Thanks for understanding @scipsycho! Since it's not possible to rename a project, we'll have to transfer `mlpack` to @rcurtin, and you'll have to register `mlpackage` as a new project whenever you're ready to publish it.

@rcurtin, What's your username on PyPI?

**Comment by scipsycho** [comment]
Sure. No problem. I will create a new package.

On 16-Sep-2019, at 9:11 AM, Dustin Ingram <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for understanding @scipsycho<https://github.com/scipsycho>! Since it's not possible to rename a project, we'll have to transfer mlpack to @rcurtin<https://github.com/rcurtin>, and you'll have to register mlpackage as a new project whenever you're ready to publish it.

@rcurtin<https://github.com/rcurtin>, What's your username on PyPI?

**Comment by yeraydiazdiaz** [comment]
@scipsycho just to be clear, you will need to add PyPI user `rcurtin` as an owner of `mlpack` in [its collaboration page](https://pypi.org/manage/project/mlpack/collaboration/). Then you can remove yourself from the project or alternatively @rcurtin may do so as well.

**Comment by scipsycho** [comment]
Oh, I thought you guys could do it. I will do it but it may take a couple of days as I am out of station.

On 17-Sep-2019, at 2:27 PM, Yeray Diaz Diaz <notifications@github.com<mailto:notifications@github.com>> wrote:


@scipsycho<https://github.com/scipsycho> just to be clear, you will need to add PyPI user rcurtin as an owner of mlpack in its collaboration page<https://pypi.org/manage/project/mlpack/collaboration/>. Then you can remove yourself from the project or alternatively @rcurtin<https://github.com/rcurtin> may do so as well.

**Comment by yeraydiazdiaz** [comment]
Admins can, but we prefer users to perform these operations themselves to reduce the burden on volunteers. :)

**Comment by rcurtin** [comment]
@scipsycho thanks so much---this will make life a lot easier for our users. :+1:  My PyPI username is `rcurtin`; let me know if there's anything I can help with.

**Comment by di** [comment]
I've added `rcurtain` as an owner of `mlpack`.

**Comment by di** [comment]
(Sorry, typo in the previous comment, `rcurtin` was added not `rcurtain`)

**Comment by rcurtin** [comment]
Hey, sorry for the slow response.  Thank you everyone for the help here!  @scipsycho really appreciate it, and @yeraydiazdiaz and @di I really appreciate your help with the process.
