### ISSUE TITLE
distribute version checking against setuptools

### ISSUE THREAD

**Issue by ericzyq** [pypa/warehouse#5370]
**Describe the bug**
within /python2.7/dist-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py (line:2430)
there was a version checking against setuptools. But since the checking logic is not implemented well, after setuptools got upgraded to version 40.7.1 on Jan 27, the version checking will fail (if '0.7' in 40.7.1 returns TRUE), and it will break the pip install

**Expected behavior**
rewrite the version checking logic

**To Reproduce**

**My Platform**

**Additional context**

**Comment by merwok** [comment]
This seems like a problem in distribute, not PyPI.

Also, distribute has been obsolete for some years now (use setuptools).

**Comment by jamadden** [comment]
Thanks for the report, but I agree: that would seem to be a distribute issue (not a warehouse one), but distribute is abandoned in favor of setuptools.
