### ISSUE TITLE
GitHub links open in new tabs

### ISSUE THREAD

**Issue by merwok** [pypa/warehouse#5371]
**Describe the bug**
Following one of the github links opens a new tab.

**Expected behavior**
I should control whether I want to stay in the same tab or not.

**To Reproduce**
Any project page with github links

**My Platform**
N/A

**Additional context**
Added in https://github.com/pypa/warehouse/pull/3583/

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by jamadden** [comment]
To be clear, this is not all arbitrary github links. This is only the links that are auto-extracted from the GitHub integration in the Statistics section. E.g., on the [gevent project page](https://pypi.org/project/gevent/), the project links for 'source code' and 'bug tracker' both point to github and *do not* open new tabs. Only the links under 'Statistics' that point to GitHub (starts, forks, open issues/prs) do open new tabs.

**Comment by di** [comment]
I've added the `good-first-issue` label to this issue.

**Comment by scottilee** [comment]
Is this as simple as removing the 'target="_blank"' in https://github.com/pypa/warehouse/blob/master/warehouse/templates/packaging/detail.html?

**Comment by di** [comment]
Yep!

**Comment by leslie-alldridge** [comment]
added PR and checks have passed

**Comment by merwok** [comment]
The PR linked does not actually fix the links added in #3583

Could someone reopen this ticket?
