### ISSUE TITLE
Error thrown for boto3 and aws.py when executing `docker-compose up`

### ISSUE THREAD

**Issue by willingc** [pypa/warehouse#538]
@dstufft I've been working on updating the developer docs. I'm getting errors with boto3 and aws.py when bringing up docker-compose. A couple of weeks ago there were no errors.

Here's the pastebin of the errors: http://pastebin.com/RXHtiBpA

Possibly related to changes in PR #525.

**Comment by dstufft** [comment]
New dependencies were added, so you'll need to do ``docker-compose build`` to rebuild the docker image.

**Comment by willingc** [comment]
@dstufft Thanks that did the trick. I had to `docker-compose rm` before `docker-compose build` otherwise `docker-compose up` would hang. Is that a normal workflow when rebuilding the docker image?

Here's a WIP preview of the updated Getting Started doc: https://github.com/pypa/warehouse/blob/b3ed0a62901f274569d897707decb3a93344b976/docs/development/getting-started.rst

**Comment by dstufft** [comment]
I've never had to do ``docker-compose rm`` before doing ``docker-compose build``. Normally I just shut down the running containers and then do ``docker-compose build``.

**Comment by willingc** [comment]
Yeah, I thought that was a little weird. I shutdown the running containers, `docker-compose build` would work but `docker-compose up` would hang. Ultimately, `docker-compose rm`, followed by `docker-compose build`, allowed `docker-compose up` to succeed.

The site looks pretty good too. A big improvement over pypi ;)

**Comment by dstufft** [comment]
Going to close this since I don't think there is anything actionable here.
