### ISSUE TITLE
19.0.1 bug 

### ISSUE THREAD

**Issue by MIDFlELDER** [pypa/warehouse#5380]
Dear PyPI  developer    
  i couldn't download  a package (PyInstaller) using pip  19.0.1 (lastert versions of pip)   i had to go back to ver 18.1 to succsesfully download it    i hope this report will help u solving it  sorry i didn t screen the trace back or the error message

**Comment by pradyunsg** [comment]
Please look at the pinned issue in pip's tracker.

**Comment by jamadden** [comment]
Thanks, this is another report of 
https://github.com/pypa/pip/issues/6163
