### ISSUE TITLE
Lost access to account

### ISSUE THREAD

**Issue by mitmul** [pypa/warehouse#5381]
I'm sorry to bother you with my mistake. I created a PyPI account in 2016, then I lost the password and the access to its associated email, so now I cannot recover the access to the account. Can someone please help me? I'm posting this here because PyPI help suggests filing an issue in such case.

**Comment by mitmul** [comment]
@di Thank you for the reply. The username is @mitmul and the email address is shuntasaito AT fb.com.

**Comment by di** [comment]
@mitmul Sent you an email to the address on your Github profile.

**Comment by mitmul** [comment]
Thank you very much. I successfully recovered the account.
