### ISSUE TITLE
Bad command on the rpi-rfsniffer page

### ISSUE THREAD

**Issue by Nickduino** [pypa/warehouse#5388]
**Describe the bug**
Here: https://pypi.org/project/rpi-rfsniffer/

Installation info says:
`sudo python setyp.py install`
Should be:
`sudo python setup.py install`

**Comment by di** [comment]
Hi, thanks for the report, but this is the wrong place for it. You should open this issue in the `rpi-rfsniffer` repo: https://github.com/jderehag/rpi-rfsniffer/issues.
