### ISSUE TITLE
Claim package name 'copernicus'

### ISSUE THREAD

**Issue by emanspeaks** [pypa/warehouse#5391]
The package listed on PyPI has not been updated since Oct 7, 2017.  The homepage links to a non-existent GitHub page.  The owner of the project has no publicly-visible contact information, and appears they no longer have a GitHub account.

I am a developer for a package being developed called 'copernicus' and would like to claim ownership of the name per PEP 541.

Please let me know if you need anything from me to facilitate this.  Thank you!

**Comment by emanspeaks** [comment]
Copernicus is a well established trajectory optimization system maintained by NASA. 
 Currently, it is not open source, but we have been working to create a Python front-end for the software for a couple of years with the intent to try to get it cleared for open source release sometime in the near future.  See https://www.nasa.gov/centers/johnson/copernicus/index.html for details about the existing software.

While it is possible that we could create an entry on the package index under a different name and the "installed" package still called `copernicus`, we've already had some incidents with developers accidentally typing `pip install copernicus`.  We think it would be confusing to our user base if we used a different name on PyPI than the name of the Python package, as evidenced by the mistakes from our own developers.  The existing package on PyPI also seemed to us to be questionable in its content (we considered raising it as a Code of Conduct violation but weren't sure we could strongly make that case), and we would like to avoid having this downloaded onto enterprise machines by mistake.

**Comment by emanspeaks** [comment]
Are there further actions needed on my part to facilitate my claim on this package?  When might I expect to hear the outcome of a decision on this matter?

**Comment by jamadden** [comment]
It seems to me that the project qualifies as abandoned, and no one has been able to reach the owner despite multiple attempts over a longer time period than specified in the PEP.

I can only help facilitate transfers where the owner is responsive, I'm not able to take action otherwise. One of the super-admins would need to step in.

**Comment by emanspeaks** [comment]
How do I get in touch with the super-admins?  Or would you be the one that needs to bring this to their attention?

**Comment by di** [comment]
Hi @emanspeaks, can you share your PyPI username with us?

**Comment by emanspeaks** [comment]
It is also `emanspeaks`

**Comment by di** [comment]
I've added you as an owner. Please note that you won't be able to reuse any of the previously used versions (https://pypi.org/project/copernicus/#history) but you can (and probably should) delete them.
