### ISSUE TITLE
Possible to rename the drf-jsonapi package to drf-jsonapi-legacy ?

### ISSUE THREAD

**Issue by leo-naeka** [pypa/warehouse#5400]
I'm the maintainer of the `drf-jsonapi` PyPI package (https://pypi.org/project/drf-jsonapi/).

Our work has been merged with the widely maintained `djangorestframework-jsonapi` package (https://pypi.org/project/djangorestframework-jsonapi/) and is stale since then.

Recently, we've been asked to release the name in favor of another JSONAPI project. So would it be possible to simply rename it without losing versions history?

**Comment by di** [comment]
Apologies for the late reply. It is not possible to rename a project on PyPI, as this would break installs for anyone depending on an old version of your project.
