### ISSUE TITLE
Lost account access

### ISSUE THREAD

**Issue by firegrass** [pypa/warehouse#5401]
Hi

Sorry to trouble you. I have lost access to my account and email address. PyPI username is firegrass and email is patrick AT tectonic DOT io.

**Comment by ewdurbin** [comment]
We're showing that emails to the address you noted are bouncing, is that expected?

**Comment by firegrass** [comment]
Yes, unfortunately so. The domain expired and someone else has registered it.

**Comment by ewdurbin** [comment]
@firegrass please email ernest@python.org and we'll get you sorted.

**Comment by firegrass** [comment]
Sent. Thanks :+1:
