### ISSUE TITLE
Xgboost - increase size limit request

### ISSUE THREAD

**Issue by RAMitchell** [pypa/warehouse#5405]
https://pypi.org/project/xgboost/

We would like to bundle the nccl static library with our release, enabling distributed and multi-GPU training for xgboost. The nccl binary itself adds around ~80mb, taking our binary size to somewhere around ~100mb.

It would be much appreciated if our limit could be increased to 200mb.

Many thanks!

**Comment by jamadden** [comment]
We've increased the pypi.org limit to 200MB. At that size, please be mindful of your release frequency to be kind to pypi.org and especially its mirrors.
