### ISSUE TITLE
After building source distribution, mac os still installing build folder files

### ISSUE THREAD

**Issue by akshaykanawat** [pypa/warehouse#5408]
I have created a private python package which I hosted on bitbucket, I used "python setup.py sdist" command to build. When I installed the package on my ubuntu system it was working fine, but when I installed it in mac os it was not working. Then I built my package using "python setup.py bdist_wheel" command then it started working fine on both the os. What would be reason behind it?

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: *If your pull request makes a visual change*, include a screenshot of your update. This helps our team give you feedback faster.

**Comment by jamadden** [comment]
Thanks for your report, but unfortunately this is not the correct place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help you build your own packages.

You might see if you can find an answer to your question using the resources at https://packaging.python.org. If not, it has a suggestion about a mailing list to reach out to. Or you could try the general [python-list](https://mail.python.org/mailman/listinfo/python-list).
