### ISSUE TITLE
Any issue with pypi.org page?

### ISSUE THREAD

**Issue by kirankotari** [pypa/warehouse#5416]
**Describe the bug**
Rendering MarkDown and Badges are not working

Links: [shconfparser](https://pypi.org/project/shconfparser/)
[pyenv-win](https://pypi.org/project/pyenv-win/)

**Expectation**
Expecting a banner if the pypi is down for maintenance
github links: [shconfparser](https://github.com/network-tools/shconfparser)
[pyenv-win](https://github.com/pyenv-win/pyenv-win/)

**My Platform**
OS: Mac 
Browser: Tested in Chrome and Safari

**Comment by jamadden** [comment]
Thanks for the report! 

The release metadata for pyenv-win is missing the long-description-content-type. I see that present in setup.cfg, but it appears that the release was created with a version of setuptools that's too old to understand that. You need at least [https://setuptools.readthedocs.io/en/latest/history.html#v36-4-0](36.4), and it appears that 28.8 was used.

The images for https://pypi.org/project/shconfparser/ do not match what's in the current GitHub source for the file, they have been rewritten to URLs like https://warehouse-camo.cmh1.psfhosted.org/f849101b3ec6773555756484d868d02f494fdea5/68747470733a2f2f7472617669732d63692e6f72672f6e6574776f726b2d746f6f6c732f7368636f6e667061727365722e7376673f6272616e63683d6d6173746572

Those URLs are currently timing out:
```console
$ http https://warehouse-camo.cmh1.psfhosted.org/f849101b3ec6773555756484d868d02f494fdea5/68747470733a2f2f7472617669732d63692e6f72672f6e6574776f726b2d746f6f6c732f7368636f6e667061727365722e7376673f6272616e63683d6d6173746572
HTTP/1.1 504 Gateway Time-out
Connection: keep-alive
Content-Length: 183
Content-Type: text/html
Date: Mon, 11 Feb 2019 15:29:10 GMT
Server: nginx/1.13.9

<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.13.9</center>
</body>
</html>
```

I observe this across projects (e.g., gevent) so this very well could be a PyPI infrastructure issue. /cc @dstuft @ewdurbin

**Comment by jamadden** [comment]
The PSF infrastructure team has corrected the image issue. Thanks again for the report!

**Comment by samapriya** [comment]
Am having the same issues, links for png replaced but not being rendered (for example) getting 

504 Gateway Time-out

https://warehouse-camo.cmh1.psfhosted.org/a3587af4a84288f6be40552a881d00bc0fee976d/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f32383830363932322f35333039363735342d64343935656538302d333465642d313165392d393830642d3431383630316263393735612e706e67

**Comment by brainwane** [comment]
@jamadden should we reopen?

**Comment by jamadden** [comment]
I can't reproduce any problems now and I also haven't seen any recent reports. Given that this report was 6 days ago and without any intervening reports, I don't think this particular ticket needs re-opened. If there are new occurrences I would encourage the use of a new ticket so that specifics can be nailed down there without clutter.

**Comment by collinstocks** [comment]
This is happening again, including on the original reporter's PyPI page: https://pypi.org/project/shconfparser/

**Comment by ewdurbin** [comment]
We recently deployed a new version of camo that appears to have crashed. I've restarted the service and we'll determine what is causing the crash.

**Comment by ewdurbin** [comment]
captured the crash

```
pypi-camo-web-5d956c8874-6qwqk web /opt/camo/server.js:75
pypi-camo-web-5d956c8874-6qwqk web     error_log("" + msg + ((error != null) || '') + ": " + ((url != null ? url.format() : void 0) || 'unknown'));
pypi-camo-web-5d956c8874-6qwqk web                                                                               ^
pypi-camo-web-5d956c8874-6qwqk web 
pypi-camo-web-5d956c8874-6qwqk web TypeError: url.format is not a function
pypi-camo-web-5d956c8874-6qwqk web     at four_oh_four (/opt/camo/server.js:75:79)
pypi-camo-web-5d956c8874-6qwqk web     at Server.<anonymous> (/opt/camo/server.js:323:18)
pypi-camo-web-5d956c8874-6qwqk web     at emitTwo (events.js:126:13)
pypi-camo-web-5d956c8874-6qwqk web     at Server.emit (events.js:214:7)
pypi-camo-web-5d956c8874-6qwqk web     at parserOnIncoming (_http_server.js:619:12)
pypi-camo-web-5d956c8874-6qwqk web     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
pypi-camo-web-5d956c8874-6qwqk web 2019/10/08 14:13:35.036253 [ERR] (cli) unexpected exit from subprocess (1)
```

**Comment by ewdurbin** [comment]
Fix for this error landed and deploying now: https://github.com/pypa/warehouse-camo/pull/4
