### ISSUE TITLE
Request for file size limit exemption

### ISSUE THREAD

**Issue by wesleyw72** [pypa/warehouse#5417]
Project: [https://test.pypi.org/project/nd4j/](https://test.pypi.org/project/nd4j/)
Size request: 300MB
Which indexes to increase: both PyPi and Test PyPi

Hello, could you please allow us to submit files of size up to 300MB? We would like to submit both a .whl and a tar.gz of this size.

This package is a bundle of JARs for [nd4j](https://github.com/deeplearning4j/deeplearning4j/tree/master/nd4j), a scientific computing library for the JVM. We use [py4j](https://github.com/bartdag/py4j) to call into these JARs from Python. Putting them in their own package will mean that each project using them can depend on this package instead of individually bundling the JARs. 

Thank you!

**Comment by jamadden** [comment]
We've increased the limit on both pypi.org and test.pypi.org to 300MB. At that size, please be mindful of your release frequency in order to be kind to pypi and its mirrors.
