### ISSUE TITLE
Request new Trove Classifier for pytest plugins

### ISSUE THREAD

**Issue by nicoddemus** [pypa/warehouse#542]
Currently pytest contains dozens of plugins on PyPI (100+), as a simple [search](https://pypi.python.org/pypi?%3Aaction=search&term=pytest&submit=search) for "pytest" shows.

We would like to make it easier for users to find these plugins, as some plugins are left out for not following this naming scheme (e.g. [backports.unittest_mock](https://pypi.python.org/pypi/backports.unittest_mock), [jaraco.mongodb](https://pypi.python.org/pypi/jaraco.mongodb)), so we request to include a new trove classifier:

```
Framework :: Pytest :: Plugin
```

Pytest's maintainers (myself included) [demonstrated interest](https://github.com/pytest-dev/plugincompat/issues/16) of supporting this officially by advertising it in the documentation and the [plugincompat]() service (which automatically finds plugins and check compatibility against different pytest versions).

(I created a duplicate of this issue at [pypa/pypi](https://bitbucket.org/pypa/pypi/issue/301) as I'm not sure which repository handles the classifiers).

**Comment by pekkaklarck** [comment]
I have also requested new classifiers without any reply. I submitted two requests to pypa/pypi project on BitBucket over two years ago ([see](https://bitbucket.org/pypa/pypi/issues/92/) [here](https://bitbucket.org/pypa/pypi/issues/93)), and then a bit later sent emails to catalog-sig and distutils-sig. No reply whatsoever.

I'm now sending an email to pypa-dev that is owner of this organization. I'll mention this issue in the email too.

**Comment by pekkaklarck** [comment]
Great, pypa-dev group shown on https://github.com/pypa is closed and my email bounced. This is getting annoying.

**Comment by nicoddemus** [comment]
Yeah, I'm almost giving up on the whole idea... :worried:

Thanks for the note though

**Comment by pekkaklarck** [comment]
Here's the email I sent (needed to join the list first):
https://groups.google.com/forum/#!topic/pypa-dev/JRv7BXsNX_w

Hopefully we get a reply. Our request even happen to be very much related.

**Comment by nicoddemus** [comment]
Yes, fingers crossed! :smile:

**Comment by nicoddemus** [comment]
Btw, I appreciate you taking the time to ping me back on this issue. Thanks!

**Comment by benjixx** [comment]
@nicoddemus I just brought this to the table again:
https://groups.google.com/d/msg/pypa-dev/JRv7BXsNX_w/AUfbrnvfBQAJ

Looks like @pekkaklarck's request has been already processed successfully, but yours has been overseen.

**Comment by nicoddemus** [comment]
Thanks for letting me know! :smile:

**Comment by benjixx** [comment]
@nicoddemus We have now a dedicated Trove Classifier:

```
Framework :: Pytest
```

This already shows up in the [Trove Classifiers List](https://pypi.python.org/pypi?%3Aaction=list_classifiers).

I guess as soon as this is mentioned somewhere in the pytest documentation this issue can be closed.

**Comment by nicoddemus** [comment]
@benjixx thanks for letting me know! I already sent an announcement email with this change, and will take care of updating the documentation myself later. :grin:
