### ISSUE TITLE
pdfminer3k 1.3.1 , some pdf, get content will throw a error

### ISSUE THREAD

**Issue by longzaitianxia23** [pypa/warehouse#5422]
**Describe the bug**
i want to use pdfminer3k get pdf content ，Most of the is  ok ,but some will throw a error

**My Platform**
python 3.6  + pdfminer3k 1.3.1

**Code**

from urllib.request import urlopen
from pdfminer.pdfinterp import PDFResourceManager, process_pdf
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from io import StringIO

def readPDF(pdfFilePath):
    print(u'打开'+pdfFilePath+'PDF链接')
    pdfFile = urlopen(pdfFilePath)
    rsrcmgr = PDFResourceManager()
    retstr = StringIO()
    laparams = LAParams()
    print(u'转换'+pdfFilePath+'PDF文件内容')
    
    device = TextConverter(rsrcmgr, retstr, laparams=laparams)  
    process_pdf(rsrcmgr, device, pdfFile)
    print(u'获取'+pdfFilePath+u'PDF文件内容')
    content = retstr.getvalue()
    print('关闭相关处理器')
    device.close()
    retstr.close()
    pdfFile.close()
    return content

print(readPDF('http://xinpi.cs.com.cn/new/file/bulletin/2019/2/11/1205822887.PDF'))

**Additional context**

you can try run this

**Comment by longzaitianxia23** [comment]
and hava other  problem
i can not catch the error，some time
it will  Cause the program to crash


Code 




from urllib.request import urlopen
from pdfminer.pdfinterp import PDFResourceManager, process_pdf
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from io import StringIO



def readPDF(pdfFilePath):
    print(u'打开'+pdfFilePath+'PDF链接')
    pdfFile = urlopen(pdfFilePath)
    rsrcmgr = PDFResourceManager()
    retstr = StringIO()
    laparams = LAParams()
    print(u'转换'+pdfFilePath+'PDF文件内容')
    
    device = TextConverter(rsrcmgr, retstr, laparams=laparams)  
    process_pdf(rsrcmgr, device, pdfFile)
    print(u'获取'+pdfFilePath+u'PDF文件内容')
    content = retstr.getvalue()
    print('关闭相关处理器')
    device.close()
    retstr.close()
    pdfFile.close()
    return content




i = 0

while True:
    print(i)
    i = i + 1
    try:
        str = readPDF('http://xinpi.cs.com.cn/new/file/bulletin/2019/2/13/1205826626.PDF')
        print(str[:20])
        readPDF('http://xinpi.cs.com.cn/new/file/bulletin/2019/2/11/1205822887.PDF')
    except :
        print('error')
    else:
        print('ok')

**Comment by jamadden** [comment]
Thanks for the report,  it this is not the place for it. This tracker is just for issues with the software that runs the website PyPI.org itself. It cannot help with packages distributed from there. You will need to contact the maintainers of pdfminer3k instead.
