### ISSUE TITLE
JapaneseTokenizer Error with mecab while installing

### ISSUE THREAD

**Issue by jiterika** [pypa/warehouse#5423]
Hi All,
I am trying to install JapaneseTokenizer and i get the following error

Using cached https://files.pythonhosted.org/packages/ac/48/295efe525df40cbc2173748eb869290e81a57e835bc41f6d3834fc5dad5f/mecab-python3-0.996.1.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: mecab-config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rd/qqy1bpm93qj1qcmrj8624qz91pyzr5/T/pip-build-9y__vnlq/mecab-python3/setup.py", line 29, in <module>
        inc_dir  = mecab_config("--inc-dir")
      File "/private/var/folders/rd/qqy1bpm93qj1qcmrj8624qz91pyzr5/T/pip-build-9y__vnlq/mecab-python3/setup.py", line 27, in mecab_config
        return os.popen("mecab-config " + arg).readlines()[0].split()
    IndexError: list index out of range

Can anyone help me fix it. Python3 is my default Python environment

Thank You

**Comment by jamadden** [comment]
Thanks for the report, but this isn't the correct place for it. This tracker is only for issues with the software that runs pypi.org itself. It can't help with packages distributed from there. You'll need to contact the maintainers of `mecab-python3` instead; this information is often on the PyPI page for the project.

**Comment by jamadden** [comment]
As an aside, it looks like this package depends on a program called `mecab-config` that's not available on your system.

**Comment by jiterika** [comment]
Hi @jamadden,
Thank you for the reply, how can i contact the maintainers, i don't see any other information other than the name. apologies if it's a lame question, but i am not very much aware of the platform.

**Comment by jamadden** [comment]
The PyPi page (https://pypi.org/project/mecab-python3/) links directly to the github repository as the homepage (https://github.com/SamuraiT/mecab-python3) which includes an issue tracker.

**Comment by jiterika** [comment]
Thank you @jamadden

**Comment by JayasreeKaveti** [comment]
Hi @jiterika, Please help me with how you solved this issue. I too am trying to install mecab using pip3 (pip3 install mecab) and getting into this error.

3.020 Collecting mecab==0.996 (from -r requirements.txt (line 25))
3.030   Downloading mecab-0.996.tar.gz (63 kB)
3.035      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 18.4 MB/s eta 0:00:00
3.045   Installing build dependencies: started
4.766   Installing build dependencies: finished with status 'done'
4.767   Getting requirements to build wheel: started
5.019   Getting requirements to build wheel: finished with status 'error'
5.027   error: subprocess-exited-with-error
5.027   
5.027   × Getting requirements to build wheel did not run successfully.
5.027   │ exit code: 1
5.027   ╰─> [20 lines of output]
5.027       **/bin/sh: mecab-config: command not found**
5.027       Traceback (most recent call last):
5.027         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
5.027           main()
5.027         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
5.027           json_out['return_val'] = hook(**hook_input['kwargs'])
5.027         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
5.027           return hook(config_settings)
5.027         File "/tmp/pip-build-env-t3byyvth/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
5.027           return self._get_build_requires(config_settings, requirements=['wheel'])
5.027         File "/tmp/pip-build-env-t3byyvth/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
5.027           self.run_setup()
5.027         File "/tmp/pip-build-env-t3byyvth/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
5.027           self).run_setup(setup_script=setup_script)
5.027         File "/tmp/pip-build-env-t3byyvth/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
5.027           exec(code, locals())
5.027         File "<string>", line 43, in <module>
5.027         File "<string>", line 14, in cmd2
5.027         File "<string>", line 10, in cmd1
5.027       IndexError: list index out of range
5.027       [end of output]
5.027   
5.027   note: This error originates from a subprocess, and is likely not a problem with pip.
5.030 error: subprocess-exited-with-error
5.030 
5.030 × Getting requirements to build wheel did not run successfully.
5.030 │ exit code: 1
5.030 ╰─> See above for output.
5.030 
5.030 note: This error originates from a subprocess, and is likely not a problem with pip.
