### ISSUE TITLE
pypi.org passwords not hashed

### ISSUE THREAD

**Issue by mikedh** [pypa/warehouse#5429]
**Describe the bug**
It appears that passwords on pypi.org may not be stored as hashes? If you go to account settings, and click "show password", it displays your actual user password in plain text. Does this mean the passwords aren't stored as a [bcrypt](https://github.com/pyca/bcrypt/) or other hash? It seems like most people would [argue against](https://security.stackexchange.com/questions/120540/why-shouldnt-i-store-passwords-in-plaintext) storing passwords as text.

**Expected behavior**
Passwords are not stored or accessible as plain text. Only the hashed and salted form is stored.

**To Reproduce**
1) Go to https://pypi.org/manage/account/
2) Check "show passwords"
3) See actual password, in plain text

**Comment by dstufft** [comment]
I'm pretty sure that you have something auto filling in passwords, the password are stored using argon2 and those fields are blank when I go to those pages.
