### ISSUE TITLE
Help accessing the `passer` wheel

### ISSUE THREAD

**Issue by affixalex** [pypa/warehouse#5434]
I can't recall what e-mail address I had used to register on pypi, it's been a few years!

I want to resume work on https://github.com/affixalex/passer which is the original repository responsible for https://pypi.org/project/passer/ and I've created a new PyPi account with the username `affixalex`.

Could you add my new account as a maintainer on that wheel?

**Comment by yeraydiazdiaz** [comment]
Hi @affixalex, the email address is the just current maintainer's user name at gmail. You should be able to reset the password and make the changes yourself.

**Comment by yeraydiazdiaz** [comment]
Closing as I assume this was resolved, if not feel free to add another comment.
