### ISSUE TITLE
PEP 541: upgrade to owner 

### ISSUE THREAD

**Issue by soumith** [pypa/warehouse#5455]
Greetings,

I am one of the maintainers of the PyTorch project. I have pushed the binaries for all releases of the pytorch project ( pypi username: soumith )

I currently have maintainer (but not owner) rights to `torch`, `pytorch` and `torchvision` projects.

@graingert ( Thomas.Grainger on PyPI ) is the current owner to these packages. Thomas is not affiliated or involved with the PyTorch project (and has never been, beyond this goodwill contribution of registering the placeholder PyPI packages).

I am requesting owner rights to these packages.

#### The context

When PyTorch released, we weren’t setup to push to PyPI because of package size limits, and unfamiliarity with building controlled linux wheels.
Hence, in the initial months, we didn’t register the pytorch, torch and torchvision PyPI packages ourselves (we were shipping anaconda binaries).

Thomas Grainger kindly registered the package names on PyPI, and put a dummy package with an error message, pointing users to our website. 
 
Over time, I requested that he add me as a collaborator to the project, and finally I started pushing binaries directly to PyPI.
 
As PyTorch grew, we (PyTorch devs) wanted to make sure that we own the PyPI package (and not just as a collaborator), so we requested Thomas to transfer ownership.

Thomas had one piece of correspondence that acknowledged that he’ll look into it after his holiday break (on April 3rd, 2018), but we received no subsequent correspondence for months.
We reached out to him over email (many emails over several months), twitter and github.
We’ve received no email response, to any correspondence since April 3rd.
He responded once on Twitter direct messages on 31st Oct 2018, saying "I'm happy to transfer the repo in person - face to face", and again there was radio silence to subsequent replies.

From what we can see Thomas is active on github, and PyPI.

We are looking for resolution into this matter, after months of good faith attempts to reach out to Thomas and trying to resolve the matter directly.

**Comment by yeraydiazdiaz** [comment]
Hi @soumith, there seems to be a misunderstanding, you are currently co-owner of all three projects `torch`, `pytorch` and `torchvision`, Thomas changed your status to Owner on all three projects on 2019-02-27.

If you visit https://pypi.org/manage/project/pytorch/collaboration/ and you should see your username listed as owner of the project.

**Comment by soumith** [comment]
thanks @yeraydiazdiaz . I opened the issue on Feb 19th, 2019. It looks like Thomas changed the ownership on 27th.

Thanks a lot @graingert !
