### ISSUE TITLE
Increase size limit request h2o4gpu

### ISSUE THREAD

**Issue by sh1ng** [pypa/warehouse#5483]
Hi,

- https://github.com/h2oai/h2o4gpu
- https://test.pypi.org/project/h2o4gpu/
- https://pypi.org/project/h2o4gpu/
- Our current release ~ 350 Mb
- We link our project statically with CUDA dependencies and support wide range of CUDA devices so the library is quite big. 

Could you increase limit to 500 Mb?

**Comment by jamadden** [comment]
Hello, very large packages like that don't produce a very good user experience, so generally they should be avoided if possible. Some ways a project can limit the size of their dependencies:

* depend on platform-specific tags and system libraries instead of bundling binaries
* break the package into smaller packages that depend on each other as necessary
* side-load large models or datasets via downloads from elsewhere at runtime/installtime.

Would any of those be an option for your project?

**Comment by sh1ng** [comment]
From our experience users have a lot of issues using correct version of CUDA and Nvidia drivers. That's why we decided that having large pkg is a less evil than a lot of effort during installation.

**Comment by sh1ng** [comment]
A bit of technical context. We have to compile cuda code with a few cuda compute capabilities e.g.  _-gencode=arch=compute_35,code=sm_35;-gencode=arch=compute_50,code=sm_50;-gencode=arch=compute_52,code=sm_52;-gencode=arch=compute_60,code=sm_60;-gencode=arch=compute_61,code=sm_61;-gencode=arch=compute_70,code=sm_70;-gencode=arch=compute_75,code=sm_75;-gencode=arch=compute_75,code=compute_75_ that results in bloat of output binary. Also we prefer to use static linking with cublas, cusparse, etc as CUDA toolkit is not compatible from version to version. Tensorflow package also gigantic by the same reason(while it requires a certain version of CUDA to be installed).

**Comment by jamadden** [comment]
Thank you for the information. The PyPI moderators have increased the upload limit to 500MB on pypi.org and test.pypi.org. With that done, we ask you to please be very mindful of the stress this puts on PyPI, our CDN, other mirrors, and users. Please manage the frequency of your releases and don't upload nightly or frequent dev builds.

We would also encourage you to add a long description (`setup` keyword `long_description`) to your releases providing information on what they are, what platforms they support, etc, and perhaps cautioning users about their extreme size.
