### ISSUE TITLE
Size limit extension : targetDB

### ISSUE THREAD

**Issue by sdecesco** [pypa/warehouse#5485]
Hi, 

I would like the upload limit to be increased for my project targetDB ( https://pypi.org/project/targetDB/ ) 

The most recent version I try to upload weight 62.3 MB. 
This size come mostly from several compressed json files that are used to populate certain tables of a relational database upon it's creation. 

I have tried different compression methods but could not go under 60 MB for this release. 

I expect the releases to go progressively larger with time as the json files are from datasources that are updated every 6months/year with new data.

I imagine 100 MB would be enough for at least 1 - 2 year of updates. 

Thanks for your help, 

Stephane 

(Pypi username: sdecesco)

**Comment by jamadden** [comment]
Hi @sdecesco , I've set the limit for targetDB to 100MB on pypi.org.
