### ISSUE TITLE
Unable to verify email address

### ISSUE THREAD

**Issue by felnne** [pypa/warehouse#5489]
Hi, apologies if this is the wrong place to report this, but I am unable to receive an email verification link sent to webapps@bas.ac.uk.

Would someone be able to check if the emails are bouncing to that address?

I’ve asked our IT department to check if anything is being blocked and they can’t see anything.

Interestingly I have been able to successfully receive the email on test.pypi.org.

**Comment by jamadden** [comment]
According to our logs, we have sent two email verifications to that address in the last week, and both have been delivered.

**Comment by felnne** [comment]
Hi,

Thanks for confirming that - I will chase up with our IT department.
