### ISSUE TITLE
new Trove Classifier Request: Plone - Addon / Plone - Core

### ISSUE THREAD

**Issue by loechel** [pypa/warehouse#5490]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: Plone :: Addon`
* `Framework :: Plone :: Core`

## Why do you want to add this classifier?

We want to specifically query for Addons and Core Modules of the Plone Family, to use and retrieve via API.

Plone currently consists of around 400 core packageas and several hundred addon packages.

**Comment by jamadden** [comment]
The `Framework :: Plone :: Theme` classifier was added back in https://github.com/pypa/pypi-legacy/issues/573 This seems to be of the same nature, and I understand that @loechel is on the Plone Foundation board (as was the requestor for the original issue), so I'm happy to add these.
