### ISSUE TITLE
R programming language trove classifier

### ISSUE THREAD

**Issue by flying-sheep** [pypa/warehouse#5495]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Programming Language :: R`

## Why do you want to add this classifier?
Projects like rpy2, pyRserve, and others allow interactions between Python and the R programming language. It would be great to be able to search for such projects on PyPI, especially since “R” is notoriously hard to search.

**Comment by pradyunsg** [comment]
Thanks for filing this @flying-sheep!

I've gone ahead and added the requested classifier 'Programming Language :: R'.

**Comment by flying-sheep** [comment]
Thank you!
