### ISSUE TITLE
Not allowed to upload to pypi but test.pypi

### ISSUE THREAD

**Issue by edouard-lopez** [pypa/warehouse#5503]
**Describe the bug**

I successfully upload my package to `test.pypi.org` (see. [`pure`](https://test.pypi.org/project/pure/)). However, when I try to upload to `pypi.org` I got an error `403`:

> HTTPError: 403 Client Error: The user 'edouard-lopez' isn't allowed to upload to project 'Pure'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/                                

Yet, there is [no `pure` project](https://pypi.org/project/Pure/) on pypi.org.

Note that my package name is lowercase `pure`, but the error mention a capitalize name `Pure`. 

```
❯ make upload-package
Pypi username:
twine upload --username edouard-lopez dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading pure-1.2.2-py3-none-any.whl
100%|██████████| 12.6k/12.6k [00:01<00:00, 7.44kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Client Error: The user 'edouard-lopez' isn't allowed to upload to project 'Pure'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
make: *** [upload-package] Error 1
makefile:107: recipe for target 'upload-package' failed  
```

**Expected behavior**

If package is accepted/refused by `test.pypi.org` it should be the same on `pypi.org`.

**To Reproduce**

**My Platform**

```
NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"
VERSION_ID="19"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tara
UBUNTU_CODENAME=bionic
```

```
❯ python3 --version
Python 3.6.7
```

```
❯ twine --version
twine version 1.13.0 (pkginfo: 1.5.0.1, requests: 2.21.0, setuptools: 40.8.0,
requests-toolbelt: 0.9.1, tqdm: 4.31.1) 
```

**Additional context**

User is the same between `test.pypi.org` and `pypi.org`, password differ.

**Comment by di** [comment]
This package already exists on PyPI, but the owner has removed all the releases (hence why it appears to be 404). I've reached out to the current owner to see if they would be willing to transfer it to you.

**Comment by rdpate** [comment]
Please transfer the package.

**Comment by di** [comment]
Thanks @rdpate.

@edouard-lopez, I've added `edouard-lopez` as an owner of the `Pure` package. Please note that you won't be able to make a release with versions `0.0.0`, `0.1.0`, or `0.1.1` as these have been previously used, and PyPI prohibits reuse of version numbers.

**Comment by edouard-lopez** [comment]
Thanks :)

**Comment by edouard-lopez** [comment]
@di why is @rdpate [listed as a maintainer](https://pypi.org/project/pure/)? I would love to have contributors but I'm not sure that's the expected behavior.

![selection_232](https://user-images.githubusercontent.com/1212392/53629224-56cc9400-3c0d-11e9-84fc-eba909cdae7f.png)

**Comment by edouard-lopez** [comment]
[listed as a maintainer](url)

**Comment by chuck1** [comment]
Hello @di I believe I am the same situation as @edouard-lopez. The project name in question is "otter". Is there a proper channel for me to request that the project be transfered to me? Thanks!

**Comment by di** [comment]
@chuck1 Please create a separate issue in this repo. [There is a large backlog of similar issues](https://github.com/pypa/warehouse/issues?q=is%3Aissue+is%3Aopen+label%3A%22PEP+541%22), be aware that unless you reach out to the maintainer yourself, and they are receptive, it is unlikely that this will be resolved as quickly as this example.
