### ISSUE TITLE
How can I update my package description without creating a new release?

### ISSUE THREAD

**Issue by edouard-lopez** [pypa/warehouse#5505]
**Describe the bug**
When working on a project it seems I can't update the package's description without a new release. If I do so I get:

    HTTPError: 400 Client Error: File already exists. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/                                                                                                  

**Expected behavior**

- release 1.2.3
- find a typo in README.md
- edit typo
- release 1.2.3

This kind of edit doesn't impact code so shouldn't require a new release.

**To Reproduce**
- release 1.2.3
- find a typo in README.md
- edit typo
- release 1.2.3

**My Platform**

**Additional context**

**Comment by jamadden** [comment]
The releases that PyPI stores are immutable for security reasons. The description is part of the metadata included in the release artifact and cannot be changed. You’ll need to upload a new release. Some projects use the `.post0` Part of a PEP440 version for non-code changes like that.
