### ISSUE TITLE
Home page link to packaging is broken

### ISSUE THREAD

**Issue by IvoMerchiers** [pypa/warehouse#5507]
On the front page there is a link with the name:
`Learn how to package your Python code for PyPI.`
Which links to [https://packaging.python.org/tutorials/distributing-packages](https://packaging.python.org/tutorials/distributing-packages), which is a non-existing page.

This should either be fixed with the correct link (which I do not know), or with the alternative link that is discussed in the FAQ, namely: https://packaging.python.org/tutorials/packaging-projects/

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
Thanks for the report! I've put the `good-first-issue` label on this issue.

**Comment by oscarmcm** [comment]
@di I created a PR for this issue, let me know if this need something else.
