### ISSUE TITLE
CPU Usage too high

### ISSUE THREAD

**Issue by kimpla7** [pypa/warehouse#5515]
**What's the problem this feature will solve?**
The CPU usage to be less.

**Describe the solution you'd like**
I'd like it to consume less resources.

**Additional context**
I think I made my point clear. My i5 8220 is wasting 22% on average with the whatsapp-cli task. It's just too much.

**Comment by jamadden** [comment]
It sounds as if you're describing a problem with https://pypi.org/project/whatsapp-cli/. Unfortunately, this is not the place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help with packages downloaded from there. You'll need to contact the maintainers of the project causing problems directly. Based on the information on the project's page, that may be at https://github.com/yausername/whatsapp-cli/issues

**Comment by kimpla7** [comment]
Thank you very much and sorry for the wrong post.
