### ISSUE TITLE
File size limit exemption or increase for pyqt5-tools

### ISSUE THREAD

**Issue by altendky** [pypa/warehouse#5516]
- A link to your project on PyPI (or Test PyPI)
  - https://pypi.org/project/pyqt5-tools/
- The size of your release, in megabytes
  - 63MB is the largest build result for the most recent dev release
- Which index/indexes you need the increase for (PyPI, Test PyPI, or both)
  - PyPI: definitely
  - Test PyPI: I honestly don't use Test PyPI, but I would of course like the increase or exemption on both in case I change my habits in the future
- A brief description of your project, including the reason for the additional size.

This package 1) provides a small pyqt5.dll which the author does not distribute in binary form and 2) also provides several Qt applications and some wrapper CLI utilities for them as an alternative to the normal Qt installation process from their website.  1) saves users from having to manage to build it themselves and 2) makes the extra Qt tools easy to get with regular Python mechanisms instead of a manual installation etc.

Thanks for everything.

Cheers,
-kyle

**Comment by jamadden** [comment]
I've set the limit to 100MB for pyqt5-tools on pypi.org. (If you begin using test.pypi.org, you'll need to create the project first before we can make a size exemption.)

As the sizes begin to go up, please keep release frequency in mind. Larger files coupled with many (pre-) releases place more of a burden on PyPI, its CDN and other mirrors.

**Comment by altendky** [comment]
@jamadden, thanks for the increase and the prompt response.  Do you have any guidance on PyPA's costs associated with storage?  I appreciate the free service but could consider donating.  Or, perhaps the cost would be prohibitive enough to make me much more wary.

**Comment by jamadden** [comment]
Sorry, no I don't, I just know that we (PyPI moderators) are asked to keep an eye on that for limit increases. Normally for projects in this size range we don't specifically mention release frequency as a concern. I just noticed that this project has a substantial number of pre-releases at a relatively fast clip and decided to mention it. I don't think anything there is too extreme or a problem though, just something to keep in mind moving forward.
