### ISSUE TITLE
markdown not rendered correctly

### ISSUE THREAD

**Issue by nschloe** [pypa/warehouse#5520]
Follow-up on #3442.

I have a number of packages on pypi, the README.md of some of which is rendered correctly (e.g., https://pypi.org/project/fastfunc/), and not for others (e.g., https://pypi.org/project/blacktex/). There is no indication of what's wrong so I don't know how to fix it.

Any hints?

**Comment by jamadden** [comment]
In the PyPI metadata, I see that release 0.1.7 of `fastfunc` has the metadata `Description-Content-Type: text/markdown`, but release 0.1.2 of `blacktex` has a blank `Description-Content-Type`. A blank value for that field means to treat it as ReST.

The `METADATA` record in [the wheel for blacktex-0.1.2](
https://files.pythonhosted.org/packages/01/79/2e525b474467d20558f4eaf5ce299928c271e5cd7251f970e620b577d9b8/blacktex-0.1.2-py2.py3-none-any.whl) appears to have a correct value for that field:
```
   1   │ Metadata-Version: 2.0
   2   │ Name: blacktex
   3   │ Version: 0.1.2
   4   │ Summary: Cleans up your LaTeX files
   5   │ Home-page: https://github.com/nschloe/blacktex
   6   │ Author: Nico Schlömer
   7   │ Author-email: nico.schloemer@gmail.com
   8   │ License: License :: OSI Approved :: MIT License
   9   │ Platform: UNKNOWN
  10   │ Classifier: License :: OSI Approved :: MIT License
  11   │ Classifier: Development Status :: 3 - Alpha
  12   │ Classifier: Operating System :: OS Independent
  13   │ Classifier: Programming Language :: Python
  14   │ Classifier: Programming Language :: Python :: 2
  15   │ Classifier: Programming Language :: Python :: 3
  16   │ Classifier: Topic :: Text Editors :: Text Processing
  17   │ Classifier: Topic :: Text Processing
  18   │ Classifier: Topic :: Text Processing :: Markup
  19   │ Classifier: Topic :: Text Processing :: Markup :: LaTeX
  20   │ Classifier: Topic :: Utilities
  21   │ Description-Content-Type: text/markdown
  22   │ Requires-Dist: pipdate (<0.4.0,>=0.3.0)
  23   │
  24   │ # blacktex
  25   │
  26   │ Cleans up your LaTeX files.
  27   │
```

However, note that it specifies a version of `2.0`. `Description-Content-Type` was only added [in version 2.1](https://packaging.python.org/specifications/core-metadata/#description-content-type).  (`fastfunc` only has a sdist, and the sdist's `PKG-INFO` uses metadata 2.1; likewise the sdist for `blacktex` also uses metadata 2.1, but it was uploaded *after* the wheel, and the metadata for display comes from the first uploaded artifact.) Did you perhaps use a version of setuptools [prior to 38.6.0](https://setuptools.readthedocs.io/en/latest/history.html#v38-6-0) to build the wheel artifact for `blacktex`?

**Comment by nschloe** [comment]
Thanks for the concise feedback!

I have no idea how Metadata Version 2.0 came about. Locally it's 2.1, and I'm using the toolchain in fairly up-to-date versions (setuptools 40.8.0). Will try another upload momentarily.

**Comment by nschloe** [comment]
Okay, I'm generating tar.gz and the wheel via
```
python3 setup.py sdist
python3 setup.py bdist_wheel --universal
```
This is with Python 3.7.2+ and setuptools 40.8.0. When unzipping the wheel, I see that METADATA says
```
Metadata-Version: 2.0
```
How can I further debug this?

**Comment by nschloe** [comment]
Okay, got it: I had an older version of wheel installed (0.30.0). Updated, issue now fixed. Thanks for the help!
