### ISSUE TITLE
PEP 541: mysql-connector-python  vs. mysql-connector

### ISSUE THREAD

**Issue by johannes** [pypa/warehouse#5537]
Hi,

I am leading the team at Oracle, which is developing our MySQL Connector for Python.

We publish our library on https://pypi.org/project/mysql-connector-python/

Due to some internal issues we didn't publish the 2.1 series on PyPi. An external person apparently tried to be helpful and registered https://pypi.org/project/mysql-connector/ serving some of the 2.1 releases, but didn't update any further for more than 1.5 years. This now seems to confuse people, as that page claims "Author: Oracle and/or its affiliates"

Is there, under PEP541, or some related policy, a way that `mysql-connector` is marked as _abandoned_ or similar and forwards to `mysql-connector-python`?

**Comment by jamadden** [comment]
Hi. Have you attempted to contact the author of that project,(e.g., at https://github.com/sanpingz/mysql-connector/issues) to see if they'd be willing to release the name ?

**Comment by johannes** [comment]
I sent out mails to the domain listed on the GH profile page without response. I now also filed https://github.com/sanpingz/mysql-connector/issues/10

**Comment by sanpingz** [comment]
I have deleted https://pypi.org/project/mysql-connector.

**Comment by markypooch** [comment]
Referencing @johannes 

A forwarding feature to a new package from an abandoned package would be quite nice with a warning  message containing a TTL before the old package is axed

**Comment by sixers** [comment]
@sanpingz Deleting mysql-connector broke our builds. From https://pypistats.org/packages/mysql-connector I can see that mysql-connector is still being downloads more than 10k times daily, so possibly it broke many people builds as well. Could you please restore deleted package? If possible, can you come up with smooth transition to mysql-connector-python package?

**Comment by matdodgson** [comment]
There's now a version 2.2.4 on [https://pypi.org/project/mysql-connector/#history]. There's no source code for that version at the github account. Is it a fake?

**Comment by sanpingz** [comment]
I uploaded again to smooth the transition, and put deprecation message. Let me know if anything else I can do to clear the confusion.

**Comment by markypooch** [comment]
We had builds fail as well. Im not very familiar with the community, but is there a defined process of getting the word out before removing a package? Especially one as heavily used as mysql-connector?

**Comment by ewengillies** [comment]
My build broke as well. It seems to find the "new" `mysql-connector` uploaded today breaks our builds as well.

This is the error message:

```
  Running setup.py install for wrapt: started
    Running setup.py install for wrapt: finished with status 'done'
  Running setup.py install for pycparser: started
    Running setup.py install for pycparser: finished with status 'done'
  Running setup.py install for nltk: started
    Running setup.py install for nltk: finished with status 'done'
  Running setup.py install for mongoengine: started
    Running setup.py install for mongoengine: finished with status 'done'
  Running setup.py install for mysql-connector: started
    Running setup.py install for mysql-connector: finished with status 'error'
    Complete output from command /mnt/opt/util-software/conda/envs/utilkg/bin/python -u -c "import setuptools, tokenize;__file__='/mnt/tmp/pip-install-yo0pshal/mysql-connector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /mnt/tmp/pip-record-u594bpde/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
```

Needless to say, googling this error comes up with a lot of messages about updating `setuptools` and `wheel`, which are both up-to-date.  This error message still occurs though.

We've switched over to `mysql-connector-python` but I am sure glad that our production environment can tolerate this failure!  This is pretty serious.

**Comment by sanpingz** [comment]
Sorry guys, I don't even know it's being used by so many people, I'm trying to recover  2.1.x and 2.2.x to minimize the impact.

**Comment by johannes** [comment]
Any guidance from some pypi expert/admin how we can smoothen the transition? Could @sanpingz create a package which simply depends on the latest version of upstream or is there some redirect feature? Or a good way to point the right way when the user tries to install this package?

**Comment by di** [comment]
There is no redirect feature. The simplest thing (for users) would be to create a new, minimal distribution which depends on `mysql-connector-python` via [`install_requires`](https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=install_requires#declaring-dependencies), something like:

```
from setuptools import setup

setup(
    name='zippo',
    install_requires=['mysql-connector-python'],
    version='3.0.0',
    packages=[],
)
```

And possibly also adds some notice to the `long_description` (looks like this has already been done).

Unfortunately that won't fix the issue for users that have explicitly pinned to the now-deleted versions of `mysql-connector`, and it's not possible to bring back the deleted releases. Generally we don't encourage deleting releases like this, as it almost always leads to breakage.

It looks like @sanpingz is still the sole owner of `mysql-connector`, perhaps it makes sense to add @johannes and others as owners and then consider this issue as resolved as it's going to be?

**Comment by EuclidHeron** [comment]
@ewengillies curious, besides putting `mysql-connector-python` in requirements.txt what other changes did you need to make? I am running into a seg fault while trying to transition.

**Comment by sanpingz** [comment]
I only have `mysql-connector` 2.1.7 and 2.2.9 kept for the transition which roughly equal `mysql-connector-python` 2.1.6 and 2.2.2 with some fixes. The issue @ewengillies reported should be gone.

**Comment by sanpingz** [comment]
BTW, no need *Protobuf* dependency for these 2 versions.

**Comment by EuclidHeron** [comment]
hi @sanpingz looking at https://pypi.org/project/mysql-connector-python/#history do you mean 2.0.4 instead of 2.1.6?

**Comment by EuclidHeron** [comment]
Hi. Does anyone have an example of a Docker file that allows mysql-connector-python to work? I have:
In my Dockerfile I have:
RUN pip3 install -r /event_git/requirements.txt

In requirements.txt I have:
mysql-connector-python==8.0.15

Is there anything else I need to do?

**Comment by sanpingz** [comment]
> hi @sanpingz looking at https://pypi.org/project/mysql-connector-python/#history do you mean 2.0.4 instead of 2.1.6?

No, here:
https://github.com/mysql/mysql-connector-python/releases

**Comment by EuclidHeron** [comment]
Thanks so much @sanpingz . Quick follow up. I got mysql-connector-python 8.0.5 working but I still have issues with 8.0.15 . You mentioned a protobuff dependency, do you recall how to fulfill that?

**Comment by di** [comment]
Folks, this is not the right place for this discussion. Please take it into the issue trackers for these projects.

@sanpingz, have you transferred ownership to @johannes? Can this issue be closed?

**Comment by johannes** [comment]
@sanpingz if you could transfer ownership to https://pypi.org/user/mysql_re_team/ as suggested by do that would be great, then we take it up to create some form of forwarding.

@EuclidHeron yes, protobuf is needed, but that should be installed as dependency, for issues please file a bug at bugs.mysql.com or reach out to me outside this specific issue here.

**Comment by sanpingz** [comment]
@johannes Don't know how to transfer but I just added **mysql_re_team** as owner.
