### ISSUE TITLE
Request for file size limit exemption

### ISSUE THREAD

**Issue by vthorsteinsson** [pypa/warehouse#5542]
Dear PyPI, I hereby request an exemption from the file size limit for PyPI (not TestPyPI) for my project *Icegrams* (`https://pypi.org/project/icegrams/`). Icegrams is a Python package that encapsulates a heavily compressed database of trigrams for Icelandic text. The database contains 34 million trigrams that occupy 788 megabytes in uncompressed text format. Using several tricks of the trade, including succinct Elias-Fano indexes and radix tries, Icegrams squeezes this data plus the associated Python code into an **80.4 megabyte** downloadable package, which exceeds PyPI's limit. Icegrams is a very useful tool for Icelandic Natural Language Processing and being able to install it in one simple step via `pip` helps its usability and adoption. I do not anticipate that the database will become bigger than this over time. I hope this request meets with your understanding.

**Comment by jamadden** [comment]
Thanks for the detailed report. I've increased the size limit to 100MB on pypi.org.
