### ISSUE TITLE
Broken link in homepage 

### ISSUE THREAD

**Issue by marcanuy** [pypa/warehouse#5545]
At https://pypi.org/ the "Uploading packages" link (actually pointing to https://packaging.python.org/tutorials/distributing-packages ) is broken.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
Thanks for the report! That's [this link here](https://github.com/pypa/warehouse/blob/master/warehouse/templates/base.html#L249). I've added the `good-first-issue` label to this issue.

**Comment by cand126** [comment]
Hi! I would like to take this issue.

**Comment by brainwane** [comment]
@cand126 Thanks for offering your help! Would you like to try working on #2921?

**Comment by cand126** [comment]
@brainwane 
Sure! I can take a look this weekend.

**Comment by brainwane** [comment]
@cand126 Thanks! How did that go for you?

**Comment by cand126** [comment]
@brainwane 
I understand what to do roughly. I will find some time to work on it this week. :)

**Comment by marcanuy** [comment]
![off topic altert](https://media1.tenor.com/images/f5dfe218ef87c7992624395b1490b057/tenor.gif)
