### ISSUE TITLE
Consolidate two PyPI accounts

### ISSUE THREAD

**Issue by flamableconcrete** [pypa/warehouse#5570]
Hi! I have two accounts on PyPI with email addresses that I have access to that I would prefer to condense into a single PyPI account. If I simply delete one account, would I be able to then go ahead and re-use the email address associated with it in the PyPI account I want to use as my only account?

The two accounts are

* flamableconcrete (flamableconcrete@gmail.com)
* jondricek (jared.ondricek@gmail.com) - prefer this to be the only account

**Comment by di** [comment]
Hi @flamableconcrete. Yes, deleting your secondary account, or otherwise removing the email address would allow you to use it for your primary account.

Be sure to add your primary account as an "Owner" of any project that your secondary account currently owns.

**Comment by flamableconcrete** [comment]
Awesome - thank you!
