### ISSUE TITLE
Increase size limit for Intel's intel-tensorflow packages on PyPi and PyPi test to 150M.

### ISSUE THREAD

**Issue by ashahba** [pypa/warehouse#5573]
@di and @dstufft,
I'm an engineer working on Intel `MKL Optimized wheels for TensorFlow`. I was wondering if it is possible to get a size increase for the following packages on upload.pypi.org/ and test.pypi.org/ to `150M`.

```
$ du -sh *
144M	intel_tensorflow-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl
144M	intel_tensorflow-1.13.1-cp34-cp34m-manylinux1_x86_64.whl
144M	intel_tensorflow-1.13.1-cp35-cp35m-manylinux1_x86_64.whl
144M	intel_tensorflow-1.13.1-cp36-cp36m-manylinux1_x86_64.whl
```

The project location in `PyPi` is here:
https://pypi.org/project/intel-tensorflow/

Please let me know if you have any questions.

Thanks!

**Comment by ashahba** [comment]
Hi Guys, any update on this?

**Comment by jamadden** [comment]
The previous limit for intel-tensorflow on both indexes was 125MB. I've now set that to 150MB.

**Comment by ashahba** [comment]
Thanks @jamadden
