### ISSUE TITLE
https://files.pythonhosted.org returns "504 Gateway Time-out" for many source files

### ISSUE THREAD

**Issue by sunpoet** [pypa/warehouse#5579]
Take https://pypi.org/project/esda/ for example.
The download link https://files.pythonhosted.org/packages/3e/84/bff39fdd34fc7f2dd3e0a1b7a6b92cea8ca17ce0ab9359a96ed301947cd6/esda-2.0.0.tar.gz on PyPI page is fetchable.
But the predictable link used in FreeBSD ports is https://files.pythonhosted.org/packages/source/e/esda/esda-2.0.0.tar.gz which is unfetchable (504 gateway timeout).
Not all of them are unreachable but it's around 80% failure to me.

## My Platform

Tested on FreeBSD and Chrome (macOS).

### DNS Resolution

```shell
dig files.pythonhosted.org A
files.pythonhosted.org.	6	IN	CNAME	dualstack.r.ssl.global.fastly.net.
dualstack.r.ssl.global.fastly.net. 29 IN A	151.101.193.63
dualstack.r.ssl.global.fastly.net. 29 IN A	151.101.1.63
dualstack.r.ssl.global.fastly.net. 29 IN A	151.101.65.63
dualstack.r.ssl.global.fastly.net. 29 IN A	151.101.129.63
```

```shell
dig files.pythonhosted.org AAAA
files.pythonhosted.org.	28	IN	CNAME	dualstack.r.ssl.global.fastly.net.
dualstack.r.ssl.global.fastly.net. 29 IN AAAA	2a04:4e42::319
dualstack.r.ssl.global.fastly.net. 29 IN AAAA	2a04:4e42:200::319
dualstack.r.ssl.global.fastly.net. 29 IN AAAA	2a04:4e42:400::319
dualstack.r.ssl.global.fastly.net. 29 IN AAAA	2a04:4e42:600::319
```

**Comment by yan12125** [comment]
Seems fixed. https://files.pythonhosted.org/packages/source/e/esda/esda-2.0.0.tar.gz can be downloaded now. Another package https://files.pythonhosted.org/packages/source/n/nvchecker/nvchecker-1.4.tar.gz is broken yesterday, and it's also fixed today.

**Comment by sunpoet** [comment]
Confirmed. All the failed downloads are OK now.

**Comment by ncopa** [comment]
This issue seems to have reappeared. https://files.pythonhosted.org/packages/source/s/sgmllib3k/sgmllib3k-1.0.0.tar.gz gives 504.

**Comment by ncopa** [comment]
this too: https://files.pythonhosted.org/packages/source/n/netaddr/netaddr-0.7.19.tar.gz

**Comment by maxwell-k** [comment]
I am also seeing the same issue from a completely unconnected client; on both the above URLs and others I forgot to note down.

**Comment by ncopa** [comment]
another: https://files.pythonhosted.org/packages/source/a/awake/awake-1.0.tar.gz

**Comment by jamadden** [comment]
Thanks. I'm able to reproduce this locally too. I've pinged the infrastructure team.

**Comment by horta** [comment]
Same problem here. I can't make the following urls work consistently:
- https://pypi.io/packages/source/l/limix-plot/limix-plot-0.1.0.tar.gz
- https://pypi.org/packages/source/l/limix-plot/limix-plot-0.1.0.tar.gz
- https://files.pythonhosted.org/packages/source/l/limix-plot/limix-plot-0.1.0.tar.gz

**Comment by sunpoet** [comment]
It seems to be solved now. I could download all the following files:
- https://files.pythonhosted.org/packages/source/s/sgmllib3k/sgmllib3k-1.0.0.tar.gz
- https://files.pythonhosted.org/packages/source/n/netaddr/netaddr-0.7.19.tar.gz
- https://files.pythonhosted.org/packages/source/p/pygit2/pygit2-0.28.0.tar.gz
- https://files.pythonhosted.org/packages/source/a/awake/awake-1.0.tar.gz
- https://pypi.io/packages/source/l/limix-plot/limix-plot-0.1.0.tar.gz
- https://pypi.org/packages/source/l/limix-plot/limix-plot-0.1.0.tar.gz
- https://files.pythonhosted.org/packages/source/l/limix-plot/limix-plot-0.1.0.tar.gz

**Comment by jamadden** [comment]
Thanks for the reports. The infrastructure team identified the issue and corrected it, and is taking steps to prevent it from occurring again.

**Comment by mickours** [comment]
Hi!
This is happening again. These two packages leads to 504 errors.
- https://files.pythonhosted.org/packages/source/k/kubernetes_asyncio/kubernetes_asyncio-9.0.0.tar.gz
- https://files.pythonhosted.org/packages/source/k/kubernetes_asyncio/kubernetes_asyncio-10.0.0.tar.gz
Since a few minutes they are back but this one is failing:
- https://files.pythonhosted.org/packages/source/m/marshmallow/marshmallow-3.0.1.tar.gz

It seems that the problem is not completely fixed.

**Comment by jamadden** [comment]
Hi @mickours I'm not able to reproduce that. If you continue to see this, please open a new issue in https://github.com/pypa/pypi-support.

**Comment by mickours** [comment]
Yes, this was a transient failure, it comes back a few minutes later...
