### ISSUE TITLE
PyPI warehouse-camo.cmh1.psfhosted.org 504 Not rendering Images

### ISSUE THREAD

**Issue by samapriya** [pypa/warehouse#5582]
Am having the issues with PyPI not updating image links. Links for png replaced but not being rendered (for example) getting 

Getting a 504 Gateway Time-out

https://warehouse-camo.cmh1.psfhosted.org/a3587af4a84288f6be40552a881d00bc0fee976d/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f32383830363932322f35333039363735342d64343935656538302d333465642d313165392d393830642d3431383630316263393735612e706e67-->

Project: https://pypi.org/project/porder/

**Comment by samapriya** [comment]
I guess it took some time and is back again, thank you in case you had time to look into this. Closing the issue for now

**Comment by mgedmin** [comment]
This is happening again.

**Comment by jamadden** [comment]
Spot-checking some newly uploaded distributions, I get 404's for images included. E.g., for https://warehouse-camo.cmh1.psfhosted.org/1d79639b11ecb13f241b995fe1d544369c1624f4/696d672f707974686f6e2e706e67 from https://pypi.org/project/netpay-ecommerce-python/

```console
$ http https://warehouse-camo.cmh1.psfhosted.org/1d79639b11ecb13f241b995fe1d544369c1624f4/696d672f707974686f6e2e706e67
HTTP/1.1 404 Not Found
Cache-Control: no-cache, no-store, private, must-revalidate
Connection: keep-alive
Content-Length: 9
Content-Security-Policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
Date: Tue, 21 May 2019 13:34:14 GMT
Server: nginx/1.13.9
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
expires: 0

Not Found
```

I haven't been able to find a 504 yet.

**Comment by di** [comment]
Should be fixed now.

**Comment by danielhers** [comment]
Is this happening again or am I missing something I have to do for my images to be rendered? [This image](https://warehouse-camo.cmh1.psfhosted.org/8056f0ead418dfb4ef16b21d653b28fcd2a1494d/6578616d706c652e706e67) on https://pypi.org/project/streusle/ is getting "Not Found".

**Comment by di** [comment]
@danielhers You're linking to `example.png` in your README. This works on GitHub where it can resolve the relative path, but on PyPI you need to link to an absolute URL like `https://raw.githubusercontent.com/nert-nlp/streusle/master/example.png`

**Comment by danielhers** [comment]
Got it, thanks @di!
