### ISSUE TITLE
2FA User Interfaces (authentication workflow)

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#5587]
Proposed UI for 2FA login workflow (swap purple for PyPI blue... and voila!):

![Screenshot from 2019-03-18 20-36-17](https://user-images.githubusercontent.com/3323703/54561844-89bca900-49bd-11e9-86ba-be719d1e43d2.png)

![Screenshot from 2019-03-18 12-04-14](https://user-images.githubusercontent.com/3323703/54561846-89bca900-49bd-11e9-8bcf-281f23df4891.png)

![Screenshot from 2019-03-18 12-04-59](https://user-images.githubusercontent.com/3323703/54561845-89bca900-49bd-11e9-933b-86074a87a461.png)

Notes:

1. two tabs will only be shown if user has chosen to setup both methods.  The 'default' method (i.e. default tab) will be defined by the user in the admin
2. 'Get help' links will link through to appropriate help section (see #5586)

@woodruffw - I decided that it would be better to separate the recovery codes from the key authentication (e.g. not use the same form, as we had discussed), because they are not equal in effectiveness.  A recovery code can only be used once, and is bypassing the 2FA process - for this reason, we want to discourage their use to only 'emergency' situations.  My concern with using the same form as the key input, is that users will believe these methods are equal in value.

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, include a screenshot in your Pull Request.

**Comment by nlhkabu** [comment]
@woodruffw if this proposal looks good to you, I will update #5567 to include the appropriate changes.

**Comment by woodruffw** [comment]
@nlhkabu This looks great to me! I really like the design.

> I decided that it would be better to separate the recovery codes from the key authentication (e.g. not use the same form, as we had discussed), because they are not equal in effectiveness. A recovery code can only be used once, and is bypassing the 2FA process - for this reason, we want to discourage their use to only 'emergency' situations. My concern with using the same form as the key input, is that users will believe these methods are equal in value.

👍 

Feel free to update #5567 whenever you're ready!

**Comment by woodruffw** [comment]
JFYI: I'm going to push some more unit tests today, so you'll probably need to rebase before adding the templates.

**Comment by brainwane** [comment]
@woodruffw mentioned [today in IRC](http://kafka.dcpython.org/day/pypa-dev/2019-05-16):

> here are the two major UI/X items: the authentication flow (/account/two-factor) needs a tabbed view, one tab for each 2FA method. i think nlh already has a good mockup of what that'll look like. the second item is turning the current rudimentary WebAuth provisioning flow (/manage/account/webauthn-provision) into something more consistent with the TOTP provisioning flow + adding help text

@nlhkabu is there anything you need for the latter?

**Comment by nlhkabu** [comment]
@brainwane - nothing needed on my side.  Just need the go-ahead from @woodruffw.  @woodruffw are you ok for me to pull down https://github.com/pypa/warehouse/pull/5795 and update templates?

**Comment by woodruffw** [comment]
@nlhkabu Yep!

**Comment by brainwane** [comment]
@nlhkabu how's this going?

**Comment by brainwane** [comment]
I believe the one remaining task here will be to support the API keys in #994 which will be another multi-factor auth method.

**Comment by brainwane** [comment]
I presume you'll be adding API key user interfaces to commits in #6084 ?

**Comment by nlhkabu** [comment]
That's right @brainwane - @woodruffw pinged me yesterday on this, and I'm starting work on that today :)

**Comment by brainwane** [comment]
Is there anything left to be done in this issue, @nlhkabu, or can we close it?

**Comment by nlhkabu** [comment]
Yes, let's close.  Recovery codes are missing, but this are documented in #5800
