### ISSUE TITLE
Missing '( )' in documentation of module EXIFREAD

### ISSUE THREAD

**Issue by etmgsMR** [pypa/warehouse#5594]
In the documentation of EXIFREAD '( )' are missing in the paragraph at print-command: 

```
for tag in tags.keys():
    if tag not in ('JPEGThumbnail', 'TIFFThumbnail', 'Filename', 'EXIF MakerNote'):
        print "Key: %s, value %s" % (tag, tags[tag])
```

Please insert a '(' after print and at the end of line.

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, I think this is the wrong place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help with packages searched for on, or installed from, pypi.org. You'll need to reach the maintainers of that specific package. Usually this information can be found starting from the project's page on pypi.org.

(FWIW, that looks like an example from Python 2, where `print` was a keyword, not a function.)
