### ISSUE TITLE
Increase the project limit size. 

### ISSUE THREAD

**Issue by yajiedesign** [pypa/warehouse#5595]
The name of the project: mxnet-cu101 and mxnet-cu101mkl
The size of your release, in megabytes: 600mb
Which index/indexes you need the increase for (PyPI, Test PyPI, or both): both
Please help me increase my upload limit, thank you

**Comment by szha** [comment]
Any update?

**Comment by jamadden** [comment]
Usually the PyPI moderators ask for justification for size increases, especially of this extreme magnitude. However, these projects appear related to other projects for which extreme size limits have been granted (e.g., `mxnet-cu100`) so I'll skip that step. 

I've granted the limit increase for both of those projects on pypi.org. The projects do not exist on test.pypi.org so I am unable to grant them there. Please open a new issue after creating the projects there if you still feel you need that. 

Please be mindful about how often you make releases of these packages given the size.

**Comment by szha** [comment]
@jamadden thanks a lot!
