### ISSUE TITLE
Markdown long description not rendering

### ISSUE THREAD

**Issue by LogX7** [pypa/warehouse#5617]
**Describe the bug**
not rendeting mardown README.md 

**To Reproduce**
i uploaded a new version using 
```
python setup.py sdist upload
```
- here's the repo [Matrix7](https://pypi.org/project/matrix7/)
- when i uploaded the first time using twine upload it worked normally, the rendering doesn't work when uploading a new version

**My Platform**
- OS: linux mint 19
- PYTHON: 3.6.7
- WHEEL 0.33.1

**Comment by jamadden** [comment]
It's [recommended](https://packaging.python.org/guides/making-a-pypi-friendly-readme/) that you use twine to perform uploads. If you want to use Markdown, [twine is also required](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/).

**Comment by LogX7** [comment]
@jamadden  how do i upload an update with twine ?
because twine upload 
shows name already used error

**Comment by jamadden** [comment]
There shouldn't be anything different about using twine to perform an initial upload and using twine to add a new release. You may just need to check your credentials then and be sure twine is using the right credentials, authorized to add to the PyPI project. 

(Note that you cannot *overwrite* an *existing* release file with any tool; PyPI simply doesn't allow that.)

**Comment by LogX7** [comment]
i am not overwriting existing releases .. 
for some reason it's not working 
if i was overwriting an existing release then 'sdist upload' wouldn't work too .. no ?

**Comment by LogX7** [comment]
apparently it was uploading just fine 
but showing the error anyways -_- 
i don't know why
