### ISSUE TITLE
Search result relevance questionable

### ISSUE THREAD

**Issue by afranke** [pypa/warehouse#5620]
I [look up 'rfc6266'](https://pypi.org/search/?q=rfc6266) because I was told about [the module](https://pypi.org/project/rfc6266/) and I want to know more about it. Said module appears sixth even though its name matches exactly my query. I look at the sorting criteria and see it’s supposed to be by relevance. I end up wondering how that is not the most relevant result.

**Comment by di** [comment]
Duplicate of #2877.
