### ISSUE TITLE
Increase size limit request for lang2vec

### ISSUE THREAD

**Issue by antonisa** [pypa/warehouse#5623]
Hi, 

I would like to request a limit increase for the lang2vec project: https://pypi.org/project/lang2vec/

The project provides typological features for the world's languages.
The new release will also provide pre-computed pairwise distances between 8070 languages,
which will lead to greater ease of use, and could be very valuable for research in NLP, typology prediction, etc.

As a result the new release will be about 270MB in size. Note that the distances are provided as compressed numpy arrays (.npz) to significantly reduce size.

Also, as we continue our collection of typological features (annotated by linguists), it would be great to have more leeway to update our database and include more features, so we might need a larger size limit for the future.

Ideally, we'd require the increase for both TestPyPI and PyPI.

Thanks!

**Comment by jamadden** [comment]
I've increased the size limit to 300MB on PyPI and TestPyPI. This size is towards the larger end allowed. Please be mindful about how often you make releases of this package given the size.
