### ISSUE TITLE
400 Client Error: Invalid value for provides

### ISSUE THREAD

**Issue by JMSwag** [pypa/warehouse#5625]
**Describe the bug**
Attempting to upload an updated version of an existing python package results in a HTTPError 400 "Invalid value for provides" response.

A condensed example below.

```python
# Fail
setup(
    name='example',
    provides=['test.plugins']
)

# Success
setup(
    name='example',
    provides=['test_plugins']
)
```
**Expected behavior**
The ability to upload a revision to an existing package after bumping the version number in the setup.py file.

**To Reproduce**
```
# Bump version in setup.py file.
$ python setup.py build sdist
$ twine upload -r testpypi dist/*
```

**My Platform**
```
python 2.7.15
twine  1.13.0  

```
**Additional context**

The last release of my package was in 2016 and requirements for the provides kwarg could have changed. If that's the case, this can be closed & I'll update my setup.py.

[Pypi release history](https://pypi.org/project/PyUpdater-s3-Plugin/#history) of the package I noticed the issue on.

**Comment by di** [comment]
Thanks for the report! I think this is probably a bug. The biggest change between the last release of your package and today is that we completely rewrote the codebase behind PyPI. 

Based on my reading of [PEP 314](https://www.python.org/dev/peps/pep-0314/#provides-multiple-use), a `Provides` field such as `xml.utils` should be valid, but we're definitely preventing such a field from being uploaded:

https://github.com/pypa/warehouse/blob/774e9021171c6ec6572ae6bc0430026721a18039/warehouse/forklift/legacy.py#L227-L228

I went ahead and created #5626 to fix this.

Also, it's probably worth mentioning that this field is deprecated (but not invalid) as of [PEP 345](https://www.python.org/dev/peps/pep-0345/#summary-of-differences-from-pep-314).

**Comment by JMSwag** [comment]
Thanks for the quick fix & heads up on PEP 345!
