### ISSUE TITLE
Request Trove classifier: HPND licence

### ISSUE THREAD

**Issue by hugovk** [pypa/warehouse#5627]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `License :: OSI Approved :: Historical Permission Notice and Disclaimer (HPND)`

(or similar)

## Why do you want to add this classifier?

It turns out the "Standard PIL license" used by Pillow is really HPND (https://github.com/python-pillow/Pillow/issues/1507), and is approved by the OSI:

* https://opensource.org/licenses/alphabetical
* https://opensource.org/licenses/HPND

Right now Pillow is using the `License :: Other/Proprietary License` classifier.

**Comment by aclark4life** [comment]
Beat me to it, thanks @hugovk

**Comment by di** [comment]
I've added the `License :: OSI Approved :: Historical Permission Notice and Disclaimer (HPND)` classifier, thanks!
