### ISSUE TITLE
Request trove classifier: Framework :: Nengo

### ISSUE THREAD

**Issue by tbekolay** [pypa/warehouse#5628]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: Nengo`

## Why do you want to add this classifier?

We develop a neural network simulator called Nengo. We have architected Nengo to be modular such that a Nengo model can be simulated on several different backends, so we have several backend projects that are released separately on PyPI. Similarly, we and others have developed projects that provide useful frontend extensions. We would like to add a Trove classifier so that it is easy to find all of the projects using the Nengo framework on PyPI.

Currently, we manually maintain [this page](https://www.nengo.ai/projects.html), which lists all of the repositories that we are aware of, but this is not a comprehensive list. Having the classifier will help us maintain this page.

While Nengo fills a relatively small niche (spiking neural networks) it has been presented at PyCon and has ~350 stars on github (see [nengo/nengo](https://github.com/nengo/nengo)).

An incomplete list of Nengo projects on PyPI that would benefit from using the Trove classifier:
- [nengo](https://pypi.org/project/nengo/)
- [nengo-gui](https://pypi.org/project/nengo-gui/)
- [nengo-spa](https://pypi.org/project/nengo-spa/)
- [nengo-ocl](https://pypi.org/project/nengo-ocl/)
- [nengo-dl](https://pypi.org/project/nengo-dl/)
- [nengo-loihi](https://pypi.org/project/nengo-loihi/)
- [nengo_spinnaker](https://pypi.org/project/nengo_spinnaker/)
- [nengo-extras](https://pypi.org/project/nengo-extras/)
- [nengolib](https://pypi.org/project/nengolib/)

**Comment by jamadden** [comment]
Hi! Thanks for the well written request. 

The PyPI moderators are in the process of developing a few guidelines for the creation of new Framework classifiers. Because removing classifiers is very difficult, and the longer the classifier list gets the harder it is to browse, I think we're expecting the bar to add new ones to be relatively high. Currently, we're looking at these guidelines:

* New framework classifiers should be created if they are "notable;" and 
* They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)

We understand that "notability" is subjective and we'd appreciate help judging that; the information you've provided goes a long way towards that. Are you able to provide a link to the PyCon presentation?

As to the other guideline ('immediate use to existing projects'), it's been suggested that 

- Requestors can demonstrate this by providing links to 10 or more **existing PyPI projects** that will use the classifier; or
- Another way to demonstrate notability would be to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier.

We're looking for some feedback on this. Does it seem reasonable to you? And if so, are gathering those links and/or comments something you would be able to help with? (I see that you've anticipated us and have provided PyPI links already; thank you!)

**Comment by tbekolay** [comment]
Hi @jamadden, I definitely appreciate that the list of Trove classifiers needs to be kept short enough to browse. There might be some opportunities to improve the browsing experience since the classifiers are inherently hierarchical, so for example on [this page](https://pypi.org/classifiers/) having some sub-classifiers (e.g. the version-specific ones) collapsed but expandable might help (though I know [this list](https://pypi.org/pypi?%3Aaction=list_classifiers) is less flexible). I'm sure there are internal discussions about that -- if you want some more voices in that conversation let us know.

I think that the criteria of notability and immediate use make sense, particularly the immediate use one. For immediate use, I'll copy the list from above and add a few other projects to up the count to 12.

- [nengo](https://pypi.org/project/nengo/)
- [nengo-gui](https://pypi.org/project/nengo-gui/)
- [nengo-spa](https://pypi.org/project/nengo-spa/)
- [nengo-ocl](https://pypi.org/project/nengo-ocl/)
- [nengo-dl](https://pypi.org/project/nengo-dl/)
- [nengo-loihi](https://pypi.org/project/nengo-loihi/)
- [nengo_spinnaker](https://pypi.org/project/nengo_spinnaker/)
- [nengo-extras](https://pypi.org/project/nengo-extras/)
- [nengolib](https://pypi.org/project/nengolib/)
- [nengo-sphinx-theme](https://pypi.org/project/nengo-sphinx-theme/)
- [aver](https://pypi.org/project/aver/)
- [nengo-distilled](https://pypi.org/project/nengo-distilled/)

Notability is definitely a tough thing to show. My PyCon talk is [here](https://www.youtube.com/watch?v=7hvpoLKJHOw). As I mentioned previously, Nengo fits into a pretty specific niche so despite being widely used in the field, the field itself is pretty small. We, of course, have had occasions in the past where we've wanted to show that we are notable, so things that we've used as evidence of that are:

- the number of [Github stars](https://github.com/nengo/nengo) (currently 387),
- the number of [contributors](https://www.nengo.ai/people.html) (currently 34),
- usage of the library across Github (through searching [`import nengo`](https://github.com/search?utf8=%E2%9C%93&q=%22import+nengo%22+OR+%22from+nengo%22&type=Code), which yields around 6000 results),
- the amount of activity on [our forum](https://forum.nengo.ai/),
- the number of PyPI downloads (I believe that information is no longer available, and also largely driven by our continuous integration testing)
- the number of [academic publications](https://scholar.google.com/scholar?start=40&q=Nengo+-Kenya+-African+-Africa+-%22Nengo-Nengo%22+-Japan+-Japanese+-Fossil+-Fossils+-Ontogeny+-cranium+-%E5%B9%B4+-Entrevista+-Ontologia+-Pengau+-Basque+-Signora&hl=en&as_sdt=0,30&as_ylo=2003) that use Nengo (currently around 800, though there are likely false positives in there)

These metrics were useful for us to compare the Nengo's popularity with other software packages in the same field as ours. Popularity isn't necessarily notability, but they're definitely correlated, and it's difficult to collect more specific metrics without harming the user experience or infringing on a user's privacy. Since Nengo was first developed in an academic lab for use in research projects, academic publications are an important metric for us, but will not be terribly useful for other Python projects.

I'll ping some Nengo project maintainers to chime in here if they have anything else to add; otherwise, let me know if there's any other information I can provide!

**Comment by arvoelke** [comment]
Weighing in as a contributor to core Nengo and maintainer of NengoLib. I think the case for being "of immediate use to existing projects" is clear, given the number of actively maintained projects within the Nengo ecosystem. I would certainly use the classifier within my project(s). But it would help to know of any other guidelines for notability. @tbekolay addressed many potential considerations above within the context of the Python and academic communities. Here are a few more in a broader public context:
 - Nengo has a [wikipedia entry](https://en.wikipedia.org/wiki/Neural_Engineering_Object).
 - An [article in Science](http://science.sciencemag.org/content/338/6111/1202) is centered about a model built using Nengo, and an [article in Nature News](https://www.nature.com/news/simulated-brain-scores-top-test-marks-1.11914) is about this same model. This received a [fair amount of press coverage](https://xchoo.github.io/spaun2.0/press.html).
 - The above model was mentioned on [Mind Field - The Stilwell Brain](https://www.imdb.com/title/tt9429144/) (Vsauce has over 14 million YouTube subscribers) and on [Stephen Hawking's Science of the Future](https://www.imdb.com/title/tt5289324/).
 - A book titled "How to Build a Brain: A Neural Architecture for Biological Cognition" uses Nengo for all of its examples.
 - This year marks the [6th annual Nengo summer school](https://www.nengo.ai/summerschool.html), a workshop that teaches academics and industry professionals how to use Nengo.
 - Applied Brain Research was awarded [2018 Technology Pioneer by the World Economic Forum](https://appliedbrainresearch.com/pressreleases/00-wef/) for its use of Nengo in neuromorphic applications.
 - Intel has publicly [expressed its support](https://newsroom.intel.com/news/intel-announces-neuromorphic-computing-research-collaborators/) for Nengo.
 - The prime minister of Canada, Justin Trudeau, [interacted with](https://appliedbrainresearch.com/pressreleases/03-trudeau/) a Nengo simulation controlling a robotic arm in a public demonstration.

**Comment by jamadden** [comment]
Thanks for your responses! With the evidence provided, to my mind, it looks like the proposed guidelines have been met, and I would suggest adding the classifier.

I'd like to allow a few days to give the other @pypa/pypi-moderators a chance to review this before taking action. (If there's no other motion on this by next week, feel free to ping me.)

**Comment by ewdurbin** [comment]
@jamadden I'm +1 on adding this classfier

**Comment by jamadden** [comment]
`Framework :: Nengo` has been added to pypi.org
