### ISSUE TITLE
PEP 541: Claiming django-latch

### ISSUE THREAD

**Issue by javimoral** [pypa/warehouse#5636]
I've forked [django-latch](https://github.com/rootedcon/django-latch), a package that hasn't been actively develop in 5 years.

Also asked its original developer [desee](https://pypi.org/user/deese/) via mail to free the name so I could use it. He agreed and deleted the package on 26/04.

I'd like to claim the name of the previously registered package to keep developing the project.

**Comment by di** [comment]
Looks like the original maintainer removed all previous releases, but did not delete the project. They can either:

* Delete the project entirely: https://pypi.org/manage/project/django-latch/settings/
* Add you as an owner of the project: https://pypi.org/manage/project/django-latch/collaboration/

**Comment by javimoral** [comment]
Contacted again with the original publisher. Thanks.
