### ISSUE TITLE
Request for size limit increase for cupy-cuda101 package

### ISSUE THREAD

**Issue by kmaehashi** [pypa/warehouse#5643]
Hello,

I would like to request a size limit increase for `cupy-cuda101` package to distribute [CuPy](https://github.com/cupy/cupy) wheels, because it contains dependency libraries (CUDA etc.).
The size of the wheel is currently approx. 300 MB. Could you please increase the limit to 350 MB?

Thanks in advance!

**Comment by jamadden** [comment]
I've set the limit for `cupy-cuda101` to 350MB on PyPI.

There seem to be several related packages of this size with synchronized release schedules (e.g., `cupy-cuda90`, `91`, `100`), so given the overall size we would ask that you please continue to be mindful about how often you make releases of them.

**Comment by kmaehashi** [comment]
Thank you for your continued support!
