### ISSUE TITLE
apt-get update fails on make build due to Debian jessie 404s

### ISSUE THREAD

**Issue by yeraydiazdiaz** [pypa/warehouse#5651]
When running `make build` the `apt-get update` command in the Dockerfile fails due to a 404 while fetching Debian Jessie updates, I believe due to https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

I haven't had time to fully look into this but a quick fix has been to upgrade the version of the `node` image in the Dockerfile to [`8.15.1` which is based on `stretch`](https://github.com/nodejs/docker-node/blob/de76fb48b532d6be012098dc3538bd15329a27d0/8/stretch/Dockerfile). I'm not certain of any ramifications of this change or we need to update other images elsewhere.

**Comment by di** [comment]
Good catch. Upgrading to `8.15.1` seems to work fine for me locally, I'll push a branch and we'll see how it goes.
