### ISSUE TITLE
XML-RPC changelog_since_serial() method is returning invalid XML due to \x01 in sdist name

### ISSUE THREAD

**Issue by jwodder** [pypa/warehouse#5653]
As of 2019-04-01 17:35:00 +0000, running the below Python 3 code:

```
#!/usr/bin/python3
import csv
from   xmlrpc.client import ServerProxy
import sys

ENDPOINT = 'https://pypi.org/pypi'
SINCE = 5011848
   
client = ServerProxy(ENDPOINT, use_builtin_types=True)
out = csv.writer(sys.stdout)
out.writerow('name version timestamp action serial'.split())
for row in client.changelog_since_serial(SINCE):
    out.writerow(row)
```

fails with:

```
Traceback (most recent call last):
  File "minimum.py", line 12, in <module>
    for row in client.changelog_since_serial(SINCE):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1336, in parse_response
    p.feed(data)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 439, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 5264, column 38
```

Manually reproducing the XML-RPC request and inspecting the response shows that the problematic piece of XML is (with line number added):

```
<value><array><data>
<value><string>request-s</string></value>
<value><string>0.0.1</string></value>
<value><int>1554118234</int></value>
<value><string>add source file request^As-0.0.1.tar.gz</string></value> <!-- line 5364 -->
<value><int>5016503</int></value>
</data></array></value>
```

The `^A` is here a literal `\x01` which somehow ended up in the filename of an sdist uploaded to the `request-s` project.  If Warehouse is going to allow uploads of such filenames, it needs to properly escape them in XML-RPC responses.

**Comment by jwodder** [comment]
Upon further investigation, it appears that the failure to escape `\x01` is the fault of Python's `xmlrpc.client.dumps()`.  BPO 26147 appears to be related.

**Comment by di** [comment]
Here's the project in question: https://pypi.org/project/request-s/

Here's where we check that it normalizes to the same value: https://github.com/pypa/warehouse/blob/a3036d44179f640be52578d0d07fce75fe4793c5/warehouse/forklift/legacy.py#L1073-L1080

AFAICT, this is a valid, albeit confusing filename, and the issue is with the client instead.

**Comment by ewdurbin** [comment]
@di is this a place where the addition of some calls to [`_clean_for_xml`](https://github.com/pypa/warehouse/blob/a3036d44179f640be52578d0d07fce75fe4793c5/warehouse/legacy/api/xmlrpc/views.py#L79-L89) are needed?

**Comment by di** [comment]
@ewdurbin Not sure. Cleaning the description/summary is one thing, but actually changing the filenames might not be helpful.

**Comment by ewdurbin** [comment]
Though on second thought, I'm fairly certain this will also effect the releases data as well.

**Comment by ewdurbin** [comment]
seems url encoding the filename field is probably the safer bet.

**Comment by jwodder** [comment]
The XML-RPC is working again now.  Thanks!
