### ISSUE TITLE
Request for size limit increase for CuPy packages

### ISSUE THREAD

**Issue by kmaehashi** [pypa/warehouse#5665]
Hello,

I'm maintaining packages for [CuPy](https://github.com/cupy/cupy), and would like to request size limit increase for the following packages to distribute wheels.

* `cupy-cuda90`, `cupy-cuda91`, `cupy-cuda92`: 350 MB
* `cupy-cuda100`, `cupy-cuda101`: 400 MB

These packages currently have limit of 300 MB / 350 MB respectively. 
This is a re-request of size increase due to the increased size of dependent library (CUDA cuDNN) in recent versions.

We had been releasing wheels with these names once per month, and would like to continue it.
Thank you as always for your continued support!

**Comment by jamadden** [comment]
I've set the upload limit for all 5 projects to 400MB on PyPI.

**Comment by kmaehashi** [comment]
Thank you!
