### ISSUE TITLE
keypad.registerKeyPressHandle

### ISSUE THREAD

**Issue by somsom1989kangs** [pypa/warehouse#5681]
am having a problem with this part of the programme(keypad.registerKeyPressHandle) in that when i run it, it first produce a none value before it gives the pressed values on the keypad. now when it come to compare the value with a predetermined password, the outcome is wrong because it present the none (the first value it obtained before the pressed ones)

**Comment by jamadden** [comment]
Thanks for the report, but unfortunately this is the wrong tracker for it. This tracker can only help with issues related to the software that runs https://pypi.org itself. It cannot help with packages distributed from or installed from there. For that, you'll need to contact the maintainers of the specific package you're having trouble with.
