### ISSUE TITLE
Unable to verify email address - received link does not verify 

### ISSUE THREAD

**Issue by penguian** [pypa/warehouse#5684]
**Describe the bug**

I clicked through the link on https://pypi.org/manage/account/#account-emails to send an email to verify my email address paul.leopardi@gmail.com
When I received the email, I clicked through the link.
This took me to https://pypi.org/manage/account/#account-emails which had the banner

`Warning Your primary email address (paul.leopardi@gmail.com) is unverified. Verify your email or add a new address.`

I then clicked through the link on https://pypi.org/manage/account/#account-emails to send a second email to verify my email address paul.leopardi@gmail.com

When I received the second email, I clicked through the link.
This took me to https://pypi.org/manage/account/#account-emails which had the banner

`Warning Your primary email address (paul.leopardi@gmail.com) is unverified. Verify your email or add a new address.`

**Expected behavior**
Clicking on the link in the email should verify my email address.

**To Reproduce**
See steps above.

**My Platform**
Not relevant, but Chromium `Version 73.0.3683.75 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)`

**Comment by penguian** [comment]
I logged out of `pypi.org` and tried the link again. It worked. This is still a bug, but maybe a documentation bug. If the email link only verifies your address if you are logged out, the email should say so. If the email link only works after a certain delay, then the email should say so.

**Comment by di** [comment]
I haven't seen any other reports of this happening, so I'm going to close this for now, but happy to reopen if this reoccurs.
