### ISSUE TITLE
PEP 541: Delete squatter's packages and transfer yield to me

### ISSUE THREAD

**Issue by timkpaine** [pypa/warehouse#5689]
Squatter: https://pypi.org/user/suroegin/
Package I want: https://pypi.org/project/yield/

**Comment by bpabel** [comment]
Really, `yield` should be a restricted package name considering it's a python keyword.

**Comment by bpabel** [comment]
Should probably delete all that user's packages, half of them are reserved keywords in python, and the rest are just squatting on names.

**Comment by timkpaine** [comment]
agreed with your second comment for sure, it could even be a malicious squatting. Not sure the policy on reserved word but my libraries import name is `yld` so id like to grab it but understand if its against policy

**Comment by jamadden** [comment]
Have you been able to contact the user at their email address as listed on the PyPI project page? Having the user transfer the name to you is the least complicated solution. (It's possible that @suroegin is the same person; replying to this issue would be helpful either way.)

**Comment by bpabel** [comment]
@jamadden I believe *all* these projects meet the criteria for "Invalid Projects" as laid out in PEP 541.

At the very least, the projects using reserved python keywords should be removed (and potentially blocked from further use), including the one specified in this request -- "yield".

**Comment by bpabel** [comment]
@timkpaine Why did you close this?  It doesn't look like it was resolved?

**Comment by timkpaine** [comment]
I don't care anymore. Someone else can deal with it.
