### ISSUE TITLE
Terms of Use in plaintext

### ISSUE THREAD

**Issue by StGabriel** [pypa/warehouse#5693]
Hi,

I want to check each time of any upload whether the PyPI Terms of Use has been changed.

Is the deployed PyPI Terms of Use on https://pypi.org/policy/terms-of-use/ the same on GitHub repository for warehouse on https://github.com/pypa/warehouse/blob/master/policies/terms.md ?
Do you see any other possibilities to check for plain text?

Best regards
Stefan Gabriel

**Comment by di** [comment]
Yes, that file and that page correlate.

**Comment by brainwane** [comment]
@StGabriel Every time that we make a change to the `master` branch of that repository, within a few minutes, we automatically deploy that new version of the site to pypi.org. So you can be assured that https://pypi.org/policy/terms-of-use/ reflects https://github.com/pypa/warehouse/blob/master/policies/terms.md , and I think that's your best bet for doing this. Therefore, closing this issue. Thanks!
