### ISSUE TITLE
Package ownership

### ISSUE THREAD

**Issue by mar10py** [pypa/warehouse#5706]
I would like to use the package name `mario`. Attempting to upload gives a 403 error. I [don't see](https://pypi.org/project/mario/) any contact info, is it possible to identify the owning account and maybe email them? It's possible that it was me and I forgot the username.

**Comment by jamadden** [comment]
The owner of that name seems to be @roll . Perhaps they can reply here and you can discuss a transfer.

**Comment by roll** [comment]
@mar10py 
Please try again. It's deleted now

**Comment by mar10py** [comment]
@jamadden Thank you for figuring this out.

@roll Perfect, thank you for releasing!
