### ISSUE TITLE
Claim package pantheon

### ISSUE THREAD

**Issue by Canisback** [pypa/warehouse#5708]
I would like to transfer ownership of this package : 
https://pypi.org/project/pantheon/

It has been untouched for 4 years now, and with no files in it.

I tried to contact the owner with no answer.

Thanks.

**Comment by jamadden** [comment]
I believe the project owner is @dveselov , who seems to be active on github. Perhaps they can comment here and work out a name transfer.

**Comment by dveselov** [comment]
Hi, I didn't received any messages or emails about this package.
Also, I need to know PyPI username to do a transfer.

**Comment by Canisback** [comment]
@dveselov Here is my PyPI username.
https://pypi.org/user/Canisback/
Thank you.

**Comment by dveselov** [comment]
I've transferred this package. Can be closed.
