### ISSUE TITLE
Document owner/maintainer roles on help page

### ISSUE THREAD

**Issue by di** [pypa/warehouse#5713]
Currently on the logged-in only "collaboration" page for a project, we document the possible roles for collaborators:

> There are two possible roles for collaborators:
> 
> Maintainer
> Can upload releases for a package. Cannot add collaborators. Cannot delete files, releases, or the project.
> Owner
> Can upload releases. Can add other collaborators. Can delete files, releases, or the entire project.

It would be good to document this at https://pypi.org/help/ as well.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by shreyasbapat** [comment]
Can I take this up? :)

**Comment by di** [comment]
@shreyasbapat Please do!

**Comment by vinayak-mehta** [comment]
@shreyasbapat Looks like there isn't a PR for this, I'll take this up :)
