### ISSUE TITLE
https://files.pythonhosted.org returns '504 Gateway Time-out' for conda build

### ISSUE THREAD

**Issue by dbakshee** [pypa/warehouse#5715]
## My Platform
Conda build on azure: for example [this ](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=29054) one (this is 2nd iteration, was able to fetch 6 wheels of 9 needed; the build few hours before that could only fetch 2).

This issue looks like the same as #5579

**Comment by jamadden** [comment]
Thanks for the report. I've pinged the infrastructure team and re-opened #5579 so we can follow this in one place.
