### ISSUE TITLE
cudatoolkit package

### ISSUE THREAD

**Issue by cristipurdel** [pypa/warehouse#5720]
**What's the problem this feature will solve?**
Portable Winpython with gpu support

**Describe the solution you'd like**
Make it for various cudatoolkit, similar to conda packages

**Additional context**
Could try to maintain, in the beginning, only the lowest cudatoolkit version supported by tensorflow, numba, cupy, etc.

**Comment by jamadden** [comment]
Thanks for the report, but unfortunately this isn't the right place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help with packages distributed from there (it doesn't maintain Python or tensorflow, numba, cupy, etc). You'll need to contact the various package maintainers instead.
