### ISSUE TITLE
Request trove classifier `Programming Language :: F#`

### ISSUE THREAD

**Issue by dbrattli** [pypa/warehouse#5727]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Programming Language :: F#`

## Why do you want to add this classifier?

Will need this classifier for https://github.com/dbrattli/sphinxcontrib-fsharp that creates a Sphinx domain for F#.

**Comment by jamadden** [comment]
Thanks for the request! We're looking into adding this, but the octothorp is not currently allowed in classifiers. #5729 is open to track this.

**Comment by dbrattli** [comment]
I used the `#` since I saw that C# was already added as `Programming Language :: C#`. We could also call it FSharp instead of F# but then C# should perhaps be called CSharp.

**Comment by jamadden** [comment]
That's a great point! In the past, I believe admins directly edited the database to add classifiers. Now there's a UI with validation on top of it, so we're most likely looking at at simple UI validation bug rather than an issue with the classifier itself.

**Comment by merwok** [comment]
The `Programming Language` classifiers are meant to describe the language(s) used in the code of the package, aren’t they?

If the sphinxcontrib-xyz projects are *about* C# or XYZ but entirely written in Python, I don’t think the classifiers are correct?

**Comment by jamadden** [comment]
> The Programming Language classifiers are meant to describe the language(s) used in the code of the package, aren’t they?

Sure, they can do that, but I don't think that's a strict constraint followed by existing usage. For example, under `PL :: PROLOG`, we find "pyDatalog - A pure-python implementation of Datalog, a truly declarative language derived from Prolog." There are examples in this exact domain (sphinx documenters, which may or may not rely on code/tools written in the language being documented) too: "sphinxcontrib-emacs - Emacs documentation support for Sphinx" is `PL :: EMACS-LISP`, "sphinxcontrib-ocaml - a Sphinx (1.6.3+) extension to document OCaml libraries" is `PL :: OCAML`, etc.

**Comment by dbrattli** [comment]
As for "sphinxcontrib-ocaml" the autodoc handing is implemented in OCaml. I'm porting this library to F#, so eventually that feature will be impl in F#. But for now it's only using domain.py which is Python and the project is currently classified as Python.

**Comment by jamadden** [comment]
I've added the classifier. (FWIW, a project can have multiple `Programming Language ::` classifiers; that's common for specifying multiple supported python versions, but there's no reason it can't be used to specify multiple different implementation or application languages.)
