### ISSUE TITLE
PEP541 - sklearn transfer to proper owner

### ISSUE THREAD

**Issue by timkpaine** [pypa/warehouse#5730]
https://pypi.org/project/sklearn/

@amueller

**Comment by jamadden** [comment]
Can you please provide more information about your request? For example: What part of PEP541 is meant to apply to this? There are three maintainers listed; have you attempted to contact them? Who is meant to be the "proper owner" (the account you tagged appears to be one of the maintainers of the `sklearn` project)?

**Comment by timkpaine** [comment]
@jamadden nope, i've linked the real owner so he can take a look and follow up if necessary.

**Comment by amueller** [comment]
Not sure what this is about. I'm one of the maintainers of scikit-learn. We also have access to sklearn which someone else had created and then we took over IIRC.

I'm an owner of sklearn from what I can see, together with @lesteve, who's also working on scikit-learn.

**Comment by timkpaine** [comment]
@amueller `pip install sklearn` doesnt use the main repo though, is this intentional?

**Comment by timkpaine** [comment]
if you have admin can you delete these bad listings: https://pypi.org/simple/sklearn/

**Comment by amueller** [comment]
What do you mean by "main repo"? pypa doesn't have a concept of aliases as far as I'm aware, so the only way to make it do anything is to have a dummy package that depends on scikit-learn.
Alternatively we could remove the sklearn package and ``pip install sklearn`` will just not work.

**Comment by timkpaine** [comment]
The latter seems to be best

**Comment by amueller** [comment]
There is an issue in the sklearn issue tracker discussing this, but I can't find it right now. Please comment there.

**Comment by timkpaine** [comment]
@amueller can also do what airflow does which is a placeholder, i'll link you their code
https://pypi.org/project/airflow/
<img width="799" alt="Screen Shot 2019-04-22 at 3 23 10 PM" src="https://user-images.githubusercontent.com/3105306/56520479-8b284680-6512-11e9-8f5c-1857d01c96e5.png">

**Comment by amueller** [comment]
@timkpaine please discuss on the issue @jamadden linked to, scikit-learn/scikit-learn#8215
