### ISSUE TITLE
Pypi project size too large to be uploaded

### ISSUE THREAD

**Issue by timmykuo** [pypa/warehouse#5736]
Link: https://pypi.org/project/mitopipeline/
Size of release: 69.3MB
Index: PyPi
Project description: Automated pipeline for genetic researchers working with the mitochondrial genome. The reason why it's so big is because I've uploaded an example .bam file in order for users to be able to test out the product

**Comment by di** [comment]
I've set the upload limit for `mitopipeline` to 100 MB on PyPI.
