### ISSUE TITLE
Error "400 Bad CSRF Origin" while register an account

### ISSUE THREAD

**Issue by martinbaun** [pypa/warehouse#5740]
Hi,
I can't register an account on https://pypi.org/account/register/ and I can't figure out where this error comes from.
I'm on Linux with Firefox 66.0.3

Best regards
Martin

```
400 Bad CSRF Origin
Access is denied. This server can not verify that the origin or referrer of your request matches the current site. Either your browser supplied the wrong Origin or Referrer or it did not supply one at all.

Origin checking failed - no Origin or Referer. 
```

**Comment by di** [comment]
Hi @martinbaun, sorry you're having issues. Is it possible your browser, platform or network is configured to not send the `Origin` or `Referrer` headers? Could you try a different browser and see if the issue persists? I was just able to register a new account, so it seems like this is not a broad issue on our end.

**Comment by martinbaun** [comment]
Hi, 
thanks for your reply. Other browsers are working. I found the problem in firefox. In about:config I changed
`network.http.sendRefererHeader;0`
to
`network.http.sendRefererHeader;2`

Strange, this is the first website that leads to this problem. However, it is working, now ;-)
