### ISSUE TITLE
Request to increase size limit

### ISSUE THREAD

**Issue by imaus10** [pypa/warehouse#5745]
Hi there,

I'm trying to upload a wheel for the package `thumbor_extras` but it's hitting the size limit. The wheel is 61.3MB because it includes the weights for a deep neural network trained to detect objects in images. This file is required to run the `dnn_object_detector`.

Could I get an increased size limit on both PyPI and Test PyPI so the package is easily distributable? Thank you!

Repo link: https://github.com/imaus10/thumbor_extras
PyPI link: https://pypi.org/project/thumbor-extras/

**Comment by jamadden** [comment]
I've increased the limit to 100MB on both pypi.org and test.pypi.org.

**Comment by imaus10** [comment]
Thank you!
