### ISSUE TITLE
File size limit increase request

### ISSUE THREAD

**Issue by Lleyton-Ariton** [pypa/warehouse#5751]
I am the creator of the Cortecx NLP library on PyPi (https://pypi.org/project/Cortecx/). The library was made with the intention of simplifying NLP for some of the beginners in an AI club I run at my high school. Unfortunately, some of the data for the students that I wanted to package along with the library was a bit too large to be held by the 60MB file size limit of PyPI. I cut down some of the data and therefore consequent the corresponding file size quite a bit from the original, and compressed it on top of that. It however still has a file size of about 100MB! Ive tried many methods including externally storing it via google cloud storage and implementing code to retrieve it etc… but nothing’s worked out so far and for now I am left without a better solution than to just go with my original plan and package it with my library. I really don't want to shave off anymore of the data because its pretty important. The total size of the library is about 105MB so I would really appreciate it (if possible) you could help me and the rest of the AI club and maybe bump up my maximum limit to at least 110MB (we could maybe use a bit of jiggle room, its never a bad thing).

**Comment by jamadden** [comment]
I've increased the upload limit for Cortecx to 150MB on PyPI.
