### ISSUE TITLE
Spam report

### ISSUE THREAD

**Issue by calston** [pypa/warehouse#5752]
Not necessarily spam, but at least a pretty despicable abuse of PyPi to advertise a service with keyword hijacking by @markolofsen

https://pypi.org/project/how-to-upload-package-to-pypi/

**Comment by jamadden** [comment]
Other similar (or identical) projects:

- https://pypi.org/project/private-pip-repository/
- https://pypi.org/project/pypi-cloud/
- https://pypi.org/project/upload-pypi/

**Comment by calston** [comment]
Might also be an infringement on Githubs AUP as the repositories contain advertising outside of the repository of its service source code. Will raise on that too

**Comment by calston** [comment]
Really? No one cares? @dstufft

**Comment by di** [comment]
These packages have been removed.

**Comment by pradyunsg** [comment]
@di we might also want to remove and ban "how-to-upload-package-to-pypi".

**Comment by di** [comment]
@pradyunsg It was removed, looks like it just didn't get purged from the cache.

**Comment by pradyunsg** [comment]
Ah. Right. Can we add that to the removal process?

**Comment by di** [comment]
Should be, seems to be either temporarily not working or a bug.
