### ISSUE TITLE
Increase upload size limit of h2o_pysparkling_x packages

### ISSUE THREAD

**Issue by jakubhava** [pypa/warehouse#5753]
Hello, I'm owner of Sparkling Water https://github.com/h2oai/sparkling-water project which has PySparkling as the Python client. I could't find better place where to ask this then here.

I would like to ask if it would be possible to increase size for our PySparkling package? It reached limit of 60mb ( has now about 61-62 mb). Right now we can't upload releases to pipy.
We have 4 versions of PySParkling package, for each spark:
h2o_pysparkling_2.1
h2o_pysparkling_2.2 
h2o_pysparkling_2.3 
h2o_pysparkling_2.4 

When new major Spark comes out we usually add new one and deprecate and stop updating the last one.

Our release cycle is usually 1 release in 3 weeks for all of those packages. We can also try to remove the old release to clean some space.

Thank you,

Jakub Hava (Kuba)

**Comment by jamadden** [comment]
Could you please confirm the PyPI URL of the project?

**Comment by jakubhava** [comment]
https://pypi.org/project/h2o-pysparkling-2.1/
https://pypi.org/project/h2o-pysparkling-2.2/
https://pypi.org/project/h2o-pysparkling-2.3/
https://pypi.org/project/h2o-pysparkling-2.4/

Thank you @jamadden

**Comment by jakubhava** [comment]
Hi @jamadden, any update please? 

Thanks, 
Kuba

**Comment by jamadden** [comment]
The limit for all four projects has been increased to 100MB on pypi.org.

**Comment by jakubhava** [comment]
thanks!

**Comment by mn-mikke** [comment]
Hi @jamadden,
Would it be possible to increase the limit to 15OMB for all four projects? It seems that the packages will grow in the next release.

Thanks,
Marek

**Comment by pradyunsg** [comment]
Hi @mn-mikke, could you file a new issue? It'll be easier to keep track of each request for increase that way. :)
