### ISSUE TITLE
 Error: pg_config executable not found during redshift-tool installation

### ISSUE THREAD

**Issue by rlinapagolla** [pypa/warehouse#5759]
I was able to resolve the pg_config error after running the following commands

pip install psycopg2-binary
pip install --upgrade setuptools
yum install postgresql-libs
yum install postgresql-devel
pip install psycopg2
pip install redshift-tool

**Comment by jamadden** [comment]
Thanks for the report, but I don't think this is the place for it. This tracker is only for issues with the software that runs pypi.org itself; it cannot help with packages distributed or `pip install`ed from there.  For that, you'll need to contact the package maintainers; this information can usually be found on the [project page](https://pypi.org/project/redshift-tool/).
