### ISSUE TITLE
Request for File-size-limit exception for CityEnergyAnalyst

### ISSUE THREAD

**Issue by daren-thomas** [pypa/warehouse#5789]
- A link to your project on PyPI: https://pypi.org/project/cityenergyanalyst/
- The size of your release, in megabytes: 65.8 MB
- Which index/indexes you need the increase for: PyPI
- A brief description of your project: The CityEnergyAnalyst  is an urban energy simulation platform and one of the first open-source computational tools for the design of low-carbon and highly efficient neighborhoods and districts The CEA combines knowledge of urban planning and energy systems engineering in an integrated framework. This allows to study the effects, trade-offs and synergies of urban design options, building retrofits and energy infrastructure plans.
- Including the reason for the additional size: I'm not really sure, tbh. It might be the inclusion of JS libraries for the dashboard functionality.

**Comment by jamadden** [comment]
The upload limit for cityenergyanalyst has been increased to 100MB on pypi.org.

**Comment by daren-thomas** [comment]
thank you :)
