### ISSUE TITLE
Send invitations when adding owner/maintainer roles

### ISSUE THREAD

**Issue by di** [pypa/warehouse#5790]
**What's the problem this feature will solve?**
Currently as a PyPI package maintainer, it's possible to give any other user an owner/maintainer role for your package without their consent.

**Describe the solution you'd like**
We should change the way role assignment currently works, from just allowing owners to assign other users roles on a given project, to allowing owners to _request_ that other users accept roles for a given project.

The way we should do this is by sending an email to the new owner/maintainer with a validation link, and allowing them to accept/reject the request before the new role is added.

**Additional context**
Originally described in #4729.

**Comment by DavidBord** [comment]
@di as discussed, we should implement a draft role so that the request initiator / admin would be able to revoke the invitation

**Comment by di** [comment]
@DavidBord How's it going here? It seemed like you were close to finishing this, need any assistance?

**Comment by DavidBord** [comment]
@di it is finished except for the 100% test coverage needed for the CI to pass: https://github.com/DavidBord/warehouse/tree/fix-5790-send-invitations
I'll do my best to complete it soon

**Comment by brainwane** [comment]
@DavidBord Let us know if you need any help! Thanks.

**Comment by brainwane** [comment]
@DavidBord how's it going? Need help with the CI?

**Comment by brainwane** [comment]
@woodruffw  @di It sounds like we should finish off the work in https://github.com/DavidBord/warehouse/tree/fix-5790-send-invitations and write up and merge a PR, since so many other features are blocked on this. Which of you could take that, maybe this week?

**Comment by DavidBord** [comment]
@brainwane I can probably get to it only next week

**Comment by brainwane** [comment]
@DavidBord OK -- if you can re-start work on it (such as submitting a Work-In-Progress pull request or getting help from us on the tests) by the end of June 7th, that's great! If you don't, then I think one of us should pick it up. Which is not a slam on you, just trying to keep the feature progress going.

**Comment by brainwane** [comment]
Hi @DavidBord -- I suggest you rebase your branch against `pypa/warehouse`'s master branch, and submit a pull request marked "WIP" in the title! That'll make it easier for us to help you with the test coverage so the CI can pass. Thank you! And it would be great if you could do that by the end of your day June 7th. :-) This feature will really help with a bunch of other stuff we'd like to build and ship as we improve account security and the usability of those new security features.

**Comment by brainwane** [comment]
We are not going to be able to finish implementing this within the scope of [the OTF-funded work we're currently doing on PyPI security](https://pyfound.blogspot.com/2019/03/commencing-security-accessibility-and.html), so I'm removing it from this milestone.

**Comment by brainwane** [comment]
A few questions we'll want to answer about the user experience here:
* can invitations be revoked?
* do invitations expire?

The backend work will involve creating a new model of invitations, creating views, supporting creating/accepting invitations, creating an email and getting it sent, and tests.

**Comment by di** [comment]
FYI, this is mostly implemented in #6054, and in that implementation invitations can be revoked and do expire.

**Comment by brainwane** [comment]
Thank you @patelneel55! Glad this is resolved!
