### ISSUE TITLE
Display whether fellow maintainers/owners have enabled 2FA

### ISSUE THREAD

**Issue by di** [pypa/warehouse#5791]
**What's the problem this feature will solve?**
Currently package owners can't determine if their fellow owners/maintainers have enabled 2FA on their accounts, which makes it difficult to maintain a certain level of security for a given package.

**Describe the solution you'd like**
On the list of roles for a project, display a label next to each user which indicates whether 2FA is enabled or disabled.

**Additional context**
Blocked on #5790, otherwise this would allow any attacker to determine the 2FA status for a given user.

**Comment by brainwane** [comment]
We are not going to be able to finish implementing this within the scope of [the OTF-funded work we're currently doing on PyPI security](https://pyfound.blogspot.com/2019/03/commencing-security-accessibility-and.html), so I'm removing it from this milestone.

**Comment by di** [comment]
This issue is no longer blocked.

**Comment by ewjoachim** [comment]
I'm going to have a go at it. If you don't see anything in a week's time, please consider this ticket free to grab, otherwise note that someone is on it :)
