### ISSUE TITLE
Sorting searches by 'Date last updated' results in 503

### ISSUE THREAD

**Issue by OmenApps** [pypa/warehouse#5796]
**Describe the bug**

When trying to search for anything on pypi.org, sorting by relevance or trending works fine, but sorting by date last updated returns a 503 error.

**Expected behavior**

Search results, sorted by date.

**To Reproduce**

Example URL: https://pypi.org/search/?q=test&o=-created

Result:

> Sorry, something went wrong
> 
> PyPI is down for maintenance or is having an outage.
> 
> This is affecting several of our services, including our web interface.
> If you are trying to install a package, you should be able to pip install packages without problem.
> 
>     Check our status page, or
>     View Python Status on Twitter

The status page, though, shows all green.

**My Platform**

- Win 10, Firefox 66.0.3
- Ubuntu 18.04, Chrome 74.0.3729.108

---

Edit: I know this functionality was working at least as recently as last Thursday, 2 May 2019.

**Comment by gsb-eng** [comment]
This is the problem with `formatting date` to human understandable format, I'm fixing this. will submit a PR soon.

**Comment by di** [comment]
This started occurring May 5, 2019 5:38:49 PM UTC, did we merge something that's causing this?

**Comment by dstufft** [comment]
I think I merged an elasticsearch update yea.
