### ISSUE TITLE
2FA not prompted on package upload?

### ISSUE THREAD

**Issue by vidartf** [pypa/warehouse#5815]
**Describe the bug**
After having just enabled 2FA on the test server, I tried uploading a new package with `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`. I was prompted for username and password as normal, and it then uploaded the packages successfully. It never prompted for a 2FA key.

**Expected behavior**
Either it should prompt for a 2FA key, or it should fail.

**My Platform**
* Windows 10
* `twine version 1.13.0 (pkginfo: 1.5.0.1, requests: 2.21.0, setuptools: 40.6.3, requests-toolbelt: 0.9.1, tqdm: 4.31.1)`

Xref #5661

**Comment by vidartf** [comment]
Thanks for the reply. Not entirely sure what is meant by an API key (https://stackoverflow.com/questions/1453073/what-is-an-api-key#1453082). Is this some long lasting token, or a one-time key?

**Comment by alex** [comment]
It's a long time key, with restricted privs -- there's a bug for it, but
I'm on my phone so I can't easily access it, sorry!

**Comment by jezdez** [comment]
The issue in question is #994.

**Comment by vidartf** [comment]
Neat. So I assume that means 2FA push to prod is blocked on #994, and that uploads through any route will fail if:
- 2FA is enabled.
- No 2FA-circumventing token is used.

Will there be a non-browser upload method supporting 2FA?

**Comment by woodruffw** [comment]
> Will there be a non-browser upload method supporting 2FA?

Probably not. We discussed some schemes early on that would allow users to embed e.g. a TOTP token alongside their password, but the ultimate goal is to remove password authentication for package upload entirely and go with well-scoped API keys instead.

**Comment by brainwane** [comment]
@vidartf per https://github.com/pypa/warehouse/issues/994#issuecomment-493171700 , although we do not plan to enable 2FA for package upload, we _do_ plan to use API keys to better secure package upload (such as via `twine`).
