### ISSUE TITLE
2FA token field not cleared on invalid input

### ISSUE THREAD

**Issue by MarkusH** [pypa/warehouse#5816]
**Describe the bug**

With enabled 2FA, when I login, and enter a wrong TOTP, and click "verify", the token verification fails (as expected) but the form field for the token still shows the wrong TOTP.

**Expected behavior**

I'd expect the input field to be cleared and not contain the invalid TOTP.

**My Platform**

* Firefox Nightly
* Arch Linux

**Additional context**

I tried this on https://pypi.org and https://test.pypi.org .

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by di** [comment]
I've added the `good-first-issue` label to this issue.

**Comment by brainwane** [comment]
@theb10n707 or @ppiyakk2 would you like to help us with this?

**Comment by ppiyakk2** [comment]
@brainwane Of course! Let me solve this issue.

**Comment by brainwane** [comment]
@ppiyakk2 Great! Please go ahead and work on it -- let us know if you have any trouble!

**Comment by brainwane** [comment]
@ppiyakk2 how is this going?

**Comment by ppiyakk2** [comment]
@brainwane  I reproduced this bug on almost browser, and try to fix it. Maybe I can send a PR on Friday.

**Comment by ppiyakk2** [comment]
@di  I want to test 2FA in my dev env. How can I enable this function?

**Comment by brainwane** [comment]
Hi, @ppiyakk2 -- I think you'd want to merge in #5889 locally in order to test 2FA in your developer environment. @woodruffw @di please speak up if I'm wrong! :-)

**Comment by woodruffw** [comment]
Yep, #5589 should do it. If you don't want to merge that AOT, you could also enable 2FA on your testing account within the admin panel (or by executing some SQL to set `two_factor_allowed` on your user manually).

**Comment by brainwane** [comment]
@ppiyakk2 how is this going? Are you having trouble with your development environment?

**Comment by woodruffw** [comment]
To follow up a bit: you shouldn't need to do any manual SQL anymore -- we've removed `two_factor_allowed` from the User model.
