### ISSUE TITLE
Ability to define a documentation URL

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#583]
We'll need some way for people to define documentation URLs to replace the old legacy documentation. Some possible options:

* Add a new database field that people can indicate where their documentation is hosted.
* Utilize the project_urls data with a "Documentation" key.

**Comment by crooksey** [comment]
Could this not be expanded to support Readme.md files (seeing as currently this is not supported)?

**Comment by dstufft** [comment]
``Readme.md`` files are not really related to this particular ticket, though it is something we want to make possible in the future. It relies on getting metadata 2.0 done though, to be able to indicate that the ``long_description`` is markdown instead of rst.

**Comment by dstufft** [comment]
I wonder if this could just be handled by a ``Documentation`` project-url, one that we fill in with the legacy documentation URL if one exists and otherwise just allow people to fill one in with their specific links.

**Comment by dstufft** [comment]
I'm going to go ahead and close this. I think the best way to handle this is to just support a ``Documentation`` project URL.

**Comment by waveform80** [comment]
We're currently looking to transition a project from pythonhosted docs to RTD docs and I've been looking into how to redirect users from the existing docs to the new set; is the `Documentation` URL now supported or is meta-data 2.0 (mentioned above) yet to be done? I've tried searching the issues and PRs for relevant bits but I'm drawing a blank so far and wondered if someone could let me know how things stand at the moment?

**Comment by brainwane** [comment]
@waveform80 I'm so sorry for the long delay in reply. Please see #582 for where people are trying to work much of this out, and https://packaging.python.org/tutorials/distributing-packages/#project-urls for a recommended way to point users to multiple URLs (including documentation) in a PyPI project page.
