### ISSUE TITLE
Request for file size limit exemption of new simbench package

### ISSUE THREAD

**Issue by SteffenMeinecke** [pypa/warehouse#5845]
Dear PyPI experts,
I request you to increase the file size limit for the new simbench package which is already available on GitHub: https://github.com/e2nIEE/simbench
In dist/* the zip size is currently about 90 MB. Consequently both must be increased, PyPI and Test PyPI.

The objective of the research project SimBench is the development of a benchmark data set to support research in grid planning and operation. SimBench Grid differs from other benchmark grids under the following key points:

- Consideration of a wide range of use cases during the development of data sets
- Provision of grid data for low voltage (LV), medium voltage (MV), high voltage (HV), extra high voltage (EHV) as well as design of data sets for a suitable interconnection of a grid among different voltage levels for cross-level simulations
- Ensuring highreproducibility and comparability by providing clearly assigned load and generation time series
- Validation of the suitability of the data sets with simulation, deliberately determined grid states including suitable dimensioning of grid assets

Since the repository includes both, the basic data of the grids and the code to make the data usable for pandapower (https://pypi.org/project/pandapower/), a minimum size of about 90-100 MB is needed.

**Comment by jamadden** [comment]
In order for the PyPI admins to adjust the size constraints  for the project, you'll need to upload an empty release to create the project first. I'd recommend using version number 0.0.0 and deleting the release afterwards (the project will remain).

**Comment by SteffenMeinecke** [comment]
Thanks for your response.
I guess that empty release is needed for both, Test PyPI and PyPI.

**Comment by jamadden** [comment]
> I guess that empty release is needed for both, Test PyPI and PyPI.

If you intend to use both pypi.org and test.pypi.org, then yes, the project must be created on both sites.

**Comment by SteffenMeinecke** [comment]
Dear jamadden,
I added the initial packages simbench to PyPI and TestPyPi: https://pypi.org/project/simbench/ https://test.pypi.org/project/simbench/
In setup.py I included README_without_images.rst since I had troubles to include images to the pypi description. Do you have an idea why the classifiers are not properly depicted on the left side of https://pypi.org/project/simbench/ and how I can integrate the simbench logo and the shields to the description in PyPI?

**Comment by jamadden** [comment]
The upload limit for those packages has been set to 100MB.

Just a guess about your README.rst: The file shipped in your sdist contains a mix of CRLF and plain CR line endings (that is, there are some Windows line endings and some Unix line endings). Consequently, the metadata file (PKG-INFO) also has a mix of CRLF and CR endings. I'm going to guess that confused the metadata tools and they weren't able to determine the expected content type to render with, nor read anything in the file after that. Try using only Unix line endings.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/1256082/57703289-62810180-7625-11e9-89c9-4f0d567a1a3d.png">
