### ISSUE TITLE
PEP541: Release unused project name "garage"

### ISSUE THREAD

**Issue by ryanjulian** [pypa/warehouse#5852]
I'd like to take ownership over the PyPI project name `garage` so that our organization can distribute [a machine learning library under the name](https://github.com/rlworkgroup/garage).

We publish several related RL libraries on PyPI:
https://pypi.org/project/akro/
https://pypi.org/project/viskit/
https://pypi.org/project/dowel/

* I cannot upload to PyPI using the package name `garage`, but the [package has no uploaded data or releases](https://pypi.org/project/garage/).
* This has been the case for at least a year, when I first tried to use the name `garage` to upload to PyPI.
* No author information is publicly-available on PyPI (as far as I can tell), so I have not been able to contact the author of the PyPI entry

I believe this falls under the ["Invalid project"](https://www.python.org/dev/peps/pep-0541/#invalid-projects) case described in PEP541.

It is possible to transfer the project to my account? Please let me know how I can help, or if I need to provide any more information

**Comment by jamadden** [comment]
I believe @jezdez is the owner of the PyPI project "garage". Perhaps they'll see this ping and respond here. They also list some contact information at https://github.com/jezdez

**Comment by ryanjulian** [comment]
thanks @jamadden -- i will contact @jezdez and report back

**Comment by jezdez** [comment]
Hi all, I've replied to @ryanjulian's email directly and added them to the project as requested. For some reason I wasn't able to remove myself as owner though, let's see if @ryanjulian can figure this out.

**Comment by ryanjulian** [comment]
Removed. Cheers. Thanks @jezdez and @jamadden !
