### ISSUE TITLE
test.pypi.org Trove classifiers not up to date

### ISSUE THREAD

**Issue by tbekolay** [pypa/warehouse#5860]
**Describe the bug**
We attempted to push a release to PyPI with the new `Framework :: Nengo` Trove classifier, but receive a 400 error that it's an invalid value (see this [build log](https://travis-ci.org/nengo/nengo-bones/jobs/533099942#L961)).

**Expected behavior**
For the release to succeed.

**To Reproduce**
Any `setup.py` using the `Framework :: Nengo` Trove classifier will fail when publishing to test.pypi.org

**My Platform**
The full [TravisCI build log](https://travis-ci.org/nengo/nengo-bones/jobs/533099942) has platform details.

**Additional context**
The classifier was added a few weeks ago, if memory serves.

**Comment by jamadden** [comment]
#5628 added the classifier to pypi.org. There's not an automated process to also add them to test.pypi.org, so due to the extra work involved that often gets forgotten or overlooked unless someone mentions that specifically.

I've added this classifier to test.pypi.org. Sorry for the trouble.

**Comment by tbekolay** [comment]
Thanks a lot for the quick resolution!
