### ISSUE TITLE
Require verified email before allowing user to enable 2FA

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#5866]
**What's the problem this feature will solve?**
Sometimes people enable two-factor auth and then run into some kind of problem like losing access to their provisioned TOTP-generating app. We want to make it easier for PyPI admins to check the legitimacy of users' requests for account recovery in such circumstances.

**Describe the solution you'd like**
Prohibit users from enabling any 2FA until the user has verified at least one email address on their account.

**Additional context**
(followup to #5661, filed on @di's behalf)

**Comment by woodruffw** [comment]
Working on this now.

**Comment by woodruffw** [comment]
Opened #5889 for this.
