### ISSUE TITLE
Increase size limit request

### ISSUE THREAD

**Issue by ivansiiito** [pypa/warehouse#5877]
Hi!

I would like to have extra space for my project https://pypi.org/project/syntactic-tagger/. I need at least 220MB in the PyPI index (as this is an initial version, I would ask for 250MB just in case).

My project is a pure Python implementation of a part-of-speech tagger for Spanish text. I wrote an academic paper that is going to be published soon, which is about a new technique for a part-of-speech tagger construction. The code of this package contains the program that I used to validate the possibility of using this new technique for Spanish language, and to be able to evaluate the results. I want to make it available, so I can include it in my paper, and other people can use it and completely understand what they read in the article, possible replicating it for some other languages.

It is so big because it contains several syntactic tables, created using the Spanish Wikipedia, appart from a quite huge lexicon and some other data files.

Thanks a lot!

**Comment by jamadden** [comment]
The upload limit has been set to 250MB on pypi.org.
