### ISSUE TITLE
File size limit increase request 

### ISSUE THREAD

**Issue by ruohoruotsi** [pypa/warehouse#5896]
- A link to your project on PyPI: https://pypi.org/project/iranlowo/
- The size of your release, in megabytes: 65-75MB
- Which index/indexes you need the increase for: PyPI
- A brief description of your project, including the reason for the additional size.
Greetings, thank you for this service. My project is a utility library for African language technology developers and researchers. One component of the library is an NLP neural-net model that can correct/normalize low-quality text. This model coming out of the PyTorch training session was over 200MB, and I optimized it by removing extraneous (debugging & optimization) bits down to about 68MB. Aside from the NLP model, the library is tiny.

I did not realize there was a limit of 60MB until I tried to upload and was met with this message to humbly request more memory. I am pretty close to the limit so I thought it worth the effort to make a formal request. cheers, iroro

**Comment by jamadden** [comment]
Thanks for the request. 

The [Homepage](https://github.com/Niger-Volta-LTI/iranlowo) link for the project points to a github repository that doesn't seem to exist. Could you please let us know what the correct github repo is?

**Comment by ruohoruotsi** [comment]
Give it a try now:
https://github.com/ruohoruotsi/iranlowo

it was private and under my account. Once everything is working well, I'll move it to the organization and make it public forever (the link you clicked on pypi). Apologies for the confusion.

**Comment by jamadden** [comment]
The upload limit for  iranlowo has been set to 100MB on pypi.org.
