### ISSUE TITLE
PEP 541: Transfer ownership of unmaintained `django-pygment` from unknown owner to  @stefantalpalaru

### ISSUE THREAD

**Issue by shurph** [pypa/warehouse#5905]
Hi,

I would like to start process of transfering ownership of the name `django-pygment` from  an unknown PyPI package owner to the current maintainer — @stefantalpalaru.

The current PyPI package is not maintained since [the first upload in 2013](https://pypi.org/project/django-pygments/#history).

As I understand from the discussion in the Pull Request (https://github.com/odeoncg/django-pygments/pull/12#issuecomment-485014055) project was uploaded to PyPI by unknown person who maybe was not related to the  `django-pygment`.

The project main author, Stefan Talpalaru, maintains now this project in  the [stefantalpalaru / django-pygments](https://github.com/stefantalpalaru/django-pygments/) repo using github account @stefantalpalaru.

Project contributors [agree with authorship and conditions](https://github.com/stefantalpalaru/django-pygments/issues/1).

References #1506.

**Comment by stefantalpalaru** [comment]
Thanks, @shurph! My PyPI account is: https://pypi.org/user/stefantalpalaru/

**Comment by jamadden** [comment]
One of the first parts of the PEP that governs name transfers, [PEP541](https://www.python.org/dev/peps/pep-0541/), is to attempt to contact the project owner. I've emailed the address we have on file for [tavein](https://pypi.org/user/tavein/), the owner of the project.

**Comment by tavein** [comment]
I'm that unknown owner (Jason contacted me via email) and have nothing against transferring ownership of django-pygments to Stefan. The reason why I took ownership of the project in the first place is that it was abandoned then.

**Comment by jamadden** [comment]
@tavein Thanks for responding! In order to do so, please log into your pypi.org account and add `stefantalpalaru` as another owner. When that's done, @stefantalpalaru should get an email notification, and could then log in and remove the `tavein` account as an owner if desired.

**Comment by tavein** [comment]
> @tavein Thanks for responding! In order to do so, please log into your pypi.org account and add `stefantalpalaru` as another owner. When that's done, @stefantalpalaru should get an email notification, and could then log in and remove the `tavein` account as an owner if desired.

done

**Comment by stefantalpalaru** [comment]
Thank you. New version released: https://pypi.org/project/django-pygments/0.3/
