### ISSUE TITLE
Add option to display primary email on public profile

### ISSUE THREAD

**Issue by di** [pypa/warehouse#5944]
**What's the problem this feature will solve?**
Currently there's no way to publicly display an email address as a point of contact for a PyPI account. Instead, maintainer/author emails for a user's packages must be used instead.

**Describe the solution you'd like**
Similar to Github, on the ["Account Settings"](https://pypi.org/manage/account/) page, we should have an option such as:

> ☑️**Keep my email address private**
> We won't show your primary email on your public PyPI profile page.

This should default to "True" for all new and existing users.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by pradyunsg** [comment]
This would be a great addition! :D

**Comment by brainwane** [comment]
@pgadige is this something you'd like to try working on?

**Comment by pgadige** [comment]
Thank you, @brainwane, for suggesting this one. I'm working on it.

**Comment by brainwane** [comment]
@pgadige How is it going? Do you have a branch somewhere that we can look at?

**Comment by pgadige** [comment]
@brainwane, I'm figuring out few JavaScript things (I'm a newbie to JS) for displaying the email address properly on the page. I managed to break the CSS of the page couple of times. I think I'll try to submit a PR by the EOD so the reviewers can show me what exactly I'm doing wrong.

**Comment by brainwane** [comment]
@pgadige Looking forward to that PR!

**Comment by brainwane** [comment]
I just emailed with @pgadige and she'll be working on sharing a work-in-progress pull request with us in the next few days.

@pgadige: If you are working on this issue and have questions or get stuck, please feel free to speak up here, or in [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or on the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).
