### ISSUE TITLE
File size limit increase for pystan

### ISSUE THREAD

**Issue by riddell-stan** [pypa/warehouse#5950]
- project: https://pypi.org/project/pystan/
- size: windows 64 wheel is ~77M
- indexes: PyPI

PyStan is a scientific computing package. Compiled extension modules are the reason the file size is so large.

PyStan provides a Python interface to Stan (1,579 GitHub stars), a package for Bayesian inference using the No-U-Turn sampler, a variant of Hamiltonian Monte Carlo.

May we have a limit of 100M? Releases are (relatively) infrequent.

**Comment by jamadden** [comment]
The limit for pystan has been set to 100MB on pypi.org
