### ISSUE TITLE
Not receiving TestPyPI verification emails

### ISSUE THREAD

**Issue by bexer** [pypa/warehouse#5957]
Hi - I'm having the same issue from #4704 and a few others I've seen. I've tried a few times to get the verification emails from test over the past two days but haven't gotten any (live PyPI goes through immediately however).

**Comment by di** [comment]
Hi, can you share your PyPI username with us?

**Comment by bexer** [comment]
bexer

**Comment by di** [comment]
I'm seeing multiple emails marked as delivered to a `@yahoo.com` address:

<img width="1003" alt="Screen Shot 2019-06-04 at 6 53 52 PM" src="https://user-images.githubusercontent.com/294415/58920969-2f003700-86fa-11e9-95d9-e2d679ef9ddd.png">

Is it possible these are getting filtered or marked as spam?

**Comment by bexer** [comment]
Of course that was it.

Thanks.
