### ISSUE TITLE
Malware packages on PyPI

### ISSUE THREAD

**Issue by lingfennan** [pypa/warehouse#5962]
Package `jajajejejiji` and `rstseuqe` are malware that steal user information. Please consider removing them. These two packages upload information to a remote server including: name of the downloaded package, name of the intended package, the python version and whether the process was running as sudo. It seems to be part of the malware campaign that was identified and removed in NpmJS registry. Please find links to the package and NpmJS report below.

https://www.npmjs.com/advisories/838
https://pypi.org/project/jajajejejiji/
https://pypi.org/project/rstseuqe/

**Comment by di** [comment]
Thanks for the report. I've removed the projects and permanently banned those project names.
