### ISSUE TITLE
Requesting Larger Limit

### ISSUE THREAD

**Issue by josephmancuso** [pypa/warehouse#5979]
A link to your project on PyPI (or Test PyPI)
https://pypi.org/project/masonite-selenium/

The size of your release, in megabytes
67MB

Which index/indexes you need the increase for (PyPI, Test PyPI, or both)
PyPI

A brief description of your project, including the reason for the additional size.
I'm the creator of the Masonite framework https://github.com/masoniteframework/masonite and I am creating a selenium package which has a few bulky drivers associated with it. It would be great if the package can ship with these drivers so developers don't have to scour the internet, find them and then insert the full path and debug. I'd like this package for Masonite to install and go.

Thank you in advance!

**Comment by jamadden** [comment]
The upload limit has been increased to 100MB on pypi.org.
