### ISSUE TITLE
Choose localization framework

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#5982]
Evaluate localization frameworks and identify one that is compatible with Warehouse's web framework, Pyramid. (See #1453 for prior thoughts.)

We assume that @woodruffw or a colleague of his at Trail of Bits will do this work.

**Additional context**
This is toward the goal of implementing internationalization support into the PyPI UI (#1453), making changes that will broaden the audience of users that can operate the PyPI interface. It's part of [the Open Technology Fund-supported work](https://github.com/python/request-for/blob/master/2019-Q1-PyPI/RFP.md#specific-tasks-1) for mid-2019.

[Thanks to OTF for their support for this work!](https://pyfound.blogspot.com/2019/03/commencing-security-accessibility-and.html)

**Comment by woodruffw** [comment]
For tracking purposes: #6535 uses `pyramid.i18n` and `pybabel` as its localization framework.

**Comment by nlhkabu** [comment]
Closing this as #6535 is now merged
