### ISSUE TITLE
Systematically find English-hardcoded UI messages

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#5983]
**What's the problem this feature will solve?**
We have a bunch of hardcoded English strings that aren't localizable, but we don't know what they are yet.

**Describe the solution you'd like**
Identify all text strings in Warehouse browser views and email templates which require localization.

We assume that @woodruffw or a colleague of his at Trail of Bits will do this work.

**Additional context**
This is toward the goal of implementing internationalization support into the PyPI UI (#1453), making changes that will broaden the audience of users that can operate the PyPI interface. It's part of [the Open Technology Fund-supported work](https://github.com/python/request-for/blob/master/2019-Q1-PyPI/RFP.md#specific-tasks-1) for mid-2019.

[Thanks to OTF for their support for this work!](https://pyfound.blogspot.com/2019/03/commencing-security-accessibility-and.html)

**Comment by woodruffw** [comment]
We'll roll this into #5984.
