### ISSUE TITLE
Replace hardcoded UI strings with localizable messages

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#5984]
**What's the problem this feature will solve?**
We have a bunch of hardcoded English strings that aren't yet localizable.

**Describe the solution you'd like**
Replace hardcoded English messages (found via #5983) with localizable messages using the localization framework (chosen in #5982).

See https://github.com/pypa/warehouse/issues/1453#issuecomment-365308151 on using Pyramid's existing localization/internationalization support in our templates:

> The actual marking of strings for translation can be done pretty easily with [`pyramid.i18n`](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/i18n.html) which provides a `request.localizer.translate` function, and [`pyramid-jinja2`](https://pypi.org/project/pyramid_jinja2/) which provides the same function for our Jinja2 templates.
> 
> The marked strings can then be extracted and compiled for translation with [`babel`](http://babel.pocoo.org/en/latest/index.html)

Note that, per that comment, this issue also includes:

>     * updating them (and all the tests that this will break, which will be a lot)
>     * figuring out how this will affect caching

And, per [our meeting yesterday](https://wiki.python.org/psf/PackagingWG/2019-06-07-Warehouse) and other comments in #1453, we'll need to provide _context_ for each string/message.

**Additional context**
Blocked on #5983 and possibly #5982.

This is toward the goal of implementing internationalization support into the PyPI UI (#1453), making changes that will broaden the audience of users that can operate the PyPI interface. It's part of [the Open Technology Fund-supported work](https://github.com/python/request-for/blob/master/2019-Q1-PyPI/RFP.md#specific-tasks-1) for mid-2019.

[Thanks to OTF for their support for this work!](https://pyfound.blogspot.com/2019/03/commencing-security-accessibility-and.html)

**Comment by nlhkabu** [comment]
I think the first step here is to localize the strings, and the second should be to assess where we actually *need* contexts.

I think we should keep this simple: we want to avoid a situation where we have to translate the same string twice, because we've added different contexts.

**Comment by nlhkabu** [comment]
A few ideas re: contexts:

1. We should add a new GitHub issue type where translators can request context for a specific string
2. We should add a new GitHUb issue type where PyPI users can report poor translations
3. We should add a section to our documentation specifically for translators
