### ISSUE TITLE
Evaluate and choose localization/translation platform

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#5985]
**What's the problem this feature will solve?**
Even once our strings are localizable, we need to provide a platform for translators to easily view the messages that need translating, and submit and approve translations.

**Describe the solution you'd like**
Evaluate localization platforms/websites, like Transifex and TranslateWiki, and identify a compatible choice. Consider data and software licenses, cost, existing translator communities, ease of integration with the Warehouse CI process, and other considerations.

**Additional context**
Depends on partial completion of #5984.

This is toward the goal of implementing internationalization support into the PyPI UI (#1453), making changes that will broaden the audience of users that can operate the PyPI interface. It's part of [the Open Technology Fund-supported work](https://github.com/python/request-for/blob/master/2019-Q1-PyPI/RFP.md#specific-tasks-1) for mid-2019.

[Thanks to OTF for their support for this work!](https://pyfound.blogspot.com/2019/03/commencing-security-accessibility-and.html)

**Comment by woodruffw** [comment]
For tracking purposes: Weblate is currently the chief candidate among translation platforms.

**Comment by nlhkabu** [comment]
Closing this as we have integrated Weblate in #6535
