### ISSUE TITLE
Integrate Warehouse with translation/localization platform service

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#5986]
**What's the problem this feature will solve?**
In order for a localization/translation platform to be of use to us, we need to hook it up to Warehouse and PyPI to fetch and integrate new translations.

**Describe the solution you'd like**
Integrate PyPI with the selected localization/translation platform, enabling continuous localization. Where necessary, create tooling to support translators and to integrate translations into PyPI.

We assume that @woodruffw or a colleague of his at Trail of Bits will do this work.

**Additional context**
Blocked on #5982 and #5985.

This is toward the goal of implementing internationalization support into the PyPI UI (#1453), making changes that will broaden the audience of users that can operate the PyPI interface. It's part of [the Open Technology Fund-supported work](https://github.com/python/request-for/blob/master/2019-Q1-PyPI/RFP.md#specific-tasks-1) for mid-2019.

[Thanks to OTF for their support for this work!](https://pyfound.blogspot.com/2019/03/commencing-security-accessibility-and.html)

**Comment by nlhkabu** [comment]
Closing as per #6535
