### ISSUE TITLE
pip install fbprophet  gcc error in centos 7

### ISSUE THREAD

**Issue by gitdckap** [pypa/warehouse#5988]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by gitdckap** [comment]
When i try to install pip install fbprophet in centos 7,  we are getting gcc error, when i tried in ubuntu, its working without error, do you have any bug in the cent os 7

**Comment by jamadden** [comment]
Thanks for the report, but unfortunately this is the wrong place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help with installing packages distributed from there. For that, you'll need to contact the package's maintainers. There are a few possible methods of contact listed on https://pypi.org/project/fbprophet/

**Comment by pradyunsg** [comment]
@gitdckap The issue tracker for that project, is at https://github.com/facebook/prophet/.
