### ISSUE TITLE
a11y: ARIA landmarks

### ISSUE THREAD

**Issue by woodruffw** [pypa/warehouse#6008]
Warehouse's frontend should support ARIA landmarks for key page elements, or use their dedicated semantic HTML5 equivalents where possible.

Examples:

* The package search `<form>` on the index and other pages should include `role=search`
    * The search `<form>` included via `base.html` includes `role=search`, but on an internal `<div>` instead of the form itself
* Session notifications/flashes *might* benefit from `role=alert`. `role=alert` is usually used when transitioning from `display: none`, but it may make sense to use it for important/security-sensitive notifications.

**Comment by nlhkabu** [comment]
Closed by #6123 and https://github.com/pypa/warehouse/pull/6150
