### ISSUE TITLE
Document what's allowed in a WebAuthn key name

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#6011]
In the WebAuthn account settings guidance, under "Please give this key a name" -- concisely document what is allowed in a key name (ASCII? Unicode? Emoji? Spaces?).

**Comment by woodruffw** [comment]
Any and all Unicode should be valid within a key label, up to 64 codepoints I'm not sure what WTForms counts as a "character" in its length validator). That means that emoji and spaces should both work.
