### ISSUE TITLE
File Size Limit Increase Reqeust

### ISSUE THREAD

**Issue by dstein64** [pypa/warehouse#6024]
Per the instructions on [pypi.org](https://pypi.org/project/pastiche/), I've opened this issue to request a file size limit increase for my project.

#### A link to your project on PyPI (or Test PyPI)

https://pypi.org/project/pastiche/

#### The size of your release, in megabytes

74.5M when compressed in tar.gz (80.2M uncompressed)

I request an increase slightly above this, to accommodate future source code updates.

#### Which index/indexes you need the increase for (PyPI, Test PyPI, or both)

PyPI

#### A brief description of your project, including the reason for the additional size.

My project applies style transfer (Gatys) to images. This relies on weights in the VGG neural network, which takes about 80.1M uncompressed.

**Comment by pradyunsg** [comment]
I've set the limit for `pastiche` to 100 MB on PyPI.
