### ISSUE TITLE
password reset fails for use chris.r.burns

### ISSUE THREAD

**Issue by chrisrburns** [pypa/warehouse#6030]
I received the notification that my password was breached and I needed to reset. I did so and it says the reset email was sent, but I have not received it. I checked spam folder. It's possible that the original email under which I registered the account was [redacted by maintainers]. If so, that domain no longer exists and I need to update it to [redacted by maintainers]. Pls help.

**Comment by ewdurbin** [comment]
Hi @chrisrburns please email ernest@python.org and I'll assist you.

**Comment by ewdurbin** [comment]
addressed.
