### ISSUE TITLE
Going straight to URL ending in #history or #files causes browser to scroll to bottom of page

### ISSUE THREAD

**Issue by njsmith** [pypa/warehouse#6036]
**Describe the bug**

When I click on either of these URLs:

* https://pypi.org/project/black/#files
* https://pypi.org/project/black/#history

Then I end up staring at PyPI's big blue footer:

![image](https://user-images.githubusercontent.com/609896/59637978-fd309c80-910b-11e9-803e-99b025649bda.png)

And then I have to manually scroll up to see the content.

This only happens when clicking a link to visit PyPI from outside, or opening a new tab. It doesn't happen if I'm already inside PyPI and click on one of the navigation links on the left.

**Expected behavior**

I expect links with anchors to take me to the top of the page, where the content is.

**To Reproduce**

As above.

**My Platform**

Firefox on Linux.

**Additional context**

n/a

**Comment by ewdurbin** [comment]
Able to reproduce in Firefox 67.0.1 on MacOS as well. Safari and Chrome do not seem to exhibit this behavior.

**Comment by di** [comment]
This should be fixed in #6135, but it will likely take a bit for the old script to fall out of the cache.
