### ISSUE TITLE
Increase file upload limit for pybacktrack

### ISSUE THREAD

**Issue by jcannon-gplates** [pypa/warehouse#6037]
Our first release (1.0) was under 60MB, however our second release (1.1) is close to 80Mb and cannot be uploaded. So it would be great if our upload limit could be increased. Also future releases will probably be even bigger.

The project link: https://pypi.org/project/pybacktrack/
Indexes needed: Only PyPI.
Project description: A scientific tool for reconstructing paleobathymetry on oceanic and continental crust.

**Comment by pradyunsg** [comment]
I've gone ahead and set the limit to 100 MB for pybacktrack on PyPI. :)
