### ISSUE TITLE
Integrate statuspage.io

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#604]
We'll want to integrate statuspage.io so that people can get a link to the status.python.org incidents when one is occuring. They have a web API that we are currently using via javascript on pypi.python.org.

See: https://status-page-blog.herokuapp.com/embed-system-status-within-your-webapp

**Comment by nlhkabu** [comment]
Design specification:

![screenshot from 2016-06-30 06-52-09](https://cloud.githubusercontent.com/assets/3323703/16478074/36753672-3e8f-11e6-8a1b-7beefb0ea379.png)
