### ISSUE TITLE
Recover access

### ISSUE THREAD

**Issue by sonnyvan** [pypa/warehouse#6042]
Hello,

I am trying to recover access to our PyPI account: plangrid.

Thank you,
Sonny Van

**Comment by yeraydiazdiaz** [comment]
Hello @sonnyvan, is the "Forgot password" link on the [login page](https://pypi.org/account/login/) not working for you?

**Comment by sonnyvan** [comment]
Hello, we weren't sure where the email was sent to and @ewdurbin helped me figure which inbox.

Thank you
