### ISSUE TITLE
Request to add License :: OSI Approved :: Open Software License 3.0 (OSL-3.0)

### ISSUE THREAD

**Issue by pope1ni** [pypa/warehouse#6063]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `License :: OSI Approved :: Open Software License 3.0 (OSL-3.0)`

## Why do you want to add this classifier?

It is an OSI Approved license that I have to use which has been missed off the list.

See https://opensource.org/licenses/OSL-3.0

**Comment by pradyunsg** [comment]
Added classifier 'License :: OSI Approved :: Open Software License 3.0 (OSL-3.0)'. :)
