### ISSUE TITLE
Service unavailable (503) on register page, pypi.org

### ISSUE THREAD

**Issue by suyash091** [pypa/warehouse#6071]
Once you try to register on https://pypi.org/account/register/, after filling all the details the site crashes with error 503. 
it says as follows:

Sorry, something went wrong
PyPI is down for maintenance or is having an outage.

This is affecting several of our services, including our web interface.
If you are trying to install a package, you should be able to pip install packages without problem.

Check our status page, or
View Python Status on Twitter
Rely on PyPI to get your job done?

**Comment by brainwane** [comment]
Thanks for the bug report @suyash091 -- Are you still experiencing this problem? I looked at our metrics dashboard and I think things _should_ be fine now...

**Comment by suyash091** [comment]
![Capture2](https://user-images.githubusercontent.com/25162118/59967421-26f02600-9547-11e9-980e-172acf5a3345.PNG)
Sorry, but it is still there. on metrics, it isn't showing up.

**Comment by suyash091** [comment]
its up and running now.

**Comment by ewdurbin** [comment]
Based on our metrics, it appears that our Content Delivery Network provider's Point of Presence in Mumbai was experiencing issues reaching the backends during this timeframe. We don't have a whole lot of visibility into what might cause a global routing issue like that unfortunately.

Can you confirm if you are near Mumbai? If so this is likely related to that transient error.
