### ISSUE TITLE
Increase file upload limit for paddlepaddle

### ISSUE THREAD

**Issue by kolinwei** [pypa/warehouse#6076]
Our first release (1.4) was under 50MB, however our second release (1.5) is close to 80Mb and cannot be uploaded. So it would be great if our upload limit could be increased. Also future releases will probably be even bigger.

The project link: https://pypi.org/project/paddlepaddle/
Indexes needed: Only PyPI.
Project description: PaddlePaddle (PArallel Distributed Deep LEarning) is an easy-to-use, efficient, flexible and scalable deep learning platform.

**Comment by jamadden** [comment]
I show paddlepaddle having a 100MB limit on pypi.org.
