### ISSUE TITLE
Increasing package size limit for mrexo 

### ISSUE THREAD

**Issue by shbhuk** [pypa/warehouse#6083]
Hi,
I'm requesting a size limit increase of the PyPI package mrexo's wheel to 200 MB. They stand at 108 MB right now, and am asking for a buffer in case the size of the package grows.

This is an astronomy package with some data products that are shipped along with the package, and are responsible for the size.

Thanks!

https://pypi.org/project/mrexo/

**Comment by shbhuk** [comment]
Hi, just checking in. Is there additional information needed?

**Comment by jamadden** [comment]
The limit has been increased on pypi.org

**Comment by shbhuk** [comment]
Thank you!
