### ISSUE TITLE
HTTPError: 400 Client Error: File too large. Limit for project 'tensorflow-tflex' is 60 MB. See https://test.pypi.org/help/#file-size-limit for url: https://test.pypi.org/legacy/

### ISSUE THREAD

**Issue by HangJie720** [pypa/warehouse#6097]
My Program is advanced tensorflow, named as tensorflow-tflex, for edge computing. Size is 69.1M, could you help me increase the upload size limit? Thank you very much !
-rw-r--r-- 1 jie.hang default  70M Jun 25 17:52 tensorflow_tflex-1.13.1-cp27-cp27mu-linux_x86_64.whl

**Comment by HangJie720** [comment]
I upload a empy packages, which web site is: https://pypi.org/project/tensorflow-tflex/
HTTPError: 400 Client Error: File too large. Limit for project 'tensorflow-tflex' is 60 MB. See https://test.pypi.org/help/#file-size-limit for url: https://test.pypi.org/legacy/

**Comment by jamadden** [comment]
The limit for tensorflow-tflex has been set to 100MB on pypi.org and test.pypi.org.

**Comment by HangJie720** [comment]
Excuse me again, I have 2 questions?
(1) I have delete my project and corresponding file, but when I use pip to install tflex or tensorflow-tflex, system still Using cached https://pypi.doubanio.com/packages/7b/1a/53c197643f62cebe06efb526ac6502caa65a2edc9c3f158ee048403da4dc/tflex-0.0.3-py2.py3-none-any.whl, which have been deleted. Although I upload new version, still install old version. Could you help me release all the cache? Thank you very much ! ! !
(2) The second problem is: I have a tensorflow-tflex program，tensorflow_tflex-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl, its size is 70M，when i upload directly，Limit for project 'tensorflow-tflex' is 60 MB. Could you help me increase the upload size for my account directly?

Because, in yesterday, I create an empty packages with tensorflow_tflex-0.0.3-py2.py3-none-any.whl and upload, then, you help me upload the size to 100M. Then, I upload tensorflow_tflex-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl, when I pip install tensorflow-tflex，tensorflow_tflex-0.0.3-py2.py3-none-any.whl are still installed instead of tensorflow_tflex-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl, why?

In general, I hope I can upload tensorflow_tflex-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl directly without create empty project, which size is 70M, while my account upload size are limited.
(3) if not, I have recreated the tensorflow-tflex project, could you help me resize this upload size again. The previous package has been deleted.
https://pypi.org/project/tensorflow-tflex/
