### ISSUE TITLE
Python package/requirement with the name - 'module' is not found now.

### ISSUE THREAD

**Issue by achitroj** [pypa/warehouse#6098]
In our project we have a package with the name - '**module**' in requirements.txt file. Today while deploying our application, we faced an issue from pip that it is not able to find the package '**module**'. But earlier, this was easily found. 
I also searched Python package directory on - _https://pypi.org/_ but could not find this package.
Looks like this has been deleted. Can you guys provide me any info what has happened to this package?
We have the entry as:
module==0.2.1 in our requirements.txt file.

Thanks in advance.

**Comment by di** [comment]
Looks like the maintainer deleted this project yesterday, unfortunately I don't have more details as to why. I'll reach out to them and point them towards this thread, however there's not much else we can do here, so I'm going to close this issue as well.
