### ISSUE TITLE
2fa: token timeout problem

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#6103]
This is copied (with permission) from an email from @steiza.

> I signed in to username "steiza" and added an Authentication App and a WebAuthn token (YubiKey Nano).

> .... For the WebAuthn token I was not able to get it to work. I was able to register the token just fine, but during login when I get to https://test.pypi.org/account/two-factor/ my YubiKey doesn't blink (I would expect it to). If I click "Authenticate with key" I get redirected to https://test.pypi.org/account/login/ with the error message "Invalid or expired two factor login." I'm running Chrome 75.0.3770.100 on Mac OS 10.14.5, and I use WebAuthn on this computer for work.

Heads-up @woodruffw.

**Comment by brainwane** [comment]
@steiza - question for you from @woodruffw ([from IRC](http://kafka.dcpython.org/day/pypa-dev/2019-06-26)):

> some quick triage: do you have any extensions that delete query parameters from GET requests, or did you leave that form open for > 5 minutes before attempting to use WebAuthn?
> that error is actually unrelated to WebAuthn; it's caused by the token we send during login timing out before the form is submitted
> (or otherwise failing to validate, but timing out is the most likely explanation)

**Comment by ewdurbin** [comment]
This should be resolved, there was a misconfiguration on test.pypi.org that was not present on pypi.org.

Can you attempt to reproduce and update us if it is still not working?

**Comment by steiza** [comment]
That configuration is now working, thanks!

**Comment by brainwane** [comment]
Great! Closing. Thanks @steiza!
