### ISSUE TITLE
Placeholder github stars and forks are misleading

### ISSUE THREAD

**Issue by maciej-gol** [pypa/warehouse#6111]
**Describe the bug**
For PyPI packages that ship with no github url, the warehouse webpage shows misleading github statistics:

![Screenshot from 2019-06-27 10-21-32](https://user-images.githubusercontent.com/1861709/60249545-5c896c00-98c5-11e9-9247-6a887c4cc64d.png)

Link to package: https://pypi.org/project/op-askpass/

**Expected behavior**
Github stats would be zero or not shown at all.

**To Reproduce**
https://pypi.org/project/op-askpass/

**My Platform**
Ubuntu

**Additional context**
Shipped an initial version of my package to make sure the name is reserved.

**Comment by maciej-gol** [comment]
Nvm, an oversight.

**Comment by pradyunsg** [comment]
For future :eyes: that might look at this and get confused, the GitHub stats were fetched for https://github.com/pypa/sampleproject, since that was a URL provided in the metadata. :)
