### ISSUE TITLE
Increasing package size limit for pyflink

### ISSUE THREAD

**Issue by WeiZhong94** [pypa/warehouse#6116]
Hi, I would like to request you to increase the size limit of the package "pyflink" to 300MB, because in the next release, pyflink will package the Flink jar files and the size will be increased to 286MB. Please help me increase the upload limit, thank you. There is a developmental release in test pypi for the moment, but it is incomplete. Its actual size is 286MB.

**A link to your project on PyPI (or Test PyPI):**
https://test.pypi.org/project/pyflink/
https://pypi.org/project/pyflink/

**The size of your release, in megabytes:**
286MB

**Which index/indexes you need the increase for (PyPI, Test PyPI, or both)**
both

**A brief description of your project, including the reason for the additional size.**
pyflink allows you to write Flink programs in Python. The additional size comes from the flink jar files.

**Comment by WeiZhong94** [comment]
@nlhkabu @jamadden Could you have a look at this request? Thanks a lot.

**Comment by jamadden** [comment]
The limit for pyflink has been set to 300MB on both pypi.org and test.pypi.org. Given that this size is at the upper end of package sizes, please be mindful of how often you make releases.

**Comment by sunjincheng121** [comment]
Hi @jamadden we do not using https://test.pypi.org/project/pyflink/ as the apache flink project now. feel free to reset the default limit of package size.
currently we using the https://test.pypi.org/project/apac-flink/ which mentioned in #6139 

Best,Jincheng

**Comment by WeiZhong94** [comment]
Thanks @jamadden, as @sunjincheng121 said apache flink do not using https://test.pypi.org/project/pyflink/ as the apache flink project now. Sorry to bother you.
