### ISSUE TITLE
Apply for larger wheel size limit

### ISSUE THREAD

**Issue by byteps** [pypa/warehouse#6124]
## A link to your project on PyPI (or Test PyPI)
https://test.pypi.org/project/byteps/

## The size of your release, in megabytes
64MB

## Which index/indexes you need the increase for (PyPI, Test PyPI, or both)
Test PyPI

## A brief description of your project, including the reason for the additional size.
We are a develop team for BytePS (https://github.com/bytedance/byteps) and would like to provide some wheel files for users, so that they will not get trouble with system environment issues (e.g., gcc not compatible, etc). But currently our package is larger than 60MB, so we cannot provide a link for users to pip install. We would appreciate it if you can do us a favor :)

Thank you in advance.

**Comment by jamadden** [comment]
Can you please explain why you need to distribute such large wheels? That is, why do the wheels need to be so large?

**Comment by byteps** [comment]
@jamadden Thank you for the response. Our wheels contain a third party library (ps-lite, which further calls ZeroMQ as its communication library), and call NCCL and CUDA for multiple GPUs communication. Indeed, the compiled fat bin is large (mostly nvidia-related binary). But we find it hard to narrow the size down because those fat bin is used to optimize the performance, and we do not want to lose the performance...

**Comment by byteps** [comment]
We finally cut the size down within the limit. Closing this issue now. Thank you.
