### ISSUE TITLE
increase size limit for file upload and release all the caches previously upload 

### ISSUE THREAD

**Issue by HangJie720** [pypa/warehouse#6127]
Excuse me again, I have 2 questions?
(1) I have delete my project and corresponding file, but when I use pip to install tflex or tensorflow-tflex, system still Using cached https://pypi.doubanio.com/packages/7b/1a/53c197643f62cebe06efb526ac6502caa65a2edc9c3f158ee048403da4dc/tflex-0.0.3-py2.py3-none-any.whl, which have been deleted. Although I upload new version, still install old version. Could you help me release all the cache? Thank you very much ! ! !
(2) The second problem is: I have a tensorflow-tflex program，tensorflow_tflex-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl, its size is 70M，when i upload directly，Limit for project 'tensorflow-tflex' is 60 MB. Could you help me increase the upload size for my account directly?

Because, in yesterday, I create an empty packages with tensorflow_tflex-0.0.3-py2.py3-none-any.whl and upload, then, you help me upload the size to 100M. Then, I upload tensorflow_tflex-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl, when I pip install tensorflow-tflex，tensorflow_tflex-0.0.3-py2.py3-none-any.whl are still installed instead of tensorflow_tflex-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl, why?

In general, I hope I can upload tensorflow_tflex-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl directly without create empty project, which size is 70M, while my account upload size are limited.
(3) if not, I have recreated the tensorflow-tflex project, could you help me resize this upload size again. The previous package has been deleted.
https://pypi.org/project/tensorflow-tflex/

**Comment by HangJie720** [comment]
could you help me release all the cache previously upload, my two projects is tflex, tensorflow-tflex, website is shown as follows:
tflex: https://pypi.org/project/tflex/
tensorflow-tflex: https://pypi.org/project/tensorflow-tflex/
and increase the upload size of tensorflow-tflex package. this package I have deleted and recreated.

**Comment by jamadden** [comment]
(1) The limit for `tensorflow-tflex` has again been set to 100MB on pypi.org. Deleting the project only makes more work for everyone, I would suggest not deleting it again.
(2) The URL you provided (https://pypi.doubanio.com/packages/...) is *not* a URL from PyPI, AFAICS. Perhaps you are using a third-party mirror. At this time, the canonical pypi.org has no distributions for `tensorflow-tflex`:
```console
$ pip download --verbose tensorflow-tflex
DEPRECATION: A future version of pip will drop support for Python 2.7.
Created temporary directory: /private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-req-tracker-Z2xT3r
Created requirements tracker '/private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-req-tracker-Z2xT3r'
Created temporary directory: /private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-download-38Qo4u
Collecting tensorflow-tflex
  1 location(s) to search for versions of tensorflow-tflex:
  * https://pypi.org/simple/tensorflow-tflex/
  Getting page https://pypi.org/simple/tensorflow-tflex/
  Looking up "https://pypi.org/simple/tensorflow-tflex/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/tensorflow-tflex/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/tensorflow-tflex/
  Could not find a version that satisfies the requirement tensorflow-tflex (from versions: )
Removed build tracker '/private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-req-tracker-Z2xT3r'
No matching distribution found for tensorflow-tflex
```

Neither does that mirror. Perhaps the mirror has caught up:
```console
$ http http://pypi.doubanio.com/simple/tensorflow-tflex/
HTTP/1.1 404 Not Found
Ali-Swift-Global-Savetime: 1561978858
Connection: keep-alive
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Mon, 01 Jul 2019 11:00:58 GMT
EagleId: 2ff6119c15619788574114859e
Server: Tengine
Timing-Allow-Origin: *
Via: cache20.l2ot7-1[529,404-1280,M], cache3.l2ot7-1[530,0], cache3.us16[781,404-1280,M], cache8.us16[782,0]
X-Cache: MISS TCP_MISS dirn:-2:-2
X-Content-Type-Options: nosniff
X-DAE-App: mfsclient
X-DAE-Node: brand26
X-DOUBAN-NEWBID: YZUwUEWqqGE
X-Swift-CacheTime: 1
X-Swift-Error: orig response 4XX error
X-Swift-Error: orig response 4XX error
X-Swift-SaveTime: Mon, 01 Jul 2019 11:00:58 GMT

404 page not found
```

Compare with tflex and notice the `files.pythonhosted.org` URLs:
```console
$ pip download --verbose tflex
Created temporary directory: /private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-req-tracker-2n35i2gd
Created requirements tracker '/private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-req-tracker-2n35i2gd'
Created temporary directory: /private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-download-i72u5s79
Collecting tflex
  1 location(s) to search for versions of tflex:
  * https://pypi.org/simple/tflex/
  Getting page https://pypi.org/simple/tflex/
  Looking up "https://pypi.org/simple/tflex/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/tflex/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/tflex/
    Found link https://files.pythonhosted.org/packages/15/74/96f7464671f1f931fc1d7f25a2aa8788c08511cc0942e1b72c1ec0d4e64f/tflex-1.0.0-py3-none-any.whl#sha256=e461f74bb2845bdee0cfe00124dd9328e8d99d16481799ad8c75655c5b261feb (from https://pypi.org/simple/tflex/), version: 1.0.0
  Using version 1.0.0 (newest of versions: 1.0.0)
  Created temporary directory: /private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/pip-unpack-24u05o02
  Looking up "https://files.pythonhosted.org/packages/15/74/96f7464671f1f931fc1d7f25a2aa8788c08511cc0942e1b72c1ec0d4e64f/tflex-1.0.0-py3-none-any.whl" in the cache
  No cache entry available
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/15/74/96f7464671f1f931fc1d7f25a2aa8788c08511cc0942e1b72c1ec0d4e64f/tflex-1.0.0-py3-none-any.whl HTTP/1.1" 200 45058
  Downloading https://files.pythonhosted.org/packages/15/74/96f7464671f1f931fc1d7f25a2aa8788c08511cc0942e1b72c1ec0d4e64f/tflex-1.0.0-py3-none-any.whl (45kB)
  Downloading from URL https://files.pythonhosted.org/packages/15/74/96f7464671f1f931fc1d7f25a2aa8788c08511cc0942e1b72c1ec0d4e64f/tflex-1.0.0-py3-none-any.whl#sha256=e461f74bb2845bdee0cfe00124dd9328e8d99d16481799ad8c75655c5b261feb (from https://pypi.org/simple/tflex/)
...
```

**Comment by HangJie720** [comment]
Thank you very much for your help!@jamadden
