### ISSUE TITLE
500 Error Uploading Library

### ISSUE THREAD

**Issue by jaitaiwan** [pypa/warehouse#6132]
**Describe the bug**
Attempting to upload any distribution of my project results in a 500 error with no detailed information as to why.

**Expected behavior**
The package is successfully uploaded

**To Reproduce**
Upload a package, checking to make sure that `twine check dist/*` has been run first to detect any issues.

**My Platform**
Python 3.7 uploading from a debian server from Sydney, Australia.

**Additional context**
Made sure to run readme checks, tried to upload individual packages (.tar.gz and a wheel) and still nothing.

**Comment by di** [comment]
Sorry, we had a brief outage. Can you try again? Should be resolved now.

**Comment by jaitaiwan** [comment]
That was it, thanks.
