### ISSUE TITLE
Pypi package size limit for Analytics Zoo

### ISSUE THREAD

**Issue by qiuxin2012** [pypa/warehouse#6140]
Perviously, we increase the limit to 120MB by #5359, but after a few months' development, the size increased to 174MB. So if it is possible to increase the limit of https://pypi.org/project/analytics-zoo/ to 200MB?

Analytics Zoo (https://github.com/intel-analytics/analytics-zoo) is a unified analytics + AI platform for distributed TensorFlow, Keras and BigDL on Apache Spark; and the reason for the large size (esp. for the upcoming releases) is that it will include more .so files for hardware accelerations, model optimizations, etc.

**Comment by jamadden** [comment]
The limit has been set to 200MB on pypi.org.
