### ISSUE TITLE
Increase file size limit for BactinspectorMax project

### ISSUE THREAD

**Issue by aunderwo** [pypa/warehouse#6148]
Please can you increase the file size limit for the [BactInspectorMax](https://pypi.org/project/BactInspectorMax/) project.

This includes a [Mash](https://mash.readthedocs.io/en/latest/) index of bacterial reference genomes. 

The repo size is 70Mb

```
ls -ltrh dist                                                                                                                         
  rw-r--r--  au3  1704    69 MiB  Thu Jul  4 08:52:56 2019    BactInspectorMax-0.0.2-py3-none-any.whl 
  rw-r--r--  au3  1704    69 MiB  Thu Jul  4 08:53:01 2019    BactInspectorMax-0.0.2.tar.gz
```

Thanks

**Comment by jamadden** [comment]
The upload limit for BactInspectorMax has been set to 100MB on pypi.org
