### ISSUE TITLE
Request to increase size limit of PyQtWebEngine

### ISSUE THREAD

**Issue by philthompson10** [pypa/warehouse#6151]
The new release of https://pypi.org/project/PyQtWebEngine/ is just over the 60M limit so I would like this to be increased to at least 70M on PyPI.

This project was created by splitting https://pypi.org/project/PyQt5/ in two. I believe that the limit of this project is about 120M (from the time before the split) and it can be reduced to the standard 60M.

Thanks.

**Comment by jamadden** [comment]
The limit for PyQtWebEngine has been set to 100MB on pypi.org.

The limit for PyQt5 is indeed 120MB; I've gone ahead and left that in place just in case.
