### ISSUE TITLE
Improve 2fa help text

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6170]
Based on feedback from user testing:

### Add help information for provisioning

The current help text explains how to _login_ with 2fa.  Instead, the help text should cover how to provision *and* login with 2fa.  However, the term "provisioning" should be avoided - use "set up" instead.

### Explain 2fa better, e.g.

> Two factor authentication makes your account more secure by requiring two things in order to login: something you know and something you have. In PyPI's case, "something you know" is your username and password, while "something you have" is either an application to generate temporary codes (see [generating a code through a TOTP application], or a physical hardware key (see [using a U2F security key.]).

### Mention that some password managers can generate TOTP codes

> Some password managers (e.g. 1password) can also handle generating TOTP codes

### Change link to webauthn spec (in help text), to point to browser support table

- Current link: https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential
- New link: https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential#Browser_compatibility

### Explain how TOTP works

e.g. https://fastmail.blog/2016/07/22/how-totp-authenticator-apps-work/

### Avoid /remove jargon

- "TOTP application" would be better as "Authentication application"
- "Webauthn" is not commonly understood.  Instead, refer to webauthn as "USB security key"

**Comment by alexwlchan** [comment]
Tiny nit: the name “1Password” uses a capital “P”.
