### ISSUE TITLE
2FA: User testing summary

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6173]
A summary of recent user testing sessions covering two factor authentication.  Thank you to the 5 participants for your time!

Issues #6172 #6171 and #6170 have been opened to address this feedback:

## User 1 (26/6/19)

- User 1 uses [1password](https://1password.com/) to manage their passwords and generate TOTP codes.
- User 1 had no problem removing their existing TOTP setup and setting it up again
- User 1 was not using a webauthn compatible browser, and did not understand what `webauthn` is - although they assumed it had something to do with security keys, as the button above was disabled
- We explored the help text together, which User 1 understood - however we did discuss some possible improvements (see #6170)
- We switched browsers to try to set up webauthn
- User 1 didn't understand that they needed to name the key before clicking on 'provision key'.  They thought they had to insert the key and press the button - as they were mislead by the help text above.
- User 1's key didn't work (probably because it's old and not compatible) - I had to explain why.  PyPI didn't offer any explanation as to why it might not be working.

## User 2 (28/6/19)

- User 2 had already set up 2FA via TOTP on their PyPI account
- User 2 uses LastPass Authenticator on their mobile phone for generating TOTP codes
- User 2 didn't know what TOTP stood for, but understood that this was "the thing" that generates authentication codes
- User 2 had no issues disabling and re-enabing TOTP on their account
- User 2 had no issues provisioning a security key (Youbikey) on their account
- I asked User 2 to read through the help text provided, they suggested that we could improve it by better explaining how 2FA makes your account secure.

## User 3 (02/07/19)

- User 3 had no issues enabling and disabling TOTP, using Duo mobile
- They wondered about recovery codes - where were they?  They expected to be shown them in the UI, or sent them by email (see #5800)
- They didn't understand what a 'security key' is, but when they saw 'Yubikey' in the help text they understood
- When they tried to setup webauthn, they didn't understand that they needed to plug in a key.  This is because FF doesn't instruct users to plug in the key.
- They think it might be useful to do account recovery via PGP.

## User 4 (04/07/19)

- User 4 didn't understand what TOTP is and when instructed to use their "application of choice" to scan the QR code, they opened a QR scanner on their phone
- User 4 didn't find the help text very helpful, as it only described the *log in* process, rather than the provisioning process
- User 4 used the terminology "Authentication application" to describe Google Authentication, etc.  "TOTP application" didn't mean anything to them
- After disabling 2fa, they were not sure if their phone application would be synced, or if they needed to also remove the PyPI entry on their app
- User 4 didn't understand what a "security key" was.  They thought it might be another type of password, not a phyiscal device.  They only understood after the browser popover with the image appeared. They described it as a "dongle".
- User 4 noted that there was no link to help from the webauthn provisioning page

## User 5 (08/07/19)

- User 5 had no problem setting up TOTP (using Authy)
- "Webauthn" didn't mean anything to them. They didn't understand that "security key" meant a physical device.
- They would like to see examples of apps/brands mentioned in the text "e.g. 'authy'", "e.g. 'Yubikey" to better understand what they need to do
- They found that the 'learn more' link on the 2fa provisioning page was broken.

**Comment by brainwane** [comment]
@nlhkabu now that we've merged fixes to the three specific issues opened as a result of the testing, would it be okay to close this issue?
