### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by bhojrampawar** [pypa/warehouse#6175]
Emergency: I have activated two factor authentication for my PyPI account. but i removed PyPI Authentication account from my phone, And now i am unable to get authentication code please help me to log in to my PyPI account.

**Comment by ewdurbin** [comment]
hello @bhojrampawar, what is your PyPI username?

**Comment by bhojrampawar** [comment]
My pypi username is "bhojrampawar"

**Comment by ewdurbin** [comment]
Thanks. I've emailed you to assist with regaining access to your account.

**Comment by ewdurbin** [comment]
Completed.

**Comment by bhojrampawar** [comment]
Sir, i did not received any assists regarding my PyPI account to recover it.

**Comment by ewdurbin** [comment]
@bhojrampawar are you stating that the correspondence with the gmail address on file for this account was fraudulent?

**Comment by bhojrampawar** [comment]
Sir, how to recover my account.

**Comment by ewdurbin** [comment]
@bhojrampawar at this point it is unclear. can you email ernest@python.org?

**Comment by bhojrampawar** [comment]
Sir, I have activated two factor authentication for my PyPI account, but by
the reason PyPI two factor auth account removed from authorization app in
my phone, And now i am unable to get two factor auth code,

and without auth code i can not log to PyPI account.

Please help.

**Comment by ewdurbin** [comment]
Please email ernest@python.org from the gmail account associated with your PyPI user.

**Comment by bhojrampawar** [comment]
5-K-8aV83-ULPrf1kiO4o85csoJIXWmnXAqQlMH3-AI

**Comment by ewdurbin** [comment]
Thanks for confirming. I've disabled TOTP on your account and issued a password reset.

**Comment by bhojrampawar** [comment]
Thank you @Ernest W. Durbin III For your amazing support,

You helped me to recover my PyPI account.
Print("Thanking you"*1000)
