### ISSUE TITLE
2FA: Enrolling a TouchID sensor as a webauthn security key fails (Chrome, Mac)

### ISSUE THREAD

**Issue by jacobian** [pypa/warehouse#6183]
**Describe the bug**
I'm trying to enroll a TouchID sensor as a webauthn device. PyPI and Chrome do let me select the sensor, and I do get prompted for a touch, but then PyPI throws an error: "Registration rejected. Error: Self attestation is not permitted.."

**Expected behavior**
I expect to be able to enroll a TouchID sensor. 

**To Reproduce**
- PyPI --> Account Settings
- Click "Add 2FA With Security Key"
- Type a key name, click "Provision Key"
- Chrome prompts to choose between a USB security key and a built-in sensor. Choose "Built-in sensor"
- MacOS prompts to hit the TouchID sensor. Do so.
- Chrome prompts, "Allow this site to see your security key?" Click "Allow"
- PyPI displays an error: "Registration rejected. Error: Self attestation is not permitted.."

**My Platform**
- MacOS 10.14.5
- MacBook Air (2018 edition, with TouchID)
- Chrome "75.0.3770.100 (Official Build) (64-bit)"

**Comment by di** [comment]
I can reproduce this with the same macOS/Chrome versions.

**Comment by woodruffw** [comment]
Thanks! I'll take a look today.

**Comment by jacobian** [comment]
Yay, thank you!
