### ISSUE TITLE
PEP541: transfer ownership of 'fiddler' package to someone at Fiddler Labs

### ISSUE THREAD

**Issue by dfrankow** [pypa/warehouse#6196]
**What's the problem this feature will solve?**
The "fiddler" package was uploaded in 2017. It has no documentation, source code repository, or contacts. It doesn't appear to install, and looking inside its tarball doesn't give me much sense for what it's about.

[Fiddler Labs](https://fiddler.ai/) is starting to develop and release libraries (such as [fiddler-client](https://pypi.org/project/fiddler-client/)), and we're concerned the broken and inscrutable "fiddler" package will confuse our users.

**Describe the solution you'd like**
Transfer ownership of the "fiddler" library to someone working at Fiddler Labs. Feel free to reach out to me, or contact info@fiddler.ai.

Alternatively, at least help us send a message to the maintainer ([rushib1](https://pypi.org/user/rushib1/)) to talk about the situation.

**Additional context**

**Comment by jamadden** [comment]
It seems possible that https://github.com/aaronchn/pyfiddler is the corresponding github repository. Perhaps @aaronchn is the PyPI owner and can comment here, or knows how to reach the owner?

**Comment by jamadden** [comment]
I've also tried to contact the owner by email; however, the email address isn't verified.

**Comment by dfrankow** [comment]
Good one, thanks!

Yes, pyfiddler is a good candidate for the repo. They both have files pyfiddler.py and certificate.py, and pyfiddler.py has these idiosyncratic lines in both places (github repo and pypi package):

```
clr.FindAssembly("FiddlerCore4")
clr.AddReference("FiddlerCore4")
```

It looks perhaps the PyPi package was uploaded later. It has more files (e.g., some dlls), and they have timestamps in June, while the github repo was all May.

**Comment by rushib1** [comment]
I am the owner of that package. I have no problem to the above request and can continue with it.

**Comment by jamadden** [comment]
@rushib1 if @dfrankow provides you with a PyPI username, can you login to pypi.org and add that username as an owner of the fiddler project?

**Comment by dfrankow** [comment]
Please add [raghu_fiddler](https://pypi.org/user/raghu_fiddler/), the owner of the [fiddler-client](https://pypi.org/project/fiddler-client/) package.

**Comment by rushib1** [comment]
@jamadden @dfrankow done.

**Comment by rangadi** [comment]
Thanks everyone! I am now the owner of 'fiddler' package. Will push a release there soon.

**Comment by dfrankow** [comment]
Thanks @rushib1 !
