### ISSUE TITLE
<a> tags have underlines for images, which shouldn't have them

### ISSUE THREAD

**Issue by nedbat** [pypa/warehouse#6198]
**Describe the bug**

I have an image with a link.  This results in an <a> tag around an <img> tag.  The <a> tag has a clever background-image css rule that gives it an underline appearance.  But my image is a PNG with a transparent background, so the underline shows through, and looks like it is crossing out the image:

https://test.pypi.org/project/coverage/5.0a6/

<img width="397" alt="image" src="https://user-images.githubusercontent.com/23789/61284840-ce025f00-a78d-11e9-8c11-b06147868ea7.png">

**Expected behavior**

I would like to be able to link transparent images without lines appearing. 

**To Reproduce**

The Tidelift logo is affected here: https://test.pypi.org/project/coverage/5.0a6/ (Note: I may fix this in the short term by changing that image to not be transparent.)

**My Platform**

**Additional context**

**Comment by jamadden** [comment]
I think this is a cup of #6158 which was just fixed in https://github.com/pypa/warehouse/pull/6165

**Comment by nedbat** [comment]
It is indeed. Thanks for the quick response!
