### ISSUE TITLE
Increase size limit request

### ISSUE THREAD

**Issue by randomboolean** [pypa/warehouse#6199]
- A link to your project on PyPI (or Test PyPI)
https://pypi.org/project/warp10-jupyter/

- The size of your release, in megabytes
85M

- Which index/indexes you need the increase for (PyPI, Test PyPI, or both)
both

- A brief description of your project, including the reason for the additional size.
Contains a Jupyter notebook cell magic `%%warpscript` that allows to execute warpscript code in a JVM from python (and interacts with its objects).
Prior releases required to connect to a py4j gateway that embed the needed jar. However it can be painful to launch the gateway outside of python for non java users or new warpscript users.
The next release includes the needed jar which is the reason for the additional size.

**Comment by jamadden** [comment]
The upload limit has been set to 100MB on pypi.org.

It seems this project does not exist on test.pypi.org. If you want to test it there, you'll need to create the project first, and after that the admins can change the upload limit. Please open a new ticket if you do that.
