### ISSUE TITLE
Ask CI providers, PyPUG to update their documentation, tell users to use API keys

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6211]
I found two specific pieces of documentation from CI providers that should be updated with the release of API keys:

It would be nice to reach out to these providers to let them know to update their docs :)

https://docs.travis-ci.com/user/deployment/pypi/
https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/

**Comment by nlhkabu** [comment]
We'll also need to open a ticket on the PyPUG to update this: https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=pypirc#create-an-account

**Comment by webknjaz** [comment]
FTR here's where you can create a PR for Travis CI docs: https://github.com/travis-ci/docs-travis-ci-com/blob/master/user/deployment/pypi.md

**Comment by webknjaz** [comment]
Created https://github.com/pypa/packaging.python.org/issues/628

**Comment by brainwane** [comment]
Thanks for the research, @nlh and @webknjaz! I can't get to this till Monday; Sviatoslav, would you like to go ahead and create a PR about this for Travis CI docs? If you can't, that's fine. :)

**Comment by webknjaz** [comment]
Sorry, I'd love to, but have zero capacity atm :(

**Comment by brainwane** [comment]
Asked Travis CI (issue linked above) and Circle CI ([on Discourse](https://discuss.circleci.com/t/adding-pypi-api-key-instructions-for-package-uploads/31598)) whether they want to add the feature to their docs yet, given that it's in beta.

**Comment by brainwane** [comment]
Fixing #6287 and deciding on good advice for #6338 is necessary in order to write docs.

**Comment by brainwane** [comment]
Contractors on the OTF-funded work need to stop work on the security features in order to ensure we complete the accessibility and internationalization work by the end of the month. Therefore, while this is necessary to get us out of beta for this feature https://github.com/pypa/warehouse/issues/5661#issuecomment-515802931 , I'm removing it from the milestone.

**Comment by brainwane** [comment]
[Travis doc](https://docs.travis-ci.com/user/deployment/pypi/) is updated; CircleCI and PyPUG still need updating.

**Comment by brainwane** [comment]
I'm giving up on CircleCI; I [asked them months ago](https://discuss.circleci.com/t/adding-pypi-api-key-instructions-for-package-uploads/31598) and got no response.

So we're just waiting for a PyPUG PR. I'll make one now.

**Comment by brainwane** [comment]
Thank you all! I'm calling this done. :-)
