### ISSUE TITLE
Disabled "Manage" button is missing tooltip

### ISSUE THREAD

**Issue by jheld** [pypa/warehouse#6217]
**Describe the bug**

I have been granted a maintainer role on a project. I am listed as a maintainer, but on my project list I cannot click the button for editing the project. Just viewing.

**Expected behavior**

I should be able to edit/maintain the project.
**To Reproduce**

Unsure how reproducible this is for other users.
**My Platform**

Firefox on multiple platforms. Have not tried other browsers.
**Additional context**

**Comment by di** [comment]
What's the name of the project? What's your username?

**Comment by jheld** [comment]
django easy audit.

snoopy1497

**Comment by di** [comment]
There are two possible roles for collaborators:

**Maintainer:**: Can upload releases for a package. Cannot add collaborators. Cannot delete files, releases, or the project.

**Owner**: Can upload releases. Can add other collaborators. Can delete files, releases, or the entire project.

If you need to edit the project, an owner needs to give you the "Owner" role instead.

There is supposed to be a tooltip on the disabled "Manage" button, but it seems like it's not working. I've retitled this issue accordingly.

**Comment by jheld** [comment]
Makes sense. Thank you! I was going to try uploading a release, but wasn't
sure if there was a UI bug or not.
