### ISSUE TITLE
List dependencies for each release

### ISSUE THREAD

**Issue by David-OConnor** [pypa/warehouse#6226]
**What's the problem this feature will solve?**
This is more of a question than a feature, but could be a feature if the question has no solution. Would allow easy access to dependency graphs, without having to download a package.

**Describe the solution you'd like**
Under each release, a list of dependencies (1 level deep is enough) should be one of the items displayed. Ie in `>=` or `^/~` format. I believe this can be found in the dist-info METADATA files.

**Comment by ewdurbin** [comment]
@di wrote this succinct summary of why this isn't currently feasible at https://dustingram.com/articles/2018/03/05/why-pypi-doesnt-know-dependencies/.

I'll leave this open for further discussion for now, but I believe it can be closed if no one objects.

**Comment by David-OConnor** [comment]
I'm going to implement this as a auto-caching standalone API

**Comment by David-OConnor** [comment]
[Early release](https://pydeps.herokuapp.com/matplotlib/3.1.1/)

**Comment by pradyunsg** [comment]
Releases where wheels are uploaded first do contain the dependency information, in the JSON API.

**Comment by David-OConnor** [comment]
Could you please post an example?

**Comment by di** [comment]
Quoting for those who might be reading via email and missing your edits:

> What would it take for future releases to ensure explicit dependency reqs? We can't undo previous mistakes, but can stop making them. Release as wheel with dist-info? Post pyproject.toml to pypi?

As the article that @ewdurbin shared says, this wouldn't be possible unless we stopped allowing source distributions configured via `setup.py`. The ecosystem is definitely moving away from `setup.py`, but it will be a long time coming.

> Could you please post an example?

```
$ curl -s https://pypi.org/pypi/requests/json | jq ".info.requires_dist"
[
  "chardet (<3.1.0,>=3.0.2)",
  "idna (<2.9,>=2.5)",
  "urllib3 (!=1.25.0,!=1.25.1,<1.26,>=1.21.1)",
  "certifi (>=2017.4.17)",
  "pyOpenSSL (>=0.14) ; extra == 'security'",
  "cryptography (>=1.3.4) ; extra == 'security'",
  "idna (>=2.0.0) ; extra == 'security'",
  "PySocks (!=1.5.7,>=1.5.6) ; extra == 'socks'",
  "win-inet-pton ; (sys_platform == \"win32\" and python_version == \"2.7\") and extra == 'socks'"
]
```

**Comment by David-OConnor** [comment]
What version of Requests is that list for? As far as I understand, you can build a dep graph from that, since it's not tied to a version. Would need that under `releases` - not just `info`.

**Comment by di** [comment]
It's for the latest version, but you can get it for any version:

```
$ curl -s https://pypi.org/pypi/requests/2.22.0/json | jq ".info.requires_dist"
[
  "chardet (<3.1.0,>=3.0.2)",
  "idna (<2.9,>=2.5)",
  "urllib3 (!=1.25.0,!=1.25.1,<1.26,>=1.21.1)",
  "certifi (>=2017.4.17)",
  "pyOpenSSL (>=0.14) ; extra == 'security'",
  "cryptography (>=1.3.4) ; extra == 'security'",
  "idna (>=2.0.0) ; extra == 'security'",
  "PySocks (!=1.5.7,>=1.5.6) ; extra == 'socks'",
  "win-inet-pton ; (sys_platform == \"win32\" and python_version == \"2.7\") and extra == 'socks'"
]
```
```
$ curl -s https://pypi.org/pypi/requests/2.8.0/json | jq ".info.requires_dist"
[
  "ndg-httpsclient; extra == 'security'",
  "pyOpenSSL; extra == 'security'",
  "pyasn1; extra == 'security'"
]
```

The API is documented here: https://warehouse.readthedocs.io/api-reference/json/

**Comment by David-OConnor** [comment]
This is exactly what I'm looking for. Thank you.

**Comment by pradyunsg** [comment]
Awesome! I'll go ahead and close this as resolved.
