### ISSUE TITLE
Dataset in my language

### ISSUE THREAD

**Issue by trbn** [pypa/warehouse#6235]
Hi
**What's the problem this feature will solve?**
Link prediction in persian

**Describe the solution you'd like**
I have entire dataset and I want to replace Freebase with it. Then train all models. 

**Additional context**
Could you help me and lead me to do it?
I look forward to hearing from you.
Best regards,
Najmeh

**Comment by yeraydiazdiaz** [comment]
Hi @trbn,

Sorry but it is unclear to me what you mean with "Link prediction in persian". Are using a specific package that provides this dataset?

If so you may want to contact the authors of the package directly as this repo is for issues regarding PyPI itself.

Hope this helps.

**Comment by trbn** [comment]
Thanks for the response. So I will ask the question from the authors.
