### ISSUE TITLE
New dataset

### ISSUE THREAD

**Issue by trbn** [pypa/warehouse#6237]
Dear authors,

Thanks for the pypa. 
I want to run embedding models on my dataset. What should I do?
Many thanks in advance.

Best Regards

**Comment by yeraydiazdiaz** [comment]
Hello again @trbn. Sorry if I was not clear. This repository is for issues with the https://pypi.org/ website.

You may want to try using Google your problem or ask in a forum as we cannot help you here.

Best of luck.
