### ISSUE TITLE
2FA: unverified-email users get banner linking to nonexistent anchor

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#6239]
When I create a new account which -- immediately after creation -- has an unverified email address, I see the "Two factor authentication is available, enable it now for your account." banner linking to `manage/account/#two-factor` but that anchor tag does not actually point anywhere on the page, and the `/manage/account` page doesn't say anything about 2FA (e.g. in the "Account emails" section).

The 2FA banner does appear under the "Warning: Your primary email address ([address]) is unverified. Verify your email or add a new address." banner.

I can see a few options, the top ones of which are:

1. Status quo. People will figure out what they need to.
2. Change the banner (for all users): instead of linking to `/manage/account`, link to `/help/#2fa`.
3. For unverified users, show a different 2FA banner.

I am in favor of option 2 because it's the most resilient to future changes IMO.

**Comment by di** [comment]
IMO we should not show the banner at all if the user cannot actually enable 2FA (due to not having a verified email address), and let the banner appear once the email address is verified.

**Comment by brainwane** [comment]
We discussed this in [the most recent planning meeting](https://wiki.python.org/psf/PackagingWG/2019-08-02-Warehouse) and we agree with @di - users with zero verified email addresses should not see the 2FA banner at all.
