### ISSUE TITLE
Size increase for PyPI project minerl

### ISSUE THREAD

**Issue by MadcowD** [pypa/warehouse#6241]
Our project `minerl` is a reinforcement learning simulator which allows its users to train AI agent in Minecraft. We package several jars along with `minerl` which the python library communicates with to start the simulator, but we need a size increase to enable our next release. **The size target is 100 MB**.

PyPi: https://pepy.tech/project/minerl
Index: PyPi
You can read more here: http://minerl.io
Here is our github repo: https://github.com/minerllabs/minerl

**Comment by MadcowD** [comment]
Thanks @jamadden :)

**Comment by MadcowD** [comment]
Bump!

**Comment by jamadden** [comment]
The upload limit for minerl has been set to 100MB on pypi.org.
