### ISSUE TITLE
Always display API token management panel

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#6256]
Noticed after deploy of #6084, that the API token management panel is not at all visible if any single email address is not verified.

I suggest that we should:
  - Always display the panel, but grey out or disable it
  - Allow for management of API Tokens when at least one verified primary email is present.

**Comment by brainwane** [comment]
I agree that we should allow for API token management if there's _at least one_ verified primary email address. @woodruffw please look into this, and also please check whether this problem also affects our 2FA methods as a whole.

I'll defer to @nlhkabu on the accessibility and UX implications of the greyed out/disabled view.

**Comment by nlhkabu** [comment]
@ewdurbin I am not able to reproduce this in dev:

User with one verified email:

![Screenshot from 2019-07-26 07-16-42](https://user-images.githubusercontent.com/3323703/61930370-6b6f4700-af75-11e9-933d-3b52f7bd9742.png)

Can see and set up API tokens (and 2fa):

![Screenshot from 2019-07-26 07-17-32](https://user-images.githubusercontent.com/3323703/61930399-7d50ea00-af75-11e9-8444-1417d3b23f41.png)

**Comment by nlhkabu** [comment]
Opened #6269 to address comment:

> Always display the panel, but grey out or disable it

**Comment by brainwane** [comment]
I also can't reproduce the issue where a single unverified email address stops the user from being able to create an API token. @ewdurbin can you still reproduce this on production?

**Comment by brainwane** [comment]
I'm going to call this addressed. Thanks!
