### ISSUE TITLE
Add API Token form confusion

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#6257]
noticed that the form elements for adding an API Token still display after creating a token

<img width="1145" alt="Screen Shot 2019-07-25 at 11 04 22 AM" src="https://user-images.githubusercontent.com/1200832/61885640-293dfb00-aecc-11e9-8ed9-42af3285862f.png">

This is a bit confusing, and I'm not sure if intentional

**Comment by Carreau** [comment]
+1 for this, Plus in scope; I woudl add which permissions are granted with this token (I believe there was a discussion about having upload-only permission, so at least say that it has all permissions for given project if true).

**Comment by brainwane** [comment]
I personally think this is fine, but I can see how it is potentially confusing. @nlhkabu I'll defer to you here!

**Comment by ewdurbin** [comment]
> I believe there was a discussion about having upload-only permission, so at least say that it has all permissions for given project if true

Tokens are only able to upload, I may not have been clear in some of the beta announcements. Seems like a great idea to explicitly state what they can do (upload releases).

**Comment by brainwane** [comment]
Noting here that per [our meeting a few days ago](https://wiki.python.org/psf/PackagingWG/2019-08-02-Warehouse) @nlhkabu will consider including assessing showing token creation UI on confirmation page in her user tests.

**Comment by nlhkabu** [comment]
First user test didn't have any issues or confusion here.  Perhaps offset by the title "Add another token". I'll continue to observe in further tests.
