### ISSUE TITLE
Improve vertical spacing (CSS)

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6291]
There are a number of places in the UI where the vertical spacing could be improved:

## `form-group__text`
![Screenshot from 2019-07-29 07-11-46](https://user-images.githubusercontent.com/3323703/62025468-285ce000-b1d0-11e9-875c-caa096d22ea5.png)

## In alerts 
The last item of the alert has bottom padding, so is pushing the border down:

![Screenshot from 2019-07-29 07-12-31](https://user-images.githubusercontent.com/3323703/62025518-49253580-b1d0-11e9-86f3-ce1cf855669c.png)

## Internal pages

The spacing at the top and bottom of the page should be consistent / checked.

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, include a screenshot in your Pull Request.

**Comment by pradyunsg** [comment]
/me thinks this is a good first issue, especially for someone familiar with CSS.

**Comment by di** [comment]
Does "internal pages" mean the Admin UI here, or just the logged-in UI? If it's the former, I think we can probably remove that as a requirement to close this issue.
