### ISSUE TITLE
Persist data on "Add API token" form when validation fails

### ISSUE THREAD

**Issue by di** [pypa/warehouse#6293]
Currently when using the "Add API token" form at `/manage/account/token/`, if there is an error in the form (either there is no token name or scope selected), when the page is loaded, any existing form data is removed. It'd be nice if anything the user has already entered is persisted, in addition to the errors being shown.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by Sterbic** [comment]
Attempting this during the PyCon AU sprints :)
