### ISSUE TITLE
Failed attempt at giving name away (perf)

### ISSUE THREAD

**Issue by daurnimator** [pypa/warehouse#6327]
The pyperf project previously was 'perf' on pypi. The author (thankfully!) freed up the name (https://github.com/vstinner/pyperf/issues/50) so that it could be taken over by the [linux perf project](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/python).
However before the linux package could be uploaded, [another project](https://github.com/isidentical/perf) nabbed the [open project name](https://pypi.org/project/perf/).

Could the perf name be reserved until the linux perf project can take it over?

**Comment by gregschmit** [comment]
Yeah the current `perf` is a trivial squatting package to my eyes. But you also shouldn't ask for the name until you have code to publish. I don't think it's normal (npm certainly doesn't do it) to reserve a package name. In their words, "Don’t squat on package names. Publish code or move out of the way."

**Comment by daurnimator** [comment]
The issue is that the participants involved work asyncronously. Unless the new packager there is online and present at the moment of disownership, then the name can be nabbed by someone else.

Note that the code *is* published (it's been part of the linux kernel for years!), the author(s) just don't have much of an interest in distributing via pypy.

**Comment by gregschmit** [comment]
Silly me, I didn't go to your link and see that the Python code already exists. Then yeah, I think it's far more notable than the current one. I would probably fork the Python stuff to a GitHub repo and do the work of writing the `setup.py` and `LICENSE` and stuff so that you can publish ASAP, because it's not common to reserve words.

**Comment by isidentical** [comment]
(As the owner of `perf` on pypi) i can transfer the package name. Just ping me at `isidentical@gmail.com`.

**Comment by isidentical** [comment]
I deleted the `perf` on `pypi` so it is open to claim now.

**Comment by yeraydiazdiaz** [comment]
Thanks, @isidentical. @daurnimator @gregschmit are you in a position to upload the package or contact someone who could?

**Comment by daurnimator** [comment]
Done (I've claimed the package name myself for now). Will tidy up when I have more time (I have been sick this week)
