### ISSUE TITLE
"set up security device" doesn't work, with error message "'user.icon' should be a secure URL"

### ISSUE THREAD

**Issue by glyph** [pypa/warehouse#6343]
**Describe the bug**

The "set up security device" button on https://pypi.org/manage/account/webauthn-provision shows an error message: 

![image](https://user-images.githubusercontent.com/716529/62319181-4174c380-b452-11e9-9b2c-85668deb4dd9.png)

**Expected behavior**
Prompt me to plug in my YubiKey, I would hope?

**To Reproduce**
Click the button.

**My Platform**
Browser:
Google Chrome Version 76.0.3809.87 (Official Build) (64-bit)

Operating System:
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G84

**Comment by woodruffw** [comment]
Thanks for the report @glyph! I was able to repro, checking out now.
