### ISSUE TITLE
[Non-prefixed API tokens] may cause HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#6347]
**Describe the bug**

Following this Tweeter thread https://twitter.com/cedrickrier/status/1156922196213805056?s=19 it seems like using a `@token` username and a non-prefixed token as a password results in HTTP 500 response which probably means a traceback in the backend logs.
Needs to be verified tho.

**Expected behavior**

HTTP 403

**To Reproduce**

N/A

**My Platform**

N/A

**Additional context**

N/A

**Comment by brainwane** [comment]
cc @cedk who reported this.

**Comment by brainwane** [comment]
Per [our conversation in a planning meeting a few days ago](https://wiki.python.org/psf/PackagingWG/2019-08-02-Warehouse), some of our upcoming fixes will probably address this -- I'll keep an eye on it.

**Comment by di** [comment]
I think the real issue here is that folks are interpreting the `pypi:` prefix as not part of the token. Changing the prefix may not resolve that issue.

**Comment by webknjaz** [comment]
Totally! I think that maybe some warning ⚠ there would be helpful.

**Comment by webknjaz** [comment]
But still the HTTP error code shouldn't be 500.

**Comment by di** [comment]
Agreed, @woodruffw can we do a better job of catching this issue?

**Comment by woodruffw** [comment]
Yep, we can. I'll take a look at it tomorrow!

**Comment by woodruffw** [comment]
Just tried reproducing this on `master` by dropping `pypi-` from the token, but didn't receive a 500 error (got the expected 403).

@webknjaz Do you have any additional information that could help me repro here?

**Comment by webknjaz** [comment]
Sorry, I only know what's in that Twitter thread.

**Comment by di** [comment]
Fixed in #6384.
