### ISSUE TITLE
Align author_profile on tablet

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6372]
## Current design
![Screenshot from 2019-08-06 07-11-48](https://user-images.githubusercontent.com/3323703/62515210-92e9cd80-b819-11e9-8fc4-5045e55dd810.png)

## Suggestion
![Screenshot from 2019-08-06 07-12-00](https://user-images.githubusercontent.com/3323703/62515208-92513700-b819-11e9-90a4-28cf4008c428.png)

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, include a screenshot in your Pull Request.

**Comment by backtrackbaba** [comment]
Hey @nlhkabu, I came across this issue and I'm interested in working on it. I tried to replicate the issue but wasn't able to do it successfully.

Could you check it out if it's resolved and if not then could you tell me the tablet/device that it was misaligned?

**Comment by di** [comment]
I can still reproduce this on a sufficiently small screen:

![pypi org_user_di_(Pixel 2 XL)](https://user-images.githubusercontent.com/294415/97459198-831c4480-1909-11eb-9d3f-741e4a5f7b8c.png)

That's at a resolution of 411 x 823 pixels.

**Comment by backtrackbaba** [comment]
Thanks for the quick response @di. I was able to replicate it and get it solved directly on the browser.

I'll fix it up in the code, test it and raise a PR this weekend

**Comment by backtrackbaba** [comment]
Hey @di && @nlhkabu,

I've raised PR which resolves the issue. 

While working on it, I realized that on mobile devices, after we hide the profile picture and there is a 30px padding on top which I think can be removed as well. If we decide to go ahead, it can be resolved by tweaking the media query used in this issue.

Here's a screenshot of it before and after the fix

![mobile-device-s5-whitespace](https://user-images.githubusercontent.com/9502343/98441319-82628a00-2123-11eb-9c79-3ec1367d32db.png)

Let me know your thoughts and feedback would be glad to incorporate them

**Comment by di** [comment]
Thanks @backtrackbaba! I agree that space should probably be removed. I noticed in your PR that it still shows up between 800px and 1000px wide as well:

![warehouse localdev_user_scbunn_](https://user-images.githubusercontent.com/294415/98597978-67b52000-229f-11eb-9592-9f41c3416918.png)
