### ISSUE TITLE
Missing dependencies on Matplotlib

### ISSUE THREAD

**Issue by David-OConnor** [pypa/warehouse#6375]
This likely affects other projects as well.

[Warehouse data](https://pypi.org/pypi/matplotlib/3.1.1/json)
`requires_dist: null`

from Matplotlib 3.1.1's dist-info/METADATA file:
```
Requires-Dist: cycler (>=0.10)
Requires-Dist: kiwisolver (>=1.0.1)
Requires-Dist: pyparsing (!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1)
Requires-Dist: python-dateutil (>=2.1)
Requires-Dist: numpy (>=1.11)
```

**Comment by David-OConnor** [comment]
Found [this related issues](https://github.com/pypa/warehouse/issues/474). From what I gather:

- The requires_dist field takes info from whatever dist was uploaded first. Ie if it was a source-dist, it shows null.
- There's no distinction between no dependencies, and can't-find-dependencies.
- Package info on the warehouse won't be changed once set, even if incorrect.

Is this right? I may have to build my own api to cache this; would be more appropriate as pypi, but I'll press with this plan if this truly is a won't-fix.

**Comment by David-OConnor** [comment]
https://github.com/David-OConnor/pydeps

**Comment by di** [comment]
> Can we consider all dependency info on the warehouse unreliable

Yes, see https://dustingram.com/articles/2018/03/05/why-pypi-doesnt-know-dependencies/, which was linked from #6226.

**Comment by David-OConnor** [comment]
Thanks. IMO this is not resolved and should be attacked by the warehouse, but I'll press with this sideproject in the meanwhile.
