### ISSUE TITLE
Remove csrf-token from button (?)

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6387]
https://github.com/pypa/warehouse/blob/master/warehouse/templates/manage/account/webauthn-provision.html#L47

This line is throwing a W3C error:
`ERROR: Attribute “csrf-token” not allowed on element “button” at this point`

@woodruffw how can we refactor this functionality to use valid HTML5?

**Comment by woodruffw** [comment]
> how can we refactor this functionality to use valid HTML5?

Hmm, we could probably stuff the CSRF token into the `value` attribute instead. I'll take a look now!
