### ISSUE TITLE
Images are not rendering

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6412]
Images served from `warehouse-camo.cmh1.psfhosted.org` are not rendering.  For example, if you visit https://pypi.org/project/black/ you see:

![Screenshot from 2019-08-11 12-28-32](https://user-images.githubusercontent.com/3323703/62833261-ae970e80-bc33-11e9-9a04-e7cbe61af613.png)
![Screenshot from 2019-08-11 12-28-27](https://user-images.githubusercontent.com/3323703/62833262-ae970e80-bc33-11e9-8a21-6a9f16163548.png)
![Screenshot from 2019-08-11 12-28-24](https://user-images.githubusercontent.com/3323703/62833263-ae970e80-bc33-11e9-8de8-ca20bc63d156.png)

When I visit any of the image URLs, I get a `504 Gateway Time-out`.

**Comment by brainwane** [comment]
Looks like this was intermittent and is now resolved. Thanks for reporting it!
