### ISSUE TITLE
excute one out file,the gdb response missing tag 'fullname'

### ISSUE THREAD

**Issue by taoxiaofei0208** [pypa/warehouse#6415]
when i write ('-file-exec-file a.out') to gdb,the response mission tag 'fullname'

**Comment by brainwane** [comment]
Hi. You probably want to ask for help with this problem. You have opened an issue in the GitHub workspace of PyPI, and we can't help you with your problem. I suggest you go to [one of the forums mentioned here](https://www.python.org/community/forums/).
