### ISSUE TITLE
file size limit exemption request pybullet

### ISSUE THREAD

**Issue by erwincoumans** [pypa/warehouse#6427]
I just started hitting a file size limit when uploading pybullet version (after 3 years).
This is a python module for physics simulation and reinforcement learning for robotics. It contains some example data and pretrained Tensorflow policies and this exceeds 60Mb.

Link to PyPi: https://pypi.org/project/pybullet/

Current size of release is around 77Mb, so I had to remove some assets.

Would it be possible to extend it to 100Mb?

Only PyPi needs to be updated, not using Test PyPi)

(I use twine to upload to pypi)
~~~~~~~~~
index-servers =
    pypi
~~~~~~~~~
See also the [pybullet quickstart guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3) for more info.

Thank you for the great project!

**Comment by jamadden** [comment]
The upload limit has been set to 100MB on pypi.org.
