### ISSUE TITLE
pyforest

### ISSUE THREAD

**Issue by cyrus-muriithi** [pypa/warehouse#6429]
I am running Python 3.7.4, and Anaconda3.
I have installed pyforest using `pip install pyforest`

when i run `from pyforest import * ` in my jupyter, i get this error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-3d1b5a8ec429> in <module>
----> 1 from pyforest import *

ModuleNotFoundError: No module named 'pyforest'

Also when i run `pip freeze` i also get this warning
~(master*) » pip3.7 freeze                     cyrusmuriithi@Cyruss-MacBook-Pro
WARNING: Could not generate requirement for distribution -forest 0.1.1 (/usr/local/lib/python3.7/site-packages): Parse error at "'-forest='": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -yforest 0.1.1 (/usr/local/lib/python3.7/site-packages): Parse error at "'-yforest'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -.forest 0.1.1 (/usr/local/lib/python3.7/site-packages): Parse error at "'-.forest'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution - forest (/usr/local/lib/python3.7/site-packages): Parse error at "'-===fore'": Expected W:(abcd...)
pyforest==0.1.1

What could be the issue that i cannot run pyforest

**Comment by yeraydiazdiaz** [comment]
Hello @cyrus-muriithi, this issue tracker is only for issues on pypi.org itself.

You may want to ask the question in [pyforest's issue tracker](https://github.com/8080labs/pyforest/issues).

**Comment by cyrus-muriithi** [comment]
Ahsante sana
