### ISSUE TITLE
PEP 541: transfer ownership of non-existent snorkel project

### ISSUE THREAD

**Issue by henryre** [pypa/warehouse#6440]
Hi, I'm trying to release Snorkel (https://github.com/snorkel-team/snorkel, https://snorkel.org) for the first time on PyPI (we had previously just been on conda). I got `The credential associated with user 'henryre' isn't allowed to upload to project 'snorkel'.` despite there being no project named "snorkel" on PyPI (https://pypi.org/project/snorkel/). It looks like there's a single 2016 upload to PyPI Test (https://test.pypi.org/project/snorkel/) under the name snorkel. Our project is fairly large at this point, and most of our users would like to install via `pip`. Any help would be greatly appreciated, and let me know if there's anything I can do to get this done quickly! Thanks!!

**Comment by henryre** [comment]
cc @di since it looks like you've handled a couple of these

**Comment by ajratner** [comment]
Quickly piping in here:
- First of all, thank you so much in advance for your help here!
- Second, just for continuity / FYI- this was the project that previously was at snorkel.stanford.edu /  https://github.com/hazyresearch/snorkel before this week

Thanks!

**Comment by henryre** [comment]
also cc @jamadden since it looks like you've provided guidance on a PEP541 issues before. thanks!!

**Comment by di** [comment]
It looks like @stephenbach who seems to be involved with https://github.com/snorkel-team/snorkel is currently an owner of the `snorkel` project on PyPI. Is this someone on your team?

**Comment by henryre** [comment]
ah of course, my arch nemesis @stephenbach. thanks a ton @di we're getting it sorted!
