### ISSUE TITLE
Can't login after password reset

### ISSUE THREAD

**Issue by stevebeisner** [pypa/warehouse#6452]
I reset my password via the login dialog's "I forgot my password"
link, then following the link in the resulting email.
BUT...
The login dialog rejects the new password, even after repeated
tries over 20 minutes.
What should I do?

**Comment by stevebeisner** [comment]
Forget it.  The multi-word requirement for passwords
tripped me up. Reset with a password having multiple
space separated words and that now works.
That's a weird requirement.

**Comment by brainwane** [comment]
@stevebeisner I am not familiar with that requirement -- would it be possible for you to look at the password reset screen you are seeing and share a (redacted) screenshot?
