### ISSUE TITLE
Option to install earliest versions possible

### ISSUE THREAD

**Issue by 1313e** [pypa/warehouse#6454]
**What's the problem this feature will solve?**
As far as I know, executing `pip install -r requirements.txt` will make sure that all requirements listed in `requirements.txt` are installed and satisfied.
When a package is required that is currently not installed (or does not satisfy the minimum/maximum version), `pip` will install/update it to the latest version that satisfies all conditions.
Of course this would be the most expected behavior, but it does make it really hard to see if the minimum requirement versions defined are correct for a package, using CI services.

**Describe the solution you'd like**
An option that allows for the earliest possible versions of all requirements to be installed, instead of the latest.
Something like `pip install -r requirements.txt --install-earliest`.
Combined with the `--force-reinstall` option, this could maybe also force all requirements (not just the ones that are currently not satisfied) to be installed at their lowest versions possible.

**Additional context**
Allowing for the earliest versions possible to be installed (where no version specified means that all versions are allowed), would allow package developers to see if their `requirements.txt` files are fully correct.
In my opinion, one should always specify the minimum version required for every required dependency, but over time, it becomes really hard to figure out if these minimum versions are still correct.
This feature/option would allow for exactly this to be tested using CI services.

**Comment by di** [comment]
Hi @1313e, thanks for the report. At first glance it looks like this might belong over at https://github.com/pypa/pip instead, but I'm also not sure I'm totally understanding your use case here. Could you provide an example?

**Comment by 1313e** [comment]
> Hi @1313e, thanks for the report. At first glance it looks like this might belong over at https://github.com/pypa/pip instead, but I'm also not sure I'm totally understanding your use case here. Could you provide an example?

Uhm, yeah, it most definitely belongs at `pypa/pip`.
No idea why I posted that here actually.

Example: let's say that I have the requirement `numpy>=1.8.0` for a package.
I cannot actually test whether that minimum requirement is correct, because most people will have a newer version already installed, and CI services just install the latest version (as that is the default behavior of `pip`).
It would therefore be extremely useful if the earliest possible version could be installed (of NumPy in this case) that satisfies this requirement and all others, such that can be tested if this minimum requirement is correct.

**Comment by di** [comment]
Got it. There's some existing discussion this use case [here](http://kafka.dcpython.org/day/pypa/2019-02-07), and a closed issue requesting the same thing at https://github.com/pypa/pip/issues/3188.

The main takeaways are that this would be hard to implement before https://github.com/pypa/pip/issues/988 is solved, and that you can probably get the same result by doing something like:

```
$ sed 's/>=/==/g' requirements.txt | pip install -r /dev/stdin
```

**Comment by 1313e** [comment]
@di Alright, thanks for that.

**Comment by NeolithEra** [comment]
Hi, maybe you can try a dependency diagnosis website http://www.watchman-pypi.com/dependency_analysis, which can help diagnoze dependency conflict problems and automatically visualize your dependency tree and those of your downstream projects.

Best,
Neolith

**Comment by dstufft** [comment]
I'm going to go ahead and close this, since it appears to be a pip feature request.
