### ISSUE TITLE
File size limit increase for pyrasterframes

### ISSUE THREAD

**Issue by metasim** [pypa/warehouse#6461]
**A link to your project on PyPI (or Test PyPI)** 
Project: https://pypi.org/project/pyrasterframes/

**The size of your release, in megabytes**
60.1 MB. Setting our limit to 80MB or so would be great, to give us some buffer.

**Which index/indexes you need the increase for (PyPI, Test PyPI, or both)**
Both would be nice. PyPI definitely.

**A brief description of your project, including the reason for the additional size.**

`pyrasterframes` is the Python bindings to [RasterFrames](https://rasterframes.io), a Spark SQL library for large geospatial raster processing. To be self contained, it has a Java JAR file embedded in it, containing all the dependencies required to run in the `pyspark-shell`, Jupyter Notebooks, etc.

**Comment by di** [comment]
I've set the upload limit for `pyrasterframes` to 100 MB on PyPI and TestPyPI.
