### ISSUE TITLE
Add gravatar to current user indicator (logged-in menu)

### ISSUE THREAD

**Issue by di** [pypa/warehouse#6462]
In #6402 we removed the "Welcome back, \<username>" that used to be in the "current user indicator" (the drop-down menu in the top right when logged in), it's now just the username and an arrow.

Now that we have more room there, it would be nice to include the user's gravatar to make it more clear that this is where the user can click to get to logged-in views.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: *If your pull request makes a visual change*, include a screenshot of your update. This helps our team give you feedback faster.

**Comment by andrzej3393** [comment]
I'm working on it, but I'm in doubt what to do if a user does not have a Gravatar. I can see two options there:
* don't display any image, just plain username like now
* display a default avatar
IMHO the second one is better because it'll look more consistent, but on the other hand the default avatar will be needed. WDYT?

**Comment by di** [comment]
> I'm working on it, but I'm in doubt what to do if a user does not have a Gravatar.

Gravatar will supply a default image if the user hasn't defined one: https://en.gravatar.com/site/implement/images/#default-image

**Comment by andrzej3393** [comment]
Thank's for the reply, it's nice that you react so quickly :smiley: I'll use the Gravatar's default then.

**Comment by kamyar** [comment]
Is this issue still relevant? I would like to try to add this.
