### ISSUE TITLE
Increase upload size limit of h2o_pysparkling_x packages to 150MB

### ISSUE THREAD

**Issue by mn-mikke** [pypa/warehouse#6490]
Hi,
I'm one of the maintainers of Sparkling Water https://github.com/h2oai/sparkling-water project which has PySparkling as the Python client. The project has integrated several features that caused growth of PySparkling packages. The size of packages is reaching the current limit 100MB.

I would like to ask you to extend the limit for Pysparkling packages to 150MB if possible.:
https://pypi.org/project/h2o-pysparkling-2.1/
https://pypi.org/project/h2o-pysparkling-2.2/
https://pypi.org/project/h2o-pysparkling-2.3/
https://pypi.org/project/h2o-pysparkling-2.4/

Thanks,
Marek Novotny

**Comment by jamadden** [comment]
The limit for all four projects has been set to 200MB on pypi.org

Collectively, that amounts to one of the larger package sizes. Please be mindful about how often you make releases of this package given the size.

**Comment by mn-mikke** [comment]
@jamadden Thanks a lot!
