### ISSUE TITLE
Something is wrong with  PyInstaller: "Compressed file ended before end of stream marker was reached" Also Hash not correct.

### ISSUE THREAD

**Issue by azaia** [pypa/warehouse#6513]
Something is wrong with  PyInstaller: "Compressed file ended before end of stream marker was reached" Also Hash not correct.

**Comment by yeraydiazdiaz** [comment]
Hello @azaia, this issue tracker is for problems with PyPI.org itself, I suggest you have a look at [PyInstaller's issue tracker](https://github.com/pyinstaller/pyinstaller/issues) and raise your issue  there if appropriate.
