### ISSUE TITLE
Visitor Activity not accepting paramaters

### ISSUE THREAD

**Issue by rmcendarfer2017** [pypa/warehouse#6514]
I am having an issue where when I create the following query 

`
from pardot.client import APIClient

client= APIClient(
	'email',
	'Password',
	'API_KEY'
	)

r= client.visitorActivity.query(created_after='yesterday',limit=1)

print(r)`

I get back Arguments (0) do not match identifiers (2) for operation query on visitorActivity

how if add to blank string like this r= client.visitorActivity.query(' ', ' ')
I get the oldest created visitor activity but I am not able to put any search criteria around my query that will give me results back. 

Am I missing something here or is there an issue?

**Comment by yeraydiazdiaz** [comment]
Hi @rmcendarfer2017, this issue tracker is for problems with PyPI.org itself. I suggest raising your issue in [PyPardot4's issue tracker].
