### ISSUE TITLE
Unauthorized Use of Apache-Superset

### ISSUE THREAD

**Issue by cgivre** [pypa/warehouse#6540]
To whom it may concern.

I am writing on behalf of the Apache Superset (Incubating) project.  We are seeing to post the most current official Apache release of Superset to Pypi, however it appears that someone who is not connected to the project has claimed the name `apache-superset`.

We would like to claim this repo name if possible as it could be very misleading, or allow someone to post a malicious twin of the Superset project.  Would it be possible to reassign the name to the Apache Project, or at a minimum, get us the contact info for the owner so that we can contact that person and make the request?
Thank you!

@mistercrunch

**Comment by cgivre** [comment]
If we don't hear back, we would like the account owner to be assigned to the "mistercrunch" user. 
Thanks,
-- C

**Comment by cgivre** [comment]
@ewdurbin 
I believe 7 days has passed and we've not heard anything about this.  Can you please go ahead and transfer the account to `mistercrunch`?  Thanks!


@mistercrunch

**Comment by ewdurbin** [comment]
Transfer complete.
