### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by dimaqq** [pypa/warehouse#6543]
https://github.com/python/cpython/ master branch is now 3.9.0alpha0
(https://github.com/python/cpython/commit/9ab2fb1c68a75115da92d51b8c40b74f60f88561)

Perhaps it's time to:

* include `Programming Language :: Python :: 3.9` at https://pypi.org/classifiers/
* allow package uploads with such classifier

```
… ~/awaitwhat> poetry publish

Publishing awaitwhat (19.1a1) to PyPI
Username: dimaqq
Password:
 - Uploading awaitwhat-19.1a1-cp37-cp37m-macosx_10_9_x86_64.whl 100%

[UploadError]
HTTP Error 400: Invalid value for classifiers. Error: 'Programming Language :: Python :: 3.9' is not a valid choice for this field
```

**Comment by ewdurbin** [comment]
Completed on test.pypi.org and pypi.org. Thanks @dimaqq
