### ISSUE TITLE
Localize 503 page

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6550]
Our 503 page is hosted in a [private repo](https://github.com/python/pypi-theme/blob/master/error_pages/503.html) and needs to remain self-contained so that we can serve it from Fastly.

However, it should be localised as part of the OTF work currently under development.

**Comment by nlhkabu** [comment]
@ewdurbin what would be the next steps here?
FYI @woodruffw

**Comment by brainwane** [comment]
Closing this - opened an issue in the other repo.
