### ISSUE TITLE
Project description: rendering of <pre> in lists ugly

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6552]
Given the following HTML structure in a project description:

![Screenshot from 2019-08-30 07-29-40](https://user-images.githubusercontent.com/3323703/63998024-12587d00-caf8-11e9-990d-6abb2b470745.png)

The rendering is poor:

![Screenshot from 2019-08-30 07-29-36](https://user-images.githubusercontent.com/3323703/63998025-12587d00-caf8-11e9-8985-47d301a851a2.png)

This requires updating warehouse/static/sass/blocks/_project-description.scss

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, include a screenshot in your Pull Request.

**Comment by Kohdz** [comment]
Hello, I would like to help with this issue

**Comment by brainwane** [comment]
@Kohdz  Yes, please go ahead and grab this issue! At least within Warehouse, our rule is: If there is not a corresponding pull request for this issue (visibly linked by issue number/PR number), and it's not marked as assigned to anyone, it is up for grabs. So in cases like this, you don't even need to ask. :) Just comment and say that you're starting to work on it, and link in a comment to your work-in-progress branch once you start.

As always, if you have questions along the way as you work on this, please feel free to ask them here, in [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev). Thank you!

**Comment by Abhi-khandelwal** [comment]
is this issue still open?

**Comment by yeraydiazdiaz** [comment]
I believe it is @Abhi-khandelwal

**Comment by yeraydiazdiaz** [comment]
For reference, the screenshot comes from this page https://pypi.org/project/twine/

**Comment by Abhi-khandelwal** [comment]
Thanks for sharing :)
