### ISSUE TITLE
those package as the same name with standand library need be review

### ISSUE THREAD

**Issue by zjjott** [pypa/warehouse#6562]
**What's the problem this feature will solve?**

those package as the same name with standand library need be review
such as `test` package,when it installed,something bad thing will be happend

**Describe the solution you'd like**

the one who upload package using the same name with standand library,reviewer is need,`six` module is do a good thing

the third module  `test` pypi url: https://pypi.org/project/test/

**Comment by di** [comment]
I've added `test` to our blocklist and removed https://pypi.org/project/test/.
