### ISSUE TITLE
TestPyPI Not Accepting Packages With OSL License Classifier

### ISSUE THREAD

**Issue by mischif** [pypa/warehouse#6591]
**Describe the bug**

When trying to upload a package to TestPyPI using the classifier "License :: OSI Approved :: Open Software License 3.0 (OSL-3.0)", I receive the error below:

```HTTPError: 400 Client Error: Invalid value for classifiers. Error: 'License :: OSI Approved :: Open Software License 3.0 (OSL-3.0)' is not a valid choice for this field for url: https://test.pypi.org/legacy/```

**Expected behavior**

My package to be accepted by TestPyPI.

**To Reproduce**

Add the OSL license classifier to a project and attempt to submit to TestPyPI

**My Platform**

**Additional context**

**Comment by greschd** [comment]
I've just run into this issue: In general the classifiers listed at https://test.pypi.org/classifiers seem to be different from the ones at https://pypi.org/classifiers.

The classifier I was trying to use (``Framework :: AiiDA``) is rather new, so maybe this is a synchronization issue.

**Comment by jamadden** [comment]
I've made sure both those classifiers are available on test.pypi.org.

**Comment by greschd** [comment]
Sweet, thank you.
