### ISSUE TITLE
Request trove classifier: Django 3.0

### ISSUE THREAD

**Issue by jschneier** [pypa/warehouse#6605]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `'Framework :: Django :: 3.0'`

## Why do you want to add this classifier?

Django 3.0 alpha was released today. See: https://www.djangoproject.com/weblog/2019/sep/10/django-30-alpha-1-released/

**Comment by carltongibson** [comment]
Hi, yes, can I bump this please? Django is now beta, and we're seeing third party packages trying to release with support.

Thanks!

**Comment by carltongibson** [comment]
Hi @ewdurbin. Sorry for the noise. You were able to resolve #5317 for us. Would you be able to look at this please? (It's becoming a little pressing... 😬) Thanks!

**Comment by jamadden** [comment]
`Framework :: Django :: 3.0` has been added to pypi.org and test.pypi.org.

**Comment by ewdurbin** [comment]
Thank you @jamadden!

**Comment by carltongibson** [comment]
Super. Thanks both!
