### ISSUE TITLE
PyPI not really pure python

### ISSUE THREAD

**Issue by mstupak** [pypa/warehouse#6620]
Since PyPI requires Numpy and SciPy, calling PyPI a "pure python" implementation is a bit of a misnomer. Both Numpy and SciPy make heavy use of "C" code. Anybody searching for a "pure java" will be looking for functions that they can run in an environment (such as jython) that does not require "C" or other non-"truly pure python" implementations. I would suggest removing the "pure python" vocabulary from the webpage and project documentation or at least put a disclaimer up front near the "pure python" claims.

**Comment by di** [comment]
Hi @mstupak. Are you confusing PyPI ("The Python Package Index") with [pypy](https://bitbucket.org/pypy/pypy/) (self-hosting Python)?

**Comment by mstupak** [comment]
Thanks @di ! Obviously I got a little crazy following links and ended up in an unintended repository.
