### ISSUE TITLE
Missing test for project detail page (template failure)

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6634]
## Problem
When updating the templates for the project detail page (e.g. https://pypi.org/project/python-ecobee-api/) I was getting a Jinja template exception from the project data include (`warehouse/templates/includes/packaging/project-data.html`)

This was *not* being picked up by running the PyPI unit tests.

## Proposed solution
We should add a unit test to check the appropriate rendering of this page

**Comment by sk1u** [comment]
Hi @nlhkabu , Can I work on this issue?

**Comment by nlhkabu** [comment]
Sure @sk1u, thanks for your PR
