### ISSUE TITLE
Reduce font size of package-snippet__released

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6635]
## Problem

The date on the search results is too large:

![Screenshot from 2019-09-14 17-58-30](https://user-images.githubusercontent.com/3323703/64911454-ddfcd780-d719-11e9-90dd-1cc0662cfb40.png)

## Solution

Add `font-size: 1rem;` to `package-snippet__released` style.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Screenshot Required**: Please include a screenshot of your update. This helps our team give you feedback faster.

**Comment by sargamm** [comment]
Hey! I just made a pull request for this issue. Kindly have a look. Thanks!
