### ISSUE TITLE
Send 'password change' email when a user changes their password via the reset workflow

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#6637]
## Current behaviour

An email (`warehouse/templates/email/password-change`) is sent to a user when they reset their password via their account settings page (assuming their email is verified)

##  Requested behaviour

The email should be sent to the user:

- When they reset their password via their account settings page **and**
- When they reset their password via the password reset workflow

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by nlhkabu** [comment]
This issue was incorrect -> the email is sending, but only when the password is changed via the 'manage account' page, *not* when it is reset via the

**Comment by di** [comment]
I've added the "good first issue" label to this issue. Looks like we need to add something like:

https://github.com/pypa/warehouse/blob/30f2389b27f0d57462e03c23c3126ff707daf8dd/warehouse/manage/views.py#L303

here: https://github.com/pypa/warehouse/blob/30f2389b27f0d57462e03c23c3126ff707daf8dd/warehouse/accounts/views.py#L518-L529

Plus updated tests.
