### ISSUE TITLE
new Trove classifier request "Framework :: Zope :: 5"

### ISSUE THREAD

**Issue by loechel** [pypa/warehouse#6641]
Request to add a new Trove classifier.

## The name of the classifier you would like to add

* `Framework :: Zope :: 5`

## Why do you want to add this classifier?

The Plone Foundation as Owner and Maintainer of the Zope Projects requests a new Trove Classifier for the next Major Version of The Zope Application Server. Zope 5 is a Major Release as Python 2 Support is stripped out.

**Comment by ewdurbin** [comment]
Added to both test.pypi.org and PyPI.org
