### ISSUE TITLE
module for ethernet cable based RFID reader

### ISSUE THREAD

**Issue by Rohithpokala** [pypa/warehouse#6659]
**What's the problem this feature will solve?**
this feature will resolve the issue of reading data from an ethernet cable based RFID reader

**Describe the solution you'd like**
the most common module available in python is mfrc522, but if we want to use another reader this module doesn't work.

**Additional context**
The reader which I am using is rrhfoem04, but try to develop a generic module for RFID readers where we can integrate readers directly with laptop

**Comment by jamadden** [comment]
Hi @Rohithpokala ! This issue tracker is for the software that runs pypi.org itself. It cannot help with the packages that are installable from there. If existing packages don't meet your needs, perhaps you can collaborate with their authors using their repositories to make improvements.

**Comment by Rohithpokala** [comment]
> Hi @jamadden ! Thank you for your response. could you suggest me how to contact the authors?

**Comment by jamadden** [comment]
Check the links on the pypi project page, or do a web search.
