### ISSUE TITLE
Support for properly displaying the site translated to RTL languages

### ISSUE THREAD

**Issue by taleinat** [pypa/warehouse#6683]
**What's the problem this feature will solve?**
Display PyPI.org propely when translated to RTL languages such as Arabic, Farsi and Hebrew.

**Describe the solution you'd like**
I can't suggest a specific technical solution, since I'm not familiar with the website's design and implementation.

**Additional context**
The context is the recent work on translation into additional languages.

**Comment by nlhkabu** [comment]
Options to investigate: 
- https://www.npmjs.com/package/postcss-rtl
- https://github.com/MohammadYounes/rtlcss

**Comment by tarkatronic** [comment]
I wanted to toss in another possibility; GoDaddy just recently developed this WebPack plugin during our efforts to build better BiDi support: https://github.com/godaddy/webpack-rtlcss-plugin

It uses rtlcss under the covers (linked above by @nlhkabu), but might make it a bit easier to use.

**Comment by di** [comment]
At the time of writing, our Arabic translation is at 29%, Hebrew is at ~0%, and Farsi does not yet exist, so this is low- to medium-priority for now.

**Comment by taleinat** [comment]
> our Arabic translation is at 29%, Hebrew is at ~0%, and Farsi does not yet exist

This is a chicken-and-egg problem: There's little point in translating to a language that the site doesn't support at a technical level. It's also more difficult since one can't properly see the result of the translations on the site itself.

If it would help, I'd be willing to help with the Hebrew translation (I'm a native speaker).

**Comment by di** [comment]
To be clear, translations are done through https://hosted.weblate.org/projects/pypa/warehouse/ and can be completed independently of whether PyPI supports them or not.

All the currently completed translations were done through that interface, and none of the translators were able to see the result of the translations on the site until they reached ~100% completion and we explicitly added support for their given locale.

I'm also not convinced that our lack of support for RTL languages is what's causing the low completion percentages for those locales. I would assume that most contributors are unaware that we'd have extra work to do to support their locale once it reaches ~100% complete.

> If it would help, I'd be willing to help with the Hebrew translation (I'm a native speaker).

Absolutely! If you're able to significantly increase the completion percentage for just one of these languages, we can prioritize this work to ensure that we're ready to support it when it's fully translated.

Let us know if you have any questions!

**Comment by taleinat** [comment]
> If you're able to significantly increase the completion percentage for just one of these languages, we can prioritize this work to ensure that we're ready to support it when it's fully translated.

That's great to hear! This is why I hadn't started helping with the translation earlier: I wasn't sure whether RTL language support would actually be worked on.

In that case I'll start working on the translation when I can.

**Comment by taleinat** [comment]
I've translated 50% of the strings for the Hebrew language so far.

BTW,
> I would assume that most contributors are unaware that we'd have extra work to do to support their locale once it reaches ~100% complete.

IMO most of those using RTL languages would likely be acutely aware of this, since we see so many issues caused by our languages being RTL in our digital age...

**Comment by taleinat** [comment]
I've completed 100% translation of PyPI.org to Hebrew. Ready for the next step!

**Comment by taleinat** [comment]
@di, with the Hebrew translation done, can this be given higher priority?

**Comment by nlhkabu** [comment]
Thank you for this @taleinat!  @di - maybe we can book some pairing time together to look at this?

**Comment by di** [comment]
@taleinat Yes!

@nlhkabu Yes! Will DM you.

**Comment by nlhkabu** [comment]
@taleinat FYI, @di and I started on this today.  Once we have made some more progress, we'll probably be looking for feedback from you as to whether or not everything is displayed correctly.

**Comment by taleinat** [comment]
@nlhkabu, that's great to hear!

**Comment by di** [comment]
Draft at #7927, @taleinat feel free to pull down that branch and test locally if you're able.

**Comment by nlhkabu** [comment]
@taleinat I've started editing our SCSS files to ensure that user generated content (usually in English) is displayed ltr, while the rest of the page renders rtl. 

This is fairly straightforward when the ltr content is a separate interface item, for example:

![Screenshot from 2020-05-12 22-23-15](https://user-images.githubusercontent.com/3323703/81746989-4665a980-949f-11ea-878b-d7448f7bd27f.png)

What I'm not clear on is how the interface should render when we have ltr and rtl content mixed together, for example:

![Screenshot from 2020-05-12 22-25-12](https://user-images.githubusercontent.com/3323703/81747150-7f9e1980-949f-11ea-88a5-d263ab83ccc6.png)

Are you able to provide some guidance here? It would be particularly useful if you could point me to examples of websites that handle this kind of thing well.

**Comment by taleinat** [comment]
Hi Nicole,

Yes I'd be happy to give some guidance and examples tomorrow.

The example image looks very good! The only issue I notice now is very minor: In the "author" field, the space between the envelope icon and the author's name is on the wrong side of the envelope.

**Comment by nlhkabu** [comment]
> The example image looks very good! The only issue I notice now is very minor: In the "author" field, the space between the envelope icon and the author's name is on the wrong side of the envelope.

That's good news, as this is the default from rtlcss (I have not yet edited the second screenshot). Icons should be fairly easy to fix :)

**Comment by taleinat** [comment]
I think a good example website is [Hebrew Wikepedia](https://he.wikipedia.org/). It seems to get everything right with regard to RTL and mixed RTL/LTR.

A few pages with interesting amounts of mixed Hebrew and English:

* [Python](https://he.wikipedia.org/wiki/%D7%A4%D7%99%D7%99%D7%AA%D7%95%D7%9F)
* [Guido van Rossum](https://he.wikipedia.org/wiki/%D7%92%D7%95%D7%95%D7%99%D7%93%D7%95_%D7%95%D7%90%D7%9F_%D7%A8%D7%95%D7%A1%D7%95%D7%9D)
* [ASCII](https://he.wikipedia.org/wiki/ASCII)
