### ISSUE TITLE
pypi says libraries.io has stats about package but there is none

### ISSUE THREAD

**Issue by amirouche** [pypa/warehouse#6689]
**Describe the bug**

pypi says libraries.io has stats about package but there is none

**Expected behavior**

- See download stats on libraries.io

**To Reproduce**

- Go to https://libraries.io/pypi/hoply

**My Platform**

ALL

**Comment by di** [comment]
Hi @amirouche, I see some statistics at that URL, what were you expecting to see?

**Comment by amirouche** [comment]
I expect to see the number of download of my project.

**Comment by Nosferican** [comment]
I believe the download statistics were [deprecated](https://mail.python.org/pipermail/distutils-sig/2013-May/020855.html). However, it may have been revived through [pepy](https://pepy.tech/project/hoply) by Petru Rares Sincraian (@psincraian).

**Comment by brainwane** [comment]
Hi @amirouche!

I looked at https://pypi.org/project/hoply/ and I saw in the sidebar:

> View statistics for this project via [Libraries.io](https://libraries.io/pypi/hoply), or by using [Google BigQuery](https://packaging.python.org/guides/analyzing-pypi-package-downloads/).

https://libraries.io/pypi/hoply does show statistics about the `hoply` package, such as repo size, dependencies, and so on. I understand that you're interested in _download_ statistics in particular; the Google BigQuery link, which was next to the Libraries.io link you saw, helps you get those. You may also want to look at [our FAQ item "Where can I see statistics about PyPI, downloads, and project/package usage?"](https://pypi.org/help/#statistics).

Thanks and I hope this helps!

**Comment by amirouche** [comment]
> https://libraries.io/pypi/hoply does show statistics about the hoply package, such as repo size...

This is clearly misleading and does not help build trust.

**Comment by amirouche** [comment]
Yes I know statistic are gone from pypi.org but pypi has an "advertisment" for libraries.io that is misleading. Trivia stuff like repo size and dependencies is not what people will expect.

Anyway thanks.
