### ISSUE TITLE
Intra-package References Documentation look unusual

### ISSUE THREAD

**Issue by Sayeed096** [pypa/warehouse#6707]
Documentation is not completed or properly described.
"For example, if the module sound.filters.vocoder needs to use the echo module in the sound.effects package, it can use from sound.effects import echo."
This example is not good to understand.
"
from . import echo
from .. import formats
from ..filters import equalizer
"
Please give some more clear explanation and example.

**Comment by jamadden** [comment]
You seem to be referring to the [standard Python documentation](https://docs.python.org/3/tutorial/modules.html#intra-package-references). This issue tracker is only for the software that runs pypi.org itself; it cannot help with the standard Python documentation. For that, you'll need https://bugs.python.org.
