### ISSUE TITLE
HTTPError: 400 Client Error: Binary wheel 'pyarrow_ppc64le-0.14.0-cp36-cp36m-linux_ppc64le.whl' has an unsupported platform tag 'linux_ppc64le'. for url: https://upload.pypi.org/legacy/

### ISSUE THREAD

**Issue by xauthulei** [pypa/warehouse#6719]
Could I know what are errors  in my local ppc64le ?

**Comment by brainwane** [comment]
@xauthulei Hi - could you show us what command you ran in order to create that wheel, and share your `setup.py` file as well? And, if you read documentation that advised you to use the platform tag 'linux_ppc64le', could you point to it? Thanks!

**Comment by di** [comment]
`linux_*` is not a valid platform for a wheel. Depending on what you're trying to distribute, you either need to either build your distributions inside the [`manylinux` Docker image](https://github.com/pypa/manylinux) or just use [`auditwheel`](https://github.com/pypa/auditwheel) to turn a `linux_*` into a repaired `manylinux_` wheel.

In addition, `ppc64le` is not a valid architecture for a [`manylinux1`](https://www.python.org/dev/peps/pep-0513/) or [`manylinux2010`](https://www.python.org/dev/peps/pep-0571/) wheel. It is a valid architecture for a [`manylinux2014`](https://www.python.org/dev/peps/pep-0599/) wheel, but the implementation of this specification is [currently in progress](https://github.com/pypa/manylinux/issues/338).

**Comment by xauthulei** [comment]
Thanks @di and @brainwane , Now it is clear to me,  Thanks.  it seems I need to wait manylinux2014.
