### ISSUE TITLE
PEP 541: Semi-urgent request ownership of 'RIFT' package/name

### ISSUE THREAD

**Issue by oshaughn** [pypa/warehouse#6720]
I would like to request ownership of the RIFT project name, so we can [replace the previous history](https://pypi.org/project/rift/#history). This project classifies as Abandoned by @yayg , who has committed only this project, whose last and only activity was 4 years ago, and who has no contact information.

This is a semi-urgent request because RIFT is used by the LIGO scientific collaboration for analysis of gravitational wave data, we strongly prefer a standard pip-installable packages, and analysis needed for publications will commence within the month (if not sooner)  -- so addressing this before mid-October 2019 is important.  Changing the namespace will introduce unnecessary confusion, as the project has been developed for almost 5 years with this name.

We're finishing the packaging now, so the structure will look a bit different, but we've used the same namespace on test.pypi.org

**Comment by jamadden** [comment]
I've emailed the owner of that project at the public email address listed for that project as well as the email address PyPI has on file for that account, opened [an issue](https://github.com/Yayg/rift/issues/1) in what appears to be the repository on github (and the account has been active recently) as well as attempted contact via the listed [twitter account](https://twitter.com/ossmkitty/status/1177549692751757312).

**Comment by Yayg** [comment]
Hi Jason,

Sorry for the late reply. The project is not maintained anymore and surely
doesn't need a pip-installable package.
Let me know what you need from to transfer the name.

All the best.

**Comment by jamadden** [comment]
Hi @yayg and thanks for the reply! If @oshaughn could supply a PyPI username, then you could add that username as an administrator of the PyPI project. They could then remove your account from the PyPI project and move forward with using the name.

**Comment by oshaughn** [comment]
My pypi username should be ‘oshaughn’

Thanks all!

From my phone- apologies for brevity, typos, etc

**Comment by Yayg** [comment]
Done! Good luck with your project :)

All the best,

raf
