### ISSUE TITLE
Add Travis CI badge to README

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#6752]
[Warehouse uses Travis CI to run integration tests](https://travis-ci.org/pypa/warehouse/). Our `README.md` file doesn't have a badge at the top saying that our Travis CI builds are passing. You can look at https://shields.io/category/build to see how to add one.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by Patil2099** [comment]
@brainwane Can I work on this issue?

**Comment by brainwane** [comment]
Sure, go ahead @Patil2099!

**Comment by brainwane** [comment]
A longer response for @Patil2099 -- Yes, please go ahead and grab this issue! At least within Warehouse, our rule is: If there is not a corresponding pull request for this issue (visibly linked by issue number/PR number), and it's not marked as assigned to anyone, it is up for grabs. So in cases like this, you don't even need to ask. :) Just comment and say that you're starting to work on it, and link in a comment to your work-in-progress branch once you start.

As always, if you have questions along the way as you work on this, please feel free to ask them here, in [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev). Thank you!
