### ISSUE TITLE
Increase size limit request

### ISSUE THREAD

**Issue by rcurtin** [pypa/warehouse#6756]
Hi there,

I'm the maintainer of the PyPI `mlpack` package: https://pypi.org/project/mlpack/

The manylinux releases turn out to be larger than the size limit of 60.0MB; specifically, they are currently 80 MB.  I'd like to request an increase to the size limit to match the limit for `mlpack3` (https://pypi.org/project/mlpack3/)---the `mlpack3` package is where the library was previously uploaded until I was able to obtain the `mlpack` package name on PyPI.

Please let me know if any other information is needed.

Thanks so much!

**Comment by jamadden** [comment]
The size limit for mlpack on pypi.org has been set to 100MB (matching mlpack3).

**Comment by rcurtin** [comment]
Thank you! :+1:
