### ISSUE TITLE
Make PYPI more like a app distribution store 

### ISSUE THREAD

**Issue by srevinsaju** [pypa/warehouse#6757]
**What's the problem this feature will solve?**
A request to add features like Embeddable Cards and Install from PYPI store button, similar to the Snap Store.

**Describe the solution you'd like**
Add a HTML/Markdown label generator similar to Snapcraft.io 
I can do the designing part, but I didn't find the HTML

**Additional context**
The idea which I would like to put forth is similar to this one;
![Screenshot_20191004-095101](https://user-images.githubusercontent.com/48695438/66187393-5a396980-e68d-11e9-84bf-890722d2b024.jpg)

**Comment by di** [comment]
Duplicte of #330. We recommend using https://shields.io/ instead.
