### ISSUE TITLE
Handle pinning on Pinterest

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#677]
See https://bitbucket.org/pypa/pypi/issues/336/python-package-pages-pin-poorly-on

> @audreyr wrote:
> For example, when I try to pin Cookiecutter 1.0.0 on Pinterest:
> * it pins as "pypi.python.org" with no mention of the package name or version
> * the image doesn't get picked up.
> * the default text image should be the package name, not PYPI PYTHON ORG
> ![3811756009-screen shot 2015-09-09 at 9 37 24 pm](https://cloud.githubusercontent.com/assets/145979/9787581/055a3efa-5792-11e5-9c56-270e18242872.png)
> Feel free to close this out if it's too low-priority. I just figured you might want to know and have it tracked, since a lot of people (esp women) use Pinterest for all their bookmarking.

**Comment by ismail-s** [comment]
See https://developers.pinterest.com/docs/rich-pins/ for more info (and https://business.pinterest.com/en/rich-pins although it doesn't tell you much more). From these links,what would be required to support this is:

1. Add metatags to /pypi/package pages. Either [OpenGraph](http://ogp.me/) or [Schema.org](schema.org)
1. Login to pinterest and run it through a [validator thingy](https://developers.pinterest.com/tools/rich-pins/validator/)
1. They email back at some point.
