### ISSUE TITLE
psycopg2 can't build

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#6782]
Followup to #3106 (or: "psycopg2: the unfolding").

I was trying to fix a different problem in my developer environment and tried `$ pip install -U -r requirements.txt` and got this error:

~~~
Collecting psycopg2==2.8.3 (from -r requirements/main.txt (line 379))
  Downloading https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz (377kB)
     |████████████████████████████████| 378kB 3.5MB/s 
    ERROR: Command errored out with exit status 1:
     command: /[path redacted]/.virtualenvs/PyPI/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0bu02wzi/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0bu02wzi/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-0bu02wzi/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
~~~

I don't actually see any instructions to pip install stuff in https://warehouse.readthedocs.io/development/getting-started/  -- we do this all in the Docker container -- so I think this is probably not actually a bug. But in case it is: I see we don't have `pg_config` anywhere listed as a requirement in the Warehouse source; should we?

**Comment by yeraydiazdiaz** [comment]
I believe this is because our `main.txt` includes `psycopg2`, which attempts to build from source and [requires](http://initd.org/psycopg/docs/install.html#prerequisites) PostgreSQL client and server library versions which `pg_config` is part of. If you happen to have PostgreSQL installed on your machine it should build fine.

The docs don't cover this because, as you say, it's all built in the Docker environment. We could include a non Docker development section if that's a use case, though it's probably more trouble than it's worth, most contributors seem comfortable with the Docker setup (I think 😄 ).

What was the problem in your enviroment you were trying to solve?

**Comment by brainwane** [comment]
#6778 and #6744 were the issues I was trying to resolve, I believe.

Maybe we could add an item about this to the Troubleshooting section? I think that would address this issue.

**Comment by brainwane** [comment]
Thanks @yeraydiazdiaz and @di!

**Comment by chrisberks** [comment]
You can fix this by installing `libpq-dev` on your system (Debian/Ubuntu). This will install the missing `pg_config` executable.

```console
$ sudo apt install libpq-dev
```

For RPM based systems—I think—the equivalent is `postgresql-devel` or `libpq-devel`.

More info in the [build prerequisites section](https://www.psycopg.org/docs/install.html?highlight=pg_config#build-prerequisites) of the Psycopg2 docs.

I hit this same error running:
```console
$ pip-compile --allow-unsafe --generate-hashes main.in
```
