### ISSUE TITLE
Update "getting stated" to discourage virtualenvs/venvs

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#6783]
Update `docs/development/getting-started.rst` (the source for https://warehouse.readthedocs.io/development/getting-started/ ) to say, in the "Configure the development environment" section, something like:

"In case you are used to using a `venv`/virtualenv or virtual environment for Python development: For Warehouse development, don't use one. Our `Makefile` scripts and Docker container development flow create and remove virtualenvs as needed while you are building and testing your work locally."

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by raghav-ys** [comment]
@brainwane - Hello, I have updated the documentation based on your comment. Submitted  a PR. Please  review.

**Comment by brainwane** [comment]
Hi, @raghav-ys and welcome to GitHub! I see you started a new branch and are working on addressing this issue in https://github.com/raghav-ys/warehouse/commit/6e4c1b879b572170b3236f050be48ec4cfbf9ab4 . Please read https://help.github.com/en/articles/about-pull-requests and submit a pull request, and then mention its PR number ("#nnnn") in a comment here on this issue, to make your change easier for someone to review. I also recommend you read the book at http://www.open-advice.org/ !

**Comment by raghav-ys** [comment]
Thanks @brainwane. I will read the book. 

Submitted PR#6784.

**Comment by deveshks** [comment]
I wanted to work on this issue, but I found that a PR https://github.com/pypa/warehouse/pull/6784 has already been created against it, but that PR hasn't been worked on for a few months now.

May I raise a new PR against this issue to add the documentation as suggested?

**Comment by di** [comment]
I think a new PR that's more in line with what @brainwane suggested in this issue would be great.

**Comment by deveshks** [comment]
> I think a new PR that's more in line with what @brainwane suggested in this issue would be great.

Thanks. I created a PR to follow the given wording at https://github.com/pypa/warehouse/pull/7908
