### ISSUE TITLE
Lost authentication app

### ISSUE THREAD

**Issue by lasote** [pypa/warehouse#6803]
Hi, I've lost my authentication app for my account "lasote" at "lasote@gmail.com". 
It is quite important I can get access. Thanks and sorry :(

**Comment by ewdurbin** [comment]
Hi @lasote please email ernest@python.org from the email address associated with your PyPI user.

**Comment by lasote** [comment]
done

**Comment by ewdurbin** [comment]
I've worked through verifications for ownership of associated projects and email addresses, reset the TOTP secret for the user, and issued a password reset.
