### ISSUE TITLE
Duniya1

### ISSUE THREAD

**Issue by Yusuf4396** [pypa/warehouse#6811]
### DNS Resolution

```shell
dig pypi.org A
<Replace with your output>
```

```shell
dig pypi.org AAAA
<Replace with your output>
```

```shell
dig files.pythonhosted.org A
<Replace with your output>
```

```shell
dig files.pythonhosted.org AAAA
<Replace with your output>
```

#### IPv4

```shell
traceroute pypi.org
<Replace with your output>
```

```shell
traceroute files.pythonhosted.org
<Replace with your output>
```

#### IPv6 (If available)

```shell
traceroute6 pypi.org
<Replace with your output>
```

```shell
traceroute6 files.pythonhosted.org
<Replace with your output>
```

#### IPv4

```shell
curl -vvv -I --ipv4 https://pypi.org/pypi/pip/json
<Replace with your output>
```

```shell
curl -vvv -I --ipv4 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz
<Replace with your output>
```

#### IPv6 (If available)

```shell
curl -vvv -I --ipv6 https://pypi.org/pypi/pip/json
<Replace with your output>
```

```shell
curl -vvv -I --ipv6 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz
<Replace with your output>
```

#### IPv4

```shell
echo -n | openssl s_client -4 -connect pypi.org:443
<Replace with your output>
```

```shell
echo -n | openssl s_client -4 -connect files.pythonhosted.org:443
<Replace with your output>
```

#### IPv6 (If available)

```shell
echo -n | openssl s_client -6 -connect pypi.org:443
<Replace with your output>
```

```shell
echo -n | openssl s_client -6 -connect files.pythonhosted.org:443
<Replace with your output>
```

**Comment by di** [comment]
There's no content here. If you're having network issues when using PyPI please run the commands listed and include the output.

**Comment by Yusuf4396** [comment]
> ## My Platform
> ## Network telemetry
> ### DNS Resolution
> ```shell
> dig pypi.org A
> <Replace with your output>
> ```
> 
> ```shell
> dig pypi.org AAAA
> <Replace with your output>
> ```
> 
> ```shell
> dig files.pythonhosted.org A
> <Replace with your output>
> ```
> 
> ```shell
> dig files.pythonhosted.org AAAA
> <Replace with your output>
> ```
> 
> ### Traceroutes
> #### IPv4
> ```shell
> traceroute pypi.org
> <Replace with your output>
> ```
> 
> ```shell
> traceroute files.pythonhosted.org
> <Replace with your output>
> ```
> 
> #### IPv6 (If available)
> ```shell
> traceroute6 pypi.org
> <Replace with your output>
> ```
> 
> ```shell
> traceroute6 files.pythonhosted.org
> <Replace with your output>
> ```
> 
> ### HTTPS Requests
> #### IPv4
> ```shell
> curl -vvv -I --ipv4 https://pypi.org/pypi/pip/json
> <Replace with your output>
> ```
> 
> ```shell
> curl -vvv -I --ipv4 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz
> <Replace with your output>
> ```
> 
> #### IPv6 (If available)
> ```shell
> curl -vvv -I --ipv6 https://pypi.org/pypi/pip/json
> <Replace with your output>
> ```
> 
> ```shell
> curl -vvv -I --ipv6 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz
> <Replace with your output>
> ```
> 
> ### TLS Debug
> #### IPv4
> ```shell
> echo -n | openssl s_client -4 -connect pypi.org:443
> <Replace with your output>
> ```
> 
> ```shell
> echo -n | openssl s_client -4 -connect files.pythonhosted.org:443
> <Replace with your output>
> ```
> 
> #### IPv6 (If available)
> ```shell
> echo -n | openssl s_client -6 -connect pypi.org:443
> <Replace with your output>
> ```
> 
> ```shell
> echo -n | openssl s_client -6 -connect files.pythonhosted.org:443
> <Replace with your output>
> ```
