### ISSUE TITLE
I'm unable to upload a project that doesn't exist on pypi.org

### ISSUE THREAD

**Issue by s1113950** [pypa/warehouse#6831]
I'd like to make a project called `pak`. I checked and that name doesn't exist here:
https://pypi.org/project/pak/

I get an error when I try and upload to pypi:
```
HTTPError: 403 Client Error: The credential associated with user 's1113950' isn't allowed to upload to project 'pak'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
```
Additionally, `pip install pak` doesn't come up with any results.

I found a related ticket: https://github.com/pypa/warehouse/issues/4057 maybe this project name had the same thing happen to it?

**Comment by di** [comment]
This project name exists, but all releases have been deleted. (See also https://pypi.org/help/#project-name)

@jezdez, looks like this project belongs to you, would you be willing to transfer it to @s1113950?

**Comment by jezdez** [comment]
@di Sure thing, will do.

@s1113950 Just added you as owner, feel free to remove me on https://pypi.org/manage/project/pak/collaboration/.

**Comment by s1113950** [comment]
Thanks so much 😄
