### ISSUE TITLE
erpc project admin access

### ISSUE THREAD

**Issue by MichalPrincNXP** [pypa/warehouse#6832]
Hello,
NXP has been administrating the erpc project (https://pypi.org/project/erpc/) using the EmbeddedRpc account aligned with the dusan.cervenka@nxp.com email address. This email address no longer exists, Dusan has left the company and lost the login. Could you please either change the email address of the EmbeddedRpc account to michal.princ@nxp.com and reset the password, or to allow the erpc project administration from my new pypi account MichalPrinc ? Thank you.
Michal Princ, NXP

**Comment by di** [comment]
@MichalPrincNXP, can you make your membership in the https://github.com/embeddedrpc/ Github organization public? I think that should suffice for verifying ownership.

**Comment by MichalPrincNXP** [comment]
Hi @di , I have just made the membership public. Is there any other step I need to do? Thank you.

**Comment by di** [comment]
Hi @MichalPrincNXP, thanks.

I've also contacted `dusan.cervenka@nxp.com` and the message didn't bounce as I expected it to. Ideally I would see a bounce or a response from that address. (Technically according to [PEP 541](https://www.python.org/dev/peps/pep-0541/) we must wait 6 weeks before we can consider an author unreachable.)

Perhaps @DusanCervenkaNXP / @Hadatko can chime in to confirm here instead?

**Comment by Hadatko** [comment]
Hi i am sorry for this inconvinience. I left the company and my email account was deleted. I am confirming that Michal Princ should be new owner of erpc pypy account.

**Comment by di** [comment]
Thanks! I've added `MichalPrinc` as an owner of the project. If you'd like to reclaim the `EmbeddedRpc` user, you'll need to give me another email address, since `michal.princ@nxp.com` is already being used by the `MichalPrinc` account.
