### ISSUE TITLE
HTML templates hardcoded with "en" language attributes

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#6848]
The base template for warehouse pages have the following hardcoded "language" bits:

https://github.com/pypa/warehouse/blob/bc6a10bf5c58332a03e389781546ce963bfee128/warehouse/templates/base.html#L65

https://github.com/pypa/warehouse/blob/bc6a10bf5c58332a03e389781546ce963bfee128/warehouse/templates/base.html#L71-L72

This was noticed in https://github.com/python/pypi-infra/pull/49 and should probably be addressed?

I'm not certain what purpose these have and am not sure how to best address.

**Comment by webknjaz** [comment]
This https://github.com/projectfluent/fluent-web/blob/master/examples/simple.html suggests that `availableLanguages` is a comma-separated list of all locales while `defaultLanguage` should be just `en-US`, I guess.
