### ISSUE TITLE
Generate `mo`-files on build/pre-deploy

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#6849]
Problem
=======

The current way of updating MOs is manual generation and push to Git.

This approach has three downsides:

1) Updates don't appear on the website until somebody remembers to run re-generation.
2) MOs are blobs and updating them in Git all the time is not a good idea because Git is not really designed to store binaries effectively, this causes the Git repo size to grow faster than it should.
3) Strings in PO files get synchronized more or less automatically which leads to a load of translation updates that seemingly get merged but don't get updated on the website causing confusion for anybody who doesn't know how internals operate.

Proposal
========

I think a logical step would be to generate them in some pre-deploy build step, probably in the infra repo. WDYT @ewdurbin?

**Comment by di** [comment]
This was recently fixed by enabling the "Generate MO files" addon in Weblate.
