### ISSUE TITLE
HTTPError: 400 Client Error: File already exists.

### ISSUE THREAD

**Issue by MNGuenther** [pypa/warehouse#6872]
Dear admins,

A newer version of setuptool's find_packages() decided to suddenly package a lot of arbitrary folders when running setup.py.
Unknowingly, I tried to upload that to PyPI as version 0.9.6, which failed as the .tar.gz file size was too large.
I then resolved the issue and tried to re-upload to PyPI.
This failed, because version 0.9.6 was already on there - even though it had said the upload failed.
I then created version 0.9.7, thinking a different version name would make it possible to upload.
But it still crashes even when uploading version 0.9.7, because it iterates through all older versions and version 0.9.6 does not exist anymore (well, it never really existed).
How could this be solved?

Many thanks for your help!

**Comment by di** [comment]
Hi, what's the project name?

**Comment by MNGuenther** [comment]
allesfitter

**Comment by di** [comment]
Looks like you successfully uploaded the built distribution for 0.9.6, but the source distribution failed:

name | version | date | submitted_by | submitted_from | action
-- | -- | -- | -- | -- | --
allesfitter | 0.9.6 | 2019-10-18 00:41:59.678005 | MNGuenther | - | add py3 file allesfitter-0.9.6-py3-none-any.whl
allesfitter | 0.9.6 | 2019-10-18 00:41:59.678005 | MNGuenther | - | new release

> But it still crashes even when uploading version 0.9.7, because it iterates through all older versions and version 0.9.6 does not exist anymore (well, it never really existed).

Do you mean that it's still trying to upload 0.9.6? Can you check which files are in your `dist` directory, and whether you're using the `--skip-existing` flag with `twine`?

**Comment by MNGuenther** [comment]
Brilliant, thanks Di!
The --skip-existing flag jumped over 0.9.6 (which caused the problem, because my local file for that does not match the uploaded file). So, using --skip-existing I was able to successfully upload 0.9.7.
Thanks so much for your quick help!

**Comment by di** [comment]
Great!
