### ISSUE TITLE
Long username overflows on profile page

### ISSUE THREAD

**Issue by di** [pypa/warehouse#6880]
A sufficiently long username overflows on the user's profile page:

<img width="598" alt="Screen Shot 2019-10-18 at 4 06 31 PM" src="https://user-images.githubusercontent.com/294415/67128477-66f7aa80-f1c1-11e9-88d5-b6cc6fadc755.png">

This will become more of a problem once #5944 is resolved and email addresses appear here as well.

**Comment by sargamm** [comment]
I would like to work on this

**Comment by sargamm** [comment]
@di I figured out that the overflow property of the author-profile needs to be changed, what would you like me to add a scrollbar option for the same so that the a longer user name can be seen properly and also an email address if visible(the issue that is being worked upon)?

**Comment by sargamm** [comment]
I have made a pull request #6886 for the same. Please have a look!

**Comment by di** [comment]
I'm not sure adding a scrollbar is the right approach here. For example, this is what Github does:

<img width="523" alt="Screen Shot 2019-10-21 at 11 09 24 AM" src="https://user-images.githubusercontent.com/294415/67222677-68101e00-f3f3-11e9-84e1-9893e99038da.png">

* Full name wraps
* Username wraps
* Email truncates with an ellipsis

I think we probably want to do the same thing here, and I think #5944 can handle truncating the email since that is different behavior.

**Comment by sargamm** [comment]
Okay, so for this I can add the word-wrap property for the required class, and undo the change I made in the overflow property. Does that work?

**Comment by di** [comment]
I think that should work.

**Comment by sargamm** [comment]
I have made changes, please have a look at the pull request

**Comment by sargamm** [comment]
Hi! Sorry for this huge delay, was caught up with my exams and assignments. I was trying to setup the project locally. I am getting an error in the make serve command, it starts with the error - database "warehouse" does not exist. Where is the database "warehouse" being created? How can I resolve this? Please help @di . Thanks!

**Comment by di** [comment]
You need to run `make initdb` first, see the development docs here: https://warehouse.readthedocs.io/development/getting-started/

**Comment by sargamm** [comment]
It worked. Thanks you.
