### ISSUE TITLE
2FA beta user needs account recovery

### ISSUE THREAD

**Issue by ryanjulian** [pypa/warehouse#6896]
I'm a maintainer of several PyPI projects and enrolled in the TOTP beta several months ago.

I wasn't aware there is no recovery process, and factory reset the phone which had my TOTP app for PyPI, and now cannot access my account.

 I apologize for taking up maintainer time because I didn't read  the fine print for the TOTP beta.

Can someone help me with recovery? I've already acquired a USB key to use as my second factor once my account is recovered.

**Comment by ewdurbin** [comment]
Hello @ryanjulian, please email ernest@python.org from the primary email address associated with your PyPI account to get started with account recovery.

**Comment by ryanjulian** [comment]
Problem resolved via github with @ewdurbin . Thanks again!
