### ISSUE TITLE
Recover account: jwplayer

### ISSUE THREAD

**Issue by ksindi** [pypa/warehouse#6901]
I work at JW Player. Unfortunately the maintainer of our [PyPI account](https://pypi.org/user/jwplayer/) left the company and we are not sure what email was used to access the account so that we can recover it.

We maintain a [package](https://pypi.org/project/jwplatform/) there and would like to takeover the account. If you can please provide me the email that would be greatly appreciated.

**Comment by di** [comment]
The email address associated with the account is a personal email address.

If you can make your membership in the https://github.com/jwplayer organization public, I can update the email address to whatever you'd like.

I'd also recommend adding some additional owners to the `jwplatform` project as well besides `jwplayer`.

**Comment by ksindi** [comment]
Thanks @di. Just made it public: https://github.com/ksindi. Can you please update the address to devops@jwplayer.com?

**Comment by di** [comment]
Done, you should have a password reset email in your inbox.

**Comment by ksindi** [comment]
Awesome. Thanks @di! Very much appreciate the quick turnaround.
