### ISSUE TITLE
Ability to create an API token for a not yet created project

### ISSUE THREAD

**Issue by MaxNoe** [pypa/warehouse#6909]
**What's the problem this feature will solve?**

Currently one can only create API tokens for an already existing project or
for *all* current and future projects.
It would simplify new project deployment, if one could create a token for a specific project, that has not yet been uploaded to PyPI.

I tried registering a project with twine, but that is no longer supported with warehouse.

**Describe the solution you'd like**

Add the possibility to create an API token for a specific new project.

**Comment by di** [comment]
Duplicate of #6378.
