### ISSUE TITLE
HEAD requests cause download counts to increase

### ISSUE THREAD

**Issue by jashandeep-sohi** [pypa/warehouse#691]
I know that almost nobody cares about the download statistics, but I believe I've discovered a bug in how downloads are counted.
Doing `HEAD` requests on package files causes the download count to increment.
Everyone knows that the download statistics aren't really reliable to begin with, but I think this exacerbates the problem.

A possible fix might be increment the count only *after* a `GET` request has been fully responded to.

I'm not sure if this bug pertains to the `warehouse` or the old `pypi` project, but I'll post here regardless.

**Comment by dstufft** [comment]
This should not be a problem with the new statistics tooling, we only log files on a ``GET`` request.
