### ISSUE TITLE
pythonhosted.org mentions abandoned domain

### ISSUE THREAD

**Issue by fcalvet** [pypa/warehouse#6940]
Hi,
https://pythonhosted.org/ mentions `https://www.pypi-mirrors.org/`, which is abandoned and squatted by some advertisement.

**Expected behavior**
No reference to an abandoned website or no landing page and redirection to another PyPA website.

**To Reproduce**
1. Go to https://pythonhosted.org/ or https://files.pythonhosted.org/
2. Follow the url supposed to list PyPI mirrors

**My Platform**
Firefox 70, Kubuntu 19.10

**Comment by ewdurbin** [comment]
Thank you for flagging this! It has been updated.
