### ISSUE TITLE
This is about "https://pypi.org" website's loop while trying to either create a new ac or try forget password option.

### ISSUE THREAD

**Issue by PranavBhattarai** [pypa/warehouse#6948]
How can these two happen at the same time?
Either there is no a/c associated with this website Or let me create one. Am I wrong, or this site is stupid!?

![Screenshot from 2019-11-02 20-15-24](https://user-images.githubusercontent.com/32763112/68072754-13847f80-fdb1-11e9-9e86-5532d97017c3.png)

![Screenshot from 2019-11-02 20-13-57](https://user-images.githubusercontent.com/32763112/68072757-1e3f1480-fdb1-11e9-92ff-215c0680e068.png)

**Comment by jamadden** [comment]
Notice that the case of the first letter is different in your examples. Apparently that's a case-sensitive field; I entered 'Prabesh432@gmail.com' on the reset page and it said an email was sent:

> An email has been sent to your registered email address.
> The email contains a link to reset your password. This link will expire in 6 hours.

**Comment by PranavBhattarai** [comment]
> Notice that the case of the first letter is different in your examples. Apparently that's a case-sensitive field.

Even email-address can be sensitive, that new. 
Anyway thanks. I can now login properly.
