### ISSUE TITLE
Release a new version didn't available in pypi webpage and pip cmdline

### ISSUE THREAD

**Issue by ailisp** [pypa/warehouse#6990]
**Describe the bug**
I release 0.1.0 version of a package called `python-rc` yesterday night. And 0.1.1 about 30 minutes ago. However, the 0.1.1 version is only available at https://pypi.org/project/python-rc/0.1.1/ but not https://pypi.org/project/python-rc. If i tried `pip3 install "python-rc==0.1.1"` I got:
```
ERROR: Could not find a version that satisfies the requirement python-rc==0.1.1 (from versions: 0.1.0)
ERROR: No matching distribution found for python-rc==0.1.1
```

I then tried delete 0.1.0 version, because it's broken and 0.1.1 is the first working version. but surprisingly this page still shows 0.1.0:
https://pypi.org/project/python-rc/

but in package managing it's clearly removed:
![image](https://user-images.githubusercontent.com/13259400/68614108-18ae9200-0475-11ea-9897-850510b85f86.png)

**Expected behavior**
0.1.1 version should be available after release. If it's cached or updated not in real time, at least need a way to install 0.1.1 version just after it's release.

**To Reproduce**
Trying release a package of 0.1.0 version. Then release a 0.1.1 version sometime later. 

**My Platform**
```
Linux bo-ubuntu 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Mozilla Firefox 69.0.2
pip: pip 19.3.1 from /home/bo/.local/share/virtualenvs/****/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by jamadden** [comment]
I currently see only 0.1.1. Could you please check again? 

Another project I work on also just experienced what looks like a (CDN?) cache-related issue.

**Comment by di** [comment]
Looks like cache purging might be lagging or delayed.

**Comment by ailisp** [comment]
Thank you a lot! it looks correct now. The last time i checked is when i just submit issue. so it's about 30~40 minute delay.

**Comment by ewdurbin** [comment]
I can confirm we currently have a backlog on the worker queue that processes asynchronous jobs for PyPI such as cache purging. I've increased our worker pool to compensate.

**Comment by ewdurbin** [comment]
I think it's better discussed in it's own issue, but the purge function for our internal XMLRPC cache at https://github.com/pypa/warehouse/blob/2b63adfeafbed7bd92085e82aa3c70f728da96ae/warehouse/legacy/api/xmlrpc/cache/fncache.py#L77-L87 is performing super badly :/

**Comment by ewdurbin** [comment]
#6991 improved the performance of this cache purge job significantly. everything appears to be flowing smoothly again.

Thanks to @ailisp for the report, and @di  for the fix.

**Comment by ailisp** [comment]
Cool! Just confirmed by uploading a new version, and it's immediately
update. Thanks for the prompt fix!
