### ISSUE TITLE
Look at using GitHub Actions for CI

### ISSUE THREAD

**Issue by cooperlees** [pypa/warehouse#7001]
**What's the problem this feature will solve?**
GitHub actions is generally available now and is a very strong CI option.
Documentation: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions
Example Project: https://github.com/pypa/bandersnatch/tree/master/.github/workflows

**Describe the solution you'd like**
- Add in CI to run on GitHub actions and reach 100% parity to what we have today
- Evaluate further possibilities with it's event integration with GitHub itself.
  - E.g. Bots

**Comment by di** [comment]
Is there an advantage here vs. Travis?

**Comment by pradyunsg** [comment]
It's significantly faster AFAICT. For pip's linting CI job:

[GitHub Actions][1]: 1m 28s
[Travis CI][2]: 2m 11s

[1]: https://github.com/pypa/pip/runs/300412899
[2]: https://travis-ci.org/pypa/pip/jobs/611651173

**Comment by jamadden** [comment]
Could the speed just be a result of newness and under-utilization? As more projects adopt it, that advantage could level out or disappear.

**Comment by di** [comment]
Would be nice to also be able to run our tests in the same Docker images we use for prod.
