### ISSUE TITLE
HSTS served on plain HTTP

### ISSUE THREAD

**Issue by scop** [pypa/warehouse#7008]
**Describe the bug**

Strict-Transport-Security header is sent over plain unencrypted HTTP which yields a warning at https://hstspreload.org/?domain=pypi.org:

> Warning: Unnecessary HSTS header over HTTP
> The HTTP page at http://pypi.org sends an HSTS header. This has no effect over HTTP, and should be removed.

**Expected behavior**

No Strict-Transport-Security header over plain unencrypted HTTP.

**To Reproduce**

```
$ curl -sI http://pypi.org | grep -i strict-transport-security
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

**My Platform**

**Additional context**

**Comment by ewdurbin** [comment]
```shell
$ curl -sI http://pypi.org | grep -i strict-transport-security
```

```shell
$ curl -sI https://pypi.org | grep -i strict-transport-security
strict-transport-security: max-age=31536000; includeSubDomains; preload
```
