### ISSUE TITLE
Wording: says "Last released:" for old releases

### ISSUE THREAD

**Issue by hugovk** [pypa/warehouse#7015]
**Describe the bug**

Might not be a bug, more of a language suggestion.

It says, for example, "Last released: Aug 31, 2010" for old releases.

**Expected behavior**

It's a little bit confusing to see "Last released:" when talking about an old release.

Is it possible for an old release to be released again at a later date?

Should it only say "Last released:" for the current release and "Released:" for older ones?

Or just say "Released:" for all releases?

**To Reproduce**

1. Visit https://pypi.org/project/numpy/
-> "Last released: Nov 11, 2019"
2. Visit an older release: https://pypi.org/project/numpy/1.5.0/
-> "Last released: Aug 31, 2010"

**My Platform**

n/a

**Additional context**

n/a

**Comment by hugovk** [comment]
And checking the files page for that example release, shows

* Last released: Aug 31, 2010
* .tar.gz uploaded Sep 15, 2010
* .exe uploaded Aug 31, 2010

![image](https://user-images.githubusercontent.com/1324225/69044723-18c30a80-09fe-11ea-8dbd-ef4dd2b2ac68.png)

* https://pypi.org/project/numpy/1.5.0/#files

So if anything, should "Last released:" be Sep 15, 2010?

**Comment by di** [comment]
Thanks! I think this is valid.

> Or just say "Released:" for all releases?

This is probably the simplest solution.

**Comment by hugovk** [comment]
Please se PR #7243.
