### ISSUE TITLE
Update usage assumptions re: localization

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#7017]
https://warehouse.readthedocs.io/application/#usage-assumptions-and-concepts says:

```Since reads are *much* more common than writes (much more goes out than goes in), we try to cache as much as possible. This is a big reason that, although we have supported localization in the past, `we currently don't <https://github.com/pypa/warehouse/issues/1453>`__.```

We have now [added localization](https://hosted.weblate.org/projects/pypa/warehouse/). Please remove the "This is a big reason" sentence. To do this, update `docs/application.rst`.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by ShraddhaAg** [comment]
Hi. I'm new to the community. I would like to take this up :)

**Comment by brainwane** [comment]
Sounds great! Please go ahead @ShraddhaAg.
