### ISSUE TITLE
Markdown does not work

### ISSUE THREAD

**Issue by JakobDev** [pypa/warehouse#7018]
**Describe the bug**
I had uploadeda package to PyPI. I had set long_description_content_type to text/markdown, but it is displayed as plain text on PyPI. Here are my [package](https://pypi.org/project/minecraft-launcher-lib) and the [Setup.py](https://gitlab.com/JakobDev/minecraft-launcher-lib/blob/master/setup.py).

**Expected behavior**
The text should be displayed as Markdown like all my other Projects who are using almost the same setup.py.

**To Reproduce**
Try to upload to PyPI maybe?

**My Platform**
I use Ubuntu 16.04.

**Additional context**
I had uploaded my library with the following commands:
```
./setup.py sdist bdist_wheel
twine upload dist/*
```

**Comment by di** [comment]
Your `.whl` file was was created with a version of `wheel` that does not know about this metadata field:

```
$ unzip -c minecraft_launcher_lib-0.1-py3-none-any.whl minecraft_launcher_lib-0.1.dist-info/WHEEL | grep Generator
Generator: bdist_wheel (0.29.0)
```

You need `wheel>=0.31.0`:

```
$ pip install -U wheel
```

**Comment by JakobDev** [comment]
@di Thanks
