### ISSUE TITLE
Integrate search design

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#702]
We need a page that will allow users to search via the web UI for projects to aid in the discovery of projects.

**Comment by dstufft** [comment]
#739 implements a very basic version of this, but I know the design will require more features.

**Comment by nlhkabu** [comment]
@dstufft I am going to remove the design tag for this and change the title to 'integrate' search page to indicate that my part is done

**Comment by dstufft** [comment]
This will need things like:

* Faceting
* Sorting
* Pagination
* Number of total results

**Comment by di** [comment]
@dstufft Looks like we already have pagination and total # of results, and #1004 adds sorting by release date.

Are there additional types of sorting we might want to support? Number of downloads might be useful.

For faceting, what else besides "Development Status"?

**Comment by dstufft** [comment]
Number of downloads is a bit interesting, though it'll take some thought maybe. Right now we're regenerating the search index every 15 minutes or so, but in the future I plan to make a full regeneration a rare thing and just have it add/remove stuff from the current index based on what is actually changing. That means there won't be a great "hook" to trigger updating the download counts as downloads happen. That's not an insurmountable thing though, we could either just periodically regenerate the entire index, or have a task that looks for the N oldest projects which were last indexed at least X time ago and reindex those.

I would guess probably ordering by name wouldn't be the worst thing to do.

For faceting, I'm not sure! I guess maybe we want to make it possible to facet on any of the classifier values? That would effectively replace the old browse page then as well as add some real functionality to classifiers.

**Comment by dstufft** [comment]
FWIW, you can see a list of all available classifiers here: https://pypi.python.org/pypi?%3Aaction=list_classifiers

**Comment by nlhkabu** [comment]
The original design specified that each classifier should work as a facet, with only one group being open at a time (https://github.com/pypa/warehouse/issues/755)

![screenshot from 2016-03-06 07-43-32](https://cloud.githubusercontent.com/assets/3323703/13552968/371f45a2-e36f-11e5-819b-9c484b30fb56.png)

On the HTML side, the checkboxes should be nested (see https://github.com/pypa/warehouse/issues/754).

For the ordering, no. of downloads was definitely a consideration when I put together the design...

Another idea is to calculate package 'popularity' by working out how many other packages depend on that package.  Unless this is already how 'relevance' works??

**Comment by dstufft** [comment]
Relevance is a full text search, it doesn't take into account anything special about the fact these are packages which depend on each other.

We can do ordering by download count, it'll just require a bit of extra work to keep that data reasonably refreshed.

The popularity idea will take a bit more effort, in general most packages don't have that information in a way that PyPI can read it, so I'm not sure if it'd be worth it to implement it until that is the case or not.

**Comment by nlhkabu** [comment]
@dstufft given we have a functional search results page now, are you happy to close this issue?
If we want to make any enhancements to what we already have, we can open new issues

**Comment by dstufft** [comment]
Sounds good to me.
