### ISSUE TITLE
Project pages do not display uploaded signatures

### ISSUE THREAD

**Issue by sigmavirus24** [pypa/warehouse#703]
On PyPI, a project (e.g., [txtorcon](https://pypi.python.org/pypi/txtorcon/0.14.0)) will have its signature file displayed along side the uploaded package file. On [Warehouse](https://warehouse.python.org/project/txtorcon/) however, there is no way to download the signature file or even note that it is there or not.

**Comment by Ivoz** [comment]
Might be a mismatch between [`file.has_signature`](https://github.com/pypa/warehouse/blob/master/warehouse/packaging/models.py#L322) in the model and [`file.has_pgp_signature`](https://github.com/pypa/warehouse/blob/master/warehouse/templates/packaging/detail.html#L55) in the view template?

**Comment by sigmavirus24** [comment]
Seems plausible @Ivoz. I think you have the right line of thinking around how a signature should be displayed.
