### ISSUE TITLE
Error for "Natural Language :: Lithuanian" 

### ISSUE THREAD

**Issue by grubert** [pypa/warehouse#7047]
uploading docutils 0.16b to test.pypi fails with 

  Invalid value for classifiers. Error: 'Natural Language :: Lithuanian' is not a valid choice for this field for url: https://test.pypi.org/legacy/

**Comment by jamadden** [comment]
`Natural Language :: Lithuanian` has been added as a classifier to pypi.org and test.pypi.org.

**Comment by grubert** [comment]
many thanks

**Comment by mitya57** [comment]
Can you please also consider adding Basque, Irish and Nepali as natural languages? In snowball project we currently have to blacklist them from the generated classifiers (see the linked MR).

**Comment by pradyunsg** [comment]
@mitya57 Please file a new issue for this request.
