### ISSUE TITLE
django-xhtml2pdf pdf printing error

### ISSUE THREAD

**Issue by roopeshnaik** [pypa/warehouse#7060]
pdf generated using django-xhtml2pdf gives postscript error while printing

**Comment by jamadden** [comment]
Thanks for the report, but this tracker isn't the right place for it. This tracker is just for issues with the software that runs pypi.org. It can't help with packages installed from pypi.org; for that, you'll need to contact the package maintainers. Contact information is often found [on the project page](https://pypi.org/project/django-xhtml2pdf/).
