### ISSUE TITLE
Flag packages with questionable security practices

### ISSUE THREAD

**Issue by richiebful** [pypa/warehouse#7061]
**What's the problem this feature will solve?**
Malicious and insecure packages are a challenge in the open source community. Malicious packages have been removed several times in the last few years. Improved automated auditing techniques would make it easier for security specialists to quickly remove malicious packages. Smart bad actors would be able to use the same test suite, certainly, but it would at minimum allow for the vetting of existing packages. Likewise, this would set up an automated process which could be enhanced over time.

**Describe the solution you'd like**
Python's ```exec()``` function is not secure and may be a good heuristic for finding malicious packages. There may be other additional heuristics that make a package appear more suspicious, and a likely target for manual auditing. Add a badge or other indicator for packages that pass/fail these tests.

**Comment by di** [comment]
Merging this into #5117.
