### ISSUE TITLE
Source tarball not available at "m/mypackage/mypackage-X.X.X.tag.gz" address

### ISSUE THREAD

**Issue by jpgill86** [pypa/warehouse#7070]
My apologies if this isn't the right place to report this issue!

**Describe the bug**

Source tarball for the latest version of my package is not available at the ``m/mypackage/mypackage-X.X.X.tag.gz`` address (the version of the address that does not contain hashes):

https://pypi.io/packages/source/n/neurotic/neurotic-1.2.1.tar.gz

The connection just times out.

**Expected behavior**

The source tarball should be available for download at that address, just as this older version is:

https://pypi.io/packages/source/n/neurotic/neurotic-1.2.0.tar.gz

**To Reproduce**

I'm not sure if this problem is reproducible. All I did was upload a new version of my package to PyPI about 8 hours ago, and it's still not available at the expected URL. I haven't tried uploading another version.

**My Platform**

N/A

**Additional context**

The ``m/mypackage/mypackage-X.X.X.tag.gz`` style URL is used by conda-forge feedstocks (e.g., [this](https://github.com/conda-forge/neurotic-feedstock/blob/b7ac4d7a2ec0442738bb75ca8e37ebfad5802f6a/recipe/meta.yaml#L9)). I discovered this issue when my [pull request](https://github.com/conda-forge/neurotic-feedstock/pull/5) to update my package's feedstock failed all its tests.

I am wondering, has PyPI changed, such that this style of address will not be supported in the future (in which case conda-forge needs to change how they fetch packages for building)? Or was there just a hiccup in my particular case with propagating my tarball to a CDN?

**Comment by ewdurbin** [comment]
This was a crash in our "conveyor" service that translates legacy URLs like `/source/{a-z}/{project-name}/{artifact}` to canonical URLs. The service has been restored. Sorry for the confusion.

**Comment by jpgill86** [comment]
Thanks for the rapid response and fix, @ewdurbin!
