### ISSUE TITLE
Link classifiers in the project description

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#71]
The classifiers need to be linked to some sort of "browse" page.

**Comment by nlhkabu** [comment]
Actually, we're not currently linking to the classifiers at all... Maybe this is something we need to look at.  Perhaps on the 'similar packages' tab??

**Comment by di** [comment]
We can now link to a search for a single classifier like this: https://warehouse.python.org/search/?c=Development+Status+%3A%3A+1+-+Planning

Where would be be linking _from_? An additional tab on the project description page?

**Comment by dstufft** [comment]
This issue was opened before the new design. The new design doesn't list the classifiers anywhere, but it probably should. See #1061.
