### ISSUE TITLE
Error 503 Backend is unhealthy

### ISSUE THREAD

**Issue by plandes** [pypa/warehouse#7101]
**Describe the bug**

I am not able to deploy to [test](https://test.pypi.org/legacy).

**Expected behavior**

Uploading wheel using `twine` failed.

**To Reproduce**

```bash
<PYTHON_BIN> -m twine upload \
  --sign-with <PYPI_SIGN> --username <PYPI_USER> \
  --repository-url <url> <WHEEL>
```

**My Platform**

macOS 10.14.5

**Additional context**

By the end of writing this, test works, but [legacy](https://upload.pypi.org/legacy) has a gateway timeout.

**Comment by ewdurbin** [comment]
PyPI's backends had an outage  that has now been resolved. If you are still experiencing this issue please reopen.
