### ISSUE TITLE
User "pypiname" name-squatting 739 projects

### ISSUE THREAD

**Issue by jkmacc-LANL** [pypa/warehouse#7123]
Hello.  On December 13-14, 2019, the user [`pypiname`](https://pypi.org/user/pipname/) systematically reserved all project name combinations containing two letters or digits.  These packages are empty, nor is there any contact information or project information for any of them.  

I understand that this is a [common problem](https://github.com/pypa/warehouse/issues/4001), and [steps are being taken](https://github.com/pypa/warehouse/issues/3231) to address them.  This, however, seems particularly egregious, and worthy of addressing earlier than the timeline of the ticketing system.

Can this user's projects be removed?

Thank you.

**Comment by ewdurbin** [comment]
Thanks for your report. These projects and this user will be removed.

**Comment by jkmacc-LANL** [comment]
Thank you!
