### ISSUE TITLE
Spam Packages

### ISSUE THREAD

**Issue by gucci-on-fleek** [pypa/warehouse#7125]
Not sure if this is the correct place to report spam, but these packages are definitely spam:
* [adt_phone_number_1-877-346-1604](https://pypi.org/project/adt_phone_number_1-877-346-1604/)
* [quickbookstechsupport](https://pypi.org/project/quickbookstechsupport/)
* [techsupport](https://pypi.org/project/techsupport/)

**Comment by ewdurbin** [comment]
Thanks @gucci-on-fleek. I've confirmed these are spam and removed the projects.
