### ISSUE TITLE
Problem while installing grammar-check

### ISSUE THREAD

**Issue by mcp111** [pypa/warehouse#7153]
While installing grammar-check, I get following error
C:\>pip install grammar-check
ERROR: Could not find a version that satisfies the requirement grammar-check (from versions: none)
ERROR: No matching distribution found for grammar-check

Why?
https://pypi.org/project/grammar-check/#description

**Comment by jamadden** [comment]
(This tracker is for issues with the software that runs pypi.org itself. For user support with packaging problems, please use https://github.com/pypa/pypi-support in the future. Thanks!)

That project has only published Python 2 wheels. I'm guessing you're trying to install using Python 3, so those wheels won't be used. You can verify with pip's `-v` argument:


```console
$ python3 -m pip install -v grammar-check
...
Analyzing links from page https://pypi.org/simple/grammar-check/
  Skipping link: none of the wheel's tags match: py2-none-any:...grammar_check-0.7.3-py2-none-any.whl
…
```

If my guess is wrong, please feel free to open a new issue in the referenced tracker.

**Comment by mcp111** [comment]
So will it work only with python 2?

I tried your command

python3 -m pip install -v grammar-check

but it just comes back to command prompt without doing anything.

I don't get

...
Analyzing links from page https://pypi.org/simple/grammar-check/
  Skipping link: none of the wheel's tags match: py2-none-any:...grammar_check-0.7.3-py2-none-any.whl
