### ISSUE TITLE
Cannot install pip packages

### ISSUE THREAD

**Issue by aryanmediratta** [pypa/warehouse#7164]
I have the same error as in https://github.com/pypa/warehouse/issues/3826 
I can not install any packages without the `--default-timeout=1000` argument. 
Is there any way to do it without that statement?
I am currently using pip version 19.3.1

**Comment by di** [comment]
Hi @aryanmediratta, sorry you're having problems. Per my comment on #3826, please file a [new Network Access issue](https://github.com/pypa/warehouse/issues/new?template=access-issues.md) instead so we can get some additional details about your network environment.
