### ISSUE TITLE
Change hint to "pip3 install maidenhead" on https://pypi.org/project/maidenhead/ . It is a newbie (me) gotcha

### ISSUE THREAD

**Issue by lmckusic** [pypa/warehouse#7167]
Thanks. Great language great library. For the last few years I have been getting Python 3 specific modules from the Ubuntu Debian repository. The "hint" on the maidenhead module main page sent me off in the wrong direction. Thanks again.

**Comment by yeraydiazdiaz** [comment]
Hi @lmckusic, without getting into too much detail whether to use `pip` or `pip3` depends on how your Python interpreter has been installed and configured. PyPI tries to not make any assumptions as to which version of Python the user is running or how it is installed hence the hint reads `pip` as it will work fine if the environment is setup in a typical way.

Here's a newbie friendly tutorial on installing Python on Linux systems: https://docs.python-guide.org/starting/install3/linux/

Good luck!
