### ISSUE TITLE
Recruit users for usability testing

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#717]
I'd like to conduct some basic remote usability testing on the new design prior to relaunch.

For this, we will need to recruit a number of community members to participate in usability testing sessions.  Ideally, the users would come from a variety of backgrounds and be at different levels of expertise, e.g:

*  Absolute beginners who are new to the Python ecosystem and have never used PyPI
*  Users who have never created a package for PyPI
*  Intermediate users who are familiar with PyPI but only use it occasionally
*  Power users who are intimate with PyPI

Volunteers will need to be:

* Available for up to one hour in late November (date TBC)
* Fluent in English
* Using a fast enough internet connection to run Google Hangouts with screen sharing enabled
* Happy to have their user session recorded
* Located in a timezone compatible with GMT

The goal of the sessions will be to identify any major usability problems with the new design.

Participants will be formally credited on the credits page when the new version of PyPI is launched.

If you would like to participate in the user testing, please **do not comment here** - instead, please submit your details at http://bit.ly/1MpAHRm

If you have any experience in conducting or facilitating usability sessions, I would appreciate your input, comments or suggestions below.

**Comment by tmblweed** [comment]
Hi - I'd like to volunteer. What will it take?

**Comment by Carreau** [comment]
I would suggest having a look at https://usabilityhub.com . We do some test for the Jupyter/IPython notebook using mockup, and it works nicely.

See what the [result look like](https://github.com/jupyter/notebook/pull/465#issuecomment-143313927) if you wish.

**Comment by techtonik** [comment]
wargaming.net organizes monthly UX meetups in Minsk, so  once you have something to share, we may arrange onsite session that will also gather some professional feedback. In addition they may release recorded material to tell Python people a little bit more about UX, why it is important and how to deal with that stuff. I think that is important considering that pull requests covering PyPI usability were declined in the past.

**Comment by nlhkabu** [comment]
@techtonik Sounds great! We will let you know when we have something ready to go - I look forward to your feedback.

**Comment by nlhkabu** [comment]
I'm going to go ahead and close this now as we've had lots of volunteers come forward.  I hope to start testing in early december :dancers:

**Comment by pitrou** [comment]
If some volunteers are still desired feel free to ping me. I *think* Hangout screen sharing should work here (Linux), never tried it though.
