### ISSUE TITLE
Wrong installation command for win32gui

### ISSUE THREAD

**Issue by Janis-Leuenberger** [pypa/warehouse#7182]
Hello,

So I was trying to install win32gui and found the command `pip install win32gui` on the [pypi website](https://pypi.org/project/win32gui/#description) not to be working.

In the [README](https://github.com/mhammond/pywin32) of this package it says to use `pip install pywin32`, which worked for me

Am I stupid or needs this to be changed?

**Comment by yeraydiazdiaz** [comment]
Hi @Janis-Leuenberger, this repo is for issues with the code running PyPI.org, the installation command "works" in as much as it will retrieve the correct package from PyPI but we cannot control whether they successfully install the project or not.

That being said the homepage for [`win32gui`](https://sourceforge.net/projects/pywin32/) explicitly reads:

> OLD project page for the Python extensions for Windows 

And its [repo help page](https://sourceforge.net/projects/pywin32/support) reads:

> Python for Windows Extensions says the best way to get help with its software is by visiting https://github.com/mhammond/pywin32. 

Which suggests `pywin32` is really the project you want to install and `win32gui` has been deprecated.
