### ISSUE TITLE
Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/netmiko

### ISSUE THREAD

**Issue by kk348** [pypa/warehouse#7208]
Hi All, facing same error again
'Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/netmiko'

**Comment by jamadden** [comment]
Hi! If you're still having issues, please open an issue in [pypa/pypi-support using the 'Network Access Issue' template](https://github.com/pypa/pypi-support/issues/new?labels=network&template=access-issues.md). If you can fill out as much of the requested information as possible it will help in troubleshooting. Thanks!
