### ISSUE TITLE
HTTP Connection Error

### ISSUE THREAD

**Issue by daffyduck25** [pypa/warehouse#7213]
**Describe the bug**

Receive HTTP connection error.

Error: The Following Error occured: HTTPConnectionPool(host='wordnetweb.princeton.edu', port=80): Max retries exceeded with url: /perl/webwn?s=production (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028D8FE64148>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Expected behavior**

Error does not occur

**To Reproduce**

from PyDictionary import PyDictionary
dictionary = PyDictionary()
(no problem with import or initiating dictionary)

word_check = dictionary.meaning('dark')  #Error is triggered here

**My Platform**

Using code within JupyterLab, Windows10

**Additional context**

Was working yesterday morning then sometime in the afternoon the code would not work.  No known changes to environment or scripting to cause issue.

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself, but you seem to be reporting an issue with `PyDictionary`. This tracker cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (`https://pypi.org/project/<SOME PACKAGE>`).
