### ISSUE TITLE
images are not rendering today (10-Jan-2020). may be an intermittent problem.

### ISSUE THREAD

**Issue by DanielGoldfarb** [pypa/warehouse#7214]
I noticed this morning that images are apparently not rendering.  This appears to have happened before ( https://github.com/pypa/warehouse/issues/6412#issue-479359946 ) and issue is on both https://test.pypi.org and https://pypi.org

All places with images rendered "from elsewhere" are broken.  For example, build stats from Travis CI, and Avitar from gravatar, as well as images in descriptions where the image is hosted on github.

One example (there are many) ... https://pypi.org/project/WORC/  <-- At top of page "Build Status" does not render.    On left side of page, half way down under "Maintainers" the Avatar does not render.

**Comment by DanielGoldfarb** [comment]
Problem is fixed now.   I'm guessing a server issue.  No idea who fixed it or how.

**Comment by alanhamlett** [comment]
This seems to be an issue again. For example [this cached image](https://warehouse-camo.cmh1.psfhosted.org/2ac4c6754c1ce3f20ead7a1d423e1ee718df1507/68747470733a2f2f77616b6174696d652e636f6d2f62616467652f6769746875622f77616b6174696d652f77616b6174696d652e706e67) from https://pypi.org/project/wakatime isn't loading.
