### ISSUE TITLE
Stale documentation on pythonhosted.org

### ISSUE THREAD

**Issue by jtniehof** [pypa/warehouse#7218]
Some time ago we uploaded SpacePy documentation to pythonhosted.org and it's still sitting there ([https://pythonhosted.org/SpacePy/](https://pythonhosted.org/SpacePy/))

With the deprecation of pythonhosted.org I tried to delete the documentation and clicked the "destroy documentation"; I can see this in [the journal](https://pypi.org/manage/project/spacepy/journal/): "docdestroy Jun 22, 2019, 11:52:56 AM".

Unfortunately the old docs are still on pythonhosted.org and they're sadly still the highest-ranked on Google, leading to issues like spacepy/spacepy#270

Any way I can actually get those docs deleted?

**Comment by ewdurbin** [comment]
@jtniehof is there a redirect you'd like in place for the docs once they're removed?

**Comment by jtniehof** [comment]
A redirect to https://spacepy.github.io/ would be awesome. Thanks!

**Comment by ewdurbin** [comment]
👍

**Comment by jtniehof** [comment]
Thank you!
