### ISSUE TITLE
Using the logical/boolean operator AND to search in pypi

### ISSUE THREAD

**Issue by darmuent** [pypa/warehouse#7233]
**What's the problem this feature will solve?**
When searching for a package in pypi with 2 keywords, I get a lot of results most of the time. 
For example, when I type "django excel", I get more than 10.000 results.
This is meant "Show me all results containing 'django' or 'excel'".

**Describe the solution you'd like**
Is it possible to restrict the number of results by an AND-operator so I'll get only the packages containing both keywords 'django' and 'excel'?

**Additional context**
Possible Solutions could be "django + excel" oder "django AND excel" or "(django excel)".

**Comment by yeraydiazdiaz** [comment]
Hi @darmuent, I just tried using quotes around the two terms, i.e. [`"django excel"`](https://pypi.org/search/?q=%22django+excel%22) which returned 17 projects, is that what you're looking for?

**Comment by darmuent** [comment]
Yes, definitly! Please feel sorry for the foolish question.
Thanks and greetings from East Germany
Helmut

**Comment by yeraydiazdiaz** [comment]
No worries, it's not particularly obvious, maybe we should add some text with search term suggestions.
