### ISSUE TITLE
Help page: Github marketplace link for project release notifications broken

### ISSUE THREAD

**Issue by HQupgradeHQ** [pypa/warehouse#7254]
**Describe the bug**

Seems that github changed url scheme on marketplace and this link:`https://github.com/works-with/category/dependency-management?query=python` no longer works.
**Expected behavior**

results for "python" filtered by Dependency management
**To Reproduce**

https://pypi.org/help/#project-release-notifications
link - GitHub apps 
**Additional context**

This link `https://github.com/marketplace?utf8=%E2%9C%93&category=dependency-management&query=python` should be instead.

**Comment by jamadden** [comment]
Thanks for the report! PR's against [the appropriate file](https://github.com/pypa/warehouse/blob/53ab9e3b5851c12c20a75f415303b1930f3042e8/warehouse/templates/pages/help.html#L436) are welcome.

**Comment by Abhi-khandelwal** [comment]
Can I take this issue?

**Comment by pradyunsg** [comment]
@Abhi-khandelwal yep, please go ahead. Feel free to ask questions here, if you have any.

**Comment by yeraydiazdiaz** [comment]
Closed via https://github.com/pypa/warehouse/pull/7302
