### ISSUE TITLE
Storage size Limit

### ISSUE THREAD

**Issue by scrgiorgio** [pypa/warehouse#7263]
When we try to upload https://github.com/sci-visus/OpenVisus artifacts to PyPi we get the following:

Found artifact 'build\Release\OpenVisus\dist\OpenVisus-1.3.69-cp37-none-win_amd64.zip' matching 'build\Release\OpenVisus\dist\*.zip' path
Uploading artifacts...
The maximum allowed artifact storage size of 50000 Mb will be exceeded.

Is it possible to increase the max file size to 100MB?
Thanks.

**Comment by jamadden** [comment]
Please open an issue at pypa/pypi-support using the [limit increase template[(https://github.com/pypa/pypi-support/issues/new?labels=limit+request&template=limit-request.md).

**Comment by di** [comment]
@scrgiorgio What are you using to upload to PyPI? That message is incorrect and should probably be fixed (the current limit is 60MB).

**Comment by scrgiorgio** [comment]
Hi and thanks for your email.
I just got the message from AppVeyor trying to upload a file to pypi.
Would it be possible to make that limit a little higher? I think it could
be I'm little more that 60MB on windows.
Thanks.
