### ISSUE TITLE
Classifier filtering is broken

### ISSUE THREAD

**Issue by di** [pypa/warehouse#7279]
Filtering by classifier is broken, e.g.

https://pypi.org/search/?q=&o=&c=Programming+Language+%3A%3A+PHP

returns results for projects without this classifier.

**Comment by di** [comment]
This may be due to #6118 (cc @yeraydiazdiaz).

**Comment by yeraydiazdiaz** [comment]
Yep, if there is no querystring we're returning a query _before_  applying the classifiers prefix.

https://github.com/pypa/warehouse/pull/6118/files#diff-ea534290c5e1ad62dad34713414810a6R55-R56

Should have fix soon.
