### ISSUE TITLE
Recruit technical writer(s) to write new tutorials

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#729]
One of the key objectives of the new design is to make it much easier for beginners to understand how to install and create packages.

To facilitate this, we'd like to create two new tutorials to compliment the content already available at [packaging.python.org](http://packaging.python.org).

The first tutorial would be a step-by-step guide for installing your first Python package.  It should describe what packages are, how they work, and best practices for installation and management.  The language should be friendly and simple, and no prior knowledge of packaging or Python development should be assumed.

The second would be a step-by-step guide for packaging and uploading your first Python package - here we can assume that the reader is more experienced, though the instructions should still be clear and concise.

Each tutorial should provide basic instructions and frequently link back to the [full package reference](http://packaging.python.org) for more detailed information.  It is also very important that the tutorial remains consistent with this resource.

To assist in this task, we're looking for a technical writer, group of writers or developers who can work with us to write the tutorials.  Ideally, we'd like to get a first version of the tutorials up within the next month, so that we can include them in our usability testing sessions (see #717).

Writers will be formally credited on the credits page of the new PyPI when it is released.

If this is something you are interested in please **do not comment below** - instead, contact Nicole Harris at n.harris [at] kabucreative.com

If you have ideas on what you'd like to see in the tutorials, or examples of great tutorials we can look to for inspiration, please **do** comment below!

**Comment by souravsingh** [comment]
I would like to work on this

**Comment by nlhkabu** [comment]
We've had lots of great writers volunteer to help us, so I'm going to go ahead and close this issue.  Thanks to everyone who spread the word.

**Comment by brainwane** [comment]
Did this turn into https://github.com/pypa/python-packaging-user-guide/tree/master/source/tutorials ? Thanks!

**Comment by rangaomkaram** [comment]
I want to contribute the documentation of the tutorial in this project.  Can I contribute in any way according to contributing guidelines? I have previous experience in blog/article writing for the python modules.
