### ISSUE TITLE
Request trove classifier

### ISSUE THREAD

**Issue by salmaShahid** [pypa/warehouse#7290]
can anyone tell me how to permanently delete project from pypi.org
while uploading package it will generate error 
`HTTPError: 400 Client Error: This filename has already been used, use a different version. See https://test.pypi.org/help/#file-name-reuse for url: https://test.pypi.org/legacy/

`

**Comment by di** [comment]
PyPI does not allow for the reuse of distribution filenames (project name + version number + distribution type).

This ensures that a given distribution for a given release for a given project will always resolve to the same file, and cannot be surreptitiously changed one day by the projects maintainer or a malicious party (it can only be removed).

You will need to change the version number to one that you haven't previously uploaded to PyPI.

**Comment by salmaShahid** [comment]
Thank You Sir!
Sir can you plz tell me why my package (which i already uploaded on pypi account)
not shown in the list of pycharm available packages
![pr](https://user-images.githubusercontent.com/51890862/73009463-70cd2180-3e32-11ea-93a9-5a4cf1f312d2.PNG)
![pr2](https://user-images.githubusercontent.com/51890862/73009464-70cd2180-3e32-11ea-8b98-1e598583a9f8.PNG)
![pr3](https://user-images.githubusercontent.com/51890862/73009465-7165b800-3e32-11ea-97a5-473cacda7b64.PNG)

**Comment by di** [comment]
This seems like a PyCharm issue, I'd recommend contacting support.
