### ISSUE TITLE
Intermittent certificate problems with files.pythonhosted.org

### ISSUE THREAD

**Issue by hartzell** [pypa/warehouse#7309]
**Describe the bug**

Briefly, various folks are having intermittent problems with certificate verification when connecting to files.pythonhosted.org.

Gory details are recorded in this [pip issue](https://github.com/pypa/pip/issues/7663).  I'm happy to cut and paste it all here, but....

One possible explanation is a recent change in certificates or configuration on the Fastly CDN network that supports files.pythonhosted.org.

@uranusjr suggested getting in touch with the PyPi folks, so I am.

**Comment by hartzell** [comment]
There's also something funny going on with the test case I'm using on my Mac to debug this but folks are also reporting the issue on [CentOS](https://github.com/pypa/pip/issues/7663#issuecomment-579125480) and [Windows](https://github.com/pypa/pip/issues/7663#issuecomment-579505092).

Here's a question I've asked on [StackExchange](https://apple.stackexchange.com/questions/380806/openssl-claims-to-use-private-etc-ssl-but-appears-not-to-what-the-heck) to try to understand how my Mac's behaving.

**Comment by ewdurbin** [comment]
Best immediate guess in reviewing the details from that ticket is that something has flagged either files.pythonhosted.org or dualstack.r.ssl.global.fastly.net, or r.ssl.global.fastly.net... etc as something worthy of blocking.

Based on the certificates and IP addresses in the pip ticket, which more or less match the contents of this help article: https://support.opendns.com/hc/en-us/articles/227986927-What-are-the-Cisco-Umbrella-Block-Page-IP-Addresses-

**Comment by ewdurbin** [comment]
I have no way to confirm this, as I don't have access to an OpenDNS/CiscoUmbrella network.

I'm also not positive if this is something that is "per install" of this product or if there is some global block list.

**Comment by hartzell** [comment]
Thanks for thinking about this.

It's not simply blocked, as the error we're seeing is a certificate verification problem.  Perhaps something along the way is doing some Man In The Middle shenanigans that are screwing up the certificate.  But, it's weird that I have a failing test case that I can "rescue" by providing an explicit path to a cert. file.

**Comment by ewdurbin** [comment]
It's rather muddy, the first two reports are clearly related to Cisco Umbrella (the initial report has it right there in the `CN` of the certificate that it read, and dns resolves to Cisco IPs).

I'm having a hard time assessing the status on yours though on closer inspection.

**Comment by hartzell** [comment]
Yes, I appear to be tripping over a known issue with the implementation of `s_client`: https://security.stackexchange.com/a/142172.  Credit to Jivan Pal for finding it and pointing me to it in this StackExchange discussion: https://apple.stackexchange.com/questions/380806/openssl-claims-to-use-private-etc-ssl-but-appears-not-to-what-the-heck

**Comment by epilif1017a** [comment]
@ewdurbin @hartzell I was able to get in touch with netops and we solved the problem. 

Indeed the solution was: **"whitelist files.pythonhosted.org under Cisco Umbrella Portal."**

So apparently the host it's flagged by default and needs to be whitelisted on a per need basis :S very strange that this is flagged in CISCO Umbrella.

**Comment by ewdurbin** [comment]
@epilif1017a Thanks for looking into it!

**Comment by ewdurbin** [comment]
@epilif1017a is there any way for you to determine if the flagging by default is from Cisco itself or from an internal policy?

**Comment by epilif1017a** [comment]
@ewdurbin at first I've been told that it is internal policy, but last week everything worked fine, so I'll double check again, and definitely I wouldn't rule out the possibility of a default CISCO policy after an update to the Umbrella tool.

**Comment by epilif1017a** [comment]
@ewdurbin not the first "incident" apparently

https://community.cisco.com/t5/cloud-security/umbrella-breaks-files-pythonhosted-org/td-p/3688704

**Comment by ewdurbin** [comment]
Closing this, as there isn't anything actionable that PyPI can do if a device is being "Man in the Middle"'d by their network provider or corporate IT.

Will continue discussion on the pip ticket.

**Comment by jrgreenberg** [comment]
I recently encountered this with my newly installed Umbrella roaming client (mac Catalina). Additional content is that I can access the file if I paste the file path into a Chrome browser. When trying to access via the pip install command from the CLI, it fails due to the SSL Certificate. I also try to CURL the file path from the CLI and receive the same SSL certificate error. Had to hunt this down a bit and thought I would add a little context for the next person that encounters this.
