### ISSUE TITLE
Large white gap to the right on Chrome on Android

### ISSUE THREAD

**Issue by kirbyfan64** [pypa/warehouse#731]
![Large white gap](http://s5.postimg.org/dlf4c5efb/Screenshot_20151021_130849.png)

**Comment by dstufft** [comment]
I'm going to close this, not because this isn't a real issue (it probably is, I don't have an android!) but because the current "design" is just a transitional thing to make it possible to implement the views until the new redesign is ready to land in the main repository.

**Comment by kirbyfan64** [comment]
@dstufft FYI, usually, Chrome's [mobile emulation mode](https://developer.chrome.com/devtools/docs/device-mode) lets you see how it'd work on Android...

**Comment by dstufft** [comment]
Oh sure. Just saying I'm not super worried about to because it's all going to go away with the new design anyways.
