### ISSUE TITLE
pip (pip3) fails to install GDAL: macOS Catalina, python 3.8.x

### ISSUE THREAD

**Issue by OldSubSailor** [pypa/warehouse#7319]
I have tried using 'install DGAL' with and without version numbers (which cant be found) and gives a fairly short response in Terminal:

```
Last login: Thu Jan 30 10:49:53 on ttys000
But what do I know? % pip3 install GDAL 3.0.4 
Collecting GDAL
  Using cached GDAL-3.0.4.tar.gz (577 kB)
ERROR: Could not find a version that satisfies the requirement 3.0.4 (from versions: none)
ERROR: No matching distribution found for 3.0.4
```
But what do I know? % 

If I use pip3 install GDAL I get a huge terminal window full of messages. 
[pip install error .txt](https://github.com/pypa/warehouse/files/4135189/pip.install.error.txt)

**Comment by OldSubSailor** [comment]
I have no idea as to why my post above is so big and bold

**Comment by jamadden** [comment]
Writing `pip3 install A B` asks pip to install both library A and library B. It does not ask pip to install version B of library A. If you want that , you write `pip3 install A==B`. So the error message `No matching distribution found for 3.0.4` is telling you that there is no library named `3.0.4` to install.

As for the rest of the errors, you'll need to contact the maintainers of the `GDAL` library. This tracker is just for the software that runs pypi.org itself; it generally cannot help with issues for libraries downloaded from there.

**Comment by OldSubSailor** [comment]
I have tried to contact them also. There are also issues there.
