### ISSUE TITLE
Get rid of all "analytics" malware.

### ISSUE THREAD

**Issue by KOLANICH** [pypa/warehouse#7331]
The trackers scripts are loaded (in fact tried to be loaded) from thkrd-party domainss even if I disagree with tracking.

DNT is not an option here:
* it is inefficient, trackers are not required to abide it;
* it is harmful and already used for browser fingerprinting;
* it is going to be removed from browsers.

**Comment by di** [comment]
The scripts we load from third party-domains are:

* Raven JS - this is for reporting errors/exceptions on the frontend
* Fastly Insights - this is for diagnosing issues with our CDN
* Google Analytics - this is for understanding what browsers, platforms and features our users use so we can prioritize the limited amount of support and accessibility work we can perform

All of these tools are crucial for PyPI to continue to exist, and we have no plans to remove any of them at this time.
