### ISSUE TITLE
Get rid of html-include.js

### ISSUE THREAD

**Issue by KOLANICH** [pypa/warehouse#7332]
**What's the problem this feature will solve?**
`html-include.js` `fetch`es HTML and inserts it into DOM. It is like JS `eval`. Mere presence of it undermines security by making the code harder to audit.

**Describe the solution you'd like**
Remove it and stop using it.

**Comment by di** [comment]
We need to be able to do client-side includes in order to maximize our ability to cache common pages. Not doing this would mean that any page that has something like the logged-in indicator would not be cacheable.
