### ISSUE TITLE
Some version metadata wrong

### ISSUE THREAD

**Issue by thatch** [pypa/warehouse#7364]
**Describe the bug**

Some archives are listed in sections that do not match the versions in their filenames or contained metadata.

**Expected behavior**

Take chaospy==2.1.1 or geminisqlite==0.11.0 or pistorms==1.7 for example.  This contains several files whose names are consistent with their PKG-INFO, but those are not the release they're listed on for pypi (the [Release history](https://pypi.org/project/chaospy/2.1.1/#files) and [json api](https://pypi.org/pypi/chaospy/json) are wrong in the same way).  Here's a snippet for chaospy.

```
    "2.1": [
      {
        ...
        "filename": "chaospy-2.1.1-py2.py3-none-any.whl",
        ...
      }
    ],
    "2.1.1": [
      {
        ...
        "filename": "chaospy-2.1.2-py2.py3-none-any.whl",
        ...
      },
      {
        ...
        "filename": "chaospy-2.1.3-py2.py3-none-any.whl",
        ...
      },
      {
        ...
        "filename": "chaospy-2.2.0.tar.gz",
      },
```

**To Reproduce**

I can do a more exhaustive check, but this appears to affect at least dozens of projects with file upload dates 2009-2015.

**Comment by di** [comment]
Thanks for the report! Given that date range, my guess would be this was a bug in [pypa/pypi-legacy](https://github.com/pypa/pypi-legacy) which no longer exists.

As a general principle, we don't usually make edits to releases once they're published (even if they're incorrect). Since this seems to affect a small amount of relatively old releases, I'm inclined to say that there's nothing to do here, but if this is affecting a large amount of users or has recently regressed for some reason, we can definitely look into it more.

Also, I'm curious: how did you discover this?

**Comment by thatch** [comment]
I discovered it while writing a testing a script that finds the likely git tag that corresponds with an sdist.  It told me that urllib3 version 0.2's sdist was actually a perfect match for the tag 0.3, and I started digging from there.  In that case, serial `141123` records the 0.3 sdist being added to version 0.2.

An upper bound is about 2000 files assigned to the wrong release (I haven't fetched them all to check yet), and a spot check of the ones that are wrong in 2019 shows they're from people manually renaming files, not this issue.  I

It's unfortunate that the json api will be returning incorrect data for these, but I presume that there's not any existing codepath to reassign a file to a different version, and this would be manual database edits (and some kind of synthesized changelog entry).  I can work around this by parsing filenames again, but *not* having to parse filenames and getting `requires_dist` were the reasons I was going to use the json api.

**Comment by di** [comment]
Thanks again for the detailed comment.

Given that, I'm going to say that while this is unfortunate, we won't be making any changes here due to the small number of cases, limited benefit, and our lack of ability to actually do this without a bunch of manual database munging.
