### ISSUE TITLE
imblearn Installed successfully, but import failed,ModuleNotFoundError: No module named 'sklearn.neighbors._base'

### ISSUE THREAD

**Issue by kaixian5639** [pypa/warehouse#7371]
![image](https://user-images.githubusercontent.com/41986821/74140585-49e35d80-4c30-11ea-91e2-e1b462752a74.png)

Hello friends，
I have a strange problem that **imblearn module  Installed successfully, but import failed，show：
ModuleNotFoundError: No module named 'sklearn.neighbors._base'**

I guess 'sklearn.neighbors._base' may be 'sklearn.neighbors.base', is that no underline before 'base' word？

please help me ，how to solve it ？ 
thank you ！

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (https://pypi.org/project/imbalanced-learn/).
