### ISSUE TITLE
Project uploaded but can't be found on https://pypi.org/simple/

### ISSUE THREAD

**Issue by leveque** [pypa/warehouse#7384]
I've uploaded a package with twine and it can be found with pip search or search form on pypi.org but it's not shown on https://pypi.org/simple/.

I was wondering if there was something more to do, some wait or if it's a bug.

**Comment by ewdurbin** [comment]
@leveque, the listing on /simple/ is heavily cached and new projects can take up to 24 hours to appear. was the project added recently?

**Comment by leveque** [comment]
Yes, less than 24 hours, good to know.

**Comment by leveque** [comment]
Now it's in, thank you for the information.
