### ISSUE TITLE
Unable to provision TOTP

### ISSUE THREAD

**Issue by ocefpaf** [pypa/warehouse#7385]
**Describe the bug**

Cannot activate two-factor authorization using the Google Authenticator App. After scanning the QR code and typing the code to validade it I get: "Invalid TOTP code"

**Expected behavior**

Enable two-factor Auth.

**To Reproduce**

Try to activate 2FA using with Google Authenticator App.

**My Platform**

**Additional context**

I had 2FA working, it stopped and even though I regained access to my PyPI account I cannot enable it again. Removing and re-installing the App did not work.

xref.: https://github.com/pypa/pypi-support/issues/178

**Comment by di** [comment]
Hi @ocefpaf, are you still able to reproduce this? Just to confirm, you are not trying to use 2FA from PyPI on TestPyPI or vice versa, correct?

**Comment by ocefpaf** [comment]
> Hi @ocefpaf, are you still able to reproduce this?

Yep. Still does not work.

> Just to confirm, you are not trying to use 2FA from PyPI on TestPyPI or vice versa, correct?

I'm pretty sure I'm not, here are a few pics just in case:

![Screenshot from 2020-02-27 09-14-27](https://user-images.githubusercontent.com/950575/75444314-fbc59e00-5941-11ea-9748-02759f6429f0.png)

![Screenshot from 2020-02-27 09-15-31](https://user-images.githubusercontent.com/950575/75444318-fcf6cb00-5941-11ea-9f57-ecb3feea4f34.png)

That's the code I get from the app when I scan the QR code.

Note that I had 2FA before and it worked for a while. At some point I had this problem and it prevented me from using my PyPI account. My access was restored with a reset but I'm still unable to use 2FA again. I cleaned the app cache, removed and reinstalled, tried from another phone... Nothing worked.

**Comment by di** [comment]
Hi @ocefpaf, can you confirm that the time on your mobile device is in sync? In the authenticator app, you can go to "Menu" -> "Settings" -> "Time correction for codes" -> "Sync now" to check the clock on your device.

**Comment by ocefpaf** [comment]
I do recall doing that before and it did not work. However, it did work now :-/

Let's close this then. Thanks for all the help!

**Comment by avivajpeyi** [comment]
Hey -- i seem to have the same issue... I've tested with both authy, google authenticator + Microsoft authenticator

![Screenshot from 2023-10-06 13-45-59](https://github.com/pypi/warehouse/assets/15642823/5f18b782-81b5-4235-aa55-544e403377b3)

This is my user account
https://pypi.org/user/avi_vajpeyi/

Any suggestions? 

(I tried the 'Time sync' option for the google authenticator app, i got a message stating "... in sync with Google servers")

**Comment by patel999jay** [comment]
> Hey -- i seem to have the same issue... I've tested with both authy, google authenticator + Microsoft authenticator
> 
> ![Screenshot from 2023-10-06 13-45-59](https://user-images.githubusercontent.com/15642823/273075546-5f18b782-81b5-4235-aa55-544e403377b3.png)
> 
> This is my user account https://pypi.org/user/avi_vajpeyi/
> 
> Any suggestions?
> 
> (I tried the 'Time sync' option for the google authenticator app, i got a message stating "... in sync with Google servers")

i have the same issue, could not do it with authy, google authenticator and/or Microsoft authenticator.

**Comment by miketheman** [comment]
<img width="650" alt="Screenshot 2023-10-06 at 16 52 03" src="https://github.com/pypi/warehouse/assets/529516/2b19036f-41d5-4cf4-81a6-805235ff2ee0">
