### ISSUE TITLE
Leftover project name after project deletion

### ISSUE THREAD

**Issue by S0mbre** [pypa/warehouse#7414]
**Describe the bug**
After removing a project completely from PyPI ("pycrossword"), the deleted project's name is still found by the search engine as existing (most probably because the internal database doesn't reindex immediately on project removal). Such behavior doesn't allow me to re-upload the updated package with that project name, for PyPI 'sees' the project as still in existence.

*Searching for 'pycrossword' reveals 1 active project...*
![11](https://user-images.githubusercontent.com/5337394/74894288-9bcf7480-53e2-11ea-89b6-e9a86da629b5.PNG)

*...which when clicked produces Error 404*
![12](https://user-images.githubusercontent.com/5337394/74894296-a2f68280-53e2-11ea-9185-629c09cdf60a.PNG)

**Expected behavior**
I expected PyPI to free the project name automatically immediately on deleting the project from my projects, since no other project with that name exists.

**To Reproduce**
1. Deleted the "pycrossword" project from My Projects.
Currently, I've got no projects:
![13](https://user-images.githubusercontent.com/5337394/74894373-e3ee9700-53e2-11ea-8a6f-7eba70144966.PNG)

2. Try to upload the "pycrossword" package:
```bash
python -m twine upload --verbose -u __token__ -p <MYAPITOKEN> <DIST>
```

3. `twine` aborts saying:
> 400 This filename has already been used, use a different version. 
> See https://pypi.org/help/#file-name-reuse
![14](https://user-images.githubusercontent.com/5337394/74895014-a4c14580-53e4-11ea-9184-33a21546f1e6.jpg)

**Comment by di** [comment]
PyPI has deleted the project, and the search cache had a bit of delay.

If you'd like to publish a new version of the package, you'll need to increment the version number. Even if you've deleted the project, you can't reuse previously used versions for a given distribution type.
