### ISSUE TITLE
Installation errror using pip/manually

### ISSUE THREAD

**Issue by kappafix** [pypa/warehouse#7415]
**Describe the bug**
During the install ov the version "striprtf-0.0.7"using pip or also manually there's a syntax error into setup.py that stops the installation:
the error is at the line:
download_url=f"https://github.com/joshy/striprtf/archive/v{about['__version__']}.tar.gz",
I solved the problem as followings:
download_url=r"https://github.com/joshy/striprtf/archive/v{about['__version__']}.tar.gz",
and installing manually.
Thaks guys, very good library.

**Comment by di** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page.
