### ISSUE TITLE
Changing "order by" does not reorder packages selected by classifier

### ISSUE THREAD

**Issue by Zac-HD** [pypa/warehouse#7439]
**Describe the bug**
https://pypi.org/search/?q=&o=-created&c=Framework+%3A%3A+Hypothesis is not ordered by date.

**Expected behavior**
When "order by: date last updated" is selected, packages are ordered from most recently to least recently updated.

**Additional context**
On my desktop (chrome) changing the order-by does not reorder packages at all; on mobile it does but the date-order is still wrong.  

It's unclear how "relevance" or "trending" are meant to order packages, but e.g. Hypothesis itself doesn't rank highest for the Hypothesis framework classifier and similarly for Pytest and Flake8.

When the filtered list is long enough to be paginated, the ordering is inconsistent between pages and this leads to missing and repeated packages.

**Comment by di** [comment]
@yeraydiazdiaz, can you take a look?
