### ISSUE TITLE
Not allowed to upload

### ISSUE THREAD

**Issue by jpcaram** [pypa/warehouse#7451]
I'm attempting to upload a project called "jibe", which does not appear to exist, but it fails with 404 user not allowed. Can you please help?

**Comment by di** [comment]
The project exists, but has no releases. Please file a PEP 541 request at https://github.com/pypa/pypi-support/issues/new/choose

**Comment by jpcaram** [comment]
Thanks for looking that up. The PEP 541 submitted: https://github.com/pypa/pypi-support/issues/230
