### ISSUE TITLE
When running python file: mapping[f'{pred}/{len(args)}'].add(args)

### ISSUE THREAD

**Issue by A-xiong** [pypa/warehouse#7458]
**Describe the bug**
When I run an example from the official website, I get the error:
Traceback (most recent call last):
  File "/home/axiong/PycharmProjects/ASP/clyngor/test1.py", line 1, in <module>
    from clyngor import ASP,solve
  File "/home/axiong/PycharmProjects/ASP/venv/lib/python3.5/site-packages/clyngor/__init__.py", line 5, in <module>
    from clyngor.answers import Answers, ClingoAnswers
  File "/home/axiong/PycharmProjects/ASP/venv/lib/python3.5/site-packages/clyngor/answers.py", line 293
    mapping[f'{pred}/{len(args)}'].add(args)
                                ^
SyntaxError: invalid syntax  

**Expected behavior**
 Should work. 

**To Reproduce**
I used pycharm and created a new python file:
```
from clyngor import ASP,solve
answers = ASP("""
rel(a,(c;d)). rel(b,(d;e)).
obj(X):- rel(X,_) ; rel(X,Y): att(Y).
att(Y):- rel(_,Y) ; rel(X,Y): obj(X).
:- not obj(X):obj(X).
:- not att(Y):att(Y).
""")
for answer in answers:
    print(answer)
``
**My Platform**
ubuntu16.04; python3.5

**Additional context**
I found the following: ~/site-packages/clyngor/answers.py.
Question code on line 293:
`mapping[f'{pred}/{len(args)}'].add(args)`
I changed the code to:
`mapping['{pred}/{len(args)}'].add(args)` .
This will run the code. But I'm a freshman, and I don't know what the consequences will be.

**Comment by ewdurbin** [comment]
Hello @A-xiong. This issue tracker is for issues with the warehouse codebase behind PyPI itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the clyngor project itself at https://github.com/aluriak/clyngor

**Comment by A-xiong** [comment]
Thanks very much!
