### ISSUE TITLE
Update "how to request a trove classifier change" help

### ISSUE THREAD

**Issue by story645** [pypa/warehouse#7463]
**Describe the bug**
The link in https://pypi.org/help/#new-classifier to trigger a new trove classifier yields an empty template opened on warehouse:
![image](https://user-images.githubusercontent.com/1300499/75516854-56570c80-59cb-11ea-8b54-3cc3033f5b53.png)

**Expected behavior**
1. The template should have the following fields since this is what's always requested:
    * name of the requested classifier 
    * a brief justification of why it is important. 
2. the issue should probably be opened on pypi-support since that's where the issue is immediately moved to

**To Reproduce**
https://github.com/pypa/warehouse/issues/new?title=Request+trove+classifier&template=new-trove-classifier.md 

attn: @brainwane xref: #3231

**Comment by di** [comment]
We moved the repo for these requests, it should link to https://github.com/pypa/pypi-support/issues/new?labels=classifier+request&template=new-trove-classifier.md&title=Trove+Classifier+Request instead.

**Comment by di** [comment]
Once https://github.com/pypa/warehouse/pull/7582 is merged, we'll actually want to update this to direct users to create a PR at https://github.com/pypa/trove-classifiers instead.

**Comment by pradyunsg** [comment]
@di Any reason to not start redirecting requests to that repository already? Given that there's concensus already that we'd want to switch to using the library in warehouse.

**Comment by di** [comment]
Yeah, I'd like to at least get some reviews on #7582 first, to make sure that's headed in the right direction.

**Comment by brainwane** [comment]
Now that we have merged #7582 I do think redirecting requests to https://github.com/pypa/trove-classifiers is the right move (plus updating https://pypi.org/help/#new-classifier ).
