### ISSUE TITLE
Add "Sign in with Google" account option 

### ISSUE THREAD

**Issue by Donboscow** [pypa/warehouse#7486]
Add "Sign in with Google" account option in your website

**Comment by di** [comment]
Hi @Donboscow, thanks for the feature request. We used to have various OAuth sign-in options with legacy PyPI, however we opted to remove them for two reasons:

1) they were infrequently used and the small number of users did not justify the maintenance burden;
2) they cannot be used to upload packages with tools like [twine](https://pypi.org/project/twine/).

Given that, we don't have any plans to add them back at this time, so I'm going to close this issue. Thanks again for taking the time to make a feature request though!
