### ISSUE TITLE
Cant delete pypi project

### ISSUE THREAD

**Issue by rosscdh** [pypa/warehouse#7495]
**Describe the bug**
Trying to delete my pypi project rosscdh/argo-workflows-dsl

**Expected behavior**
Trying to delete the project to return ownership to the original owner.

**To Reproduce**
https://pypi.org/manage/project/argo-workflows-dsl/settings/

Go through delete project process.. settings delete enter project name
Errors out 404 project not found (but the project still exists).

**My Platform**

**Additional context**

**Comment by ewdurbin** [comment]
Thanks @rosscdh this is related to #2745. It appears that you added your own user as a Maintainer on the project (you implicitly become Owner of projects that you create).

I've cleaned up the errant record and you should be able to delete your project now.

**Comment by rosscdh** [comment]
@ewdurbin thanks for that!
