### ISSUE TITLE
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText.

### ISSUE THREAD

**Issue by robml** [pypa/warehouse#7509]
**Describe the bug**

I constantly encounter the following error when I try to upload to PyPi using twine (the log in credentials I use are correct, I have checked many times).

HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/

**Expected behavior**

From the documentation I should be able to have uploaded the package without a problem.

**Additional context**

The package I have been trying to upload is posted on my github:

https://github.com/robml/django_dbaccounting

**Comment by di** [comment]
What's the output of `twine check dist/*`?

**Comment by robml** [comment]
Hey @di, there was some markup error with the Title overline being too short. Looked it up and edited it. The problem turned out to be that some of the files were not in the package folder needed for setup. Needless to say, resolved it. Thanks for the tip! (Note however I am still unable to upload to the test server, only the official one, but I have raised that as a separate issue as #7510.
