### ISSUE TITLE
HTTPError: 403 Client Error: Invalid or non-existent authentication information. (On Test PyPi)

### ISSUE THREAD

**Issue by robml** [pypa/warehouse#7510]
**Describe the bug**

I have followed the tutorial on packaging.python.org to upload my project onto the Test repository for PyPi using an API token. Yet I get the following error:

HTTPError: 403 Client Error: Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for details for url: https://test.pypi.org/legacy/

**Expected behavior**

To have uploaded to the test repository.

**To Reproduce**

I created an API token on the Test PyPi (not the regular one), and followed the instructions on packaging.python.org

**Additional context**

The related package I am trying to upload is on github:

https://github.com/robml/django_dbaccounting

**Comment by di** [comment]
Can you confirm that you're using the username `__token__` and that the password is the full API key starting with `pypi-`? Are you specifying this on the command line or via a `.pypirc` file?

**Comment by di** [comment]
Closing due to lack of response. Feel free to comment if you're still having this issue.
