### ISSUE TITLE
Where can I find a binary package for django-jet==1.0.8?

### ISSUE THREAD

**Issue by vseavello** [pypa/warehouse#7512]
Installing django-jet using the --only-binary=:all: option fails with 

  Could not find a version that satisfies the requirement django-jet==1.0.8 (from versions: )
  No matching distribution found for django-jet==1.0.8

When removing this option the installation completes. 

We are intending on installation of django-jet on a production system. Installing binary only facilitates building a stable and maintainable platform. A binary distribution of django-jet2 is available, but it doesn't appear that one is available for django-jet. 

Can you point me at a binary distribution, or make one available for installation?

**Comment by yeraydiazdiaz** [comment]
Hello @vseavello, this repo is only for issues related to the codebase that runs pypi.org, the appropriate place for your question would be the [`django-jet` repo](https://github.com/geex-arts/django-jet).

That being said it seems `django-jet` does not release binary distributions. In the [download files section of the project](https://pypi.org/project/django-jet/1.0.8/#files) you can see the only file type is "Source". If you require one or need more information please open a ticket in the `django-jet` repo.

Good luck!

**Comment by vseavello** [comment]
Thank you for your reply.

Vince
