### ISSUE TITLE
Make 'show verified email' the same width and height as other inputs

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#7523]
# current 
![ES1onn8XkAcKdcn](https://user-images.githubusercontent.com/3323703/76443514-69e67800-63ba-11ea-8bfa-214f9100a1a7.jpeg)

# would be nicer as...

![Screenshot from 2020-03-11 17-09-53](https://user-images.githubusercontent.com/3323703/76444010-39eba480-63bb-11ea-81ac-d382e6f473c1.png)

# fix

change class `form-group__select` to `form-group__input`

FYI @di @rascalking 
sorry for brevity. typing with a baby on one arm :P

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, include a screenshot in your Pull Request.

**Comment by nlhkabu** [comment]
While we're at it, we should probably rename `form-group__input` to `form-group__field`

**Comment by di** [comment]
Also while we're here @nlhkabu, I did some very rudimentary CSS on the public profile page for this (https://github.com/pypa/warehouse/pull/6833/files#diff-13dd850a07ccc0d7a0b641b1ff93af12R140-R148) but introducing `@ellipsis` creates a bit of an alignment issue that I wasn't able to fix:

<img width="403" alt="Screen Shot 2020-03-11 at 12 29 42 PM" src="https://user-images.githubusercontent.com/294415/76445882-20833200-6394-11ea-99d6-eaac9f9b8767.png">

Any ideas?

**Comment by nlhkabu** [comment]
Not sure @di. If you want to open a separate ticket, I'll take a look
