### ISSUE TITLE
Got locked out of my account automatically due to 2FA

### ISSUE THREAD

**Issue by remcohaszing** [pypa/warehouse#7532]
**Describe the bug**

When trying to log in to pypi.org, I need to enter a 2FA code. However, I have **not** configured this (yet).

**Expected behavior**

The ability to login

**To Reproduce**

Attempt to login

**My Platform**

Irellevant

**Additional context**

I just received the following email from noreply@pypi.org

> Hello remcohaszing,
>
> PyPI now supports provisioning Recovery Codes!
>
> Your account is current configured with these Two Factor Authenticaion Methods:
> 
> - Authentication Application (TOTP)
>
> In the event that you lose access to your two factor method(s) and have not provisioned Recovery Codes, you may permanently lose access to your PyPI account.
>
> Read more about Recovery Codes at https://pypi.org/help/#recoverycodes.
>
> To provision recovery codes log into your PyPI account and click "Generate Recovery Codes" in your account settings.
>
> -The PyPI Team

I am actually interested in configuring 2FA, but I can’t, because I can’t login.

**Comment by ewdurbin** [comment]
@remcohaszing no Two Factor authentication methods were automatically provisioned for any user. If you need assistance recovering your account due to a lost two factor auth method, please see https://pypi.org/help/#account-recovery

**Comment by ewdurbin** [comment]
logs indicate that you configured a TOTP method on 2019-09-03 and successfully logged in with that method most recently on 2019-11-12.

**Comment by remcohaszing** [comment]
Ehm, my bad. I overlooked it in my 2FA app :sweat_smile: 

Thanks for the fast response though!
