### ISSUE TITLE
Only load images when they display via CSS

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#757]
Currently we only show sponsor logos when the window is wider than 800px. Otherwise, a ``'display: none'`` rule is applied. This is great from a UX perspective, but it also means (AFAIK) that the images are still being loaded on mobile, even if they are not displayed. It would be great if we only loaded the images if the page is over 800px wide.

The same is true for the large (full size) PyPI logo; this displays only at displays above 550px wide.

*Copied from nlhkabu/warehouse-ui#4*

**Comment by nlhkabu** [comment]
I don't think this is such a large performance issue that it is worth worrying about as we have now switched to (much smaller) SVGs
