### ISSUE TITLE
Cannot set up 2FA with Microsoft Validator

### ISSUE THREAD

**Issue by staticdev** [pypa/warehouse#7584]
**Describe the bug**
I try to set up Microsoft Validator on PyPI's manage account page option Set up 2FA with an authentication application (TOTP) and it does not work.

**Expected behavior**
Application set up.

**To Reproduce**
Following the [steps here](https://pypi.org/help/#totp), I enter the app, click in Add Account, scan the QR Code in the link https://pypi.org/manage/account/totp-provision from PyPI.org, and the app generates a number with 6 characters and a space in the middle. "XXX XXX". I input this on PyPI's website and click Set up application.

Scenario 1 (I put the 6 digit number with the space)

I get the validation message: `Please match the requested format.`. I assume this behavior is expected, BUT I don't see any expected format in the page.

Scenario 2 (I put in the 6 position number without the space)
I always get `Invalid TOTP code. Try again?`no matter how many times I try.

**My Platform**
I am using Linux Ubuntu 19.10 with Firefox 74 64-bit.

**Additional context**
Don't need.

**Comment by di** [comment]
Hi, I'm guessing you're actually using [Microsoft Authenticator](https://www.microsoft.com/en-us/account/authenticator) instead, correct?

I just tried setting up 2FA with that app on Android and it worked for me.

Can you check that the time on your mobile device is up-to-date?

**Comment by di** [comment]
> I assume this behavior is expected, BUT I don't see any expected format in the page.

Good catch, I filed a separate issue for this here: https://github.com/pypa/warehouse/issues/7585

**Comment by staticdev** [comment]
@di Indeed my mobile device is 2 minutes ahead of current time in Google. I will try to put automatic time on my Android settings and try again.

**Comment by di** [comment]
@staticdev Also a great idea, I created https://github.com/pypa/warehouse/issues/7588.

Glad that your issue was resolved!
