### ISSUE TITLE
Use web test to implement a functional test suite

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#76]
We need some functional tests to ensure that Warehouse functions at a high level. Ideally this would use webtest to avoid needing to parse http and simply use the wsgi application.

**Comment by domenkozar** [comment]
I'd balance between selenium (backed by robot framework) and webtest depending on amount of JavaScript we have. I don't think we'll have that much so webtest should make it easy.

**Comment by dstufft** [comment]
This has been started now, so I'm going to go ahead and close this.
