### ISSUE TITLE
Marking a valid zipcode as "unreal"

### ISSUE THREAD

**Issue by sheyxpeare** [pypa/warehouse#7623]
It looks like the Boston zipcode 02101 is missing in your database.

**Comment by ewdurbin** [comment]
Hi @sheyxpeare, it sounds like you might be having a problem with a project hosted on PyPI.org, not PyPI itself.

This tracker is only for issues with the software that runs pypi.org itself. It cannot help with packages distributed from there. You'll need to contact the maintainers of the package you're trying to use.
