### ISSUE TITLE
Upload failed with 504 Server Error: Gateway Time-out

### ISSUE THREAD

**Issue by fullcircle23** [pypa/warehouse#7645]
**Describe the bug**
1. Package upload to https://test.pypi.org/legacy/ or https://upload.pypi.org/legacy/ failed with "504 Server Error: Gateway Time-out"

2. Also getting "PyPI is down for maintenance or is having an outage." for https://pypi.org/account/login/ 

3. And "Error 503 Backend is unhealthy .. cache-sin18043-SIN .." for
https://test.pypi.org/account/register/

**Expected behavior**
1. Package to be upload to pypi or testpypi.
2. Get account login page.
3. Get account register page.

**To Reproduce**
```
<PYTHON_BIN> -m twine upload \
  -u <PYPI_USER> \
  -p <PYPI_PASSWORD> \
  --repository-url <url> <WHEEL>
```

**My Platform**
Issue appears on both local and remote platforms.
1. Local: macOS 10.13.6
2. Remote: Travis CI

**Additional context**
Worked fine for me this morning till early afternoon today.

**Comment by jamadden** [comment]
Thanks for the report! The admins and moderators are aware. In the interest of centralizing things, I'm going to close this in favor of #7643; please feel free to subscribe to that issue or follow 'pypi' and 'pythonstatus' on twitter.

**Comment by fullcircle23** [comment]
Thank you!
