### ISSUE TITLE
Email "Options" dropdown of account setting unresponsive

### ISSUE THREAD

**Issue by cjw85** [pypa/warehouse#7647]
**Describe the bug**
Clicking the options button in the Account Emails section of https://pypi.org/manage/account/ leads to nothing happening.

![image](https://user-images.githubusercontent.com/3592009/77647955-3e898e80-6f5f-11ea-8138-0b5b2b6b0da4.png)

**Expected behavior**
A dropdown menu appears, presumably with items like "resend verification email"

**To Reproduce**
On account page click the aforementioned button.

**My Platform**
MacOS using both chrome 80.0.3987.149 and safari 13.0.5 (15608.5.11)

**Additional context**
None

**Comment by di** [comment]
Thanks for the report! This was due to #7649 and is now resolved by #7650.
