### ISSUE TITLE
Role.role_name can be null

### ISSUE THREAD

**Issue by di** [pypa/warehouse#7688]
Pairing with @ewdurbin on #2745 we noticed that `Role.role_name` can be null:

https://github.com/pypa/warehouse/blob/32f621a359bfa7ecb84d8b0ff77e675aae2cd9e1/warehouse/packaging/models.py#L64

Enforcing this to be `nullable=False` causes a lot of our tests to fail due to our `ProjectFactory` and `UserFactory` implicitly creating roles without names, since they bypass the `RoleFactory`.

We should update our test fixtures to allow us to set `nullable=False`.

Some possible leads: https://factoryboy.readthedocs.io/en/latest/reference.html

**Comment by ewdurbin** [comment]
After #7689, it looks like only 4 tests are left depending on the implicit Role creation here.

I'm not sure if supporting

`test_project = ProjectFactory(users=[test_user0, test_user1])`
or
`test_user = UserFactory(projects=[test_project0, test_project1])`

is worth it really.
