### ISSUE TITLE
Implement placeholder logo for Warehouse

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#772]
Currently if you don't have pypi-theme installed you get broken image links. It'd be nice if we had some basic (even plain squares?) logos of the same sizes of the PyPI logo to act as placeholder logos.

**Comment by dstufft** [comment]
In #873 I "create" some logos by just using a 1x1 blank square. Some placeholder logos would still be nice though but at a minimum there are no longer broken images shown by default when developing Warehouse.

**Comment by nlhkabu** [comment]
Do we want them to just say "Logo"?

**Comment by dstufft** [comment]
That works for me.
