### ISSUE TITLE
Tkinter tkhtmlview Package

### ISSUE THREAD

**Issue by iamprakhar016** [pypa/warehouse#7723]
I am not able to see any color nor i am able to set color for select feature.

If a user selects any word or letter in html, i am able to get that word by selection_get() method, but i am not  able to see or set color i.e. by default blue.

Another Problem is not able apply style which is put in head tag. Taking as a string and printing it.

[code.txt](https://github.com/pypa/warehouse/files/4426932/code.txt)

How to tackle it.

**Comment by di** [comment]
This issue tracker is for issues with the codebase behind pypi.org itself, not the projects hosted on it.

You should report this issue to the tracker for the tkhtmlview project itself at https://github.com/bauripalash/tkhtmlview instead.
