### ISSUE TITLE
Have top projects use the last 30 days or so instead of all time

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#775]
Right now the "top projects" thing on the index page uses the all time download counts. This is OK but it means that they are unlikely to _ever_ really change. Instead it'd be nice if we used the last N days or something like that.

**Comment by mahmoud** [comment]
Even in that case, setuptools/simplejson/pip will basically always dominate. Not to say those aren't decent projects, but if they are the most downloaded, wouldn't one think enough people already know about them?

I'm not sure what your stomach for state is, but "Trending" is probably better. The least complex way I can think to implement this would be to reuse the daily/weekly/monthly counts and look at packages that have, e.g., 500 downloads today and only 3000 downloads for the month or 3000 this week and only 4000 for the month. Plus, filter out newly uploaded packages that have a low total download count (or establish a baseline download count model for new packages).

**Comment by dstufft** [comment]
I agree this should probably use trending instead of the last 30 days. That makes a lot more sense. However, that probably means that this is more work that we should put into it prior to the initial launch so I'm going to bump this out of Become PyPI.
