### ISSUE TITLE
How to leave as "Maintainer" of a project?

### ISSUE THREAD

**Issue by grantjenks** [pypa/warehouse#7774]
I was added as a "Maintainer" to https://pypi.org/project/freegames-extended/ and https://pypi.org/project/tk-dragtool/ despite having NO RELATIONSHIP with the packages or "Owner" whatsoever. The freegames-extended package looks like a knock-off of my https://pypi.org/project/freegames/ package for which I am the current "Owner". I know nothing about the "-extended" variant and I think it looks suspicious.

I promptly did two things:

1. Uploaded "blank" packages with version 9.9.9 to get the attention of the "Owner".
2. Emailed the "Owner" explaining my actions in (1) and asking to be removed as a "Maintainer".

In general, I would like to be able to leave as "Maintainer" of these projects but could find no way to do so through the PyPI user interface.

**Comment by yeraydiazdiaz** [comment]
Thanks for the report @grantjenks, this has been raised a couple of times before.

Closing in favor of https://github.com/pypa/warehouse/issues/4729.

**Comment by ewdurbin** [comment]
@grantjenks you've been removed as maintainer from those two projects. I'll look into the suspicious aspects shortly.

**Comment by ewdurbin** [comment]
I don't see anything malicious in the diff between freegames-2.3.2 and freegames-extended-2.3.2, but it seems reasonable to keep an eye on the activity of this user. Thank you for the heads @grantjenks, and apologies for the confusion.

**Comment by grantjenks** [comment]
Thank you!
