### ISSUE TITLE
Search default or option: exclude projects with zero downloadable distributions

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#7778]
**What's the problem this feature will solve?**
Some PyPI projects have zero past releases, or have released distributions in the past but then deleted the distributions. When users search for projects, they are probably searching for packages they can download, and may be frustrated if the results include projects without any downloadable files.

**Describe the solution you'd like**
Either by default, or as a faceted search option, in search results, we could filter out packages that don't have downloadable distributions available.

**Additional context**
Requested in https://github.com/pypa/warehouse/issues/194#issuecomment-41197783 by @agronholm and seconded in the subsequent comment by @dstufft.

**Comment by di** [comment]
This can be done by adjusting the query used for reindexing to exclude releases without files: https://github.com/pypa/warehouse/blob/dc120b9c0f8fba9dc98809e68e1b56a1d1bda5e6/warehouse/search/tasks.py#L33-L95
