### ISSUE TITLE
Add Browser Analytics

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#779]
We'll want to add Google Analytics or something so that we can see traffic and browsers and such. This will most likely largely be done in ``pypi-theme``.

**Comment by nlhkabu** [comment]
Surely we want this to be active on launch?

**Comment by dstufft** [comment]
Yea we want this active on launch, but it's trivial to do so it shouldn't be hard, it'll just be dropping in a bit of JS into the template. The only hard part is our CSP policy.

**Comment by brainwane** [comment]
I asked for some clarification in IRC in `#pypa-dev` from Donald just now, and learned:

We already have metrics on legacy PyPI, so it's important to have analytics active in Warehouse at launch, so we don't miss data during the switch.

To abide by the content security policy, we need to figure out how to do GA without chunking some inline JS; our CSP policy instructs browsers to reject inline JavaScript in the HTML, only [allowing] linked scripts. In the worst case, we could relax the restrictions, but Donald would rather not do that.
