### ISSUE TITLE
Facing error while installing websocket

### ISSUE THREAD

**Issue by chandra1618** [pypa/warehouse#7791]
Hi,

I am facing an error while installing websocket-client package using pip. I am sharing a screenshot of the error, please help me to troubleshoot it.

![Screenshot from 2020-04-12 19-29-59](https://user-images.githubusercontent.com/34679608/79070509-1e462780-7cf4-11ea-924b-3a20290d296d.png)

**Comment by jamadden** [comment]
I cannot duplicate this with current version of pip and Python 2.7:
```console
$ pip install websocket_client
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting websocket_client
  Downloading websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
     |████████████████████████████████| 200 kB 4.0 MB/s
Requirement already satisfied: six in ./lib/python2.7/site-packages (from websocket_client) (1.14.0)
Installing collected packages: websocket-client
Successfully installed websocket-client-0.57.0
```

The [PyPI project page for websocket_client](https://pypi.org/project/websocket_client/#files) does not list anything about `packagecloud.io` (and at any rate, installing from external links hasn't worked in pip for a *long* time, [1.5 (2014-01-01)](https://pip.pypa.io/en/stable/news/#id318) IIRC). Perhaps you're using a non-standard index URL (check for ~/.pypirc) or a non-standard and/or outdated pip?

**Comment by chandra1618** [comment]
Hi Jamadden,

Thank you so much for your reply, I was able to install websocket-client using the same command, i also have tried to install the same package using pip3, but i see the same error.

**Comment by ewdurbin** [comment]
Based on your error output, it appears that you're attempting to install from packagecloud.io, not pypi.org/files.pythonhosted.org

Please review your [pip configurations](https://pip.pypa.io/en/stable/user_guide/#configuration), specifically the value for `index-url`... which based on the last line of the error in the screenshot appears to be set to https://packagecloud.io/github/git-lfs/pypi/simple/
