### ISSUE TITLE
Donation links are broken

### ISSUE THREAD

**Issue by PavanTatikonda** [pypa/warehouse#7798]
Hello Team,

When I click on ```Donate Here``` on  page ```https://pypi.org/sponsor/``` or ```Donate today!``` on page ```https://pypi.org/``` it is re-directing to the below url and throwing the following error:

URL: ```https://psfmember.org/civicrm/contribute/transact?reset=1&id=13```
```
Error
The website encountered an unexpected error. Please try again later.
Error messagePDOException: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) in lock_may_be_available() (line 167 of /usr/local/share/drupal7/includes/lock.inc).
```

Please help take a look and let me know if you need any other info.

Thanks,
Pavan.

**Comment by ewdurbin** [comment]
Thanks @PavanTatikonda, looks like the PSF crm is under maintenance, but should be available again soon.
