### ISSUE TITLE
Style the logged in / logged out indicator

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#780]
We'll want to fix things so that there is a logged in indicator when the user is logged in that can list all of their projects and take them to the management pages for their projects.

**Comment by dstufft** [comment]
With #837 this now only needs for the design to incorporate a logged in indicator. That bit of the design is controlled by the ``warehouse/templates/includes/current-user-indicator.html`` template.

**Comment by di** [comment]
Now that #1437 is merged, should we take this out of the "Launch" milestone?

**Comment by dstufft** [comment]
This should be good enough for launch yes.

**Comment by nlhkabu** [comment]
Adding this back to launched milestone as we need to address this (along with the extra links) on mobile :)

![screenshot from 2017-05-25 11-41-34](https://cloud.githubusercontent.com/assets/3323703/26447170/2476a1b4-413f-11e7-983e-5018c3ed0197.png)
