### ISSUE TITLE
Default Kivy rotation is 90 instead of 0 as of 2020.04.15

### ISSUE THREAD

**Issue by nooninm** [pypa/warehouse#7804]
**Describe the bug**

After clean install of both Python 3.8 and Kivy 2.0.0rc1, all kivy-examples examples pop up windows have their contents are displayed sideways.  That is, rotated 90 degrees.
This gets fixed by running any of the kivy example code, pressing F1 to get to the kivy settings, and reset the rotation to 0.

No windows should be rotated by default.
**To Reproduce**

Just do a clean install of Kivy 2.0.0rc1 and try some of the example code
**My Platform**
Windows 10

**Additional context**

Again,, this gets fixed by running any of the kivy example code, pressing F1 to get to the kivy settings, and reset the rotation to 0.

**Comment by nooninm** [comment]
Not a problem after all.  I found out today there was a .kivy directory with a config.ini file.  I believe I changed the rotation while trying out many things, following an (excellent) Alex Taylor Kivy tutorial video.  I deleted Python, Kivy, and the .kivy directory, reinstalled everything, and it all works just fine.

**Comment by pradyunsg** [comment]
@nooninm You probably want to file an issue at https://github.com/kivy/kivy, and not here.
