### ISSUE TITLE
Figure out what to do with the "prolific pythonista"label

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#781]
The user page currently has a label that says "Prolific Pythonista". In what situations should this be displayed? /cc @nlhkabu

**Comment by nlhkabu** [comment]
Haha!  Yes, this is going to be interesting!  I'm not sure if it needs to be categorised under 'Become PyPI' though?  Unless you *really* like it?

**Comment by dstufft** [comment]
We should probably at least hide or remove it before we launch if we're not going to do anything with it before we launch.

**Comment by nlhkabu** [comment]
+1

**Comment by dstufft** [comment]
With #838 this no longer needs to be handled prior to becoming PyPI (and I'm not sure if we need an open issue for it at all?).

**Comment by nlhkabu** [comment]
Yes, I agree.  It's really an idea to be discussed in the future.
