### ISSUE TITLE
scholarly.search_author_custom_url   is not responding

### ISSUE THREAD

**Issue by baberjunaid** [pypa/warehouse#7815]
Dear contributer, 

It is a wonderful contribution. However, after trying several examples; author custom url function is not working, or I am doing some mistake. You have not given any example of that function as well. 

Let the custom url be
```
a_url = "https://scholar.google.com/citations?user=rggPjyoAAAAJ&hl=en"
search_query = scholarly.search_author_custom_url(a_url)
```
then following error is received

ConnectionError: HTTPSConnectionPool(host='scholar.google.comhttps', port=443): Max retries exceeded with url: //scholar.google.com/citations?user=rggPjyoAAAAJ&hl=en (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7c92718048>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by baberjunaid** [comment]
Lastly, if you could entend the API for affiliation search as well. Please.

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (`https://pypi.org/project/scholarly`).
