### ISSUE TITLE
Decide on Gravatar vs Local Avatar vs Both

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#782]
The new design uses avatars for users. Currently this is just using Gravatar but is that what we want to have? Should we instead use local avatars? Or should we support local avatars and then fall back to gravatar?

**Comment by nlhkabu** [comment]
I think just Gravatar support is fine, at least for the initial release.  I would, however, like to add a custom default fallback if no Gravatar image is found.

**Comment by dstufft** [comment]
Ok, then we'll continue to use Gravatar! I'll go ahead and close this issue :)
