### ISSUE TITLE
Cryptography docs

### ISSUE THREAD

**Issue by phoenixredwolf** [pypa/warehouse#7832]
**Describe the bug**

Documentation for the cryptography library is returning a 403 Forbidden error.

**Expected behavior**

View and/or download package documentation

**To Reproduce**

goto https://cryptography.io/

**My Platform**

Page inaccessible from both Chrome and Firefox on Windows 10

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead: https://github.com/pyca/cryptography/issues
