### ISSUE TITLE
redirects for Databased Backed Blacklists

### ISSUE THREAD

**Issue by graingert** [pypa/warehouse#7840]
**What's the problem this feature will solve?**
currently you run `pip install requirements.txt` or `pip install pip-sync` and pip fails with no useful advice

**Describe the solution you'd like**
pypi should provide advice for each blacklisted package eg
requirements.txt -> "you should use -r requirements.txt"
pip-sync -> "you should install pip-compile"
bad-package-with-virus -> "this package was removed because it was malicious"

Where redirecting to a package the HTTP interface should also redirect to the new package

**Additional context**
https://github.com/graingert/pip-compile/issues/1

**Comment by graingert** [comment]
somewhat like https://docs.npmjs.com/cli/deprecate

**Comment by di** [comment]
I think this makes more sense as a feature request for pip, similar to https://github.com/pypa/pip/issues/5777, which would also be blocked on implementing https://github.com/pypa/warehouse/issues/4703.
