### ISSUE TITLE
CODATA.py symbol names not in line with current "allascii.txt"

### ISSUE THREAD

**Issue by farbeiter** [pypa/warehouse#7849]
**Describe the bug**
when importing constants from CODATA, like "from CODATA import c0" I get the error:

    mu_0 = mag_constant
NameError: name 'mag_constant' is not defined

When I fix this by inserting into __init__.py line 175
#   Magnetic constant
mag_constant = vacuum_mag_permeability

this error seems fixed, but the next one appears:

    epsilon_0 = electric_constant
NameError: name 'electric_constant' is not defined

.. and so on.

**Expected behavior**
The names of the constants in allascii.txt/CODATA.txt  should be updated in the code to match
https://physics.nist.gov/cuu/Constants/Table/allascii.txt

**To Reproduce**

**My Platform**
Win10, Anaconda3, Spyder, Python3.7

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (`https://pypi.org/project/<SOME PACKAGE>`).
