### ISSUE TITLE
Translate emails too

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#7850]
## Bad source in Weblate

Emails don't have translatable regions marked w/ Jinja

For example, I've just got https://github.com/pypa/warehouse/blob/69ce3dddab53503fa737c82488a77a40c819987b/warehouse/templates/email/unyanked-project-release/body.txt in English and noticed that those strings weren't even present in Weblate.

**Comment by di** [comment]
Duplicate of #7583.
