### ISSUE TITLE
How to remove myself as a collaborator on a project?

### ISSUE THREAD

**Issue by inklesspen** [pypa/warehouse#7854]
I am currently marked as a collaborator on three projects I don't want to be. I am not the sole collaborator on any of them. However, the "Remove" button next to my name is grayed out. How can I remove myself from the projects?

**Comment by yeraydiazdiaz** [comment]
Hello @inklesspen, I believe only owners can remove collaborators in PyPI at the moment. I feel it's a feature requested before but I can't find the issue right now.

**Comment by pradyunsg** [comment]
https://github.com/pypa/warehouse/issues/5790 is what you're looking for @yeraydiazdiaz. :)

**Comment by inklesspen** [comment]
I _am_ an owner on the project, though, actually. And I don't want to be.

![image](https://user-images.githubusercontent.com/11397/80314712-f05aeb80-87a7-11ea-9a35-ec450087aa84.png)

**Comment by inklesspen** [comment]
So looks like it's #4729.

**Comment by di** [comment]
Yep! Closing as a duplicate of #4729.
