### ISSUE TITLE
Give maintainers the ability to provide reason for yanking

### ISSUE THREAD

**Issue by di** [pypa/warehouse#7856]
PEP 592 permits the use of an arbitrary string which gives a reason for yanking:

> The value of the `data-yanked` attribute, if present, is an arbitrary string that represents the reason for why the file has been yanked. Tools that process the simple repository API MAY surface this string to end users.

PyPI does not currently support this. Completing this issue would include a UI to allow the user to set this when yanking, an update to the DB model to change this from a boolean to a text field, and an update to the simple page to surface this value if present.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev).

**Comment by pradyunsg** [comment]
FYI: pip prints the reason for yanking if it is provided, and if it is not, it prints "Reason for being yanked: \<none given>".

As a result of this, any yanked releases on PyPI today will result in pip's output when installing a yanked release saying "Reason for being yanked: \<none given>".

Reported/mentioned in https://github.com/pypa/pip/issues/8160#issuecomment-620772136.

**Comment by deveshks** [comment]
Just to confirm, is this issue also taken up by someone to work on as per https://github.com/pypa/warehouse/issues/7886#issuecomment-626093001 ?

**Comment by daneah** [comment]
@deveshks yep, I'm working on this.
