### ISSUE TITLE
1.3a1 release page has incorrect link to associated "what's new" page

### ISSUE THREAD

**Issue by allyn-psyonix** [pypa/warehouse#7868]
**Describe the bug**
This issue is for the gevent 1.3a1 release page: https://pypi.org/project/gevent/1.3a1/

I was digging into the changes since the previous version our project is using and found one of the links on this page is incorrect.

The "what's new" link, second to last line under "Project Description", is incorrect. It should be pointing to http://www.gevent.org/whatsnew_1_3.html but it is pointing to the 1.2 what's new page. I assume this field was copied from the 1.2 release page and just forgot to update it. It appears to be correct on the 1.3a2 release page.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead: https://github.com/gevent/gevent/issues

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (`https://pypi.org/project/<SOME PACKAGE>`).

That said, I'm the gevent maintainer 😄  The metadata for releases on PyPI is immutable, so there's nothing that can be done about it, short of yanking the entire release (which just makes it more difficult to see).
