### ISSUE TITLE
Link to Twine on "Add API token" page points to virtualenv

### ISSUE THREAD

**Issue by pganssle** [pypa/warehouse#7891]
I created an API token on test.pypi.org and was going to go to the twine documentation to make sure I knew what environment variable to set. There's a link in the page, this one:

![image](https://user-images.githubusercontent.com/1377457/81069893-841b6e80-8eb0-11ea-8634-74752b8ee3d6.png)

But that link points to https://pypi.org/project/virtualenv/ when it should presumably point to https://pypi.org/project/twine/.

**Comment by pganssle** [comment]
From a cursory search, I believe it needs to be changed [here](https://github.com/pypa/warehouse/blob/f37f57b0315bbbf940148f45ebc980b81f0cf65f/warehouse/templates/manage/token.html#L77), but I don't know if this is duplicated anywhere else.

**Comment by di** [comment]
Yep, that's the right place. I've put a "good first issue" label on this issue.

**Comment by deveshks** [comment]
I think this needs to be changed [here](https://github.com/pypa/warehouse/blob/master/warehouse/templates/manage/token.html#L87) too. 

Can I create a PR for the same? And may I also know what kinds of tests should be done locally to verify the template update. (The only thing I can think of is to deploy the website locally and verify that the link has been correctly updated.)

**Comment by di** [comment]
@deveshks Please do! And I think the change in the templates is sufficient.

**Comment by deveshks** [comment]
Thanks. I have created a PR for the same.
