### ISSUE TITLE
Handle the case when a project doesn't have a long description

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#790]
When a project doesn't have a description we currently land on a blank pane on the UI. Is this acceptable? Should we switch to a different pane?

**Comment by nlhkabu** [comment]
I think for the description pane, we should add a default message like "This package does not have a package description.  If you are the owner of this package you can provide a description by <instructions here>.".  

But for the other panes, we should simply hide them.  For example, when there are no downloads, we should hide the download pane and link altogether.

**Comment by nlhkabu** [comment]
@dstufft I've got a styled solution for this ready to go...

```
{% if release.description %}
<div class="release-description">
  {{ release.description|readme(format="rst") }}
</div>
{% else %}
<div class="callout-block">
  <p>The author of this package has not provided a project description.</p>
</div>
{% endif %}
```

The only problem is that when a package description is not available, the code is returning 'unknown' as a string.  Should it be doing this?  How can I get around it?  I'm not keen on string matching for 'unknown' in the template...

**Comment by dstufft** [comment]
Don't special case ``UNKNOWN``.

There's some history there where distutils would "helpfully" fill in a missing but required value with ``UNKNOWN`` which has caused a bunch of ``UNKNOWN`` in the database to show up. Warehouse correctly sanitizes out the ``UNKNOWN`` values upon new uploads and stores them as ``NULL`` or ``""`` in the database (which will show up as ``None`` or ``""`` in Python). That leaves the existing packages that still have ``UNKNOWN`` in the database, and my plan is once legacy PyPI is gone and no longer able to add more of them into the database, then I'll do a data migration to clean the database of them. This is being tracked by #69.

For now, Warehouse should just treat an ``UNKNOWN`` as if someone actually typed that into the description and render it as such.

**Comment by nlhkabu** [comment]
Ok, thanks for the explanation.  Sounds good to me :D

**Comment by dstufft** [comment]
Is this handled now that #875 is merged?

**Comment by nlhkabu** [comment]
Yes! :tada:
