### ISSUE TITLE
B311 gives false positive

### ISSUE THREAD

**Issue by JonathanCloudDef** [pypa/warehouse#7901]
**Describe the bug**
Ran a project with no security or cryptography features, packages, etc... in it.  Received B311 error.

**Expected behavior**
Pseudo random number generator is fine for the work I was using it for (splitting data into training and testing datasets).  This should not trigger a B311 error.

**To Reproduce**
This is the full message I received:
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
   Severity: Low   Confidence: High
   Location: namematching/TrainingData.py:58
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random
57                                      while (found == 1): # It's possible we accidentally grab a match so we will grab lines at random until we find one that fails the simple matching
58                                              linesIndex = random.randint(0, maxLines - 1)
59                                              nameToMatch = self.Lines[linesIndex][1]

--------------------------------------------------
>> Issue: [B311:blacklist] Standard pseudo-random generators are not suitable for security/cryptographic purposes.
   Severity: Low   Confidence: High
   Location: namematching/TrainingData.py:73
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b311-random
72                      for data in self.EncodedTrainingData:
73                              pct = random.uniform(0,1)
74                              if (pct < splitPct): # goes to Testing

--------------------------------------------------

**My Platform**
python 3.6 and anaconda with bandit.  pytorch is heavily used in scanned software.

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
