### ISSUE TITLE
Display how long ago the release was made

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#791]
We'll want to display how long ago the release was made on the project/release detail page. Probably we'll want to implement this in javascript?

**Comment by nlhkabu** [comment]
@dstufft I also want to make sure that we are consistent in the way that we display dates across all pages.  So, something like "April 10th, 2015"??  I prefer to avoid "4/10/15" as a format, as (unless we enable internationalisation) this means 4th October here...

It would also be cool if we could do something similar to https://docs.djangoproject.com/en/dev/ref/contrib/humanize/#naturaltime

**Comment by dstufft** [comment]
Right now all dates are displayed using a filter that does localization (though it only supports en-us right now I think). Anything that isn't "static" should be done via javascript (e.g. April 10th, 2015 is static, it's always going to be april 10th, 2015 but '6 months ago' is dynamic, in 6 more months it's going to be '12 months ago').

Whatever we do though, it should handle localization and translation.
