### ISSUE TITLE
Camera comtrol with PTP PTPy 0.3.2 fails with No backend available

### ISSUE THREAD

**Issue by jonoboy9** [pypa/warehouse#7914]
I am trying to run the camera control software ptpy 0.3.2
I am using window 10, python38.
I installed the software by pip install ptpy-0.3.2-py3-none-any.whl

From python, I execute the following commands:
from ptpy import PTPy
camera = PTPy()
I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python38\lib\site-packages\ptpy\__init__.py", line 110, in __new__
    plain_camera = plain(device=device)
  File "D:\Python38\lib\site-packages\ptpy\ptp.py", line 712, in __init__
    super(PTP, self).__init__(*args, **kwargs)
  File "D:\Python38\lib\site-packages\ptpy\transports\usb.py", line 90, in __init__
    else find_usb_cameras(name=name)
  File "D:\Python38\lib\site-packages\ptpy\transports\usb.py", line 61, in find_usb_cameras
    return usb.core.find(
  File "D:\Python38\lib\site-packages\usb\core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

In the python directory I have \site-packages\pyusb-1.0.2-py3.8.egg-info. 
In site-packages\usb\backend I have libusb0.py, libusb1.py and openusb.py
In the Windows directory I only have only libusb0.dll in C:\Windows\System32\DriverStore\FileRepository\arduino_gemma.inf_amd64_ccc1c03de7b2c57b\amd64

In the locate_library function in D:\Python38\Lib\site-packages\usb\libloader.py, the find_library is ctypes.util.find_library
It is looking for the following DLLs:
usb-1.0.dll, libusb-1.0.dll, usb.dll, openusb.dll, usb-0.1.dll, libusb0.dll
I have also noticed that none of the above are in the Windows System32 directory. Should the code be modified to look for DLLs for other names in Windows 10.

**Comment by deveshks** [comment]
I think you should raise this issue in the github repo for `ptpy` which you are using in the code. (I assume https://github.com/Parrot-Developers/sequoia-ptpy/ is that repo)

This repo houses the backend for https://pypi.org/ and IMO not the correct place for filing this.

**Comment by jarrott616** [comment]
Solved.
