### ISSUE TITLE
Reduce header screen realestate usage

### ISSUE THREAD

**Issue by rsyring** [pypa/warehouse#793]
I'd like to request that you reconsider how much screen realestate the header is using up (area in the red rectangle in my screenshot).  IMO, it's way too tall and dominates the landscape of the page, which is unnecessary and not particularly user friendly.

![screenshot - 11202015 - 11 30 32 am](https://cloud.githubusercontent.com/assets/109467/11305561/4aa11cec-8f7b-11e5-9829-ef843efb813d.png)

I'd recommend you look at GitHub's new design as a template for a minimal and yet useful header area.

**Comment by qwcode** [comment]
+1

**Comment by nlhkabu** [comment]
Thanks for the feedback.  I'll put this on the list of items to test in our user testing sessions.

**Comment by rsyring** [comment]
@nlhkabu thank you :)

**Comment by pradyunsg** [comment]
How about shifting `pip install ...` box to in the same line as the package name, to the left/right of the license?

That way, the vertical wastage of real-estate is reduced.

**Comment by nedbat** [comment]
FWIW, this was my first reaction also: "What's going to eventually go in the big blue box?"

**Comment by nlhkabu** [comment]
Closing this issue now, as:

- The padding on the header has been reduced and the font size made smaller
- The badges bar will be removed in #1308 

Further changes are planned on the package detail page, so we'll keep this objective in mind when updating the UI.

Thanks for the feedback.

**Comment by nlhkabu** [comment]
Refs #1988

**Comment by pradyunsg** [comment]
> How about shifting `pip install ...` box to in the same line as the package name?

![image](https://cloud.githubusercontent.com/assets/3275593/26104659/7f636a6a-3a5c-11e7-8810-140bd8bb4164.png)

@nlhkabu Thoughts?
