### ISSUE TITLE
Outdated instructions for systemd

### ISSUE THREAD

**Issue by djh42** [pypa/warehouse#7936]
**The instructions on https://pypi.org/project/systemd/ are outdated.

The page says:

  **Installation**

  You should install systemd headers
  For debian users:

```
  apt-get install build-essential \
      libsystemd-journal-dev \
      libsystemd-daemon-dev \
      libsystemd-dev
```

That is out of date. _libsystemd-journal-dev_ and _libsystemd-daemon-dev_ no longer exist and are incorporated within _libsystemd-dev_ now.

It then goes on to say:

  And install it from pypi

  `pip install systemd`

Again, that is outdated and on many systems it is necessary to use _pip3_ rather than _pip_. The possibility should certainly be mentioned.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
