### ISSUE TITLE
Work out what to do with RSS

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#794]
We do not have any links to RSS on the new design.

![screenshot-pypi python org 2015-11-20 17-11-13](https://cloud.githubusercontent.com/assets/3323703/11306468/e0340692-8fa9-11e5-9118-6ea4601d37b4.png)

We need to work out:
a) Are we still supporting them
b) If yes, from where should we link to them (footer maybe??)

**Comment by dstufft** [comment]
We could also just use the ``<head>`` fields that let people auto discover them.

**Comment by nlhkabu** [comment]
Yes, I think this is a good solution.

**Comment by di** [comment]
The RSS feeds are currently at:
* https://pypi.python.org/pypi?%3Aaction=rss
* https://pypi.python.org/pypi?%3Aaction=packages_rss

In the interest of not breaking people's existing feeds, seems like we need to:
* Add 301 redirect for legacy RSS feed URLs
* Add new RSS feeds to Warehouse
* Add RSS feeds to `<head>`

**Comment by dstufft** [comment]
Yea, that seems to be accurate.
