### ISSUE TITLE
scapy_iface_getmacbyip_get_if_hwaddr_errror

### ISSUE THREAD

**Issue by Ymigmli** [pypa/warehouse#7948]
![image](https://user-images.githubusercontent.com/47731874/81917682-1685e580-9608-11ea-86d6-6728daa52c8c.png)

![image](https://user-images.githubusercontent.com/47731874/81918052-94e28780-9608-11ea-80c4-a95b529d466a.png)

![image](https://user-images.githubusercontent.com/47731874/81917768-34534a80-9608-11ea-8bce-ceb99b6197a9.png)

![image](https://user-images.githubusercontent.com/47731874/81918132-af1c6580-9608-11ea-8649-6d8428b23ae8.png)

![image](https://user-images.githubusercontent.com/47731874/81917957-72506e80-9608-11ea-99ae-ccec34999041.png)

for windows 10,Normal before patch update，abnormal after update，iface can't find interface
Linux,mac normal

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by Ymigmli** [comment]
thanks
