### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by nedbat** [pypa/warehouse#795]
I noticed a Slack URL in the new layout.  I hope this is a placeholder, and we aren't going to be enshrining the idea that packages all have Slack teams.  IRC is broadly used, and there are modern alternatives to Slack.
Perhaps this should say "Chat" or "Support" instead?

**Comment by nlhkabu** [comment]
Yes, this is just a placeholder.

As I understand it, a package manager can now specify any number of links - so this could (in theory) include a link to a slack channel.  I was just demonstrating that would we attach a slack icon in this case.

**Comment by nedbat** [comment]
Oh interesting, I hadn't heard about that new option.  Is there something I can read (even code) about it?  What would make it have a Slack icon? And what would happen in the IRC case?

**Comment by dstufft** [comment]
It's not really exposed yet in setuptools though it could be, the capability is there in PyPI already. The current icons are mostly just hardcoded with TODO items just because I hadn't done it yet. The behavior of those icons is being tracked by #783

**Comment by nlhkabu** [comment]
And for IRC, I am not sure.. let me open another issue for that!
