### ISSUE TITLE
My user isn't allowed to upload to project

### ISSUE THREAD

**Issue by long2ice** [pypa/warehouse#7954]
Hello,I want upload a new package named ``alice`` and the project name is used by https://pypi.org/project/alice ,but that project is empty and last active year 2010, I don't want change my project name, so how can I use the project name in pypi? Thanks!

**Comment by di** [comment]
[Please open a PEP 541 request here](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md).
