### ISSUE TITLE
Add Sass Lint configuration

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#799]
Once a Sass styleguide is set, then we will need to create a .yaml file for the linter, as per https://github.com/brigade/scss-lint

**Comment by nlhkabu** [comment]
https://github.com/sasstools/sass-lint is a better choice here as it has no ruby dependency.

I've chosen the Airbnb styleguide (https://github.com/airbnb/css) because it is clear, without being to prescriptive.

@dstufft if I put together the linting file, can you integrate it into the build process? 

The documentation specifies that it should live in the project root (https://github.com/sasstools/sass-lint#configuring) - unless you want it to be located elsewhere?

**Comment by dstufft** [comment]
@nlhkabu Sure. Although if it's a node.js thing, it should be as easy as adding the linter to ``packages.json`` devDependencies and then adding the command to do the linting to the ``make lint`` target.
