### ISSUE TITLE
list recent sent emails in security/account settings

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#7992]
**What's the problem this feature will solve?**
Sometimes administrators want to send our users email notifications to ask that they do something, but we don't want to inure them to clicking on links in emails, and we want a way to credibly demonstrate that the email is legitimate.

**Describe the solution you'd like**
Via <a href="https://twitter.com/runasand/status/1248385736677576706">this tweet</a> I saw that Facebook archives recent automated emails sent to users so that each user can check in their settings to find those notifications:

> To confirm whether an email claiming to be from Facebook is authentic, review recent emails we've sent in your Security and Login Settings

Could we do this?

**Additional context**
In the next 12-18 months, PyPI will probably add more features or increase the strictness of authentication, etc. for project maintainers and owners. When we do those things, we'll want to notify users in a credible way.

**Comment by di** [comment]
> Could we do this?

Seems reasonable. We could potentially add sent emails to the existing "Security History" feed.

Does the Facebook implementation of this feature include the entire email, or just the subject/timestamp?

**Comment by brainwane** [comment]
Good question! I don't know. (I don't have a Facebook account.)

**Comment by di** [comment]
Me neither 🙂

**Comment by pradyunsg** [comment]
It's a table, with:

- Date (eg: "July 20, 20:26")
- Sent to (i.e. the email)
- Email subject

**Comment by patelneel55** [comment]
Hey guys, I think this is a pretty neat feature and I am currently in the works of implementing it. I had a couple of discussion topics to determine the use cases of the recent emails tab. How long back in time should be our definition of "recent"? For reference, Facebook shows recent emails for the [past 2 weeks](https://www.facebook.com/help/1956527391029758?helpref=faq_content#u_0_17:~:text=We%20will%20show%20you%20recent%20security,two%20weeks%20in%20your%20SECURITY%20tab.) for security emails and the [past 2 days](https://www.facebook.com/help/1956527391029758?helpref=faq_content#u_0_17:~:text=We%20will%20show%20you%20any%20other,days%20in%20your%20OTHER%20EMAILS%20tab) for other emails.

Another topic of discussion is should there be an action item next to the emails such as a `"I Didn't Do This"` button for a user to either reset password or contact `PyPI`?

**Comment by brainwane** [comment]
Good questions @patelneel55!

(Other people looking: @patelneel55's work is [in this branch](https://github.com/patelneel55/warehouse/tree/show-emails) I think.)

Most maintainers only maintain one package. And PyPI emails them notifications roughly 1-10 times per year. So -- assuming this is ok on a performance level -- I think the past 3 months, for security and other emails, would make sense.

I think an action item for each email would make sense. I think you're suggesting "I Didn't Do This" but that might be too specific; maybe "Help" would be better, with the 2 possible actions coming out of that being "contact PyPI administrators about this" and "reset my password"? In that case, would the "Help" bit be implemented in JavaScript?

**Comment by patelneel55** [comment]
> I think the past 3 months, for security and other emails, would make sense.

Sounds good!



> maybe "Help" would be better, with the 2 possible actions coming out of that being "contact PyPI administrators about this" and "reset my password"? In that case, would the "Help" bit be implemented in JavaScript?

Hmm, it shouldn't be a problem to create the action, we could maybe create a new section in the help page that covers contacting the admins and resetting the password if necessary. However, now that I think about it, don't these actions relate more towards the other events such as `"Logged in"` or `"Password reset"` rather than `"Email sent"`? We could maybe provide a link to the newly created help page above the event table in case anyone notices anything suspicious?

**Comment by brainwane** [comment]
Thank you @patelneel55 -- the screenshot in https://github.com/pypa/warehouse/pull/8170#issue-440366108 looks great!
