### ISSUE TITLE
Code highlights 

### ISSUE THREAD

**Issue by frankwiles** [pypa/warehouse#800]
Apologies if this has been raised before but I think using something like Pygments or at the very least using a slightly different background color on the package detail/README page would go a long way to improving the look and readability of that information.  

So instead of this: 

![screen shot 2015-11-20 at 4 00 49 pm](https://cloud.githubusercontent.com/assets/144159/11313081/f27a3984-8f9f-11e5-8d8e-b0b342163916.png)

Something more like:

![screen shot 2015-11-20 at 4 03 11 pm](https://cloud.githubusercontent.com/assets/144159/11313130/3adb65c2-8fa0-11e5-9109-229a1f072405.png)

**Comment by nlhkabu** [comment]
Yes, agreed.  The package content panel is yet to receive any styling at all, so this is yet to be done (amongst other things).  I am going to close this now, as I have opened a larger issue that covers the styling of the entire panel (see #801).
