### ISSUE TITLE
Update mailing list link in developer docs

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#8012]
We've now [decommissioned](https://groups.google.com/d/msg/pypa-dev/rUNsfIbruHM/LCEx-CB5AgAJ) the [pypa-dev Google Group](https://groups.google.com/forum/#!forum/pypa-dev).

I'd like for someone to go through the following developer documentation pages and update all the following links so that they point to [https://mail.python.org/mailman3/lists/distutils-sig.python.org/](https://mail.python.org/mailman3/lists/distutils-sig.python.org/) instead.

This is a good first contribution for someone who's new to this repository. You open up the files listed below and change the URL on the following lines:

* `README.rst`, line 54:.```. _`pypa-dev mailing list`: https://groups.google.com/forum/#!forum/pypa-dev```
* `docs/development/getting-started.rst`, starting on line 26: ```- For longer-form questions or discussion, message the `pypa-dev mailing```
* `docs/development/getting-started.rst`, line 609: ```Freenode`_, or the `pypa-dev mailing list`_, to ask questions or get```
* `docs/development/getting-started.rst`, line 633: ```.. _`pypa-dev mailing list`: https://groups.google.com/forum/#!forum/pypa-dev```
* `docs/development/index.rst`, line 19: ```or the `pypa-dev mailing list`_, to ask questions or get involved.```
* `docs/development/index.rst`, line 38: ```.. _`pypa-dev mailing list`: https://groups.google.com/forum/#!forum/pypa-dev```

and then open a pull request.

This is a followup to #8010.

--

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/). If you are working on this issue and have questions, feel free to ask them here, [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [distutils-sig.python.org mailing list](https://mail.python.org/mailman3/lists/distutils-sig.python.org/).

**Comment by Manthan03583** [comment]
I want to work on it.

**Comment by brainwane** [comment]
It looks like @arshadrr didn't see your note before making a pull request, @Manthan03583 -- I've opened  #8031 for you to work on instead.

**Comment by Manthan03583** [comment]
mailing list link in developer docs updated #8030
