### ISSUE TITLE
Version issue on a certain package.

### ISSUE THREAD

**Issue by Animenosekai** [pypa/warehouse#8015]
**Describe the bug**

I already opened an issue into the pip repository but they told me to open one here concerning an inconsistency in the version of a certain on the website

https://github.com/pypa/pip/issues/8360

**Expected behavior**
To show the latest version ( 1.5 ) on both the search result page and the project page.

**To Reproduce**
Search for `filecenter` on PyPi.

**My Platform**
I experience this bug in every browser and with the `pip search` command (also it doesn’t want to upgrade from an old version to the new one while `pip install` installs the latest version.)

![0CF632DF-3904-4B12-9984-13B11F420073](https://user-images.githubusercontent.com/40539549/83282502-a3d65600-a214-11ea-9b66-ee8fac36846f.jpeg)
![D60B5B89-C238-4498-B0C1-BF785C9DB24D](https://user-images.githubusercontent.com/40539549/83282510-a769dd00-a214-11ea-99a2-92f5e1c03950.jpeg)

**Comment by di** [comment]
Updates to the search index are not immediate, it may take up to 24 hours for the new release to be indexed and for the pages in question to fall out of cache.

**Comment by Animenosekai** [comment]
> Updates to the search index are not immediate, it may take up to 24 hours for the new release to be indexed and for the pages in question to fall out of cache.

Ok thank you!

**Comment by Animenosekai** [comment]
Now that it works fine should I close the issue?
