### ISSUE TITLE
pyrealsense2 is available in /project but not found in /simple

### ISSUE THREAD

**Issue by androiddrew** [pypa/warehouse#8018]
**Describe the bug**

I went to pip install pyrealsense2  and received 

```
ERROR: Could not find a version that satisfies the requirement pyrealsense2 (from versions: none)
ERROR: No matching distribution found for pyrealsense2
```

I can download the wheels however at the project page 

https://pypi.org/project/pyrealsense2/#files

**Expected behavior**

I expect to be able to use the pip install command to install pyrealsense2

**To Reproduce**

copy and paste the  pip command from the project page 

```
 pip install pyrealsense2
```

**My Platform**

Ubuntu Linux (Arm64)
Mac OS X

**Additional context**

**Comment by jamadden** [comment]
Thanks for the report. Unfortunately, https://pypi.org/project/pyrealsense2/ only publishes binary wheels for manylinux1 and Windows. It does not publish the source needed to build wheels for other platforms, and neither of your platforms are supported by the wheels it does publish:

- The `manylinux1` standard is x86/x86_64 only and does not allow for Arm wheels. 
- While it's possible to distribute macOS binary wheels, this project is not doing so. 

If you use the `-v` argument to pip, you can see it check and discard all these wheels (here, I'm on macOS):
```console
$ pip install -v pyrealsense2
...
1 location(s) to search for versions of pyrealsense2:
* https://pypi.org/simple/pyrealsense2/
Fetching project page and analyzing links: https://pypi.org/simple/pyrealsense2/
...
  Skipping link: none of the wheel's tags match: cp27-cp27m-manylinux1_x86_64: https://files.pythonhosted.org/packages/71/6e/e47da1a4c399b651670255c5f58de2eecbe0b31f927f4041672f28e5d6ac/pyrealsense2-2.9.1-cp27-cp27m-manylinux1_x86_64.whl#sha256=9acf45bd3612cf2225f02c236c9c0efe4f46f38cd6b003f81c63edf08994852c (from https://pypi.org/simple/pyrealsense2/)
…
```

If you'd like the project to publish source or additional binary wheels, you'll need to ask the maintainers of that project.
