### ISSUE TITLE
Fix CSS errors

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#802]
Fix the following CSS errors (mostly a result of the CSS restructure):

- [ ] Reduce the font size of the badges

![badge-font-size](https://cloud.githubusercontent.com/assets/3323703/11318373/62ee51da-9047-11e5-8bc1-e2a3ba3b7612.png)

- [ ] Remove underline on sidebar links (also make cursor pointer)

![sidebar-link-underline](https://cloud.githubusercontent.com/assets/3323703/11318375/62f940f4-9047-11e5-98f2-901251ab0cf0.png)

- [ ] Make the introduction text align left

![intro-tect-alignment](https://cloud.githubusercontent.com/assets/3323703/11318370/62975498-9047-11e5-938e-c039428fb3cd.png)

- [ ] Make the button group share internal borders

![button-group](https://cloud.githubusercontent.com/assets/3323703/11318371/62991ca6-9047-11e5-9d65-f0ff4c9226ba.png)

- [ ] Make the package history design work with just one release (remove vertical line)

![single-package-history](https://cloud.githubusercontent.com/assets/3323703/11318374/62f1227a-9047-11e5-831e-3d3b7a54d110.png)

- [ ] Add padding to the horizontal links

![horizontal-links](https://cloud.githubusercontent.com/assets/3323703/11318372/62dc6f4c-9047-11e5-8113-be5a08f19d6f.png)

- [ ] Make the package card bg white

![package-card](https://cloud.githubusercontent.com/assets/3323703/11318377/7815b6e8-9047-11e5-99a5-3da479399e72.png)

- [ ] Add padding to the bottom of the footer

![footer-padding](https://cloud.githubusercontent.com/assets/3323703/11318388/3e75fc8a-9048-11e5-9881-275873de0371.png)

- [ ] Fix alignment and spacing of Changelog title and button
![changelog-title](https://cloud.githubusercontent.com/assets/3323703/11348426/6f71689c-921e-11e5-84e5-c5ab3b4af49b.png)

**Comment by alexwlchan** [comment]
I think I have fixes for most of these; I’ll put up a PR when I’ve got a working dev environment and can check my changes are behaving as I expect. :)

**Comment by nlhkabu** [comment]
Great al

**Comment by nlhkabu** [comment]
Hi @alexwlchan thanks for this.  Actually, I already have fixes ready for all of these (I just have not integrated them yet), so it's probably not the best use of your time.  Sorry, I should have been more explicit in the issue listing and assigned it to myself.
