### ISSUE TITLE
Default search message

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#803]
We need to add a message for when a search doesn't match any packages.

**Comment by nlhkabu** [comment]
This message should use

**Comment by di** [comment]
Hi @nlhkabu, is this close to what you had in mind?

Original:
<img width="852" alt="screen shot 2016-02-04 at 9 59 00 am" src="https://cloud.githubusercontent.com/assets/294415/12818720/f9a245f0-cb25-11e5-9354-8f9290b7cb62.png">
New:
<img width="849" alt="screen shot 2016-02-04 at 9 57 08 am" src="https://cloud.githubusercontent.com/assets/294415/12818669/ce177ce8-cb25-11e5-9c41-9e76129cb489.png">

Should the match count element stay, go away or be replaced by this message?

**Comment by nlhkabu** [comment]
That's great, thanks @di!

I don't think the duplication is a problem - it just reinforces the message.  

What would be **awesome** is if we could display some other search terms that are close to the input...

For example, if I search "Pyranid", I should see:

> There were no packages matching _Pyranid_ did you mean **Pyramid**

ping @dstufft and @HonzaKral - is this possible with elastic?

**Comment by dstufft** [comment]
Looks like it can, [Phrase Suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-phrase.html).

**Comment by HonzaKral** [comment]
Yes, as @dstufft mentioned - Phrase or Term suggesters is what you are looking for. The difference is that `terms` suggester is only looking at individual words in isolation whereas `phrase` is considering their use together. The simple demonstration is that terms suggester cannot see anything wrong with `"johnny walker"` (since both words are correct and exist in the index) whereas phrase suggester will suggest `"johnnie walker"`.

I would also suggest using completion suggester for auto complete, might help a lot. Let me know if you'd like to discuss the options in more detail, I an hop on irc. Thanks

**Comment by nlhkabu** [comment]
Fantastic!  @dstufft I'm guessing this is not on the list for "become PyPI" - so maybe we should open another issue?

**Comment by di** [comment]
Hi @nlhkabu, how does this look?

<img width="834" alt="screen shot 2016-02-04 at 5 22 51 pm" src="https://cloud.githubusercontent.com/assets/294415/12831749/f54e703a-cb63-11e5-9f95-de3a06f5f7e9.png">

The link leads to `/search/?q=pybankid`

(For whatever reason the `pyramid` package is not actually in the development DB, so `pybankid` is elasticsearch's best guess)

**Comment by dstufft** [comment]
The development DB uses a snapshot of the TestPyPI database. I could probably switch it to using a snapshot of the real PyPI database.

**Comment by nlhkabu** [comment]
@di - amazing!

One thing I am wondering - If I input 'dajngo' at the moment, I get 4 results (because some maintainers have spelled django incorrectly in their package descriptions)...

Is there a way to still provide this message if there is a similar result with a much larger set of results?

Something like:

> 4 results for 'Dajngo'.  Did you mean 'Django' (3902 results)?

**Comment by di** [comment]
@nlhkabu Sure thing! Here's what I've got:

If there are no results for the term, but the suggestion is a direct match for a package name, the suggestion is shown with no "result count" (and the default message is shown):

<img width="836" alt="screen shot 2016-02-05 at 10 28 45 am" src="https://cloud.githubusercontent.com/assets/294415/12850704/1c231702-cbf4-11e5-9e90-292206467627.png">

If there are no results for the term, but the top suggestion occurs multiple times, a suggestion with the "result count" is shown (and the default message is shown):

<img width="838" alt="screen shot 2016-02-05 at 10 28 59 am" src="https://cloud.githubusercontent.com/assets/294415/12850771/69596d1e-cbf4-11e5-8a3e-9986b7273dc3.png">

If the term has results, but the top suggestion occurs more frequently than the term, a suggestion is shown with the "result count":

<img width="837" alt="screen shot 2016-02-05 at 10 29 08 am" src="https://cloud.githubusercontent.com/assets/294415/12850791/8cde015a-cbf4-11e5-879f-ba755593a5a0.png">

And if there is no search term, nothing changes:

<img width="833" alt="screen shot 2016-02-05 at 10 29 38 am" src="https://cloud.githubusercontent.com/assets/294415/12850795/96759fde-cbf4-11e5-8908-3f260f26381f.png">

**Comment by dstufft** [comment]
This is awesome :sparkles:

**Comment by nlhkabu** [comment]
:+1: Looks great @di !
