### ISSUE TITLE
documentation: commands under "Dependency Management" need refinement

### ISSUE THREAD

**Issue by woodruffw** [pypa/warehouse#8032]
The [Dependency Management](https://warehouse.readthedocs.io/development/patterns/#dependency-management) section of the documentation page currently documents commands like these for adding and removing dependencies:

```bash
$ pip-compile --allow-unsafe --generate-hashes {file}.in
```

These are _slightly_ inaccurate, as the actual generated files are generated from the repository root and contain paths in comments that are relative to root. Running the commands as document will cause a lot of unnecessary `diff` churn.

Instead, the commands should be documented as:

```bash
$ pip-compile --allow-unsafe --generate-hashes --output-file={file}/main.txt {file}/main.in
```

...with emphasis placed on the fact that these commands should be run from the repo root.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/).

If you are working on this issue and have questions, feel free to ask them here, in the [`#pypa-dev` chat channel on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or on the [distutils-sig.python.org mailing list](https://mail.python.org/mailman3/lists/distutils-sig.python.org/).

**Comment by di** [comment]
I think we want:

```
$ pip-compile --allow-unsafe --generate-hashes --output-file=requirements/{file}.txt requirements/{file}.in
```

The examples are attempting to be agnostic to what `{file}` is being used, but they're all in the `requirements` directory.
