### ISSUE TITLE
Document how to translate strings

### ISSUE THREAD

**Issue by di** [pypa/warehouse#8040]
Our development guide includes references to working with translations in two places:

* ["Submitting patches"](https://warehouse.readthedocs.io/development/submitting-patches/) tells the developer how to use `make translations`
* ["Adding a newly completed translation"](https://warehouse.readthedocs.io/translations/#adding-a-newly-completed-translation) tells the developer how to add a newly completed translation

Neither of these guides tell the developer how to mark strings for translations (in Python files or in HTML templates), how to pluralize translated strings, and how/why to mark views as translatable.

Ideally, these sections would be added to https://warehouse.readthedocs.io/translations/ and referenced from https://warehouse.readthedocs.io/development/submitting-patches/.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/).

If you are working on this issue and have questions, feel free to ask them here, in the [`#pypa-dev` chat channel on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or on the [distutils-sig.python.org mailing list](https://mail.python.org/mailman3/lists/distutils-sig.python.org/).

**Comment by sandeep3136** [comment]
I will work on this issue. Please explain the issue clearly

**Comment by Manthan03583** [comment]
Can i work on this issue ?

**Comment by di** [comment]
Please note from the issue description:

> If there is not a corresponding pull request for this issue, it is up for grabs.

There is no corresponding pull request for this issue yet, so it's available to anyone to work on.

**Comment by di** [comment]
This should probably include how to pass non-translated values to translated strings, e.g.:

```
{% trans trimmed href=request.route_path('classifiers') %}
 Filter by <a href="{{ href }}">classifier</a>
{% endtrans %}
```

As well as examples of how to do everything in both the templates and in Python.
