### ISSUE TITLE
Assorted HTML cleanups

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#806]
All picked up in our accessibility review:

- [x] Add language to the `html` tag.  Currently we have: `<html class="no-js" lang="">`
- [ ] Remove hardcoded protocol on Google Font include (and any others)
- [x]  Remove `chrome=1` from `X-UA-Compatible`. It has been deprecated since Chrome Frame reached end-of-life in February 2014 (Poor Chrome Frame :crying_cat_face: )
- [ ] Set the button type to `submit` in the search forms

**Comment by dstufft** [comment]
Adding the ``lang`` attribute to the ``<html>`` tag was done in #832.

**Comment by dstufft** [comment]
Removing ``chrome=1`` from ``X-UA-Compatible`` was done in #848.
