### ISSUE TITLE
Is there any specific definition on classifiers?

### ISSUE THREAD

**Issue by rayluo** [pypa/warehouse#8064]
**What's the problem this feature will solve?**

[PyPI defines a list of classifiers](https://pypi.org/classifiers/) that can be used to describe a project, and then audience can even filter projects by them. But there seems no specific definition from the 2 referenced documents in the link above.

In particular, what is the definition of `Development Status :: 6 - Mature`? It seems to mean a software will no longer receive feature update, isn't it?

**Comment by jamadden** [comment]
The classifiers, according to [PEP 301])https://www.python.org/dev/peps/pep-0301/#distutils-trove-classification) are "Trove classifiers". At that time, Trove was [a particular project](http://www.catb.org/~esr/trove/) creating "an open-source distributed archiving system."


Meaning beyond those references, I suspect, is in the eye of the beholder.

I doubt you will find a more specific answer. Perhaps you could close this issue?

**Comment by rayluo** [comment]
Interesting. Thanks for sharing the info of this [2-decades old project](http://www.catb.org/~esr/trove/) and its 2-months old (partial) implementation. LOL

So, it seems:
* not even that original Trove project defines `Development Status`.
* but I managed to find some description from a [Google Book link to "Open Source Software: Quality Verification"](https://books.google.com/books?id=7pS6BQAAQBAJ&pg=PA34&lpg=PA34&dq=development+status+alpha+beta+stable+mature&source=bl&ots=jZQiKFvie-&sig=ACfU3U3qvmEn1g5EO3I6bVOZgapJXrMj4g&hl=en&sa=X&ved=2ahUKEwiUjry18OvpAhUWrJ4KHc4bC04Q6AEwAnoECAcQAQ#v=onepage&q=development%20status%20alpha%20beta%20stable%20mature&f=false) suggesting this was originated from SourceForge.net
* lastly, this is a relevant [blog post](https://martin-thoma.com/software-development-stages/)

Closing this issue.
