### ISSUE TITLE
Unable to run `make serve`: `"celery" executable file not found in path`

### ISSUE THREAD

**Issue by alexwlchan** [pypa/warehouse#808]
I’ve taken a clean checkout of the repository at commit f392327, but I’m unable to run the `make serve` command.

When I run `make serve` to start a local environment, it exits with an error. I’ve posted [full output from a clean run](https://gist.github.com/alexwlchan/be9660f4d564587ee73b) in a Gist; below is the output when I run the command a second time:

<pre><code>
alexwlchan at Alexs-iMac.local in ~/D/warehouse on git:master
$ make serve
docker-compose up
warehouse_redis_1 is up-to-date
Starting warehouse_app_1
warehouse_db_1 is up-to-date
warehouse_rabbitmq_1 is up-to-date
warehouse_static_1 is up-to-date
warehouse_elasticsearch_1 is up-to-date
<strong>Starting warehouse_worker_1
ERROR: Cannot start container 8b4f7a1476c15725720508ec5dc3ef5be82fb54942b55c6fcdb6b52ca583ed6b: [8] System error: exec: "celery": executable file not found in $PATH
make: *** [serve] Error 1</strong></code></pre>

Before I blow away my environment and start over (which I’d rather avoid, because it took quite a while to get to this stage, and it could easily fail in the same way again), any suggestions for what I should do next?

---

Further, possibly useful info:

The container is definitely known to Docker, and trying to run a celery command:

```
$ docker ps --all | grep 8b4
8b4f7a1476c1        warehouse_worker    "celery -A warehouse "   6 minutes ago       Created                                                          warehouse_worker_1
```

If I look inside the warehouse_worker image for celery-name-like files, I haven’t found anything useful:

```
$ docker run -it warehouse_worker sh
# find / -name *celery*
/app/warehouse/celery.py
/app/tests/unit/test_celery.py
# python /app/warehouse/celery.py -A warehouse
Traceback (most recent call last):
  File "/app/warehouse/celery.py", line 13, in <module>
    import celery.backends
  File "/app/warehouse/celery.py", line 13, in <module>
    import celery.backends
ImportError: No module named 'celery.backends'; 'celery' is not a package
```

Software versions:

* OS X 10.11.1 (15B42)
* Docker version 1.9.1, build a34a1d5
* docker-compose version: 1.5.1

**Comment by dstufft** [comment]
Can you try with #809? Make sure you run ``make purge`` first to clear out any state and see if it works?

**Comment by alexwlchan** [comment]
Indeed, running `make purge` and using the tip of dstufft:dont-rebuild (PR #809) seems to have got me past the celery issue. Thanks!

**Comment by dstufft** [comment]
Should be fixed in ``master`` now. Sorry about that!
