### ISSUE TITLE
Unable to install micropython-urequests

### ISSUE THREAD

**Issue by jjurotte** [pypa/warehouse#8087]
Hi
I am getting this when trying to install micropython-urequests. Same result on both my laptop and PC, both running Windows 10.

C:\Users\jjgli>pip install micropython-urequests
Collecting micropython-urequests
  Using cached https://files.pythonhosted.org/packages/1e/ac/bb123d5cd30bdfba6881f71adf01cefd3df2874d1d82e60a7e9f484790ce/micropython-urequests-0.9.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jjgli\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jjgli\\AppData\\Local\\Temp\\pip-install-2nei4xm7\\micropython-urequests\\setup.py'"'"'; __file__='"'"'C:\\Users\\jjgli\\AppData\\Local\\Temp\\pip-install-2nei4xm7\\micropython-urequests\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\jjgli\AppData\Local\Temp\pip-install-2nei4xm7\micropython-urequests\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\jjgli\appdata\local\programs\python\python38\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jjgli\\AppData\\Local\\Temp\\pip-install-2nei4xm7\\micropython-urequests\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\jjgli>

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
