### ISSUE TITLE
Change icon for changelog / history ?

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#8089]
On the package detail page, we currently show the "gift" icon for the following words:
"changelog", "change log", "changes", "release notes", "news", "what's new", "history"

e.g.

![Screenshot from 2020-06-10 22-01-39](https://user-images.githubusercontent.com/3323703/84318245-03622900-ab66-11ea-9a44-ce82a953d012.png)

Maybe this is not the best icon?
see https://github.com/pypa/warehouse/pull/7896#issuecomment-624788423

Maybe we should choose a different fontawesome icon?

---

**Screenshot Required**: This issue will require an update to the visual design of the site. To help our team give you faster feedback, include a screenshot in your Pull Request.

**Comment by scop** [comment]
I'm biased, but linking to my previous explanations which explain why I think the gift icon is a great choice for this, and why some others are not a good one:

https://github.com/pypa/warehouse/pull/7896#issuecomment-625018494
https://github.com/pypa/warehouse/pull/7896#issuecomment-624822886

**Comment by merwok** [comment]
To give a different opinion: I have seen the gift icons used in some proprietary web apps, tied to a «new features» menu.  I don’t find it an obvious icons for «changelog» in general.

The fa-history icon is already used for previous versions of a project, which is appropriate (the drawing suggests an action, going back in time, which is good for PyPI interface but wouldn’t fit a changelog link IMO).

Suggestion: fa-scroll :scroll: (evokes «document» more than «history», which I think is ok for changelog)

**Comment by boringow** [comment]
Hello! Can I take this issue as my first or second task to do in here? Although I do not find the "present" icon on the webpage.

**Comment by merwok** [comment]
@nlhkabu does your +1 on my comment mean that you recommend / decide on fa-scroll for this?

**Comment by scop** [comment]
> To give a different opinion: I have seen the gift icons used in some proprietary web apps, tied to a «new features» menu.

Firefox too, I think GitLab as well, anyway I think we can leave out the proprietary/not angle here.

> I don’t find it an obvious icons for «changelog» in general.

To remind, it's not being used only for changelog at the moment. One option if people feel strongly about this would be to split that in two and e.g. keep gift for release notes, what's new and news, and scroll for the rest. Not convinced myself that there's enough difference from user's point of view for doing that. I think "what's new" is essentially the question answered for people by that link and the reason for that link to exist prominently in PyPI in the first place (instead of "what's the change log" or "what's the history"), and gift conveys being an answer to that question better than scroll.
https://github.com/pypa/warehouse/blob/5f4a04652f19dd569f0595d7974edf524731314a/warehouse/templates/packaging/detail.html#L24

**Comment by merwok** [comment]
I don’t see any gift icon in Firefox modal windows, do you have a screenshot?

I agree that splitting the list of matched terms does not make sense.  I still don’t agree with 🎁 for a changelog 🙂

**Comment by scop** [comment]
Don't know about modal windows, nor do I have it visible in any of mine at the moment because I've peeked at what it has to show already. But searching for "firefox gift icon" brings up some examples, e.g. https://winaero.com/remove-whats-new-gift-box-icon-from-firefox/

**Comment by nlhkabu** [comment]
Thanks for your feedback everyone. I agree with @merwok's suggestion - I think we should change the 'gift' icon to `fa-scroll`

@boringow if you are interested in making your first PR, you can find the line to change here:
https://github.com/pypa/warehouse/blob/aafc5185e57e67d43487ce4faa95913dd4573e14/warehouse/templates/packaging/detail.html#L25

Not all projects have a changelog, so that's why you might not be able to see the icon on the interface.

**Comment by boringow** [comment]
changed it :)

**Comment by pradyunsg** [comment]
Sooooo, I'm a little bored. So here's a bunch of options for the right people to choose from:

---

fa-clipboard-list

<img width="307" alt="Screenshot 2021-02-27 at 2 30 05 PM" src="https://user-images.githubusercontent.com/3275593/109390248-610eef00-7908-11eb-85f5-d93ef46d8d61.png">

fa-history

<img width="307" alt="Screenshot 2021-02-27 at 2 27 35 PM" src="https://user-images.githubusercontent.com/3275593/109390249-610eef00-7908-11eb-8ac9-36865c4ab809.png">

fa-scroll

<img width="307" alt="Screenshot 2021-02-27 at 2 26 22 PM" src="https://user-images.githubusercontent.com/3275593/109390250-61a78580-7908-11eb-8f7f-8794b9e1e17f.png">

fa-gift (current)

<img width="307" alt="Screenshot 2021-02-27 at 2 26 07 PM" src="https://user-images.githubusercontent.com/3275593/109390251-61a78580-7908-11eb-8105-8a1e31e0a123.png">

fa-newspaper

<img width="307" alt="Screenshot 2021-02-27 at 2 25 58 PM" src="https://user-images.githubusercontent.com/3275593/109390252-62401c00-7908-11eb-9a75-0fd12cacaaf3.png">

**Comment by di** [comment]
I'm in favor of the scroll as well!

**Comment by pradyunsg** [comment]
I think the best fit for changelog-style content is gonna be `fa-history`; and for release notes, I'd say `fa-clipboard-list` works best.

**Comment by boringow** [comment]
I will also go for fa-history as @pradyunsg and if u are bored you could teach me a bit more!

**Comment by merwok** [comment]
history is used for the link to older releases, and it’s perfect there IMO (the icon is not just a clock but suggests going back to something).

newspaper and clipboard look great!  but I’d still pick scroll.

Pradyun, I’m not sure of the difference beteween a changelog and release notes.
