### ISSUE TITLE
Website search cannot find my package

### ISSUE THREAD

**Issue by thomasmfish** [pypa/warehouse#8106]
**Describe the bug**
When I [search "StitchM" on PyPI](https://pypi.org/search/?q=StitchM) it returns nothing despite [this package](https://pypi.org/project/StitchM/) existing. The exact same thing is happening on test.pypi.org. However, a [separate package](https://test.pypi.org/project/txrm2tiff/) that I uploaded at the same time is showing up in searches [here](https://pypi.org/search/?q=txrm2tiff).

**Expected behavior**
All existing packages should be findable when searching the package name.

**To Reproduce**
Follow the in-text links above.

**My Platform**
Using Chrome (83.0.4103.97) on MacOS Catalina

**Additional context**
"Curtains", another package with capitalisation, can be found.
Searching "stitch" doesn't find StitchM either.

**Comment by ewdurbin** [comment]
In the event that the initial indexing fails, search  may take up to 24 hours to index new projects.

**Comment by thomasmfish** [comment]
Okay, that's fine then, thanks!
