### ISSUE TITLE
Lint HTML

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#811]
Currently the HTML is not pure HTML5 (my mistake!!), as, for example, it still includes `/>` on image tags.

It would be great if we could install an HTML5 linter to catch this now and in future.

**Comment by dstufft** [comment]
This might be difficult since we don't actually have HTML files we have template files that just happen to output HTML. If you're aware of something that can handle that that'd be great, otherwise I'll see what I can find!

**Comment by nlhkabu** [comment]
https://pypi.python.org/pypi/html-linter/0.1.3 (or something else) with https://github.com/deezer/template-remover ?
