### ISSUE TITLE
Provide an api for for accessing request history

### ISSUE THREAD

**Issue by yaaminu** [pypa/warehouse#8112]
**What's the problem this feature will solve?**
This feature will allow developers to test that the right request payload are being sent

**Describe the solution you'd like**
```python
mock.get('url', body="some json", status=201)
call_function_under_test()
# assert that the function actually made the call with the right payload
assert mock.request_history[0].payload == {"user_id":"1223"}
```

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by yaaminu** [comment]
Ah, thanks. I followed the worng link!
