### ISSUE TITLE
Section name in .pypirc for testpypi should not be pypi

### ISSUE THREAD

**Issue by shuhari** [pypa/warehouse#8132]
**Describe the bug**
When I create a new API token in test.pypi.org, it gives tips as following screenshot.

However, after I copied the content to ~/.pypirc, then twine command still asks for password . I tried to resolve and found that it only works when the section name change from [pypi] to [testpypi].

It seemed that the tip is same with main PYPI site, but a bit misleading. Make it sync with current site could be more clear.

The problem should be not related to OS platform or browser types.

**Additional context**

![图片](https://user-images.githubusercontent.com/2049955/85017339-e77e0900-b19d-11ea-91b1-652e95ad4e45.png)

**Comment by di** [comment]
Thanks! Looks like we need to add some special logic here depending on what site this is on. Something similar to this should work:

https://github.com/pypa/warehouse/blob/6721a8aba73e13129f4400a64ff273099ce52850/warehouse/templates/accounts/login.html#L22-L26

I've added the "good first issue" label to this issue.
