### ISSUE TITLE
"Creating Mesh objects from a list of vertices and faces" fails on float Positions

### ISSUE THREAD

**Issue by SandUhrGucker** [pypa/warehouse#8134]
You describe on https://pypi.org/project/numpy-stl/ howto "Creating Mesh objects from a list of vertices and faces".

The folowing error ocurs if using float-coordinates:

```
    cube.vectors[i][j] = vertices[f[j],:]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```
**Describe the bug**
Doesnt work with floats (Which is motly used in RL I think).

**Expected behavior**
normal operation.

**To Reproduce**
Just modify some Verticses and Faces coordinates to floats.

**My Platform**
Ubuntu 10Buster tested with python 2.7,with
numpy 1.16.6

Ubuntu 10Buster and  python 3.6, with
numpy 1.18.5

Windows 10 python 3.8.3 with
numpy 1.18.4

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to [the tracker for the project in question instead](https://github.com/WoLpH/numpy-stl/issues).
