### ISSUE TITLE
Add custom fallback avatar for when Gravatar does not find an image

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#815]
Related #782

**Comment by di** [comment]
Currently this is using the default Gravatar fallback, which actually works pretty well for us, so I'm going to close this.

<img width="613" alt="Screen Shot 2020-03-24 at 3 59 07 PM" src="https://user-images.githubusercontent.com/294415/77476345-699da200-6de8-11ea-94f0-0aaf3b3d9ec4.png">
