### ISSUE TITLE
automatically build documentation for PRs

### ISSUE THREAD

**Issue by brainwane** [pypa/warehouse#8166]
@pradyunsg said:

> Pull Requests on pip's tracker automatically get their documentation built + made available for preview. It's a check called "docs/readthedocs.org:pip" in the list of checks on the PR, and "details" link on it, points to the preview.

> The section added in this PR is available at: https://pip--8493.org.readthedocs.build/en/8493/user_guide/#fixing-conflicting-dependencies

> Any changes made on this PR will also get reflected on that page. :)

_Originally posted by @pradyunsg in https://github.com/pypa/pip/pull/8493#issuecomment-649006820_

I'd like that! It'd help me with, for instance, the work I'm doing with #8011. (My local environment is messed up.) Can we set that up for Warehouse PRs as well, since we also use Read the Docs to build and host [our docs](https://warehouse.readthedocs.io/)?

**Comment by pradyunsg** [comment]
pip was a beta tester for this functionality in RTD, which has now become a checkbox to tick in the read the docs admin UI. 

https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by di** [comment]
I've checked the box, let's see what happens!

**Comment by brainwane** [comment]
@di  If you compare #8011 and https://github.com/pypa/pip/pull/8493 you see that the list of checks at the bottom of https://github.com/pypa/pip/pull/8493 includes

> docs/readthedocs.org:pip — Read the Docs build succeeded!  [link to docs]

I don't see that in the Warehouse PR (though I just force-pushed there). So I'm not sure the automated build is happening, or where I would look for the link.

**Comment by di** [comment]
OK, I've now checked the box, _and_ hit "Save", and #8011 now has a "docs/readthedocs.org:warehouse — Read the Docs build succeeded!" status.
