### ISSUE TITLE
it seems possible to upload a file without correct authentication

### ISSUE THREAD

**Issue by cameron-simpson** [pypa/warehouse#8167]
I use twine to upload my packages via upload.pypi.org/legacy/ and tripped over this through mistyping my password:

    + twine upload dist/cs.upd-20200626.tar.gz
    Uploading distributions to https://upload.pypi.org/legacy/
    Enter your username: cameron.simpson
    Enter your password:
    Uploading cs.upd-20200626.tar.gz
    100% .................
    NOTE: Try --verbose to see response content.
    HTTPError: 403 Client Error: Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information. for url: https://upload.pypi.org/legacy/

So, bad password, that makes sense. Then I reran with the correct password:

    + twine upload dist/cs.upd-20200626.tar.gz
    Uploading distributions to https://upload.pypi.org/legacy/
    Enter your username: cameron.simpson
    Enter your password:
    Uploading cs.upd-20200626.tar.gz
    100% ............
    NOTE: Try --verbose to see response content.
    HTTPError: 400 Client Error: File already exists. See https://pypi.org/help/#file-name-reuse for more information. for url: https://upload.pypi.org/legacy/

Regardless of what twine itself might do, doesn't this imply that my first upload succeeded? That seems wrong.

In case it's relevant, I'm using Python 3.7.7, twine-3.2.0-py3-none-any.whl on a Mac running MacOS Catalina. However, this seems like a server side issue.

**Comment by di** [comment]
I just tried to reproduce the same behavior and it worked as it should:

```
$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: di
Enter your password:
Uploading test-failed-upload-0.0.0.tar.gz
100%|██████████████████████████████████████| 3.31k/3.31k [00:00<00:00, 9.74kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Client Error: Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information. for url: https://upload.pypi.org/legacy/

$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: di
Enter your password:
Uploading test-failed-upload-0.0.0.tar.gz
100%|██████████████████████████████████████| 3.31k/3.31k [00:02<00:00, 1.48kB/s]

View at:
https://pypi.org/project/test-failed-upload/0.0.0/
```

It looks like `cs.upd==20200626` was [uploaded about 1 hour ago](https://pypi.org/project/cs.upd/20200626/), is it possible you had already uploaded it? Or did you only invoke twine these two times?

Is it possible you're trying to upload a newer release and actually want to call `twine upload --skip-existing dist/*`?

**Comment by cameron-simpson** [comment]
Gah! You are correct, I had an even earlier successful upload.

My apologies, I'll close this. My error. Thanks, Cameron
