### ISSUE TITLE
Copy pip command and sha256 hash on click (relies on #819)

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#818]
Clicking on the copy icon should copy the content to the clipboard:

On the package page:
![pip](https://cloud.githubusercontent.com/assets/3323703/11322702/5b3bd4ea-90f0-11e5-88f6-967a7878c8bc.png)

On the downloads tab on the package page:
![md5](https://cloud.githubusercontent.com/assets/3323703/11322701/5541d8e6-90f0-11e5-85fd-b845eb8699b5.png)

I would like this to work with a tooltip as on Github:
![copy-to-clipboard](https://cloud.githubusercontent.com/assets/3323703/11322714/ce826af4-90f0-11e5-83bf-99589936aa5a.png)

![copied](https://cloud.githubusercontent.com/assets/3323703/11322713/ce7f1eda-90f0-11e5-85f3-ec0737d3f2b8.png)

Relies on #819

**Comment by domenkozar** [comment]
Could we instead of insecure `md5` use `sha256`? New PyPI could be a chance to fix this.

**Comment by nlhkabu** [comment]
@domenkozar something to talk to @dstufft about :)  - Can you please open another issue for this, as I don't want that discussion to take over this thread.

**Comment by nlhkabu** [comment]
@domenkozar in fact - this is already being discussed at #681

**Comment by domenkozar** [comment]
I've opened https://github.com/pypa/warehouse/issues/820, sorry for the noise here.

**Comment by alex** [comment]
https://clipboardjs.com/ is pleasant to use from my experience

**Comment by dstufft** [comment]
This is implemented now in #1245!
