### ISSUE TITLE
SHA mismatch with Tensorflow

### ISSUE THREAD

**Issue by akshayb7** [pypa/warehouse#8180]
Describe the bug
While trying to install tensorflow==2.1.0 in a docker container, an SHA mismatch happens

I'd created another container (small unrelated differences) without such an issue about a week ago, so might be someone messing with the codebase.

Expected behavior
Tensorflow installs without such an error.

My Platform
Docker community edition - 19.03.8

![image](https://user-images.githubusercontent.com/29649801/86093578-d05be700-bacc-11ea-8b73-5d7bcff6c65f.png)

**Comment by jamadden** [comment]
(Please avoid posting screenshots of errors when unnecessary. Please post the actual text. Screenshots are not accessible, cannot be quoted, or easily compared, etc. Thanks!)

If I download what I think is the same distribution and check its sha256, I get the expected value.

```console
$ wget https://files.pythonhosted.org/packages/1d/56/0dbdae2a3c527a119bec0d5cf441655fe030ce1daa6fa6b9542f7dbd8664/tensorflow-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl
--2020-06-30 06:05:54--  https://files.pythonhosted.org/packages/1d/56/0dbdae2a3c527a119bec0d5cf441655fe030ce1daa6fa6b9542f7dbd8664/tensorflow-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl
Loaded CA certificate '/opt/local/share/curl/curl-ca-bundle.crt'
Resolving files.pythonhosted.org (files.pythonhosted.org)... 2a04:4e42::319, 2a04:4e42:200::319, 2a04:4e42:400::319, ...
Connecting to files.pythonhosted.org (files.pythonhosted.org)|2a04:4e42::319|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 421812652 (402M) [binary/octet-stream]
Saving to: ‘tensorflow-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl’

tensorflow-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl                                                                         100%[======...====>] 402.27M  47.7MB/s    in 7.6s

2020-06-30 06:06:02 (53.0 MB/s) - ‘tensorflow-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl’ saved [421812652/421812652]

$ sha256sum ./tensorflow-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl
92c4f1c939de438fbe484d011e5eebe059fc8e5244cfe32a81c6891b3357d109  ./tensorflow-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl
```

Perhaps there's corruption in your local pip cache? I've seen that happen before.

**Comment by akshayb7** [comment]
Yes that was the reason. Using  `--no-cache-dir`  did the trick. Thank you for your help. Closing the issue now.

(I'll also keep in mind to not post screenshots from now.)
