### ISSUE TITLE
Ordering at /stats is incorrect for TestPyPI

### ISSUE THREAD

**Issue by di** [pypa/warehouse#8188]
The list at https://test.pypi.org/stats/ is incorrect and lists projects with 0 bytes first:

<img width="736" alt="Screen Shot 2020-07-01 at 10 06 59 AM" src="https://user-images.githubusercontent.com/294415/86260240-a06f1b00-bb82-11ea-8940-4cc7aced95f6.png">

The 0-byte projects should not be included in that list. 

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/).

If you are working on this issue and have questions, feel free to ask them here, in the [`#pypa-dev` chat channel on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or on the [distutils-sig.python.org mailing list](https://mail.python.org/mailman3/lists/distutils-sig.python.org/).

**Screenshot Required**: *If your pull request makes a visual change*, include a screenshot of your update. This helps our team give you feedback faster.

**Comment by imsahil007** [comment]
How can we add a new empty package while running this locally?

**Comment by di** [comment]
Hi @imsahil007, you can modify any package from the development shell:

```
$ make shell
docker-compose run --rm web python -m warehouse shell
Starting warehouse_notdatadog_1 ... done
Starting warehouse_elasticsearch_1 ... done
Starting warehouse_redis_1         ... done
Starting warehouse_localstack_1    ... done
Starting warehouse_db_1            ... done
Python 3.8.2 (default, Apr 23 2020, 14:32:57)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from warehouse.packaging.models import Project
>>> p = db.query(Project).first()
>>> p.total_size
12521
>>> p.total_size = None
>>> db.commit()
>>> p.total_size == None
True
```

However I should mention that someone is already working on this issue in #8021 .

**Comment by imsahil007** [comment]
> docker-compose run --rm web python -m warehouse shell

Okay. Thanks for the help though!
