### ISSUE TITLE
Integrate tooltip library

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#819]
Requirements:
- We should be able to invoke the tooltip on hover or click
- The tooltip should work with all directions (top, left, bottom, right)

It would be nice if the plugin could automatically calculate the best direction, though this is not essential.

Organisation:
Please put all relevant CSS into a new file at:
`https://github.com/pypa/warehouse/tree/master/warehouse/static/sass/components/_tooltip.scss`

**Comment by karan** [comment]
OK to close this @nlhkabu?
