### ISSUE TITLE
Replace md5 with sha256 on UI

### ISSUE THREAD

**Issue by domenkozar** [pypa/warehouse#820]
Since PyPI is being rewritten, it's a good opportunity to replace md5 hashes with sha256.

NOTE: there is also #681 which talks about the upload functionality related to md5

**Comment by nlhkabu** [comment]
Related #681

**Comment by dstufft** [comment]
It's planned to do that yes. It requires a bit of work to migrate everything because we have to loop over *all* of the current packages and recompute their hashes.
