### ISSUE TITLE
[Question] Is there a dataset of all pypi projects with title & description?

### ISSUE THREAD

**Issue by youssefavx** [pypa/warehouse#8212]
I'm looking for a CSV of all pypi projects which are python 3 and 2 compatible. It seems the website only displays the first 10K results. I want a list of the projects with [Title, Description, Other properties] etc. 

The reason I want to do this is I want to generate embeddings for each project description to be able to do a semantic similarity search whenever I need a package.

**Comment by di** [comment]
Not yet, but this will be possible once https://github.com/pypa/warehouse/issues/7403 is resolved.

One alternative would be to query the [JSON API](https://warehouse.readthedocs.io/api-reference/json/) for every project listed at https://pypi.org/simple/.

Closing as a duplicate of #7403, but thanks for asking!

**Comment by youssefavx** [comment]
Thank you so much! Exciting to hear, I'll try that option.
