### ISSUE TITLE
Create a help page

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#825]
Our lead writer for the PYPUG rewrite has suggested that we have a page in between Warehouse and PYPUG, as per below:
 
![help](https://cloud.githubusercontent.com/assets/3323703/11332809/95102c7c-91c0-11e5-8731-90e1cfa2c5cd.png)

**Comment by souravsingh** [comment]
I will work on the issue

**Comment by nlhkabu** [comment]
Closed with last PR.
