### ISSUE TITLE
Add a date to the release history?

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#826]
One thing I had in the old Warehouse design that I thought was useful was on the list of all releases for a project, I had the dates listed for each one. That let me get a sense of cadence of the entire project and if something started failing around a particular date I could easily see if a release occurred around that time.

It might be useful to add this?

**Comment by nlhkabu** [comment]
Yes, good idea!
For now, let's add it as an additional `<p>` at the bottom of the `.version` div.

**Comment by Ivoz** [comment]
+5000
