### ISSUE TITLE
files.pythonhosted.org can randomly return 503 errors even with 3 retries

### ISSUE THREAD

**Issue by ssbarnea** [pypa/warehouse#8260]
We recently found on OpenStack builds that occasionally requests sent to files.pythonhosted.org can return 503 errors, even 3 times in a raw, causing pip to fail.

For performance and reliability reasons we do have mirrors implemented, but they cannot help when we have a single upstream that returns the same failure.

Example: https://opendev.org/opendev/system-config/src/branch/master/playbooks/roles/mirror/templates/mirror.vhost.j2#L94

While the 503 issue with the CDN needs investigation by itself, it would be extreamly useful to have a backup-fallback address that we can use for transient errors like 503.

So we could reconfigure our mirror to try the backup when it receives a 503, which would likely be a 200 that would avoid a build failure.

**Comment by fungi** [comment]
To be clear, it's not a mirror of PyPI, it's a caching proxy. The 503 responses we saw were for various files and spanned a little over 5 minutes between 10:40:55 and 10:46:19 UTC from two different public clouds in Quebec, Canada. We did not see any similar errors elsewhere globally, leading me to suspect the issue could be limited to one of the Fastly CDN endpoints in the Quebec area.

**Comment by dstufft** [comment]
So is this a recurring issue, or did it only occur during that 5 minute period? I do see a short blip where all of Fastly went to "degraded performance" on their status page this morning.

**Comment by fungi** [comment]
According to our proxy logs, this is the only occurrence over the past two weeks.

**Comment by di** [comment]
Seems like this is almost definitely https://status.fastly.com/incidents/f7hg0w5c078c then, which lasted from 10:42 UTC until 11:05 UTC.

**Comment by ssbarnea** [comment]
While I doubt that there is something PYPA can do to make fastly be 100% reliable, I think that documenting a fallback server to be used could be a viable measure to ameliorate CDN flakiness. What do you think? It can be something very-very slow, also its log could prove as very useful source of information regarding how often the CDN misbehaves.

**Comment by di** [comment]
PyPI has no SLA on uptime. Generally if the potential for this kind of flakiness is disruptive for you, we recommend hosting your own mirror (https://packaging.python.org/guides/index-mirrors-and-caches/ has details).

But it seems like you're maybe already doing that? Why did the mirror need to reach upstream for this particular install? Generally a mirror would only claim to host the distributions it's been successfully able to mirror.

**Comment by ewdurbin** [comment]
Another issue with fallback would be that people would begin to just point at that rather than our CDN :/

Currently everything that could/would act as a publicly available fallback has very high costs for bandwidth that we need to reserve for CDN to backend. If users began using the fallback exclusively it would make managing our costs difficult.

**Comment by fungi** [comment]
To reiterate my earlier comment, "it's not a mirror of PyPI, it's a caching proxy."

We did run a PyPI mirror network at one time, and were one of the driving communities behind a number of improvements in bandersnatch, but once projects like tensorflow started uploading nightly datasets and ballooned the storage requirements by an order of magnitude we had to stop. Switching to maintaining caches inside each of our CI providers was a choice to reduce our maintenance burden at the potential expense of additional occasional retrieval errors.

Also yes, I know PyPI has no SLA (neither do we). I don't personally think that a 5-minute outage for a CDN endpoint in one corner of the World is worth sinking engineering time into building a workaround for, there are plenty of other ways fetching packages can fail and you can't realistically implement solutions for each and every one or the system as a whole would become so complex that the complexity itself would contribute to worse outages.

I'm not personally advocating for any solutions or fallbacks here, I'm merely attempting to set the record straight after one of our users opened this GH issue and asked me to comment on it.

**Comment by dstufft** [comment]
I'm going to go ahead and close this issue even though I asked the reporter to open it. I was under the impression that this was a long standing issue with intermittent 503 errors and wanted an issue to track them and determine if we could do something to fix those issues.

However, given that this was just a temporary outage and not a long standing intermittent problem, I don't believe that there are real actionable items for us here that are worth any additional complexity or engineering effort to solve. Projects are free to setup their own fallback if desired, or they'll have to deal with occasional downtime that might occur in a single shared service.

**Comment by ssbarnea** [comment]
I am 100% sure I seen multiple similar 503 issues over the last year and I doubt the CDN used a [retry-after](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header when it did this because, clearly pip still failed in the end.

I could attempt to add a task that grep the logs and auto-create a bugs whenever I receive a 503? Would this motivate PYPA to do consider it as a real issue?

Looking from the consumer point of view, I can see an unreliable chain in client-server implementation. The package failed to reach the consumer. In fact this issue has nothing to do with using a proxy/mirror.

I think that you are looking at the problem from the wrong angle: is not about today's 10min outage, is about finding a solution where consumers are not affected by glitches in the matrix. 

This is about finding a solution that avoids build failures even in the presence of intermitent networking issues. I be a Netflix engineer would not have closed the bug with a "not my problem".

Is it really so hard to just say "use x.y.z if files.pythonhosted.org fails"?

**Comment by dstufft** [comment]
it is non trivial to operate another package repository that can withstand the traffic that PyPI gets yes. For one if these are truly intermittent errors, then by the time the user plumbs in the fallback index into their command then it will have resolved itself. The other option is to have it always configured in pip all the time, but that is a non trivial amount of traffic that we would have to support a parallel deployment of.

There's nothing that requires us to run a mirror of PyPI, if you feel this is a service that is severely lacking, I encourage you to stand that up on your own. Our resources are finite and we do not have the resources to do this.

**Comment by ssbarnea** [comment]
This is happening again and was like this for >5h, and results are easy to read http://status.openstack.org/elastic-recheck/

PS. As I do not think it is ok to use the same issue tracker for operational issues, I opened a thread on https://discuss.python.org/t/any-chance-to-an-issue-tracker-for-pypi-org-operational-problems/5219 -- hoping that we endup with a separated place where we can track ops issues and find solutions for them.
