### ISSUE TITLE
Getting Error as "ValueError: Zip does not support timestamps before 1980" while installing Setuptools-scm Pypi

### ISSUE THREAD

**Issue by Rameshaaa** [pypa/warehouse#8266]
**Describe the bug**

Am working on Client machine where i don't have access for external severs. So i have to download the packages from Python websites and extract the zip-files and i have to install the packages in my machine by passing a command "python setup.py install in Command prompt. First two packages (Selenium and urllib3) working fine in my machine and setup also good. 

I have try to install the Pytest Pypi but that requires setuptools-scm. So i downloaded the setuptools-scm packages and i try to to install it but **Getting error as ValueError: Zip does not support timestamps before 1980.**

**Expected behavior**

Setuptools-scm should be installed 

**To Reproduce**

Download the setuptools-scm package from https://pypi.org/project/setuptools-scm/
Extract the zip-files and installing the setuptools-scm by passing **python setup.py install**
Observe that **Getting error as ValueError: Zip does not support timestamps before 1980.**

**My Platform**

Problem with command line tool. Version 10.0.17763.1282

**Additional context**

![Zip Error Python](https://user-images.githubusercontent.com/68278771/87512909-7561ec80-c695-11ea-8483-62ed7911c26d.png)

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there. You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page; in this case it is https://github.com/pypa/setuptools_scm/

I will add that `pip` can install directly from downloaded built wheels, so there's probably no need to manually run `setup.py install`. Something like this:

```console
$ python -mensurepip
$ wget https://files.pythonhosted.org/.../setuptools_scm-4.1.2-py2.py3-none-any.whl
$ python -m pip --no-index --disable-pip-version-check install setuptools_scm-4.1.2-py2.py3-none-any.whl 
Processing ./setuptools_scm-4.1.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /.../site-packages (from setuptools-scm==4.1.2) (44.0.0)
Installing collected packages: setuptools-scm
Successfully installed setuptools-scm-4.1.2
```
