### ISSUE TITLE
TUF implementation should consider blessing distribution mirrors

### ISSUE THREAD

**Issue by jku** [pypa/warehouse#8277]
(Filing this based on discussion with @woodruffw)

**What's the problem this feature will solve?**

Currently clients when downloading distributions will take URLs they find in `https://pypi.org/simple/<project>/` and download them -- from whatever host the URL happens to point to. 

**Describe the solution you'd like**

Once TUF is in use we may want to use the verified metadata we are already passing to inform the clients of the distribution mirrors they should trust (at the moment "files.pythonhosted.org"): this way an attack that manages to modify `https://pypi.org/simple/<project>/` can not trick clients to even download files from random hosts.

Note that this is not required to get a TUF client working: the client can just believe `https://pypi.org/simple/<project>/` and download from whatever host is listed there: the distribution will be verified after download.

**Comment by jku** [comment]
It should probably be noted that reproducing pypi.org (let's say a company internal mirror with only curated upstream distributions available) might work pretty well with TUF... but the addition I suggest would break this case. Nothing a little client configuration couldn't fix but this may be worth considering (no idea if this a common use case)?

**Comment by dstufft** [comment]
A lot of companies mirror PyPI yes, there is tooling for doing that at https://pypi.org/project/bandersnatch/ that we wouldn't want to break.

**Comment by jku** [comment]
When I filed this it was not clear the project index files will be verified by tuf. This is actually the case so this issue is probably not very relevant. I think it can be closed.

**Comment by pradyunsg** [comment]
Closed as requested.
