### ISSUE TITLE
Markdown long description parsed as rst on py3 upload

### ISSUE THREAD

**Issue by djmitche** [pypa/warehouse#8281]
```
lamport ~/p/taskcluster-lib-urls/src/github.com/taskcluster/taskcluster-lib-urls [master] $ twine upload dist/*
Enter your username: djmitche
Enter your password: 
Uploading distributions to https://upload.pypi.org/legacy/
Uploading taskcluster_urls-13.0.1-py2-none-any.whl
..
Uploading taskcluster_urls-13.0.1-py3-none-any.whl
..
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/
```

So the upload works just fine for py2, but not for py3.  The setup.py has

```
    long_description=open(os.path.join(os.path.dirname(__file__), 'README.md')).read(),
    long_description_content_type='text/markdown',
```

**Comment by di** [comment]
Can you attach the distribution you're trying to upload here?

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster-lib-urls/blob/master/setup.py (or did you mean to attach the file itself?)

**Comment by di** [comment]
The file itself, thanks!

**Comment by djmitche** [comment]
[taskcluster_urls-13.0.1-py3-none-any.whl.gz](https://github.com/pypa/warehouse/files/4939289/taskcluster_urls-13.0.1-py3-none-any.whl.gz)

(GitHub wouldn't handle the .whl, so I gzipped it)

**Comment by djmitche** [comment]
I see that that contains a `DESCRIPTION.rst`, although `METADATA` contains `Description-Content-Type: text/markdown`

**Comment by di** [comment]
The issue is that the wheel was built with `wheel==0.30.0`:

```
$ cat taskcluster_urls-13.0.1.dist-info/WHEEL | grep Generator
Generator: bdist_wheel (0.30.0)
```

This results in producing metadata with version 2.0 of the spec:
```
$ cat taskcluster_urls-13.0.1.dist-info/METADATA | grep Metadata-Version
Metadata-Version: 2.0
```

The `Description-Content-Type` field is not supported until version 2.1: https://www.python.org/dev/peps/pep-0566/

You should update to `wheel>=0.31.0` and rebuild your distribution.

**Comment by djmitche** [comment]
Great success!  I think I missed that my py3 environment had an old wheel.  Thank you!
