### ISSUE TITLE
guietta error

### ISSUE THREAD

**Issue by mahanthkj** [pypa/warehouse#8290]
Python version used : 3.7

kindly help to resolve this issue.
script :
from guietta import _, Gui, Quit

gui = Gui(

  [  'Enter numbers:', '__a__'  , '+' , '__b__',  ['Calculate'] ],
  [  'Result:  -->'  , 'result' ,  _  ,    _   ,       _        ],
  [  _               ,    _     ,  _  ,    _   ,      Quit      ]
)

with gui.Calculate:
    gui.result = gui.a + gui.b

gui.run()

### **Error:**
C:\Users\labuser\Downloads\temp>python cguietta.py
Traceback (most recent call last):
  File "cguietta.py", line 11, in <module>
    gui.result = gui.a + gui.b
  File "C:\Users\labuser\AppData\Local\Programs\Python\Python37\lib\site-packages\guietta\guietta.py", line 159, in __exit__
    raise ValueError('Could not determine the Gui instance identifier')
ValueError: Could not determine the Gui instance identifier

C:\Users\labuser\Downloads\temp>

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by mahanthkj** [comment]
I am not sure if you can help me to find the guietta project tracker . 

Thanks in advance !!

**Comment by jamadden** [comment]
On the [PyPI project page for guietta](https://pypi.org/project/guietta/) look in the left column for the link to 'open issues'.
