### ISSUE TITLE
Unable to access PyPI's CDN (files.pythonhosted.org) on macOS with IPv6 connectivity

### ISSUE THREAD

**Issue by segevfiner** [pypa/warehouse#8292]
**Describe the bug**
I'm unable to use pip to install any packages due to it failing to access PyPI's CDN (files.pythonhosted.org), and sometimes PyPI itself, on macOS with IPv6 connectivity (Enabled & available on the network, this is a true dual-stack network, with both real IPv4 & IPv6 address, I know, right? An actual ISP that does that)

The socket gets immediately closed on connection which leads to errors like this (Which are retried until eventually giving up):

```
Could not fetch URL https://pypi.org/simple/requests/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/requests/ (Caused by ProtocolError('Connection aborted.', OSError(22, 'Inv    alid argument'))) - skipping
```

```
HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl (Caused by ProtocolError('Connection aborted.', OSError(22, 'Invalid argument')))
```

`getpeername` on macOS returns with errno `EINVAL` when the socket is closed.

Disabling IPv6 external connectivity by setting "Configure IPv6" to "Link-local only" in macOS network preferences causes `pip` to work again, but is obviously not desired.

**Expected behavior**

For `pip install` to work. Even with IPv6 connectivity on macOS.

**To Reproduce**

```
pip install -v requests
```

Literally any request to PyPI when you have IPv6 connectivity.

**My Platform**

pip version 20.1.1
Python 3.8.4 from Homebrew
macOS 10.14.6
A dual-stack IPv4/IPv6 network. Has both a public IPv4 address behind local router NAT, and IPv6 connectivity.

**Additional context**

[log.txt](https://github.com/pypa/warehouse/files/4946028/log.txt) from running `pip install -vvv requests`

**Comment by jamadden** [comment]
Hi! Could you please open this issue in https://github.com/pypa/pypi-support/issues using the "Network Access Issue" template? That requests some information that helps debug the problem.

FWIW, I'm in the same situation (IpV4 nat, public IPv6) on macOS and haven't experienced this problem, so it's not universal.
