### ISSUE TITLE
Using undeclared dependency attrs

### ISSUE THREAD

**Issue by ewjoachim** [pypa/warehouse#8299]
**Describe the bug**

From @di 

Regarding:
https://github.com/pypa/warehouse/blob/b344984ee83126eb6fc541406d1f34719fad8b6b/warehouse/email/services.py#L36

> Currently attrs is not a top-level dependency of Warehouse, it's only available as a sub-dependency of automat. If we truly need to use attrs here, it should be added to https://github.com/pypa/warehouse/blob/master/requirements/main.in and those dependencies should be re-compiled.

(source: https://github.com/pypa/warehouse/pull/7124#discussion_r453729298)

**Expected behavior**

attrs should be added in main.in OR removed from the codebase.

**Comment by di** [comment]
I've added the "good first issue" label to this issue.

I also said on that comment: 

> However I think I'd prefer to just use a regular class here.

**Comment by ewjoachim** [comment]
Ah, I didn't know if it applied here too ! :)
