### ISSUE TITLE
redirect loop when uploading package named bleach_allowed_list followed by bleach-allowed-list

### ISSUE THREAD

**Issue by graingert** [pypa/warehouse#8318]
**Describe the bug**

redirect loop on the URL: https://pypi.org/project/bleach-allowed-list/
after uploading package named bleach_allowed_list followed by bleach-allowed-list
it's fixed now, because I deleted the bleach_allowed_list release.

**Expected behavior**
no redirect loop

**To Reproduce**
^

**My Platform**
N/A
**Additional context**

**Comment by graingert** [comment]
I tried it again here, but I can't repeat it :( https://pypi.org/project/bleach-allowlist/0.0.0a2/ https://pypi.org/project/bleach-allowlist/0.0.0a0/

**Comment by di** [comment]
Closing this as not reproducible (I couldn't duplicate it), feel free to reopen if you can find a way to reproduce.
