### ISSUE TITLE
Dependabot is not bumping the version of Sphinx. 

### ISSUE THREAD

**Issue by shireenrao** [pypa/warehouse#8348]
The Sphinx version was stuck at 3.0.3, where as the latest version is at 3.1.2. For some reason, Dependabot is not working here.

**Comment by shireenrao** [comment]
I was trying to figure this out, and couldn't see where dependabot is setup. I thought it was under Security, but dont see it there. Can anybody point me in the right direction?

**Comment by di** [comment]
Dependabot is configured via the files in the repository. We don't have a `.dependabot/config.yml` file, so it should be picking up on the `requirements.txt` file in the root of the repo.

It might make sense to move to a `.dependabot/config.yml` file though, as the `requirements.txt` file isn't used by anything else and sometimes confusing to developers trying to get started with the project.

**Comment by di** [comment]
Actually here's a screenshot of what Dependabot is currently configured to do:

![image](https://user-images.githubusercontent.com/294415/88975885-aee34c00-d280-11ea-8c49-d6dba15597b5.png)

I'm not sure what to make of this, it seems to include the `docs.txt`. It might be better to be more explicit about this with a configuration file.

**Comment by shireenrao** [comment]
I wonder if it's because docs has two sets configurations in the screenshot 

- Docs/requirements.txt
- requirements/docs.txt

The versions in both are different.

**Comment by di** [comment]
Ah, good catch! That might be the culprit. I think that probably exists to configure ReadTheDocs maybe?

**Comment by shireenrao** [comment]
The last time Dependabot updated both the files was Nov 12, 2018 for version 1.8.2 (#5044). Since then requirements/docs.txt has been updated manually.
