### ISSUE TITLE
Package not listed in https://pypi.org/simple/

### ISSUE THREAD

**Issue by OSHI7** [pypa/warehouse#8385]
Hello, 
This is similar to [issue](https://github.com/pypa/warehouse/issues/5017): but I am unable to resolve.  

**Describe the bug**
I recently uploaded a new package to the PyPI (https://pypi.org/project/matlablib/), and it successfully appears at https://pypi.org/simple/matlablib/, but not in the index at https://pypi.org/simple/. This is my first package, so I may be doing something incorrect.  Alternately, I am not sure if there is something going on with the index cache. I have checked on some other new packages, and they seem to be getting through okay.

Note that installation via pip still works fine, but if the package does not appear in this index ( https://pypi.python.org/simple), then PyCharm cannot pick up the package. Additionally, I believe that additionally mirrors and proxies of the pypi index cannot then pick up the package either.

**Expected behavior**
The package (matlablib) should appear in the global list of packages.

To Reproduce
$ curl https://pypi.org/simple/ | grep matlablib

**Comment by di** [comment]
See also https://github.com/pypa/warehouse/issues/7384: it takes ~24 hours for projects to appear on `/simple`. This shouldn't affect installability as installers go directly to the project's simple page, e.g.: https://pypi.org/simple/matlablib/

**Comment by OSHI7** [comment]
Hello di,
Yes! You are correct.   It is up today, ~24 hours later, as you said.
Thanks for taking the time to respond to the ticket.   Let's close this one up.

Much appreciated, & thanks again.
Regards,
Josh

**Comment by di** [comment]
I created an upstream issue with PyCharm here: https://youtrack.jetbrains.com/issue/PY-44003
