### ISSUE TITLE
Slack PIP (Slack API) replaced with https://github.com/zweifisch/slack

### ISSUE THREAD

**Issue by sfdc-jd** [pypa/warehouse#8401]
**Describe the bug**
The PIP called "Slack" used to be an API for Slack.
It now installs something from https://github.com/zweifisch/slack

**Expected behavior**
The Slack API library should be installed

**To Reproduce**
pip install slack
pip show slack

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, are you thinking of https://pypi.org/project/slackclient/?

**Comment by ewdurbin** [comment]
Hello @sfdc-jd. The project `slack` on PyPI has not changed since 2014-05-14. You may be installing the wrong project.

**Comment by sfdc-jd** [comment]
Looks like "slackclient" installs in "lib/python3.8/site-packages/slack". That's the confusion. Thanks!
