### ISSUE TITLE
[Python 3.8.3] Cannot add_argument in argparse 1.4.0

### ISSUE THREAD

**Issue by dungdoant** [pypa/warehouse#8410]
[Python 3.8.3 64bit] Cannot add_argument in argparse 1.4.0

Describe:
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--input", type=str, default="", help="path to input image")

**Expected behavior**
Command is running without errors.

**Observed behavior**
C:\Program Files\Python38\Lib\site-packages>python
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import argparse
>>> argparse.__version__
'1.4.0'
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument("-i", "--input", type=str, default="", help="path to input image")
_StoreAction(option_strings=['-i', '--input'], dest='input', nargs=None, const=None, default='', type=<class 'str'>, choices=None, help='path to input image', metavar=None)
>>>

**To Reproduce**
Follow the codes.

**My Platform**
Python 3.8.3 64bit
argparse 1.4.0
Win7 64bit

**Additional context**
not yet

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
