### ISSUE TITLE
New packages not appearing in pypi.org/simple index

### ISSUE THREAD

**Issue by wwmx** [pypa/warehouse#8416]
I have read closed bug #5017,#8385. But ...

**Describe the bug**
I recently uploaded a new package to the PyPI (https://pypi.org/project/whois11/), and it successfully appears at https://pypi.org/simple/whois11/, but not in the index at https://pypi.org/simple/. This is my first package, so I may be doing something incorrect. Alternately, I am not sure if there is something going on with the index cache. I have checked on some other new packages, and they seem to be getting through okay.

About 36 hours have already passed, but it's not indexed.

NOTE1 that installation via pip still works fine, but if the package does not appear in this index ( https://pypi.python.org/simple), then PyCharm cannot pick up the package. Additionally, I believe that additionally mirrors and proxies of the pypi index cannot then pick up the package either.
NOTE2 that the package appears in test index ( https://test.pypi.org/simple) when I uploaded to testpypi(https://test.pypi.org/legacy/).

**Expected behavior**
The package (whois11) should appear in the global list of packages.

**To Reproduce**
$ curl https://pypi.org/simple/ | grep whois11

**Comment by wwmx** [comment]
Now, it is listed, after about 44 hours.

**Comment by di** [comment]
I created an upstream issue with PyCharm here: https://youtrack.jetbrains.com/issue/PY-44003

**Comment by wwmx** [comment]
I saw https://youtrack.jetbrains.com/issue/PY-44003
Sorry, but I think it's a misguided answer.

Perhaps most PyCharm users raise this issue with the purpose of publishing the new package, not with what the test wants to do.

In other words, the true purpose is to be added to a new packeage to the package list in Pycharm.
To get the package list, Pycharm references a https://pypi.org/simple (https://pypi.python.org/simple)
