### ISSUE TITLE
500 error when uploading with breached password

### ISSUE THREAD

**Issue by F1ashhimself** [pypa/warehouse#8431]
**Describe the bug**
Uploading package with twine fails with 500 Internal Server Error.

```
e:\Git\ui-map-parser>twine upload dist\ui_map_parser-1.0.0-py3-none-any.whl --verbose
Uploading distributions to https://upload.pypi.org/legacy/
  dist\ui_map_parser-1.0.0-py3-none-any.whl (10.0 KB)
Uploading ui_map_parser-1.0.0-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15.5k/15.5k [00:06<00:00, 2.54kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 1 of 5
Uploading ui_map_parser-1.0.0-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15.5k/15.5k [00:05<00:00, 2.93kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 2 of 5
Uploading ui_map_parser-1.0.0-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15.5k/15.5k [00:05<00:00, 2.73kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 3 of 5
Uploading ui_map_parser-1.0.0-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15.5k/15.5k [00:05<00:00, 2.93kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 4 of 5
Uploading ui_map_parser-1.0.0-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15.5k/15.5k [00:05<00:00, 2.81kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 5 of 5
Content received from server:
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>

HTTPError: 500 Internal Server Error from https://upload.pypi.org/legacy/
Internal Server Error
```

`twine check dist\*` output shows that all is ok:
```
e:\Git\ui-map-parser>twine check dist\*
Checking dist\ui_map_parser-1.0.0-py3-none-any.whl: PASSED
Checking dist\ui-map-parser-1.0.0.tar.gz: PASSED
```

The same if trying to upload `ui-map-parser-1.0.0.tar.gz` file.

**Expected behavior**
Package should be uploaded succesfully.

**To Reproduce**
Execute `twine upload ui-map-parser-1.0.0.tar.gz`

**My Platform**
Windows 10.0.17763
Python 3.7.3
Twine 3.2.0

**Additional context**
Project repo: https://github.com/F1ashhimself/ui-map-parser
[ui-map-parser-1.0.0.tar.gz](https://github.com/pypa/warehouse/files/5074613/ui-map-parser-1.0.0.tar.gz)

**Comment by di** [comment]
I can't reproduce your issue with the `ui-map-parser-1.0.0.tar.gz` file provided. Can you provide the wheel as well?

Would it be possible for you to try this again and note the time so I can correlate this with the logs?

**Comment by F1ashhimself** [comment]
I cant add `.whl` file because this format is not supported, I just added `.zip` to end of file. You can remove this extension and operate like with `.whl` file.

[ui_map_parser-1.0.0-py3-none-any.whl.zip](https://github.com/pypa/warehouse/files/5076401/ui_map_parser-1.0.0-py3-none-any.whl.zip)

**Comment by di** [comment]
I can't reproduce with that file either, I'll need you to try again & let me know the time that you got the error.

**Comment by F1ashhimself** [comment]
Here are gif with all steps including creation of wheel and tar.gz files.
https://i.imgur.com/yAaRrZe.gif

**Comment by F1ashhimself** [comment]
@di also I have reproduced it one more time for you at 09:10 UTC 17 Aug 2020

**Comment by di** [comment]
I can correlate this with our logs, but all I see is this (with no stack trace):

```
pypi-warehouse-web-uploads-cdb98bcb-gqgg5 web-uploads  - - [17/Aug/2020:09:10:24 +0000] "POST /legacy/ HTTP/1.1" 500 0 "-" "-"
pypi-warehouse-web-uploads-cdb98bcb-s49qv web-uploads  - - [17/Aug/2020:09:10:18 +0000] "POST /legacy/ HTTP/1.1" 500 0 "-" "-"
```

And there's no corresponding issue in our alerting system, which is odd.

**Comment by F1ashhimself** [comment]
@di how I can help to figure out the problem?

**Comment by di** [comment]
@F1ashhimself Could you try to reproduce by uploading to https://test.pypi.org/?

**Comment by F1ashhimself** [comment]
@di I have deleted .pypirc file and created it again with token instead of password and uploaded this package to main pypi successfully. Thank you for your help.

**Comment by di** [comment]
@F1ashhimself That's interesting. Did your password contain any non-ascii characters or anything else unusual?

**Comment by F1ashhimself** [comment]
@di I have password with only characters and number but it was set long time ago, so when Im trying to login on site with this password I have received message that password is not met requirements and should be changed. After changing it I tried only with token. Maybe the problem was in that old password that was need to be renewed.

**Comment by di** [comment]
@F1ashhimself Was the message that your password was included in a breach? PyPI integrates with https://haveibeenpwned.com/ to prevent using accounts with breached passwords. It sounds like this might not be working 100% correctly.

**Comment by F1ashhimself** [comment]
@di The message was something like "You password is insecure, you should add one or two words to it...".

**Comment by di** [comment]
@F1ashhimself Can you run the following script, changing the `password` variable to be the old password you were using, and let me know what it prints?

This will use https://haveibeenpwned.com/API/v2#PwnedPasswords to determine if PyPI would have considered your password breached. Your password will be hashed before it's sent to the API.

```python
import hashlib
import requests

password = "your password here"

hash_object = hashlib.sha1(password.encode("utf-8"))
digest = hash_object.hexdigest()
result = requests.get("https://api.pwnedpasswords.com/range/" + digest[:5]).text
print(digest[5:].upper() in result)
```

**Comment by F1ashhimself** [comment]
@di script returns `True` and as I said previously this password was leaked but message when logging in was not about leaked password.

**Comment by di** [comment]
Thanks for confirming! I've updated the issue title accordingly.
