### ISSUE TITLE
Help page still links to distutils-sig

### ISSUE THREAD

**Issue by Julian** [pypa/warehouse#8440]
**Describe the bug**
The [help page](https://pypi.org/help/) suggests:

> The Python Packaging Authority (PyPA) is a working group who work together to improve Python packaging. If you'd like to get in touch with a core packaging developer, use #pypa on IRC (freenode), or join the distutils-sig mailing list. 

though most of the `distutils-sig` discussion now occurs in [Discuss Packaging](https://discuss.python.org/c/packaging/14).

**Expected behavior**
Linking to the discuss instead seems possibly better if that's where most discussion/maintainers are participating.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/).

If you are working on this issue and have questions, feel free to ask them here, in the [`#pypa-dev` chat channel on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or on the [distutils-sig.python.org mailing list](https://mail.python.org/mailman3/lists/distutils-sig.python.org/).

**Comment by di** [comment]
Thanks! I've added the "good first issue" label to this issue.
