### ISSUE TITLE
Pypi store my new package version but return 400 filename reuse error

### ISSUE THREAD

**Issue by inkhey** [pypa/warehouse#8470]
**Describe the bug**

I'm trying to release a new version of https://github.com/algoo/preview-generator , but i do not success to have a real new release in pypi. My package get stuck in a sort of  "mid-zone", not really released but stored by pypi website.

During the twine process, i do get this error:
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse for more information
```

The problem here, is that... i do not have already used this filename, so i don't see why i do get this issue.
It seems that pypi as somehow accepted my new version of package as pypi do store the version i just tried now to push as 
https://github.com/algoo/preview-generator/archive/release_0.15.tar.gz is accessible (and the code here is really the 0.15 code) but pypi (and pip) say the last version remained 0.14, so the new version is not **really** released, and not usable with pip.

I do make a test on test pypi instance but cannot reproduce the issue. i was able to push a proper new release : https://test.pypi.org/project/preview-generator/

note: 0.15, 0.15.1 and 15.2 are both 3 "broken release" (i do some retry to be sure that the behavior wasn't just some kind of "bad luck"). 

**Expected behavior**

Have proper new release when i do use `twine upload` command line.

**To Reproduce**
i do reproduce when i try to upload a new version in preview_generator project using twine on official pypi website, cannot reproduce the problem in testpypi.

**My Platform**

```
twine --version
twine version 3.2.0 (pkginfo: 1.5.0.1, requests: 2.24.0, setuptools: 40.8.0,
requests-toolbelt: 0.9.1, tqdm: 4.47.0)
```

**Comment by jamadden** [comment]
According to PyPI's logs, the versions 0.15, 0.15.1, 0.15.2 and 0.15.3 were used by the previous project owner in May of 2017. You won't be able to use those versions and will have to pick [a new version](https://www.python.org/dev/peps/pep-0440/).

**Comment by jamadden** [comment]
Not to my knowledge.

**Comment by pradyunsg** [comment]
> Thanks, is there anyway to know if there is other hidden already used version ?

You might be able to look at the audit logs/security logs of the package, to see what past releases have been made.
