### ISSUE TITLE
pip install project description not in English

### ISSUE THREAD

**Issue by elenahensinger** [pypa/warehouse#8486]
Not sure whether there exists a guideline that project descriptions should be in English, or English + any other language?
The content seems to be all code-related (according to Google Translate), but majority is in Chinese.
https://pypi.org/project/sqllib/
<img width="1189" alt="Screenshot 2020-08-28 at 09 38 50" src="https://user-images.githubusercontent.com/64856102/91540940-72ece680-e913-11ea-9e37-4c64eac5e45f.png">

**Comment by di** [comment]
Thanks for the issue! There's no requirement that project descriptions are in English.
