### ISSUE TITLE
XML-RPC API timeout when getting all packages

### ISSUE THREAD

**Issue by saulshanabrook** [pypa/warehouse#849]
If I try to use [the `changelog` and `changelog_since_serial` XML-RPC methods](https://warehouse.readthedocs.org/api-reference/xml-rpc/#mirroring-support) to get a lot of packages, they fail with timeouts.

```python
# python 3
import xmlrpc.client

client = xmlrpc.client.ServerProxy('https://warehouse.python.org/pypi')

# get all packages, this fails
client.changelog_since_serial(0)

import time
# get all packages in last year, this fails
client.changelog(time.time() - 60*60*24*360)
```

They both fail with:

```
---------------------------------------------------------------------------
ProtocolError                             Traceback (most recent call last)
<ipython-input-17-19d7cae1b25e> in <module>()
----> 1 client.changelog(time.time() - 60*60*24*360)

/usr/local/lib/python3.5/xmlrpc/client.py in __call__(self, *args)
   1089         return _Method(self.__send, "%s.%s" % (self.__name, name))
   1090     def __call__(self, *args):
-> 1091         return self.__send(self.__name, args)
   1092
   1093 ##

/usr/local/lib/python3.5/xmlrpc/client.py in __request(self, methodname, params)
   1429             self.__handler,
   1430             request,
-> 1431             verbose=self.__verbose
   1432             )
   1433

/usr/local/lib/python3.5/xmlrpc/client.py in request(self, host, handler, request_body, verbose)
   1131         for i in (0, 1):
   1132             try:
-> 1133                 return self.single_request(host, handler, request_body, verbose)
   1134             except OSError as e:
   1135                 if i or e.errno not in (errno.ECONNRESET, errno.ECONNABORTED,

/usr/local/lib/python3.5/xmlrpc/client.py in single_request(self, host, handler, request_body, verbose)
   1164             host + handler,
   1165             resp.status, resp.reason,
-> 1166             dict(resp.getheaders())
   1167             )
   1168

ProtocolError: <ProtocolError for warehouse.python.org/pypi: 503 backend read error>
```

When I try queries that return less packages, they work properly.

I am trying to query to get all the names, versions, and times for all releases ever. There doesn't seem to be any way to do this, because these methods fail for older times. No other methods return the time a release happened.

**Comment by saulshanabrook** [comment]
I assume this is happening because [this DB query](https://github.com/pypa/warehouse/blob/f970b73d0a4a6ca6b432c346686b727091fced56/warehouse/legacy/api/xmlrpc.py#L298-L301) times out when too many `JournalEntry`s are being queried.

**Comment by dstufft** [comment]
It's actually a timeout from the CDN because if it takes too long to get a response back, the CDN times out the connection. It's unlikely that going back that far is ever going to work via XMLRPC. I do have plans to deprecate the XMLRPC interface and provide a much nicer JSON based API instead, that doesn't help you right now though.

What are you trying to do with this data? Is this a one off thing that I can just hand you the data out of band?

**Comment by saulshanabrook** [comment]
I am trying to [create automated dockerhub images for all Python packages](https://github.com/saulshanabrook/pypi-dockerhub), mainly for CLI python apps. So that I can do something like `docker run --rm -it pypi/ansible`. 

I have [gotten around this](https://github.com/saulshanabrook/pypi-dockerhub/blob/d64eeb5f3cb2e8df475fff7ec5aeebae375c1c2e/pypi/release.go#L124-L147) by using `list_packages` to get all packages, then for each of those calling `package_releases` to get all versions, then getting the `upload_time` from the first release from `release_urls`, for that particular release.

Then once I have imported all packages, to just get the new ones I can use the `changelog` method.

**Comment by dstufft** [comment]
Awesome!

You might want to use the JSON API instead of ``package_releases`` and ``release_urls``. Something like:

```python
import requests
import xmlrpc.client

for package in xmlrpc.client.Server("https://pypi.python.org/pypi").list_packages():
    print(requests.get("https://pypi.python.org/pypi/{}/json".format(package)).json())
```

**Comment by saulshanabrook** [comment]
Thanks! That is a lot better, I can get all the versions and times in one request :+1:
