### ISSUE TITLE
Update 'Getting started' documentation for Mac and Windows

### ISSUE THREAD

**Issue by niroyb** [pypa/warehouse#853]
I have a few issues following the instructions on the [Getting started](https://warehouse.readthedocs.org/development/getting-started/#installing-docker) page. I installed [Docker Toolbox](https://www.docker.com/docker-toolbox) on windows 10 after reading the  latest docker [installation steps for windows](http://docs.docker.com/engine/installation/windows/).
### [Quickstart](https://warehouse.readthedocs.org/development/getting-started/#quickstart-for-developers-with-docker-experience)
- The quickstep on Windows could clone using https.
- `docker start` Failed with :

```
/D/git/warehouse (master)
$ docker start
docker: "start" requires a minimum of 1 argument.
See 'C:\Program Files\Docker Toolbox\docker.exe start --help'.
Usage:  docker start [OPTIONS] CONTAINER [CONTAINER...]
```
### [Installing docker](https://warehouse.readthedocs.org/development/getting-started/#installing-docker)
- The latest docker release [depecrates Boot2Docker in favor of Docker Machine](http://docs.docker.com/engine/installation/windows/). The "Installing Docker" section could reflect that.

Sorry for bundling multiple issues in one, I feel like they are all related to the latest install procedure by Docker.

**Comment by zoidbergwill** [comment]
So `boot2docker` has been replaced with `docker-machine`, and I think a `docker-machine start default` is equivalent to doing both the steps for `boot2docker`. Do you get an error when doing the `make build` step?

**Comment by Carreau** [comment]
Here is what I get when trying to use docker-machine instead of boot2docker:
```
~/dev/warehouse master$ make build
docker-compose build
redis uses an image, skipping
Building app
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
make: *** [build] Error 1

~/dev/warehouse master$ docker-machine start default
Host does not exist: "default"
```

**Comment by berkerpeksag** [comment]
With Docker for Mac and Docker for Windows, it should be very straightforward to install Warehouse on OS X and Windows now. I've updated the getting started guide in https://github.com/pypa/warehouse/pull/1398.

I think this can be closed now.
