### ISSUE TITLE
When you visit the homepage, the search box should have focus by default

### ISSUE THREAD

**Issue by alex** [pypa/warehouse#854]

**Comment by nlhkabu** [comment]
Yes, I agree.  However, we have had some early user feedback that suggests this is not great on mobile, where the focus prompts the keyboard, which can take up to 50% of the screen real estate.

Perhaps the solution is to only focus the input for viewports > 400px.

**Comment by alex** [comment]
that sounds like a good compromise!

**Comment by nlhkabu** [comment]
Update on this (in case anyone else is thinking on jumping in).  I have a fix for this and will make a PR soon.

**Comment by carlcarl** [comment]
Seems this should be closed?

**Comment by miohtama** [comment]
This still bugs on tablet, the soft keyboard appears, as one cannot discriminate tables and hardware keyboard devices from each other based on viewports. Furthermore HDPI mobile screens also may cause the keyboard appear.

The "search focus by default" paradigm is unfortunately not very good approach considering many devices have soft keyboards nowadays. The case has different 10 years ago with different accessibility standards.

I suggest rolling back this as sudden appear of soft keyboard without user interaction is a major buster until we can detect hardware keyboard only devices via JavaScript.

**Comment by nlhkabu** [comment]
The objective here wasn't to avoid prompting a soft keyboard *ever*, but rather to avoid prompting it on small (mobile) screen sizes, where the soft keyboard would take a disproportionate amount of space.

**Comment by miohtama** [comment]
Please take a look on the attached screenshot of Warehouse front page. This is a horrible decision. Please do not have autofocus ever as it is against current usability principles as explained above and this makes me cry with my 20 years of web development experience and I will jump from the bridge if this happens for my beloved PyPi.

![screenshot_20160224-221357](https://cloud.githubusercontent.com/assets/49922/13309625/2edb8bc2-db44-11e5-9637-a5236888d8d7.png)

**Comment by nlhkabu** [comment]
> I will jump from the bridge if this happens for my beloved PyPi.

If you are genuinely considering self harm over this issue, please seek medical help.  Otherwise it is neither necessary nor appropriate to escalate this issue with such language.

I agree that this is a problem.  If you would like to see if changed, please submit a PR.

Refs: #983

**Comment by dstufft** [comment]
I mean, it's not like this is a new thing for PyPI. The current version of pypi.python.org has the autofocus attribute set on the home page. as far as I know, nobody has complained about that so maybe just using the HTML5 is less error prone.

**Comment by miohtama** [comment]
@nlhkabu Thank you for understanding.

I apologize the tone of the language.

Pull request submitted.

**Comment by twm** [comment]
The behavior on pypi.python.org has driven me crazy for years, but that site doesn't have a "Report a Bug" link at the bottom of the page like Warehous, which is how you got #983.  So Warehouse is already an improvement from a community engagement perspective. :)

**Comment by merwok** [comment]
> as far as I know, nobody has complained about that 

I thought I had!

I found it very annoying to be prevented from using keyboard shortcuts (space to scroll, / to search, arrows) on old PyPI.
