### ISSUE TITLE
Pypi doesn't show latest release-version of Plugwise-Smile

### ISSUE THREAD

**Issue by bouwew** [pypa/warehouse#8547]
**Describe the bug**

As the title: when I browse to https://pypi.org/project/Plugwise-Smile/ it shows version 1.4.1 while version 1.5.0 has been released and built: https://pypi.org/project/Plugwise-Smile/1.5.0/

**Expected behavior**

Show version 1.5.0

**To Reproduce**

When browsing here https://pypi.org/project/Plugwise-Smile/1.5.0a1/ on the right it shows there a new version - 1.5.0 but when clicking the link, v1.4.1 is shown.

**My Platform**

Linux Mint Debbie4, Chromium browser.

**Additional context**

**Comment by di** [comment]
Looks like the attempt to purge the cache failed, it's updated now.

**Comment by bouwew** [comment]
Thanks!
