### ISSUE TITLE
Make tag display consistent

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#855]
![tags-alt](https://cloud.githubusercontent.com/assets/3323703/11621054/3eb9941c-9cb0-11e5-8119-150e0a0648c0.png)

![tags](https://cloud.githubusercontent.com/assets/3323703/11621055/3edf45fe-9cb0-11e5-8e4e-f5c8973c44f9.png)

We need to make the output of tags consistent.  Each tag should be followed by a comma and space `, ` i.e `tag1, tag2, tag3`

**Comment by dstufft** [comment]
This will require some massaging of the data. Currently the tags field is just a raw text box that people can put whatever they want into. Some people do ``tag,tag,tag`` others do ``tag, tag, tag`` others do ``tag tag tag`` and I'm sure there are other variations as well.

**Comment by shiroyuki** [comment]
How about:
1. Split the tags up with `/[, ]+/g`.
2. Split the tag icon and text into two separate columns, like:

```html
<div class="tags">
  <div class="icon">TAG_ICON</div>
  <ul>
    <li>TAG_1</li>
    <li>TAG_2</li>
  </ul>
</div>
```

?

**Comment by di** [comment]
@shiroyuki Some tag fields have multiple-word tags separated by commas, e.g. `tagA,tagB,another tag`, this would need to be taken into consideration, as this should produce `['tagA', 'tagB', 'another tag']` and not `['tagA', 'tagB', 'another', 'tag']`

**Comment by shiroyuki** [comment]
So... this means the splitter function has to be:

```javascript
function splitTags(tagText) {
  var tags = [];
  return tagText.match(/,/)
    ? tagText.split(/\s*,\s*/g) // split with comma surrounding by any whitespaces
    : tagText.split(/\s+/g) // split with whitespace
  ;
}
```

**Comment by di** [comment]
@shiroyuki I found a few more example cases that we may want to be able to handle as well:

* Double-quoted, separated with commas: `"Record","speaking","Toefl","Rehearse","Educational","pickledb","Tkinter"`
* Double-quoted, separated with commas and spaces:
`"consul", "backup", "yml", "key-value", "boto", "s3", "s3bucket", "bucket", "cli", "command"`
* Separated with semicolons and spaces:
`natural language processing; thesaurus`

So probably:
* Split on comma or semicolon if present, if not, spaces;
* Strip whitespace, single quotes and double quotes from the split elements.

**Comment by shiroyuki** [comment]
That sounds about right. Wow, I'm impressed. :D

**Comment by nlhkabu** [comment]
On the HTML side, I'd prefer if we kept the existing tag structure and simply replace the content, returning a comma separated string.

**Comment by shiroyuki** [comment]
@nlhkabu IMO, the only reason to wrap each tag in a HTML tag is so that we can control the white spaces. For example, instead of...

```
something this long
```

would not end up like

```
something <next line>
this long
```
.

**Comment by nlhkabu** [comment]
In this case, each tag should be wrapped in a span with `display: inline-block` applied.

**Comment by rjwebb** [comment]
```javascript
function stripTag(tag) {
  return tag.replace(/^["'\s]+|["'\s]+$/g, '');
}

function splitTags(tagText) {
  var tags = [];
  return tagText.match(/,/)
    ? tagText.split(/\s*,\s*/g) // split with comma surrounding by any whitespaces
    : tagText.split(/\s+/g) // split with whitespace
  ;
}

function formatTags(tagText) {
  return $.map(splitTags(tagText), stripTag);
}
```
Does this look like the right sort of thing? Or should the server split the tags (e.g. with a jinja2 filter, which could be called ```format_tags```) then render them in the template? Something like:
```html+jinja
{% if release.keywords %}
<p class="tags"><i class="fa fa-tags"></i>
  {% for keyword in release.keywords | format_tags %}
  <span class='keyword'>{{ keyword }}</span>
  {% endfor %}
</p>
{% endif %}
```
(disclaimer: this is my first comment on this project! so if I have been too unclear or done something obviously wrong please don't be afraid to tell me.)

**Comment by dstufft** [comment]
I would prefer to have it handled inside of a jinja2 filter.

And no worries! You're doing fine :)

**Comment by shiroyuki** [comment]
I think the Jinja2 approach is better. :D
