### ISSUE TITLE
API token failed to work after #7124 fix

### ISSUE THREAD

**Issue by daniel-yj-yang** [pypa/warehouse#8554]
**Describe the bug**

(1) 
python3 -m twine upload --repository testpypi dist/*
...
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
Invalid API Token: invalid macaroon!r

This can be reproduced in pypi.org and test.pypi.org

(2)
Also, there is a minor typo here:
https://test.pypi.org/manage/account/token/
After API token is created, under "Use this token"
Set your password to the token value, including the **test**pypi- prefix

It should be:
Set your password to the token value, including the pypi- prefix

**Expected behavior**

python3 -m twine upload --repository testpypi dist/*
...
Successfully installed ...

**To Reproduce**

Follow the instruction here: https://packaging.python.org/tutorials/packaging-projects/

**My Platform**

Mac OS
Python 3.8.3.
setuptools-50.3.0
wheel-0.35.1
twine-3.2.0

**Additional context**

**Comment by di** [comment]
Thanks, I can reproduce this:

```
$ twine upload --repository-url https://test.pypi.org/legacy/ dist/*
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: __token__
Enter your password:
Uploading sampleproject-2.0.0.tar.gz
100%|██████████████████████████████████████| 13.6k/13.6k [00:00<00:00, 46.7kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
Invalid API Token: invalid macaroon signature!r
```
