### ISSUE TITLE
API token broken after #8554 fix

### ISSUE THREAD

**Issue by daniel-yj-yang** [pypa/warehouse#8558]
**Describe the bug**

python3 -m twine upload -r pypi dist/* 
...
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
This filename has already been used, use a different version. See https://pypi.org/help/#file-name-reuse for more information.

**Expected behavior**

python3 -m twine upload -r pypi dist/* 
...
Successful ...

**To Reproduce**

Any upload to the regular pypi.org
For example, follow the instruction here: https://packaging.python.org/tutorials/packaging-projects/
but using -r pypi, instead of -r testpypi

**My Platform**

Mac OS
Python 3.8.3.
setuptools-50.3.0
wheel-0.35.1
twine-3.2.0

**Additional context**

**Comment by di** [comment]
This looks like expected behavior. Can you share the filename you were attempting to upload?

**Comment by daniel-yj-yang** [comment]
under dist/
example-pkg-danielyang-0.0.1.tar.gz
example_pkg_danielyang-0.0.1-py3-none-any.whl

But I currently do not have any project in testpypi or pypi

**Comment by di** [comment]
Can you include the entire output of the `twine` command? Do you have any other files in your `dist` directory?

**Comment by daniel-yj-yang** [comment]
After reading https://pypi.org/help/#file-name-reuse, I see what's going on.
I increased the version to 0.0.2 and it worked now.
I deleted 0.0.1, which I created previously. This is not a bug. I will close the issue now.
