### ISSUE TITLE
Invalid API Token: invalid macaroon!r for url

### ISSUE THREAD

**Issue by snowman2** [pypa/warehouse#8565]
**Describe the bug**
Possibly related to #6259
When using the same token generated from pypi a couple of months ago, now I got the error:
```
HTTPError: 403 Client Error: Invalid API Token: invalid macaroon!r for url: https://upload.pypi.org/legacy/
```
I figured it was based on an old key and re-generated a token, but I get the same error.

I verified that the version of `twine` did not change between the successful execution and the failure.

**Expected behavior**
No error on upload.

**To Reproduce**

TWINE_USERNAME=`__token__`
TWINE_PASSWORD=`<token generated at pypi.org>`

twine upload ...

**My Platform**
```
Build dist: xenial
Runtime kernel version: 4.15.0-1077-gcp
```
**Additional context**
https://travis-ci.com/github/pyproj4/pyproj-wheels/jobs/384840987

**Comment by di** [comment]
Hi @snowman2, this should be resolved by #8555 (and the error message improved by #8561), can you confirm?

**Comment by snowman2** [comment]
Thanks for the fix - restarted build: https://travis-ci.com/github/pyproj4/pyproj-wheels/builds/184304607

**Comment by snowman2** [comment]
It worked, thanks :+1:

**Comment by childish-sambino** [comment]
Just got a similar error. Was working fine a week ago.

https://travis-ci.org/github/twilio/twilio-python/jobs/729123230

**Comment by a-feld** [comment]
We also just got a similar error:
https://github.com/newrelic/newrelic-python-agent/runs/1146467559?check_suite_focus=true#step:9:14

**Comment by di** [comment]
Thanks, looks like https://github.com/pypa/warehouse/pull/8562 has re-introduced this (cc @ewjoachim).

**Comment by shiftan** [comment]
> Thanks, looks like #8562 has re-introduced this (cc @ewjoachim).

Same for me...

**Comment by better365** [comment]
+1 here. Please prioritize to fix this issue.

**Comment by Daggy1234** [comment]
I am also getting this error

**Comment by Daggy1234** [comment]
Sure

**Comment by nerohmot** [comment]
any update on the "403 Invalid API Token: InvalidMacaroon('invalid macaroon signature')" ?!?
