### ISSUE TITLE
Converting Unknowns in Formulas to Uppercase Hurts My Use Case and Seems Unnecessary

### ISSUE THREAD

**Issue by Taichikitty** [pypa/warehouse#8579]
I am in the process of loading ( and resolving ) formulas from a couple of work sheets from an .xlsx file downloaded from Google Docs.  When I use:

```
func = formulas.Parser().ast(line)[1].compile()
list_of_func_inputs = func.inputs
for item in list_of_func_inputs:
   print(str(item)) 
```

All the constants that were titlecase with underscores turned into all uppercase with underscores.  This interferes with my ability to use those terms as references to rows in a Pandas dataframe.
In my current situation, I can get away with making all those terms uppercase in my dataframe; but it seems unnecessary to have that requirement, and interferes with human-readability.

Example:
`CheivonGraphics_1DAvgGrayscale_Sum `
...gets converted to...
`CHEIVONGRAPHICS_1DAVGGRAYSCALE_SUM`

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
