### ISSUE TITLE
Feature request: Show packages that depend on a package

### ISSUE THREAD

**Issue by cool-RR** [pypa/warehouse#8581]
Today I want to curious to see which PyPI packages depend on mor-itertools. I hoped PyPI would have a link to that information from the more-itertools page, but nope. I know GitHub provides that information, but I trust PyPI's database better.

**Comment by di** [comment]
Thanks for the feature request. This is a duplicate of https://github.com/pypa/warehouse/issues/789.

(I'll also add that this is challenging to get right, see https://dustingram.com/articles/2018/03/05/why-pypi-doesnt-know-dependencies/)
