### ISSUE TITLE
pip install shows error

### ISSUE THREAD

**Issue by sunilpandya** [pypa/warehouse#8585]
Your command pip install beautifulsoup4 shows an error in python 3.8.5, it says syntax error invalid command

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (`https://pypi.org/project/<SOME PACKAGE>`).
