### ISSUE TITLE
500 Internal Error when uploading a package

### ISSUE THREAD

**Issue by pavelvelikhov** [pypa/warehouse#8614]
**Describe the bug**
Getting a 500 Internal Error when submitting my package to PyPI

**Expected behavior**
The package should make it into PyPI repository

**To Reproduce**
You can try to upload this distribution: [https://github.com/pythonql/pythonql/blob/dist-patch/pythonql3-0.9.69.tar.gz](https://github.com/pythonql/pythonql/blob/dist-patch/pythonql3-0.9.69.tar.gz)

**Comment by di** [comment]
Hi, can you confirm that you can log in to PyPI with the same credentials? This may be https://github.com/pypa/warehouse/issues/8431

**Comment by pavelvelikhov** [comment]
Yes, it was a credentials error, thank you!

The strange thing is that is uploaded around 17% of the package and then returned 500
