### ISSUE TITLE
Confused instruction

### ISSUE THREAD

**Issue by mingyu003** [pypa/warehouse#8619]
Some users might want to install the toolbox without MPI support. This is possible, but not through the pip command:

.....

$ tar xzf TensorToolbox-x.x.x.tar.gz %there is no such a file.

.....

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
