### ISSUE TITLE
PyPBLib PBLib issue cannot contact maintainer

### ISSUE THREAD

**Issue by vlastikw** [pypa/warehouse#8632]
**Describe the bug**

PBLib converts PB constraint to CNF always the same way regardless encoder used i.e. PBConfig.PB_Encoder
**Expected behavior**

Expected output CNF should differ in variables and clauses not always the same.
**To Reproduce**

Conversion to CNF with cardinality encoder works as expected. Code for both to compare attached.
from pypblib import pblib
from pypblib.pblib import PBConfig, Pb2cnf
max = 129
lits=list(range(1,max))
wlits=[]
print(lits)
weights=[]
for x in lits:
 weights.append(1)
 wlits.append(pblib.WeightedLit(x, 1))

print("Number of weights %d" % len(weights))

pb_encoders=[pblib.PB_BDD,pblib.PB_SWC, pblib.PB_SORTINGNETWORKS, pblib.PB_ADDER, pblib.PB_BINARY_MERGE]

for x in pb_encoders:
  print("Encoding PB %d" % (x))

  config = PBConfig()
  config.set_PB_Encoder(pblib.PB_BDD)
#print(config)

  formula = []
  pb2 = Pb2cnf(PBConfig())
  max_var = pb2.encode_both(weights,lits, 1,1, formula, max)
  print("Number of variables %d" % max_var)
  print("Number of clauses %d" % len(formula) )

  constr = pblib.PBConstraint(wlits, pblib.BOTH, 1)
  aux_var = pblib.AuxVarManager(max)
  formula = pblib.VectorClauseDatabase(config)
  pb2cnf = pblib.Pb2cnf(config)
  pb2cnf.encode(constr, formula, aux_var)
  print("Number of variables %d" % aux_var.get_biggest_returned_auxvar() )
  print("Number of clauses %d" % formula.get_num_clauses() )

from pysat import *
from pysat.pb import *
from pysat.card import *

lits=list(range(1,129))
print(lits)

for x in range(1,6):
    print("Encoding PB %d" % (x))
    cnf = PBEnc.equals(lits=lits, encoding=x)
#    print(cnf.clauses)
    print("Number of variables %d" % cnf.nv)
    print("Number of clauses %d" % len(cnf.clauses) )

print("****************************")

for x in range(0, 9):
    print("Encoding SAT %d" % (x))
    cnf = CardEnc.equals(lits=lits, encoding=x)
#    print(cnf.clauses)
    print("Number of variables %d" % cnf.nv)
    print("Number of clauses %d" % len(cnf.clauses) )

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by vlastikw** [comment]
I know, but if you allow package to integrate then there should be a way
how to contact maintainer or report bug/issue. Unfortunately I'm not aware
of doing this. Can you please advice?

Thank you

st 30. 9. 2020 v 0:51 odesílatel Dustin Ingram <notifications@github.com>
napsal:

**Comment by di** [comment]
Looks like @jponf is listed as one of the authors, perhaps they can help? Otherwise, sorry, there's no additional contact information.

**Comment by jponf** [comment]
Hi,

Sorry for the inconvenience, I'm not currently maintaining the package but I'll forward your message to the other authors and try to keep you posted.

Thanks @di for finding a way to contact us, we'll update the package information ASAP to include our contact information.

**Comment by vlastikw** [comment]
Hi,

thank you. It would be nice to make repositery for PBLib open. I've found
one on github already and created issue. So it would be nice to migrate you
repo and docu to this repository which is open for everybody and link it
with PySAT.

https://github.com/rjungbeck/pypblib/issues/1

Hope that then it would be much easier to contact authors or fix bugs.

Thanks a lot

Vlasta

st 30. 9. 2020 v 7:47 odesílatel Josep Pon Farreny <notifications@github.com>
napsal:
