### ISSUE TITLE
How to deprecate a package at pypi.org?

### ISSUE THREAD

**Issue by guettli** [pypa/warehouse#8659]
**What's the problem this feature will solve?**

If a package at pypi is deprecated, then it would be nice if an author could declare this in
an explicit way.

**Describe the solution you'd like**

Maybe a new attribute in the metadata dictionary would be a solution.

**Additional context**

Example: https://github.com/patarapolw/ankisync/issues/11

Ankisync is deprecated, and the author asks how to make a package deprecated.

**Comment by ewjoachim** [comment]
Maybe the trove classifier `Development Status :: 7 - Inactive` ?

**Comment by ewdurbin** [comment]
Closing as duplicate of #345
