### ISSUE TITLE
Broken readthedocs links in README

### ISSUE THREAD

**Issue by zdog234** [pypa/warehouse#8677]
sorry if there's already an issue for this, but I wasn't able to find anything after a few searches

**Describe the bug**

The warehouse.readthedocs.io links in the readme are broken (for me)

[a broken (for me, at least) link in the readme](https://warehouse.readthedocs.io/development/getting-started/)

[A tweaked link that works](https://warehouse.readthedocs.io/development/getting-started.html)

**Comment by di** [comment]
I think https://github.com/pypa/warehouse/pull/8656 is attempting to resolve this same issue.

**Comment by di** [comment]
I fixed this by enabling the `Sphinx HTMLDir -> HTML` redirect:
![image](https://user-images.githubusercontent.com/294415/95510525-ae032080-097b-11eb-87ec-2a516d4be575.png)
