### ISSUE TITLE
Unable to install Postman on Python 3.8, Python 3.7, Python 3 in general?

### ISSUE THREAD

**Issue by richkatz** [pypa/warehouse#8696]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by richkatz** [comment]
During pip install Postman install on Python 3, gets a Python 2 incompatibility error, looking for something from boto (boto is a Python 2 package).

Where is the tracker "for the project in question?"

**Comment by di** [comment]
It's here: https://github.com/paltman-archive/postman/issues

By the way, the project you're trying to install was last released in 2011, it seems likely that it doesn't work and isn't maintained anymore.
