### ISSUE TITLE
Installing pipenv on docker results to hash mismatch from requirements files

### ISSUE THREAD

**Issue by lambchamps** [pypa/warehouse#8705]
**Describe the bug**

I'm trying to run a project on my docker, but whenever it tries to install pipenv through `pip install pipenv` it gives me an error about hash mismatch from the requirements file, the error looks like this:

`
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pipenv from https://files.pythonhosted.org/packages/8b/02/cf3cb144314f56eaf388a83bcf481a3200c9df46ca6ceeecfb6eb4be155a/pipenv-2020.8.13-py2.py3-none-any.whl#sha256=448ac3a36443db633d52a2359cac15ecbc4f429eab4ddd420697602b721d1c5a:
Expected sha256 448ac3a36443db633d52a2359cac15ecbc4f429eab4ddd420697602b721d1c5a
Got <something else>
`

**Expected behavior**

Expect to successfully install pipenv and run the docker container

**To Reproduce**

docker-compose -f <path/to/env/yml> up -d
yml contains pip install pipenv

**My Platform**

Windows 10 Pro

**Additional context**

I already asked pipenv here https://github.com/pypa/pipenv/issues/4487, and they say it might be network issue, of which I don't know how to fix, although I have problems running virtual machines on my VirtualBox. and manage to fix it by reinstalling multiple times in different manner

**Comment by ewjoachim** [comment]
When I check the file you mention, I'm getting the proper hash:
```console
$ curl https://files.pythonhosted.org/packages/8b/02/cf3cb144314f56eaf388a83bcf481a3200c9df46ca6ceeecfb6eb4be155a/pipenv-2020.8.13-py2.py3-none-any.whl | sha256sum                                                  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3784k  100 3784k    0     0  2752k      0  0:00:01  0:00:01 --:--:-- 2752k
448ac3a36443db633d52a2359cac15ecbc4f429eab4ddd420697602b721d1c5a  -
```

Assuming you have curl installed, can you run the same command and send the result ? Are you using a proxy or anything that might be tempering with your network ?

**Comment by di** [comment]
@lambchamps Can you also include the entire `pip install` command and output?

**Comment by lambchamps** [comment]
> @lambchamps Can you also include the entire `pip install` command and output?

![image](https://user-images.githubusercontent.com/18628157/96073023-22881300-0ed8-11eb-910a-ba14bfc14efe.png)

I know nothings wrong with the command since, I'm the only one experiencing it on my team

**Comment by di** [comment]
@lambchamps Could you provide a minimally reproducing `Dockerfile` or `docker-compose.yml` file?

**Comment by lambchamps** [comment]
> @lambchamps Could you provide a minimally reproducing `Dockerfile` or `docker-compose.yml` file?

I'm not sure if I can, but as I've said the yml and dockerfile works fine with my team. I've done a few research, and since I'm the only one experiencing the issue, I think it's a network issue on my local and virtualbox

**Comment by ewjoachim** [comment]
I'm not sure there's a lot we can do to help then :)

I'll let you close the issue, but if you find something that's not done right on the PyPI side, by all means, please feel free to explain/reopen :)

(Good luck for your investigations, networking issues are never fun !)

(Pssst: a lead: in my whole life, *everytime* I've had random arbitrary networking issues where bytes got lost in the process, it was a MTU issue. Look it up ;) )

**Comment by lambchamps** [comment]
Thank you, I will look it up. I think I can say that Pipenv and PyPI are neither the issue,
