### ISSUE TITLE
Add maintainer to thrift (maintainer is unresponsive - again)

### ISSUE THREAD

**Issue by Jens-G** [pypa/warehouse#8707]
Very similar to what i wrote [here](https://github.com/pypa/warehouse/issues/5346#issuecomment-511117112), we are now in that exact situation I wanted to avoid. We have again the case that the only active maintainer again became unresponsive and inactive. 

Hence, I'd like to ask whether someone could add [my account](https://pypi.org/user/JensG/) as a maintainer to the [Apache Thrift package](https://pypi.org/project/thrift/).

Necessary details can be found in the other ticket, if anything is unclear, don't hesitate to ask.

**Comment by di** [comment]
Hi @Jens-G, the process has changed since that issue, please open a PEP 541 request at https://github.com/pypa/pypi-support/issues/new/choose instead, thanks!
