### ISSUE TITLE
URGENT: Accidentally deleted project, re-uploading throws HTTPError 400

### ISSUE THREAD

**Issue by SFM61319** [pypa/warehouse#8730]
**Describe the bug**  
I have made a project ,`dyepy`, and released it to [PyPI](https://pypi.org) recently. A few minutes ago, I accidentally deleted it on PyPI. So I wanted to re-upload it (under a new token) to PyPI using `twine`. But twine won't upload the project to PyPI. It throws  
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
This filename has already been used, use a different version. See
https://pypi.org/help/#file-name-reuse for more information.
```
  
**Expected behavior**  
`twine` should upload the package to PyPI without throwing any error.  
  
**To Reproduce**  
```bash
C:\> pip install --upgrade setuptools wheel twine
C:\> python setup.py sdist bdist_wheel
C:\> twine upload dist/*
username: __token__
password: pypi-new/different_api_token
```  
  
**My Platform**  
Windows 10  
`twine version 3.2.0 (pkginfo: 1.5.0.1, requests: 2.24.0, setuptools: 50.3.2, requests-toolbelt: 0.9.1, tqdm: 4.50.2)`  
  
**Additional context**

**Comment by ewdurbin** [comment]
Please see the help text at https://pypi.org/help/#file-name-reuse from the error message.

You must increment the version. Consider using [Post Release](https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=post%20release#standards-compliance-for-interoperability) to reupload deleted versions.

**Comment by SFM61319** [comment]
@ewdurbin uhhh I read that article(?) but that didn't help me much. I couldn't find version `1.0.0` of my package *anywhere* on PyPI, but twine says v1.0.0 exists. So I wanted to kinda "replace" the (non-existent) package on PyPI with my local package through twine. It's it possible?  
  
And I don't understand why I'm unable to find v1 if it exists... Maybe a bug? Like, PyPI is saying my package exists when it's not/deleted, which is weird... I can't even yank v1.0.0 (if it exists, which is most likely not possible)

**Comment by ewdurbin** [comment]
"PyPI does not allow for a filename to be reused, even once a project has been deleted and recreated."

This is about the filename, not the version number. PyPI keeps track of all filenames and checksums that have been uploaded in the past and does not allow them to be reused.

Thus, the files and filenames you originally uploaded for version 1.0.0 `dyepy-1.0.0.tar.gz` and `dyepy-1.0.0-py3-none-any.whl` cannot be reused.

**Comment by SFM61319** [comment]
@ewdurbin Ah understood... guess ill have to change the version to re-upload... Will this change in the future? cause this sounds like a headache to deal with.. also, will we be able to "replace" an existing version in the future? cause creating a new version for a very minor fix doesn't sound very "[semantic](https://semver.org)" (wrt pypi)  
  
Anyway, thanks for replying with a solution/workaround!

**Comment by di** [comment]
No, this is by design. This ensures that a given distribution for a given release for a given project will always resolve to the same file, and cannot be surreptitiously changed one day by the projects maintainer or a malicious party (it can only be removed).

**Comment by SFM61319** [comment]
> (it can only be removed).

I don't get it... i thought deleting the project (pypi) doesnt delete the files and they stay forever (hence the bad name error). Wdym by they can be "removed"? can i perma-delete everything related to my package and start fresh (with the same name, file structure and version)?

**Comment by SFM61319** [comment]
ohkay i get it now thanks!

**Comment by SFM61319** [comment]
> We still keep a log of what files have been previously uploaded so they can't be reused.

wait so if i change the file structure a bit (to differ from the structure saved in the logs), i can upload it without any problems right?

**Comment by di** [comment]
By "files" I mean the filename, like `dyepy-1.0.0.tar.gz`. PyPI doesn't look at the actual file structure.

**Comment by SFM61319** [comment]
oh. then ill have to change the version. thanks!

**Comment by ewjoachim** [comment]
@SFM61319

Don't forget what Ernest said:

> Consider using [Post Release](https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=post%20release#standards-compliance-for-interoperability) to reupload deleted versions.

You can make a `1.0.0.post1` that contains exactly the same code as 1.0.0, and if people pip install your lib at 1.0.0, they'll get your post1.
