### ISSUE TITLE
Cannot run curl -vvv --ipv4 https://files.pythonhosted.org/  -  'Network is Unreachable' error

### ISSUE THREAD

**Issue by ealemany** [pypa/warehouse#8758]
Hello,

We have a Ubuntu 18.04 server we purchased from Lambda Labs. It came pre-loaded with all the software. The server is 2 years old. It worked fine until Monday Oct 26. When users contacted me.

We have are  issue for few days now. does not seem to work. We cannot run 
```
curl -vvv --ipv4 https://files.pythonhosted.org/  
```
We get a "Network is unreachable" error. This error does not happen on all our servers just a few (3 servers) same VLAN same firewall rules. 

My first guess was the firewall. Local firewall on server is disabled - inactive. Our network team confirmed that port 443, 80, 8080 etc.. are open

Running wget on the PyPI link does not work either. We are not experiencing this problem on other sites.

DNS resolution shows no error and shows expected results - as far as i can tell.

Thank you for your help.

Best,
Eric

**Comment by di** [comment]
Hi, sorry to hear you're having problems. Can you file a "Network Access Issue" here instead? https://github.com/pypa/pypi-support/issues/new/choose

Please make sure to include as much output as you can. The IP addresses of the affected machines would also be helpful if you're able to share them.

**Comment by ealemany** [comment]
ok - Thank you !!
