### ISSUE TITLE
lxml (-Problem

### ISSUE THREAD

**Issue by schloessl** [pypa/warehouse#8780]
sudo pip3 install --upgrade lxml

Collecting lxml
Using cached lxml-4.6.1.tar.gz (3.2 MB)
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sxp2qgwt/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-ins tall-sxp2qgwt/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__fil e__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile( code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tnep q0ht
cwd: /tmp/pip-install-sxp2qgwt/lxml/
Complete output (3 lines):
Building lxml version 4.6.1.
Building without Cython.
Error: Please make sure the libxml2 and libxslt development packages are ins talled.     "ohne Erfolg bei der Insatallation"
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th e logs for full command output.
[root@SmartHomeNGRPI4N34 ~]# Collecting lxml
-bash: Collecting: Kommando nicht gefunden.
[root@SmartHomeNGRPI4N34 ~]# Using cached lxml-4.6.1.tar.gz (3.2 MB)
-bash: Syntaxfehler beim unerwarteten Wort `('
[root@SmartHomeNGRPI4N34 ~]# ERROR: Command errored out with exit status 1:
-bash: ERROR:: Kommando nicht gefunden.
[root@SmartHomeNGRPI4N34 ~]# command: /usr/bin/python3 -c 'import sys, set uptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cwo4rnxl/lxml/setup.py'"' "'; __file__='"'"'/tmp/pip-install-cwo4rnxl/lxml/setup.py'"'"';f=getattr(tokeniz e, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"' "', '"'"'\n '"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-b ase /tmp/pip-pip-egg-info-72zoaquw
-bash: command:: Kommando nicht gefunden.
[root@SmartHomeNGRPI4N34 ~]# cwd: /tmp/pip-install-cwo4rnxl/lxml/
-bash: cwd:: Kommando nicht gefunden.
[root@SmartHomeNGRPI4N34 ~]# Complete output (3 lines):
-bash: Syntaxfehler beim unerwarteten Wort `('
[root@SmartHomeNGRPI4N34 ~]# Building lxml version 4.6.1.
-bash: Building: Kommando nicht gefunden.
[root@SmartHomeNGRPI4N34 ~]# Building without Cython.
-bash: Building: Kommando nicht gefunden.
[root@SmartHomeNGRPI4N34 ~]# Error: Please make sure the libxml2 and libxsl t development packages are installed.
-bash: Error:: Kommando nicht gefunden.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the [tracker for the project in question](https://lxml.de/index.html#bug-tracker) instead.
