### ISSUE TITLE
Uploading package fails due to Invalid or non-existent authentication information, even though it exists

### ISSUE THREAD

**Issue by kaitrepte** [pypa/warehouse#8787]
Hi there,

I tried uploading a new version of a package to PyPi.
I did the same steps as always, but I keep encountering an error with my authentication information.
I now also added an API token to my account, and changed the .pypirc file accordingly.
But I keep getting the same error.

Is this a known issue?

Best

**Comment by di** [comment]
Hi @kaitrepte, sorry you're having trouble. Can you confirm that you're using the `__token__` username instead of your PyPI username in your `.pypirc` file? Also, can you confirm that you're not using a token from TestPyPI for PyPI, or vice versa?

**Comment by kaitrepte** [comment]
Hi there,

I guess I missunderstood the logic here. I now changed the token explicitely to __token__ . 
Sorry about that. Now the upload worked,

Thanks.
