### ISSUE TITLE
gif crop works only for >1 column 

### ISSUE THREAD

**Issue by Kamal-Sonani** [pypa/warehouse#8801]
> open this gif and zoom it .

> check 1x10 cropped gif scrolling color mismatched position while width is **1**

when width is **>1 it works perfectly**  
check this gif
👇(**Zoom it**)
![1010](https://user-images.githubusercontent.com/31804807/98519528-e48fcc00-2296-11eb-872d-102b062587ab.gif)

output of color in gif not as original gif

**-- Not Working  --**  **width is 1**

from imgpy import Img

with Img(fp='1010.gif') as im:
im.crop(box=(0, 1, 1, 10))
im.save(fp='crop.gif')

**-- Working --**  **width is 2**

from imgpy import Img

with Img(fp='1010.gif') as im:
im.crop(box=(0, 1, 2, 10))
im.save(fp='crop.gif')

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
