### ISSUE TITLE
Issue with long description

### ISSUE THREAD

**Issue by PowerBroker2** [pypa/warehouse#8830]
**Describe the bug**
I'm trying to add a long description to [one of my packages](https://github.com/PowerBroker2/WarThunder), but get the following error when trying to push the change:
```
running upload
Submitting dist\WarThunder-2.2.1.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.
error: Upload failed (400): The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.
```
I've already tried everything [mentioned here](https://github.com/pypa/warehouse/issues/5890#issuecomment-494868157), but all the checks pass and the problem still persists.

**My Platform**
Windows 10

Any help would be greatly appreciated

**Comment by hugovk** [comment]
The error says it failed to render RST but your long description is Markdown.

This is a useful guide:

https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/

What versions of setuptools, twine and wheel do you have? Does it work after updating them?

**Comment by PowerBroker2** [comment]
> The error says it failed to render RST but your long description is Markdown.

Idk why it's trying to render in RST when my setup.py specifically says markdown:
```Python

from setuptools import setup

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(
    name             = 'WarThunder',
    packages         = ['WarThunder'],
    version          = '2.2.1',
    description      = 'Python package used to access air vehicle telemetry while in War Thunder air battles',
    long_description = long_description,
    long_description_content_type = "text/markdown",
    author           = 'Power_Broker',
    author_email     = 'gitstuff2@gmail.com',
    url              = 'https://github.com/PowerBroker2/WarThunder',
    download_url     = 'https://github.com/PowerBroker2/WarThunder/archive/2.2.1.tar.gz',
    keywords         = ['War Thunder'],
    classifiers      = [],
    install_requires = ['imagehash', 'requests', 'Pillow', 'WarThunder']
)
```

> What versions of setuptools, twine and wheel do you have? Does it work after updating them?

- setuptools - 50.3.2
- twine - 3.2.0
- wheel - 0.35.1

and no, it doesn't work after update

**Comment by hugovk** [comment]
What command are you using to upload? Please could you paste the whole command and output?

You need to use twine (e.g. `twine upload dist/*`) not something like `python setup.py sdist upload`.

**Comment by pradyunsg** [comment]
You're using setup.py upload. That does not correctly handle metadata and or the files.

Pleass use twine for performing uploads.
