### ISSUE TITLE
Intermittent 404 for existing package/releases

### ISSUE THREAD

**Issue by moser** [pypa/warehouse#8837]
**Describe the bug**
I have seen intermittent 404 responses for some packages. For instance, I tried to access [https://pypi.org/pypi/itypes/1.2.0/json](https://pypi.org/pypi/itypes/1.2.0/json) at 2020-11-17 07:33:51 UTC and got a 404. When I tried a couple of minutes later, I got a 200 response. I only introduced some more logging lately, so I can't tell you the times & packages where the error occurred in the past.

**Expected behavior**
Never return a 404 for an existing package/release. If something goes wrong, PyPI should return a 5xx error so that consumers can detect intermittent failures & retry the request.

**To Reproduce**
Probably hard to reproduce. Maybe you can run a script that does a couple of requests every second and see if you get 404s sometimes.

**My Platform**
OS: Docker image based on python:3.8-slim
"Browser": urllib.request.urlopen
Running on AWS Fargate in eu-central-1

**Additional context**
-

**Comment by di** [comment]
I'm seeing fairly consistent and expected 404 responses from our CDN over the last 24 hours:

![image](https://user-images.githubusercontent.com/294415/99419999-53d27500-28c2-11eb-9ff0-ee15fd65ebd6.png)

Are you still experiencing this?

**Comment by di** [comment]
Closing due to lack of response. If you experience this again and can provide us with a complete request/response it would help significantly to debug.

**Comment by moser** [comment]
Hi, sorry for the late response. Here is a CSV with some events I observed since the bug report. Please note that all those pkg/version combinations exist and usually the requests against those URLs succeed.

```csv
Time UTC,Error,pkg,version,url
14.12.2020 12:13:17,PackageNotFound: Package tablib (1.1.0) not found.,tablib,1.1.0,https://pypi.org/pypi/tablib/1.1.0/json
14.12.2020 09:27:21,PackageNotFound: Package django-money (0.15) not found.,django-money,0.15,https://pypi.org/pypi/django-money/0.15/json
14.12.2020 08:52:53,PackageNotFound: Package django-money (0.15) not found.,django-money,0.15,https://pypi.org/pypi/django-money/0.15/json
14.12.2020 08:40:38,PackageNotFound: Package python-decouple-aws (0.3.2) not found.,python-decouple-aws,0.3.2,https://pypi.org/pypi/python-decouple-aws/0.3.2/json
14.12.2020 08:15:26,PackageNotFound: Package watchtower (1.0.0) not found.,watchtower,1.0.0,https://pypi.org/pypi/watchtower/1.0.0/json
02.12.2020 07:13:27,PackageNotFound: Package faker (4.17.1) not found.,faker,4.17.1,https://pypi.org/pypi/faker/4.17.1/json
02.12.2020 07:13:19,PackageNotFound: Package faker (4.17.1) not found.,faker,4.17.1,https://pypi.org/pypi/faker/4.17.1/json
02.12.2020 07:08:36,PackageNotFound: Package faker (4.17.1) not found.,faker,4.17.1,https://pypi.org/pypi/faker/4.17.1/json
10.11.2020 12:46:32,PackageNotFound: Package tablib (1.1.0) not found.,tablib,1.1.0,https://pypi.org/pypi/tablib/1.1.0/json
```

@di Can you re-open the issue? (I can't)

**Comment by di** [comment]
Would you be able to provide the full 404 response (including headers) the next time you experience this?

Are you only experiencing this for endpoints in the JSON API?

**Comment by moser** [comment]
I only have observed the problem on the JSON API.

I added a bit more error handling which will log the response headers & content. It will also retry the request to see if it would fail two times in a row. Now we have to wait for a while, as the problem is kind of rare :-)

**Comment by di** [comment]
Hi @moser, are you still experiencing this?

**Comment by moser** [comment]
No, I have not had the problem again since mid December. Maybe it was fixed by coincidence :-) Thanks for checking back!

Closing.
