### ISSUE TITLE
Account recovery

### ISSUE THREAD

**Issue by Lancercmd** [pypa/warehouse#8838]
Hi. I unexpectedly deteled a project named "nonebot_plugin_rauthman" before, and I couldn't upload by the same name now unfortunately. Due to its symbolic meaning with its function, I wonder if I could get a recovery for this deleted project. Many thanks.

The account is "Lancercmd"

**Comment by di** [comment]
You can recover the project name by uploading a new version. See https://pypi.org/help/#file-name-reuse.
