### ISSUE TITLE
Does simple-smartsheet work with AWS

### ISSUE THREAD

**Issue by cabbsman** [pypa/warehouse#8856]
I have written Python scripts that use simple-smartsheet.  My work wants to port the code to AWS Lambda environment.  I'm new to the AWS LAMBDA Server less environment. It's described as an AWS Linux environment.

Will I be able to use the simple-smartsheet in this server less environment?

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
