### ISSUE TITLE
Unable to upload package to Pypi using twine, Getting error requests.exceptions.ConnectionError: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))

### ISSUE THREAD

**Issue by 1297rohit** [pypa/warehouse#8863]
**Describe the bug**
I am not able to upload the new version of my package using pypi even after generating token for my project.

**Expected behavior**
Whenever i try to upload it throws error "requests.exceptions.ConnectionError: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))"

**To Reproduce**
twine upload dist/* --repository-url https://pypi.org/project/FaceReco/ -u __token__ -p pypi_token

**My Platform**
Windows

**Additional context**

**Comment by di** [comment]
Hi @1297rohit, sorry you're having issues.

The `--repository-url` you're trying to use isn't valid. It should be the upload endpoint for PyPI instead, not the project URL.

You can omit this flag entirely and twine will default to https://upload.pypi.org/legacy/

**Comment by 1297rohit** [comment]
It starts to upload with my current command but stops just seconds after starting so i think command is right but some other issue.
If i dont specify the url then how will it find ny package.

**Comment by di** [comment]
Specifying the directory `dist/*` tells twine where to find your distribution. PyPI will determine where the release goes based on the project name.

**Comment by 1297rohit** [comment]
Thanks for the help was able to upload it by creating **.pypirc file** and changing the repository url to **https://upload.pypi.org/legacy/**. Pypirc file format can be found from the link **https://packaging.python.org/specifications/pypirc/#pypirc**
