### ISSUE TITLE
macOS 11 wheel upload is not allowed

### ISSUE THREAD

**Issue by minrk** [pypa/warehouse#8870]
**Describe the bug**

Upload of wheels targeting latest stable macOS (11.0) is rejected due to unsupported platform tag:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Binary wheel 'pyzmq-20.0.0-cp38-cp38-macosx_11_0_x86_64.whl' has an unsupported platform tag 'macosx_11_0_x86_64'.
```

**Expected behavior**

Upload of wheels built for current stable macOS (11.0) should be allowed.

**To Reproduce**

Build a wheel with tag `macosx_11_0_x86_64` and try to upload with `twine`. The simplest path is probably to `brew install python` on macOS 11.0 and build a wheel with that. I'm using pyzmq-20.0.0, but anything should do:

```python
brew install python@3.8
/usr/local/opt/python@3.8/bin/python3 -m venv ./env
source ./env/bin/activate
pip wheel pyzmq
twine upload ...
```

Folks who know more about wheels could probably hand-craft an os-tagged wheel on another platform without needing to install the latest macOS.

**My Platform**

macOS 11.0.1, Python 3.8, 3.9 from homebrew. Only homebrew Python targets the latest OS as the minimum version, but probably pyenv or similar would as well, or any Python built from source, I think. Pythons with an earlier target OS (conda, Python.org) do not have this issue.

**Additional context**

This is related to https://github.com/pypa/packaging/pull/319. I don't know where warehouse gets its supported tag list, and it may be that that PR to packaging is actually the only fix necessary, but as of today upload of valid tags is not allowed.

**Comment by di** [comment]
We'll need to make an update here: https://github.com/pypa/warehouse/blob/b9316cb12d0e0d91bf52f6a88f612db40ebf137a/warehouse/forklift/legacy.py#L126-L138

**Comment by minrk** [comment]
@di thanks! opened #8881 and #8882 as candidates to allow upload of these wheels. #8882 *only* adds 11 as a supported major version, whereas #8881 implements support for  pypa/packaging#319 arch tags and allows upload of any major version of macOS >= 10
