### ISSUE TITLE
Add support for "universal2" as a CPU in the platform tag

### ISSUE THREAD

**Issue by ronaldoussoren** [pypa/warehouse#8884]
**What's the problem this feature will solve?**
We added a build variant to CPython that creates "Universal 2" fat binaries on macOS (containing both x86_64 and arm64 code). An example wheel has the filename "pyobjc_core-7.0.1-cp39-cp39-macosx_11_0_universal2.whl".

This wheel is currently rejected by PyPI:

```
% twine upload distribution-dir/*universal2*.whl
Uploading distributions to https://upload.pypi.org/legacy/
Uploading pyobjc_core-7.0.1-cp39-cp39-macosx_11_0_universal2.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 508k/508k [00:01<00:00, 357kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Binary wheel 'pyobjc_core-7.0.1-cp39-cp39-macosx_11_0_universal2.whl' has an unsupported platform tag 'macosx_11_0_universal2'.
```

**Describe the solution you'd like**
I'd like to see support for wheels like this on PyPI, with various version of macOS (the example about uses macOS version 11.0, but older versions should also work. In particular 10.9 because that's the deployment target in the experimental "universal2" installer on python.org.

**Additional context**
See also bpo-41100.

**Comment by dstufft** [comment]
I think this ends up fixed by https://github.com/pypa/warehouse/pull/8881, we just haven't had someone have the time to review it yet. 

If you don't mind giving that a quick look to make sure the platform tags match reality (this is allowing macos 10 and 11, and arm6 and universal2), I can merge that and it should go live.

**Comment by ronaldoussoren** [comment]
The platform tags in that PR look fine. 

I have added a second comment about the check for the major release.  That check will require yearly updates to PyPI: given the current beta for 11.1 it is pretty clear that next summer's major release will be 12.0.

**Comment by dstufft** [comment]
Closing this as I just merged that PR, it should auto deploy relatively soon.

**Comment by ronaldoussoren** [comment]
Thanks for the quick response!
