### ISSUE TITLE
Supporting local version identification for dev release uploads

### ISSUE THREAD

**Issue by jakirkham** [pypa/warehouse#8891]
**What's the problem this feature will solve?**

PEP 440 outlines [local version identifiers]( https://www.python.org/dev/peps/pep-0440/#local-version-identifiers ) as a `+` followed by some alphanumeric characters and optionally `.`s that follow. In turn tools like [versioneer use this to describe changes after a tag]( https://github.com/python-versioneer/python-versioneer/blob/b09e7dbc06944e78afe0e8df0e0a89134c9ca294/details.md#how-do-i-select-a-version-style ). For example here is one such version that versioneer would create `0.17.0a+56.g3bdf95b`. When developing a package, it can be useful to distribute these pre-released versions to end-users using prerelease support from PyPI and pip. However currently it appears PyPI rejects uploads that use these local version identifiers to describe these packages.

**Describe the solution you'd like**

It would be great if PyPI allowed local version identifiers at least for pre-release packages. This way libraries using versioneer or other similar tools can upload there packages without modification.

**Additional context**

NA

**Comment by hugovk** [comment]
This also affects https://github.com/pypa/setuptools_scm, requiring a [workaround to drop the local version](https://github.com/hugovk/pypistats/blob/7c49ab42d0973f8a6b1445189b4dcd806a877732/setup.py#L7-L10).

**Comment by di** [comment]
PEP 440 also says:

> Local version identifiers SHOULD NOT be used when publishing upstream projects to a public index server, but MAY be used to identify private builds created directly from the project source. Local version identifiers SHOULD be used by downstream projects when releasing a version that is API compatible with the version of the upstream project identified by the public version identifier, but contains additional changes (such as bug fixes). As the Python Package Index is intended solely for indexing and hosting upstream projects, it MUST NOT allow the use of local version identifiers.

Closing since PEP 440 explicitly states that local versions should not be used on upstream indices like PyPI.

See also https://github.com/pypa/warehouse/issues/7989

**Comment by jakirkham** [comment]
While I understand that was the original intent of the PEP, it seems like the community has embraced this for dev releases in a few commonly tools. Given this, wouldn't it be worth discussing further?

**Comment by dstufft** [comment]
Discussions would have to happen at discuss.python.org, and would possibly need a new PEP to modify PEP 440.
