### ISSUE TITLE
Encourage generation of 2FA recovery codes

### ISSUE THREAD

**Issue by di** [pypa/warehouse#8897]
In order to cut down on 2FA reset requests, PyPI should encourage/require users to generate recovery codes.

Some ideas:

* Require recovery codes to be generated before upload can succeed if 2FA is enabled
* Require recovery codes to be generated before the user can log in
* Require recovery codes to be generated as part of the 2FA setup
  * Additionally, require the user to burn one of the codes immediately after generation to ensure the codes have actually been downloaded/stored.

**Comment by ewjoachim** [comment]
> Additionally, require the user to burn one of the codes immediately after generation to ensure the codes have actually been downloaded/stored.

I think this is the only way to make sure users actually did write them somewhere.

If we could also check sometimes at login time that they have it (e.g. add a checkbox once every ~2 months asking them to check that they can still access their recovery code, without requesting that they enter one, just to make sure they're aware that it's a thing they might need, and highlighting that if they loose their 2FA app without recovery codes, they will be permanently locked out without any recovery procedure)
