### ISSUE TITLE
can add TensorFlow version for Mac M1 aarch64 version for install

### ISSUE THREAD

**Issue by stride83** [pypa/warehouse#8911]
**What's the problem this feature will solve?**
install tenforflow for Mac arm arch

**Describe the solution you'd like**
whl file for pip3 install 

**Additional context**
no

**Comment by hugovk** [comment]
@stride83 This is the repo for the https://pypi.org/ website, not the actual libraries and projects it hosts.

Please report TensorFlow issues to the project at https://github.com/tensorflow/tensorflow, and it looks like https://github.com/tensorflow/tensorflow/pull/45404 might be what you're after.
