### ISSUE TITLE
abut jaydebeapi problem connect database

### ISSUE THREAD

**Issue by drapelli** [pypa/warehouse#8915]
Hi, 
i install jaydebeapi using pip
appear all work very good 

but when i try to connect it to a database, it not work show error in initialization of import __JPype 

te errro msg are this 

![erro](https://user-images.githubusercontent.com/3890395/102025655-346f2080-3d78-11eb-9627-f35afbf3abf2.png)

I using this code 

import jaydebeapi
conn = jaydebeapi.connect("zim.jdbc.ZJ_DRIVER",
                           "jdbc:zim://localhost:6002:/zimdb01.",
                           ["ZIM", ""],
                           r'C:\Users\xxx\Documents\p01\zimjdbc8.jar')
curs = conn.cursor()
curs.execute('create table CUSTOMER'
               '("CUST_ID" INTEGER not null,'
                ' "NAME" VARCHAR not null,'
                ' primary key ("CUST_ID"))'
             )
curs.execute("insert into CUSTOMER values (1, 'John')")
curs.execute("select * from CUSTOMER")
curs.fetchall()
[(1, u'John')]
curs.close()
conn.close()

i will try connect using drive to sqlite3 jdbc but the error are the same

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
