### ISSUE TITLE
error in 'One File'

### ISSUE THREAD

**Issue by IvanPy-Exe** [pypa/warehouse#8927]
line: pygame. font. Font ('Sumdex Bold. ttf', 26) returns the error: "this file was not found" when I load this file together with main.py in 'one file' with the address: '.' this is sad...

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by IvanPy-Exe** [comment]
> Привет, этот трекер проблем предназначен для проблем с кодовой базой позади https://pypi.org сам по себе, а не проекты, размещенные на PyPI.
> 
> Вместо этого вы должны сообщить об этой проблеме в трекер для рассматриваемого проекта.

если что, это НЕ МОЯ ОШИБКА то что компилятор в пизду запихивает фонт

**Comment by IvanPy-Exe** [comment]
> Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.
> 
> You should report this issue to the tracker for the project in question instead.

если что, это НЕ МОЯ ОШИБКА то что компилятор в пизду запихивает фонт!!!!!
