### ISSUE TITLE
No matching distribution found for torchvision==0.3.0 / torchvision==0.4.0 & other versions

### ISSUE THREAD

**Issue by Amos-85** [pypa/warehouse#8936]
From yesterday I can't download most versions of torchvision package.
I'm getting this exception:

```
ERROR: Could not find a version that satisfies the requirement torchvision==0.4.0
ERROR: No matching distribution found for torchvision==0.4.0
```
same for version 0.4.1 / 0.4.2 / 0.5.0 etc.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
