### ISSUE TITLE
Broken Link in inputimeout 1.0.4

### ISSUE THREAD

**Issue by Rexpert** [pypa/warehouse#8946]
**Describe the bug**

The project link in project page [inputimeout 1.0.4](https://pypi.org/project/inputimeout/) pointed to a 404 Error Page in Github: [http://github.com/johejo/inutimeout](http://github.com/johejo/inutimeout)

**Expected behavior**

It is suppose to redirect user to [http://github.com/johejo/inputimeout](http://github.com/johejo/inputimeout), a **p** is missing in the href attribute

**To Reproduce**

1. Go to project page [inputimeout 1.0.4](https://pypi.org/project/inputimeout/)
2. Click on the project link that redirect you to the github page

**My Platform**

Chrome 87 on Windows 10

**Additional context**

No

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
