### ISSUE TITLE
Please, fix the errata in command "pip install django-celery-progresbar" 

### ISSUE THREAD

**Issue by pikulevlv** [pypa/warehouse#8947]
Please, fix the errata in command "pip install django-celery-progresbar" to "pip install django-celery-progressbar" (double s).
https://pypi.org/project/django-celery-progressbar/

**Comment by pradyunsg** [comment]
This issue tracker is for PyPI itself, not for projects on it.

The correct place for reporting this would be on the project's issue tracker, which can be found from the "project details" section on the PyPI page you've provided: https://github.com/mora9715/django-celery-progressbar
