### ISSUE TITLE
Pypi changed "_" for "-" in the Package name

### ISSUE THREAD

**Issue by milcent** [pypa/warehouse#8950]
**Describe the bug**
In the last release of the [package](https://pypi.org/project/benford-py/), Pypi changed its name from `benford_py` to `benford-py`.

**Expected behavior**
It should keep with its original name, with "_", like it is in [github](https://github.com/milcent/benford_py)  AND in the project setup.py file

**To Reproduce**
[Se here](https://pypi.org/project/benford-py/)

**My Platform**
The only thing different I did in this last release was use twine for uploading the package to Pypi. Before, I was doing the [old way](https://www.codementor.io/@arpitbhayani/host-your-python-package-using-github-on-pypi-du107t7ku).

**Additional context**

**Comment by pradyunsg** [comment]
PyPI (and modern Python packaging tooling) normalises names of packages. Post normalisation "." "-" "_" are all equivalent and represented as "-".

The normalisation is necessary for stabilising URLs and for ensuring that very similar project names don't exist on PyPI.

**Comment by ewdurbin** [comment]
The normalization that you are reporting is happening in [twine itself](https://github.com/pypa/twine/blob/534385596820129b41cbcdcc83d34aa8788067f1/twine/package.py#L61) PyPI does not modify the metadata itself on upload.

warehouse _does_ however normalize the URL for a project, but if the metadata itself is submitted with an `_` that is what would be displayed on the Project page.
