### ISSUE TITLE
403 Forbidden received trying to upload a package with twine

### ISSUE THREAD

**Issue by javiquinte** [pypa/warehouse#8964]
Hi everyone.

When trying to upload a new package I'm receiving a 403 Forbidden error

> $ twine upload dist/daslib-0.5b3.tar.gz
Uploading distributions to https://upload.pypi.org/legacy/
Uploading daslib-0.5b3.tar.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 40.0k/40.0k [00:01<00:00, 26.0kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'javiquinte' isn't allowed to upload to project 'daslib'. See https://pypi.org/help/#project-name for more information.

If I try to upload it to test.pypi.org I see no problems

> $ twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
Uploading distributions to https://test.pypi.org/legacy/
  dist/daslib-0.5b3.tar.gz (27.2 KB)
Enter your username: javiquinte
Enter your password:
username: javiquinte
password: <hidden>
Uploading daslib-0.5b3.tar.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 40.0k/40.0k [00:02<00:00, 20.1kB/s]

View at:
https://test.pypi.org/project/daslib/0.5b3/

**Expected behavior**

As the project is actually a copy (with another name of course) of another one already uploaded to Pypi I expected to upload it quickly and without issues.

**My Platform**

I'm running this in a Mac with python3.9

> $ python3
Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)
[Clang 6.0 (clang-600.0.57)] on darwin

> $ twine --version
twine version 3.3.0 (pkginfo: 1.6.1, requests: 2.25.0, setuptools: 49.2.1, requests-toolbelt: 0.9.1, tqdm: 4.55.1)

Any help would be appreciated!

**Comment by di** [comment]
Hi @javiquinte, sorry you're having trouble.

PyPI and TestPyPI are separate, unfortunately the library `daslib` on PyPI was already used in the past and already has an owner, although it appears abandoned w/ all releases deleted.

You should file a PEP 541 request to acquire the project name at https://github.com/pypa/pypi-support/issues/new/choose.

**Comment by javiquinte** [comment]
Thanks @di for the answer!
I had searched for the name before choosing this one and I found nothing.

https://pypi.org/search/?q=daslib

Could you tell me how should I do to select a name and be sure that there will be no conflicts?

Thanks again for your support!

**Comment by di** [comment]
Yep, sorry about that, it's a bit of an edge case we have: https://github.com/pypa/warehouse/issues/1388

The not-great answer is that you can check whether `https://pypi.org/simple/<project_name>` exists, e.g. https://pypi.org/simple/daslib/ is 200 but https://pypi.org/simple/this-doesnt-exist/ is 404.

**Comment by javiquinte** [comment]
That tip is more than enough! :-)
Thanks!
