### ISSUE TITLE
JSON endpoint for project is 404 if only yanked releases are available

### ISSUE THREAD

**Issue by di** [pypa/warehouse#8966]
From https://github.com/pypa/warehouse/issues/3709#issuecomment-754973958, it appears that the JSON API for a project is 404 if the only releases available are yanked releases.

E.g. https://pypi.org/pypi/django-twilio2/json should probably look like https://pypi.org/pypi/django-twilio2/0.9.0/json instead of being 404.

**Comment by AustinTSchaffer** [comment]
@di Do you know if anyone is working on this? I'm interested in taking a crack at it. I'm working through the getting-started and submitting-patches guides, just didn't want to duplicate any efforts.

**Comment by di** [comment]
It does not appear that anyone is working on this at the moment!

**Comment by AustinTSchaffer** [comment]
Sweet. I have a hopefully quick followup question about this. In the case where all non-prerelease versions of a package are yanked, but there are prerelease versions available that are not yanked, should this endpoint default to a yanked version or a prerelease version?

**Comment by di** [comment]
> Sweet! I have a hopefully quick followup question about this. In the case where all non-prerelease versions of a package are yanked, but there are prerelease versions available that are not yanked, should this endpoint default to a yanked version or a prerelease version?

I think we should return a yanked release only if there are no other non-yanked releases available.

**Comment by AustinTSchaffer** [comment]
Thanks for all of the swift responses, I believe this is all finalized and ready for review.
