### ISSUE TITLE
Dates of data in 2021 are all reported as 2020

### ISSUE THREAD

**Issue by akhilarj** [pypa/warehouse#8997]
The date column reports 2020 Jan data for 2021 cases.

**Comment by di** [comment]
Hi, can you give us more details? What project/URL? Do you have a screenshot?

**Comment by akhilarj** [comment]
Hi,

I am trying to download covid-19 case details with the following command.
turkey_data = covid_daily.data(country = 'Turkey', chart =
'coronavirus-cases-linear', as_json = False)

The output I receive from above is attached here. You can see that 2021
data is labelled under 2020 Jan.

Thanks and Best,
Akhila Joseph

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
