### ISSUE TITLE
Allow package maintainer register an external URL instead of upload real wheel file

### ISSUE THREAD

**Issue by xxr3376** [pypa/warehouse#8998]
**What's the problem this feature will solve?**

Nowadays, lots of packages contain large GPU code binaries that may take hundreds of megabytes. As CUDA11 has released recently, we found our package size increased from 850MB to 2.3GB, we have to request a larger limit again and again
(see https://github.com/pypa/pypi-support/issues/289 https://github.com/pypa/pypi-support/issues/767 ). This lead to 2 problem

1. spent a great amount of bandwidth and storage from PyPI
2. have to delete all old version for more space, this means no history version on PyPI

**Describe the solution you'd like**

* Package maintainer should serve the wheel file on external service (CDN or S3)
* PyPI should allow the package maintainer to register an external URL & checksum, which will be looked like a normal release for users
* pip should follow the external URL and crawl real wheel package from it; validate the checksum for security reason

Additionally, to solve the history version problem:
* PyPI should allow the maintainer to update an existing URL in order to fix a dead link
* PyPI should allow the maintainer to convert a normal file into an external URL (for saving space)
* Maintainer must not change the checksum for an existing item

**Additional context**

* This solution provides a better user experience comparing to ask users to add `-f https://....` after `pip install`
* Another potential way to solve this problem is addressed in  https://github.com/pypa/warehouse/issues/7852

**Comment by di** [comment]
Thanks for raising the issue.

This used to be a feature of PyPI, and was removed. The reasons why are documented in https://www.python.org/dev/peps/pep-0470/ and still stand today -- ultimately, while it may be easier for maintainers in the short term, it's not very user-friendly in the long term.

We're generally able to raise limits for projects like `megengine` and are happy to help explore other options for reducing distribution size, but we're not likely to reverse PEP 470 anytime soon.
