### ISSUE TITLE
Rendering setup.py as project description

### ISSUE THREAD

**Issue by MakerStuff** [pypa/warehouse#8999]
I uploaded a new project today and got the following error returned on `twine upload dist/*`:
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.
```
setup.py/setup/long_description is in markdown format, which i did specify in long_description_content_type="text/markdown"

I did manage to upload my project using
```
python setup.py sdist
python setup.py install
twine upload dist/*
```
but it does not render the way it did the other times i uploaded a project to pypi.org.

The project descriptions includes most of the parameters i used in `setup.py/setup()`. Just some information (license; i included the full text here) is split to project meta and project description and other information is stuffed in there with no line break.

For reference: my project can be found [on PyPI](https://pypi.org/project/PyTop-Generator/0.0.1/) and my repo is located [on GitLab](https://gitlab.com/Raspilot/pytop-generator).

Is the packaging information i used (i double checked the [official tutorial](https://packaging.python.org/tutorials/packaging-projects/) outdated or is it a bug in warehouse?

Edit: `python3 -m readme_renderer ~/Documents/Projects/Software/pytop_generator/README.md -o /tmp/README.html && firefox /tmp/README.html` shows the plain README.md without any formatting.

**Comment by di** [comment]
Hi, looks like this is https://github.com/pypa/setuptools/issues/1390, you should check if there are newlines in your `Description` (or summary) field.

**Comment by MakerStuff** [comment]
Yep. That was just about it. Close enough at least to figure out, that the same problem appears when using new lines in `license`. I previously used `license=open("LICENSE").read(),`. Now i reduced it to be `license="BSD License"`. Thank you for the hint!
