### ISSUE TITLE
"500: Internal Server Error" during a routine package update

### ISSUE THREAD

**Issue by MKuranowski** [pypa/warehouse#9033]
**Describe the bug**

During a routine package upload the servers (both the "normal" and "test" repos) reply with a non-descriptive "500 Internal Server Error".

Apart from not being able to upload updated packages, I am also tempted to say that a simple "500 Internal Server Error" reply is an issue in and of itself, and that more information about what went wrong should be returned. I have no clue what could I do to resolve this issue on my own and I have to bother you and create an issue.

**Expected behavior**

I would expect the package to be normally uploaded, or, at least an error message that would describe what went wrong.

**To Reproduce**

```
git clone git@github.com:MKuranowski/osmiter.git
python setup.py sdist bdist_wheel
twine upload --verbose dist/osmiter-1.1.1.tar.gz dist/osmiter-1.1.1-py3-none-any.whl
```

<details>

<summary>Output of twine</summary>

```
Using configuration from /home/mikolaj/.pypirc
Uploading distributions to https://upload.pypi.org/legacy/
  dist/osmiter-1.1.1-py3-none-any.whl (19.0 KB)
  dist/osmiter-1.1.1.tar.gz (18.8 KB)
username set from config file
password set from config file
username: __token__
password: <hidden>
Uploading osmiter-1.1.1-py3-none-any.whl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.7k/29.7k [00:00<00:00, 35.9kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 1 of 5
Uploading osmiter-1.1.1-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.7k/29.7k [00:00<00:00, 156kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 2 of 5
Uploading osmiter-1.1.1-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.7k/29.7k [00:00<00:00, 157kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 3 of 5
Uploading osmiter-1.1.1-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.7k/29.7k [00:00<00:00, 137kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 4 of 5
Uploading osmiter-1.1.1-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.7k/29.7k [00:00<00:00, 120kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 5 of 5
Content received from server:
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>

HTTPError: 500 Internal Server Error from https://upload.pypi.org/legacy/
Internal Server Error
```

</details>

**My Platform**
Linux 5.10, Manjaro, Python 3.9.1.

Twine is installed via the system package manager, and the output of `twine --version` is:
`twine version 3.3.0 (pkginfo: 1.7.0, requests: 2.25.1, setuptools: 51.1.2, requests-toolbelt: 0.9.1, tqdm: 4.56.0)`

**Additional context**
Tried authenticating both with username-password and tokens - didn't help.

Changing the passwords and tokens didn't help, as per #8431.

Manually installing the created wheel and sdist files in a venv works perfectly fine.

Exact timings for uploads are:
- upload.pypi.org: 2021-01-28 10:45:15 UTC
- test.pypi.org: 2021-01-28 10:48:41 UTC

Here are the files I'm trying to upload:
- [osmiter-1.1.1.tar.gz](https://github.com/pypa/warehouse/files/5886570/osmiter-1.1.1.tar.gz)
- [osmiter-1.1.1-py3-none-any.whl.zip](https://github.com/pypa/warehouse/files/5886578/osmiter-1.1.1-py3-none-any.whl.zip)

**Comment by ewdurbin** [comment]
Seems the error is being raised by our webserver, and not warehouse code which is what is causing the nondescript error.

```UnicodeEncodeError: 'latin-1' codec can't encode character '\u0430' in position 27: ordinal not in range(256)```

This seems to have been introduced in https://github.com/MKuranowski/osmiter/commit/08e8a7a8b2226f0d870ae8603b0e34da32e4fa0a and encodes a `Unicode Character 'CYRILLIC SMALL LETTER A' (U+0430)` for the `[at]` part of the obfuscated email address.

It's still not clear exactly why this is choking out our webserver.

**Comment by ewdurbin** [comment]
OK, on closer inspection it appears that the issue is that there is some error _attempting_ to be returned from warehouse's backend.

The flawed design of the error response in [this code](https://github.com/pypa/warehouse/blob/18747c5ffa40e42a4283bd08fd0441a9b19b75df/warehouse/forklift/legacy.py#L212-L217) includes the full message in the HTTP Status header, which could absolutely include characters that are not valid for an HTTP header.

**Comment by ewdurbin** [comment]
@MKuranowski I suspect the issue is that your new obfuscated email including ` [аt] ` rather than `@` for the Author-Email metadata field failing to validate as a valid RFC822 email address (because it is not).

The resulting error includes that `Unicode Character 'CYRILLIC SMALL LETTER A' (U+0430)` which then causes the webserver to error, leading to a 500.

**Comment by ewdurbin** [comment]
Confirmed and reproduced locally. Will submit a fix shortly.

**Comment by MKuranowski** [comment]
Ok, makes total sense that author_email has to be a valid email address.

Replacing the cyrylic a with an ascii a creates a nice error `HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
'mkuranowski [at] gmail.com' is an invalid value for Author-email. Error: Use a valid email address See https://packaging.python.org/specifications/core-metadata for more information`.

I guess there should be a fix somewhere in the [form validation](https://github.com/pypa/warehouse/blob/18747c5ffa40e42a4283bd08fd0441a9b19b75df/warehouse/forklift/legacy.py#L861) against non-valid charachters?

**Comment by ewdurbin** [comment]
this should be resolved. characters that cannot be encoded into latin-1/iso-8895-1 will be replaced with `?` in messages.
