### ISSUE TITLE
Dismissing in the documentation that customization for INSTALLED_APPS is required

### ISSUE THREAD

**Issue by jimdevops19** [pypa/warehouse#9040]
**What's the problem this feature will solve?**
https://pypi.org/project/django-markdownfield/ documentation does not include to write `markdownfield` under INSTALLED_APPS

**Additional context**
Might not be very obvious for new learners :)

**Comment by pradyunsg** [comment]
Hi! This issue tracker is for the codebase that runs pypi.org, not for projects hosted on pypi.org. Please file an issue on that django-markdownfield's issue tracker instead of here.
