### ISSUE TITLE
New change to simple pages creating SAX parser exception issue

### ISSUE THREAD

**Issue by pegacloud** [pypa/warehouse#9046]
We are using gradle jython
https://github.com/rzabini/gradle-jython and suddenly all our gradle builds have started failing with this

_00:32:46 Downloading troposphere, version 2.6.3
00:32:46 inferred path is: https://pypi.python.org/simple/troposphere
Caused by: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 5; The element type "meta" must be terminated by the matching end-tag "</meta>"._

The error  is coming from

https://github.com/rzabini/gradle-jython/blob/dad5d00435922bc66a7f5f8f999025433786082f/src/main/groovy/jython/util/PackageFinder.groovy#L49

After debugging it more we found out the following commit https://github.com/pypa/warehouse/pull/9030 has added meta tag which is causing the code to throw SAXParser exception.
The gradle builds were working without any issues till Last week. I appreciate any help in resolving this issue.

**Comment by ewdurbin** [comment]
The Simple Repository API defined in [PEP 503](https://www.python.org/dev/peps/pep-0503/) and further extended by [PEP 592](https://www.python.org/dev/peps/pep-0592/)/[PEP 629](https://www.python.org/dev/peps/pep-0629/)(which is implemented in the referenced PR) specifies the pages as HTML and that is what is implemented by warehouse.

The newly added `<meta>` tag is valid HTML, however it appears that the project is using an XML parser.

I believe this issue should be filed with the [gradle-jython project](https://github.com/rzabini/gradle-jython) to be resolved.

**Comment by pegacloud** [comment]
ok.. Thanks.. We will follow up with gradle-jython project.
