### ISSUE TITLE
Inconsistent version information on pypi.org for `pyrouge` package

### ISSUE THREAD

**Issue by rshin** [pypa/warehouse#9053]
**Describe the bug**

https://pypi.org/search/?q=pyrouge shows 0.1.2 as the latest available version:
![Screen Shot 2021-02-03 at 11 48 10 AM](https://user-images.githubusercontent.com/13770/106800755-bdd2fe80-6615-11eb-9712-50b6342a9139.png)

But https://pypi.org/project/pyrouge/ and https://pypi.org/project/pyrouge/#history show 0.1.3 as the latest, released in October 2016.

At the JSON endpoint, https://pypi.org/pypi/pyrouge/json, we see the following:
```
{
    "info": {
		...
        "release_url": "https://pypi.org/project/pyrouge/0.1.3/",
        ...
        "version": "0.1.3",
        ...
    },
    "last_serial": 2388559,
    "releases": {
        "0.1.0": [
        	...
        ],
        "0.1.1": [
			...
        ],
        "0.1.2": [
            {
				...
                "downloads": -1,
                "filename": "pyrouge-0.1.3.tar.gz",
                "upload_time": "2016-10-08T18:37:10",
                "upload_time_iso_8601": "2016-10-08T18:37:10.654022Z",
                "url": "https://files.pythonhosted.org/packages/11/85/e522dd6b36880ca19dcf7f262b22365748f56edc6f455e7b6a37d0382c32/pyrouge-0.1.3.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "0.1.3": []
    },
    "urls": []
}
```
where 0.1.3 is shown as the latest version under `info`, but `0.1.3` is empty under `releases`, and `pyrouge-0.1.3.tar.gz` is present under `0.1.2`.

**Expected behavior**

The above sources should agree that 0.1.3 is the latest version.

**To Reproduce**

See above links.

**My Platform**

I noticed this because `poetry` refused to install `pyrouge==0.1.3`. This seems to be because `["releases"]["0.1.3"]` in the JSON was empty.

**Comment by di** [comment]
The release has no files, compare https://pypi.org/project/pyrouge/0.1.2/#files and https://pypi.org/project/pyrouge/0.1.3/#files (doesn't exist) so there's no distribution to actually install for that release, and nothing to show in the JSON result.

It looks like the original distribution files were removed but the release was not deleted. This was done in 2016 before the PyPI relaunch, so it's almost definitely not possible to do today.

The solution would be to just delete that release, but it also looks like the project isn't maintained anymore. A workaround for users like you would be to specify `pyrouge<=0.1.2`.
