### ISSUE TITLE
python connexion module expecting formData key which we never use in open api 3

### ISSUE THREAD

**Issue by vijaya2497** [pypa/warehouse#9074]
i am working open api 3.  For my PUT request  content-type  set to  multipart/form-data and I also have path parameter too. I enabled strict_validation for validating parameters. Parameter validator in connexion/decorators/validation.py is validating form parameters but in open api 3 we are not defining formData parameters like this( in:formData) anymore we are using request body only for media types.

    def validate_formdata_parameter_list(self, request):
        request_params = request.form.keys()
       
        try:
            spec_params = [x['name'] for x in self.parameters['formData']]
        except KeyError:
            # OAS 3
            return set()
        return validate_parameter_list(request_params, spec_params)

    we are using only in:path and in:query in openapi 3 so no need of validating formData parameters in parameter validator so my suggestion is to remove validate_formdata_parameter_list function from parameter validator

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
