### ISSUE TITLE
pip install tables fails on Mac

### ISSUE THREAD

**Issue by andycon** [pypa/warehouse#9077]
**Describe the bug**
pip install tables
fails for python3.9 on macOS Catalina

note: on same system "pip3.8 install tables" works fine.

**Expected behavior**
Successful pip install of tables

**To Reproduce**

with Python3.9:

pip install tables

**My Platform**

--- ~ » pip --version                                                                        2 ↵
pip 20.2.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	1037.147.4.0.0 (iBridge: 17.16.16610.0.0,0)
  Serial Number (system):	C02ZC4N1LVDQ
  Hardware UUID:	E053BA4E-85A9-55D1-BFE0-B6CEC08397CE
  Activation Lock Status:	Enabled

System Software Overview:

  System Version:	macOS 10.15.7 (19H15)
  Kernel Version:	Darwin 19.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	Andrew’s MacBook Pro (3)
  User Name:	Andrew Connolly (andy)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	9 days 3:10

**Additional context**
[tables_pip3.9_bugreport.txt](https://github.com/pypa/warehouse/files/5961383/tables_pip3.9_bugreport.txt)

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
