### ISSUE TITLE
2FA works on test.pypi.org but not pypi.org

### ISSUE THREAD

**Issue by sffjunkie** [pypa/warehouse#9086]
**Describe the bug**
When trying to log into `pypi.org` it asks for a USB 2FA device to be used (a Yubikey). This raises the following error on Firefox when using the Yubikey

    An attempt was made to use an object that is not, or is no longer, usable

On Chromium it shows 

    You're using a security key that's not registered with this website

**However logging into `test.pypi.org` using the Yubikey works**

How can I get access to the main `pypi.org` account?
If I remove 2FA from `test.pypi.org` will that affect both `pypi.org` and `test.pypi.org`, will it screw up both accounts?

Note:
* 2FA was set up during the initial rollout
* I think I only configured it on `test.pypi.org`
* I have not logged in for about a year.

**Expected behavior**
The system allows me in to `pypi.org`

**Comment by di** [comment]
PyPI and TestPyPI are completely separate. Is it possible you registered a different 2FA device with PyPI?

**Comment by sffjunkie** [comment]
Damn, I'm getting old. Is that a good enough excuse?

I bought a new key recently and I do not remember updating my account to use it. Anyway it works. Thanks for the prompt to challenge my assumptions.

Why is it only after you publicly ask the question that you work out the answer for yourself? PEBKAC.
