### ISSUE TITLE
Developer setup inst. main/master?

### ISSUE THREAD

**Issue by just-linux** [pypa/warehouse#9087]
Seeing that the project has switched to "main" as default now, the current developer setup steps start out as:

- git remote add upstream https://github.com/pypa/warehouse.git
- git checkout **master**
- git fetch upstream
- git merge upstream/**master**

Should master be changed to main here?

**Comment by di** [comment]
Yes! Thanks for raising the issue.

**Comment by just-linux** [comment]
I have completed most of the changes to the documents with exception of the historical section. Some of the links in the historical section do not appear to be valid links anymore.

I am trying to work through one issue with a change that gives a *warning, treated as an error* when I run *make docs*.

**Comment by just-linux** [comment]
I ref #9095, somehow posted the pull request  to #9095 instead of here.
