### ISSUE TITLE
latest version of package is not showing up correctly

### ISSUE THREAD

**Issue by tank-overlord** [pypa/warehouse#9094]
**Describe the bug**

I uploaded a new version (0.0.0a10) for chess4fun yesterday.
However, the pypi page of the package (https://pypi.org/project/chess4fun/) still shows the older version from last week (0.0.0a9).

What is weird is that when I connect to 0.0.0a9 directly (https://pypi.org/project/chess4fun/0.0.0a9/), a click says "Newer version available (0.0.0a10)", but when I click that link (https://pypi.org/project/chess4fun/), it redirects me to 0.0.0a9 again.

**Expected behavior**

as of today, https://pypi.org/project/chess4fun/ should show 0.0.0a10, not 0.0.0a9

**To Reproduce**

https://pypi.org/project/chess4fun/
https://pypi.org/project/chess4fun/0.0.0a9/
https://pypi.org/project/chess4fun/0.0.0a10/

**My Platform**

OS, browser - independent

**Additional context**

**Comment by di** [comment]
I see `0.0.0a10` when loading the project page:

![image](https://user-images.githubusercontent.com/294415/107992223-df30d480-6f9d-11eb-9a59-498b7f6ced5d.png)

It's likely that this wasn't immediately purged from our CDN's cache.
