### ISSUE TITLE
Cannot upload my project

### ISSUE THREAD

**Issue by neutrinoceros** [pypa/warehouse#9099]
**Describe the bug**

I'm trying to upload my project named `pyw` but I'm getting this error message
```
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'crobert' isn't allowed to upload to project 'pyw'. See https://pypi.org/help/#project-name for more information.
```
While the url https://pypi.org/project/pyw/ actually seems free, and I was able to upload to test.pypi without a problem.
I'm guessing what's happening is that the name is already taken by a removed project, in which case, can I claim it ?
Thanks.

**Comment by di** [comment]
Yes, please file a PEP 541 request here: https://github.com/pypa/pypi-support/issues
