### ISSUE TITLE
PypeR stops working suddenly when  we make 2 calls to same r script at the same time. 

### ISSUE THREAD

**Issue by manibha-jain** [pypa/warehouse#9127]
**Describe the bug**
hi i am using django framework and used python's "pyper" module to run r script from python but the code suddenly stops working when 2 requests are sent at the same time to pyper.

**Expected behavior**
 It should atleast complete a single request and not hang the project or server. 

**To Reproduce**
just write a code to run r script and run it 5-6 times at the same time.

**My Platform**
  this error shows up even in localhost and my python version is 3.6.9.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
