### ISSUE TITLE
HTTPError: 502 Bad Gateway from https://upload.pypi.org/legacy/

### ISSUE THREAD

**Issue by dantuin** [pypa/warehouse#9151]
Pypi returns 502 error when uploading several packages via twine, **test pypi works fine**

Received "502: Bad Gateway" Package upload appears to have failed.  Retry 5 of 5
Content received from server:
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.13.9</center>
</body>
</html>

HTTPError: 502 Bad Gateway from https://upload.pypi.org/legacy/
Bad Gateway

**Comment by Innixma** [comment]
Same issue here, been experiencing for the past 1.5 hrs

**Comment by casperdcl** [comment]
Also does https://status.python.org incorrectly get formatted as if it's on a 150px wide screen for anyone else?

**Comment by busunkim96** [comment]
https://status.python.org still shows "partial outage" for "pypi.org - Backends" but some uploads seem to be making it through now. The latest releases lists multiple packages from the last five minutes.

**Comment by ewdurbin** [comment]
Apologies. During the cleanup for a recent mass upload, our DB was inadvertently locked in such a way that uploads would fail while nearly all other events on the site were successful.

This was detected when our DB finally overflowed on sessions, and not sooner because the uploads endpoint "liveness" was broken in such a bizarre way (package upload times out due to DB lock up).

I've updated our monitoring to include an alert for "time since last upload" to catch these more subtle failures sooner.

**Comment by verhovsky** [comment]
Not sure if this is related, but I uploaded version 0.0.7 of my package 45 minutes ago. I can navigate to it directly https://pypi.org/project/postalcodes-ca/0.0.7/ and opening an old release says "Newer version available (0.0.7)" but the homepage of my project still shows 0.0.6 https://pypi.org/project/postalcodes-ca and it's not listed in the "Release history" tab https://pypi.org/project/postalcodes-ca/#history but it is listed in the tab if I'm on one of the version specific pages https://pypi.org/project/postalcodes-ca/0.0.6/#history

**Comment by ad12** [comment]
+1

**Comment by itsbrex** [comment]
Thanks @di. Been going in circles here with my ci action

**Comment by fjarri** [comment]
Happening again for me. Is there a procedure for reporting this?

**Comment by miketheman** [comment]
@fjarri https://status.python.org/incidents/6zgs59xbw9s4

**Comment by Wenzel** [comment]
Also happened to me right now
![image](https://github.com/pypi/warehouse/assets/964610/c7ca0193-aa6b-46bb-b201-73336b6af8d5)

**Comment by niklassiemer** [comment]
It is happening again - https://status.python.org/incidents/z5wjvxhnscby tracks the current status.

**Comment by vietanhdev** [comment]
It is happening for me now - Vietnam.

**Comment by gferragu** [comment]
@niklassiemer, @vietanhdev, also just experienced this with PyPi and can confirm TestPyPi was working fine immediately beforehand.

**Comment by TahaAli0** [comment]
Currently having the same issue.
```shell
Enter your username: __token__
Enter your password: 
Uploading pikanetwork.py-0.0.1.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 kB • 00:00 • ?
WARNING  Received "502: Bad Gateway"
         Package upload appears to have failed. Retry 1 of 5.
Uploading pikanetwork.py-0.0.1.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 kB • 00:00 • ?
WARNING  Received "502: Bad Gateway"
         Package upload appears to have failed. Retry 2 of 5.
Uploading pikanetwork.py-0.0.1.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 kB • 00:00 • ?
WARNING  Received "502: Bad Gateway"
         Package upload appears to have failed. Retry 3 of 5.
Uploading pikanetwork.py-0.0.1.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 kB • 00:00 • ?
WARNING  Received "502: Bad Gateway"
         Package upload appears to have failed. Retry 4 of 5.
Uploading pikanetwork.py-0.0.1.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 kB • 00:00 • ?
WARNING  Received "502: Bad Gateway"
         Package upload appears to have failed. Retry 5 of 5.
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 502 Bad Gateway from https://upload.pypi.org/legacy/
         Bad Gateway

```

**Comment by ewdurbin** [comment]
The recent issues in the past 48 hours have been due to a backfill script running that was causing lock contention in the DB. I've dropped the batch size on this task to reduce the impact.

Locking this issue. Future upload issues should be reported to a new issue.
