### ISSUE TITLE
How to override nav config so the exclude plugin works?

### ISSUE THREAD

**Issue by NavyaG-lab** [pypa/warehouse#9152]
I have a scenario where in the mkdocs.yml, the nav is customized as per designed taxonomy. Now, we want to exclude some folders not to be rendered on the static site. For that, I used mkdocs-exclude and removed links under the "nav" in the mkdocs.yml. As the files are in docs directory and not under nav, it's throwing error.

Could someone please help me how to achieve desired goal?

Exclude the specific folders in the repo and remove some links from nav, so the static site renders only the desired content.

Thanks!

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
