### ISSUE TITLE
browse(classifiers) without XML-RPC

### ISSUE THREAD

**Issue by tlambert03** [pypa/warehouse#9156]
I feel certain that this has been discussed... please forgive me if I missed the previous issue:
I'm wondering if there is an API to retrieve a list of all releases classified with a given classifier in one of the newer APIs, similar to the `browse` function in the deprecated XML-RPC API.

thanks!

**Comment by di** [comment]
There is not. A few alternatives:

* Use the Web UI instead: https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3
* Use the `distribution_metadata` table in our public dataset instead: https://console.cloud.google.com/marketplace/product/gcp-public-data-pypi/pypi

Could you explain your use case a bit?

**Comment by tlambert03** [comment]
Thanks for the quick response!  I work on an app (https://github.com/napari/napari/) that has an integrated gui plugin installer (see quick gif [here](https://github.com/napari/napari/pull/1357) if curious), where we'd like to surface packages that provide [`Framework :: napari`](https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+napari).  Currently we _are_ just parsing the HTML from the web UI... and can continue to do so, but just wondered if there was a better way.

Thanks for pointing me to the public dataset, I'll look into how we might use that instead.

**Comment by di** [comment]
In that case, the public dataset might not be ideal: while it's updated in near-real-time, there is a bit of a lag. You'd also probably want to run the query yourself and cache the results somewhere.

The HTML from the web UI will probably not change significantly between now and when we eventually provide an equivalent JSON API.

**Comment by tlambert03** [comment]
ok, thanks!  between caching the result and just parsing the HTML, I think we'll be fine for now.  Will keep an eye out for JSON API updates.  Thanks for your help!

**Comment by neuromusic** [comment]
> when we eventually provide an equivalent JSON API

@di do you have a sense of the timeline for this? or a good issue to track?

**Comment by di** [comment]
I have no timeline, sorry. The issue to track is https://github.com/pypa/warehouse/pull/284.

**Comment by neuromusic** [comment]
perfect, thank you!
