### ISSUE TITLE
Provide for robots.txt disabling indexing altogether (eg. for test repos)

### ISSUE THREAD

**Issue by dkuebric** [pypa/warehouse#916]
testpypi.python.org is currently indexed by google.  This isn't too useful, and also has the chance of "leaking" test releases of packages which might not be ready to ship.  A simple way to address this would be using robots.txt to disable indexing on the entire warehouse instance.

**Comment by ewdurbin** [comment]
This is a great idea, thank you @dkuebric!

**Comment by ewdurbin** [comment]
I think `X-Robots-Tag: noindex` on the Fastly configuration for testpypi.python.org and test.pypi.org is sufficient.

We can get this out today.

**Comment by di** [comment]
Does it make sense to do both? For robots that may disregard the header.

**Comment by ewdurbin** [comment]
Header now set for testpypi.python.org. I'll look into adding a robots.txt for the old codebase another time.

PR incoming for test.pypi.org.
