### ISSUE TITLE
Can't install infoblox_client

### ISSUE THREAD

**Issue by dazmac10** [pypa/warehouse#9173]
Can't install infoblox_client using pip

using python 3.9.2
Windows 10

Entered the following command

pip install infoblox-client

got this error.
Running setup.py install for netifaces ... error

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
