### ISSUE TITLE
Strange wording for "Last released" on user pages.

### ISSUE THREAD

**Issue by domdfcoding** [pypa/warehouse#9174]
**Describe the bug**
On a user page on PyPI (e.g. https://pypi.org/user/DomDF/), in the list of projects the wording which indicates when a project was last released is strange.

With dates, it works, displaying the message:

```
Last released on Mar 6, 2020
```

For projects with recent releases, however, the message has strange wording:

```
Last released on less than a minute ago
```

or 

```
Last released on 9 minutes ago
```

or 

```
Last released on about 3 hours ago
```

Here is a screenshot illustrating this:

![image](https://user-images.githubusercontent.com/8050853/110256916-4d602a00-7f93-11eb-99d6-0976ac7ae08a.png)

**Expected behavior**

The message should read e.g. `Last released 9 minutes ago` (i.e. with the word `on` only appearing with dates, not times.)

**To Reproduce**
1. Click on one of the "New releases" on the pypi.org homepage.
2. Click on one of the names under "Maintainers" on the sidebar to go to the user's page
3. The strange wording can be observed for their most recently updated project.

**Comment by di** [comment]
Thanks! Looks like this was missed in https://github.com/pypa/warehouse/pull/8965.

I've added the "good first issue" label to this issue.

**Comment by Dhairya3124** [comment]
Hey @di I would like to work on this issue
