### ISSUE TITLE
Download statistics

### ISSUE THREAD

**Issue by Dancho80** [pypa/warehouse#9191]
We are trying to understand how many new consumers are downloading our packages each month.
The new user is considered as a consumer  (person/system/etc) who had never done this before.
A MAC address of the consumer may be a good indicator since it doesn’t change.
IP address is probably not sufficient as a consumer IP may be changed based on its network policy.
Is it possible to get this data?

**Comment by ewdurbin** [comment]
https://warehouse.readthedocs.io/api-reference/bigquery-datasets.html documents the public datasets available for analyzing PyPI's download statistics and access to the simple index. no further data is accessible or planned to be made accessible.
