### ISSUE TITLE
Give sponsors a week notice before Warehouse goes live

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#920]
It's been requested that we give our sponsors a little bit of notice for when Warehouse goes live so that they can write blog posts or do other sort of marketing type things to coincide with the launch and the inclusion of their logo and such in our footer. This seems like a pretty reasonable request so I'm just filing this as a pre-launch task.

**Comment by brainwane** [comment]
To be very clear, I am treating this as something we will do before the redirect-type launch, not something we will do before announcing the beta.

**Comment by brainwane** [comment]
@MarkMangoba is this now complete?

**Comment by dstufft** [comment]
Talked to Mark, this is done.
