### ISSUE TITLE
Confirm password prompts warning before we start giving input to it.

### ISSUE THREAD

**Issue by Dhairya3124** [pypa/warehouse#9203]
![image](https://user-images.githubusercontent.com/31827131/110896613-f73c0f80-8321-11eb-9abd-033420cc37f4.png)

From the above image we can see that confirm password starts prompting "Passwords do not match" but I think that it should start the prompt when we have given at least one character input.

**Comment by di** [comment]
I agree! The logic for this is here: https://github.com/pypa/warehouse/blob/aafc5185e57e67d43487ce4faa95913dd4573e14/warehouse/static/js/warehouse/controllers/password_match_controller.js#L24-L40

I've also added the "good first issue" and "javascript" labels to this issue.

**Comment by Dhairya3124** [comment]
Okay @di I'm working on it 👍

**Comment by Dhairya3124** [comment]
In line 25 we can check for the first field by  this.passwordMatchTargets.every(field => field.value === "") but how we can check for the second field any hint or idea?

**Comment by Dhairya3124** [comment]
And anyone can tell how I can check my code quickly after making changes in .js files as I have to stop the makefile and then run it again.

**Comment by di** [comment]
> In line 25 we can check for the first field by this.passwordMatchTargets.every(field => field.value === "") but how we can check for the second field any hint or idea?

Maybe instead of `.every` there is a `.any`? Using that would let us disable the check if any of the fields are empty.

> And anyone can tell how I can check my code quickly after making changes in .js files as I have to stop the makefile and then run it again.

The static pipeline should rebuild automatically when a change is made, if it's not for this file it's a bug.

**Comment by Dhairya3124** [comment]
@di Thanks and Yeah I think it's a bug.

**Comment by abid1998** [comment]
@di @Dhairya3124 are you still working on it ? if not i can pick this up. I am a new contributor.

**Comment by Dhairya3124** [comment]
Hey @abid1998 I'm still working up on it 😊

**Comment by ViAsmit** [comment]
Anyone working on this issue? I am taking it up.

**Comment by pransin** [comment]
Hey, is anyone working on this issue?
