### ISSUE TITLE
module ‘time’ has no attribute ‘clock’

### ISSUE THREAD

**Issue by lichanghong** [pypa/warehouse#9211]
time.clock（）已经在新的版本中移除了。在Python3.8中更新了。期待Crypto也能更新下
“The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)”

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
