### ISSUE TITLE
Link directly to subpages of a package

### ISSUE THREAD

**Issue by tritium21** [pypa/warehouse#932]
It would be lovely to be able to link directly to the subpage of a package, so that one can link directly to the page they are interested in.  I understand this can be done by appending an anchor or id...or some other string that the javascript can handle... to the url's fragment.

(By subpage, I mean the Dependencies graph, the version history, the download statistics, etc)

**Comment by dstufft** [comment]
I was talking about this with @nlhkabu earlier today! Tagged it with design since this is in her domain :]

**Comment by nlhkabu** [comment]
Yes, as discussed this will most likely require a new JS tab plugin.  I'm happy to look into some lightweight alternatives to what we are currently using (http://refills.bourbon.io/)
