### ISSUE TITLE
Reset password doesn't work if user doesn't have verified/primary email address.

### ISSUE THREAD

**Issue by gward** [pypa/warehouse#9321]
**Describe the bug**

Password reset is not working. I get the email, follow the link, enter the password twice, submit the form, and get back a page with no error messages. But the page title is "Error processing form -- Log in".

**Expected behavior**

I expected a positive confirmation that my password was reset, and to be able to login with the new password. Neither one happens.

**To Reproduce**

1. Start at `https://pypi.org/account/login/`
2. Click "Forgot password?" link
3. Enter the email address associated with my PyPI account (gerg.ward at gmail dot com)
4. Check my inbox and the email is already there.
5. Click the link: `https://pypi.org/account/reset-password/?token=.eJw1...`
6. Generate a new password outside my browser.
7. Copy/paste the new password into both password fields; text changes to "Passwords match" and the "Reset password" button is enabled.
8. Click "Reset password"
9. Receive the same "Reset password" form again, but with positive confirmation and no error messages. Only the page title gives a clue: "Error processing form –  Reset your password · PyPI". When I try to login with the new password (again, copy/pasted), it does not work.
 
I'll attach HTML and screenshot.

**My Platform**

Firefox 87.0 on Ubuntu 20.04.2.

Same behaviour with Chromium.

No HTTP proxy.

**Additional context**

**Comment by gward** [comment]
Screenshot 1: right before I submit the form:

![pypi-password-reset-fail-1](https://user-images.githubusercontent.com/51437/113213624-6f716300-9246-11eb-8c47-72e7416b1746.png)

Screenshot 2: the result of submitting the form:

![pypi-password-reset-fail-2](https://user-images.githubusercontent.com/51437/113213668-7d26e880-9246-11eb-817e-c381c1d6ef20.png)

**Comment by gward** [comment]
gzipped HTML of the error page, with tokens censored:

[pypi-password-reset-fail.html.gz](https://github.com/pypa/warehouse/files/6239682/pypi-password-reset-fail.html.gz)

**Comment by di** [comment]
I just went through this flow with a new account and was able to successfully reset my password.

Are you able to open Chrome/Firefox devtools and check for JavaScript/console/network errors? Are you able to try a different platform entirely? Also can you share your PyPI username with us?

**Comment by gward** [comment]
PyPI username is `gward`. This account was recently recovered with a [support ticket](https://github.com/pypa/pypi-support/issues/993). I hope that's not relevant, but you never know!

**Comment by gward** [comment]
When I load the page initially (eg. by following the reset link in my email), Firefox' JS console logs this:
```
Navigated to https://pypi.org/account/reset-password/?token=.eJw1...
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:794067
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-55961911-1”. reset-password:73:1
Loading failed for the <script> with source “https://www.fastly-insights.com/insights.js?k=6a52360a-f306-421e-8ed5-7417d0d4a4e9&dnt=true”. reset-password:74:1
```
(with token censored manually)

When I submit the form, it seems to log exactly the same thing again:
```
Navigated to https://pypi.org/account/reset-password/?token=.eJw1...
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:794067
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-55961911-1”. reset-password:73:1
Loading failed for the <script> with source “https://www.fastly-insights.com/insights.js?k=6a52360a-f306-421e-8ed5-7417d0d4a4e9&dnt=true”. reset-password:74:1
```

**Comment by di** [comment]
The ways that this form can fail include:

* No data provided
* Password strength isn't sufficient
* Password fields don't match
* Password has appeared in a breach (via https://haveibeenpwned.com/)

Can you confirm that you're using a new, strong, randomly generated password? Are you generating a different password each time?

**Comment by di** [comment]
I also confirmed that attempting to use a breached password will raise a corresponding error:

![image](https://user-images.githubusercontent.com/294415/113217159-1f44d180-9243-11eb-9fe1-744a59e9f194.png)

Are you able to attempt to reset with the breached password `ilovedogs` to confirm you can see such an error message?

**Comment by gward** [comment]
Yes, I am using a new, strong, randomly generated password. Sometimes I use Firefox builtin password generator, sometimes I use the generator in keepassxc, and sometimes I use a command-line tool called `makepasswd`. Either way, they're long and random and full of a delightful mix of lowercase, uppercase, and numbers. I've avoided punctuation _just in case_ that was causing problems.

However, I have NOT used a different password each time. I switched to a shorter password (12 chars instead of 20) for testing on my phone, but I used the same random password for all tests on my phone.

I can certainly try again with a unique password each time.

**Comment by gward** [comment]
Oh yeah, I also confirmed that the "known weak password" feature works for me. I tried with "rush2112" and said I need more words. Tried with "ilovedogs" and I got the same result as you did.

**Comment by gward** [comment]
Oh, another guilty admission: I have used the same reset token many times. You seem to have some rate limiting on password reset requests (good!!), which means testing with a new token each time would be annoying. I can do that too, if it helps.

**Comment by gward** [comment]
OK just tried it with a new reset token and a new random password: same error. Still with Firefox 87.0 on Ubuntu 20.04.2.

**Comment by di** [comment]
OK, can you try again? I noticed that the email address on your account was not marked as verified or primary, which likely happened when you went through the account recovery process.

**Comment by gward** [comment]
Ahhhhh, thank you! I just tried it on Chrome on a Mac and it suddenly worked. I'm guessing it's because you tweaked my verification flag, rather than because of the change of browser and platform. ;-)

Thank you!!

(And, also, thank you for your work on PyPI. It's a fantastic piece of infrastructure and you are making the world a better place.)

**Comment by gward** [comment]
Wait, I probably should not close this. My problem is solved, but the error reporting could definitely be better. ;-)

**Comment by di** [comment]
Yep, I'd consider this a bug. Will update the title accordingly.
