### ISSUE TITLE
django-horizontal-list-filter 0.1.2 don't change filter position

### ISSUE THREAD

**Issue by LZORZA** [pypa/warehouse#9338]
Instaled package via PIP on Linux CentOS 7, Django 3.1.7 and Python 3.6.8,

Included in 

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_horizontal_list_filter',
    'django.contrib.staticfiles',
    'cat.apps.CatConfig',
    'tomb.apps.TombConfig',
]
Console show "GET /static/django-horizontal-list-filter/js/django-horizontal-list-filter.js HTTP/1.1" 304 0,
but filter continue in the right side of the list.

![Horizontal-list-filter](https://user-images.githubusercontent.com/19285792/113475378-a49ad280-944b-11eb-9062-342b1f88e5ae.jpg)

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
