### ISSUE TITLE
django-admin-relation-links 0.2.5 

### ISSUE THREAD

**Issue by DBonbon** [pypa/warehouse#9360]
What problem does this feature will solve?

How can one use this feature with import-export feature. 
I assume the existence of a certain DB already in place as links are needed. 

Can it work also with import-export CSV files? where the links are established after the import?
If yes, how one should apply
class AdminMember(ImportExportModelAdmin)
with class GroupAdmin(AdminChangeLinksMixin, admin.ModelAdmin)

Or should the import be done via a script of separated tables? 
or else, how it differs from linking say members and groups in manytomany relationship via dedicated script that adds a linking model, say membership and via get_or_create command?

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
