### ISSUE TITLE
Unable to upload bdist_wheel with a none platform tag and an sdist

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [pypa/warehouse#9361]
**Describe the bug**
While attempting to upload a bdist_wheel with a none platform tag (IE: PyGithub-1.54.0-py3-none-any.whl) and an sdist (PyGithub-1.54.0.tar.gz), the upload returns 400 Bad Request: Only one sdist may be uploaded per release.

**Expected behavior**
Both the bdist_wheel and the sdist are successfully uploaded.

**My Platform**
Using GitHub Actions with https://github.com/PyGithub/PyGithub/blob/master/.github/workflows/pypi-release.yml to upload using twine.

**Comment by s-t-e-v-e-n-k** [comment]
```
Uploading PyGithub-1.54.0-py3-none-any.whl
923
924
  0%|          | 0.00/289k [00:00<?, ?B/s]
925
  3%|▎         | 8.00k/289k [00:00<00:03, 80.3kB/s]
926
100%|██████████| 289k/289k [00:01<00:00, 240kB/s]  
927
Uploading PyGithub-1.54.0.tar.gz
928
929
  0%|          | 0.00/158k [00:00<?, ?B/s]
930
100%|██████████| 158k/158k [00:00<00:00, 1.14MB/s]
931
NOTE: Try --verbose to see response content.
932
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
933
Only one sdist may be uploaded per release.
934
```

**Comment by di** [comment]
The versions `1.54` and `1.54.0` are considered equivalent. Your wheel is here: https://pypi.org/project/PyGithub/1.54/

See https://www.python.org/dev/peps/pep-0440/#version-matching for more details.
