### ISSUE TITLE
SDRplay support for PyPI

### ISSUE THREAD

**Issue by G4ABQ** [pypa/warehouse#9395]
We want to support developers who want their SDR receiver applications to run on SDRplay hardware. This is for when they need better performance than is possible with an RTL-SDR dongle and to address HF frequencies and below.  Having Python control of a powerful communications receiver has many possibilities for intelligent (content specific) radio signal selection/tuning.  

The solution I'd like, is to work with Roger to create a Python wrapper working for the RSP1A SDR.

Links to the RSP1A details can be found here: [https://www.sdrplay.com/products/](url)

Please contact jon.hudson@sdrplay.com to explore how we can help make this happen.
 
Best regards, Jon, SDRplay in the UK

**Comment by yeraydiazdiaz** [comment]
Hello @G4ABQ, this issue tracker is for issues related to the code that powers pypi.org so I'm closing this issue.

Sounds like you'd like to start a Python project for your particular use case, but this is is not the right forum for that. I would start by contacting users of your products that may have experience in Python. Good luck!
