### ISSUE TITLE
Implement a report URI for the Content Security Policy

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#94]
In #93 a Content Security Policy was added, however reports are not being sent anywhere. Ideally they would go to something like Sentry (perhaps even sentry itself?).

**Comment by mattrobenolt** [comment]
Oh hey, we can beta test this now in Sentry for those that are interested. @dstufft, gimme a holla.

![](http://cdn.meme.am/instances/50194253.jpg)
