### ISSUE TITLE
Virustotal.com engine detects pypi.org and files.pythonhosted.org as hosting possibly malicious content.

### ISSUE THREAD

**Issue by jonathandl2** [pypa/warehouse#9401]
**Describe the proposed check**
Periodically check virustotal.com to see if files.pythonhosted.org, pypi.org and pypi.python.org are detected by any vendors.

**What kind of attack does this check detect?**
Check to see if domain names are blacklisted, which may indicate that somebody uploaded an infected file somewhere.

**Additional context**
Currently CRDF.fr detects files.pythonhosted.org as "malicious";
CLEAN MX detects pypi.org as "malicious"; and
Quttera detects pypi.python.org as "suspicious."
If you are confident these are false positives then please report them to their respective vendors.

**Comment by di** [comment]
Hi, thanks for the report. Can you explain how this is affecting you as a PyPI user?

**Comment by jonathandl2** [comment]
Hi.  I personally am not a PYPI user; however, I work for a company that 
uses it.

And although the VirusTotal detections don't affect me personally, I 
think it is very desirable to find the cause of any detections and 
report false-positives to the respective vendors (CRDF and Clean-MX).

Thank you for your help!

**Comment by jonathandl2** [comment]
I have gotten Quttera to remove pypi.python.org from their blacklist.

**Comment by di** [comment]
I'm also not seeing CDRF reporting a false positive anymore and I can't even load the CLEAN MX website, so I'm going to close this, but thank for the report.

**Comment by jonathandl2** [comment]
Good evening,

Looks like, according to VirusTotal, CRDF still detects 
files.pythonhosted.org as "Malicious."

CleanMX is no longer blacklisting you.

Thanks,
Jonathan

**Comment by di** [comment]
Here's what I'm seeing at https://www.virustotal.com/gui/domain/files.pythonhosted.org/detection:

![image](https://user-images.githubusercontent.com/294415/115488923-ec2da680-a220-11eb-9786-41ca7d250e52.png)

Are you seeing something different?

**Comment by jonathandl2** [comment]
I sent an email to ***@***.***" asking them what specific file is 
detected, and they didn't reply (it's even later at night French time 
than it is here) but it looks like it got reclassified in the last 2 hours.
