### ISSUE TITLE
Package not showing up in pypi search.

### ISSUE THREAD

**Issue by Atharva-Phatak** [pypa/warehouse#9409]
Hi sorry, I could not find anyone to contact hence I am opening this issue. I released a package name "torchflare" just about 3 hours ago. I can see the package listed when I log into my account and also accessible when I go the directlink: <https://pypi.org/project/torchflare/> but when I search it on pypi website I cannot seem to find it. 

Please help me

**Comment by ewjoachim** [comment]
![Screenshot from 2021-04-22 09-48-11](https://user-images.githubusercontent.com/1457576/115676442-e387be00-a34f-11eb-9043-539c3fb4c4f3.png)
Looks like it works now. Maybe there was just a backlog of re-indexations. Can you confirm it works for you now ?

**Comment by Atharva-Phatak** [comment]
It works now thank you ! I am closing this issue now.
