### ISSUE TITLE
Acquiring deprecated package

### ISSUE THREAD

**Issue by YoSTEALTH** [pypa/warehouse#9412]
Hello,

I would like to acquire deprecated package account https://pypi.org/project/importer/ for a project I created. I did talk to the maintainer (few years ago)

``` text
I am not sure I have the login credentials for that. If they are tied to my *** 
email address then I'm out luck since I no longer have access to it.

I've hit the forgot password button and we'll see. :)
```

Could this be done?

Thank you

**Comment by yeraydiazdiaz** [comment]
Hi @YoSTEALTH, please open a PEP 541 requests at https://github.com/pypa/pypi-support/issues/new/choose

**Comment by YoSTEALTH** [comment]
Thanks @yeraydiazdiaz
