### ISSUE TITLE
Delete account fails with 503

### ISSUE THREAD

**Issue by ulope** [pypa/warehouse#9413]
**Describe the bug**
Trying to delete a no longer necessary "machine" account (`raiden_pypi_automated`) results in a 503 "Sorry, something went wrong" response.

**Expected behavior**
The account to be deleted.

**To Reproduce**
Trying to delete account via Account Settings

**My Platform**
Safari on macOS

**Additional context**
The account no longer has any projects associated. But it was removed from those projects only shortly before trying to delete it.

Another user had the same symptoms in #4728.

**Comment by di** [comment]
It looks like our backend workers may have just been temporarily overwhelmed. Could you retry?

**Comment by ulope** [comment]
Indeed, now it worked.
Thanks!
