### ISSUE TITLE
Usability review

### ISSUE THREAD

**Issue by techtonik** [pypa/warehouse#943]
Where to hold conversation about usability issues with the current design?

**Comment by nlhkabu** [comment]
We have a label in the issue tracker specifically for usability.  If you think you see a usability problem, please create an issue and tag it under this category.

We are also planning on running some usability tests prior to launch.  Please see https://github.com/pypa/warehouse/issues/717 for more information.

**Comment by techtonik** [comment]
@nlhkabu awesome! =)
