### ISSUE TITLE
Move package navigation to the left

### ISSUE THREAD

**Issue by techtonik** [pypa/warehouse#944]
This is the current package page on the notebook with a touchpad.

![image](https://cloud.githubusercontent.com/assets/515889/12668587/25fd6bdc-c669-11e5-909c-ad1bd45a6fe6.png)

As you see, I have to use scrollbar on the right to get to the package content. Then I have to go all the way across the screen to get to different information about package, then I have to go back to scrollbar again, because tab content is unlikely to fit page again.

**Comment by nlhkabu** [comment]
Thanks for your feedback @techtonik - I have opened #1988 to address this and other similar feedback.

**Comment by techtonik** [comment]
#1988 is a general issue. I am afraid that this specific "Move package navigation to the left" wish will be lost.

See https://docs.ubuntu.com/maas/2.1/en/installconfig-checklist where it is implemented.
