### ISSUE TITLE
Landing design vs Functional design

### ISSUE THREAD

**Issue by techtonik** [pypa/warehouse#945]
I don't have other words for definition of that style except like `Landing design`. That's kind of design is like a picture that you may see from 10m away in a caffee, read the name and got impressed.

![image](https://cloud.githubusercontent.com/assets/515889/12668678/26d27b5a-c66a-11e5-9c96-f8cb0bd08973.png)

"OMG! This guy uses python, enters queries and works with **cryptography 1.2.1** and installs it with `pip install cryptography`". On the second visit the information here is not useful. Take GitHub for example - it won from everybody, and yet for years until last week there were no formatting buttons on its text entry forms.

The `Functional design` means that it is tied to the most frequent functions that users do on the site. GitHub interface is scary the first time you use it, but not annoying in the long run. PyPI is not a one time site, and excessive headings that you need to scroll up are annoying.

Title page:

![image](https://cloud.githubusercontent.com/assets/515889/12668788/2bcd7168-c66b-11e5-9309-9c3547fad546.png)

On this page I am not interested in the slogan at all - it is a waste of space. I am also less interested in reading 6-digit numbers that steal my vertical space for more useful information, and that useful information are latest things that people posted on PyPI.

In functional design you may have a small search form at any place of the title page and any size, even in top right. Just make sure that cursor is blinking there and it is ready for entering text without additional scrolling and clicking. Moving hands from mouse to keyboard and back is an awful user experience.

**Comment by nlhkabu** [comment]
Thanks for your feedback @techtonik - I have opened #1988 to address this and other similar feedback.
