### ISSUE TITLE
Bad overflow in HTML.

### ISSUE THREAD

**Issue by Carreau** [pypa/warehouse#947]
example in https://warehouse.python.org/project/ipython/:

![screen shot 2016-01-29 at 11 34 23](https://cloud.githubusercontent.com/assets/335567/12686012/6aa267a2-c67c-11e5-91c8-8147921c611f.png)

**Comment by dstufft** [comment]
Hey! Thinks for the issue, we do have #855 already tacking this so I'm going to close this as a duplicate.

**Comment by Carreau** [comment]
Oops, sorry, I missed that while searching. My bad.
