### ISSUE TITLE
Add the timezone in the release date alt text

### ISSUE THREAD

**Issue by thedrow** [pypa/warehouse#9476]
**What's the problem this feature will solve?**

It's hard to guess which timezone the timestamps use and while assuming the user assumes it is UTC is reasonable, it's not explicit.

![image](https://user-images.githubusercontent.com/48936/117298773-6a748480-ae80-11eb-891a-1d39bbd70c50.png)

**Describe the solution you'd like**

Just add the timezone to the timestamp.

**Additional context**

None.

**Comment by vivek-gite** [comment]
I'm a beginner in this issue can you please suggest me how to get started. 
Thanks!!

**Comment by Shams66789** [comment]
Is this issue still open? If not, then I would like to work on it.

**Comment by thedrow** [comment]
@Shams66789 Feel free to join the effort in #9494.
