### ISSUE TITLE
Wasted space

### ISSUE THREAD

**Issue by aklaver** [pypa/warehouse#948]
Checked out the new site and while it looks nice, there is a lot of wasted space.  As an example compare:

https://pypi.python.org/pypi?%3Aaction=search&term=xls&submit=search
to:
https://warehouse.python.org/search/?q=xls

I get a lot more information per screen in the first view versus the second .  PyPi is a search engine it should minimize glitz and maximize content.

**Comment by nlhkabu** [comment]
We already have a number of other issues providing similar feedback - which will be looked into in due course.  I'm going to close this issue as a duplicate.  thanks for your feedback.

**Comment by aklaver** [comment]
In that case it would be nice if the lead issue number was identified and this issue and other similar issues where pointed to it when closed, in order that those creating the issues could follow along in the conversation.

**Comment by nlhkabu** [comment]
Please see https://github.com/pypa/warehouse/issues/793 and https://github.com/pypa/warehouse/issues/945

**Comment by sigmavirus24** [comment]
@aklaver GitHub has some great functionality built-in to search existing issues. Searching for [header](https://github.com/pypa/warehouse/issues?utf8=✓&q=is:issue+header) or [space](https://github.com/pypa/warehouse/issues?utf8=✓&q=is:issue+space) help you find exactly the two issues @nlhkabu so kindly linked for you.

**Comment by aklaver** [comment]
True, but that assumes you are talking the same problem as someone else. For instance I was concerned with the content returned from a search and not the header, so I would not have thought to search on header. More to the point, even if I had used those search terms there is no indication that the two issues are considered the same issue by the project. Using the duplicate tag(label) and Duplicate of issue #123 syntax (http://stackoverflow.com/questions/9417146/merge-differents-issues-on-github)  creates a bread crumb trail for subsequent users to follow. It also creates a primary issue where the concerns can be consolidated. My comments are made in the interest of making things clearer as Warehouse gains wider interest and accumulates more issues. Though in the final analysis how you manage this is up to you.

**Comment by nlhkabu** [comment]
Refs #1988
