### ISSUE TITLE
Can't install in 32-bit environment

### ISSUE THREAD

**Issue by ccjs1234** [pypa/warehouse#9507]
**Describe the bug**

Please understand that I used a translator.
Attempting to install PySide6 in a 32-bit environment fails.
It worked fine in a 64-bit environment.
This occurred when installing in a virtual environment that used anaconda and converted it to 32-bit.
I must use 32-bit, and I really hope this is resolved.

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by yeraydiazdiaz** [comment]
I believe you're looking for https://wiki.qt.io/Qt_for_Python/Reporting_Bugs
