### ISSUE TITLE
Failed to download geckodriver archive:

### ISSUE THREAD

**Issue by sachinyadav342** [pypa/warehouse#9533]
ERROR :
raise RuntimeError(f'Failed to download geckodriver archive: {url}')
RuntimeError: Failed to download geckodriver archive: https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-win32.tar.gz

I am using using windows 10

Step1 : installed geckodriver
command : pip install geckodriver-autoinstaller

Step2: Executed below program

from selenium import webdriver
import geckodriver_autoinstaller

geckodriver_autoinstaller.install()
driver = webdriver.Firefox()
driver.get("http://www.python.org")
assert "Python" in driver.title

Step3: when i opend below Link as mentioned in above error section web page opens and say Not found.
Link : https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-win32.tar.gz

Step4: When i went to : https://github.com/mozilla/geckodriver/releases/v0.29.1/

i saw there for windows gekodriver is in .zip format (geckodriver-v0.29.1-win32.zip) and from error i came to know that it is downloading .tar.gz file.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
