### ISSUE TITLE
[Feature Request] UI for adding maintainers

### ISSUE THREAD

**Issue by scopatz** [pypa/warehouse#956]
The idea here is simple, but I have no clue how hard it would be to implement. That said, it would be great if warehouse had a user interface for current maintainers of a project to add other maintainers.

**Comment by shiroyuki** [comment]
@dstufft Need help?

**Comment by dstufft** [comment]
Contributions are always welcome :)

**Comment by nlhkabu** [comment]
As this is a new feature, I'm going to move this out of the 'shutdown' milestone and label it with post launch high priority.

**Comment by dstufft** [comment]
This isn't a new feature, it exists on PyPI today, people can add/remove Owners and Maintainers and it's needed before we shut down legacy or else people won't be able to manage the permissions of their projects.

**Comment by brainwane** [comment]
In our [meeting today](https://wiki.python.org/psf/PackagingWG/2017-12-19-Warehouse) we decided this belongs in [the first milestone, the MVP for package maintainers](https://github.com/pypa/warehouse/milestone/8).
