### ISSUE TITLE
fraudulent pisi package, attempt to hijack my project

### ISSUE THREAD

**Issue by examachine** [pypa/warehouse#9573]
Hi there,

I'm the original author and maintainer of the pisi package manager project. Somebody created a pisi package with a fake email address (the email name is a joke in Turkish) and a high version number (999.999), please remove this fraudulent package because we will upload the releases here.

Best Wishes,

Eray

On behalf of PISI and pisi linux projects.

**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for the codebase behind PyPI. 

Please file a PEP 541 request here instead: https://github.com/pypa/pypi-support/issues/new/choose

**Comment by examachine** [comment]
thank you!

**Comment by examachine** [comment]
FYI: 
https://github.com/pypa/pypi-support/issues/1107
