### ISSUE TITLE
Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#961]
I am experiencing the following error when I try to add approximately 80 lines of css to `/_release-description.scss`:

![screenshot from 2016-02-07 09-13-17](https://cloud.githubusercontent.com/assets/3323703/12873834/a7ae1ae8-cdbf-11e5-98c5-83440897936c.png)

I haven't the foggiest idea of how to debug it.  It is perhaps related to our CSS maps?

**Comment by dstufft** [comment]
I think you need to manually delete the dist folder and make sure you're using the latest master, so:

```console
$ rm -rf warehouse/static/dist
```

**Comment by nlhkabu** [comment]
Thanks @dstufft, that's fixed it :P
