### ISSUE TITLE
Respons time of url like: https://pypi.org/pypi/<package>/json

### ISSUE THREAD

**Issue by pconesa** [pypa/warehouse#9620]
We have a code that queries this kind of pypi URLs:
https://pypi.org/pypi/<package>/json

Through the browser seems responsive. But our software has recently experienced a huge slowdown.

We haven't changed the code for a long time thus my first guess is if is there any "delay" you are aware of in the response time of those kind of URLS?

**Comment by di** [comment]
I don't believe anything has changed recently that would explain this. Can you give us an example of a request with a "slow" request? What response times are you experiencing? Any more details about how you're using the API would be helpful.

**Comment by pconesa** [comment]
thanks @di , If not in your side I'll review our code. If I find a slow request, I'll post it here and reopen the issue. Thanks for the quick response.

**Comment by ndanielsen** [comment]
I'm having a similar issue that started roughly 24 hours ago. 

```
Retrying HTTP request in 0.5 seconds.

  ConnectionError

  HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/{package}/2.1.0/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fce3dd65340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

  at /opt/conda/lib/python3.8/site-packages/requests/adapters.py:516 in send
      512│             if isinstance(e.reason, _SSLError):
      513│                 # This branch is for urllib3 v1.22 and later.
      514│                 raise SSLError(e, request=request)
      515│ 
    → 516│             raise ConnectionError(e, request=request)
      517│ 
      518│         except ClosedPoolError as e:
      519│             raise ConnectionError(e, request=request)
      520│ 


  ConnectionError

  HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/{package}/1.3.0/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fce3dcdad30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

  at /opt/conda/lib/python3.8/site-packages/requests/adapters.py:516 in send
      512│             if isinstance(e.reason, _SSLError):
      513│                 # This branch is for urllib3 v1.22 and later.
      514│                 raise SSLError(e, request=request)
      515│ 
    → 516│             raise ConnectionError(e, request=request)
      517│ 
      518│         except ClosedPoolError as e:
      519│             raise ConnectionError(e, request=request)
      520│ 
```

**Comment by di** [comment]
@ndanielsen, that looks like a DNS issue, could you fill out a [Network Access Issue](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=network&template=access-issues.yml) to provide some more information? (Please make sure to run the commands on the same machine that is experiencing the issues).

**Comment by pconesa** [comment]
In mi case, i was connected to a poor performance WiFi access point. I
switched to the main router and went as before.
