### ISSUE TITLE
PyPI MT103 13C

### ISSUE THREAD

**Issue by MR-SASO** [pypa/warehouse#9643]
The author asking for help
 "_it’s unclear as to whether this section is permitted to repeat (meaning it should be parsed as a list) or if it’s one value only._"

Yes, 13C is a repetitive Optional field , expect zero , one or more occurrence.

13C Time Indication
One or several time indication(s) related to the processing of the payment instruction.
Format
Option C	/8c/4!n1!x4!n	(Code)(Time indication)(Sign)(Time offset)

By the way MT103 will die soon and will be replaced with ISO 20022 pacs008

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
