### ISSUE TITLE
Error encountered when attempting to convert postman collection to yaml

### ISSUE THREAD

**Issue by jethfo** [pypa/warehouse#9652]
**Describe the bug**
openman convert repairq-api.postman_collection.json repairq-api.yaml
Traceback (most recent call last):
  File “/usr/local/bin/openman”, line 8, in <module>
    sys.exit(cli())
  File “/usr/local/lib/python3.9/site-packages/click/core.py”, line 1137, in __call__
    return self.main(*args, **kwargs)
  File “/usr/local/lib/python3.9/site-packages/click/core.py”, line 1062, in main
    rv = self.invoke(ctx)
  File “/usr/local/lib/python3.9/site-packages/click/core.py”, line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File “/usr/local/lib/python3.9/site-packages/click/core.py”, line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File “/usr/local/lib/python3.9/site-packages/click/core.py”, line 763, in invoke
    return __callback(*args, **kwargs)
  File “/usr/local/lib/python3.9/site-packages/openman/cli.py”, line 36, in convert
    apispec = spec.get_spec(ignorespec=ignore_file)
  File “/usr/local/lib/python3.9/site-packages/openman/spec/spec.py”, line 52, in get_spec
    for requestitem in self.postman_collection.get_requestitems():
  File “/usr/local/lib/python3.9/site-packages/openman/parser/collection.py”, line 54, in get_requestitems
    items.extend(folder.get_requestitems())
  File “/usr/local/lib/python3.9/site-packages/openman/parser/folder.py”, line 40, in get_requestitems
    request_items.append(RequestItem(item))
  File “/usr/local/lib/python3.9/site-packages/openman/parser/requestitem.py”, line 11, in __init__
    raise RequestItemParserException(‘Not a valid request’)
openman.errors.RequestItemParserException: Not a valid request

**Expected behavior**
Expected the file to be converted from postman collection json to yaml

**To Reproduce**
Run the convert tool on a collection file downloaded from postman.

**My Platform**
macOS Big Sur, python3.9, postman collection version v2.1.0

**Additional context**
Thank you for any assistance you can provide.  I'm happy to provide additional details as would be helpful.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
