### ISSUE TITLE
Add Traditional Chinese Translation

### ISSUE THREAD

**Issue by meowmeowmeowcat** [pypa/warehouse#9667]
The Traditional Chinese Translation is at 100% on Weblate so I think it should be added to the localization footer.

**Comment by ewjoachim** [comment]
For reference, [here's the documentation](https://warehouse.pypa.io/translations.html?#adding-a-newly-completed-translation). Do you want to take care of the PR adding the language? 

The current Weblate PR is https://github.com/pypa/warehouse/pull/9502 and it's already 6000 lines, so you may need someone to merge this first.

**Comment by meowmeowmeowcat** [comment]
Thank you !
But who can merge #9502?

**Comment by meowmeowmeowcat** [comment]
Thank you !
But who can merge #9502 ?

**Comment by ewjoachim** [comment]
@di / @ewdurbin :)

**Comment by di** [comment]
Merged!

**Comment by meowmeowmeowcat** [comment]
I've submitted PR #9669 !

Please help me to merge it

Thank you !
