### ISSUE TITLE
IRC presence (Freenode?)

### ISSUE THREAD

**Issue by mgedmin** [pypa/warehouse#9677]
I've noticed that https://github.com/pypa/warehouse/blob/main/docs/development/index.rst and several other pages (git grep -l freenode|wc -l shows 71 files, most of them in warehouse/locale/) still refer to #pypa and #pypa-dev channels on Freenode.  Given [recent events](https://www.devever.net/~hl/freenode_suicide) I'd like to ask for clarification about this: are you still on Freenode, or have you moved the channels to Libera.Chat or OFTC or some other place?

**Comment by di** [comment]
Yes, https://web.libera.chat/#pypa and https://web.libera.chat/#pypa-dev also exist, as well as https://discord.gg/pypa.

We should update the docs accordingly.
