### ISSUE TITLE
Define canonical URLs on package detail pages

### ISSUE THREAD

**Issue by ncoghlan** [pypa/warehouse#968]
One issue with the current PyPI is search engines delivering links to the details page for a specific old version of a package, rather than the latest version.

I was looking into the use of canonical URLs for the CPython documentation, and realised they may be an appropriate solution for the "search engines pointing to old versions" problem on PyPI as well: http://docs.readthedocs.org/en/latest/canonical.html

**Comment by miohtama** [comment]
This is a pretty interesting though! Might apply to some other problems too - I am thinking Sphinx documentation.
