### ISSUE TITLE
pdfservices-sdk 1.0.0

### ISSUE THREAD

**Issue by terryemon** [pypa/warehouse#9686]
I have installed pdfservices-sdk 1.0.0 for python sucessfully
When i tried to call extract_txt_from_pdf.py
i got the following error. Need help , what is this error? and how to fix?

Traceback (most recent call last):
  File "extract_txt_from_pdf.py", line 35, in <module>
    from adobe.pdfservices.operation.auth.credentials import Credentials
ModuleNotFoundError: No module named 'adobe'

**Comment by ewjoachim** [comment]
Hi, this issue tracker is for issues with the codebase behind pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
