### ISSUE TITLE
Add a reminder to thank contributors

### ISSUE THREAD

**Issue by willingc** [pypa/warehouse#969]
Hi Warehouse team,

It's been a couple of months since I pulled up the site. It looks awesome! Thank you @nlhkabu @dstufft and all the contributors. I can't wait for official launch :cake: :tada: :bouquet: 

Feel free to close this issue or add to the launch milestone (just in case you need a reminder of how thankful others are for your work).

Carol

**Comment by nlhkabu** [comment]
Thanks @willingc !! A big shout out also to @di who has been making some great contributions recently.
