### ISSUE TITLE
Update communication channels

### ISSUE THREAD

**Issue by ewjoachim** [pypa/warehouse#9695]
Following #9690 and especially https://github.com/pypa/warehouse/pull/9690#issuecomment-863819204, we could update the communication channels advertised throughout the project:

- Wherever `distutils-sig` is mentionned, a reference to the [Discourse](https://discuss.python.org/c/packaging/14) would be more appropriate, so it should be replaced
- Wherever IRC is mentionned, adding a reference to the [PyPA Discord](https://discord.gg/pypa) is advised (but IRC should be there too, both are live)

**Comment by meowmeowmeowcat** [comment]
Will be fixed in #9698
