### ISSUE TITLE
Scapy Traffic Generator is not available for download

### ISSUE THREAD

**Issue by andressavergutz** [pypa/warehouse#9696]
**Describe the bug**
ScapyTrafficGenerator is not installing by Pip. 

**Expected behavior**
By using `pip3 install ScapyTrafficGenerator` should install the library. However, it is not working. I get a request exception HTTP error, i.e., the current URL is not working. 

**To Reproduce**
If you don't have the library installed, try to run `pip3 install ScapyTrafficGenerator` in your terminal.

**My Platform**
Ubuntu Server 18.04.

**Additional context**
See the image attached.
![WhatsApp Image 2021-06-18 at 14 42 06](https://user-images.githubusercontent.com/8582505/122599216-5f4a7200-d044-11eb-93cd-1ef87c8032bc.jpeg)

**Comment by di** [comment]
This project was removed by it's maintainer on 2021-06-09 and no longer exists. Sorry about that!
