### ISSUE TITLE
Replace factory.fuzzy calss in favor of factory.Faker

### ISSUE THREAD

**Issue by berinhard** [pypa/warehouse#9707]
This issue was created after [@ewjoachim comment on replacing `factory.fuzzy` by `fatory.Faker`](https://github.com/pypa/warehouse/pull/9656#discussion_r650127008). The reason is that the `fuzzy` method is deprecated in favor of faker.

So, the goal of this issue is to update all factories class under `tests/common/db/` to replace the methods as commented above. Since this will only touch test code, the acceptance criteria for a possible PR would be its CI status.

---

**Good First Issue**: This issue is good for first time contributors. If you've already contributed to Warehouse, work on [another issue without this label](https://github.com/pypa/warehouse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22good+first+issue%22) instead. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see our [Getting Started Guide](https://warehouse.pypa.io/development/getting-started/).

If you are working on this issue and have questions, feel free to ask them here, in the [`#pypa-dev` chat channel on Libera](https://web.libera.chat/#pypa-dev), or on the [distutils-sig.python.org mailing list](https://mail.python.org/mailman3/lists/distutils-sig.python.org/).

**Screenshot Required**: *If your pull request makes a visual change*, include a screenshot of your update. This helps our team give you feedback faster.

**Comment by berinhard** [comment]
@ewdurbin or @ewjoachim can you flag this as a Good first issue? I don't have the permission to do so. Thanks =)

**Comment by meowmeowmeowcat** [comment]
Hi, I would like to work on this issue.

And I have a question :

Should I change `factory.fuzzy.FuzzyNaiveDateTime` to  `factory.Faker("date")` [here](https://github.com/pypa/warehouse/blob/21a6432ad9e6fac1ba0cac3bd4797a1ad4180e93/tests/common/db/accounts.py#L37)?

**Comment by prius** [comment]
Here is a PR with an attempt to address the issue #9980
