### ISSUE TITLE
More spam on Pypi.org

### ISSUE THREAD

**Issue by ricotorre** [pypa/warehouse#9717]
I want to report spam projects created on pypi.org 
These projects contains links to survey scam sites. Someone check and remove them. Thanks.

Here are they..

https://pypi.org/project/HACK-INSTAGRAM-ACCOUNT-2021-HACK-INSTA-USING-OUR-SITE-IN-5-MINUTES/
https://pypi.org/project/Garena-Free-Fire-Hack-No-Survery-Diamonds-Generator-No-Verify/
https://pypi.org/project/GARENA-FREE-FIRE-DIAMOND-GENERATOR-FREE-FIRE-HACK/
https://pypi.org/project/free-onlyfans-hack-premium-subscription-accounts-new/
https://pypi.org/project/onlyfans-premium-free-accounts-subscription-hack-2021-working/
https://pypi.org/project/Hack-Facebook-Account-Hack-Fb-Online-2021-Using-Our-Site/
https://pypi.org/project/HACK-INSTAGRAM-ACCOUNT-2021-HACK-INSTA-In-6-Minutes-2021/
https://pypi.org/project/HACK-FACEBOOK-ACCOUNT-HACK-FB-ONLINE-1-MINUTES-USING-OUR-SITE/
https://pypi.org/project/Among-Us-Hack-Mod-Menu-2021-No-Survey/
https://pypi.org/project/Cash-App-Money-Generator-Working-2021-free-hack/
https://pypi.org/project/free-paypal-money-generator-hack-adder-no-human-verification-2021-hack/9.0.8/
https://pypi.org/project/Onlyfans-Hack-2021-Free-Premium-Account-No-Survey/
https://pypi.org/project/onlyfans-premium-free-accounts-subscription-hack-2021-new/2.0.9/
https://pypi.org/project/new-onlyfans-premium-free-accounts-subscription-hack-2021-hack/
https://pypi.org/project/Pokemon-Go-Hack-Free-Spoofing-Joystick-No-Survey-2021/
https://pypi.org/project/Clash-of-clans-hack-cheats-generator-gems/
https://pypi.org/project/onlyfans-premium-free-accounts-subscription-hack-2021-n/
https://pypi.org/project/Dragon-city-hack-gems-2021/
https://pypi.org/project/onlyfans-premium-free-accounts-subscription-hack-2021-working/2.0.8/
https://pypi.org/project/free-paypal-money-generator-hack-adder-no-human-verification/
https://pypi.org/project/onlyfans-premium-free-accounts-subscription-hack-2021-best/
https://pypi.org/project/onlyfans-premium-free-accounts-subscription-hack-2021-best/2.0.8/
https://pypi.org/project/onlyfans-premium-free-accounts-subscription-hack-2021-secure/
https://pypi.org/project/onlyfans-premium-free-accounts-subscription-hack-2021-n/2.0.8/
https://pypi.org/project/free-cash-app-money-legit-gift-card-hack-generator-new/
https://pypi.org/project/onlyfans-premium-free-accounts-subscription-hack-2021-secure/2.0.8/
https://pypi.org/project/new-onlyfans-premium-free-accounts-subscription-hack-2021-work/

**Comment by di** [comment]
Thanks, these have been removed. In the future you can email `admin@pypi.org` instead.
