### ISSUE TITLE
Scapy keeps throwing error for Circular Import

### ISSUE THREAD

**Issue by utkarsh0902311047** [pypa/warehouse#9723]
hi,
I am trying to run scapy on windows 10. I installed it using pip install scapy.
But it keeps giving me error
![scapy_error2](https://user-images.githubusercontent.com/78134056/123501372-f5028480-d676-11eb-83c5-5e5897110a7f.png)
Any help is appreciated

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
