### ISSUE TITLE
Reporting spam in Pypi

### ISSUE THREAD

**Issue by borkregina** [pypa/warehouse#9725]
Hey, I want to report some spam projects created on Pypi.org.  These are survey scam.

https://pypi.org/project/Fake-Cash-App-Generator-legit-2021/
https://pypi.org/project/WORKING-Cash-App-Money-Generator-free-2021/
https://pypi.org/project/WORKING-Cash-App-Money-Generator-free-2021-NEW/
https://pypi.org/project/NEW-Fake-Cash-App-Generator-Wokring-2021/
https://pypi.org/project/Fake-Cash-App-Generator-Wokring-2021/
https://pypi.org/project/FREE-V-BUCKS-FORTNITE-V-BUCKS-GENERATOR-WORKING/
https://pypi.org/project/FREE-V-BUCKS-FORTNITE-V-BUCKS-GENERATOR-NEW/0.2.2/
https://pypi.org/project/How-to-Earn-FIFA-21-Coins-points-generator/
https://pypi.org/project/HACK-INSTAGRAM-ACCOUNT-2021-HACK-INSTA-In-6-Minutes-2021/
https://pypi.org/project/royal-match-game-free-coins-lives-cheats-hack/
https://pypi.org/project/rise-of-kingdoms-cheats-hack-mod-apk/
https://pypi.org/project/episode-cheats-free-gems-unlimited-hack-generator-mod-apk/
https://pypi.org/project/Free-Fortnite-account-generator-hack-2021/
https://pypi.org/project/aprikaointb/
https://pypi.org/project/Cash-App-Money-Generator-Working-2021/
https://pypi.org/user/Coin-Master-cheats-hack-free-spins-generator-2021/
https://pypi.org/project/Cash-App-Free-Money-Code-without-human-verification-new/2.2.8/
https://pypi.org/user/Chidnfa14/
https://pypi.org/user/Cash-App-Free-Money-Code-without-verification/

**Comment by Coronon** [comment]
I think one should report them in this repo:
https://github.com/pypa/pypi-support

**Comment by di** [comment]
Thanks, these have been removed. In the future you can send these to admin@pypi.org instead.
