### ISSUE TITLE
Bug with django-verify-email

### ISSUE THREAD

**Issue by Idris01** [pypa/warehouse#9728]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

I write to notify on the bug I've found on the django-verify-email app. 
as shown in the app disription, when the app is imported in the view as follows 
<pre>
from verify_email.email_handler import send_verification_email
</pre>

and used as follows 

<pre>
inactive_user=send_verification_email(request, form) 
</pre>

The inactive_user is not surposed to be type bool, but it is returning type bool

Thank you

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
