### ISSUE TITLE
can't upload a package with the name 'warehouse'

### ISSUE THREAD

**Issue by dmfigol** [pypa/warehouse#9732]
I am sorry for using a bug template, but I haven't found a better place/way to ask this question

**Describe the bug**
I am trying to upload a package with the name **warehouse** to PyPi and it is failing:
```
-> %   poetry publish
Publishing warehouse (0.1.0) to PyPi
 - Uploading warehouse-0.1.0-py3-none-any.whl 100%

UploadError
HTTP Error 403: The user 'dmfigol' isn't allowed to upload to project 'warehouse'. See https://pypi.org/help/#project-name for more information.`
```

**Expected behavior**
Upload should succeed?

**To Reproduce**
try uploading a package with the name `warehouse`

**My Platform**
Ubuntu 20.04, poetry version 1.1.6 for publishing

**Additional context**
I read the [this page](https://pypi.org/help/#project-name) and `warehouse` project name is not in std lib and the PyPi page for that project doesn't exist. So it seems to be blocked by PyPi administrators. I understand that PyPi runs on the project named 'warehouse', but I am not sure how this applies to the blocked package name? Could you provide more insight?

**Comment by di** [comment]
The project name "warehouse" on PyPI is prohibited due to the name for this project, which powers PyPI, is called "warehouse". Sorry about that!

**Comment by dmfigol** [comment]
@di thanks for clarification!
