### ISSUE TITLE
Help me figure out the license please

### ISSUE THREAD

**Issue by 0GRAF0** [pypa/warehouse#9753]
Hello, I am a 16 year old aspiring developer from Russia. I would like to use PyQT to write a program for a desktop to control routers (School project) I know that I can use a library for open source and free code, but can I send this program to competitions and Olympiads? (After all, there I can get an award) Can an educational institution use my program within its walls?

Best wishes, Yaroslav.

P.S. I tried to figure out the license myself, but I didn't succeed. Please forgive me for distracting you from work.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

(I think you may want to reach out to their mailing list here: https://www.riverbankcomputing.com/mailman/listinfo/pyqt)

**Comment by 0GRAF0** [comment]
Thanks for the quick response
