### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by sunilt99** [pypa/warehouse#9763]
There's a mistake in two of the links that you've provided to download python projects and its dependencies.
I've taken a snip of it , hope you check it out .
<img width="815" alt="Capture" src="https://user-images.githubusercontent.com/87071321/124748695-0d10b880-df41-11eb-8e16-a96e93712042.PNG">

**Comment by ewjoachim** [comment]
Hi, this is not a part of PyPI but of the project `pip-download`/

This issue tracker is for issues with the codebase behind [pypi.org](https://pypi.org) itself, not the projects hosted on PyPI.

You should report this issue to the [tracker for the project](https://github.com/youngquan/pip-download/issues) in question instead. (Note that despites its name, the project is not affiliated with PyPA)
