### ISSUE TITLE
No spacing between large logo and home page content

### ISSUE THREAD

**Issue by dstufft** [pypa/warehouse#977]
This may be intended, but it looks a bit odd to me. There isn't any spacing between the large logo and the home page text. This isn't immediately obvious because the real logo is mostly transparent background on it's right hand side, but you can see it with the TM in the top right corner. 

<img width="496" alt="screen-shot-2016-02-19-07-15-37" src="https://cloud.githubusercontent.com/assets/145979/13175679/25b1b63e-d6da-11e5-8f67-a35c8988ffbb.png">

**Comment by nlhkabu** [comment]
No, this isn't right, it should look like this:

![screenshot from 2016-02-20 07-01-22](https://cloud.githubusercontent.com/assets/3323703/13195078/d4d5b794-d79f-11e5-92f3-627263cdc965.png)

What browser and resolution are you seeing this on?

**Comment by dstufft** [comment]
Chrome 48.0.2564.116 on OSX. My monitor resolution is 5120x2880 and my browser is almost maximized.

**Comment by sigmavirus24** [comment]
<img width="1172" alt="screen shot 2016-02-22 at 15 16 25" src="https://cloud.githubusercontent.com/assets/240830/13233007/44043a36-d977-11e5-8407-c629ff178228.png">

Using Firefox 44.0.x on OSX. My browser is nowhere near maximixed with 2880 x 1800 ... in fact to give context:

<img width="1360" alt="screen shot 2016-02-22 at 15 18 03" src="https://cloud.githubusercontent.com/assets/240830/13233038/7fa4b5a2-d977-11e5-894f-ab0b9922efe2.png">

Which GitHub seems to think is ~1360 wide... so hopefully this helps.

**Comment by sigmavirus24** [comment]
For reference, I am seeing that on Chrome Version 48.0.2564.109 (64-bit) on OSX
