### ISSUE TITLE
PyPi.org PYCURL page loops around to itself when the Python.org link is used, and the bintray link doesn't work

### ISSUE THREAD

**Issue by BDProductions** [pypa/warehouse#9799]
I don't see a better place to report broken download links on the Pypi website project pages for pycurl

Please move this if there is a better place for it.

I need pycurl or to be able to pass URLs to cURL from Python 3.8 in windows 7.

The Win7 PC  isn't "online,"  it is used to send REST commands to another app when relay closures are detected by a serial port GPI device.

Due to ZERO other applications that do what the one does with the REST server, we are stuck using Windows 7.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead: https://github.com/pycurl/pycurl/issues
