### ISSUE TITLE
Search field autofocused on package pages

### ISSUE THREAD

**Issue by twm** [pypa/warehouse#983]
On package pages the search field is automatically focused (for example https://warehouse.python.org/project/simplejson/).  This means that once the page loads you must unfocus the search field before you can scroll via the keyboard.

Automatically focusing the search field is arguably reasonable for the front page, where the search field is front and center, but it's a misfeature for pages where search is just part of the site header.  Worse, the field is focused via JavaScript, so it doesn't obey the user's configured autofocus preferences.

**Comment by dstufft** [comment]
I agree we should only autofocus on the main page. I also wonder if we should autofocus using the HTML5 attribute instead of javascript.

**Comment by dstufft** [comment]
I guess a reason not to use the autofocus HTML5 attribute is there is no way to only use it on desktops and not on mobile clients.

**Comment by twm** [comment]
It looks like this is done based on screen width right now: https://github.com/pypa/warehouse/blob/c4cce33720f2af493c13dd17b2fc291a43bc08d9/warehouse/static/js/main.js#L81-L91  That's probably available as the page loads&mdash;it's a bit retro, but you could ``document.write()`` out the ``<input autofocus>`` tag based on that.

(Doing this based on screen width seems weird to me. Windows can be narrow on desktop machines too.  And why width over height?  The input widget will probably consume vertical space, not horizontal.)

**Comment by miohtama** [comment]
It is weird. Please see new comment on the original issue:

https://github.com/pypa/warehouse/issues/854#issuecomment-188606918
