### ISSUE TITLE
options and option_chain in yfinance do not work properly

### ISSUE THREAD

**Issue by auto-expert** [pypa/warehouse#9834]
I work in Google Colab

!pip install yfinance
import yfinance as yf

stock = yf.Ticker('WU')
stock.options

As a result I receive ('2022-01-21', '2023-01-20')
Which is not true. There are more expiration dates.

I tried and option_chain but the result is the same. It gives put and call options only for these dates.
Which is not true. There are more expiration dates.

I tried more than 400 symbols. It gives wrong result for around 15% of them.

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
