### ISSUE TITLE
Serial and Parallel - Different Results

### ISSUE THREAD

**Issue by mill1016** [pypa/warehouse#9843]
Running ga2 in a 'for loop'.

When I run in serial mode, my **_objective function_** from the GA matches my computation outside of the GA.
model_ga.run(no_plot=True, disable_progress_bar=False) --> No problem.

When I am running in parallel mode, my **_objecitve function_** from that GA is NOT matching my computation outside of the GA.
model_ga.run(no_plot=True, disable_progress_bar=False, set_function= ga.set_function_multiprocess(f, n_jobs = 4))  --> Problem

Python 3.6.5
GeneticAlgorithm2:  Says does not have a '__version__' so could not find.  Intalled not too long ago.

Thanks for any help.

Additional Info if required:
#### Parameters
algorithm_param = {'max_num_iteration':200,\
                   'population_size':50,\
                   'mutation_probability':0.1,\
                   'elit_ratio': 0.01,\
                   'crossover_probability': 0.5,\
                   'parents_portion': 0.3,\
                   'crossover_type':'uniform',\
                   'max_iteration_without_improv':75}
### Set-up the model.
model_ga = ga(function=f, dimension=len(col_features_rf), variable_type='bool', 
           algorithm_parameters=algorithm_param)
## Loop.  Run a bunch of 
for i in no_of_items_to_optimize:
      Run GA w/ Random Forest Function to determine optimal parameters.
      --> Computes Objective function optimal and optimal parameters.

Re-Compute random forest and Objective Function using optimal parameters.
--> It's here that the parallel differs from the GA Objective Function | Serial mode gives same results.

**Comment by ewjoachim** [comment]
Hi, this issue tracker is for issues with the codebase behind [pypi.org](https://pypi.org) itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
