### ISSUE TITLE
Relative upload time wrong by 8 hours (UTC vs local time ?)

### ISSUE THREAD

**Issue by Carreau** [pypa/warehouse#987]
- Publish package
 - go to https://warehouse.python.org/project/yourpackage/
 - be in non UTC timezone ?

It says:
```
Uploaded about 8 hours ago by <me> <myavatar>
```

html:

```
<time class="-js-relative-time" datetime="2016-02-26T22:00:26" title="Feb 26, 2016">about 8 hours ago</time>
```

It's locally 14h00 (Pacific Time), so my guess it's a JS side only issue.
Not really important I guess, as you don't upload that often.

But in case something else is wrong with dates....

**Comment by dstufft** [comment]
This might be solvable by adding a ``Z`` to the end of the ``datetime="..."``.

**Comment by Carreau** [comment]
Humm maybe, but in this case why doesn't the text say "in 8 hours" ?
and BTW, it now say "Uploaded about 5 hours ago". So I expect it to think the package will be publish in the future at about 9pm and 26 seconds tonight PST :-P

**Comment by Carreau** [comment]
Thanks!
