### ISSUE TITLE
python 3.9 versiyon AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by bilalcelik** [pypa/warehouse#9891]
Hi i am using python new versiyon 3.9 
and i get some error
AttributeError: module 'time' has no attribute 'clock'

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.

**Comment by bilalcelik** [comment]
sorry thanks for answer
