### ISSUE TITLE
Vulnerability reporting task is not resilient to deleted releases

### ISSUE THREAD

**Issue by di** [pypa/warehouse#9913]
Currently attempting to publish a vulnerability report for a notification that includes release versions that have been deleted (or never existed) causes an error and prevents the entire report from being stored.

Example: https://sentry.io/share/issue/69362937025d4524be01918a80f830d1/

If the release is not found, we should just skip that version and continue storing the vulnerability report. If *none* of the versions are found, we should error.

**Comment by DiddiLeija** [comment]
Hi @di, seems like no one is working on this issue. I'm interested, can you tell me what do I have to do?

**Comment by di** [comment]
Sure. The `analyze_vulnerability` function handles a report of a vulnerability for multiple release versions. Currently it fails if one of the releases are missing:

https://github.com/pypa/warehouse/blob/b0da6add8783535879057d011ee5300330a154f8/warehouse/integrations/vulnerabilities/utils.py#L105-L112

(This might happen due to a typo, or more likely if the release has been removed since the vulnerability has been discovered)

If one or more of the versions in the report don't correspond to a release, we should just skip that version and continue storing the vulnerability report. If none of the versions in the report are found, we should error.

**Comment by DiddiLeija** [comment]
Thanks. I'll work on it later.
