### ISSUE TITLE
Mouser package on PyPI

### ISSUE THREAD

**Issue by eeintech** [pypa/warehouse#9925]
I would like your help deleting the package named "mouser" from PyPI: https://pypi.org/project/mouser/

Reasons to delete:
1. this packaged doesn't do anything other than copying-pasting some of the `django-admin` tools from the Django framework project

Example: the file `core/management/base.py`
``` python
# -*- coding: utf-8 -*-
"""
Base classes for writing management commands (named commands which can
be executed through ``django-admin``).
"""
from __future__ import unicode_literals

import os
import sys
from argparse import ArgumentParser

import mouser
from mouser.core.management.color import color_style, no_style
from mouser.utils.encoding import force_text

class CommandError(Exception):
    """
    Exception class indicating a problem while executing a management
    command.

    If this exception is raised during the execution of a management
    command, it will be caught and turned into a nicely-printed error
    message to the appropriate output stream (i.e., stderr); as a
    result, raising this exception (with a sensible description of the
    error) is the preferred way to indicate that something has gone
    wrong in the execution of a command.
    """
    pass
```

is an older copy of: https://github.com/django/django/blob/main/django/core/management/base.py

2. There were no update since 2016 (stale since the first upload)
3. The original repository has been deleted from Github: https://github.com/bristy/mouser

I have contacted the [main author](https://github.com/bristy/) to delete the project from PyPI, but no answer...

I am maintaining a similarly named package which is based on a existing electronics supplier API: https://github.com/sparkmicro/mouser-api/

And I would like to use the name "mouser" to publish my package to PyPI.

Can you please help with the removal?
Thank you!

EDIT: Sorry for the mislabeled issue if it is the case

**Comment by di** [comment]
Hi, this is the wrong place for this kind of request, please see https://pypi.org/help/#project-name-claim

**Comment by eeintech** [comment]
Nice thanks :+1: 

Reference: https://github.com/pypa/pypi-support/issues/1268
