### ISSUE TITLE
No option to unbatch the search result listing

### ISSUE THREAD

**Issue by zopyx** [pypa/warehouse#993]
Digging manually through ten or more batches of search results is not very usable. Power users want the complete listing search through the list using the browser's search functionality. Don't point people to the improved search capabilities. There is a use case for having the search results unbatched optionally.

**Comment by dstufft** [comment]
I don't believe it's possible to unbatch the search results with Elasticsearch. I think the only option is to increase the batch size.

**Comment by zopyx** [comment]
But for a given query you know the number of search results (#batches as
shown as results times the batch size).
So it should be issue to perform the same search again with the number of
total hits as batch size.

2016-03-01 12:12 GMT+01:00 Donald Stufft <notifications@github.com>:

**Comment by dstufft** [comment]
I'm going to close this, because I don't think we're going to implement it. We have over 100,000 items on PyPI and I don't think it's sane to allow you to get 100,000+ items returned on a single page (much less the computation and such it takes to produce such a result of that size).
