### ISSUE TITLE
alpha installed instead of latest stable release

### ISSUE THREAD

**Issue by 9EOR9** [pypa/warehouse#9946]
**Describe the bug**
pip3 install mariadb installs mariadb-1.1.1-alpha instead of latest stable

**Expected behavior**
Should install mariadb-1.0.7

**To Reproduce**
pip3 install mariadb

**My Platform**
Linux 64-bit, Ubuntu 20.10

**Additional context**
classifiers in setup.py contains "'Development Status :: 3 - Alpha',"

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

This release was not published with a [pre-release version](https://www.python.org/dev/peps/pep-0440/#pre-releases) and thus pip does not consider it a pre-release. Classifiers are not used during dependency resolution to determine pre-release status, so this is working as expected.

You should report this issue to the tracker for the project in question instead, asking them to yank the current releases and publish them with pre-release specifiers instead.
