### ISSUE TITLE
Issue with versions

### ISSUE THREAD

**Issue by larean** [pypa/warehouse#9965]
Hello.

I uploaded yesterday a new build of my project, obsinfo. The build is 0.110.8. It uploaded OK with twine upload. But now, when I look for obsinfo (just the package name) in the homepage of PyPI, I get the weirdest behavior. It DOES find build 0.110.8, but when you click on it, it sends you to the previous build, 0.110.7, with no trace of the newer build either in the page or in release history.  Still, the build is there! I can find it by using this URL:

https://pypi.org/project/obsinfo/0.110.8/

I am tempted to upload another build but would like to know before if you have experienced similar problems.

**Comment by di** [comment]
The page at https://pypi.org/project/obsinfo/ shows 0.110.8 for me, is that what you mean? It's possible you were experiencing a stale cache.

**Comment by larean** [comment]
Thank you. I checked it in my mobile phone and it works!
