### ISSUE TITLE
streamlit_analytics not allowing st.expand or st.columns 

### ISSUE THREAD

**Issue by SteveRNewman** [pypa/warehouse#9987]
Thank you for creating the awesome tool of streamlit analytics. I do get an error when viewing my analytics page on the latest version of streamlit (I think 84 or 85). It shows the features that recently came out of beta an an error. Is this a known issue?

Thanks

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
