### ISSUE TITLE
Send confirmation email when password changed

### ISSUE THREAD

**Issue by edmorley** [pypa/warehouse#999]
Currently on PyPI, if a user changes their password, there is no email notification, meaning account compromise can go unnoticed.

Changing of password doesn't seem to be implemented on https://warehouse.python.org/ yet, but filing this now to ensure it's not forgotten :-)

**Comment by edmorley** [comment]
(And for that matter, I really hope the new implementation will confirm the existing password, rather than just allow changing it via the session cookie.)

**Comment by brainwane** [comment]
@edmorley Thanks for creating this issue, and sorry for the slow response!

The folks working on Warehouse have gotten [funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- the most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable.

We're working on #2831 right now, which should also address this issue.

Thanks and sorry again for the wait.

**Comment by waseem18** [comment]
@di This looks like an issue I can work on (no assignee :smile: )

**Comment by di** [comment]
Ah sorry again @waseem18, this issue is going to get closed along with #2831 in the same PR.

**Comment by waseem18** [comment]
My bad! Can you please link me to an issue I can work on?

Thanks

**Comment by di** [comment]
@waseem18 https://github.com/pypa/warehouse/issues/1886 might be a good one for you. Feel free to ask any questions on that issue.

**Comment by waseem18** [comment]
Thanks for the suggestion @di :)

I'll hop on to it.
